ALTER TABLE AA_SERIE_CADENA_DET_SINCRO
         ADD CONSTRAINT AA_SERIE_CADENA_DET_SINCRO_FK
         	FOREIGN KEY  (SERIE_CADENA)
        		 REFERENCES AA_SERIE_CADENA_SINCRO
go        		 
        		 