ALTER TABLE AUDITORIA_AD
  ADD CONSTRAINT AUDITADSUPERAD FOREIGN KEY (SUPERVISOR)
    REFERENCES SUPERVISOR_AD(SUPERVISOR)
go


ALTER TABLE PED_LINEA_SERIE_AD  WITH CHECK 
 ADD  CONSTRAINT PEDLINSERPEDLINAD 
  FOREIGN KEY(LINEA, PEDIDO)
   REFERENCES PEDIDO_LINEA_AD (LINEA, PEDIDO)
    ON DELETE CASCADE
	
go


ALTER TABLE PEDIDO_LINEA_AD  WITH CHECK 
 ADD  CONSTRAINT PEDLINPEDIDOAD
  FOREIGN KEY(PEDIDO)
   REFERENCES PEDIDO_AD (PEDIDO)
    ON DELETE CASCADE
go