
 
 CREATE TABLE ACTIVO_ACCION (
        ACTIVO_ACCION        	int NOT NULL,
        UBICACION            	VARCHAR(8) NULL,
        RESPONSABLE          	VARCHAR(20) NULL,
        TIPO_ACCION_AF       	VARCHAR(4) NOT NULL,
        ESTADO_ACTIVO        	VARCHAR(4) NULL,
        ACTIVO_FIJO          	VARCHAR(10) NOT NULL,
        ESTADO_ACCION        	VARCHAR(1) NOT NULL,
        FECHA                	DATETIME NOT NULL,
        FECHA_RIGE           	DATETIME NOT NULL,
        FECHA_VENCE          	DATETIME NULL,
        NOTAS                	TEXT NULL,
        USUARIO_CREACION     	VARCHAR(25) NOT NULL,
        FECHA_CREACION       	DATETIME NOT NULL,
        FECHA_APROBACION     	DATETIME NULL,
        USUARIO_APLICACION   	VARCHAR(25) NULL,
        FECHA_APLICACION     	DATETIME NULL,
        USUARIO_APROBACION   	VARCHAR(25) NULL,
        ESTADO_ACTIVO_ANT    	VARCHAR(4) NULL,
        RUBRO1_ACTIVO		VARCHAR(40) NULL,
	RUBRO2_ACTIVO		VARCHAR(40) NULL,
	RUBRO3_ACTIVO		VARCHAR(40) NULL,
	RUBRO4_ACTIVO		VARCHAR(40) NULL,
	RUBRO5_ACTIVO		VARCHAR(40) NULL,
	RUBRO6_ACTIVO		VARCHAR(40) NULL,
	RUBRO7_ACTIVO		VARCHAR(40) NULL,
	RUBRO8_ACTIVO		VARCHAR(40) NULL,
	RUBRO9_ACTIVO		VARCHAR(40) NULL,
	RUBRO10_ACTIVO		VARCHAR(40) NULL,
	RUBRO11_ACTIVO		VARCHAR(40) NULL,
	RUBRO12_ACTIVO		VARCHAR(40) NULL,
	RUBRO13_ACTIVO		VARCHAR(40) NULL,
	RUBRO14_ACTIVO		VARCHAR(40) NULL,
	RUBRO15_ACTIVO		VARCHAR(40) NULL        
 )
go
 
 
 ALTER TABLE ACTIVO_ACCION
        ADD CONSTRAINT XPKACTIVO_ACCION PRIMARY KEY (ACTIVO_ACCION)
go
 
 
 CREATE TABLE ACTIVO_CENTRO (
        ACTIVO_FIJO          VARCHAR(10)   NOT NULL,
        CENTRO_COSTO         VARCHAR(25)   NOT NULL,
        PORCENTAJE           DECIMAL(28,8) NOT NULL,
        FASE                 VARCHAR(25)   NULL, 
        ACTIVO_CENTRO 	     int IDENTITY(1,1) NOT NULL
 )
go
 
 
 ALTER TABLE ACTIVO_CENTRO
        ADD CONSTRAINT PK_ACTIVO_CENTRO PRIMARY KEY
        	(ACTIVO_CENTRO,ACTIVO_FIJO,CENTRO_COSTO)
go
 
 
CREATE TABLE ACTIVO_DESMANTELAMIENTO
(
       	DESMANTELAMIENTO		VARCHAR(10)   NOT NULL,
       	DESCRIPCION              	VARCHAR(60)   NULL,
       	ACTIVO_FIJO              	VARCHAR(10) NOT NULL,
       	MEJORA                   	VARCHAR(10)   NOT NULL,
       	FECHA_ADQUISICION		DATETIME          NULL,
       	FECHA_ACTIVACION		DATETIME          NULL,
       	PROVEEDOR                	VARCHAR(20) NULL,
       	ORDEN_COMPRA			VARCHAR(10)   NULL,
       	DOCUMENTO_CP			VARCHAR(50)   NULL,
       	NUMERO_SERIE			VARCHAR(20)   NULL,
       	CODIGO_BARRAS			VARCHAR(20) NULL,
       	COSTO_ORIG_FIS_LOCAL   		DECIMAL(28,8) NOT NULL default 0,
       	COSTO_ORIG_FIS_DOLAR   		DECIMAL(28,8) NOT NULL default 0,
       	COSTO_ORIG_COM_LOCAL		DECIMAL(28,8) NOT NULL default 0,
       	COSTO_ORIG_COM_DOLAR		DECIMAL(28,8) NOT NULL default 0,
       	VALOR_RESC_LOCAL_F   		DECIMAL(28,8) NOT NULL default 0,
       	VALOR_RESC_DOLAR_F   		DECIMAL(28,8) NOT NULL default 0,
       	VALOR_RESC_LOCAL_C		DECIMAL(28,8) NOT NULL default 0,
       	VALOR_RESC_DOLAR_C		DECIMAL(28,8) NOT NULL default 0,
       	MAX_VALORLIB_LOC_F   		DECIMAL(28,8) NULL default 0,
       	MAX_VALORLIB_DOL_F   		DECIMAL(28,8) NULL default 0,
       	MAX_VALORLIB_LOC_C		DECIMAL(28,8) NULL,
       	MAX_VALORLIB_DOL_C		DECIMAL(28,8) NULL,
       	TIPO_DEPR_FIS     		VARCHAR(1) NOT NULL,
       	TIPO_DEPR_COMP			VARCHAR(1) NOT NULL,
       	TASA_REDUCC_SALDO		DECIMAL(28,8) NULL,
       	TASA_REDUCC_SALDO_F    		DECIMAL(28,8) NULL,
       	PLAZO_VIDA_UTIL_F      		SMALLINT          NOT NULL default 0,
       	PLAZO_VIDA_UTIL			SMALLINT          NOT NULL default 0,
       	TIPO_REVAL_F       		VARCHAR(1) NOT NULL,
       	TIPO_REVAL_C			VARCHAR(1) NOT NULL ,
       	PORC_REVAL_F       		DECIMAL(28,8) NULL,
       	PORC_REVAL			DECIMAL(28,8) NULL,
       	TIPO_INDICE_PRECIO_F   		VARCHAR(4)    NULL,
       	TIPO_INDICE_PRECIO		VARCHAR(4)    NULL,
       	ORIGEN				VARCHAR(1) NOT NULL,
       	FECHA_ULT_DEPRE_F      		DATETIME          NULL,
       	FECHA_ULT_DEPRE			DATETIME          NULL,
       	FECHA_ULT_REVAL_F      		DATETIME          NULL,
       	FECHA_ULT_REVAL			DATETIME          NULL,
       	ACUM_DETERIORO_LOC_F   		DECIMAL(28,8) NULL,
       	ACUM_DETERIORO_DOL_F   		DECIMAL(28,8) NULL,
	ACUM_DETERIORO_LOC_C		DECIMAL(28,8) NULL,
	ACUM_DETERIORO_DOL_C		DECIMAL(28,8) NULL,
       	ACUM_REVAL_LOC_F     		DECIMAL(28,8) NULL,
       	ACUM_REVAL_DOL_F     		DECIMAL(28,8) NULL,
	ACUM_REVAL_LOC_C		DECIMAL(28,8) NULL,
	ACUM_REVAL_DOL_C		DECIMAL(28,8) NULL,
	DEP_ACUM_REVAL_LOC_C		DECIMAL(28,8) NULL,
	DEP_ACUM_REVAL_DOL_C		DECIMAL(28,8) NULL,
       	DEP_ACUM_REVAL_LOC_F   		DECIMAL(28,8) NULL,
       	DEP_ACUM_REVAL_DOL_F   		DECIMAL(28,8) NULL,
	DEP_ACUM_DESMANTELA_LOC_C  	DECIMAL(28,8) NULL,
	DEP_ACUM_DESMANTELA_DOL_C 	DECIMAL(28,8) NULL,
	DEP_ACUM_DESMANTELA_LOC_F 	DECIMAL(28,8) NULL,
	DEP_ACUM_DESMANTELA_DOL_F 	DECIMAL(28,8) NULL,
       	NOTAS				TEXT              NULL,
       	USUARIO_ULT_MOD			VARCHAR(25) NOT NULL,
       	FECHA_ULT_MOD			DATETIME          NOT NULL,
       	USUARIO_RETIRO			VARCHAR(25) NULL,
       	FECHA_RETIRO			DATETIME          NULL,
       	ASIENTO_INGRESO_F      		VARCHAR(10)   NULL,
       	ASIENTO_INGRESO			VARCHAR(10)   NULL,
       	ASIENTO_RETIRO_F     		VARCHAR(10)   NULL,
       	ASIENTO_RETIRO_C		VARCHAR(10)   NULL
)

go

ALTER TABLE $$COMPANIA$$.ACTIVO_DESMANTELAMIENTO
        ADD CONSTRAINT XPKDESMANTELA PRIMARY KEY NONCLUSTERED ( DESMANTELAMIENTO, ACTIVO_FIJO, MEJORA)
go

 
 
 CREATE TABLE ACTIVO_FIJO (
        ACTIVO_FIJO          	VARCHAR(10) 	NOT NULL,
        ESTADO_ACTIVO        	VARCHAR(4) 	NULL,
        UBICACION            	VARCHAR(8) 	NULL,
        TIPO_ACTIVO          	VARCHAR(4) 	NOT NULL,
        DESCRIPCION          	VARCHAR(60) 	NOT NULL,
        FECHA_ULT_MANT       	DATETIME 	NULL,
        FECHA_PROX_MANT      	DATETIME 	NULL,
        TASA_DEPRECIACION_F 	DECIMAL(28,8) 	NULL,
	TASA_DEPRECIACION_C 	DECIMAL(28,8)	NULL,
	CLASIFICACION 		VARCHAR(1) 	NULL,
	USA_COMPONENTE 		VARCHAR(1) 	NOT NULL DEFAULT 'N'
 )
go
 
 
 ALTER TABLE ACTIVO_FIJO
        ADD CONSTRAINT ACTIVOFIJOPK PRIMARY KEY NONCLUSTERED (
               ACTIVO_FIJO)
go
 
 
 CREATE TABLE ACTIVO_HIST_MANT (
        FECHA                DATETIME 		NOT NULL,
        ACTIVO_FIJO          VARCHAR(10) 	NOT NULL,
        TIPO_MANTENIMIENTO   VARCHAR(1)	 	NOT NULL,
        DESCRIPCION          VARCHAR(40) 	NOT NULL,
        MONTO                DECIMAL(28,8) 	NOT NULL
 )
go
 
 
 ALTER TABLE ACTIVO_HIST_MANT
        ADD CONSTRAINT ACTIVOHISTMANTPK PRIMARY KEY NONCLUSTERED (
               FECHA, ACTIVO_FIJO)
go
 
 
 CREATE TABLE ACTIVO_HIST_REVAL (
        HIST_REVALUACION     	int 		NOT NULL,
        ACTIVO_FIJO          	VARCHAR(10) 	NOT NULL,
        MEJORA               	VARCHAR(10) 	NOT NULL,
        FECHA                	DATETIME 	NOT NULL,
        METODO               	VARCHAR(1) 	NOT NULL,
        REVAL_VALOR          	DECIMAL(28,8) 	NOT NULL,
        REVAL_VALOR_C        	DECIMAL(28,8) 	NOT NULL,
        REVAL_DEPR_ACUM_F    	DECIMAL(28,8) 	NOT NULL,
        REVAL_DEPR_ACUM_C    	DECIMAL(28,8) 	NOT NULL,
        TIPO_CAMBIO          	DECIMAL(28,8) 	NOT NULL,
        USUARIO              	VARCHAR(25) 	NOT NULL,
        FECHA_HORA           	DATETIME 	NOT NULL,
        ASIENTO_FISCAL       	VARCHAR(10) 	NULL,
        ASIENTO_COMP         	VARCHAR(10) 	NULL,
        COMENTARIO	     	VARCHAR(254) 	NULL,
        METODO_C	     	VARCHAR(1)	NOT NULL,
        CONSEC_DEPR_F 	     	int		NULL,
        CONSEC_DEPR_C	     	int		NULL,
        AJUSTE_INFLA_F		VARCHAR(1)      NOT NULL  DEFAULT 'N',
	AJUSTE_INFLA_C		VARCHAR(1)      NOT NULL  DEFAULT 'N',
	AJU_INFLAC_DEPREC_F	DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	AJU_INFLAC_DEPREC_C	DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	DESMANTELAMIENTO 	VARCHAR(10) 	NULL
 )
go
 
 
 ALTER TABLE ACTIVO_HIST_REVAL
        ADD CONSTRAINT ACTIVOHISTREVALPK PRIMARY KEY NONCLUSTERED (
               HIST_REVALUACION)
go
 
 
 CREATE TABLE ACTIVO_MEJORA (
        ACTIVO_FIJO          	VARCHAR(10) 	NOT NULL,
        MEJORA               	VARCHAR(10) 	NOT NULL,
        RESPONSABLE          	VARCHAR(20) 	NULL,
        DESCRIPCION          	VARCHAR(60) 	NOT NULL,
        PLAZO_VIDA_UTIL      	INT 			NOT NULL,
        PLAZO_VIDA_COMP      	INT 			NOT NULL,
        FECHA_ULT_REVAL_F    	DATETIME 	NULL,
        FECHA_ULT_REVAL_C    	DATETIME 	NULL,
        FECHA_ULT_DEPR_F     	DATETIME 	NULL,
        FECHA_ULT_DEPR_C     	DATETIME 	NULL,
        TIPO_DEPR_FISCAL     	VARCHAR(1) 	NOT NULL,
        TIPO_DEPR_COMP       	VARCHAR(1) 	NOT NULL,
        TIPO_REVAL           	VARCHAR(1) 	NOT NULL,
        TIPO_INDICE_PRECIO   	VARCHAR(4) 	NULL,
        PORC_REVAL           	DECIMAL(28,8) 	NOT NULL,
        COSTO_ORIG_LOCAL     	DECIMAL(28,8) 	NOT NULL,
        COSTO_ORIG_DOLAR     	DECIMAL(28,8) 	NOT NULL,
        VALOR_RESC_LOCAL_F   	DECIMAL(28,8) 	NOT NULL,
        VALOR_RESC_DOLAR_F   	DECIMAL(28,8) 	NOT NULL,
        VALOR_RESC_LOCAL_C   	DECIMAL(28,8) 	NOT NULL,
        VALOR_RESC_DOLAR_C   	DECIMAL(28,8) 	NOT NULL,
        MAX_VALORLIB_LOC_F   	DECIMAL(28,8) 	NULL,
        MAX_VALORLIB_DOL_F   	DECIMAL(28,8) 	NULL,
        MAX_VALORLIB_LOC_C   	DECIMAL(28,8) 	NULL,
        MAX_VALORLIB_DOL_C   	DECIMAL(28,8) 	NULL,
        DEP_ACU_HIST_LOC_F   	DECIMAL(28,8) 	NOT NULL,
        DEP_ACU_HIST_DOL_F   	DECIMAL(28,8) 	NOT NULL,
        DEP_ACU_HIST_LOC_C   	DECIMAL(28,8) 	NOT NULL,
        DEP_ACU_HIST_DOL_C   	DECIMAL(28,8) 	NOT NULL,
        DEP_ACU_REVA_LOC_F   	DECIMAL(28,8) 	NOT NULL,
        DEP_ACU_REVA_DOL_F   	DECIMAL(28,8) 	NOT NULL,
        DEP_ACU_REVA_LOC_C   	DECIMAL(28,8) 	NOT NULL,
        DEP_ACU_REVA_DOL_C   	DECIMAL(28,8) 	NOT NULL,
        ACUM_REVAL_LOC_F     	DECIMAL(28,8) 	NOT NULL,
        ACUM_REVAL_DOL_F     	DECIMAL(28,8) 	NOT NULL,
        ACUM_REVAL_LOC_C     	DECIMAL(28,8) 	NOT NULL,
        ACUM_REVAL_DOL_C     	DECIMAL(28,8) 	NOT NULL,
        FECHA_ADQUISICION    	DATETIME 	NOT NULL,
        FECHA_ACTIVACION     	DATETIME 	NOT NULL,
        FECHA_RETIRO         	DATETIME 	NULL,
        USUARIO_RETIRO       	VARCHAR(25) 	NULL,
        FECHA_ULT_MOD        	DATETIME 	NOT NULL,
        USUARIO_ULT_MOD      	VARCHAR(25) 	NOT NULL,
        ORDEN_COMPRA         	VARCHAR(10) 	NULL,
        PROVEEDOR            	VARCHAR(20) 	NULL,
        CODIGO_BARRAS        	VARCHAR(20) 	NULL,
        NUMERO_SERIE         	VARCHAR(20) 	NULL,
        ASIENTO_INGRESO      	VARCHAR(10) 	NULL,
        ASIENTO_RETIRO_F     	VARCHAR(10) 	NULL,
        ASIENTO_RETIRO_C     	VARCHAR(10) 	NULL,
        NOTAS                	TEXT 		NULL,	
        RUBRO1_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO2_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO3_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO4_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO5_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO6_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO7_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO8_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO9_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO10_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO11_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO12_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO13_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO14_ACTIVO	     	VARCHAR(40) 	NULL,
	RUBRO15_ACTIVO	     	VARCHAR(40) 	NULL,
	DOCUMENTO_CP	     	VARCHAR(50) 	NULL,
	TIPO_REVAL_C	     	VARCHAR(1)	NOT NULL,
	PORC_REVAL_C	     	DECIMAL(28,8) 	NULL,
	TIPO_INDICE_PRECIO_C 	VARCHAR(4)	NULL,
	FECHA_AUD_RET_FISC   	DATETIME	NULL,
	COSTO_ORIG_COM_DOLAR 	DECIMAL(28,8) 	NOT NULL DEFAULT 0, 
	COSTO_ORIG_COM_LOCAL 	DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	TASA_REDUCC_SALDOSF  	DECIMAL(28,8) 	NULL,
	TASA_REDUCC_SALDOSC  	DECIMAL(28,8) 	NULL,
	ASIENTO_INGRESO_C    	VARCHAR(10)   	NULL,
	ORIGEN	             	VARCHAR(1) 	NOT NULL  DEFAULT 'M',
	AJUSTE_INFLA_F       	VARCHAR(1) 	NOT NULL  DEFAULT 'N',
	AJUSTE_INFLA_C	     	VARCHAR(1) 	NOT NULL  DEFAULT 'N',
	COMPONENTE	     	VARCHAR(10)     NULL,
	DEP_ACU_AI_LOC_F	DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	DEP_ACU_AI_LOC_C	DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	DEP_ACU_AI_DOL_F	DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	DEP_ACU_AI_DOL_C	DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	ACTIVO_ORIGEN		VARCHAR(10) 	NULL,
	MEJORA_ORIGEN		VARCHAR(10) 	NULL,
	ACUM_DETERIORO_LOC_C 	DECIMAL(28,8) 	NULL,
	ACUM_DETERIORO_DOL_C 	DECIMAL(28,8) 	NULL,
	ACUM_DETERIORO_LOC_F 	DECIMAL(28,8) 	NULL,
	ACUM_DETERIORO_DOL_F 	DECIMAL(28,8) 	NULL,
	FECHA_ULT_DETERIORO 	DATETIME 	NULL,
	FECHA_ULT_DETERIORO_F 	DATETIME 	NULL,
	ACUM_DESMANTELA_LOC_C 	DECIMAL(28,8) 	NULL,
	ACUM_DESMANTELA_DOL_C 	DECIMAL(28,8) 	NULL,
	ACUM_DESMANTELA_LOC_F 	DECIMAL(28,8) 	NULL,
	ACUM_DESMANTELA_DOL_F 	DECIMAL(28,8) 	NULL,
	DEP_ACUM_DESMANTELA_LOC_C  	DECIMAL(28,8) 	NULL,
	DEP_ACUM_DESMANTELA_DOL_C 	DECIMAL(28,8) 	NULL,
	DEP_ACUM_DESMANTELA_LOC_F 	DECIMAL(28,8) 	NULL,
	DEP_ACUM_DESMANTELA_DOL_F 	DECIMAL(28,8) 	NULL,
	DESGLOSE_IMP 		VARCHAR(1) 	NULL 	
 )
go
 
 
 ALTER TABLE ACTIVO_MEJORA
        ADD CONSTRAINT ACTIVO_MEJORAPK PRIMARY KEY NONCLUSTERED (
               ACTIVO_FIJO, MEJORA)
go
 
 
 CREATE TABLE CUENTA_DEPRECIACIO (
        TIPO_ACTIVO          	VARCHAR(4)  NOT NULL,
        CENTRO_COSTO         	VARCHAR(25) NOT NULL,
        CTA_DEPR_NORMAL      	VARCHAR(25) NOT NULL,
        CTA_DEPR_REVAL       	VARCHAR(25) NOT NULL,
        PROYECTO 	     	VARCHAR(25) NULL,
        FASE                 	VARCHAR(25) NULL,
        CTA_DEPR_NORMAL_C    	VARCHAR(25) NULL,
	CTA_DEPR_REVAL_C     	VARCHAR(25) NULL,
	CTA_DEPR_AI_F	     	VARCHAR(25) NULL,
	CTA_DEPR_AI_C	     	VARCHAR(25) NULL,
	CTA_DEPR_DESMANTELA_F 	VARCHAR(25) NULL,
	CTA_DEPR_DESMANTELA_C 	VARCHAR(25) NULL
 )
go
 
 
 ALTER TABLE CUENTA_DEPRECIACIO
        ADD CONSTRAINT XPKCUENTA_DEPRECIA PRIMARY KEY (TIPO_ACTIVO, 
               CENTRO_COSTO)
go
 
 
 CREATE TABLE DEPR_CENTRO_COSTO (
        HIST_DEPRECIACION    int           NOT NULL,
        CENTRO_COSTO         VARCHAR(25)   NOT NULL,
        DEPR_LOCAL           DECIMAL(28,8) NOT NULL,
        DEPR_DOLAR           DECIMAL(28,8) NOT NULL,
        FASE                 VARCHAR(25)   NULL,
        CENTRO_DEPRE int IDENTITY(1,1) NOT NULL
 )
go
 
 
 ALTER TABLE DEPR_CENTRO_COSTO
        ADD CONSTRAINT PK_DEPR_CENTRO_COSTO PRIMARY KEY
        		(CENTRO_DEPRE,HIST_DEPRECIACION,CENTRO_COSTO)
go
 
 
 CREATE TABLE DEPR_PORCENTAJE (
        ACTIVO_FIJO          VARCHAR(10)   NOT NULL,
        MEJORA               VARCHAR(10)   NOT NULL,
        PERIODO              smallint      NOT NULL,
        CONTABILIDAD         VARCHAR(1)    NOT NULL,
        PORCENTAJE           DECIMAL(28,8) NOT NULL
 )
go
 
 
 ALTER TABLE DEPR_PORCENTAJE
        ADD CONSTRAINT XPKDEPR_PORCENTAJE PRIMARY KEY (ACTIVO_FIJO, 
               MEJORA, PERIODO, CONTABILIDAD)
go
 
 
CREATE TABLE DET_SOLICITUD_AF_NOTIF (
	 SOLICITUD		INT		NOT NULL,
         ACTIVO_FIJO		VARCHAR(10)     NOT NULL
)
go


ALTER TABLE DET_SOLICITUD_AF_NOTIF ADD CONSTRAINT DETSOLAFNOTPK PRIMARY KEY (SOLICITUD,ACTIVO_FIJO)
go

  
 
 CREATE TABLE ESTADO_ACTIVO (
        ESTADO_ACTIVO        VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        ACTIVO               VARCHAR(1) NULL
 )
go
 
 
 ALTER TABLE ESTADO_ACTIVO
        ADD CONSTRAINT XPKESTADO_ACTIVO PRIMARY KEY (ESTADO_ACTIVO)
go
 
 
 CREATE TABLE GLOBALES_AF (
        CTA_CORRECC_DA       	VARCHAR(25) 	NULL,
        FECHA_ULT_COMP       	DATETIME 	NULL,
        CTA_ORDEN_VENTA      	VARCHAR(25) 	NULL,
        CTR_SUPERAVIT        	VARCHAR(25) 	NULL,
        CTA_SUPERAVIT        	VARCHAR(25) 	NULL,
        CTR_REI              	VARCHAR(25) 	NULL,
        CTA_REI              	VARCHAR(25) 	NULL,
        PAQUETE              	VARCHAR(4) 	NULL,
        TIPO_ASIENTO         	VARCHAR(4) 	NULL,
        ASNT_INCLUSION       	VARCHAR(1) 	NULL,
        AJUSTAR_CALC_DEPR    	VARCHAR(1) 	NOT NULL,
        CTR_UTILIDAD_VENTA   	VARCHAR(25)     NULL,
        CTA_UTILIDAD_VENTA   	VARCHAR(25) 	NULL,
        CTR_PERDIDA_VENTA    	VARCHAR(25) 	NULL,
        CTA_PERDIDA_VENTA    	VARCHAR(25) 	NULL,
        CTR_ORDEN_INGRESO    	VARCHAR(25) 	NULL,
        CTA_ORDEN_INGRESO    	VARCHAR(25) 	NULL,
        CTR_ORDEN_VENTA      	VARCHAR(25) 	NULL,
        ASNT_EXCLUSION       	VARCHAR(1) 	NULL,
        MEJ_DEPR_ACTIVO      	VARCHAR(1) 	NULL,
        MEJ_REVAL_ACTIVO     	VARCHAR(1) 	NULL,
        MEJ_VIDA_ACTIVO      	VARCHAR(1) 	NULL,
        TIPO_FASB52          	VARCHAR(1) 	NULL,
        MESES_REVAL          	smallint 	NULL,
        TIPO_CONSECUTIVO     	VARCHAR(1) 	NULL,
        CONSECUTIVO          	VARCHAR(10) 	NULL,
        INTEGRACION_CONTA    	VARCHAR(1) 	NOT NULL,
        MOD_APLIC_ASIENTO    	smallint 	NOT NULL,
        TIPO_CONTA_OMISION   	VARCHAR(1) 	NOT NULL,
        CORPORATIVA_ACTIVA   	VARCHAR(1) 	NULL,
        PERMITIR_REVAL_NEG   	VARCHAR(1) 	NULL,
        CONTABILIDAD_REVAL   	VARCHAR(1) 	NULL,
        ULT_DEPRECIACION     	int 		NOT NULL,
        ULT_REVALUACION      	int 		NOT NULL,
        ACCIONES_ING         	VARCHAR(4) 	NULL,
        ACCIONES_RET         	VARCHAR(4) 	NULL,
        CTR_CORRECC_DA       	VARCHAR(25)	NULL,
        AJUSTE_INFLAC        	VARCHAR(1) 	NOT NULL,
        ACCIONES_CENTRO		VARCHAR(4)  	NULL,
		NOM_RUBRO1_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO2_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO3_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO4_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO5_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO6_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO7_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO8_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO9_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO10_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO11_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO12_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO13_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO14_ACT		VARCHAR(60) 	NULL,
		NOM_RUBRO15_ACT		VARCHAR(60) 	NULL,
		CANT_DECIMALES		SMALLINT    	NOT NULL,
		TRUNCAR_VALOR		VARCHAR(1)  	NOT NULL,
		COND_ACTIVOS 		VARCHAR(1)  	NOT NULL,
		OPCION_DEPR 		VARCHAR(1)  	NOT NULL,
		USA_COMPONENTES 	VARCHAR(1) 	NOT NULL  DEFAULT 'N',
		CTR_AJU_INFLAC		VARCHAR(25) 	NULL,
		CTA_AJU_INFLAC		VARCHAR(25) 	NULL,
		DESMAN_DEPR_ACTIVO 	VARCHAR(1) 	NOT NULL DEFAULT 'N',
		CTR_DETERIORO 		VARCHAR(25) 	NULL,
		CTA_DETERIORO 		VARCHAR(25) 	NULL,
		ULT_DETERIORO 		INT 		NOT NULL DEFAULT 0,
		DESMAN_VIDA_ACTIVO 	VARCHAR(1) 	NOT NULL DEFAULT 'N',
		CONTA_IMPUESTO 	VARCHAR(1) 	NOT NULL DEFAULT 'F'
)
go
 
 
 CREATE TABLE HIST_DEPRECIACION (
        HIST_DEPRECIACION    	int 		NOT NULL,
        ACTIVO_FIJO          	VARCHAR(10) 	NOT NULL,
        MEJORA               	VARCHAR(10) 	NOT NULL,
        FECHA                	DATETIME 	NOT NULL,
        CONTABILIDAD         	VARCHAR(1) 	NOT NULL,
        REFERENCIA           	VARCHAR(1) 	NOT NULL,
        AJUSTE               	VARCHAR(1) 	NOT NULL,
        METODO               	VARCHAR(1) 	NOT NULL,
        DEPR_LOCAL           	DECIMAL(28,8) 	NOT NULL,
        DEPR_DOLAR           	DECIMAL(28,8) 	NOT NULL,
        ASIENTO              	VARCHAR(10) 	NULL,
        USUARIO              	VARCHAR(25) 	NOT NULL,
        FECHA_HORA           	DATETIME 	NOT NULL,
        DESMANTELAMIENTO 	VARCHAR(10) 	NULL
 )
go
 
 
 ALTER TABLE HIST_DEPRECIACION
        ADD CONSTRAINT XPKHIST_DEPRECIACI PRIMARY KEY NONCLUSTERED (
               HIST_DEPRECIACION)
go


CREATE TABLE HIST_DETERIORO
	(
	 HIST_DETERIORO INT NOT NULL,
	 ACTIVO_FIJO VARCHAR(10) NOT NULL,
	 MEJORA VARCHAR(10) NOT NULL,
	 DESMANTELAMIENTO VARCHAR(10) NULL,
	 FECHA DATETIME NOT NULL,
	 VALOR_LOCAL DECIMAL(28,8) NOT NULL default 0,
	 VALOR_DOLAR DECIMAL(28,8) NOT NULL default 0,
	 VALOR_LOCAL_F DECIMAL(28,8) NOT NULL default 0,
	 VALOR_DOLAR_F DECIMAL(28,8) NOT NULL default 0,
	 TIPO_CAMBIO DECIMAL(28,8) NOT NULL default 1,
	 ASIENTO VARCHAR(10) NULL,
	 ASIENTO_F VARCHAR(10) NULL,
	 USUARIO VARCHAR(25) NOT NULL,
	 FECHA_HORA DATETIME NOT NULL
	)

go


ALTER TABLE $$COMPANIA$$.HIST_DETERIORO
	ADD CONSTRAINT XPKDETERIORO PRIMARY KEY (HIST_DETERIORO)
go


CREATE TABLE $$COMPANIA$$.IMPUESTO_ACTIVO  (
	ACTIVO 		VARCHAR(10) 	NOT NULL,
	MEJORA 		VARCHAR(10) 	NOT NULL,
	CONSECUTIVO 	INT 		NOT NULL,
	IMPUESTO 	VARCHAR(4) 	NOT NULL,
	CONCEPTO_ME 	VARCHAR(4) 	NOT NULL,
	VALOR 		DECIMAL(28,8) 	NOT NULL,
	PORCENTAJE 	DECIMAL(28,8) 	NOT NULL,
	IMPUESTO_AC 	VARCHAR(1) 	NOT NULL,
	TIPO_IMPUESTO 	VARCHAR(4) 	NOT NULL,
	IMPUESTO_ASUMIDO VARCHAR(1) 	NOT NULL
)
go

ALTER TABLE $$COMPANIA$$.IMPUESTO_ACTIVO  ADD CONSTRAINT PK_ACTMEJ_IMP 
		PRIMARY KEY(ACTIVO,MEJORA,CONSECUTIVO)
go
 
 CREATE TABLE INDICE_PRECIOS (
        TIPO_INDICE_PRECIO   VARCHAR(4) NOT NULL,
        FECHA                DATETIME NOT NULL,
        MONTO                DECIMAL(28,8) NOT NULL
 )
go
 
 
 ALTER TABLE INDICE_PRECIOS
        ADD CONSTRAINT INDICEPRECIOSPK PRIMARY KEY NONCLUSTERED (
               TIPO_INDICE_PRECIO, FECHA)
go
 
 

CREATE TABLE SOLICITUD_AF_AUDIT (
         SOLICITUD	 	INT          	NOT NULL,
         USUARIO         	VARCHAR(25)  	NOT NULL,
         NIVEL           	SMALLINT     	NOT NULL,
         ESTADO          	VARCHAR(1)   	NOT NULL,
         FECHA_ESTADO    	DATETIME     	NOT NULL,
         OBSERVACIONES   	TEXT         	NULL,
	 ESTADO_NOT	 	VARCHAR(1)   	NULL
)
go



ALTER TABLE SOLICITUD_AF_AUDIT ADD CONSTRAINT SOLAFAUDITPK PRIMARY KEY NONCLUSTERED (SOLICITUD, USUARIO)
go
       


CREATE TABLE SOLICITUD_AF_NOTIF (
	SOLICITUD  		INT         	NOT NULL,
	RESPONSABLE_CREADOR    	VARCHAR(20)	NOT NULL,
	RESPONSABLE_TRASLADO	VARCHAR(20)	NOT NULL,
	RESPONSABLE_CREADOPOR	VARCHAR(20)	NOT NULL,
	ESTADO_SOLICITUD       	VARCHAR(1)  	NOT NULL,
	TIPO_ACCION		VARCHAR(4)	NOT NULL,
       	FECHA			DATETIME    	NULL, 
	FECHA_RIGE		DATETIME	NOT NULL,
	NOTAS			TEXT		NULL,		
	CAMBIA_CENTRO_COSTO	INT		NULL,
	GEN_OTRO_RESP		INT		NULL
)
go



ALTER TABLE SOLICITUD_AF_NOTIF  ADD CONSTRAINT SOLICITUDAFNOTIFPK PRIMARY KEY NONCLUSTERED (SOLICITUD )
go        
  
   
 
 
 
 CREATE TABLE TEMP_HIST_DEPR (
        USUARIO              VARCHAR(25) NOT NULL,
        CONSECUTIVO          int NOT NULL,
        ACTIVO_FIJO          VARCHAR(10) NOT NULL,
        MEJORA               VARCHAR(10) NOT NULL,
        TIPO_ACTIVO          VARCHAR(4) NOT NULL,
        CONTABILIDAD         VARCHAR(1) NOT NULL,
        METODO               VARCHAR(1) NOT NULL,
        DEPR_LOCAL           DECIMAL(28,8) NOT NULL,
        DEPR_DOLAR           DECIMAL(28,8) NOT NULL,
        DEPR_REV_LOCAL       DECIMAL(28,8) NOT NULL,
        DEPR_REV_DOLAR       DECIMAL(28,8) NOT NULL
 )
go
 
 
 ALTER TABLE TEMP_HIST_DEPR
        ADD CONSTRAINT XPKHIST_DEPR_TEMP PRIMARY KEY (USUARIO, 
               CONSECUTIVO)
go
 
 
 CREATE TABLE TEMP_HIST_REVAL (
        USUARIO              VARCHAR(25) NOT NULL,
        CONSECUTIVO          int NOT NULL,
        ACTIVO_FIJO          VARCHAR(10) NOT NULL,
        MEJORA               VARCHAR(10) NOT NULL,
        TIPO_ACTIVO          VARCHAR(4) NOT NULL,
        METODO               VARCHAR(1) NOT NULL,
        REVAL_VALOR          DECIMAL(28,8) NOT NULL,
        REVAL_VALOR_C        DECIMAL(28,8) NOT NULL,
        REVAL_DEPR_ACUM_F    DECIMAL(28,8) NOT NULL,
        REVAL_DEPR_ACUM_C    DECIMAL(28,8) NOT NULL,
        METODO_C	     VARCHAR(1)	NOT NULL
 )
go
 
 
 ALTER TABLE TEMP_HIST_REVAL
        ADD CONSTRAINT XPKHIST_REV_TEMP PRIMARY KEY NONCLUSTERED (
               USUARIO, CONSECUTIVO)
go
 
 
 CREATE TABLE TIPO_ACCION_AF (
        TIPO_ACCION_AF       VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        TIPO_ACCION_PREDEF   smallint NOT NULL,
        TEXTO_PREDEF         TEXT NULL
 )
go
 
 
 ALTER TABLE TIPO_ACCION_AF
        ADD CONSTRAINT XPKTIPO_ACCION_AF PRIMARY KEY (TIPO_ACCION_AF)
go
 
 
 CREATE TABLE TIPO_ACTIVO (
        TIPO_ACTIVO          	VARCHAR(4) 	NOT NULL,
        CTA_REVAL_DA         	VARCHAR(25) 	NULL,
        DESCRIPCION          	VARCHAR(40) 	NOT NULL,
        TIPO_DEPR_FISCAL     	VARCHAR(1) 	NOT NULL,
        TIPO_DEPR_COMP       	VARCHAR(1) 	NOT NULL,
        USA_DEPR_PORC        	VARCHAR(1) 	NOT NULL,
        SUMA_100_DEPR_PORC   	VARCHAR(1) 	NULL,
        TIPO_REVAL           	VARCHAR(1) 	NOT NULL,
        PORC_REVAL           	DECIMAL(28,8) 	NOT NULL,
        CTR_ACTIVO           	VARCHAR(25) 	NULL,
        CTA_ACTIVO           	VARCHAR(25) 	NULL,
        CTR_DEPR_ACUM_NORM   	VARCHAR(25) 	NULL,
        CTA_DEPR_ACUM_NORM   	VARCHAR(25) 	NULL,
        CTR_REVALUACION      	VARCHAR(25) 	NULL,
        CTA_REVALUACION      	VARCHAR(25) 	NULL,
        CTR_DEPR_ACUM_REV    	VARCHAR(25) 	NULL,
        CTA_DEPR_ACUM_REV    	VARCHAR(25) 	NULL,
        TIPO_INDICE_PRECIO   	VARCHAR(4) 	NULL,
        CONSECUTIVO          	VARCHAR(10) 	NULL,
        CTR_REVAL_DA         	VARCHAR(25) 	NULL,
        PORC_COMP_EXT        	DECIMAL(28,8) 	NULL,        
	PORC_COMP_LOC        	DECIMAL(28,8) 	NULL,
	IND_REV_COMP_1       	VARCHAR(4)	NULL,
	IND_REV_COMP_2       	VARCHAR(4)	NULL,
	IND_REV_COMP_3       	VARCHAR(4)	NULL,
	TIPO_REVAL_C	     	VARCHAR(1)	NOT NULL,
	PORC_REVAL_C	     	DECIMAL(28,8) 	NULL,
	TIPO_INDICE_PRECIO_C 	VARCHAR(4)	NULL,
	PORC_DEPR_FISCAL     	DECIMAL(28,8) 	NULL,
	PORC_DEPR_COMP 	     	DECIMAL(28,8) 	NULL,
	TASA_DEPRECIACION_F 	DECIMAL(28,8) 	NULL,
	TASA_DEPRECIACION_C 	DECIMAL(28,8)	NULL,
	CTR_ACTIVO_C        	VARCHAR(25) 	NULL,
	CTA_ACTIVO_C		VARCHAR(25) 	NULL,
	CTR_DEPR_ACUM_NORM_C	VARCHAR(25) 	NULL,
	CTA_DEPR_ACUM_NORM_C	VARCHAR(25) 	NULL,
	CTR_REVALUACION_C	VARCHAR(25) 	NULL,
	CTA_REVALUACION_C	VARCHAR(25) 	NULL,
	CTR_DEPR_ACUM_REV_C	VARCHAR(25) 	NULL,
	CTA_DEPR_ACUM_REV_C	VARCHAR(25) 	NULL,
	CTR_REVAL_DA_C		VARCHAR(25) 	NULL,
	CTA_REVAL_DA_C		VARCHAR(25) 	NULL,
	CTR_DEPR_ACUM_AI_F	VARCHAR(25) 	NULL,
	CTA_DEPR_ACUM_AI_F	VARCHAR(25) 	NULL,
	CTR_DEPR_ACUM_AI_C	VARCHAR(25) 	NULL,
	CTA_DEPR_ACUM_AI_C	VARCHAR(25) 	NULL,
	CTR_AJU_INFLAC		VARCHAR(25) 	NULL,
	CTA_AJU_INFLAC		VARCHAR(25) 	NULL,
	CTR_AJU_INFLAC_C	VARCHAR(25) 	NULL,
	CTA_AJU_INFLAC_C	VARCHAR(25) 	NULL,
	CTR_AI_DEPREC		VARCHAR(25) 	NULL,
	CTA_AI_DEPREC		VARCHAR(25) 	NULL,
	CTR_AI_DEPREC_C		VARCHAR(25) 	NULL,
	CTA_AI_DEPREC_C		VARCHAR(25) 	NULL,
	ES_TERRENO 		VARCHAR(1) 	NULL,
	CTR_DETERIORO_C 	VARCHAR(25) 	NULL,
	CTA_DETERIORO_C 	VARCHAR(25) 	NULL,
	CTR_GASTO_DETERIORO_C 	VARCHAR(25) 	NULL,
	CTA_GASTO_DETERIORO_C 	VARCHAR(25) 	NULL,
	CTR_DESMAN_C 		VARCHAR(25) 	NULL,
	CTA_DESMAN_C 		VARCHAR(25) 	NULL,
	CTR_DEPR_DESMAN_C 	VARCHAR(25) 	NULL,
	CTA_DEPR_DESMAN_C 	VARCHAR(25) 	NULL,	
	CTR_DETERIORO_F 	VARCHAR(25) 	NULL,
	CTA_DETERIORO_F 	VARCHAR(25) 	NULL,
	CTR_GASTO_DETERIORO_F 	VARCHAR(25) 	NULL,
	CTA_GASTO_DETERIORO_F 	VARCHAR(25) 	NULL,
	CTR_DESMAN_F 		VARCHAR(25) 	NULL,
	CTA_DESMAN_F 		VARCHAR(25) 	NULL,
	CTR_DEPR_DESMAN_F 	VARCHAR(25) 	NULL,
	CTA_DEPR_DESMAN_F 	VARCHAR(25) 	NULL,
	CONCEPTO_ME 		VARCHAR(4) 	NULL
 )
go
 
 
 ALTER TABLE TIPO_ACTIVO
        ADD CONSTRAINT TIPOACTIVOPK PRIMARY KEY NONCLUSTERED (TIPO_ACTIVO)
go
 
 
 CREATE TABLE TIPO_INDICE_PRECIO (
        TIPO_INDICE_PRECIO   VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL
 )
go
 
 
 ALTER TABLE TIPO_INDICE_PRECIO
        ADD CONSTRAINT TIPOINDICEPRECIOPK PRIMARY KEY NONCLUSTERED (
               TIPO_INDICE_PRECIO)
go
 
CREATE TABLE TOMA_ACTIVO_OBSERV (
        ACTIVO_OBSERVACION    VARCHAR(4) 	NOT NULL,
        DESCRIPCION	      VARCHAR(254)	NULL,
        TIPO_OBSERVACION      INT 		NULL     
)
go

ALTER TABLE TOMA_ACTIVO_OBSERV
         ADD CONSTRAINT XPKTOMAOBS PRIMARY KEY NONCLUSTERED (ACTIVO_OBSERVACION)
go

CREATE TABLE TOMA_ACTIVO_ACCION (
        ACTIVO_FIJO        VARCHAR(10) NOT NULL,
        ACTIVO_OBSERVACION VARCHAR(4) NOT NULL,
        NUEVO_VALOR	   VARCHAR(18)  NULL,
        FIRME		   INT NULL,
        TIPO_ACCION	   VARCHAR(11) NULL,
        POCKET_ID	   VARCHAR(25) NULL
 )
go
 
 ALTER TABLE TOMA_ACTIVO_ACCION
       ADD  CONSTRAINT XPKTOMAACC PRIMARY KEY (ACTIVO_FIJO) 
go

CREATE TABLE TOMA_ACTIVO_CAMBIO (
        ACTIVO_FIJO          VARCHAR(10) NOT NULL,
        TIPO_ACTIVO          VARCHAR(4)  NULL,
        DESCRIPCION          VARCHAR(40) NULL,     
        RESPONSABLE          VARCHAR(20) NULL,
 	UBICACION            VARCHAR(8) NULL,        
        CODIGO_BARRAS        VARCHAR(20) NULL,
        NUMERO_SERIE         VARCHAR(20) NULL,
        ESTADO_ACTIVO	     VARCHAR(4)  NULL,		
        NOTAS                TEXT NULL,
        RUBRO1_ACTIVO	     VARCHAR(40) NULL,
	RUBRO2_ACTIVO	     VARCHAR(40) NULL,
	RUBRO3_ACTIVO	     VARCHAR(40) NULL,
	RUBRO4_ACTIVO	     VARCHAR(40) NULL,
	RUBRO5_ACTIVO	     VARCHAR(40) NULL,
	RUBRO6_ACTIVO	     VARCHAR(40) NULL,
	RUBRO7_ACTIVO	     VARCHAR(40) NULL,
	RUBRO8_ACTIVO	     VARCHAR(40) NULL,
	RUBRO9_ACTIVO	     VARCHAR(40) NULL,
	RUBRO10_ACTIVO	     VARCHAR(40) NULL,
	RUBRO11_ACTIVO	     VARCHAR(40) NULL,
	RUBRO12_ACTIVO	     VARCHAR(40) NULL,
	RUBRO13_ACTIVO	     VARCHAR(40) NULL,
	RUBRO14_ACTIVO	     VARCHAR(40) NULL,
	RUBRO15_ACTIVO	     VARCHAR(40) NULL,
	POCKET_ID	     VARCHAR(25) NULL,
	ID_SINCRO	     VARCHAR(25) NOT NULL,
	FECHA_SINCRO	     DATETIME NULL
)
go

ALTER TABLE TOMA_ACTIVO_CAMBIO
       ADD  CONSTRAINT XPKTOMACMB PRIMARY KEY (ACTIVO_FIJO,ID_SINCRO)
go

CREATE TABLE TOMA_ACTIVO_CONTROL (
        ACTIVO_FIJO          VARCHAR(10)  NOT NULL,
        ESTATUS_ACTIVO       VARCHAR(25)  NULL,
        NUEVO		     INT          NULL,
        CODIGO_ACTIVO        VARCHAR(10)  NULL,
        POCKET_ID	     VARCHAR(25)  NULL,
        ID_SINCRO	     VARCHAR(25)  NOT NULL,
	FECHA_SINCRO	     DATETIME     NULL
)
go

ALTER TABLE TOMA_ACTIVO_CONTROL
       ADD  CONSTRAINT XPKTOMACTR PRIMARY KEY (ACTIVO_FIJO,ID_SINCRO)
go

 