         	
 
 
ALTER TABLE ATRIBUTO_VALOR
        ADD CONSTRAINT ESPRANGO
               FOREIGN KEY (ATRIBUTO)
                              REFERENCES ATRIBUTO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE AUDITORIA_DE_PROC
        ADD CONSTRAINT AUDPUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
ALTER TABLE BOD_CARGA_MANUF
         ADD CONSTRAINT BODCARGMANUF
         FOREIGN KEY  ( BODEGA )
         REFERENCES BODEGA ( BODEGA )
go

ALTER TABLE BODEGA
	ADD CONSTRAINT BODECONSECI
               FOREIGN KEY (CONSEC_TRASLADOS)
                              REFERENCES CONSECUTIVO_CI
go   


ALTER TABLE BODEGA_ENCARGADO
         ADD CONSTRAINT FKBODENCAR
         	FOREIGN KEY  ( BODEGA )
         		REFERENCES BODEGA ( BODEGA )
go       		


ALTER TABLE BODEGA_ENCARGADO
         ADD CONSTRAINT FKEMPBODENCAR
        	 FOREIGN KEY  ( EMPLEADO )
        		 REFERENCES EMPLEADO ( EMPLEADO )
go 



 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCCCXCCC
               FOREIGN KEY (CTR_CREDITO_CXC, CTA_CREDITO_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCDCXCCC
               FOREIGN KEY (CTR_DEBITO_CXC, CTA_DEBITO_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCRCXCCC
               FOREIGN KEY (CTR_RECIBOS_CXC, CTA_RECIBOS_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCIMCCCC
               FOREIGN KEY (CTR_INT_MORA_CXC, CTA_INT_MORA_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCPPCCCC
               FOREIGN KEY (CTR_PRONTO_PAG_CXC, CTA_PRONTO_PAG_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCCONTCC
               FOREIGN KEY (CTR_CONTADO, CTA_CONTADO)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCLXCCC
               FOREIGN KEY (CTR_LXC, CTA_LXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCCXCCC
               FOREIGN KEY (CTR_CXC, CTA_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCCCOMCC
               FOREIGN KEY (CTR_COBR_COM, CTA_COBR_COM)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCVCOMCC
               FOREIGN KEY (CTR_VEND_COM, CTA_VEND_COM)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCCLINCC
               FOREIGN KEY (CTR_COST_LIN, CTA_COST_LIN)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCDLINCC
               FOREIGN KEY (CTR_DESC_LIN, CTA_DESC_LIN)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCCVENCC
               FOREIGN KEY (CTR_COST_VENT, CTA_COST_VENT)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCDGRLCC
               FOREIGN KEY (CTR_DESC_GRAL, CTA_DESC_GRAL)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCVENTCC
               FOREIGN KEY (CTR_VENTAS, CTA_VENTAS)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCANTCXCCC
               FOREIGN KEY (CTR_ANTICIPO_CXC, CTA_ANTICIPO_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCRUB2CXCCC
               FOREIGN KEY (CTR_RUBRO2_CXC, CTA_RUBRO2_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCRUB1CXCCC
               FOREIGN KEY (CTR_RUBRO1_CXC, CTA_RUBRO1_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCIMP2CXCCC
               FOREIGN KEY (CTR_IMPUESTO2_CXC, CTA_IMPUESTO2_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CCIMP1CXCCC
               FOREIGN KEY (CTR_IMPUESTO1_CXC, CTA_IMPUESTO1_CXC)
                              REFERENCES CENTRO_CUENTA
go


ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CATCLIDVCTRCTA
               FOREIGN KEY (CTR_DEV_VENTAS, CTA_DEV_VENTAS)
                              REFERENCES CENTRO_CUENTA
go 

ALTER TABLE CATEGORIA_CLIENTE
         ADD CONSTRAINT CATINTCTECC
         	FOREIGN KEY  ( CTR_INT_CORRIENTE, CTA_INT_CORRIENTE )
         		REFERENCES CENTRO_CUENTA( CENTRO_COSTO,CUENTA_CONTABLE )
go         		

ALTER TABLE CATEGORIA_CLIENTE
	ADD CONSTRAINT CTAVENTEXEN
		FOREIGN KEY (CTR_VENTAS_EXEN,CTA_VENTAS_EXEN)
			REFERENCES CENTRO_CUENTA
go
			
ALTER TABLE CATEGORIA_CLIENTE
	ADD CONSTRAINT CTAAJUSREDONDEOCATCLI
		FOREIGN KEY (CTR_AJUSTE_REDONDEO,CTA_AJUSTE_REDONDEO)
			REFERENCES CENTRO_CUENTA
go
	
 ALTER TABLE CATEGORIA_PROVEED
        ADD CONSTRAINT CPCXPCC
               FOREIGN KEY (CTR_CXP, CTA_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_PROVEED
        ADD CONSTRAINT CPANTCC
               FOREIGN KEY (CTR_ANTICIPO_CXP, CTA_ANTICIPO_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_PROVEED
        ADD CONSTRAINT CPRUB2CC
               FOREIGN KEY (CTR_RUBRO2_CXP, CTA_RUBRO2_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_PROVEED
        ADD CONSTRAINT CPRUB1CC
               FOREIGN KEY (CTR_RUBRO1_CXP, CTA_RUBRO1_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_PROVEED
        ADD CONSTRAINT CPIMP2CC
               FOREIGN KEY (CTR_IMPUESTO2_CXP, CTA_IMPUESTO2_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_PROVEED
        ADD CONSTRAINT CPIMP1CC
               FOREIGN KEY (CTR_IMPUESTO1_CXP, CTA_IMPUESTO1_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_PROVEED
        ADD CONSTRAINT CPCOMCC
               FOREIGN KEY (CTR_COMISION_CXP, CTA_COMISION_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_PROVEED
        ADD CONSTRAINT CPPRPCC
               FOREIGN KEY (CTR_PRONTO_PAG_CXP, CTA_PRONTO_PAG_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_PROVEED
        ADD CONSTRAINT CPDEBCC
               FOREIGN KEY (CTR_DEBITO_CXP, CTA_DEBITO_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CATEGORIA_PROVEED
        ADD CONSTRAINT CPCRECC
               FOREIGN KEY (CTR_CREDITO_CXP, CTA_CREDITO_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 ALTER TABLE CATEGORIA_PROVEED
	ADD CONSTRAINT CTAAJUSREDONDEOCATPROV
		FOREIGN KEY (CTR_AJUSTE_REDONDEO,CTA_AJUSTE_REDONDEO)
			REFERENCES CENTRO_CUENTA
go

 ALTER TABLE CATEGORIA_PROVEED
        ADD CONSTRAINT CPLXPCC
               FOREIGN KEY (CTR_LXP, CTA_LXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE COBRADOR
        ADD CONSTRAINT COCOMICC
               FOREIGN KEY (CTR_COMISION, CTA_COMISION)
                              REFERENCES CENTRO_CUENTA
go


ALTER TABLE CONFIG_TARJETAS
	ADD CONSTRAINT CONFTARJTIPTARJE
		FOREIGN KEY (TIPO_TARJETA)
			REFERENCES TIPO_TARJETA(TIPO_TARJETA)
go

ALTER TABLE CONSECUTIVO
	ADD CONSTRAINT FKCONSEFA 
		FOREIGN KEY (CONSECUTIVO_NC)
			REFERENCES CONSECUTIVO_FA (CODIGO_CONSECUTIVO)
go

ALTER TABLE CONSECUTIVO_USUARIO
	ADD CONSTRAINT FK_CONSECUTIVOUSUARIO 
		FOREIGN KEY ( CONSECUTIVO )
			REFERENCES CONSECUTIVO(CONSECUTIVO)
go			

ALTER TABLE	CONSECUTIVO_USUARIO
	ADD CONSTRAINT FK_USUARIOCONSECUTIVO 
		FOREIGN KEY ( USUARIO )
			REFERENCES ERPADMIN.USUARIO(USUARIO)
go			
 
 ALTER TABLE DESC_PRONTO_PAGO
        ADD CONSTRAINT DESCPPAGCONDPAG
               FOREIGN KEY (CONDICION_PAGO)
                              REFERENCES CONDICION_PAGO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE DETALLE_DIRECCION
        ADD CONSTRAINT DETDIRDIR
               FOREIGN KEY (DIRECCION)
                              REFERENCES DIRECCION
go
 


ALTER TABLE DIVISION_GEOGRAFICA1
         ADD CONSTRAINT PAISDIV1
         	FOREIGN KEY  ( PAIS )
         		REFERENCES PAIS ( PAIS )
go



ALTER TABLE DIVISION_GEOGRAFICA2
         ADD CONSTRAINT PAISDIV1DIVGEO2
         	FOREIGN KEY  ( PAIS, DIVISION_GEOGRAFICA1 )
         		REFERENCES DIVISION_GEOGRAFICA1 ( PAIS, DIVISION_GEOGRAFICA1 )
         			ON DELETE CASCADE
go         			


ALTER TABLE DIVISION_GEOGRAFICA3
         ADD CONSTRAINT PAISDIV3
         	FOREIGN KEY  ( PAIS )
         		REFERENCES PAIS (PAIS) 
go

ALTER TABLE DIVISION_GEOGRAFICA3
         ADD CONSTRAINT PAISDIV1DIVGEO3
         	FOREIGN KEY  ( PAIS, DIVISION_GEOGRAFICA1, DIVISION_GEOGRAFICA2 )
         		REFERENCES DIVISION_GEOGRAFICA2 ( PAIS, DIVISION_GEOGRAFICA1, DIVISION_GEOGRAFICA2 )
         			ON DELETE CASCADE 
go

ALTER TABLE DIVISION_GEOGRAFICA4
         ADD CONSTRAINT PAISDIV4
         	FOREIGN KEY  (PAIS)
         		REFERENCES PAIS (PAIS) 
go


ALTER TABLE DIVISION_GEOGRAFICA4
         ADD CONSTRAINT PAISDIV1DIVGEO4
         	FOREIGN KEY  ( PAIS, DIVISION_GEOGRAFICA1, DIVISION_GEOGRAFICA2, DIVISION_GEOGRAFICA3  )
         		REFERENCES DIVISION_GEOGRAFICA3 ( PAIS, DIVISION_GEOGRAFICA1, DIVISION_GEOGRAFICA2 , DIVISION_GEOGRAFICA3 )
         			ON DELETE CASCADE 
go					

 
 ALTER TABLE ENTIDAD_FINANCIERA
        ADD CONSTRAINT ENTIDADFINNIT
               FOREIGN KEY (NIT)
                              REFERENCES NIT
go
 
 
ALTER TABLE EXCEP_CIUDAD
	ADD CONSTRAINT EXCEPCIURET
		FOREIGN KEY (CODIGO_RETENCION)
			REFERENCES RETENCIONES
go


ALTER TABLE EXCEP_CIUDAD
	ADD CONSTRAINT EXCEPREGRET
		FOREIGN KEY (CODIGO_RETENCION)
			REFERENCES RETENCIONES
go			

ALTER TABLE EXCEP_CIUDAD
        ADD CONSTRAINT EXCEPCIUDIVGEO
               FOREIGN KEY (PAIS, DIVISION_GEOGRAFICA1, DIVISION_GEOGRAFICA2 )
                              REFERENCES DIVISION_GEOGRAFICA2
go                              
 
 
ALTER TABLE EXCEP_CIUDAD 
        ADD CONSTRAINT EXCEPCIU_CTRCTA
               FOREIGN KEY (CENTRO_COSTO, CUENTA_CONTABLE)
               		REFERENCES CENTRO_CUENTA
go


ALTER TABLE EXCEP_REGIMEN 
        ADD CONSTRAINT EXCEPREG_CTRCTA
               FOREIGN KEY (CENTRO_COSTO, CUENTA_CONTABLE)
               		REFERENCES CENTRO_CUENTA
go               		


 
ALTER TABLE FORMATO_TRANSFER
	ADD CONSTRAINT FKFORMATOTRANSFERENTIDAD 
		FOREIGN KEY (ENTIDAD_FINANCIERA) 
			REFERENCES ENTIDAD_FINANCIERA
go

ALTER TABLE FORMATO_TRAN_PARAM
	ADD CONSTRAINT FKFORMATOPARAMTRANS 
		FOREIGN KEY (FORMATO) 
			REFERENCES FORMATO_TRANSFER
go

ALTER TABLE FORMATO_TRAN_SFTP  WITH CHECK ADD 
		FOREIGN KEY(FORMATO)
			REFERENCES FORMATO_TRANSFER (FORMATO)
go

 
 ALTER TABLE GLOBALES_AS
        ADD CONSTRAINT GBASTCMB
               FOREIGN KEY (TIPO_CAMBIO_DOLAR)
                              REFERENCES TIPO_CAMBIO
go
 
 
 ALTER TABLE GLOBALES_AS
        ADD CONSTRAINT GBASMOND
               FOREIGN KEY (MONEDA_DOLAR)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE GLOBALES_AS
        ADD CONSTRAINT GBASMONL
               FOREIGN KEY (MONEDA_LOCAL)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE GLOBALES_AS
        ADD CONSTRAINT GBASPAIS
               FOREIGN KEY (PAIS_LOCAL)
                              REFERENCES PAIS
go

 ALTER TABLE IMPUESTO
        ADD CONSTRAINT IMP1GEN_CTAC
               FOREIGN KEY (CTR_IMP1_GEN, CTA_IMP1_GEN)
                              REFERENCES CENTRO_CUENTA
go                              

 ALTER TABLE IMPUESTO
        ADD CONSTRAINT IMP2GEN_CTAC
               FOREIGN KEY (CTR_IMP2_GEN, CTA_IMP2_GEN)
                              REFERENCES CENTRO_CUENTA
go                              


 ALTER TABLE IMPUESTO
        ADD CONSTRAINT IMP1GENVTS_CTAC
               FOREIGN KEY (CTR_IMP1_GEN_VTS, CTA_IMP1_GEN_VTS)
                              REFERENCES CENTRO_CUENTA
go                              


 ALTER TABLE IMPUESTO
        ADD CONSTRAINT IMP2GENVTS_CTAC
               FOREIGN KEY (CTR_IMP2_GEN_VTS, CTA_IMP2_GEN_VTS)
                              REFERENCES CENTRO_CUENTA
go                              


 ALTER TABLE IMPUESTO
        ADD CONSTRAINT IMP1DESCCMPS_CTAC
               FOREIGN KEY (CTR_IMP1_DESC_CMPS, CTA_IMP1_DESC_CMPS)
                              REFERENCES CENTRO_CUENTA
go                              


 ALTER TABLE IMPUESTO
        ADD CONSTRAINT IMP2DESCCMPS_CTAC
               FOREIGN KEY (CTR_IMP2_DESC_CMPS, CTA_IMP2_DESC_CMPS)
                              REFERENCES CENTRO_CUENTA
go                              


 ALTER TABLE IMPUESTO
        ADD CONSTRAINT IMP1DEVCMPS_CTAC
               FOREIGN KEY (CTR_IMP1_DEV_CMPS, CTA_IMP1_DEV_CMPS)
                              REFERENCES CENTRO_CUENTA
go                              


 ALTER TABLE IMPUESTO
        ADD CONSTRAINT IMP2DEVCMPS_CTAC
               FOREIGN KEY (CTR_IMP2_DEV_CMPS, CTA_IMP2_DEV_CMPS)
                              REFERENCES CENTRO_CUENTA
go                              


 ALTER TABLE IMPUESTO
        ADD CONSTRAINT IMP1DEVVTS_CTAC
               FOREIGN KEY (CTR_IMP1_DEV_VTS, CTA_IMP1_DEV_VTS)
                              REFERENCES CENTRO_CUENTA
go                              


 ALTER TABLE IMPUESTO
        ADD CONSTRAINT IMP2DEVVTS_CTAC
               FOREIGN KEY (CTR_IMP2_DEV_VTS, CTA_IMP2_DEV_VTS)
                              REFERENCES CENTRO_CUENTA
go 
 
ALTER TABLE IMPUESTO
	ADD CONSTRAINT  FKTIPIMP1  
		FOREIGN KEY (TIPO_IMPUESTO1)
			REFERENCES TIPO_IMPUESTO (TIPO_IMPUESTO)
go

ALTER TABLE IMPUESTO
	ADD CONSTRAINT  FKTIPIMP2  
		FOREIGN KEY (TIPO_IMPUESTO2)
			REFERENCES TIPO_IMPUESTO (TIPO_IMPUESTO)
go

ALTER TABLE IMPUESTO
	ADD CONSTRAINT  FKTIPIMP1  
		FOREIGN KEY (TIPO_IMPUESTO1)
			REFERENCES TIPO_IMPUESTO (TIPO_IMPUESTO)
go

	ALTER TABLE IMPUESTO
	ADD CONSTRAINT  FKTIPIMP2  
		FOREIGN KEY (TIPO_IMPUESTO2)
			REFERENCES TIPO_IMPUESTO (TIPO_IMPUESTO)
go

 ALTER TABLE LOCALIZACION
        ADD CONSTRAINT LOCABOD
               FOREIGN KEY (BODEGA)
                              REFERENCES BODEGA
go
 
 
 ALTER TABLE LOCKS
        ADD CONSTRAINT LOCKUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE MONEDA_HIST
        ADD CONSTRAINT HTMONUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE MONEDA_HIST
        ADD CONSTRAINT HTMONMN
               FOREIGN KEY (MONEDA)
                              REFERENCES MONEDA
                              ON DELETE CASCADE
go


ALTER TABLE	NCF_CONSECUTIVO_USUARIO
		ADD CONSTRAINT FK_NCFCONSECUTIVOUSUARIO 
			FOREIGN KEY ( PREFIJO )
				REFERENCES NCF_CONSECUTIVO( PREFIJO ) 
go				
			

ALTER TABLE	NCF_CONSECUTIVO_USUARIO
		ADD CONSTRAINT FK_USUARIONCFCONSECUTIVO 
			FOREIGN KEY ( USUARIO )
				REFERENCES ERPADMIN.USUARIO(USUARIO)
go				

ALTER TABLE	NCF_CONSECUTIVO_USUARIO
		ADD CONSTRAINT FK_NCFCONSECUTIVOUSUARIO 
			FOREIGN KEY ( PREFIJO )
				REFERENCES NCF_CONSECUTIVO( PREFIJO )
go

ALTER TABLE NIT 
	ADD CONSTRAINT FK_TIPONIT 
		FOREIGN KEY (TIPO)
                	REFERENCES TIPO_NIT
go  


ALTER TABLE NIT
        ADD CONSTRAINT NITPAIS
               FOREIGN KEY (PAIS)
                              REFERENCES PAIS
go             
 
 
 ALTER TABLE NIVEL_PRECIO
        ADD CONSTRAINT NIVPRECCONDPAG
               FOREIGN KEY (CONDICION_PAGO)
                              REFERENCES CONDICION_PAGO
go
 
 
 ALTER TABLE PAGOS_PARCIALES
        ADD CONSTRAINT PAGPARCONDPAG
               FOREIGN KEY (CONDICION_PAGO)
                              REFERENCES CONDICION_PAGO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PAISDIR
               FOREIGN KEY (DIRECCION)
                              REFERENCES DIRECCION
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PARUB2CC
               FOREIGN KEY (CTR_RUBRO2_CXP, CTA_RUBRO2_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PADLINCC
               FOREIGN KEY (CTR_DESC_LIN, CTA_DESC_LIN)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PACVENCC
               FOREIGN KEY (CTR_COST_VENT, CTA_COST_VENT)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PADGRLCC
               FOREIGN KEY (CTR_DESC_GRAL, CTA_DESC_GRAL)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PAVENTCC
               FOREIGN KEY (CTR_VENTAS, CTA_VENTAS)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PAIMP2CC
               FOREIGN KEY (CTR_IMPUESTO2_CXP, CTA_IMPUESTO2_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PAIMP1CC
               FOREIGN KEY (CTR_IMPUESTO1_CXP, CTA_IMPUESTO1_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PACOCPCC
               FOREIGN KEY (CTR_COMISION_CXP, CTA_COMISION_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PAPPCPCC
               FOREIGN KEY (CTR_PRONTO_PAG_CXP, CTA_PRONTO_PAG_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PACXPCC
               FOREIGN KEY (CTR_CXP, CTA_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PADCXPCC
               FOREIGN KEY (CTR_DEBITO_CXP, CTA_DEBITO_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PACCXPCC
               FOREIGN KEY (CTR_CREDITO_CXP, CTA_CREDITO_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PALXPCC
               FOREIGN KEY (CTR_LXP, CTA_LXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PACCXCCC
               FOREIGN KEY (CTR_CREDITO_CXC, CTA_CREDITO_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PADCXCCC
               FOREIGN KEY (CTR_DEBITO_CXC, CTA_DEBITO_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PARCXCCC
               FOREIGN KEY (CTR_RECIBOS_CXC, CTA_RECIBOS_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PAINTMCC
               FOREIGN KEY (CTR_INT_MORA_CXC, CTA_INT_MORA_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PAPPCCCC
               FOREIGN KEY (CTR_PRONTO_PAG_CXC, CTA_PRONTO_PAG_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PALXCCC
               FOREIGN KEY (CTR_LXC, CTA_LXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PACXCCC
               FOREIGN KEY (CTR_CXC, CTA_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PACONTCC
               FOREIGN KEY (CTR_CONTADO, CTA_CONTADO)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PAGCOMCC
               FOREIGN KEY (CTR_GAST_COM, CTA_GAST_COM)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PACLINCC
               FOREIGN KEY (CTR_COST_LIN, CTA_COST_LIN)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PAANTCXCCC
               FOREIGN KEY (CTR_ANTICIPO_CXC, CTA_ANTICIPO_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PARUB2CXCCC
               FOREIGN KEY (CTR_RUBRO2_CXC, CTA_RUBRO2_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PARUB1CXCCC
               FOREIGN KEY (CTR_RUBRO1_CXC, CTA_RUBRO1_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PAIMP2CXCCC
               FOREIGN KEY (CTR_IMPUESTO2_CXC, CTA_IMPUESTO2_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PAIMP1CXCCC
               FOREIGN KEY (CTR_IMPUESTO1_CXC, CTA_IMPUESTO1_CXC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PAANTCC
               FOREIGN KEY (CTR_ANTICIPO_CXP, CTA_ANTICIPO_CXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PARUB1CC
               FOREIGN KEY (CTR_RUBRO1_CXP, CTA_RUBRO1_CXP)
                              REFERENCES CENTRO_CUENTA
go


ALTER TABLE PAIS
        ADD CONSTRAINT PAISDVCTRCTA
               FOREIGN KEY (CTR_DEV_VENTAS , CTA_DEV_VENTAS)
                              REFERENCES CENTRO_CUENTA
go                              


ALTER TABLE PAIS 
         ADD CONSTRAINT PAINTCTECC
         	FOREIGN KEY  ( CTR_INT_CORRIENTE, CTA_INT_CORRIENTE )
         		REFERENCES CENTRO_CUENTA( CENTRO_COSTO,CUENTA_CONTABLE )
go

ALTER TABLE PAIS
	ADD CONSTRAINT CTAVENTEXENPAIS
		FOREIGN KEY (CTR_VENTAS_EXEN,CTA_VENTAS_EXEN)
			REFERENCES CENTRO_CUENTA
go
			
ALTER TABLE PAIS
	ADD CONSTRAINT CTAAJUSREDONDEOPAIS
		FOREIGN KEY (CTR_AJUSTE_REDONDEO,CTA_AJUSTE_REDONDEO)
			REFERENCES CENTRO_CUENTA
go         
 
 ALTER TABLE PREFERENCIA
        ADD CONSTRAINT PREFUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go


ALTER TABLE REGIMENES
         ADD CONSTRAINT MODEREGIM
         	FOREIGN KEY  ( MODELO_RETENCION )
         		REFERENCES MODELO_RETENCION ( MODELO_RETENCION )
go         		


ALTER TABLE REGIMENES 
	ADD CONSTRAINT REGIMENESCENTROCTA
		FOREIGN KEY (CENTRO_COSTO, CUENTA_CONTABLE)
			REFERENCES CENTRO_CUENTA
go			



ALTER TABLE REGIMENES 
        ADD CONSTRAINT REG_CONSEC
               FOREIGN KEY (CONSECUTIVO)
               		REFERENCES CONSECUTIVO
go



ALTER TABLE REGION_DET
        ADD CONSTRAINT FK_REGIONDETPAIS
               FOREIGN KEY ( PAIS )
                              REFERENCES PAIS ( PAIS )
go                              

ALTER TABLE REGION_DET
        ADD CONSTRAINT FK_REGIONDETREGION
               FOREIGN KEY ( REGION )
                              REFERENCES REGION ( REGION ) 
                              ON DELETE CASCADE
go                              
 
 
 ALTER TABLE RESPONSABLE
        ADD CONSTRAINT RESPEMP
               FOREIGN KEY (EMPLEADO)
                              REFERENCES EMPLEADO
go
 
 
 ALTER TABLE RETENCIONES
        ADD CONSTRAINT CCTARET
               FOREIGN KEY (CTR_RETENCION, CTA_RETENCION)
                              REFERENCES CENTRO_CUENTA
go

ALTER TABLE RETENCIONES 
	ADD CONSTRAINT FTK_CLASIFICACION
		FOREIGN KEY (CLASIFICACION_ART) 
			REFERENCES CLASIFICACION (CLASIFICACION) 
go   



ALTER TABLE RETENCIONES 
        ADD CONSTRAINT RET_BASE_RET
               FOREIGN KEY (RETENCION_BASE)
                              REFERENCES RETENCIONES
go

ALTER TABLE RETENCIONES
       ADD CONSTRAINT CTAAUTORETCECU
              FOREIGN KEY ( CTR_AUTORETENCION,CTA_AUTORETENCION)
                             REFERENCES CENTRO_CUENTA
go

ALTER TABLE RETENCIONES
		ADD CONSTRAINT FKREING 
			FOREIGN KEY (CODIGO_INGRESO)
				REFERENCES COD_INGRESO (COD_INGRESO)

go         

ALTER TABLE RETENCIONES
	ADD CONSTRAINT  FKTIPIMPRET  
		FOREIGN KEY (TIPO_IMPUESTO)
			REFERENCES TIPO_IMPUESTO (TIPO_IMPUESTO)
go	

ALTER TABLE TABLA_UDF 
        ADD CONSTRAINT TBLUDFENCTBLUDF
               FOREIGN KEY (TABLA)
                              REFERENCES ENC_TABLA_UDF
go                              


 
 ALTER TABLE TIPO_CAMBIO_HIST
        ADD CONSTRAINT HTCMBUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE TIPO_CAMBIO_HIST
        ADD CONSTRAINT HTCMBTCB
               FOREIGN KEY (TIPO_CAMBIO)
                              REFERENCES TIPO_CAMBIO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE USUARIO_BODEGA
        ADD CONSTRAINT USUARIOBOD
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE USUARIO_BODEGA
        ADD CONSTRAINT BODEGAUSR
               FOREIGN KEY (BODEGA)
                              REFERENCES BODEGA
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE VENDEDOR
        ADD CONSTRAINT VECOMICC
               FOREIGN KEY (CTR_COMISION, CTA_COMISION)
                              REFERENCES CENTRO_CUENTA
go
 
 
ALTER TABLE PAIS
        ADD CONSTRAINT CCDESCBONIFPAIS
               FOREIGN KEY (CTR_DESC_BONIF, CTA_DESC_BONIF)
                              REFERENCES CENTRO_CUENTA (CENTRO_COSTO, CUENTA_CONTABLE)
go


ALTER TABLE  CATEGORIA_CLIENTE 
        ADD CONSTRAINT CCDESCBONIFCATCLI
               FOREIGN KEY (CTR_DESC_BONIF, CTA_DESC_BONIF)
                              REFERENCES CENTRO_CUENTA (CENTRO_COSTO, CUENTA_CONTABLE)
go

                             