CREATE TABLE ADUANA (
         ADUANA         VARCHAR(12)         NOT NULL,
         DESCRIPCION         VARCHAR(254)         NOT NULL 
)
go         


ALTER TABLE ADUANA
         ADD CONSTRAINT ADUANAPK PRIMARY KEY NONCLUSTERED  (ADUANA )
go   


CREATE TABLE AGENTE_ADUANAL (
         AGENTE_ADUANAL         VARCHAR(12)         NOT NULL,
         DESCRIPCION         VARCHAR(254)         NOT NULL 
)
go


ALTER TABLE AGENTE_ADUANAL
         ADD CONSTRAINT AGENTE_ADUANALPK PRIMARY KEY NONCLUSTERED
         (AGENTE_ADUANAL )
go  
 
 CREATE TABLE ATRIBUTO (
        ATRIBUTO             VARCHAR(20) NOT NULL,
        CLASE                VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE ATRIBUTO
        ADD CONSTRAINT ATRIBUTOPK PRIMARY KEY NONCLUSTERED (ATRIBUTO)
go
 
 
 CREATE TABLE ATRIBUTO_VALOR (
        ATRIBUTO             VARCHAR(20) NOT NULL,
        VALOR                VARCHAR(20) NOT NULL
 )
go
 
 
 ALTER TABLE ATRIBUTO_VALOR
        ADD CONSTRAINT ESPECIFICA_CALIFPK PRIMARY KEY NONCLUSTERED (
               ATRIBUTO, VALOR)
go
 
 
 CREATE TABLE AUDITORIA_DE_PROC (
        USUARIO              VARCHAR(25) NOT NULL,
        FECHA_HORA           DATETIME NOT NULL,
        ORIGEN               VARCHAR(4) NOT NULL,
        OPCION               VARCHAR(40) NOT NULL,
        NOTAS                TEXT NULL,
        ASIENTO              VARCHAR(10) NULL
 )
go
 

 CREATE TABLE BODEGA (
        BODEGA               VARCHAR(4) NOT NULL,
        NOMBRE               VARCHAR(40) NOT NULL,
        TIPO                 VARCHAR(1) NOT NULL,
        TELEFONO             VARCHAR(15) NOT NULL,
        DIRECCION            VARCHAR(120) NULL,
        CONSEC_TRASLADOS     VARCHAR(10) NULL
 )
go
 
 
 ALTER TABLE BODEGA
        ADD CONSTRAINT BODEGAPK PRIMARY KEY NONCLUSTERED (BODEGA)
go
 
CREATE TABLE BOD_CARGA_MANUF (
         BODEGA         	VARCHAR(4)         NOT NULL,
         UTILIZA_MANUF         VARCHAR(1)         NOT NULL,
         MODULO         	VARCHAR(1)         NULL )
go



ALTER TABLE BOD_CARGA_MANUF
         ADD CONSTRAINT XPK_BODCARGMANUF PRIMARY KEY NONCLUSTERED
         (BODEGA )
go


CREATE TABLE BODEGA_ENCARGADO (
         BODEGA         VARCHAR(4)  	NOT NULL,
         ENCARGADO      VARCHAR(70) 	NOT NULL,
         EMPLEADO       VARCHAR(20) 	NULL,
         E_MAIL         VARCHAR(250) 	NOT NULL )
go


ALTER TABLE BODEGA_ENCARGADO
         ADD CONSTRAINT XPKBODEGA_ENCARGAD PRIMARY KEY NONCLUSTERED
         (BODEGA, ENCARGADO )
go 


CREATE TABLE CARGOS (
	CODIGO		VARCHAR(4) NOT NULL,
	DESCRIPCION	VARCHAR(30) NULL
)
go

ALTER TABLE CARGOS ADD CONSTRAINT XPKCARGO PRIMARY KEY (CODIGO)
go


 CREATE TABLE CATEGORIA_CLIENTE (
        CATEGORIA_CLIENTE    VARCHAR(8) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        CTR_VENTAS           VARCHAR(25) NULL,
        CTA_VENTAS           VARCHAR(25) NULL,
        CTR_DESC_GRAL        VARCHAR(25) NULL,
        CTA_DESC_GRAL        VARCHAR(25) NULL,
        CTR_COST_VENT        VARCHAR(25) NULL,
        CTA_COST_VENT        VARCHAR(25) NULL,
        CTR_DESC_LIN         VARCHAR(25) NULL,
        CTA_DESC_LIN         VARCHAR(25) NULL,
        CTR_COST_LIN         VARCHAR(25) NULL,
        CTA_COST_LIN         VARCHAR(25) NULL,
        CTR_VEND_COM         VARCHAR(25) NULL,
        CTA_VEND_COM         VARCHAR(25) NULL,
        CTR_COBR_COM         VARCHAR(25) NULL,
        CTA_COBR_COM         VARCHAR(25) NULL,
        CTR_CXC              VARCHAR(25) NULL,
        CTA_CXC              VARCHAR(25) NULL,
        CTR_LXC              VARCHAR(25) NULL,
        CTA_LXC              VARCHAR(25) NULL,
        CTR_CONTADO          VARCHAR(25) NULL,
        CTA_CONTADO          VARCHAR(25) NULL,
        CTR_PRONTO_PAG_CXC   VARCHAR(25) NULL,
        CTA_PRONTO_PAG_CXC   VARCHAR(25) NULL,
        CTR_INT_MORA_CXC     VARCHAR(25) NULL,
        CTA_INT_MORA_CXC     VARCHAR(25) NULL,
        CTR_RECIBOS_CXC      VARCHAR(25) NULL,
        CTA_RECIBOS_CXC      VARCHAR(25) NULL,
        CTR_DEBITO_CXC       VARCHAR(25) NULL,
        CTA_DEBITO_CXC       VARCHAR(25) NULL,
        CTR_CREDITO_CXC      VARCHAR(25) NULL,
        CTA_CREDITO_CXC      VARCHAR(25) NULL,
        CTR_IMPUESTO1_CXC    VARCHAR(25) NULL,
        CTA_IMPUESTO1_CXC    VARCHAR(25) NULL,
        CTR_IMPUESTO2_CXC    VARCHAR(25) NULL,
        CTA_IMPUESTO2_CXC    VARCHAR(25) NULL,
        CTR_RUBRO1_CXC       VARCHAR(25) NULL,
        CTA_RUBRO1_CXC       VARCHAR(25) NULL,
        CTR_RUBRO2_CXC       VARCHAR(25) NULL,
        CTA_RUBRO2_CXC       VARCHAR(25) NULL,
        CTR_ANTICIPO_CXC     VARCHAR(25) NULL,
        CTA_ANTICIPO_CXC     VARCHAR(25) NULL,
        CTR_DESC_BONIF       VARCHAR(25) NULL,
        CTA_DESC_BONIF       VARCHAR(25) NULL,
        CTR_DEV_VENTAS       VARCHAR(25) NULL,
        CTA_DEV_VENTAS       VARCHAR(25) NULL,
        CTR_INT_CORRIENTE    VARCHAR(25) NULL,        
		CTA_INT_CORRIENTE    VARCHAR(25) NULL,
		CTR_VENTAS_EXEN 	 VARCHAR(25) NULL,
		CTA_VENTAS_EXEN 	 VARCHAR(25) NULL,
		CTR_AJUSTE_REDONDEO  VARCHAR(25) NULL,
		CTA_AJUSTE_REDONDEO  VARCHAR(25) NULL		
 	    
 )
go
 
 
 ALTER TABLE CATEGORIA_CLIENTE
        ADD CONSTRAINT CATEGORIA_CLIENTPK PRIMARY KEY NONCLUSTERED (
               CATEGORIA_CLIENTE)
go
 
 
 CREATE TABLE CATEGORIA_PROVEED (
        CATEGORIA_PROVEED    VARCHAR(8) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        CTR_CXP              VARCHAR(25) NULL,
        CTA_CXP              VARCHAR(25) NULL,
        CTR_LXP              VARCHAR(25) NULL,
        CTA_LXP              VARCHAR(25) NULL,
        CTR_CREDITO_CXP      VARCHAR(25) NULL,
        CTA_CREDITO_CXP      VARCHAR(25) NULL,
        CTR_DEBITO_CXP       VARCHAR(25) NULL,
        CTA_DEBITO_CXP       VARCHAR(25) NULL,
        CTR_PRONTO_PAG_CXP   VARCHAR(25) NULL,
        CTA_PRONTO_PAG_CXP   VARCHAR(25) NULL,
        CTR_COMISION_CXP     VARCHAR(25) NULL,
        CTA_COMISION_CXP     VARCHAR(25) NULL,
        CTR_IMPUESTO1_CXP    VARCHAR(25) NULL,
        CTA_IMPUESTO1_CXP    VARCHAR(25) NULL,
        CTR_IMPUESTO2_CXP    VARCHAR(25) NULL,
        CTA_IMPUESTO2_CXP    VARCHAR(25) NULL,
        CTR_RUBRO1_CXP       VARCHAR(25) NULL,
        CTA_RUBRO1_CXP       VARCHAR(25) NULL,
        CTR_RUBRO2_CXP       VARCHAR(25) NULL,
        CTA_RUBRO2_CXP       VARCHAR(25) NULL,
        CTR_ANTICIPO_CXP     VARCHAR(25) NULL,
        CTA_ANTICIPO_CXP     VARCHAR(25) NULL,
		CTR_AJUSTE_REDONDEO  VARCHAR(25) NULL,
		CTA_AJUSTE_REDONDEO  VARCHAR(25) NULL
 )
go
 
 
 ALTER TABLE CATEGORIA_PROVEED
        ADD CONSTRAINT CATEGORIA_PROVEEPK PRIMARY KEY NONCLUSTERED (
               CATEGORIA_PROVEED)
go
 
 
 CREATE TABLE CENTRO_COSTO (
        CENTRO_COSTO         VARCHAR(25) NOT NULL,
        DESCRIPCION          VARCHAR(200) NOT NULL,
        ACEPTA_DATOS         VARCHAR(1)  NOT NULL,
        TIPO         	     VARCHAR(1)  NOT NULL
 )
go
 
 
 ALTER TABLE CENTRO_COSTO
        ADD CONSTRAINT CENTROCOSTOPK PRIMARY KEY NONCLUSTERED (
               CENTRO_COSTO)
go
 
 
 CREATE TABLE COBRADOR (
        COBRADOR             VARCHAR(4) NOT NULL,
        NOMBRE               VARCHAR(40) NOT NULL,
        EMPLEADO             VARCHAR(20) NULL,
        COMISION             DECIMAL(28,8) NOT NULL,
        CTR_COMISION         VARCHAR(25) NULL,
        CTA_COMISION         VARCHAR(25) NULL,
        E_MAIL               VARCHAR(249) NULL,
        ACTIVO               VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE COBRADOR
        ADD CONSTRAINT COBRADORPK PRIMARY KEY NONCLUSTERED (COBRADOR)
go
 
 
 CREATE TABLE CONDICION_PAGO (
        CONDICION_PAGO       	VARCHAR(4) 	NOT NULL,
        DESCRIPCION          	VARCHAR(40) 	NOT NULL,
        DIAS_NETO            	int 		NOT NULL,
        PAGOS_PARCIALES      	VARCHAR(1) 	NOT NULL,
        DESCUENTO_CONTADO    	Decimal(28,8) 	NOT NULL,
        TIPO_CONDPAGO        	VARCHAR(2)    	NOT NULL,        
		PLAZO_CONDPAGO       	int           	NULL,
		TIPO_DIFERIDO 			VARCHAR(4) 	NULL,
		USA_DIFERIDO 		VARCHAR(1) 	NOT NULL DEFAULT ('N'),
		U_METODO_PAGO 		VARCHAR(100) NULL,
		U_FORMA_PAGO 		VARCHAR(100) NULL
 )
go
 
 
 ALTER TABLE CONDICION_PAGO
        ADD CONSTRAINT CONDPAGOPK PRIMARY KEY NONCLUSTERED (
               CONDICION_PAGO)
go


 CREATE TABLE CONFIG_ENVIOS (
        CODIGO                  VARCHAR(50)   	NOT NULL,
        DESCRIPCION         	VARCHAR(18)	NOT NULL,
        USA_CUENTA_ACTUAL   	VARCHAR(1)	NULL,
        SERVIDOR_SMTP       	VARCHAR(50)	NULL,
        ENVIO_MAIL_SALIDA  	VARCHAR(100)	NULL,
        PUERTO              	INT		NULL,
        REQ_AUTENTICACION   	VARCHAR(1)	NULL,
        USUARIO_SMTP        	VARCHAR(100)	NULL,
        USUARIO_PWD_SMTP    	VARCHAR(100)	NULL,
        CONFIRM_PWD_SMTP    	VARCHAR(100)	NULL,
        USA_USUARIO_RED     	VARCHAR(1)	NULL,
        USA_CONEXION_SSL    	VARCHAR(1)	NULL,
        METODO_ENTREGA      	VARCHAR(10)	NULL
 )
go


ALTER TABLE CONFIG_ENVIOS
        ADD CONSTRAINT PKCONFIG_ENVIOS PRIMARY KEY (CODIGO)
go
      

CREATE TABLE CONFIG_TARJETAS
(
 TIPO_TARJETA	VARCHAR(12)	NOT NULL,
 NOMBRE		VARCHAR(30) 	NOT NULL,
 TIPO		VARCHAR(1) 	NOT NULL 	DEFAULT ('S'),
 VALOR		VARCHAR(250) 	NOT NULL
)
go

ALTER TABLE CONFIG_TARJETAS
	ADD CONSTRAINT XPKCONFIG_TARJETAS	
		PRIMARY KEY NONCLUSTERED (TIPO_TARJETA, NOMBRE)
go


CREATE TABLE CONSECUTIVO(     
	CONSECUTIVO 			VARCHAR(10) 	NOT NULL, 
	DESCRIPCION			VARCHAR(40) 	NOT NULL,
	ACTIVO				VARCHAR(1) 	NOT NULL DEFAULT 'N', 			
	LONGITUD			DECIMAL(28,8) 	NOT NULL,
	ENTIDAD				VARCHAR(40) 	NOT NULL,
	DOCUMENTO			VARCHAR(50) 	NOT NULL,
	FORMATO_IMPRESION_DETALLADO	VARCHAR(250) 	NULL, 
	FORMATO_IMPRESION_RESUMIDO	VARCHAR(250) 	NULL,
	MASCARA				VARCHAR(50) 	NOT NULL,
	VALOR_INICIAL			VARCHAR(50) 	NOT NULL,
	VALOR_FINAL			VARCHAR(50) 	NOT NULL,
	ULTIMO_VALOR			VARCHAR(50) 	NOT NULL,
	ULTIMO_USUARIO			VARCHAR(25)	NOT NULL,
	FECHA_HORA_ULT			DATETIME	NOT NULL,
	CONSECUTIVO_NC  VARCHAR(10) NULL
)
go

 ALTER TABLE CONSECUTIVO
        ADD CONSTRAINT XPK_CONSECUTIVO 
        	PRIMARY KEY NONCLUSTERED (CONSECUTIVO)
go


CREATE TABLE CONSECUTIVO_USUARIO(
	CONSECUTIVO	VARCHAR(10) NOT NULL,
	USUARIO		VARCHAR(25) NOT NULL
)
go
 

ALTER TABLE CONSECUTIVO_USUARIO
         ADD CONSTRAINT  XPKCONSECUSUARIO PRIMARY KEY NONCLUSTERED
         (CONSECUTIVO, USUARIO)
go
			 
 
 
 CREATE TABLE DENOMINACION (
        TIPO                 VARCHAR(1) NOT NULL,
        DENOM_MONTO          Decimal(28,8) NOT NULL
 )
go
 
 
 ALTER TABLE DENOMINACION
        ADD CONSTRAINT DENOMINACIONPK PRIMARY KEY NONCLUSTERED (TIPO, 
               DENOM_MONTO)
go
 
 
 CREATE TABLE DEPARTAMENTO (
        DEPARTAMENTO         VARCHAR(10) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        JEFE                 VARCHAR(250) NULL
 )
go
 
 
 ALTER TABLE DEPARTAMENTO
        ADD CONSTRAINT DEPTOPKDEPTO PRIMARY KEY NONCLUSTERED (
               DEPARTAMENTO)
go
 
 
 CREATE TABLE DESC_PRONTO_PAGO (
        CONDICION_PAGO       VARCHAR(4) NOT NULL,
        CONSECUTIVO          smallint NOT NULL,
        DIA_INICIO           int NOT NULL,
        DIA_FIN              int NOT NULL,
        DESCUENTO            Decimal(28,8) NOT NULL
 )
go
 
 
 ALTER TABLE DESC_PRONTO_PAGO
        ADD CONSTRAINT XPKDESC_PRONTO_PAGO PRIMARY KEY (
               CONDICION_PAGO, CONSECUTIVO)
go


CREATE TABLE DET_MOD_RETENCION (
	CODIGO_RETENCION	VARCHAR(4)		NOT NULL,
	MODELO_RETENCION	VARCHAR(4) 		NOT NULL ,
	APLICA			VARCHAR(1)		NOT NULL DEFAULT 'A'
)
go


ALTER TABLE DET_MOD_RETENCION 
	ADD CONSTRAINT XPK_DETMODRET
		PRIMARY KEY (CODIGO_RETENCION, MODELO_RETENCION) 
go


 
 
 CREATE TABLE DETALLE_DIRECCION (
        DETALLE_DIRECCION    int NOT NULL,
        DIRECCION            VARCHAR(10) NOT NULL,
        CAMPO_1              VARCHAR(250) NULL,
        CAMPO_2              VARCHAR(250) NULL,
        CAMPO_3              VARCHAR(250) NULL,
        CAMPO_4              VARCHAR(250) NULL,
        CAMPO_5              VARCHAR(250) NULL,
        CAMPO_6              VARCHAR(250) NULL,
        CAMPO_7              VARCHAR(250) NULL,
        CAMPO_8              VARCHAR(250) NULL,
        CAMPO_9              VARCHAR(250) NULL,
        CAMPO_10             VARCHAR(250) NULL
 )
go
 
 
 ALTER TABLE DETALLE_DIRECCION
        ADD CONSTRAINT XPKDETALLE_DIRECCION PRIMARY KEY (
               DETALLE_DIRECCION)
go


CREATE TABLE DIAS_FERIADOS (
	 ID_FERIADO	   SMALLINT	     NOT NULL,
         DIA         	   SMALLINT	     NOT NULL,
	 MES		   SMALLINT          NOT NULL,
	 ANO	           SMALLINT	     NULL,
         DESCRIPCION       VARCHAR(100)      NULL,
	 TIPO		   VARCHAR(1)	     NOT NULL)
go	 

ALTER TABLE DIAS_FERIADOS 
         ADD CONSTRAINT XPKFERIADO PRIMARY KEY NONCLUSTERED
         (ID_FERIADO)
go         

 
 CREATE TABLE DIRECCION (
        DIRECCION            VARCHAR(10) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        NOMBRE_CAMPO_1       VARCHAR(60) NULL,
        NOMBRE_CAMPO_2       VARCHAR(60) NULL,
        NOMBRE_CAMPO_3       VARCHAR(60) NULL,
        NOMBRE_CAMPO_4       VARCHAR(60) NULL,
        NOMBRE_CAMPO_5       VARCHAR(60) NULL,
        NOMBRE_CAMPO_6       VARCHAR(60) NULL,
        NOMBRE_CAMPO_7       VARCHAR(60) NULL,
        NOMBRE_CAMPO_8       VARCHAR(60) NULL,
        NOMBRE_CAMPO_9       VARCHAR(60) NULL,
        NOMBRE_CAMPO_10      VARCHAR(60) NULL,
        USUARIO_CREACION     VARCHAR(25) NOT NULL,
        FECHA_CREACION       DATETIME NOT NULL,
        USUARIO_ULT_MODIF    VARCHAR(25) NOT NULL,
        FECHA_ULT_MODIF      DATETIME NOT NULL
 )
go
 
 
 ALTER TABLE DIRECCION
        ADD CONSTRAINT XPKDIRECCION PRIMARY KEY (DIRECCION)
go



CREATE TABLE DIVISION_GEOGRAFICA1
(	
	PAIS VARCHAR(4) NOT NULL,
	DIVISION_GEOGRAFICA1 VARCHAR(12) NOT NULL,
	NOMBRE VARCHAR(40) NOT NULL
)
go

ALTER TABLE DIVISION_GEOGRAFICA1
         ADD CONSTRAINT DIVGEOGRA1PK PRIMARY KEY NONCLUSTERED
         	(PAIS, DIVISION_GEOGRAFICA1 )
go


CREATE TABLE DIVISION_GEOGRAFICA2     
(	
	PAIS VARCHAR(4) NOT NULL,
	DIVISION_GEOGRAFICA1 VARCHAR(12) NOT NULL,
	DIVISION_GEOGRAFICA2 VARCHAR(12) NOT NULL,
	NOMBRE VARCHAR(40) NOT NULL	
)
go

ALTER TABLE DIVISION_GEOGRAFICA2
         ADD CONSTRAINT DIVGEOGRA2PK PRIMARY KEY NONCLUSTERED
        	 ( PAIS, DIVISION_GEOGRAFICA1 , DIVISION_GEOGRAFICA2 )
go        	 

CREATE TABLE DIVISION_GEOGRAFICA3
(	
	PAIS VARCHAR(4) NOT NULL,
	DIVISION_GEOGRAFICA1 VARCHAR(12) NOT NULL,
	DIVISION_GEOGRAFICA2 VARCHAR(12) NOT NULL,
	DIVISION_GEOGRAFICA3 VARCHAR(12) NOT NULL,
	NOMBRE VARCHAR(40) NOT NULL
) 
go

ALTER TABLE DIVISION_GEOGRAFICA3 
	ADD CONSTRAINT DIVGEOGRA3PK 
		PRIMARY KEY NONCLUSTERED (PAIS, DIVISION_GEOGRAFICA1 , DIVISION_GEOGRAFICA2, DIVISION_GEOGRAFICA3) 
go

CREATE TABLE DIVISION_GEOGRAFICA4
(	
	PAIS 				 VARCHAR(4)  NOT NULL,
	DIVISION_GEOGRAFICA1 VARCHAR(12) NOT NULL,
	DIVISION_GEOGRAFICA2 VARCHAR(12) NOT NULL,
	DIVISION_GEOGRAFICA3 VARCHAR(12) NOT NULL,
	DIVISION_GEOGRAFICA4 VARCHAR(12) NOT NULL,
	NOMBRE 				 VARCHAR(40) NOT NULL
) 
go

ALTER TABLE DIVISION_GEOGRAFICA4
	ADD CONSTRAINT DIVGEOGRA4PK 
		PRIMARY KEY NONCLUSTERED (PAIS, DIVISION_GEOGRAFICA1 , DIVISION_GEOGRAFICA2, DIVISION_GEOGRAFICA3, DIVISION_GEOGRAFICA4) 
go

CREATE TABLE DOC_ADJUNTO
(
	TABLA 		VARCHAR(32) 		NOT NULL,
	ROW_ID 		UNIQUEIDENTIFIER 	NOT NULL,
	CONSECUTIVO 	INTEGER IDENTITY(1,1) 	NOT NULL,
	NOMBRE 		VARCHAR(40) 		NOT NULL,
	DESCRIPCION 	VARCHAR(254) 		NOT NULL,
	CONTENIDO 	IMAGE 			NOT NULL,
)
go

ALTER TABLE DOC_ADJUNTO
	ADD CONSTRAINT DOC_ADJUNTO_PK  
		PRIMARY KEY (TABLA,ROW_ID,CONSECUTIVO,NOMBRE)
go		

CREATE TABLE ELIMINACION_SINCRO_POS (
	 ID_SENTENCIA		 INT IDENTITY(1,1)		NOT NULL,
	 TIPO_TIENDA		 VARCHAR(1)				NOT NULL DEFAULT('C'),
	 FECHA_ELIMINACION	 DATETIME				NOT NULL,
     SENTENCIA			 VARCHAR(8000)			NOT NULL,
     NOMBRE_TABLA		 VARCHAR(254)			NOT NULL,
     ESTADO				 VARCHAR(1)				NOT NULL DEFAULT('P'),	
     FECHA_APLICACION	 DATETIME				NULL,
     DETALLE_ERROR		 VARCHAR(8000)			NULL
)
go

ALTER TABLE ELIMINACION_SINCRO_POS
       ADD CONSTRAINT XPKELIMINASINCPOS PRIMARY KEY (ID_SENTENCIA, TIPO_TIENDA)
go


CREATE TABLE ENC_TABLA_UDF (
        TABLA		VARCHAR(18)	NOT NULL,
       	NOTAS   	TEXT		NULL,
       	LAYOUT 		VARCHAR(max) 	NULL,
	TIPO 		VARCHAR(1) 	NOT NULL DEFAULT ' ',
	ETIQUETA 	VARCHAR(30) 	NOT NULL DEFAULT ' '
)
go

ALTER TABLE ENC_TABLA_UDF 
       ADD CONSTRAINT XPKENCTABLAUDF 
       		PRIMARY KEY (TABLA)
go       		
 
 
 CREATE TABLE ENTIDAD_FINANCIERA (
        ENTIDAD_FINANCIERA   VARCHAR(8)  NOT NULL,
        NIT                  VARCHAR(20) NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        COD_ELECTRONICO      VARCHAR(20) NULL
 )
go
 
 
 
ALTER TABLE ENTIDAD_FINANCIERA
        ADD CONSTRAINT ENTIDAD_FINANCIPK PRIMARY KEY NONCLUSTERED (
               ENTIDAD_FINANCIERA)
go



CREATE TABLE EXCEP_CIUDAD  (
	PAIS			VARCHAR(4)	NOT NULL,
	DIVISION_GEOGRAFICA1	VARCHAR(12)	NOT NULL,
	DIVISION_GEOGRAFICA2	VARCHAR(12)	NOT NULL,
	CODIGO_RETENCION	VARCHAR(4) 	NOT NULL,
	PORCENTAJE		DECIMAL(28, 8)	NOT NULL,
	CENTRO_COSTO 		VARCHAR(25) 	NULL,
	CUENTA_CONTABLE		VARCHAR(25) 	NULL)
go	



ALTER TABLE EXCEP_CIUDAD
	ADD CONSTRAINT EXCEPCIONCUIDADPK PRIMARY KEY NONCLUSTERED  (PAIS, DIVISION_GEOGRAFICA1, DIVISION_GEOGRAFICA2, CODIGO_RETENCION)
go	


CREATE TABLE EXCEP_REGIMEN  (
	CODIGO			VARCHAR(12)	NOT NULL,
	CODIGO_RETENCION	VARCHAR(4) 	NOT NULL,
	PORCENTAJE 		DECIMAL(28, 8)	NOT NULL,
	CENTRO_COSTO 		VARCHAR(25) 	NULL,
	CUENTA_CONTABLE 	VARCHAR(25) 	NULL)
go	



ALTER TABLE EXCEP_REGIMEN
         ADD CONSTRAINT EXCEPCIONREGIMENPK PRIMARY KEY NONCLUSTERED  (CODIGO, CODIGO_RETENCION)
go         



CREATE TABLE FORMATO_TRANSFER (
        FORMATO       	     	VARCHAR(10) 	NOT NULL,
        DESCRIPCION          	VARCHAR(254)	NOT NULL, 
        ENTIDAD_FINANCIERA   	VARCHAR(8) 	NOT NULL, 
        TIPO_ARCHIVO          	VARCHAR(4) 	NOT NULL, 
        ARCHIVO_TRANSFORMACION  VARCHAR(50) 	NOT NULL, 
        FUENTE_DATOS         	VARCHAR(1) 	NOT NULL 
)
go

ALTER TABLE FORMATO_TRANSFER
        ADD CONSTRAINT PKFORMATOTRANSFER 
        	PRIMARY KEY (FORMATO)
go

CREATE TABLE FORMATO_TRAN_PARAM (
        FORMATO		VARCHAR(10) 	NOT NULL,
        NOMBRE        	VARCHAR(50)	NOT NULL,
        TIPO            VARCHAR(1) 	NOT NULL,
        VALOR           VARCHAR(100) 	NULL,
        UBICACION       VARCHAR(1) 	NOT NULL
)
go
 

ALTER TABLE FORMATO_TRAN_PARAM
        ADD CONSTRAINT PKFORMATOTRANSPARAM 
        	PRIMARY KEY (FORMATO, NOMBRE)
go    	
 
CREATE TABLE FORMATO_TRAN_SFTP(
	SERVIDOR_SFTP VARCHAR(50) NOT NULL,
	DIRECTORIO_SFTP VARCHAR(100) NOT NULL,
	PUERTO_SFTP INT NOT NULL,
	USUARIO VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	PASSWORD_CONFIRMACION VARCHAR(100) NOT NULL,
	PREFIJO_ARCHIVO VARCHAR(100) NOT NULL,
	FORMATO VARCHAR(10) NOT NULL,
)
go

ALTER TABLE FORMATO_TRAN_SFTP
		ADD CONSTRAINT FORMATO_TRAN_SFTP_PK 
			PRIMARY KEY (FORMATO)
go
 
CREATE TABLE GLOBALES (
         MODULO	   VARCHAR(20) 	NOT NULL,
         NOMBRE	   VARCHAR(30) 	NOT NULL,
         TIPO	   VARCHAR(1) 	NOT NULL,
         VALOR	   VARCHAR(250) NULL,
	 TEXTO     TEXT         NULL
)
go  

ALTER TABLE GLOBALES
        ADD CONSTRAINT GLOBALESPK 
		PRIMARY KEY NONCLUSTERED (MODULO, NOMBRE)
go
 
 
 CREATE TABLE GLOBALES_AS (
        FECHA_ADV_INI        DATETIME    NOT NULL,
        FECHA_ADV_FIN        DATETIME    NOT NULL,
        FECHA_TRABAJO_INI    DATETIME    NOT NULL,
        FECHA_TRABAJO_FIN    DATETIME    NOT NULL,
        NOMBRE_MON_FUNC      VARCHAR(10) NOT NULL,
        NOMBRE_MON_REP       VARCHAR(10) NOT NULL,
        SIMBOLO_MON_FUNC     VARCHAR(3)  NOT NULL,
        SIMBOLO_MON_REP      VARCHAR(3)  NOT NULL,
        IMPUESTO1_DESC       VARCHAR(10) NOT NULL,
        IMPUESTO2_DESC       VARCHAR(10) NOT NULL,
        PAIS_LOCAL           VARCHAR(4)  NOT NULL,
        MONEDA_LOCAL         VARCHAR(4)  NOT NULL,
        MONEDA_DOLAR         VARCHAR(4)  NOT NULL,
        TIPO_CAMBIO_DOLAR    VARCHAR(4)  NOT NULL,
        PATRON_CCOSTO        VARCHAR(25) NULL,
        COBRAR_IMP1PP_CC     VARCHAR(1)  NOT NULL,        
	COBRAR_IMP2PP_CC     VARCHAR(1)  NOT NULL,    
	CALC_FRACC_INTCTE    VARCHAR(1)  NOT NULL,            
	AJUSTAR_FECHAPAGO    VARCHAR(1)  NOT NULL,  
	AJ_FCHPAGO_ATRAS     VARCHAR(1)  NOT NULL,        
  	AJ_FCHPAGO_ADE       VARCHAR(1)  NOT NULL,
  	REPL_TC_CODIGO 	     VARCHAR(1)  NOT NULL,
	REPL_TC_HIST 	     VARCHAR(1)  NOT NULL,
	REPL_LISTA_CIA 	     TEXT	 NULL
 )
go
 
 
 CREATE TABLE IMAGEN (
        OBJECTKEY            VARCHAR(30) NOT NULL,
        OBJECT               TEXT NULL
 )
go
 
 
 ALTER TABLE IMAGEN
        ADD CONSTRAINT IMAGENPK PRIMARY KEY NONCLUSTERED (OBJECTKEY)
go
 
 
 
CREATE TABLE IMAGENES
(
	ROW_POINTER_GENERICO 	UNIQUEIDENTIFIER	NULL,
	IMAGEN 			IMAGE			NULL
)
go
  
 
 
 CREATE TABLE IMPUESTO (
	IMPUESTO                VARCHAR(4)      NOT NULL,
	DESCRIPCION             VARCHAR(40)     NOT NULL,
	IMPUESTO1               DECIMAL(28,8)   NOT NULL,
	IMPUESTO2               DECIMAL(28,8)   NOT NULL,
	USA_IMPUESTO2_CANTIDAD  VARCHAR(1)      NULL,
	IMPUESTO2_CANTIDAD      DECIMAL(28,8)   NULL,
	CTR_IMP1_GEN 		VARCHAR(25) 	NULL,
	CTA_IMP1_GEN 		VARCHAR(25) 	NULL,
	CTR_IMP2_GEN 		VARCHAR(25) 	NULL,
	CTA_IMP2_GEN 		VARCHAR(25) 	NULL,
	CTR_IMP1_GEN_VTS 	VARCHAR(25) 	NULL,
	CTA_IMP1_GEN_VTS 	VARCHAR(25) 	NULL,
	CTR_IMP2_GEN_VTS 	VARCHAR(25) 	NULL,
	CTA_IMP2_GEN_VTS 	VARCHAR(25) 	NULL,
	CTR_IMP1_DESC_CMPS 	VARCHAR(25) 	NULL,
	CTA_IMP1_DESC_CMPS 	VARCHAR(25) 	NULL,
	CTR_IMP2_DESC_CMPS 	VARCHAR(25) 	NULL,
	CTA_IMP2_DESC_CMPS 	VARCHAR(25) 	NULL,
	CTR_IMP1_DEV_CMPS 	VARCHAR(25) 	NULL,
	CTA_IMP1_DEV_CMPS 	VARCHAR(25) 	NULL,
	CTR_IMP2_DEV_CMPS 	VARCHAR(25) 	NULL,
	CTA_IMP2_DEV_CMPS 	VARCHAR(25) 	NULL,
	CTR_IMP1_DEV_VTS 	VARCHAR(25) 	NULL,
	CTA_IMP1_DEV_VTS 	VARCHAR(25) 	NULL,
	CTR_IMP2_DEV_VTS 	VARCHAR(25) 	NULL,
	CTA_IMP2_DEV_VTS 	VARCHAR(25) 	NULL,
	TIPO_CONTAB_IMP1 	VARCHAR(1)  	NOT NULL  DEFAULT 'U',
	TIPO_CONTAB_IMP2 	VARCHAR(1)  	NOT NULL  DEFAULT 'U',
	CONTAB_DEV_IMP1 	VARCHAR(1)  	NOT NULL  DEFAULT 'N',
	CONTAB_DEV_IMP2 	VARCHAR(1)  	NOT NULL  DEFAULT 'N',
	CALCULO_IMP2		VARCHAR(1)  	NOT NULL  DEFAULT 'I',
	U_IMPUESTO1_SAT 	VARCHAR(3) 		NULL, 
	U_IMPUESTO2_SAT 	VARCHAR(3) 		NULL,
	TIPO_IMPUESTO1 		VARCHAR (4)  	NULL, 
	TIPO_IMPUESTO2 		VARCHAR (4) 	NULL,
	U_IMPUESTO 			VARCHAR(4)		NULL,
	U_IMPUESTO2 		VARCHAR(4)		NULL
 )
go
 
 
 ALTER TABLE IMPUESTO
        ADD CONSTRAINT IMPUESTOPK PRIMARY KEY NONCLUSTERED (IMPUESTO)
go
 
 
 CREATE TABLE LOCALIZACION (
        BODEGA               VARCHAR(4) NOT NULL,
        LOCALIZACION         VARCHAR(8) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        VOLUMEN              DECIMAL(28,8) NOT NULL,
        PESO_MAXIMO          DECIMAL(28,8) NOT NULL
 )
go
 
 
 ALTER TABLE LOCALIZACION
        ADD CONSTRAINT LOCALIZACIONPK PRIMARY KEY NONCLUSTERED (
               BODEGA, LOCALIZACION)
go
 
 
 CREATE TABLE LOCKS (
        LLAVE                VARCHAR(100) NOT NULL,
        USUARIO              VARCHAR(25) NOT NULL,
        CONNECTION_ID        VARCHAR(80) NOT NULL,
        FECHA                DATETIME 	 NOT NULL
 )
go
 
 
 ALTER TABLE LOCKS
        ADD CONSTRAINT LOCKSPK PRIMARY KEY NONCLUSTERED (LLAVE)
go
 
 

CREATE TABLE MODELO_RETENCION ( 
	MODELO_RETENCION	VARCHAR(4) 	NOT NULL,
  	DESCRIPCION 		VARCHAR(40) 	NOT NULL
)
go

  
ALTER TABLE MODELO_RETENCION 
	ADD CONSTRAINT XPK_MODELORETENCION
		PRIMARY KEY (MODELO_RETENCION)
go
 

 CREATE TABLE MONEDA (
        MONEDA		VARCHAR(4)  NOT NULL,
        NOMBRE		VARCHAR(40) NOT NULL,
        CODIGO_ISO 	VARCHAR(4)  NULL
 )
go
 
 
 ALTER TABLE MONEDA
        ADD CONSTRAINT MONEDAPK PRIMARY KEY NONCLUSTERED (MONEDA)
go
 
 
 CREATE TABLE MONEDA_HIST (
        MONEDA               VARCHAR(4) 	NOT NULL,
        FECHA                DATETIME 		NOT NULL,
        USUARIO              VARCHAR(25) 	NOT NULL,
        MONTO                DECIMAL(28,8) 	NOT NULL
 )
go
 
 
 ALTER TABLE MONEDA_HIST
        ADD CONSTRAINT MONEDA_HISTPK PRIMARY KEY NONCLUSTERED (MONEDA, 
               FECHA)
go

CREATE TABLE NCF_CONSECUTIVO( 
	PREFIJO 		VARCHAR(50) 	NOT NULL,
  	DESCRIPCION 		VARCHAR(70) 	NOT NULL,
  	ULTIMO_VALOR 		VARCHAR(20) 	NOT NULL,
  	SECUENCIA_INICIAL 	VARCHAR(20) 	NOT NULL,
  	SECUENCIA_FINAL   	VARCHAR(20) 	NOT NULL,
  	ACTIVO 			VARCHAR(1) 	NOT NULL,
  	TIPO 			VARCHAR(6) 	NOT NULL,
  	USUARIO_CREACION 	VARCHAR(25) 	NULL,
  	USUARIO_MODIFICA 	VARCHAR(25)	NULL,  
  	USUARIO_AJUSTE 		VARCHAR(25)	NULL,
  	FECHAHORA_CREACION 	DATETIME 	NULL,
  	FECHAHORA_MODIFICA 	DATETIME	NULL,  
  	FECHAHORA_AJUSTE 	DATETIME	NULL,
  	TIPO_DOC 		VARCHAR(21) 	NOT NULL,
  	TIPO_CONTRIBUYENTE 	VARCHAR(1) 	NOT NULL,
  	SUGERIR 		VARCHAR(1) 	NULL   	 DEFAULT 'S',
  	NCF_UNICO 		VARCHAR(1) 	NOT NULL DEFAULT 'N',
	FECHA_VENCIMIENTO_CAI DATETIME NULL
)
go  	



ALTER TABLE NCF_CONSECUTIVO ADD CONSTRAINT XPKNCF_CONSECUTIVO
	PRIMARY KEY (PREFIJO) 
go	
	

CREATE TABLE NCF_CONSECUTIVO_USUARIO(
	PREFIJO		VARCHAR(50) NOT NULL,
	USUARIO		VARCHAR(25) NOT NULL,
	NCF_DEFAULT VARCHAR(1) DEFAULT 'N' NOT NULL,
	SECUENCIA 	INT 		NOT NULL
)
go

ALTER TABLE NCF_CONSECUTIVO_USUARIO ADD CONSTRAINT XPKNCF_CONSEC_USUARIO
		PRIMARY KEY (PREFIJO,USUARIO,SECUENCIA)
go


CREATE TABLE NCF_DOCUMENTO (
	NCF 			VARCHAR(50) 		NOT NULL,
	DOC_ROWPOINTER 		uniqueidentifier 	NOT NULL,
	MODULO 			VARCHAR(4)  		NOT NULL,
	TIPO_DOCUMENTO 		VARCHAR (6) 		NOT NULL,
	TABLA 			VARCHAR(20)  		NOT NULL,
	TIPO_ANULACION		VARCHAR(3)		NULL,
	FECHA_VENCE_SECUENCIA DATETIME          NULL,
	SECUENCIA       INT    					NULL
) 
go


ALTER TABLE NCF_DOCUMENTO ADD CONSTRAINT XPKNCF_DOCUMENTO 
	PRIMARY KEY (NCF,DOC_ROWPOINTER) 
go	

CREATE TABLE NCF_SECUENCIA 
( 
	PREFIJO 	VARCHAR(50) NOT NULL,
	SECUENCIA 	INT IDENTITY(1,1) NOT NULL,
	SECUENCIA_INICIAL VARCHAR(20) NOT NULL,
	SECUENCIA_FINAL VARCHAR(20) NOT NULL,
	FECHA_VENCE DATETIME NOT NULL,
	ULTIMO_VALOR VARCHAR(20) NULL
)
go


ALTER TABLE NCF_SECUENCIA 
	ADD CONSTRAINT NCFSECUENCIAPK 
		PRIMARY KEY NONCLUSTERED ( PREFIJO, SECUENCIA)
		
go


 
 CREATE TABLE NIT (
	NIT                  	VARCHAR(20) 	NOT NULL,
	RAZON_SOCIAL 			VARCHAR(150) NOT NULL,
	ALIAS 					VARCHAR(150) NULL,
	NOTAS                	TEXT 		NULL,	
	TIPO                 	VARCHAR(25) 	DEFAULT ('ND')	NULL,
	DIGITO_VERIFICADOR   	VARCHAR(10) 	NULL,
	USA_REPORTE_D151     	VARCHAR(1)  	NULL,
	ORIGEN					VARCHAR(1)  	NOT NULL DEFAULT('O'),
	NUMERO_DOC_NIT			VARCHAR(20) 	NULL,
	SUCURSAL				VARCHAR(20) 	NULL,
	PRIMER_NOMBRE			VARCHAR(60) 	NULL,
	SEGUNDO_NOMBRE			VARCHAR(60) 	NULL,
	PRIMER_APELLIDO			VARCHAR(60) 	NULL,
	SEGUNDO_APELLIDO		VARCHAR(60) 	NULL,
	TIPO_DOCUMENTO			VARCHAR(2) 	NULL,
	CLASE_DOCUMENTO			VARCHAR(5) 	NULL,
	DEPARTAMENTO			VARCHAR(12) 	NULL,
	MUNICIPIO				VARCHAR(12) 	NULL,
	PAIS					VARCHAR(4) 	NULL,
	EXTERIOR				VARCHAR(1) 	NULL,
	DETALLE_DIRECCION		INT 		NULL,
	DIRECCION				VARCHAR(3000) 	NULL,
	NATURALEZA				VARCHAR(1) 	NULL,
	ACTIVIDAD_ECONOMINA		VARCHAR(4) 	NULL,
	CORREO					VARCHAR(100) 	NULL,
	TELEFONO				VARCHAR(14)	NULL,
	CELULAR					VARCHAR(14)	NULL,
	ACTIVO 					VARCHAR(1) 	NOT NULL DEFAULT ('S'),
	TIPO_CONTRIBUYENTE 		VARCHAR(1) NULL, 
	NRC 					VARCHAR(20) NULL, 
	GIRO 					VARCHAR(40) NULL, 
	CATEGORIA 				VARCHAR(20) NULL, 
	DUI 					VARCHAR(12) NULL,
	TIPO_REGIMEN 			VARCHAR(1) NULL
 )
go
 
 
 ALTER TABLE NIT
        ADD CONSTRAINT XPKNIT PRIMARY KEY (NIT)
go
 
 
 CREATE TABLE NIVEL_PRECIO (
        NIVEL_PRECIO         VARCHAR(12) NOT NULL,
        MONEDA               VARCHAR(1) NOT NULL,
        CONDICION_PAGO       VARCHAR(4) NULL,
        ESQUEMA_TRABAJO      VARCHAR(1) NOT NULL,
        DESCUENTOS           VARCHAR(1) NOT NULL,
        SUGERIR_DESCUENTO    VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE NIVEL_PRECIO
        ADD CONSTRAINT NIVEL_PRECIOPK PRIMARY KEY NONCLUSTERED (
               NIVEL_PRECIO, MONEDA)
go
 
 
 CREATE TABLE PAGOS_PARCIALES (
        CONDICION_PAGO       VARCHAR(4) NOT NULL,
        CONSECUTIVO          smallint NOT NULL,
        DIAS_NETO_PARCIAL    int NOT NULL,
        PORC_MONTO           Decimal(28,8) NOT NULL
 )
go
 
 
 ALTER TABLE PAGOS_PARCIALES
        ADD CONSTRAINT XPKPAGOS_PARCIALES PRIMARY KEY (CONDICION_PAGO, 
               CONSECUTIVO)
go
 
 
 CREATE TABLE PAIS (
        PAIS                 VARCHAR(4) NOT NULL,
        DIRECCION            VARCHAR(10) NOT NULL,
        NOMBRE               VARCHAR(40) NOT NULL,
        CTR_VENTAS           VARCHAR(25) NULL,
        CTA_VENTAS           VARCHAR(25) NULL,
        CTR_DESC_GRAL        VARCHAR(25) NULL,
        CTA_DESC_GRAL        VARCHAR(25) NULL,
        CTR_COST_VENT        VARCHAR(25) NULL,
        CTA_COST_VENT        VARCHAR(25) NULL,
        CTR_DESC_LIN         VARCHAR(25) NULL,
        CTA_DESC_LIN         VARCHAR(25) NULL,
        CTR_COST_LIN         VARCHAR(25) NULL,
        CTA_COST_LIN         VARCHAR(25) NULL,
        CTR_GAST_COM         VARCHAR(25) NULL,
        CTA_GAST_COM         VARCHAR(25) NULL,
        CTR_CONTADO          VARCHAR(25) NULL,
        CTA_CONTADO          VARCHAR(25) NULL,
        CTR_CXC              VARCHAR(25) NULL,
        CTA_CXC              VARCHAR(25) NULL,
        CTR_LXC              VARCHAR(25) NULL,
        CTA_LXC              VARCHAR(25) NULL,
        CTR_PRONTO_PAG_CXC   VARCHAR(25) NULL,
        CTA_PRONTO_PAG_CXC   VARCHAR(25) NULL,
        CTR_INT_MORA_CXC     VARCHAR(25) NULL,
        CTA_INT_MORA_CXC     VARCHAR(25) NULL,
        CTR_RECIBOS_CXC      VARCHAR(25) NULL,
        CTA_RECIBOS_CXC      VARCHAR(25) NULL,
        CTR_DEBITO_CXC       VARCHAR(25) NULL,
        CTA_DEBITO_CXC       VARCHAR(25) NULL,
        CTR_CREDITO_CXC      VARCHAR(25) NULL,
        CTA_CREDITO_CXC      VARCHAR(25) NULL,
        CTR_IMPUESTO1_CXC    VARCHAR(25) NULL,
        CTA_IMPUESTO1_CXC    VARCHAR(25) NULL,
        CTR_IMPUESTO2_CXC    VARCHAR(25) NULL,
        CTA_IMPUESTO2_CXC    VARCHAR(25) NULL,
        CTR_RUBRO1_CXC       VARCHAR(25) NULL,
        CTA_RUBRO1_CXC       VARCHAR(25) NULL,
        CTR_RUBRO2_CXC       VARCHAR(25) NULL,
        CTA_RUBRO2_CXC       VARCHAR(25) NULL,
        CTR_ANTICIPO_CXC     VARCHAR(25) NULL,
        CTA_ANTICIPO_CXC     VARCHAR(25) NULL,
        CTR_LXP              VARCHAR(25) NULL,
        CTA_LXP              VARCHAR(25) NULL,
        CTR_CREDITO_CXP      VARCHAR(25) NULL,
        CTA_CREDITO_CXP      VARCHAR(25) NULL,
        CTR_DEBITO_CXP       VARCHAR(25) NULL,
        CTA_DEBITO_CXP       VARCHAR(25) NULL,
        CTR_CXP              VARCHAR(25) NULL,
        CTA_CXP              VARCHAR(25) NULL,
        CTR_PRONTO_PAG_CXP   VARCHAR(25) NULL,
        CTA_PRONTO_PAG_CXP   VARCHAR(25) NULL,
        CTR_COMISION_CXP     VARCHAR(25) NULL,
        CTA_COMISION_CXP     VARCHAR(25) NULL,
        CTR_IMPUESTO1_CXP    VARCHAR(25) NULL,
        CTA_IMPUESTO1_CXP    VARCHAR(25) NULL,
        CTR_IMPUESTO2_CXP    VARCHAR(25) NULL,
        CTA_IMPUESTO2_CXP    VARCHAR(25) NULL,
        CTR_RUBRO1_CXP       VARCHAR(25) NULL,
        CTA_RUBRO1_CXP       VARCHAR(25) NULL,
        CTR_RUBRO2_CXP       VARCHAR(25) NULL,
        CTA_RUBRO2_CXP       VARCHAR(25) NULL,
        CTR_ANTICIPO_CXP     VARCHAR(25) NULL,
        CTA_ANTICIPO_CXP     VARCHAR(25) NULL,
        CTR_DESC_BONIF       VARCHAR(25) NULL,
        CTA_DESC_BONIF       VARCHAR(25) NULL,
        CTR_DEV_VENTAS       VARCHAR(25) NULL,
        CTA_DEV_VENTAS       VARCHAR(25) NULL,
        CTR_INT_CORRIENTE    VARCHAR(25) NULL,        
		CTA_INT_CORRIENTE    VARCHAR(25) NULL,
		CODIGO_ISO 	     	 VARCHAR(4)  NULL,
		ETIQUETA_DIV_GEO1    VARCHAR(20) NULL,
		ETIQUETA_DIV_GEO2    VARCHAR(20) NULL,
		MONEDA		      	 VARCHAR(4)  NULL,
		CTR_VENTAS_EXEN 	 VARCHAR(25) NULL,
		CTA_VENTAS_EXEN 	 VARCHAR(25) NULL,
		CTR_AJUSTE_REDONDEO  VARCHAR(25) NULL,
		CTA_AJUSTE_REDONDEO  VARCHAR(25) NULL,
		ETIQUETA_DIV_GEO3    VARCHAR(20) NULL,
		ETIQUETA_DIV_GEO4    VARCHAR(20) NULL
 )
go
 
 
 ALTER TABLE PAIS
        ADD CONSTRAINT PAISPK PRIMARY KEY NONCLUSTERED (PAIS)
go
 
 
 CREATE TABLE PERIODO_CONTABLE (
        FECHA_FINAL          DATETIME NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        CONTABILIDAD         VARCHAR(1) NOT NULL,
        FIN_PERIODO_ANUAL    VARCHAR(1) NOT NULL,
        ESTADO               VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE PERIODO_CONTABLE
        ADD CONSTRAINT PERIODOCONTAPK PRIMARY KEY NONCLUSTERED (
               FECHA_FINAL, CONTABILIDAD)
go
 
 
 CREATE TABLE PREFERENCIA (
        USUARIO              VARCHAR(25) 	NOT NULL,
        ORIGEN               VARCHAR(4) 	NOT NULL,
        OPCION               VARCHAR(50) 	NOT NULL,
        PREFERENCIA1         VARCHAR(250) 	NULL,
        PREFERENCIA2         VARCHAR(250) 	NULL,
        PREFERENCIA3         VARCHAR(250) 	NULL,
        PREFERENCIA4         TEXT 		NULL
 )
go
 
 
 ALTER TABLE PREFERENCIA
        ADD CONSTRAINT PREFERENCIAPK PRIMARY KEY NONCLUSTERED (
               USUARIO, ORIGEN, OPCION)
go


CREATE TABLE REGIMENES
( 
	REGIMEN 		VARCHAR(12) 	NOT NULL,
	DESCRIPCION 		VARCHAR(40) 	NOT NULL,
	MODELO_RETENCION 	VARCHAR(4) 	NULL,
	IMP1_ASUMIDO_COMPRAS	VARCHAR(1) 	NOT NULL DEFAULT('N'),
	CENTRO_COSTO            VARCHAR(25) 	NULL,
	CUENTA_CONTABLE       	VARCHAR(25) 	NULL,
	CONSECUTIVO		VARCHAR(10) 	NULL
)
go

ALTER TABLE REGIMENES
         ADD CONSTRAINT REGIMENESPK PRIMARY KEY NONCLUSTERED
         	( REGIMEN )
go         	



CREATE TABLE REGION(
	REGION 	VARCHAR(4) 	NOT NULL,
	NOMBRE 	VARCHAR(40) 	NOT NULL,
	NOTAS 	VARCHAR(254) 	NULL
)
go


ALTER TABLE REGION
	ADD CONSTRAINT PK_REGION 
		PRIMARY KEY NONCLUSTERED ( REGION )
go

CREATE TABLE REGION_DET (
	REGION 	VARCHAR(4) NOT NULL,
	PAIS 	VARCHAR(4) NOT NULL
)
go

ALTER TABLE REGION_DET
	ADD CONSTRAINT PK_REGIONDET 
		PRIMARY KEY NONCLUSTERED ( REGION, PAIS )
go		

CREATE TABLE REPORTE_REPX(
	NOMBRE 		VARCHAR(100) 		NOT NULL,
	ARCHIVO 	VARCHAR(max) 		NULL,
	DESCRIPCION 	VARCHAR(200) 		NULL,
	MODULO VARCHAR(10) DEFAULT 'RP'
)
go


ALTER TABLE REPORTE_REPX ADD 
	CONSTRAINT PK_REPORTE PRIMARY KEY (NOMBRE)
go
 
 CREATE TABLE RESPONSABLE (
        RESPONSABLE          VARCHAR(20) NOT NULL,
        NOMBRE               VARCHAR(50) NOT NULL,
        EMPLEADO             VARCHAR(20) NULL
 )
go
 
 
 ALTER TABLE RESPONSABLE
        ADD CONSTRAINT XPKRESPONSABLE PRIMARY KEY (RESPONSABLE)
go
 

 CREATE TABLE RETENCIONES (
        CODIGO_RETENCION     	VARCHAR(4) 	NOT NULL,
        DESCRIPCION          	VARCHAR(40) 	NOT NULL,
        PORCENTAJE           	Decimal(28,8) 	NOT NULL,
        TIPO                 	VARCHAR(1) 	NOT NULL,
        APLICA_MONTO         	VARCHAR(1) 	NOT NULL,
        APLICA_SUBTOTAL      	VARCHAR(1) 	NOT NULL,
        APLICA_SUB_DESC      	VARCHAR(1) 	NOT NULL,
        APLICA_IMPUESTO1     	VARCHAR(1) 	NOT NULL,
        APLICA_IMPUESTO2     	VARCHAR(1) 	NOT NULL,
        APLICA_RUBRO1        	VARCHAR(1) 	NOT NULL,
        APLICA_RUBRO2        	VARCHAR(1) 	NOT NULL,
        ESTADO               	VARCHAR(1) 	NOT NULL,
        MONTO_MINIMO         	DECIMAL(28,8) 	NOT NULL,
        CTR_RETENCION        	VARCHAR(25) 	NULL,
        CTA_RETENCION        	VARCHAR(25) 	NULL,
        RET_POR_ARTICULO     	VARCHAR(1)	NULL DEFAULT ('N'), 
		ES_AUTORETENEDOR     	VARCHAR(1) 	NULL DEFAULT ('N'), 
		CLASIFICACION_ART    	VARCHAR(12) 	NULL,
		CTR_AUTORETENCION    	VARCHAR(25) 	NULL,
		CTA_AUTORETENCION    	VARCHAR(25) 	NULL,
		TIPO_EXCEPCION 	     	VARCHAR(1)  	NOT NULL DEFAULT('D'),
		NOAPLICA_PROV_AUTO   	VARCHAR(1)  	NOT NULL DEFAULT('N'),
		APLICA_RETENCION     	VARCHAR(1)  	NOT NULL DEFAULT('N'),
		RETENCION_BASE	     	VARCHAR(4)  	NULL,
		APLICA_IMP1_DESC		VARCHAR(1) 	NOT NULL DEFAULT('N'),
		APLICA_IMP1_NODESC		VARCHAR(1) 	NOT NULL DEFAULT('N'),
		TIPO_DOC_CC_CREDITO 	VARCHAR (4000) 	NULL,
		TIPO_DOC_CC_DEBITO 		VARCHAR (4000) 	NULL,
		TIPO_DOC_CP_CREDITO 	VARCHAR (4000) 	NULL,
		TIPO_DOC_CP_DEBITO 		VARCHAR (4000) 	NULL,
		UTILIZA_TARIFA_UVT		VARCHAR(1) 	NOT NULL DEFAULT('N'),
		CONSEC_RET_VENTA 		VARCHAR(10) 	NULL,
		CONSEC_RET_COMPRA 		VARCHAR(10) 	NULL,
		PER_GENERAR_RET_CERO 	VARCHAR(1) 	NOT NULL DEFAULT('N'),
		TIPO_APLI_CANCELAR 		VARCHAR(1) 	NOT NULL DEFAULT('T'),
		CODIGO_INGRESO 			VARCHAR (4) NULL,
        U_IMPUESTO_SAT          VARCHAR(3) NULL,
		TIPO_IMPUESTO			VARCHAR (4)  NULL,
		U_CLAVE_RET 			VARCHAR(2) NULL,
		U_IMPUESTO 				VARCHAR(4) NULL
 )
go
 
 
 ALTER TABLE RETENCIONES
        ADD CONSTRAINT XPKRETENCIONES PRIMARY KEY (CODIGO_RETENCION)
go
  
 
 
 
 CREATE TABLE RUTA (
        RUTA                 VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL
 )
go
 
 
 ALTER TABLE RUTA
        ADD CONSTRAINT RUTAPK PRIMARY KEY NONCLUSTERED (RUTA)
go

CREATE TABLE TABLA_UDF (
        TABLA		VARCHAR(18)	NOT NULL,
        UDF             VARCHAR(30) 	NOT NULL,
	DESCRIPCION	VARCHAR(30)	NOT NULL,
       	TIPO            VARCHAR(1) 	NOT NULL,
       	ORDEN           int	 	NOT NULL,
        PERMITE_NULOS   VARCHAR(1) 	NOT NULL,
	VALOR_DEFAULT 	VARCHAR(254)	NULL,
       	SQL       	VARCHAR(4000)	NULL,
       	TIPO_FUENTE 	VARCHAR(1) 	NOT NULL,
	UDT  		VARCHAR(72) 	NULL,
	LARGO		SMALLINT 	NULL
)
go

ALTER TABLE TABLA_UDF 
       ADD CONSTRAINT XPKTABLAUDF 
       		PRIMARY KEY (TABLA, UDF)
go     

CREATE TABLE TIPO_ANULACIONES ( 
	TIPO_ANULACION		VARCHAR(3) 		NOT NULL,
  	DESCRIPCION 		VARCHAR(50)		NOT NULL
)
go

  
ALTER TABLE TIPO_ANULACIONES 
	ADD CONSTRAINT PK_TIPO_ANULACION
		PRIMARY KEY (TIPO_ANULACION) 
go		


 
 
 CREATE TABLE TIPO_CAMBIO (
        TIPO_CAMBIO          VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL
 )
go
 
 
 ALTER TABLE TIPO_CAMBIO
        ADD CONSTRAINT TIPO_CAMBIOPK PRIMARY KEY NONCLUSTERED (
               TIPO_CAMBIO)
go
 
 
 CREATE TABLE TIPO_CAMBIO_HIST (
        TIPO_CAMBIO          VARCHAR(4) 	NOT NULL,
        FECHA                DATETIME 		NOT NULL,
        USUARIO              VARCHAR(25) 	NOT NULL,
        MONTO                DECIMAL(28,8) 	NOT NULL
 )
go
 
 
 ALTER TABLE TIPO_CAMBIO_HIST
        ADD CONSTRAINT TIPO_CAMBIO_HISPK PRIMARY KEY NONCLUSTERED (
               TIPO_CAMBIO, FECHA)
go

CREATE TABLE TIPO_IMPUESTO(
	TIPO_IMPUESTO VARCHAR (4) NOT NULL, 
	DESCRIPCION VARCHAR (40) NOT NULL
)
go

ALTER TABLE TIPO_IMPUESTO 
	ADD CONSTRAINT PKTIPIMP 
		PRIMARY KEY (TIPO_IMPUESTO)
go

CREATE TABLE TIPO_NIT(     
	TIPO	VARCHAR(25) NOT NULL,
  	MASCARA	VARCHAR(20) NOT NULL,
	DESCRIPCION 	VARCHAR(25) NULL,
	U_TIPO_DOCUMENTO_IDENTIDAD VARCHAR(4)
)
go

ALTER TABLE TIPO_NIT
	ADD CONSTRAINT XPK_TIPONIT 
	        PRIMARY KEY NONCLUSTERED (TIPO)
go	        
 
 
CREATE TABLE TIPO_TARJETA (
        TIPO_TARJETA         	VARCHAR(12) 	NOT NULL,
        TIPO_COBRO 		VARCHAR(1) 	NOT NULL DEFAULT ('M'),
        ASSEMBLY_INVOCACION 	VARCHAR(100) 	NULL
 )
go
 
 
 ALTER TABLE TIPO_TARJETA
        ADD CONSTRAINT TIPO_TARJETAPK PRIMARY KEY NONCLUSTERED (
               TIPO_TARJETA)
go


CREATE TABLE U_TIPO_DOCUMENTO(
	U_CODIGO 	varchar(4) 	NOT NULL,
	U_DESCRIP 	varchar(249) 	NULL )
go
	
CREATE TABLE U_ACTIV_ECONOMICA(
	U_CODIGO 	varchar(4) 	NOT NULL,
	U_DESCRIP 	varchar(249) 	NULL	)
go
 
 
 CREATE TABLE UBICACION (
        UBICACION            VARCHAR(8) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL
 )
go
 
 
 ALTER TABLE UBICACION
        ADD CONSTRAINT UBICACIONPK PRIMARY KEY NONCLUSTERED (
               UBICACION)
go
 
 
 CREATE TABLE UNIDAD (
        UNIDAD               VARCHAR(15) NOT NULL,
        DESCRIPCION          VARCHAR(40) NULL
 )
go
 
 
 ALTER TABLE UNIDAD
        ADD CONSTRAINT XPKUNIDAD PRIMARY KEY (UNIDAD)
go
 
 
 CREATE TABLE USUARIO_BODEGA (
        BODEGA               VARCHAR(4) 	NOT NULL,
        USUARIO              VARCHAR(25) 	NOT NULL
 )
go
 
 
 ALTER TABLE USUARIO_BODEGA
        ADD CONSTRAINT XPKUSUARIO_BODEGA PRIMARY KEY (BODEGA, USUARIO)
go
 
 
 CREATE TABLE VENDEDOR (
        VENDEDOR             VARCHAR(4) NOT NULL,
        NOMBRE               VARCHAR(40) NOT NULL,
        EMPLEADO             VARCHAR(20) NOT NULL,
        COMISION             DECIMAL(28,8) NOT NULL,
        CTR_COMISION         VARCHAR(25) NULL,
        CTA_COMISION         VARCHAR(25) NULL,
        E_MAIL               VARCHAR(249) NULL,
        ACTIVO               VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE VENDEDOR
        ADD CONSTRAINT VENDEDORPK PRIMARY KEY NONCLUSTERED (VENDEDOR)
go
 
 
 CREATE TABLE ZONA (
        ZONA                 VARCHAR(4) NOT NULL,
        NOMBRE               VARCHAR(40) NOT NULL
 )
go
 
 
 ALTER TABLE ZONA
        ADD CONSTRAINT ZONAPK PRIMARY KEY NONCLUSTERED (ZONA)
go

CREATE TABLE erpadmin.USUARIO_API
(
 CORREO_ELECTRONICO VARCHAR(249) NOT NULL,
 DESCRIPCION		VARCHAR(200),
 USUARIO_ERP   		VARCHAR(25),
 CLAVE    			VARCHAR(200)
)
go


ALTER TABLE erpadmin.USUARIO_API 
        ADD CONSTRAINT XPKUSUARIO_API 
			PRIMARY KEY NONCLUSTERED (CORREO_ELECTRONICO)
go			
