
 
 ALTER TABLE ASIENTOS_CHEQUE
        ADD CONSTRAINT ACHQCTAC
               FOREIGN KEY (CTR_CONTABLE, CTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ASIENTOS_CHEQUE
        ADD CONSTRAINT ACHQTIPO
               FOREIGN KEY (TIPO_ASIENTO)
                              REFERENCES TIPO_ASIENTO
go
 
 
 ALTER TABLE ASIENTOS_CHEQUE
        ADD CONSTRAINT ASCHQINT
               FOREIGN KEY (CHEQUE_INTERNO)
                              REFERENCES CHEQUE
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE CHEQUE
        ADD CONSTRAINT CHQCTAB
               FOREIGN KEY (CUENTA_BANCO)
                              REFERENCES CUENTA_BANCARIA
go
 
 
 ALTER TABLE CHEQUE
        ADD CONSTRAINT USUARIOULTAPL_CHEQ
               FOREIGN KEY (USUARIO_ULT_APLIC)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CHEQUE
        ADD CONSTRAINT USUARIOCREA_CHEQ
               FOREIGN KEY (USUARIO_CREACION)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CHEQUE
        ADD CONSTRAINT USUARIOMODIF_CHEQ
               FOREIGN KEY (USUARIO_MODIFIC)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CHEQUE
        ADD CONSTRAINT SUBTIPODOC_CB_CHEQ
               FOREIGN KEY (TIPO, SUBTIPO)
                              REFERENCES SUBTIPO_DOC_CB
go
 
 
 ALTER TABLE CHEQUE
        ADD CONSTRAINT CHQNIT
               FOREIGN KEY (CONTRIBUYENTE)
                              REFERENCES NIT
go
 
 
 ALTER TABLE CONCILIACION
        ADD CONSTRAINT USUARIO_APR_CONCIL
               FOREIGN KEY (USUARIO_APROBAC)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CONCILIACION
        ADD CONSTRAINT USUARIO_MOD_CONCIL
               FOREIGN KEY (USUARIO_MODIFIC)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CONCILIACION
        ADD CONSTRAINT USUARIO_CREA_CONCI
               FOREIGN KEY (USUARIO_CREACION)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CONCILIACION
        ADD CONSTRAINT CONCILIA_CTABA
               FOREIGN KEY (CUENTA_BANCO)
                              REFERENCES CUENTA_BANCARIA
go

ALTER TABLE CUENTA_BANCARIA
         ADD CONSTRAINT CTABCCTA
         	FOREIGN KEY  ( CTR_TRANSF_IC , CTA_TRANSF_IC)
         		REFERENCES CENTRO_CUENTA ( CENTRO_COSTO,CUENTA_CONTABLE)	
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT USUARIO_MOD_CTAB
               FOREIGN KEY (USUARIO_MODIFIC)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT USUARIO_CREA_CTAB
               FOREIGN KEY (USUARIO_CREACION)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT CTAB_AJUSTE_DEB
               FOREIGN KEY (CTR_AJUSTE_DEB, CTA_AJUSTE_DEB)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT CTAB_AJUSTE_CRED
               FOREIGN KEY (CTR_AJUSTE_CRED, CTA_AJUSTE_CRED)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT CTAB_LIQDEB
               FOREIGN KEY (CTR_LIQUIDAR_DEB, CTA_LIQUIDAR_DEB)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT CTAB_LIQCRED
               FOREIGN KEY (CTR_LIQUIDAR_CRED, CTA_LIQUIDAR_CRED)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT CTABCTAR
               FOREIGN KEY (CTR_CIERRE_CRED, CTA_CIERRE_CRED)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT CTABCTAD
               FOREIGN KEY (CTR_CIERRE_DEB, CTA_CIERRE_DEB)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT CTABCTAC
               FOREIGN KEY (CTR_CONTABLE, CTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT CTABEFIN
               FOREIGN KEY (ENTIDAD_FINANCIERA)
                              REFERENCES ENTIDAD_FINANCIERA
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT CTABMOND
               FOREIGN KEY (MONEDA)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT CTABCTRANSF
               FOREIGN KEY (CTR_GASTO_TRANSF, CTA_GASTO_TRANSF)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT CTABCTRANSF_IC
               FOREIGN KEY (CTR_TRANSF_IC, CTA_TRANSF_IC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 
ALTER TABLE CUENTA_BANCARIA 
        ADD CONSTRAINT TIPCTA_TCTA
               FOREIGN KEY (TIPO_CUENTA)
                              REFERENCES TIPO_CUENTA
go                              
 
ALTER TABLE CUENTA_BANCARIA
         ADD CONSTRAINT CUENTABANCCTRCUENTA
         	FOREIGN KEY  ( CTR_DOC_GP, CTA_DOC_GP )
         		REFERENCES CENTRO_CUENTA ( CENTRO_COSTO, CUENTA_CONTABLE )
go	
 
 
ALTER TABLE DET_TIPOSERVICIO_CB
	ADD CONSTRAINT DETTIPOSERVICFASEPY
		FOREIGN KEY (PROYECTO,FASE)
			REFERENCES FASE_PY
go			


ALTER TABLE DET_TIPOSERVICIO_CB
	ADD CONSTRAINT DETTIPOSERVICMOVBANC
		FOREIGN KEY (CUENTA_BANCO,TIPO_DOCUMENTO,NUMERO)
			REFERENCES MOV_BANCOS
                              	ON DELETE CASCADE
go                              	
 
 
 
 ALTER TABLE DET_TRANS_CB
        ADD CONSTRAINT TRANDET
               FOREIGN KEY (CUENTA_ORIGEN, TIPO_ORIGEN, NUMERO_ORIGEN)
                              REFERENCES TRANSFERENCIA_CB
go



ALTER TABLE DET_TRANS_CB  	
        ADD CONSTRAINT DETTRANSCBENTFIN
               FOREIGN KEY (ENTIDAD_FINANCIERA)
                              REFERENCES ENTIDAD_FINANCIERA
go                              


 ALTER TABLE DET_TRANS_CB  	
        ADD CONSTRAINT DETTRANSCBMONEDA
               FOREIGN KEY (MONEDA)
                              REFERENCES MONEDA
go                              
 
 ALTER TABLE GLOBALES_CB
        ADD CONSTRAINT GBCBPAQ
               FOREIGN KEY (PAQUETE)
                              REFERENCES PAQUETE
go
 
 
 ALTER TABLE GLOBALES_CB
        ADD CONSTRAINT GBCBTASN
               FOREIGN KEY (TIPO_ASIENTO)
                              REFERENCES TIPO_ASIENTO
go


ALTER TABLE HIST_DIFCAM_CB
         ADD CONSTRAINT USUARHISTDFCB
         	FOREIGN KEY  ( usuario_auditoria)
         		REFERENCES ERPADMIN.USUARIO(USUARIO)
go

ALTER TABLE MOV_BANCOS        
         ADD CONSTRAINT USUARMOVBANUSRANUL
         	FOREIGN KEY  ( USUARIO_ANULADO )
         		REFERENCES ERPADMIN.USUARIO(USUARIO)
go         		
 
 
 ALTER TABLE MOV_BANCOS
        ADD CONSTRAINT CONCIL_MOVBANCOCONACL
               FOREIGN KEY (CUENTA_BANCO, CONCIL_ACLARACION)
                              REFERENCES CONCILIACION
go
 
 
 ALTER TABLE MOV_BANCOS
        ADD CONSTRAINT CONCIL_MOVBANCO
               FOREIGN KEY (CUENTA_BANCO, CONCILIACION)
                              REFERENCES CONCILIACION
go
 
 
 ALTER TABLE MOV_BANCOS
        ADD CONSTRAINT DOCREP_DOCAJUSTE
               FOREIGN KEY (DOC_AJUSTE)
                              REFERENCES MOV_REPORTADOS
go
 
 
 ALTER TABLE MOV_BANCOS
        ADD CONSTRAINT DOCREP_MOVBAN
               FOREIGN KEY (DOC_REPORTADO)
                              REFERENCES MOV_REPORTADOS
go
 
 
 ALTER TABLE MOV_BANCOS
        ADD CONSTRAINT MVBNPROV
               FOREIGN KEY (PROVEEDOR)
                              REFERENCES PROVEEDOR
go
 
 
 ALTER TABLE MOV_BANCOS
        ADD CONSTRAINT MVBCCTAB
               FOREIGN KEY (CUENTA_BANCO)
                              REFERENCES CUENTA_BANCARIA
go
 
 
 ALTER TABLE MOV_BANCOS
        ADD CONSTRAINT SUBTIPO_MOVBANCOCB
               FOREIGN KEY (TIPO_DOCUMENTO, SUBTIPO)
                              REFERENCES SUBTIPO_DOC_CB
go
 
 
 ALTER TABLE MOV_BANCOS
        ADD CONSTRAINT USUARIOCREA_MOV
               FOREIGN KEY (USUARIO_CREACION)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE MOV_BANCOS
        ADD CONSTRAINT USUARIOMODIF_MOV
               FOREIGN KEY (USUARIO_MODIFIC)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE MOV_BANCOS
        ADD CONSTRAINT MVBCNIT
               FOREIGN KEY (CONTRIBUYENTE)
                              REFERENCES NIT
go
 

ALTER TABLE MOV_BANCOS
	ADD CONSTRAINT MOVBNCTIPOASNT
		FOREIGN KEY (TIPO_ASIENTO)
			REFERENCES TIPO_ASIENTO(TIPO_ASIENTO)
go			
			

ALTER TABLE MOV_BANCOS
	ADD CONSTRAINT MOVBNCPAQUETE
		FOREIGN KEY (PAQUETE)
			REFERENCES PAQUETE(PAQUETE)
go			


ALTER TABLE MOV_BANCOS
	ADD CONSTRAINT MOVBANCOS_IMPUESTO1
		FOREIGN KEY (COD_IMPUESTO1)
			REFERENCES IMPUESTO (IMPUESTO)
go


ALTER TABLE MOV_PROCESADOS
         ADD CONSTRAINT MOVPROCCTABAN
         	FOREIGN KEY  ( CUENTA_BANCO )
         		REFERENCES CUENTA_BANCARIA ( CUENTA_BANCO )
go         

ALTER TABLE MOV_PROCESADOS
         ADD CONSTRAINT MOVPROCUSUARIO
         	FOREIGN KEY  ( USUARIO_PROCESA )
         		REFERENCES ERPADMIN.USUARIO ( USUARIO )
go 

 
 ALTER TABLE MOV_REPORTADOS
        ADD CONSTRAINT DOCREP_CONCILIACIO
               FOREIGN KEY (CUENTA_BANCO, CONCILIACION)
                              REFERENCES CONCILIACION
go
 
 
 ALTER TABLE MOV_REPORTADOS
        ADD CONSTRAINT DOCREP_CTABA
               FOREIGN KEY (CUENTA_BANCO)
                              REFERENCES CUENTA_BANCARIA
go
 
 
 ALTER TABLE MOV_REPORTADOS
        ADD CONSTRAINT USUA_MOD_DOCREP
               FOREIGN KEY (USUARIO_MODIFIC)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE MOV_REPORTADOS
        ADD CONSTRAINT USUA_CREA_DOCREP
               FOREIGN KEY (USUARIO_CREACION)
                              REFERENCES ERPADMIN.USUARIO
go

 ALTER TABLE MOV_REPORTADOS
        ADD CONSTRAINT DOCREP_DOCCOMPENSA
               FOREIGN KEY (DOC_COMPENSAC)
                              REFERENCES MOV_REPORTADOS
go

ALTER TABLE SUBTIPO_DOC_CB
        ADD CONSTRAINT SUBDOCCB_CTAC
               FOREIGN KEY (CENTRO_COSTO, CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go                              
 
 
ALTER TABLE SUBTIPO_DOC_CB
	ADD CONSTRAINT SUBDOCCBTIPOASNT
		FOREIGN KEY (TIPO_ASIENTO)
			REFERENCES TIPO_ASIENTO(TIPO_ASIENTO)
go			
			

ALTER TABLE SUBTIPO_DOC_CB
	ADD CONSTRAINT SUBDOCCBPAQUETE
		FOREIGN KEY (PAQUETE)
			REFERENCES PAQUETE(PAQUETE)
go			
 
 
 
 ALTER TABLE TRANSFERENCIA_CB
        ADD CONSTRAINT MOVTRAN
               FOREIGN KEY (CUENTA_ORIGEN, TIPO_ORIGEN, NUMERO_ORIGEN)
                              REFERENCES MOV_BANCOS
go
 
 
 
ALTER TABLE TIPO_SERVICIO_CB
	ADD CONSTRAINT TIPOSERVICBCTRCTA
		FOREIGN KEY (CENTRO_COSTO,CUENTA_CONTABLE)
			REFERENCES CENTRO_CUENTA
go