 
 CREATE TABLE ASIENTOS_CHEQUE (
        CHEQUE_INTERNO       int 		NOT NULL,
        CONSECUTIVO          int 		NOT NULL,
        CTR_CONTABLE         VARCHAR(25) 	NOT NULL,
        CTA_CONTABLE         VARCHAR(25) 	NOT NULL,
        TIPO_ASIENTO         VARCHAR(4) 	NOT NULL,
        FECHA                DATETIME 		NOT NULL,
        REFERENCIA           VARCHAR(249) 	NOT NULL,
        CONTABILIDAD         VARCHAR(1)		NOT NULL,
        DEBITO               DECIMAL(28,8) 	NULL,
        CREDITO              DECIMAL(28,8) 	NULL
 )
go
 
 
 ALTER TABLE ASIENTOS_CHEQUE
        ADD CONSTRAINT ASIENTOS_CHEQUEPK PRIMARY KEY NONCLUSTERED (
               CHEQUE_INTERNO, CONSECUTIVO)
go
 
 
 CREATE TABLE CHEQUE (
        CHEQUE_INTERNO       int 		NOT NULL,
        CUENTA_BANCO         VARCHAR(20) 	NOT NULL,
        TIPO                 VARCHAR(3) 	NULL,
        SUBTIPO              smallint 		NULL,
        PAGADERO_A           VARCHAR(150) 	NOT NULL,
        REFERENCIA           VARCHAR(249) 	NOT NULL,
        MONTO                DECIMAL(28,8) 	NOT NULL,
        USUARIO_CREACION     VARCHAR(25) 	NOT NULL,
        FCH_HORA_MODIFIC     DATETIME 		NULL,
        USUARIO_MODIFIC      VARCHAR(25) 	NULL,
        FCH_HORA_ULT_APLIC   DATETIME 		NULL,
        RECURRENTE           VARCHAR(1) 	NOT NULL,
        CONCEPTO             TEXT 		NULL,
        CONTRIBUYENTE        VARCHAR(20) 	NULL,
        SELECCIONADO         VARCHAR(1) 	NOT NULL,
        FCH_HORA_CREACION    DATETIME 		NOT NULL,
        USUARIO_ULT_APLIC    VARCHAR(25) 	NULL,
        RESPONSABLE_SOLICI   VARCHAR(100)  	NULL,
        ESTADO_SOLICITUD     VARCHAR(1) 	NOT NULL,
        ORIGEN_SOLICITUD     VARCHAR(40) 	NOT NULL,
        DOCUMENTO_GLOBAL     VARCHAR(50) 	NULL
 )
go
 
 
 ALTER TABLE CHEQUE
        ADD CONSTRAINT XPKCHEQUE PRIMARY KEY NONCLUSTERED (
               CHEQUE_INTERNO)
go
 
 
 CREATE TABLE CONCILIACION (
        CUENTA_BANCO         VARCHAR(20) 	NOT NULL,
        CONCILIACION         int 		NOT NULL,
        FECHA_INICIAL        DATETIME 		NOT NULL,
        FECHA_FINAL          DATETIME 		NOT NULL,
        SALDO_LIBROS         DECIMAL(28,8) 	NULL,
        SALDO_BANCOS         DECIMAL(28,8) 	NULL,
        CREDITOS_TRANSITO    DECIMAL(28,8) 	NULL,
        DEBITOS_TRANSITO     DECIMAL(28,8) 	NULL,
        CREDITOS_CONCIL      DECIMAL(28,8) 	NULL,
        DEBITOS_CONCIL       DECIMAL(28,8) 	NULL,
        CREDITOS_SIN_DIF     DECIMAL(28,8) 	NULL,
        DEBITOS_SIN_DIF      DECIMAL(28,8) 	NULL,
        CREDITOS_CON_AJUST   DECIMAL(28,8) 	NULL,
        DEBITOS_CON_AJUST    DECIMAL(28,8) 	NULL,
        CREDITOS_AJUSTES     DECIMAL(28,8) 	NULL,
        DEBITOS_AJUSTES      DECIMAL(28,8) 	NULL,
        CREDITOS_LIQUIDAR    DECIMAL(28,8) 	NULL,
        DEBITOS_LIQUIDAR     DECIMAL(28,8) 	NULL,
        CREDITOS_ACLARAR     DECIMAL(28,8) 	NULL,
        DEBITOS_ACLARAR      DECIMAL(28,8) 	NULL,
        CREDITOS_ACLARA_EF   DECIMAL(28,8) 	NULL,
        DEBITOS_ACLARA_EF    DECIMAL(28,8) 	NULL,
        CREDITOS_ACLARA_CB   DECIMAL(28,8) 	NULL,
        DEBITOS_ACLARA_CB    DECIMAL(28,8) 	NULL,
        ESTADO               VARCHAR(1) 	NOT NULL,
        NOTAS                TEXT 		NULL,
        FCH_HORA_CREACION    DATETIME 		NOT NULL,
        USUARIO_CREACION     VARCHAR(25) 	NOT NULL,
        FCH_HORA_MODIFIC     DATETIME 		NULL,
        USUARIO_MODIFIC      VARCHAR(25) 	NULL,
        FCH_HORA_APROBAC     DATETIME 		NULL,
        USUARIO_APROBAC      VARCHAR(25) 	NULL
 )
go
 
 
 ALTER TABLE CONCILIACION
        ADD CONSTRAINT XPKCONCILIACION PRIMARY KEY (CUENTA_BANCO, 
               CONCILIACION)
go
 
 
 CREATE TABLE CUENTA_BANCARIA (
        CUENTA_BANCO         	VARCHAR(20)	NOT NULL,
        NOMBRE               	VARCHAR(40)	NOT NULL,
        ENTIDAD_FINANCIERA   	VARCHAR(8) 	NOT NULL,
        MONEDA               	VARCHAR(4) 	NOT NULL,
        DIRECCION            	VARCHAR(90)	NOT NULL,
        TELEFONO1            	VARCHAR(15)	NOT NULL,
        TELEFONO2            	VARCHAR(15)	NOT NULL,
        CONTACTO             	VARCHAR(40)	NOT NULL,
        CARGO                	VARCHAR(40)	NOT NULL,
        FORMATO              	VARCHAR(128) 	NOT NULL,
        FECHA_ULT_MOV        	DATETIME 	NOT NULL,
        SALDO                	DECIMAL(28,8) 	NOT NULL,
        SALDO_BANCOS         	DECIMAL(28,8) 	NOT NULL,
        POSICION_DE_CAJA     	DECIMAL(28,8) 	NOT NULL,
        SALDO_ANTERIOR       	DECIMAL(28,8) 	NOT NULL,
        TIPO_CAMBIO_LOCAL    	DECIMAL(28,8) 	NOT NULL,
        TIPO_CAMBIO_DOLAR    	DECIMAL(28,8) 	NOT NULL,
        ACTIVA               	VARCHAR(1) 	NOT NULL,
        ULTIMO_DEPOSITO      	decimal(28,0) 	NOT NULL,
        ULTIMA_TEFCR         	decimal(28,0) 	NOT NULL,
        LIMITE_SOBREGIRO     	DECIMAL(28,8) 	NOT NULL,
        CTR_CONTABLE         	VARCHAR(25) 	NULL,
        CTA_CONTABLE         	VARCHAR(25) 	NULL,
        CTR_CIERRE_DEB       	VARCHAR(25) 	NULL,
        CTA_CIERRE_DEB       	VARCHAR(25) 	NULL,
        CTR_CIERRE_CRED      	VARCHAR(25) 	NULL,
        CTA_CIERRE_CRED      	VARCHAR(25) 	NULL,
        ULTIMA_NOTACR        	decimal(28,0) 	NOT NULL,
        ULTIMO_CHEQUE        	DECIMAL(28,8) 	NULL,
        ULTIMO_OTROCR        	decimal(28,0) 	NOT NULL,
        ULTIMA_TEFDB         	DECIMAL(28,8) 	NULL,
        ULTIMA_NOTADB        	decimal(28,0) 	NOT NULL,
        ULTIMO_OTRODB        	decimal(28,0) 	NOT NULL,
        ULTIMA_CONCIL        	int 		NULL,
        MODO_CONCILIAR       	VARCHAR(1) 	NOT NULL,
        IDIOMA_MON_LETRAS    	VARCHAR(1) 	NOT NULL,
        TIPO_CRED_AJUSTE     	VARCHAR(3) 	NULL,
        SUBTIPO_CRED_AJUST   	smallint 	NULL,
        TIPO_DEB_AJUSTE      	VARCHAR(3) 	NULL,
        SUBTIPO_DEB_AJUST    	smallint 	NULL,
        PERMITE_SOBREGIRO    	VARCHAR(1) 	NOT NULL,
        CTA_AJUSTE_CRED      	VARCHAR(25) 	NULL,
        FCH_HORA_CREACION    	DATETIME 	NOT NULL,
        USUARIO_CREACION     	VARCHAR(25) 	NOT NULL,
        CTR_AJUSTE_DEB       	VARCHAR(25) 	NULL,
        CTR_GASTO_TRANSF     	VARCHAR(25) 	NULL,
        CTA_AJUSTE_DEB       	VARCHAR(25) 	NULL,
        CTA_GASTO_TRANSF     	VARCHAR(25) 	NULL,
        CTR_LIQUIDAR_CRED    	VARCHAR(25) 	NULL,
        CTA_LIQUIDAR_CRED    	VARCHAR(25) 	NULL,
        CTR_LIQUIDAR_DEB     	VARCHAR(25) 	NULL,
        CTA_LIQUIDAR_DEB     	VARCHAR(25) 	NULL,
        CTR_AJUSTE_CRED      	VARCHAR(25) 	NULL,
        FCH_HORA_MODIFIC     	DATETIME 	NULL,
        USUARIO_MODIFIC      	VARCHAR(25)	NULL,
        PERMITE_TRANSF_IC    	VARCHAR(1) 	NOT NULL,
        CTA_TRANSF_IC        	VARCHAR(25)	NULL,
        CTR_TRANSF_IC        	VARCHAR(25)	NULL,
        RUBRO1_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO2_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO3_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO4_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO5_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO6_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO7_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO8_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO9_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO10_CTABANCO     	VARCHAR(40)	NULL,
        CONSE_CHEQUE 	     	VARCHAR(10)	NULL,
		CONSE_TEF 	     		VARCHAR(10)	NULL,
		TIPO_CUENTA	     		VARCHAR(12) 	NULL,
		CTR_DOC_GP 				VARCHAR(25) 	NULL,
		CTA_DOC_GP 				VARCHAR(25) 	NULL,
		SALDO_TRANS 			DECIMAL(28,8) 	DEFAULT 0 	NOT NULL,
		SALDO_TRANS_LOCAL 		DECIMAL(28,8) 	DEFAULT 0 	NOT NULL,
		SALDO_TRANS_DOLAR 		DECIMAL(28,8) 	DEFAULT 0 	NOT NULL,
		PERMITE_DOC_GP			VARCHAR(1) 	DEFAULT 'N' 	NOT NULL,
		PARTICIPA_FLUJOCAJA		VARCHAR(1)  	DEFAULT 'N'	NOT NULL,
		CTA_ELECTRONICA 		VARCHAR(50) 	NULL
 )
go
 
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT XPKCUENTA_BANCARIA PRIMARY KEY NONCLUSTERED (
               CUENTA_BANCO)
go
 
 
 


CREATE TABLE DET_TIPOSERVICIO_CB(
       	CUENTA_BANCO         	VARCHAR(20) 		NOT NULL,
       	TIPO_DOCUMENTO       	VARCHAR(3) 		NOT NULL,
	NUMERO			decimal(28)		NOT NULL,
       	TIPO_SERVICIO        	VARCHAR(10)		NOT NULL,
	CONSECUTIVO		INT IDENTITY(1,1)	NOT NULL,
       	PROYECTO             	VARCHAR(25) 		NULL,
       	FASE                 	VARCHAR(25) 		NULL,
       	MONTO_LOCAL	    	DECIMAL(28,8) 		NULL,
	MONTO_DOLAR	    	DECIMAL(28,8) 		NULL,
       	MONTO_BANCO	    	DECIMAL(28,8) 		NULL
)
go


ALTER TABLE DET_TIPOSERVICIO_CB
       ADD CONSTRAINT XPKDET_TIPOSERVICIO_CB 
     		PRIMARY KEY (CUENTA_BANCO,TIPO_DOCUMENTO,NUMERO,TIPO_SERVICIO,CONSECUTIVO)
go

 
 
 CREATE TABLE DET_TRANS_CB (
        CONSECUTIVO          	DECIMAL(28,8) 	NOT NULL,
        CUENTA_ORIGEN        	VARCHAR(20)	NOT NULL,
        TIPO_ORIGEN          	VARCHAR(3) 	NOT NULL,
        NUMERO_ORIGEN        	decimal(28,0) 	NOT NULL,
        CUENTA_DESTINO       	VARCHAR(50) 	NOT NULL,
        TIPO_DESTINO         	VARCHAR(3) 	NOT NULL,
        NUMERO_DESTINO       	decimal(28,0) 	NOT NULL,
        MONTO_COMISION       	DECIMAL(28,8) 	NULL,
        TIPO_CAMBIO          	DECIMAL(28,8) 	NULL,
        MONTO_ORIGEN         	DECIMAL(28,8) 	NOT NULL,
        MONTO_DESTINO        	DECIMAL(28,8) 	NOT NULL,
        COMPANIA_DESTINO     	VARCHAR(10) 	NOT NULL,
        TIPO_MOV	     	VARCHAR(1)  	NULL,	
		BENEFICIARIO	     	VARCHAR(150) 	NULL,
		CONTRIBUYENTE        	VARCHAR(20) 	NULL,
		CONCEPTO	     	VARCHAR(100) 	NULL,	
		ENTIDAD_FINANCIERA	VARCHAR(8)  	NULL,
		MONEDA			VARCHAR(4)  	NULL,
		RUBRO1_DETTRANS		VARCHAR(100) 	NULL,
		RUBRO2_DETTRANS		VARCHAR(100) 	NULL,
		RUBRO3_DETTRANS		VARCHAR(100) 	NULL,
		RUBRO4_DETTRANS		VARCHAR(100) 	NULL,
		RUBRO5_DETTRANS		VARCHAR(100) 	NULL,
		RUBRO6_DETTRANS		VARCHAR(100) 	NULL,
		RUBRO7_DETTRANS		VARCHAR(100) 	NULL,
		RUBRO8_DETTRANS		VARCHAR(100) 	NULL,
		RUBRO9_DETTRANS		VARCHAR(100) 	NULL,
		RUBRO10_DETTRANS	VARCHAR(100) 	NULL,
		CTR_CIERRE_TERCEROS	VARCHAR(25)  	NULL,
		CTA_CIERRE_TERCEROS	VARCHAR(25)  	NULL
 )
go
 
 
 ALTER TABLE DET_TRANS_CB
        ADD CONSTRAINT XPKDET_TRANS_CB PRIMARY KEY (CONSECUTIVO, 
               CUENTA_ORIGEN, TIPO_ORIGEN, NUMERO_ORIGEN)
go
 
 
 CREATE TABLE GLOBALES_CB (
        PAUSAR_EN_CHEQUES    VARCHAR(1) NOT NULL,
        FEC_ASIENTO_CHEQ     VARCHAR(1) NOT NULL,
        IMP_CHEQ_PANTALLA    VARCHAR(1) NOT NULL,
        TIPO_ASIENTO         VARCHAR(4) NULL,
        PAQUETE              VARCHAR(4) NULL,
        ASIENTO_DEP          VARCHAR(1) NULL,
        ASIENTO_NCR          VARCHAR(1) NULL,
        ASIENTO_OCR          VARCHAR(1) NULL,
        ASIENTO_CHQ          VARCHAR(1) NULL,
        ASIENTO_NDB          VARCHAR(1) NULL,
        ASIENTO_ODB          VARCHAR(1) NULL,
        ASIENTO_TEFDB        VARCHAR(1) NULL,
        ASIENTO_TEFCR        VARCHAR(1) NULL,
        FECHA_ULT_DIFCAMB    DATETIME NOT NULL,
        CONCIL_NOENTREGADO   VARCHAR(1) NOT NULL,
        DEFDOC_ENTREGADO     VARCHAR(1) NOT NULL,
        INTEGRACION_CONTA    VARCHAR(1) NOT NULL,
        MOD_APLIC_ASIENTO    smallint NOT NULL,
        TIPO_CONTA_OMISION   VARCHAR(1) NOT NULL,
        COPIARNOTASENASNT    VARCHAR(1) NOT NULL,
        MOSTRAR_CHQ_SUG      VARCHAR(1) NOT NULL,
        IMPRIMIR_MONTO_MON   VARCHAR(1) NOT NULL,
        CANT_LINEAS_ASNT     int NOT NULL,
        VALIDAR_DOC_ASNT     VARCHAR(1) NOT NULL,
        VER_CTAS_INACTIVAS   VARCHAR(1) NOT NULL,
        FORMA_CREACION       VARCHAR(1) NOT NULL,
        USARUBROS_CTABANCO	VARCHAR(1)  NULL,
        RUBRO1_CTABANCO		VARCHAR(60) NULL,
        RUBRO2_CTABANCO		VARCHAR(60) NULL,
        RUBRO3_CTABANCO		VARCHAR(60) NULL,
        RUBRO4_CTABANCO		VARCHAR(60) NULL,
        RUBRO5_CTABANCO		VARCHAR(60) NULL,
        RUBRO6_CTABANCO		VARCHAR(60) NULL,
        RUBRO7_CTABANCO		VARCHAR(60) NULL,
        RUBRO8_CTABANCO		VARCHAR(60) NULL,
        RUBRO9_CTABANCO		VARCHAR(60) NULL,
        RUBRO10_CTABANCO	VARCHAR(60) NULL
 )
go
 

CREATE TABLE HIST_DIFCAM_CB(
	id_hist 		UniqueIdentifier 	NOT NULL,
        usuario_auditoria 	VARCHAR(25)		NOT NULL,
	fecha_auditoria 	DATETIME		NOT NULL,
	fecha_proc		DATETIME		NOT NULL,
	cuenta_bancaria		VARCHAR(20)		NOT NULL,
	tipo_cambio_proc	DECIMAL(28,8)		NOT NULL,
	asiento_proc		VARCHAR(10)		NULL,
	dif_cam_local		DECIMAL(28,8)		NOT NULL,
	dif_cam_dolar		DECIMAL(28,8)		NOT NULL,
	tcamb_loc_doc_ant	DECIMAL(28,8) 		NOT NULL,
	tcamb_dol_doc_ant	DECIMAL(28,8) 		NOT NULL,
	tcamb_loc_doc_act	DECIMAL(28,8) 		NOT NULL,
	tcamb_dol_doc_act	DECIMAL(28,8) 		NOT NULL,
	cuenta_contable		VARCHAR(25)		NULL,
	centro_costo		VARCHAR(25)		NULL,
	estado			VARCHAR(1)		NOT NULL,
	notas_rev    		TEXT	  		NULL
)
go


ALTER TABLE HIST_DIFCAM_CB 
	ADD CONSTRAINT IDDEF_HISTDCCB   
		DEFAULT (NEWID()) FOR [ID_HIST]
go		


ALTER TABLE HIST_DIFCAM_CB
         ADD CONSTRAINT HISTDFCBPK PRIMARY KEY NONCLUSTERED 
         (Id_hist)
go         


 
 CREATE TABLE MOV_BANCOS (
        CUENTA_BANCO         	VARCHAR(20) 	NOT NULL,
        TIPO_DOCUMENTO       	VARCHAR(3) 	NOT NULL,
        NUMERO               	decimal(28,0) 	NOT NULL,
        SUBTIPO              	smallint 	NULL,
        FECHA                	DATETIME 	NOT NULL,
        PAGADERO_A           	VARCHAR(150) 	NULL,
        REFERENCIA           	VARCHAR(249) 	NOT NULL,
        MONTO                	DECIMAL(28,8) 	NOT NULL,
        CONCIL_ACLARACION    	int 		NULL,
        PROVEEDOR            	VARCHAR(20) 	NULL,
        CONTRIBUYENTE        	VARCHAR(20) 	NULL,
        DETALLE              	TEXT 	NULL,
        CONFIRMADO           	VARCHAR(1) 	NOT NULL,
        ORIGEN               	VARCHAR(2) 	NULL,
        ASIENTO              	VARCHAR(10) 	NULL,
        ANULADO              	VARCHAR(1) 	NOT NULL,
        FCH_HORA_CREACION    	DATETIME 	NOT NULL,
        USUARIO_CREACION     	VARCHAR(25) 	NOT NULL,
        MONTO_ANULADO        	DECIMAL(28,8) 	NULL,
        ESTADO               	VARCHAR(1) 	NOT NULL,
        CONCILIACION         	int 		NULL,
        IMPRESO              	VARCHAR(1) 	NULL,
        DOC_REPORTADO        	int 		NULL,
        MONTO_REPORTADO      	DECIMAL(28,8) 	NULL,
        CLASE_DIF            	VARCHAR(1) 	NOT NULL,
        ACLARADA_DIF         	VARCHAR(1) 	NOT NULL,
        DOC_AJUSTE           	int 		NULL,
        TIPO_DOC_AJUSTE      	VARCHAR(3) 	NULL,
        NUMERO_DOC_AJUSTE    	decimal(28,0) 	NULL,
        CLASE_DOCUMENTO      	VARCHAR(1) 	NOT NULL,
        MODO_REGISTRO        	VARCHAR(1) 	NOT NULL,
        LIQUIDADO            	VARCHAR(1) 	NOT NULL,
        FCH_HORA_MODIFIC     	DATETIME 	NULL,
        USUARIO_MODIFIC      	VARCHAR(25) 	NULL,
        TIPO_CAMBIO_LOCAL    	DECIMAL(28,8) 	NOT NULL,
        TIPO_CAMBIO_DOLAR    	DECIMAL(28,8) 	NOT NULL,
        FCH_HORA_ANULADO     	DATETIME 	NULL,
	USUARIO_ANULADO      	VARCHAR(25)   	NULL,
	REFERENCIA_ANULADO   	VARCHAR(249)   	NULL,
	APROBADO 	     	VARCHAR(1) 	NOT NULL, 
	USUARIO_APROBACION   	VARCHAR(25) 	NULL,
	FECHA_APROBACION     	DATETIME 	NULL,
	TIPO_ASIENTO 		VARCHAR(4) 	NULL,
	PAQUETE 		VARCHAR(4) 	NULL,
	DEPENDIENTE_GP 		VARCHAR(1) 	NOT NULL    DEFAULT 'N',
	DOCUMENTO_FISCAL	VARCHAR(50) 	NULL,
	FECHA_CONTABLE 		DATETIME 	NULL,
	COD_IMPUESTO1 		VARCHAR(4) 	NULL,
	IMPUESTO1		DECIMAL(28,8) 	NULL,
	IMP1_NODES		DECIMAL (28,8) 	NULL,
	DOCUMENTO_GLOBAL 	VARCHAR(50) 	NULL
 )
go
 
 
 ALTER TABLE MOV_BANCOS
        ADD CONSTRAINT XPKMOV_BANCOS PRIMARY KEY NONCLUSTERED (
               CUENTA_BANCO, TIPO_DOCUMENTO, NUMERO)
go
 
CREATE TABLE MOV_PROCESADOS (
         CUENTA_BANCO		VARCHAR(20)	NOT NULL,
         TIPO_DOCUMENTO		VARCHAR(3)	NOT NULL,
         NUMERO         	DECIMAL(28,0)  	NOT NULL,
         ARCHIVO_TXT		VARCHAR(250)	NOT NULL,
         FECHA_GENERADO         DATETIME	NOT NULL,
         USUARIO_PROCESA	VARCHAR(25)	NOT NULL,
         FECHA_PROCESA		DATETIME	NOT NULL )
go

ALTER TABLE MOV_PROCESADOS
         ADD CONSTRAINT XPKMOV_PROCESADOS PRIMARY KEY NONCLUSTERED
         (CUENTA_BANCO, TIPO_DOCUMENTO, NUMERO )
go



 
 CREATE TABLE MOV_REPORTADOS (
        DOC_REPORTADO        int 		NOT NULL,
        CUENTA_BANCO         VARCHAR(20) 	NULL,
        TIPO_DOCUMENTO       VARCHAR(3) 	NOT NULL,
        NUMERO               decimal(28,0) 	NOT NULL,
        MONTO                DECIMAL(28,8) 	NOT NULL,
        FECHA                DATETIME 		NOT NULL,
        ESTADO               VARCHAR(1) 	NOT NULL,
        MODO_REGISTRO        VARCHAR(1) 	NOT NULL,
        COMPENSADO           VARCHAR(1) 	NOT NULL,
        CONCILIACION         int 		NULL,
        NOTAS                TEXT 		NULL,
        FCH_HORA_CREACION    DATETIME 		NOT NULL,
        FCH_HORA_MODIFIC     DATETIME 		NULL,
        DOC_COMPENSAC        int 		NULL,
        USUARIO_CREACION     VARCHAR(25) 	NOT NULL,
        USUARIO_MODIFIC      VARCHAR(25) 	NULL
 )
go
 
 
 ALTER TABLE MOV_REPORTADOS
        ADD CONSTRAINT XPKMOV_REPORTADOS PRIMARY KEY (DOC_REPORTADO)
go
 
 
 CREATE TABLE SUBTIPO_DOC_CB (
        TIPO                 	VARCHAR(3) 	NOT NULL,
        SUBTIPO              	smallint 	NOT NULL,
        DESCRIPCION          	VARCHAR(40)	NOT NULL,
        CUENTA_CONTABLE      	VARCHAR(25)	NULL,
	CENTRO_COSTO         	VARCHAR(25)	NULL,
	TIPO_ASIENTO 		VARCHAR(4) 	NULL,
	PAQUETE 		VARCHAR(4) 	NULL,
	TIPO_SERVICIO 		VARCHAR(2) 	NULL,
	DOCUMENTO_GLOBAL 	VARCHAR(10) 	NULL
 )
go
 
 
 ALTER TABLE SUBTIPO_DOC_CB
        ADD CONSTRAINT XPKSUBTIPO_DOC_CB PRIMARY KEY (TIPO, SUBTIPO)
go
 
 
 CREATE TABLE TRANSFERENCIA_CB (
        CUENTA_ORIGEN        VARCHAR(20) 	NOT NULL,
        TIPO_ORIGEN          VARCHAR(3) 	NOT NULL,
        NUMERO_ORIGEN        decimal(28,0) 	NOT NULL,
        DESCRIPCION          VARCHAR(80) 	NOT NULL,
        MONTO_COMISION       DECIMAL(28,8) 	NULL,
        MONTO_ORIGEN         DECIMAL(28,8) 	NOT NULL,
        ASIENTO              VARCHAR(10) 	NULL,
        FCH_HORA_CREACION    DATETIME 		NOT NULL,
        USUARIO_CREACION     VARCHAR(25) 	NOT NULL,
        FCH_HORA_MODIFIC     DATETIME 		NULL,
        USUARIO_MODIFIC      VARCHAR(25) 	NULL,
        ESTADO               VARCHAR(1) 	NOT NULL,
	FECHA_APLICACION     DATETIME  		NULL,
	RUBRO1_TRANS	     VARCHAR(100) 	NULL,
	RUBRO2_TRANS	     VARCHAR(100) 	NULL,
	RUBRO3_TRANS	     VARCHAR(100) 	NULL,
	RUBRO4_TRANS	     VARCHAR(100) 	NULL,
	RUBRO5_TRANS	     VARCHAR(100) 	NULL,
	RUBRO6_TRANS	     VARCHAR(100) 	NULL,
	RUBRO7_TRANS	     VARCHAR(100) 	NULL,
	RUBRO8_TRANS	     VARCHAR(100) 	NULL,
	RUBRO9_TRANS	     VARCHAR(100) 	NULL,
	RUBRO10_TRANS	     VARCHAR(100) 	NULL,
	DOCUMENTO_FISCAL     VARCHAR(50) 	NULL,
	DOCUMENTO_GLOBAL     VARCHAR(50) 	NULL
 )
go
 
 
 ALTER TABLE TRANSFERENCIA_CB
        ADD CONSTRAINT XPKTRANSFERENCIA_CB PRIMARY KEY (CUENTA_ORIGEN, 
               TIPO_ORIGEN, NUMERO_ORIGEN)
go
 
 
 
CREATE TABLE TIPO_CUENTA (
        TIPO_CUENTA	     VARCHAR(12) 	NOT NULL,
        DESCRIPCION          VARCHAR(40)	NOT NULL        
 )
 go


ALTER TABLE TIPO_CUENTA
        ADD CONSTRAINT XPKTIPO_CUENTA PRIMARY KEY (TIPO_CUENTA)
go    


CREATE TABLE TIPO_SERVICIO_CB(
       TIPO_SERVICIO	    VARCHAR(10) 	NOT NULL,
       DESCRIPCION          VARCHAR(249) 	NULL,
       CENTRO_COSTO         VARCHAR(25)		NULL,
       CUENTA_CONTABLE      VARCHAR(25) 	NULL
)
go


ALTER TABLE TIPO_SERVICIO_CB  ADD CONSTRAINT XPKTIPO_SERVICIO_CB PRIMARY KEY (TIPO_SERVICIO)
go

