
 
 ALTER TABLE AUXILIAR_CC
        ADD CONSTRAINT AUXCCCLIDEBCLIENTE
               FOREIGN KEY (CLI_DOC_DEBITO)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE AUXILIAR_CC
        ADD CONSTRAINT AUXCCCLICRECLIENTE
               FOREIGN KEY (CLI_DOC_CREDIT)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE AUXILIAR_CC
        ADD CONSTRAINT AUXCLIREPDCLIENTE
               FOREIGN KEY (CLI_REPORTE_DEBITO)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE AUXILIAR_CC
        ADD CONSTRAINT AUXCLIREPCCLIENTE
               FOREIGN KEY (CLI_REPORTE_CREDIT)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE AUXILIAR_CC
        ADD CONSTRAINT AUXCCMONDEB
               FOREIGN KEY (MONEDA_DEBITO)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE AUXILIAR_CC
        ADD CONSTRAINT AUXCCMONCRE
               FOREIGN KEY (MONEDA_CREDITO)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE AUXILIAR_CC
        ADD CONSTRAINT AUXCCDBD
               FOREIGN KEY (DEBITO, TIPO_DEBITO)
                              REFERENCES DOCUMENTOS_CC
                              ON DELETE CASCADE
go
 
 
 
ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIVEND
               FOREIGN KEY (VENDEDOR)
                              REFERENCES VENDEDOR
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIZONA
               FOREIGN KEY (ZONA)
                              REFERENCES ZONA
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIPAIS
               FOREIGN KEY (PAIS)
                              REFERENCES PAIS
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLICONDP
               FOREIGN KEY (CONDICION_PAGO)
                              REFERENCES CONDICION_PAGO
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIENTEMONEDA
               FOREIGN KEY (MONEDA)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIETTAR
               FOREIGN KEY (TIPO_TARJETA)
                              REFERENCES TIPO_TARJETA
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIECATG
               FOREIGN KEY (CATEGORIA_CLIENTE)
                              REFERENCES CATEGORIA_CLIENTE
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIECOBR
               FOREIGN KEY (COBRADOR)
                              REFERENCES COBRADOR
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIERUTA
               FOREIGN KEY (RUTA)
                              REFERENCES RUTA
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIENIPR
               FOREIGN KEY (NIVEL_PRECIO, MONEDA_NIVEL)
                              REFERENCES NIVEL_PRECIO
go
 
 

 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIDETDIR
               FOREIGN KEY (DETALLE_DIRECCION)
                              REFERENCES DETALLE_DIRECCION
go


ALTER TABLE CLIENTE
	ADD CONSTRAINT CLIENTENIT
		FOREIGN KEY (CONTRIBUYENTE)
			REFERENCES NIT
go  

 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIENTECLICORPASOC
               FOREIGN KEY (CLI_CORPORAC_ASOC)
                              REFERENCES CLIENTE
go

ALTER TABLE CLIENTE 
	ADD CONSTRAINT FTK_MODRETCC
		FOREIGN KEY (MODELO_RETENCION)
			REFERENCES MODELO_RETENCION(MODELO_RETENCION)
go

ALTER TABLE CLIENTE
        ADD CONSTRAINT CLICODIMP
               FOREIGN KEY (CODIGO_IMPUESTO)
                              REFERENCES IMPUESTO
go 


ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIENTEUSRC
		FOREIGN KEY ( USUARIO_CREACION )
			REFERENCES ERPADMIN.USUARIO
go

ALTER TABLE CLIENTE
	ADD CONSTRAINT CLIENTEUSRM
		FOREIGN KEY ( USUARIO_ULT_MOD )
			REFERENCES ERPADMIN.USUARIO
go


ALTER TABLE DOCUMENTOS_CC
        ADD CONSTRAINT DOCCODIMP
               FOREIGN KEY (CODIGO_IMPUESTO)
                              REFERENCES IMPUESTO
go    

ALTER TABLE DOCUMENTOS_CC
	ADD CONSTRAINT DOCUMENCCTIPOASNT
		FOREIGN KEY (TIPO_ASIENTO)
			REFERENCES TIPO_ASIENTO(TIPO_ASIENTO)
go 
			
ALTER TABLE DOCUMENTOS_CC
	ADD CONSTRAINT DOCUMENCCPAQUETE
		FOREIGN KEY (PAQUETE)
			REFERENCES PAQUETE(PAQUETE)
go 



 ALTER TABLE CLIENTE_RETENCION
        ADD CONSTRAINT CLRETRET
               FOREIGN KEY (CODIGO_RETENCION)
                              REFERENCES RETENCIONES
go
 
 
 ALTER TABLE CLIENTE_RETENCION
        ADD CONSTRAINT PRETCL
               FOREIGN KEY (CLIENTE)
                              REFERENCES CLIENTE
go 
 
 
 ALTER TABLE CLIENTE_VENDEDOR
        ADD CONSTRAINT CLVDCLIE
               FOREIGN KEY (CLIENTE)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE CLIENTE_VENDEDOR
        ADD CONSTRAINT CLVDVEND
               FOREIGN KEY (VENDEDOR)
                              REFERENCES VENDEDOR
go
 
 
 
ALTER TABLE CONTACTO_CLIENTE  WITH CHECK ADD
      CONSTRAINT FK_CONTACTOCL_CLIENTE 
            FOREIGN KEY(CLIENTE)
                  REFERENCES CLIENTE (CLIENTE)
go                  
 
 ALTER TABLE CONTRARECIBOS_CC
        ADD CONSTRAINT CNTRRECCUSU
               FOREIGN KEY (USUARIO_ULT_MOD)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CONTRARECIBOS_CC
        ADD CONSTRAINT CNDPAGCNTRECC
               FOREIGN KEY (CONDICION_PAGO)
                              REFERENCES CONDICION_PAGO
go
 
 
 ALTER TABLE CONTRARECIBOS_CC
        ADD CONSTRAINT CNTRECCCLI
               FOREIGN KEY (CLIENTE)
                              REFERENCES CLIENTE
go
 
 
ALTER TABLE DET_TIPOSERVICIO_CC
        ADD CONSTRAINT DETTIPOSERVICCCFASEPY
               FOREIGN KEY (PROYECTO,FASE)
                              REFERENCES FASE_PY
go


ALTER TABLE DET_TIPOSERVICIO_CC
        ADD CONSTRAINT DETTIPOSERVICDOCUMENTOCC
               FOREIGN KEY (DOCUMENTO,TIPO)
                              REFERENCES DOCUMENTOS_CC
                              ON DELETE CASCADE
go
 
  
 ALTER TABLE DIRECC_EMBARQUE
        ADD CONSTRAINT DIRECLIE
               FOREIGN KEY (CLIENTE)
                              REFERENCES CLIENTE
go
 
  
 ALTER TABLE DIRECC_EMBARQUE
        ADD CONSTRAINT DIREMBDETDIR
               FOREIGN KEY (DETALLE_DIRECCION)
                              REFERENCES DETALLE_DIRECCION
go
 
 
 ALTER TABLE DOCUMENTO_ASOCIADO
        ADD CONSTRAINT DOCASORIGENDOCCC
               FOREIGN KEY (DOC_ORIGEN, TIPO_DOC_ORIGEN)
                              REFERENCES DOCUMENTOS_CC
go
 
 
 ALTER TABLE DOCUMENTO_ASOCIADO
        ADD CONSTRAINT DOCASOCDOCCC
               FOREIGN KEY (DOCUMENTO, TIPO)
                              REFERENCES DOCUMENTOS_CC
go
 
 
 ALTER TABLE DOCUMENTOS_CC
        ADD CONSTRAINT DOCCCMONEDA
               FOREIGN KEY (MONEDA)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE DOCUMENTOS_CC
        ADD CONSTRAINT DOCCCSUBCC
               FOREIGN KEY (TIPO, SUBTIPO)
                              REFERENCES SUBTIPO_DOC_CC
go
 
 
 ALTER TABLE DOCUMENTOS_CC
        ADD CONSTRAINT DOCCCUSR
               FOREIGN KEY (USUARIO_ULT_MOD)
                              REFERENCES ERPADMIN.USUARIO
go

ALTER TABLE DOCUMENTOS_CC    
         ADD CONSTRAINT USUARAPROBDOCCC
         	FOREIGN KEY  (USUARIO_APROBACION) 
         			REFERENCES ERPADMIN.USUARIO(USUARIO)
go         			

 
 
 ALTER TABLE DOCUMENTOS_CC
        ADD CONSTRAINT DOCCTABN
               FOREIGN KEY (CTA_BANCARIA)
                              REFERENCES CUENTA_BANCARIA
go
 
 
 ALTER TABLE DOCUMENTOS_CC
        ADD CONSTRAINT DOCCOBRA
               FOREIGN KEY (COBRADOR)
                              REFERENCES COBRADOR
go
 
 
 ALTER TABLE DOCUMENTOS_CC
        ADD CONSTRAINT DOCCCVEN
               FOREIGN KEY (VENDEDOR)
                              REFERENCES VENDEDOR
go
 
 
 ALTER TABLE DOCUMENTOS_CC
        ADD CONSTRAINT DOCCCCON
               FOREIGN KEY (CONDICION_PAGO)
                              REFERENCES CONDICION_PAGO
go
 
 
 ALTER TABLE DOCUMENTOS_CC
        ADD CONSTRAINT DOCCCCLI
               FOREIGN KEY (CLIENTE)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE DOCUMENTOS_CC
        ADD CONSTRAINT DOCSCCCLIORIGENCLI
               FOREIGN KEY (CLIENTE_ORIGEN)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE DOCUMENTOS_CC
        ADD CONSTRAINT DOCSCCCLIREPORTCLI
               FOREIGN KEY (CLIENTE_REPORTE)
                              REFERENCES CLIENTE
go


ALTER TABLE DOCUMENTOS_CC    
         ADD CONSTRAINT USUARAUDANULDOCCC
         	FOREIGN KEY  ( AUD_USUARIO_ANUL) 
         		REFERENCES ERPADMIN.USUARIO(USUARIO)
go      

ALTER TABLE DOCUMENTOS_CC 
        ADD CONSTRAINT DOCCCDIVGEO
               FOREIGN KEY (PAIS,DIVISION_GEOGRAFICA1,DIVISION_GEOGRAFICA2 )
                              REFERENCES DIVISION_GEOGRAFICA2
go                              


 ALTER TABLE AUXILIAR_CC
        ADD CONSTRAINT AUXCCCRD
               FOREIGN KEY (CREDITO,TIPO_CREDITO)
                              REFERENCES DOCUMENTOS_CC
go

ALTER TABLE FIADORES_DOC_CC 
         ADD CONSTRAINT FIADORDOCCC
         	FOREIGN KEY  ( DOCUMENTO, TIPO)
         		REFERENCES DOCUMENTOS_CC (DOCUMENTO, TIPO) 
go

ALTER TABLE GARANTIAS_DOC_CC 
         ADD CONSTRAINT GARANDOCCC
         	FOREIGN KEY  ( DOCUMENTO, TIPO)
         		REFERENCES DOCUMENTOS_CC (DOCUMENTO, TIPO)
go         		

ALTER TABLE GARANTIAS_DOC_CC 
         ADD CONSTRAINT GARANART
         	FOREIGN KEY  ( ART_GARANTIA)
         		REFERENCES ARTICULO (ARTICULO)
go         		
         
         
 ALTER TABLE GLOBALES_CC
        ADD CONSTRAINT GBCCPQDB
               FOREIGN KEY (PAQUETE_DEB)
                              REFERENCES PAQUETE
go
 
 
 ALTER TABLE GLOBALES_CC
        ADD CONSTRAINT GBCCTADB
               FOREIGN KEY (TIPO_ASIENTO_DEB)
                              REFERENCES TIPO_ASIENTO
go
 
 
 ALTER TABLE GLOBALES_CC
        ADD CONSTRAINT GLOBCCIMP
               FOREIGN KEY (IMPUESTO_X_OMISION)
                              REFERENCES IMPUESTO
go
 
 
 ALTER TABLE GLOBALES_CC
        ADD CONSTRAINT GBCCPQCR
               FOREIGN KEY (PAQUETE_CRE)
                              REFERENCES PAQUETE
go
 
 
 ALTER TABLE GLOBALES_CC
        ADD CONSTRAINT GBCCTACR
               FOREIGN KEY (TIPO_ASIENTO_CRE)
                              REFERENCES TIPO_ASIENTO
go
 

ALTER TABLE HIST_DIFCAM_CC
         ADD CONSTRAINT USUARHISTDFCC
         	FOREIGN KEY  ( usuario_auditoria)
         		REFERENCES ERPADMIN.USUARIO(USUARIO)
go
 
 ALTER TABLE PARCIALIDADES_CC
        ADD CONSTRAINT PARCCDOCCC
               FOREIGN KEY (DOCUMENTO_ORIGEN, TIPO_DOC_ORIGEN)
                              REFERENCES DOCUMENTOS_CC
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE RETENCIONES_DOC_CC
        ADD CONSTRAINT RETDOCCCRET
               FOREIGN KEY (CODIGO_RETENCION)
                              REFERENCES RETENCIONES
go
 
 
 ALTER TABLE RETENCIONES_DOC_CC
        ADD CONSTRAINT RETDOCCCDOCCC
               FOREIGN KEY (DOCUMENTO, TIPO)
                              REFERENCES DOCUMENTOS_CC
go
 
 
 ALTER TABLE SALDO_CLIENTE
        ADD CONSTRAINT SALDOCLICLIENTE
               FOREIGN KEY (CLIENTE)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE SALDO_CLIENTE
        ADD CONSTRAINT SALDOCLIMONEDA
               FOREIGN KEY (MONEDA)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE SUBTIPO_DOC_CC
        ADD CONSTRAINT ASOC_SUBTCB_SUBTCC
               FOREIGN KEY (TIPO_CB, SUBTIPO_CB)
                              REFERENCES SUBTIPO_DOC_CB
go

ALTER TABLE SUBTIPO_DOC_CC
        ADD CONSTRAINT SUBDOCCC_CTAC
               FOREIGN KEY (CENTRO_COSTO, CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go                              
 
 
ALTER TABLE SUBTIPO_DOC_CC
	ADD CONSTRAINT SUBDOCCCTIPOASNT
		FOREIGN KEY (TIPO_ASIENTO)
			REFERENCES TIPO_ASIENTO(TIPO_ASIENTO)
go  
			
ALTER TABLE SUBTIPO_DOC_CC
	ADD CONSTRAINT SUBDOCCCPAQUETE
		FOREIGN KEY (PAQUETE)
			REFERENCES PAQUETE(PAQUETE)
go   
 
 
 
 ALTER TABLE TEXTOS_DOCS_CC
        ADD CONSTRAINT DOCUMENTOSTEXTOSCC
               FOREIGN KEY (DOCUMENTO, TIPO)
                              REFERENCES DOCUMENTOS_CC
                              ON DELETE CASCADE
go
 
 
ALTER TABLE TIPO_SERVICIO_CC
        ADD CONSTRAINT TIPOSERVICCCTRCTA
               FOREIGN KEY (CENTRO_COSTO,CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go                              
 