CREATE TABLE GRUPO_CE (
       USUARIO              VARCHAR(25)  NOT NULL,
       NOMBRE               VARCHAR(100) NOT NULL       
)
go
       
       
ALTER TABLE GRUPO_CE
	ADD CONSTRAINT XPKGRUPO_CE PRIMARY KEY (USUARIO)
go


CREATE TABLE IMAGEN_CE (
         INFORMACION		INT		NOT NULL,
         MODULO			INT		NOT NULL,
         DIRECCION_IMAGEN	VARCHAR(70)	NOT NULL,
         POSICION_IMAGEN	VARCHAR(15)	NULL,
         LINK_IMAGEN		VARCHAR(50)	NULL )
go 


ALTER TABLE IMAGEN_CE
         ADD CONSTRAINT IMAGENCEPK PRIMARY KEY NONCLUSTERED (INFORMACION, MODULO )
go 
         	

CREATE TABLE INFORMACION (
         INFORMACION		INT		NOT NULL IDENTITY(1,1),
         MODULO			INT		NOT NULL,
         TIPO_FORMATO		INT		NOT NULL,
         TIPO_INFORMACION	INT		NOT NULL,
         NOMBRE_INFORMACION     VARCHAR(50)     NOT NULL,         
         FECHA_INICIO		DATETIME	NOT NULL,
         FECHA_HASTA		DATETIME	NOT NULL,
         CUERPO			TEXT		NULL,
         TEXTO_LINK		VARCHAR(50)	NULL,
         DIRECCION_LINK		VARCHAR(50)	NULL,
         IDIOMA                 VARCHAR(5)      NULL)
go 


ALTER TABLE INFORMACION
         ADD CONSTRAINT INFORMACIONPK PRIMARY KEY NONCLUSTERED 	(INFORMACION, MODULO )
go 
         	

CREATE TABLE INFORMACION_CONTAC (
       CODIGO               VARCHAR(40) NOT NULL,
       NOMBRE_EMPRESA       VARCHAR(50) NULL
)
go


ALTER TABLE INFORMACION_CONTAC
	ADD CONSTRAINT XPKINFORMACION_CONTAC PRIMARY KEY (CODIGO)
go


CREATE TABLE INFORMACION_GRUPO (
         INFORMACION_GRUPO	INT	NOT NULL,
         MODULO			INT	NOT NULL,
         INFORMACION		INT	NOT NULL )
go 


ALTER TABLE INFORMACION_GRUPO
         ADD CONSTRAINT INFGRUPOPK PRIMARY KEY NONCLUSTERED (INFORMACION_GRUPO, MODULO, INFORMACION )
go 


CREATE TABLE MODULO (
         MODULO		INT		NOT NULL,
         NOMBRE_MODULO	VARCHAR(50)	NOT NULL )
go 


ALTER TABLE MODULO
         ADD CONSTRAINT MODULOPK PRIMARY KEY NONCLUSTERED (MODULO )
go 


CREATE TABLE NOTICIA (
         INFORMACION	INT	NOT NULL,
         MODULO		INT	NOT NULL )
go 


ALTER TABLE NOTICIA
         ADD CONSTRAINT NOTICIAPK PRIMARY KEY NONCLUSTERED (INFORMACION, MODULO )
go 


CREATE TABLE OFERTA (
	INFORMACION	INT		NOT NULL,
	MODULO		INT		NOT NULL,
	ARTICULO     	VARCHAR(20) 	NULL,
	TIPO_OFERTA     VARCHAR(20) 	NULL
)
go 


ALTER TABLE OFERTA
         ADD CONSTRAINT OFERTAPK PRIMARY KEY NONCLUSTERED (INFORMACION, MODULO )
go 


CREATE TABLE PAGINA (
         PAGINA		INT		NOT NULL,
         MODULO		INT		NOT NULL,
         NOMBRE_PAGINA	VARCHAR(30)	NOT NULL )
go 


ALTER TABLE PAGINA
         ADD CONSTRAINT PAGINAPK PRIMARY KEY NONCLUSTERED (PAGINA, MODULO )
go 


CREATE TABLE PEDIDO_GUARDADO_CE (
       PEDIDO               VARCHAR(50) NOT NULL,
       FECHA_PEDIDO         DATETIME 	NOT NULL,
       OBSERVACIONES        TEXT 	NULL,
       TOTAL_MERCADERIA     float 	NOT NULL,
       TOTAL_IMPUESTO1      float 	NULL,
       TOTAL_IMPUESTO2      float 	NULL,
       TOTAL_PEDIDO         float 	NOT NULL,
       DESCUENTO            float 	NULL,
       CLIENTE              VARCHAR(20) NOT NULL,
       CONDICION_PAGO       VARCHAR(4) 	NOT NULL
)
go       
       
ALTER TABLE PEDIDO_GUARDADO_CE
	ADD CONSTRAINT XPKPEDIDO_GUARDADO_CE PRIMARY KEY (PEDIDO)
go
       
       
CREATE TABLE PED_GUARD_CE_LINEA (
       PEDIDO_LINEA         smallint 	NOT NULL,
       PEDIDO               VARCHAR(12) NOT NULL,
       ARTICULO             VARCHAR(20) NOT NULL,
       PRECIO_UNITARIO      float 	NULL,
       CANTIDAD_PEDIDA      float 	NULL,
       CANTIDAD_BONIFICADA  float 	NULL,
       PORC_DESCUENTO       float 	NULL,
       TOTAL_LINEA          float 	NULL,
       Monto_Descuento	    float 	NULL
)
go    
       
ALTER TABLE PED_GUARD_CE_LINEA
	ADD CONSTRAINT XPKPED_GUARD_CE_LINEA PRIMARY KEY (PEDIDO_LINEA, PEDIDO)
go

CREATE TABLE PEDIDO_INTERNET (
       ARTICULO             VARCHAR(20) NOT NULL,
       CLIENTE              VARCHAR(20) NOT NULL,
       CANTIDAD             float 	NOT NULL,
       PRECIO               float 	NOT NULL
       
)
go

ALTER TABLE PEDIDO_INTERNET
       ADD CONSTRAINT XPKPEDIDO_INTERNET PRIMARY KEY (ARTICULO, CLIENTE)
go              
   
   
CREATE TABLE PEDIDO_USUARIO (
       PEDIDO               VARCHAR(50)    NOT NULL,
       CODIGO		    VARCHAR(40)    NULL
)
go


ALTER TABLE PEDIDO_USUARIO
	ADD CONSTRAINT XPKPEDIDO_USUARIO PRIMARY KEY (PEDIDO)
go

CREATE TABLE SCROLL (
         INFORMACION	INT		NOT NULL,
         MODULO		INT		NOT NULL )
go 


ALTER TABLE SCROLL
         ADD CONSTRAINT SCROLLPK PRIMARY KEY NONCLUSTERED (INFORMACION, MODULO )
go 
         	

CREATE TABLE SEC_INFORMACION (
         SECCION	INT		NOT NULL,
         PAGINA		INT		NOT NULL,
         MODULO		INT		NOT NULL,
         INFORMACION	INT		NOT NULL )
go 


ALTER TABLE SEC_INFORMACION
         ADD CONSTRAINT SECINFPK PRIMARY KEY NONCLUSTERED (SECCION, PAGINA, MODULO, INFORMACION )
go 


CREATE TABLE SECCION (
         SECCION	INT		NOT NULL,
         PAGINA		INT		NOT NULL,
         MODULO		INT		NOT NULL,
         DESC_SECCION	VARCHAR(50)	NOT NULL )
go 


ALTER TABLE SECCION
         ADD CONSTRAINT SECCIONPK PRIMARY KEY NONCLUSTERED (SECCION, PAGINA, MODULO )
go 


CREATE TABLE TEXTO (
         INFORMACION		INT		NOT NULL,
         MODULO			INT		NOT NULL,
         TITULO			VARCHAR(50)	NULL,
         COLOR_TITULO		VARCHAR(15)	NOT NULL,
         POSICION_TITULO	VARCHAR(15)	NOT NULL,
         COLOR_CUERPO		VARCHAR(15)	NULL )
go 


ALTER TABLE TEXTO
         ADD CONSTRAINT TEXTOPK PRIMARY KEY NONCLUSTERED (INFORMACION, MODULO )
go 
         	

CREATE TABLE TIPO_FORMATO (
         TIPO_FORMATO		INT		NOT NULL,
         MODULO			INT		NOT NULL,
         DESC_TIPO_FORMATO	VARCHAR(10)	NOT NULL )
go 


ALTER TABLE TIPO_FORMATO
         ADD CONSTRAINT TIPOFORMATOPK PRIMARY KEY NONCLUSTERED (TIPO_FORMATO, MODULO )
go 


CREATE TABLE TIPO_INFORMACION (
         TIPO_INFORMACION	INT		NOT NULL,
         MODULO			INT		NOT NULL,
         DESC_TIPO_INFO		VARCHAR(10)	NOT NULL )
go 


ALTER TABLE TIPO_INFORMACION
         ADD CONSTRAINT TIPINFPK PRIMARY KEY NONCLUSTERED (TIPO_INFORMACION, MODULO )
go 


CREATE TABLE USUARIO_CE (
       EMAIL                VARCHAR(100) 	NOT NULL,
       CODIGO               VARCHAR (40) 	NOT NULL,
       NOMBRE               VARCHAR(100) 	NOT NULL,
       TELEFONO             VARCHAR(15) 	NULL,
       ACTIVO               VARCHAR(1) 		NOT NULL,
       CLIENTE              VARCHAR(20) 	NULL,
       SUPERUSUARIO         VARCHAR(1)          NULL
)
go       


ALTER TABLE USUARIO_CE
	ADD CONSTRAINT XPKUSUARIO_CE PRIMARY KEY (EMAIL)
go


CREATE TABLE VENDEDOR_EMAIL (
       VENDEDOR		VARCHAR(4)	NOT NULL,
       EMAIL            char(80)	NOT NULL 
)
go

