INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('100','Activo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('100.01','Activo a corto plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('101','Caja')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('101.01','Caja y efectivo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('102','Bancos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('102.01','Bancos nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('102.02','Bancos extranjeros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('103','Inversiones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('103.01','Inversiones temporales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('103.02','Inversiones en fideicomisos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('103.03','Otras inversiones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('104','Otros instrumentos financieros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('104.01','Otros instrumentos financieros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('105','Clientes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('105.01','Clientes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('105.02','Clientes extranjeros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('105.03','Clientes nacionales parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('105.04','Clientes extranjeros parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('106','Cuentas y documentos por cobrar a corto plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('106.01','Cuentas y documentos por cobrar a corto plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('106.02','Cuentas y documentos por cobrar a corto plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('106.03','Cuentas y documentos por cobrar a corto plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('106.04','Cuentas y documentos por cobrar a corto plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('106.05','Intereses por cobrar a corto plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('106.06','Intereses por cobrar a corto plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('106.07','Intereses por cobrar a corto plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('106.08','Intereses por cobrar a corto plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('106.09','Otras cuentas y documentos por cobrar a corto plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('106.10','Otras cuentas y documentos por cobrar a corto plazo parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('107','Deudores diversos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('107.01','Funcionarios y empleados')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('107.02','Socios y accionistas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('107.03','Partes relacionadas nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('107.04','Partes relacionadas extranjeros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('107.05','Otros deudores diversos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('108','Estimación de cuentas incobrables')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('108.01','Estimación de cuentas incobrables nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('108.02','Estimación de cuentas incobrables extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('108.03','Estimación de cuentas incobrables nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('108.04','Estimación de cuentas incobrables extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109','Pagos anticipados')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.01','Seguros y fianzas pagados por anticipado nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.02','Seguros y fianzas pagados por anticipado extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.03','Seguros y fianzas pagados por anticipado nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.04','Seguros y fianzas pagados por anticipado extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.05','Rentas pagados por anticipado nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.06','Rentas pagados por anticipado extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.07','Rentas pagados por anticipado nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.08','Rentas pagados por anticipado extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.09','Intereses pagados por anticipado nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.10','Intereses pagados por anticipado extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.11','Intereses pagados por anticipado nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.12','Intereses pagados por anticipado extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.13','Factoraje financiero pagados por anticipado nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.14','Factoraje financiero pagados por anticipado extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.15','Factoraje financiero pagados por anticipado nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.16','Factoraje financiero pagados por anticipado extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.17','Arrendamiento financiero pagados por anticipado nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.18','Arrendamiento financiero pagados por anticipado extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.19','Arrendamiento financiero pagados por anticipado nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.20','Arrendamiento financiero pagados por anticipado extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.21','Pérdida por deterioro de pagos anticipados')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.22','Derechos fiduciarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('109.23','Otros pagos anticipados')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('110','Subsidio al empleo por aplicar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('110.01','Subsidio al empleo por aplicar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('111','Crédito al diesel por acreditar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('111.01','Crédito al diesel por acreditar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('112','Otros estímulos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('112.01','Otros estímulos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('113','Impuestos a favor')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('113.01','IVA a favor')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('113.02','ISR a favor')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('113.03','IETU a favor')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('113.04','IDE a favor')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('113.05','IA a favor')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('113.06','Subsidio al empleo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('113.07','Pago de lo indebido')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('113.08','Otros impuestos a favor')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('114','Pagos provisionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('114.01','Pagos provisionales de ISR')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('115','Inventario')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('115.01','Inventario')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('115.02','Materia prima y materiales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('115.03','Producción en proceso')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('115.04','Productos terminados')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('115.05','Mercancías en tránsito')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('115.06','Mercancías en poder de terceros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('115.07','Otros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('116','Estimación de inventarios obsoletos y de lento movimiento')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('116.01','Estimación de inventarios obsoletos y de lento movimiento')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('117','Obras en proceso de inmuebles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('117.01','Obras en proceso de inmuebles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('118','Impuestos acreditables pagados')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('118.01','IVA acreditable pagado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('118.02','IVA acreditable de importación pagado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('118.03','IEPS acreditable pagado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('118.04','IEPS pagado en importación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('119','Impuestos acreditables por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('119.01','IVA pendiente de pago')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('119.02','IVA de importación pendiente de pago')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('119.03','IEPS pendiente de pago')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('119.04','IEPS pendiente de pago en importación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('120','Anticipo a proveedores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('120.01','Anticipo a proveedores nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('120.02','Anticipo a proveedores extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('120.03','Anticipo a proveedores nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('120.04','Anticipo a proveedores extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('121','Otros activos a corto plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('121.01','Otros activos a corto plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('151','Terrenos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('151.01','Terrenos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('152','Edificios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('152.01','Edificios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('153','Maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('153.01','Maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('154','Automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('154.01','Automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('155','Mobiliario y equipo de oficina')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('155.01','Mobiliario y equipo de oficina')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('156','Equipo de cómputo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('156.01','Equipo de cómputo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('157','Equipo de comunicación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('157.01','Equipo de comunicación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('158','Activos biológicos, vegetales y semovientes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('158.01','Activos biológicos, vegetales y semovientes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('159','Obras en proceso de activos fijos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('159.01','Obras en proceso de activos fijos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('160','Otros activos fijos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('160.01','Otros activos fijos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('161','Ferrocarriles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('161.01','Ferrocarriles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('162','Embarcaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('162.01','Embarcaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('163','Aviones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('163.01','Aviones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('164','Troqueles, moldes, matrices y herramental')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('164.01','Troqueles, moldes, matrices y herramental')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('165','Equipo de comunicaciones telefónicas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('165.01','Equipo de comunicaciones telefónicas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('166','Equipo de comunicación satelital')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('166.01','Equipo de comunicación satelital')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('167','Equipo de adaptaciones para personas con capacidades diferentes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('167.01','Equipo de adaptaciones para personas con capacidades diferentes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('168','Maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('168.01','Maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('169','Otra maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('169.01','Otra maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('170','Adaptaciones y mejoras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('170.01','Adaptaciones y mejoras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171','Depreciación acumulada de activos fijos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.01','Depreciación acumulada de edificios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.02','Depreciación acumulada de maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.03','Depreciación acumulada de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.04','Depreciación acumulada de mobiliario y equipo de oficina')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.05','Depreciación acumulada de equipo de cómputo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.06','Depreciación acumulada de equipo de comunicación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.07','Depreciación acumulada de activos biológicos, vegetales y semovientes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.08','Depreciación acumulada de otros activos fijos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.09','Depreciación acumulada de ferrocarriles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.10','Depreciación acumulada de embarcaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.11','Depreciación acumulada de aviones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.12','Depreciación acumulada de troqueles, moldes, matrices y herramental')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.13','Depreciación acumulada de equipo de comunicaciones telefónicas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.14','Depreciación acumulada de equipo de comunicación satelital')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.15','Depreciación acumulada de equipo de adaptaciones para personas con capacidades diferentes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.16','Depreciación acumulada de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.17','Depreciación acumulada de adaptaciones y mejoras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('171.18','Depreciación acumulada de otra maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172','Pérdida por deterioro acumulado de activos fijos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.01','Pérdida por deterioro acumulado de edificios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.02','Pérdida por deterioro acumulado de maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.03','Pérdida por deterioro acumulado de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.04','Pérdida por deterioro acumulado de mobiliario y equipo de oficina')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.05','Pérdida por deterioro acumulado de equipo de cómputo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.06','Pérdida por deterioro acumulado de equipo de comunicación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.07','Pérdida por deterioro acumulado de activos biológicos, vegetales y semovientes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.08','Pérdida por deterioro acumulado de otros activos fijos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.09','Pérdida por deterioro acumulado de ferrocarriles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.10','Pérdida por deterioro acumulado de embarcaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.11','Pérdida por deterioro acumulado de aviones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.12','Pérdida por deterioro acumulado de troqueles, moldes, matrices y herramental')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.13','Pérdida por deterioro acumulado de equipo de comunicaciones telefónicas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.14','Pérdida por deterioro acumulado de equipo de comunicación satelital')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.15','Pérdida por deterioro acumulado de equipo de adaptaciones para personas con capacidades diferentes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.16','Pérdida por deterioro acumulado de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.17','Pérdida por deterioro acumulado de adaptaciones y mejoras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('172.18','Pérdida por deterioro acumulado de otra maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('173','Gastos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('173.01','Gastos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('174','Gastos pre operativos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('174.01','Gastos pre operativos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('175','Regalías, asistencia técnica y otros gastos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('175.01','Regalías, asistencia técnica y otros gastos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('176','Activos intangibles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('176.01','Activos intangibles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('177','Gastos de organización')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('177.01','Gastos de organización')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('178','Investigación y desarrollo de mercado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('178.01','Investigación y desarrollo de mercado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('179','Marcas y patentes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('179.01','Marcas y patentes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('180','Crédito mercantil')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('180.01','Crédito mercantil')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('181','Gastos de instalación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('181.01','Gastos de instalación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('182','Otros activos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('182.01','Otros activos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('183','Amortización acumulada de activos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('183.01','Amortización acumulada de gastos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('183.02','Amortización acumulada de gastos pre operativos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('183.03','Amortización acumulada de regalías, asistencia técnica y otros gastos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('183.04','Amortización acumulada de activos intangibles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('183.05','Amortización acumulada de gastos de organización')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('183.06','Amortización acumulada de investigación y desarrollo de mercado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('183.07','Amortización acumulada de marcas y patentes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('183.08','Amortización acumulada de crédito mercantil')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('183.09','Amortización acumulada de gastos de instalación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('183.10','Amortización acumulada de otros activos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('184','Depósitos en garantía')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('184.01','Depósitos de fianzas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('184.02','Depósitos de arrendamiento de bienes inmuebles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('184.03','Otros depósitos en garantía')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('185','Impuestos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('185.01','Impuestos diferidos ISR')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('186','Cuentas y documentos por cobrar a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('186.01','Cuentas y documentos por cobrar a largo plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('186.02','Cuentas y documentos por cobrar a largo plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('186.03','Cuentas y documentos por cobrar a largo plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('186.04','Cuentas y documentos por cobrar a largo plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('186.05','Intereses por cobrar a largo plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('186.06','Intereses por cobrar a largo plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('186.07','Intereses por cobrar a largo plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('186.08','Intereses por cobrar a largo plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('186.09','Otras cuentas y documentos por cobrar a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('186.10','Otras cuentas y documentos por cobrar a largo plazo parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('187','Participación de los trabajadores en las utilidades diferidas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('187.01','Participación de los trabajadores en las utilidades diferidas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('188','Inversiones permanentes en acciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('188.01','Inversiones a largo plazo en subsidiarias')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('188.02','Inversiones a largo plazo en asociadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('188.03','Otras inversiones permanentes en acciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('189','Estimación por deterioro de inversiones permanentes en acciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('189.01','Estimación por deterioro de inversiones permanentes en acciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('190','Otros instrumentos financieros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('190.01','Otros instrumentos financieros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('191','Otros activos a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('191.01','Otros activos a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('201','Proveedores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('201.01','Proveedores nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('201.02','Proveedores extranjeros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('201.03','Proveedores nacionales parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('201.04','Proveedores extranjeros parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('202','Cuentas por pagar a corto plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('202.01','Documentos por pagar bancario y financiero nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('202.02','Documentos por pagar bancario y financiero extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('202.03','Documentos y cuentas por pagar a corto plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('202.04','Documentos y cuentas por pagar a corto plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('202.05','Documentos y cuentas por pagar a corto plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('202.06','Documentos y cuentas por pagar a corto plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('202.07','Intereses por pagar a corto plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('202.08','Intereses por pagar a corto plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('202.09','Intereses por pagar a corto plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('202.10','Intereses por pagar a corto plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('202.11','Dividendo por pagar nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('202.12','Dividendo por pagar extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203','Cobros anticipados a corto plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.01','Rentas cobradas por anticipado a corto plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.02','Rentas cobradas por anticipado a corto plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.03','Rentas cobradas por anticipado a corto plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.04','Rentas cobradas por anticipado a corto plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.05','Intereses cobrados por anticipado a corto plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.06','Intereses cobrados por anticipado a corto plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.07','Intereses cobrados por anticipado a corto plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.08','Intereses cobrados por anticipado a corto plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.09','Factoraje financiero cobrados por anticipado a corto plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.10','Factoraje financiero cobrados por anticipado a corto plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.11','Factoraje financiero cobrados por anticipado a corto plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.12','Factoraje financiero cobrados por anticipado a corto plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.13','Arrendamiento financiero cobrados por anticipado a corto plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.14','Arrendamiento financiero cobrados por anticipado a corto plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.15','Arrendamiento financiero cobrados por anticipado a corto plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.16','Arrendamiento financiero cobrados por anticipado a corto plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.17','Derechos fiduciarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('203.18','Otros cobros anticipados')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('204','Instrumentos financieros a corto plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('204.01','Instrumentos financieros a corto plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('205','Acreedores diversos a corto plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('205.01','Socios, accionistas o representante legal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('205.02','Acreedores diversos a corto plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('205.03','Acreedores diversos a corto plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('205.04','Acreedores diversos a corto plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('205.05','Acreedores diversos a corto plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('205.06','Otros acreedores diversos a corto plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('206','Anticipo de cliente')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('206.01','Anticipo de cliente nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('206.02','Anticipo de cliente extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('206.03','Anticipo de cliente nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('206.04','Anticipo de cliente extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('206.05','Otros anticipos de clientes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('207','Impuestos trasladados')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('207.01','IVA trasladado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('207.02','IEPS trasladado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('208','Impuestos trasladados cobrados')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('208.01','IVA trasladado cobrado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('208.02','IEPS trasladado cobrado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('209','Impuestos trasladados no cobrados')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('209.01','IVA trasladado no cobrado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('209.02','IEPS trasladado no cobrado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('210','Provisión de sueldos y salarios por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('210.01','Provisión de sueldos y salarios por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('210.02','Provisión de vacaciones por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('210.03','Provisión de aguinaldo por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('210.04','Provisión de fondo de ahorro por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('210.05','Provisión de asimilados a salarios por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('210.06','Provisión de anticipos o remanentes por distribuir')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('210.07','Provisión de otros sueldos y salarios por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('211','Provisión de contribuciones de seguridad social por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('211.01','Provisión de IMSS patronal por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('211.02','Provisión de SAR por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('211.03','Provisión de infonavit por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('212','Provisión de impuesto estatal sobre nómina por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('212.01','Provisión de impuesto estatal sobre nómina por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('213','Impuestos y derechos por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('213.01','IVA por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('213.02','IEPS por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('213.03','ISR por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('213.04','Impuesto estatal sobre nómina por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('213.05','Impuesto estatal y municipal por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('213.06','Derechos por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('213.07','Otros impuestos por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('214','Dividendos por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('214.01','Dividendos por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('215','PTU por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('215.01','PTU por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('215.02','PTU por pagar de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('215.03','Provisión de PTU por pagar')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('216','Impuestos retenidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('216.01','Impuestos retenidos de ISR por sueldos y salarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('216.02','Impuestos retenidos de ISR por asimilados a salarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('216.03','Impuestos retenidos de ISR por arrendamiento')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('216.04','Impuestos retenidos de ISR por servicios profesionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('216.05','Impuestos retenidos de ISR por dividendos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('216.06','Impuestos retenidos de ISR por intereses')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('216.07','Impuestos retenidos de ISR por pagos al extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('216.08','Impuestos retenidos de ISR por venta de acciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('216.09','Impuestos retenidos de ISR por venta de partes sociales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('216.10','Impuestos retenidos de IVA')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('216.11','Retenciones de IMSS a los trabajadores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('216.12','Otras impuestos retenidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('217','Pagos realizados por cuenta de terceros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('217.01','Pagos realizados por cuenta de terceros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('218','Otros pasivos a corto plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('218.01','Otros pasivos a corto plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('251','Acreedores diversos a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('251.01','Socios, accionistas o representante legal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('251.02','Acreedores diversos a largo plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('251.03','Acreedores diversos a largo plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('251.04','Acreedores diversos a largo plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('251.05','Acreedores diversos a largo plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('251.06','Otros acreedores diversos a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252','Cuentas por pagar a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.01','Documentos bancarios y financieros por pagar a largo plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.02','Documentos bancarios y financieros por pagar a largo plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.03','Documentos y cuentas por pagar a largo plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.04','Documentos y cuentas por pagar a largo plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.05','Documentos y cuentas por pagar a largo plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.06','Documentos y cuentas por pagar a largo plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.07','Hipotecas por pagar a largo plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.08','Hipotecas por pagar a largo plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.09','Hipotecas por pagar a largo plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.10','Hipotecas por pagar a largo plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.11','Intereses por pagar a largo plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.12','Intereses por pagar a largo plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.13','Intereses por pagar a largo plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.14','Intereses por pagar a largo plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.15','Dividendos por pagar nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.16','Dividendos por pagar extranjeros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('252.17','Otras cuentas y documentos por pagar a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253','Cobros anticipados a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.01','Rentas cobradas por anticipado a largo plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.02','Rentas cobradas por anticipado a largo plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.03','Rentas cobradas por anticipado a largo plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.04','Rentas cobradas por anticipado a largo plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.05','Intereses cobrados por anticipado a largo plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.06','Intereses cobrados por anticipado a largo plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.07','Intereses cobrados por anticipado a largo plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.08','Intereses cobrados por anticipado a largo plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.09','Factoraje financiero cobrados por anticipado a largo plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.10','Factoraje financiero cobrados por anticipado a largo plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.11','Factoraje financiero cobrados por anticipado a largo plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.12','Factoraje financiero cobrados por anticipado a largo plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.13','Arrendamiento financiero cobrados por anticipado a largo plazo nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.14','Arrendamiento financiero cobrados por anticipado a largo plazo extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.15','Arrendamiento financiero cobrados por anticipado a largo plazo nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.16','Arrendamiento financiero cobrados por anticipado a largo plazo extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.17','Derechos fiduciarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('253.18','Otros cobros anticipados')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('254','Instrumentos financieros a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('254.01','Instrumentos financieros a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('255','Pasivos por beneficios a los empleados a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('255.01','Pasivos por beneficios a los empleados a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('256','Otros pasivos a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('256.01','Otros pasivos a largo plazo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('257','Participación de los trabajadores en las utilidades diferida')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('257.01','Participación de los trabajadores en las utilidades diferida')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('258','Obligaciones contraídas de fideicomisos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('258.01','Obligaciones contraídas de fideicomisos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('259','Impuestos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('259.01','ISR diferido')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('259.02','ISR por dividendo diferido')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('259.03','Otros impuestos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('260','Pasivos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('260.01','Pasivos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('301','Capital social')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('301.01','Capital fijo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('301.02','Capital variable')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('301.03','Aportaciones para futuros aumentos de capital')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('301.04','Prima en suscripción de acciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('301.05','Prima en suscripción de partes sociales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('302','Patrimonio')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('302.01','Patrimonio')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('302.02','Aportación patrimonial')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('302.03','Déficit o remanente del ejercicio')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('303','Reserva legal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('303.01','Reserva legal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('304','Resultado de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('304.01','Utilidad de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('304.02','Pérdida de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('304.03','Resultado integral de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('304.04','Déficit o remanente de ejercicio anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('305','Resultado del ejercicio')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('305.01','Utilidad del ejercicio')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('305.02','Pérdida del ejercicio')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('305.03','Resultado integral')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('306','Otras cuentas de capital')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('306.01','Otras cuentas de capital')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401','Ingresos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.01','Ventas y/o servicios gravados a la tasa general')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.02','Ventas y/o servicios gravados a la tasa general de contado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.03','Ventas y/o servicios gravados a la tasa general a crédito')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.04','Ventas y/o servicios gravados al 0%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.05','Ventas y/o servicios gravados al 0% de contado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.06','Ventas y/o servicios gravados al 0% a crédito')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.07','Ventas y/o servicios exentos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.08','Ventas y/o servicios exentos de contado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.09','Ventas y/o servicios exentos a crédito')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.10','Ventas y/o servicios gravados a la tasa general nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.11','Ventas y/o servicios gravados a la tasa general extranjeros partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.12','Ventas y/o servicios gravados al 0% nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.13','Ventas y/o servicios gravados al 0% extranjeros partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.14','Ventas y/o servicios exentos nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.15','Ventas y/o servicios exentos extranjeros partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.16','Ingresos por servicios administrativos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.17','Ingresos por servicios administrativos nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.18','Ingresos por servicios administrativos extranjeros partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.19','Ingresos por servicios profesionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.20','Ingresos por servicios profesionales nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.21','Ingresos por servicios profesionales extranjeros partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.22','Ingresos por arrendamiento')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.23','Ingresos por arrendamiento nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.24','Ingresos por arrendamiento extranjeros partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.25','Ingresos por exportación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.26','Ingresos por comisiones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.27','Ingresos por maquila')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.28','Ingresos por coordinados')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.29','Ingresos por regalías')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.30','Ingresos por asistencia técnica')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.31','Ingresos por donativos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.32','Ingresos por intereses (actividad propia)')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.33','Ingresos de copropiedad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.34','Ingresos por fideicomisos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.35','Ingresos por factoraje financiero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.36','Ingresos por arrendamiento financiero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.37','Ingresos de extranjeros con establecimiento en el país')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('401.38','Otros ingresos propios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('402','Devoluciones, descuentos o bonificaciones sobre ingresos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('402.01','Devoluciones, descuentos o bonificaciones sobre ventas y/o servicios a la tasa general')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('402.02','Devoluciones, descuentos o bonificaciones sobre ventas y/o servicios al 0%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('402.03','Devoluciones, descuentos o bonificaciones sobre ventas y/o servicios exentos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('402.04','Devoluciones, descuentos o bonificaciones de otros ingresos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('403','Otros ingresos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('403.01','Otros Ingresos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('403.02','Otros ingresos nacionales parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('403.03','Otros ingresos extranjeros parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('403.04','Ingresos por operaciones discontinuas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('403.05','Ingresos por condonación de adeudo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('501','Costo de venta y/o servicio')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('501.01','Costo de venta')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('501.02','Costo de servicios (Mano de obra)')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('501.03','Materia prima directa utilizada para la producción')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('501.04','Materia prima consumida en el proceso productivo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('501.05','Mano de obra directa consumida')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('501.06','Mano de obra directa')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('501.07','Cargos indirectos de producción')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('501.08','Otros conceptos de costo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('502','Compras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('502.01','Compras nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('502.02','Compras nacionales parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('502.03','Compras de Importación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('502.04','Compras de Importación partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('503','Devoluciones, descuentos o bonificaciones sobre compras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('503.01','Devoluciones, descuentos o bonificaciones sobre compras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504','Otras cuentas de costos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.01','Gastos indirectos de fabricación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.02','Gastos indirectos de fabricación de partes relacionadas nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.03','Gastos indirectos de fabricación de partes relacionadas extranjeras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.04','Otras cuentas de costos incurridos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.05','Otras cuentas de costos incurridos con partes relacionadas nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.06','Otras cuentas de costos incurridos con partes relacionadas extranjeras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.07','Depreciación de edificios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.08','Depreciación de maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.09','Depreciación de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.10','Depreciación de mobiliario y equipo de oficina')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.11','Depreciación de equipo de cómputo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.12','Depreciación de equipo de comunicación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.13','Depreciación de activos biológicos, vegetales y semovientes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.14','Depreciación de otros activos fijos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.15','Depreciación de ferrocarriles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.16','Depreciación de embarcaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.17','Depreciación de aviones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.18','Depreciación de troqueles, moldes, matrices y herramental')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.19','Depreciación de equipo de comunicaciones telefónicas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.20','Depreciación de equipo de comunicación satelital')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.21','Depreciación de equipo de adaptaciones para personas con capacidades diferentes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.22','Depreciación de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.23','Depreciación de adaptaciones y mejoras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.24','Depreciación de otra maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('504.25','Otras cuentas de costos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('505','Costo de activo fijo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('505.01','Costo por venta de activo fijo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('505.02','Costo por baja de activo fijo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601','Gastos generales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.01','Sueldos y salarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.02','Compensaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.03','Tiempos extras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.04','Premios de asistencia')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.05','Premios de puntualidad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.06','Vacaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.07','Prima vacacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.08','Prima dominical')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.09','Días festivos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.10','Gratificaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.11','Primas de antigüedad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.12','Aguinaldo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.13','Indemnizaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.14','Destajo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.15','Despensa')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.16','Transporte')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.17','Servicio médico')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.18','Ayuda en gastos funerarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.19','Fondo de ahorro')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.20','Cuotas sindicales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.21','PTU')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.22','Estímulo al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.23','Previsión social')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.24','Aportaciones para el plan de jubilación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.25','Otras prestaciones al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.26','Cuotas al IMSS')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.27','Aportaciones al infonavit')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.28','Aportaciones al SAR')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.29','Impuesto estatal sobre nóminas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.30','Otras aportaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.31','Asimilados a salarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.32','Servicios administrativos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.33','Servicios administrativos partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.34','Honorarios a personas físicas residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.35','Honorarios a personas físicas residentes nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.36','Honorarios a personas físicas residentes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.37','Honorarios a personas físicas residentes del extranjero partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.38','Honorarios a personas morales residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.39','Honorarios a personas morales residentes nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.40','Honorarios a personas morales residentes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.41','Honorarios a personas morales residentes del extranjero partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.42','Honorarios aduanales personas físicas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.43','Honorarios aduanales personas morales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.44','Honorarios al consejo de administración')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.45','Arrendamiento a personas físicas residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.46','Arrendamiento a personas morales residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.47','Arrendamiento a residentes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.48','Combustibles y lubricantes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.49','Viáticos y gastos de viaje')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.50','Teléfono, internet')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.51','Agua')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.52','Energía eléctrica')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.53','Vigilancia y seguridad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.54','Limpieza')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.55','Papelería y artículos de oficina')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.56','Mantenimiento y conservación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.57','Seguros y fianzas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.58','Otros impuestos y derechos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.59','Recargos fiscales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.60','Cuotas y suscripciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.61','Propaganda y publicidad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.62','Capacitación al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.63','Donativos y ayudas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.64','Asistencia técnica')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.65','Regalías sujetas a otros porcentajes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.66','Regalías sujetas al 5%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.67','Regalías sujetas al 10%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.68','Regalías sujetas al 15%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.69','Regalías sujetas al 25%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.70','Regalías sujetas al 30%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.71','Regalías sin retención')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.72','Fletes y acarreos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.73','Gastos de importación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.74','Comisiones sobre ventas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.75','Comisiones por tarjetas de crédito')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.76','Patentes y marcas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.77','Uniformes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.78','Prediales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.79','Gastos generales de urbanización')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.80','Gastos generales de construcción')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.81','Fletes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.82','Recolección de bienes del sector agropecuario y/o ganadero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.83','Gastos no deducibles (sin requisitos fiscales)')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('601.84','Otros gastos generales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602','Gastos de venta')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.01','Sueldos y salarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.02','Compensaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.03','Tiempos extras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.04','Premios de asistencia')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.05','Premios de puntualidad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.06','Vacaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.07','Prima vacacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.08','Prima dominical')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.09','Días festivos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.10','Gratificaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.11','Primas de antigüedad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.12','Aguinaldo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.13','Indemnizaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.14','Destajo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.15','Despensa')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.16','Transporte')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.17','Servicio médico')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.18','Ayuda en gastos funerarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.19','Fondo de ahorro')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.20','Cuotas sindicales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.21','PTU')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.22','Estímulo al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.23','Previsión social')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.24','Aportaciones para el plan de jubilación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.25','Otras prestaciones al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.26','Cuotas al IMSS')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.27','Aportaciones al infonavit')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.28','Aportaciones al SAR')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.29','Impuesto estatal sobre nóminas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.30','Otras aportaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.31','Asimilados a salarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.32','Servicios administrativos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.33','Servicios administrativos partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.34','Honorarios a personas físicas residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.35','Honorarios a personas físicas residentes nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.36','Honorarios a personas físicas residentes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.37','Honorarios a personas físicas residentes del extranjero partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.38','Honorarios a personas morales residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.39','Honorarios a personas morales residentes nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.40','Honorarios a personas morales residentes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.41','Honorarios a personas morales residentes del extranjero partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.42','Honorarios aduanales personas físicas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.43','Honorarios aduanales personas morales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.44','Honorarios al consejo de administración')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.45','Arrendamiento a personas físicas residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.46','Arrendamiento a personas morales residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.47','Arrendamiento a residentes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.48','Combustibles y lubricantes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.49','Viáticos y gastos de viaje')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.50','Teléfono, internet')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.51','Agua')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.52','Energía eléctrica')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.53','Vigilancia y seguridad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.54','Limpieza')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.55','Papelería y artículos de oficina')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.56','Mantenimiento y conservación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.57','Seguros y fianzas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.58','Otros impuestos y derechos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.59','Recargos fiscales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.60','Cuotas y suscripciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.61','Propaganda y publicidad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.62','Capacitación al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.63','Donativos y ayudas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.64','Asistencia técnica')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.65','Regalías sujetas a otros porcentajes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.66','Regalías sujetas al 5%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.67','Regalías sujetas al 10%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.68','Regalías sujetas al 15%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.69','Regalías sujetas al 25%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.70','Regalías sujetas al 30%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.71','Regalías sin retención')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.72','Fletes y acarreos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.73','Gastos de importación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.74','Comisiones sobre ventas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.75','Comisiones por tarjetas de crédito')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.76','Patentes y marcas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.77','Uniformes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.78','Prediales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.79','Gastos de venta de urbanización')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.80','Gastos de venta de construcción')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.81','Fletes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.82','Recolección de bienes del sector agropecuario y/o ganadero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.83','Gastos no deducibles (sin requisitos fiscales)')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('602.84','Otros gastos de venta')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603','Gastos de administración')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.01','Sueldos y salarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.02','Compensaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.03','Tiempos extras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.04','Premios de asistencia')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.05','Premios de puntualidad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.06','Vacaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.07','Prima vacacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.08','Prima dominical')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.09','Días festivos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.10','Gratificaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.11','Primas de antigüedad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.12','Aguinaldo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.13','Indemnizaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.14','Destajo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.15','Despensa')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.16','Transporte')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.17','Servicio médico')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.18','Ayuda en gastos funerarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.19','Fondo de ahorro')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.20','Cuotas sindicales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.21','PTU')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.22','Estímulo al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.23','Previsión social')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.24','Aportaciones para el plan de jubilación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.25','Otras prestaciones al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.26','Cuotas al IMSS')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.27','Aportaciones al infonavit')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.28','Aportaciones al SAR')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.29','Impuesto estatal sobre nóminas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.30','Otras aportaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.31','Asimilados a salarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.32','Servicios administrativos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.33','Servicios administrativos partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.34','Honorarios a personas físicas residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.35','Honorarios a personas físicas residentes nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.36','Honorarios a personas físicas residentes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.37','Honorarios a personas físicas residentes del extranjero partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.38','Honorarios a personas morales residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.39','Honorarios a personas morales residentes nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.40','Honorarios a personas morales residentes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.41','Honorarios a personas morales residentes del extranjero partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.42','Honorarios aduanales personas físicas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.43','Honorarios aduanales personas morales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.44','Honorarios al consejo de administración')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.45','Arrendamiento a personas físicas residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.46','Arrendamiento a personas morales residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.47','Arrendamiento a residentes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.48','Combustibles y lubricantes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.49','Viáticos y gastos de viaje')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.50','Teléfono, internet')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.51','Agua')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.52','Energía eléctrica')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.53','Vigilancia y seguridad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.54','Limpieza')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.55','Papelería y artículos de oficina')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.56','Mantenimiento y conservación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.57','Seguros y fianzas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.58','Otros impuestos y derechos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.59','Recargos fiscales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.60','Cuotas y suscripciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.61','Propaganda y publicidad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.62','Capacitación al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.63','Donativos y ayudas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.64','Asistencia técnica')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.65','Regalías sujetas a otros porcentajes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.66','Regalías sujetas al 5%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.67','Regalías sujetas al 10%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.68','Regalías sujetas al 15%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.69','Regalías sujetas al 25%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.70','Regalías sujetas al 30%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.71','Regalías sin retención')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.72','Fletes y acarreos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.73','Gastos de importación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.74','Patentes y marcas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.75','Uniformes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.76','Prediales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.77','Gastos de administración de urbanización')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.78','Gastos de administración de construcción')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.79','Fletes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.80','Recolección de bienes del sector agropecuario y/o ganadero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.81','Gastos no deducibles (sin requisitos fiscales)')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('603.82','Otros gastos de administración')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604','Gastos de fabricación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.01','Sueldos y salarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.02','Compensaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.03','Tiempos extras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.04','Premios de asistencia')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.05','Premios de puntualidad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.06','Vacaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.07','Prima vacacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.08','Prima dominical')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.09','Días festivos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.10','Gratificaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.11','Primas de antigüedad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.12','Aguinaldo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.13','Indemnizaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.14','Destajo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.15','Despensa')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.16','Transporte')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.17','Servicio médico')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.18','Ayuda en gastos funerarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.19','Fondo de ahorro')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.20','Cuotas sindicales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.21','PTU')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.22','Estímulo al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.23','Previsión social')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.24','Aportaciones para el plan de jubilación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.25','Otras prestaciones al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.26','Cuotas al IMSS')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.27','Aportaciones al infonavit')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.28','Aportaciones al SAR')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.29','Impuesto estatal sobre nóminas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.30','Otras aportaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.31','Asimilados a salarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.32','Servicios administrativos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.33','Servicios administrativos partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.34','Honorarios a personas físicas residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.35','Honorarios a personas físicas residentes nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.36','Honorarios a personas físicas residentes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.37','Honorarios a personas físicas residentes del extranjero partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.38','Honorarios a personas morales residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.39','Honorarios a personas morales residentes nacionales partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.40','Honorarios a personas morales residentes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.41','Honorarios a personas morales residentes del extranjero partes relacionadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.42','Honorarios aduanales personas físicas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.43','Honorarios aduanales personas morales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.44','Honorarios al consejo de administración')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.45','Arrendamiento a personas físicas residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.46','Arrendamiento a personas morales residentes nacionales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.47','Arrendamiento a residentes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.48','Combustibles y lubricantes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.49','Viáticos y gastos de viaje')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.50','Teléfono, internet')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.51','Agua')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.52','Energía eléctrica')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.53','Vigilancia y seguridad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.54','Limpieza')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.55','Papelería y artículos de oficina')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.56','Mantenimiento y conservación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.57','Seguros y fianzas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.58','Otros impuestos y derechos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.59','Recargos fiscales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.60','Cuotas y suscripciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.61','Propaganda y publicidad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.62','Capacitación al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.63','Donativos y ayudas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.64','Asistencia técnica')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.65','Regalías sujetas a otros porcentajes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.66','Regalías sujetas al 5%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.67','Regalías sujetas al 10%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.68','Regalías sujetas al 15%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.69','Regalías sujetas al 25%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.70','Regalías sujetas al 30%')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.71','Regalías sin retención')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.72','Fletes y acarreos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.73','Gastos de importación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.74','Patentes y marcas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.75','Uniformes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.76','Prediales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.77','Gastos de fabricación de urbanización')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.78','Gastos de fabricación de construcción')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.79','Fletes del extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.80','Recolección de bienes del sector agropecuario y/o ganadero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.81','Gastos no deducibles (sin requisitos fiscales)')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('604.82','Otros gastos de fabricación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605','Mano de obra directa')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.01','Mano de obra')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.02','Sueldos y Salarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.03','Compensaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.04','Tiempos extras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.05','Premios de asistencia')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.06','Premios de puntualidad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.07','Vacaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.08','Prima vacacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.09','Prima dominical')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.10','Días festivos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.11','Gratificaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.12','Primas de antigüedad')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.13','Aguinaldo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.14','Indemnizaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.15','Destajo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.16','Despensa')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.17','Transporte')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.18','Servicio médico')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.19','Ayuda en gastos funerarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.20','Fondo de ahorro')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.21','Cuotas sindicales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.22','PTU')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.23','Estímulo al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.24','Previsión social')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.25','Aportaciones para el plan de jubilación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.26','Otras prestaciones al personal')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.27','Asimilados a salarios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.28','Cuotas al IMSS')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.29','Aportaciones al infonavit')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.30','Aportaciones al SAR')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('605.31','Otros costos de mano de obra directa')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('606','Facilidades administrativas fiscales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('606.01','Facilidades administrativas fiscales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('607','Participación de los trabajadores en las utilidades')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('607.01','Participación de los trabajadores en las utilidades')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('608','Participación en resultados de subsidiarias')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('608.01','Participación en resultados de subsidiarias')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('609','Participación en resultados de asociadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('609.01','Participación en resultados de asociadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('610','Participación de los trabajadores en las utilidades diferida')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('610.01','Participación de los trabajadores en las utilidades diferida')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('611','Impuesto Sobre la renta')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('611.01','Impuesto Sobre la renta')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('611.02','Impuesto Sobre la renta por remanente distribuible')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('612','Gastos no deducibles para CUFIN')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('612.01','Gastos no deducibles para CUFIN')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613','Depreciación contable')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.01','Depreciación de edificios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.02','Depreciación de maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.03','Depreciación de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.04','Depreciación de mobiliario y equipo de oficina')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.05','Depreciación de equipo de cómputo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.06','Depreciación de equipo de comunicación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.07','Depreciación de activos biológicos, vegetales y semovientes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.08','Depreciación de otros activos fijos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.09','Depreciación de ferrocarriles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.10','Depreciación de embarcaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.11','Depreciación de aviones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.12','Depreciación de troqueles, moldes, matrices y herramental')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.13','Depreciación de equipo de comunicaciones telefónicas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.14','Depreciación de equipo de comunicación satelital')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.15','Depreciación de equipo de adaptaciones para personas con capacidades diferentes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.16','Depreciación de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.17','Depreciación de adaptaciones y mejoras')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('613.18','Depreciación de otra maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('614','Amortización contable')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('614.01','Amortización de gastos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('614.02','Amortización de gastos pre operativos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('614.03','Amortización de regalías, asistencia técnica y otros gastos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('614.04','Amortización de activos intangibles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('614.05','Amortización de gastos de organización')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('614.06','Amortización de investigación y desarrollo de mercado')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('614.07','Amortización de marcas y patentes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('614.08','Amortización de crédito mercantil')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('614.09','Amortización de gastos de instalación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('614.10','Amortización de otros activos diferidos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('701','Gastos financieros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('701.01','Pérdida cambiaria')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('701.02','Pérdida cambiaria nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('701.03','Pérdida cambiaria extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('701.04','Intereses a cargo bancario nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('701.05','Intereses a cargo bancario extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('701.06','Intereses a cargo de personas físicas nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('701.07','Intereses a cargo de personas físicas extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('701.08','Intereses a cargo de personas morales nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('701.09','Intereses a cargo de personas morales extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('701.10','Comisiones bancarias')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('701.11','Otros gastos financieros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('702','Productos financieros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('702.01','Utilidad cambiaria')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('702.02','Utilidad cambiaria nacional parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('702.03','Utilidad cambiaria extranjero parte relacionada')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('702.04','Intereses a favor bancarios nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('702.05','Intereses a favor bancarios extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('702.06','Intereses a favor de personas físicas nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('702.07','Intereses a favor de personas físicas extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('702.08','Intereses a favor de personas morales nacional')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('702.09','Intereses a favor de personas morales extranjero')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('702.10','Otros productos financieros')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703','Otros gastos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.01','Pérdida en venta y/o baja de terrenos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.02','Pérdida en venta y/o baja de edificios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.03','Pérdida en venta y/o baja de maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.04','Pérdida en venta y/o baja de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.05','Pérdida en venta y/o baja de mobiliario y equipo de oficina')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.06','Pérdida en venta y/o baja de equipo de cómputo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.07','Pérdida en venta y/o baja de equipo de comunicación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.08','Pérdida en venta y/o baja de activos biológicos, vegetales y semovientes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.09','Pérdida en venta y/o baja de otros activos fijos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.10','Pérdida en venta y/o baja de ferrocarriles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.11','Pérdida en venta y/o baja de embarcaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.12','Pérdida en venta y/o baja de aviones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.13','Pérdida en venta y/o baja de troqueles, moldes, matrices y herramental')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.14','Pérdida en venta y/o baja de equipo de comunicaciones telefónicas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.15','Pérdida en venta y/o baja de equipo de comunicación satelital')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.16','Pérdida en venta y/o baja de equipo de adaptaciones para personas con capacidades diferentes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.17','Pérdida en venta y/o baja de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.18','Pérdida en venta y/o baja de otra maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.19','Pérdida por enajenación de acciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.20','Pérdida por enajenación de partes sociales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('703.21','Otros gastos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704','Otros productos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.01','Ganancia en venta y/o baja de terrenos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.02','Ganancia en venta y/o baja de edificios')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.03','Ganancia en venta y/o baja de maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.04','Ganancia en venta y/o baja de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.05','Ganancia en venta y/o baja de mobiliario y equipo de oficina')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.06','Ganancia en venta y/o baja de equipo de cómputo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.07','Ganancia en venta y/o baja de equipo de comunicación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.08','Ganancia en venta y/o baja de activos biológicos, vegetales y semovientes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.09','Ganancia en venta y/o baja de otros activos fijos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.10','Ganancia en venta y/o baja de ferrocarriles')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.11','Ganancia en venta y/o baja de embarcaciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.12','Ganancia en venta y/o baja de aviones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.13','Ganancia en venta y/o baja de troqueles, moldes, matrices y herramental')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.14','Ganancia en venta y/o baja de equipo de comunicaciones telefónicas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.15','Ganancia en venta y/o baja de equipo de comunicación satelital')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.16','Ganancia en venta y/o baja de equipo de adaptaciones para personas con capacidades diferentes')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.17','Ganancia en venta de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.18','Ganancia en venta y/o baja de otra maquinaria y equipo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.19','Ganancia por enajenación de acciones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.20','Ganancia por enajenación de partes sociales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.21','Ingresos por estímulos fiscales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.22','Ingresos por condonación de adeudo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('704.23','Otros productos')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('801','UFIN del ejercicio')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('801.01','UFIN')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('801.02','Contra cuenta UFIN')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('802','CUFIN del ejercicio')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('802.01','CUFIN')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('802.02','Contra cuenta CUFIN')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('803','CUFIN de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('803.01','CUFIN de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('803.02','Contra cuenta CUFIN de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('804','CUFINRE del ejercicio')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('804.01','CUFINRE')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('804.02','Contra cuenta CUFINRE')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('805','CUFINRE de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('805.01','CUFINRE de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('805.02','Contra cuenta CUFINRE de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('806','CUCA del ejercicio')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('806.01','CUCA')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('806.02','Contra cuenta CUCA')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('807','CUCA de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('807.01','CUCA de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('807.02','Contra cuenta CUCA de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('808','Ajuste anual por inflación acumulable')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('808.01','Ajuste anual por inflación acumulable')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('808.02','Acumulación del ajuste anual inflacionario')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('809','Ajuste anual por inflación deducible')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('809.01','Ajuste anual por inflación deducible')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('809.02','Deducción del ajuste anual inflacionario')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('810','Deducción de inversión')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('810.01','Deducción de inversión')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('810.02','Contra cuenta deducción de inversiones')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('811','Utilidad o pérdida fiscal en venta y/o baja de activo fijo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('811.01','Utilidad o pérdida fiscal en venta y/o baja de activo fijo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('811.02','Contra cuenta utilidad o pérdida fiscal en venta y/o baja de activo fijo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('812','Utilidad o pérdida fiscal en venta acciones o partes sociales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('812.01','Utilidad o pérdida fiscal en venta acciones o partes sociales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('812.02','Contra cuenta utilidad o pérdida fiscal en venta acciones o partes sociales')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('813','Pérdidas fiscales pendientes de amortizar actualizadas de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('813.01','Pérdidas fiscales pendientes de amortizar actualizadas de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('813.02','Actualización de pérdidas fiscales pendientes de amortizar de ejercicios anteriores')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('814','Mercancías recibidas en consignación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('814.01','Mercancías recibidas en consignación')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('814.02','Consignación de mercancías recibidas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('815','Crédito fiscal de IVA e IEPS por la importación de mercancías para empresas certificadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('815.01','Crédito fiscal de IVA e IEPS por la importación de mercancías')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('815.02','Importación de mercancías con aplicación de crédito fiscal de IVA e IEPS')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('816','Crédito fiscal de IVA e IEPS por la importación de activos fijos para empresas certificadas')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('816.01','Crédito fiscal de IVA e IEPS por la importación de activo fijo')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('816.02','Importación de activo fijo con aplicación de crédito fiscal de IVA e IEPS')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('899','Otras cuentas de orden')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('899.01','Otras cuentas de orden')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('899.02','Contra cuenta otras cuentas de orden')
go
INSERT INTO $$COMPANIA$$.U_COD_AGRUPADOR (U_CODIGO, U_DESCRIP) VALUES ('000','Código para uso exclusivo de contribuyentes del sector financiero')
go
