
 
 ALTER TABLE ASIENTO_DE_DIARIO
        ADD CONSTRAINT ASNTDUSR
               FOREIGN KEY (ULTIMO_USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE ASIENTO_DE_DIARIO
        ADD CONSTRAINT ASNTDPAQ
               FOREIGN KEY (PAQUETE)
                              REFERENCES PAQUETE
go
 
 
 ALTER TABLE ASIENTO_DE_DIARIO
        ADD CONSTRAINT ASNTDTAS
               FOREIGN KEY (TIPO_ASIENTO)
                              REFERENCES TIPO_ASIENTO
go
 
 
 ALTER TABLE ASIENTO_DE_DIARIO
        ADD CONSTRAINT USUARIOCREA_ASNTDI
               FOREIGN KEY (USUARIO_CREACION)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE ASIENTO_DIST_LINEA
        ADD CONSTRAINT ADLINEAASNTDIST
               FOREIGN KEY (ASIENTO_DISTRIBUID)
                              REFERENCES ASIENTO_DISTRIBUID
                              ON DELETE CASCADE	
go
 
 
 ALTER TABLE ASIENTO_DIST_LINEA
        ADD CONSTRAINT CTROCTAADL
               FOREIGN KEY (CENTRO_COSTO, CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ASIENTO_DIST_LINEA
        ADD CONSTRAINT ASNTDISTLINNIT
               FOREIGN KEY (NIT)
                              REFERENCES NIT
go
 

ALTER TABLE ASIENTO_DIST_LINEA
        ADD CONSTRAINT ASNTDISTLINEAFASEPY
               FOREIGN KEY (PROYECTO,FASE)
                              REFERENCES FASE_PY (PROYECTO,FASE)
go                              

 
 ALTER TABLE ASIENTO_DISTRIBUID
        ADD CONSTRAINT ADCREAUSR
               FOREIGN KEY (USUARIO_CREACION)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE ASIENTO_DISTRIBUID
        ADD CONSTRAINT ADMODIUSR
               FOREIGN KEY (USUARIO_ULT_MODIF)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE ASIENTO_DISTRIBUID
        ADD CONSTRAINT ADAPLICUSR
               FOREIGN KEY (USUARIO_ULT_APLIC)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE ASIENTO_DISTRIBUID
        ADD CONSTRAINT ASNTDISTPAQ
               FOREIGN KEY (PAQUETE)
                              REFERENCES PAQUETE
go
 
 
 ALTER TABLE ASIENTO_DISTRIBUID
        ADD CONSTRAINT ASNTDISTTASNT
               FOREIGN KEY (TIPO_ASIENTO)
                              REFERENCES TIPO_ASIENTO
go
 
 
 ALTER TABLE ASIENTO_MARCADO
        ADD CONSTRAINT ASNTMARCASNTDIA
               FOREIGN KEY (ASIENTO)
                              REFERENCES ASIENTO_DE_DIARIO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE ASIENTO_MARCADO
        ADD CONSTRAINT ASNTMARCUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE ASIENTO_MARCADO
        ADD CONSTRAINT ASNTMARCPAQ
               FOREIGN KEY (PAQUETE)
                              REFERENCES PAQUETE
go
 
 
 ALTER TABLE ASIENTO_MAYORIZADO
        ADD CONSTRAINT ASNTMUSR
               FOREIGN KEY (ULTIMO_USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE ASIENTO_MAYORIZADO
        ADD CONSTRAINT ASNTMAUD
               FOREIGN KEY (MAYOR_AUDITORIA)
                              REFERENCES MAYOR_AUDITORIA
go
 
 
 ALTER TABLE ASIENTO_MAYORIZADO
        ADD CONSTRAINT ASNTMTAS
               FOREIGN KEY (TIPO_ASIENTO)
                              REFERENCES TIPO_ASIENTO
go
 
 
 ALTER TABLE ASIENTO_MAYORIZADO
        ADD CONSTRAINT USUARIOCREA_ASNTMA
               FOREIGN KEY (USUARIO_CREACION)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE ASIENTO_RECU_LINEA
        ADD CONSTRAINT ARLNAREC
               FOREIGN KEY (ASIENTO_RECURRENTE)
                              REFERENCES ASIENTO_RECURRENTE
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE ASIENTO_RECU_LINEA
        ADD CONSTRAINT ASNTRECULINNIT
               FOREIGN KEY (NIT)
                              REFERENCES NIT
go
 
 
 ALTER TABLE ASIENTO_RECU_LINEA
        ADD CONSTRAINT ASNTRCC
               FOREIGN KEY (CENTRO_COSTO, CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go
 
 
ALTER TABLE ASIENTO_RECU_LINEA
        ADD CONSTRAINT ASNTRECULINEAFASEPY
               FOREIGN KEY (PROYECTO,FASE)
                              REFERENCES FASE_PY(PROYECTO,FASE)
go                             


 
 ALTER TABLE ASIENTO_RECURRENTE
        ADD CONSTRAINT ASNTRUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE ASIENTO_RECURRENTE
        ADD CONSTRAINT ASREUSUL
               FOREIGN KEY (USUARIO_ULT_APLIC)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE ASIENTO_RECURRENTE
        ADD CONSTRAINT ASNTRTA
               FOREIGN KEY (TIPO_ASIENTO)
                              REFERENCES TIPO_ASIENTO
go
 
 
 ALTER TABLE ASIENTO_RECURRENTE
        ADD CONSTRAINT ASNTRPAQ
               FOREIGN KEY (PAQUETE)
                              REFERENCES PAQUETE
go
 
 
 
 
 ALTER TABLE CENTRO_CUENTA
        ADD CONSTRAINT CNTCTACT
               FOREIGN KEY (CUENTA_CONTABLE)
                              REFERENCES CUENTA_CONTABLE
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE CENTRO_CUENTA
        ADD CONSTRAINT CNTCTACN
               FOREIGN KEY (CENTRO_COSTO)
                              REFERENCES CENTRO_COSTO
                              	ON DELETE CASCADE
go


 ALTER TABLE CENTRO_CUENTA
        ADD CONSTRAINT CC_GASTO
               FOREIGN KEY (CENTRO_GASTO, CUENTA_GASTO)
                              REFERENCES CENTRO_CUENTA  (CENTRO_COSTO, CUENTA_CONTABLE)
go



 ALTER TABLE CENTRO_CUENTA
        ADD CONSTRAINT CC_POZO
               FOREIGN KEY (CENTRO_POZO, CUENTA_POZO)
                              REFERENCES CENTRO_CUENTA (CENTRO_COSTO, CUENTA_CONTABLE)
go
 
 
 ALTER TABLE CORRIDA_AD
        ADD CONSTRAINT CORUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CTA_AJUSTE_INFL
        ADD CONSTRAINT DBAJUCNTRA
               FOREIGN KEY (CONTRA_CTA_AJUSTE)
                              REFERENCES CUENTA_CONTABLE
go
 
 
 ALTER TABLE CTA_AJUSTE_INFL
        ADD CONSTRAINT DBAJUAJTE
               FOREIGN KEY (CTA_AJUSTE)
                              REFERENCES CUENTA_CONTABLE
go
 
 
 ALTER TABLE CTA_AJUSTE_INFL
        ADD CONSTRAINT DBAJUAJSTA
               FOREIGN KEY (CTA_AJUSTABLE)
                              REFERENCES CUENTA_CONTABLE
go
 
 
 ALTER TABLE CUENTA_CONTABLE
        ADD CONSTRAINT CTACBLSECCTA
               FOREIGN KEY (SECCION_CUENTA)
                              REFERENCES SECCION_CUENTA
go
 
 
 ALTER TABLE CUENTA_CONTABLE
        ADD CONSTRAINT USUOWNCUEN
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CUENTA_CONTABLE
        ADD CONSTRAINT USUULTMOD
               FOREIGN KEY (USUARIO_ULT_MOD)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CUENTA_CONTABLE
        ADD CONSTRAINT CTACTCMB
               FOREIGN KEY (TIPO_CAMBIO)
                              REFERENCES TIPO_CAMBIO
go
 
 
 ALTER TABLE CUENTA_CONTABLE
        ADD CONSTRAINT UNIDAD_CTA_CONTA
               FOREIGN KEY (UNIDAD)
                              REFERENCES UNIDAD
go
 
 
 ALTER TABLE CUENTA_SECCION 
 	ADD  CONSTRAINT FK_CUENTA_SECCION_CUENTA_CONTABLE 
 		FOREIGN KEY(CUENTA_CONTABLE)
 			REFERENCES CUENTA_CONTABLE (CUENTA_CONTABLE)
 
 
 go
 
 
 ALTER TABLE CUENTA_SECCION 
 	ADD  CONSTRAINT FK_CUENTA_SECCION_SUBSECCION_REPORTES 
 		FOREIGN KEY(TIPO_R, CODIGO_R, SECCION_R, SUBSECCION)
 			REFERENCES SUBSECCION_REPORTES (TIPO_R, CODIGO_R, SECCION_R, SUBSECCION)
 
 
 go 
 
 
 
 ALTER TABLE DETALLE_CORRIDA
        ADD CONSTRAINT DETCOR
               FOREIGN KEY (CORRIDA_AD)
                              REFERENCES CORRIDA_AD
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE DETALLE_CORRIDA
        ADD CONSTRAINT DETCORAD
               FOREIGN KEY (ASIENTO_DISTRIBUID)
                              REFERENCES ASIENTO_DISTRIBUID
go
 
 
 ALTER TABLE DIARIO
        ADD CONSTRAINT DIAASNT
               FOREIGN KEY (ASIENTO)
                              REFERENCES ASIENTO_DE_DIARIO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE DIARIO
        ADD CONSTRAINT DIACTAC
               FOREIGN KEY (CENTRO_COSTO, CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE DIARIO
        ADD CONSTRAINT DIARIONIT
               FOREIGN KEY (NIT)
                              REFERENCES NIT
go
 

ALTER TABLE DIARIO
        ADD CONSTRAINT DIAFASPY
               FOREIGN KEY (PROYECTO, FASE)
                              REFERENCES FASE_PY ( PROYECTO, FASE )
go                              


ALTER TABLE DIFERIDO
        ADD CONSTRAINT DIFERUSUARIOANUL
               FOREIGN KEY (USUARIO_ANULACION)
                              REFERENCES ERPADMIN.USUARIO
go    


ALTER TABLE $$COMPANIA$$.DIFERIDO
	ADD CONSTRAINT FKIMPDIFE 
		FOREIGN KEY (CONCEPTO_ME)
			REFERENCES $$COMPANIA$$.CONCEPTOS_ME (CONCEPTO)
go


ALTER TABLE $$COMPANIA$$.DIFERIDO_DOC_CC 
        ADD CONSTRAINT XDIFERIDO
               FOREIGN KEY (DIFERIDO)
                              REFERENCES $$COMPANIA$$.DIFERIDO
							  ON DELETE CASCADE
go

ALTER TABLE $$COMPANIA$$.DIFERIDO_DOC_CC 
        ADD CONSTRAINT XDIFERIDODOCC
               FOREIGN KEY (DOCUMENTO, TIPO_DOC)
                              REFERENCES $$COMPANIA$$.DOCUMENTOS_CC(DOCUMENTO, TIPO)
go



ALTER TABLE $$COMPANIA$$.DIFERIDO_DOC_CP
        ADD CONSTRAINT XDIFERIDOCP
               FOREIGN KEY (DIFERIDO)
                              REFERENCES $$COMPANIA$$.DIFERIDO
							  ON DELETE CASCADE
go


ALTER TABLE $$COMPANIA$$.DIFERIDOS_IMPUESTOS
	ADD CONSTRAINT FKDIFIMP
		FOREIGN KEY (DIFERIDO)
			REFERENCES $$COMPANIA$$.DIFERIDO (DIFERIDO)
go

ALTER TABLE $$COMPANIA$$.DIFERIDOS_IMPUESTOS
	ADD CONSTRAINT FKDIFCODIMP
		FOREIGN KEY (IMPUESTO)
			REFERENCES $$COMPANIA$$.IMPUESTO (IMPUESTO)
go

ALTER TABLE $$COMPANIA$$.DIFERIDOS_IMPUESTOS
	ADD CONSTRAINT FKDIFIMPCME
		FOREIGN KEY (CONCEPTO_ME)
			REFERENCES $$COMPANIA$$.CONCEPTOS_ME (CONCEPTO)
go

ALTER TABLE $$COMPANIA$$.DIFERIDOS_IMPUESTOS
	ADD CONSTRAINT FKDIFTIMP
		FOREIGN KEY (TIPO_IMPUESTO)
			REFERENCES $$COMPANIA$$.TIPO_IMPUESTO (TIPO_IMPUESTO)
go
 
 ALTER TABLE GLOBALES_CG
        ADD CONSTRAINT GBCGCTAPD
               FOREIGN KEY (CTR_PERD_DIFCAMDOL, CTA_PERD_DIFCAMDOL)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE GLOBALES_CG
        ADD CONSTRAINT GBCGCTAPL
               FOREIGN KEY (CTR_PERD_DIFCAMLOC, CTA_PERD_DIFCAMLOC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE GLOBALES_CG
        ADD CONSTRAINT GBCGCTAD
               FOREIGN KEY (CTR_DIFCAMBIODOLAR, CTA_DIFCAMBIODOLAR)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE GLOBALES_CG
        ADD CONSTRAINT GBCGCTAL
               FOREIGN KEY (CTR_DIFCAMBIOLOCAL, CTA_DIFCAMBIOLOCAL)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE GLOBALES_CG
        ADD CONSTRAINT CTRCTOCIERRE_GLOCG
               FOREIGN KEY (CTR_CIERRE)
                              REFERENCES CENTRO_COSTO
go
 
 
 ALTER TABLE GLOBALES_CG
        ADD CONSTRAINT CTACTACIERRE_GLOCG
               FOREIGN KEY (CTA_CIERRE)
                              REFERENCES CUENTA_CONTABLE
go
 
 
 ALTER TABLE GLOBALES_CG
        ADD CONSTRAINT TIPOASNTANUAL_CG
               FOREIGN KEY (TIP_ASNT_CIERRE_AN)
                              REFERENCES TIPO_ASIENTO
go
 
 
ALTER TABLE GLOBALES_CG
	ADD CONSTRAINT GLOBCGPRESUPCR
		FOREIGN KEY (PRESUPUESTO_CR)
			REFERENCES PRESUPUESTO_CR (PRESUPUESTO)
go

ALTER TABLE GLOBALES_CG
	ADD CONSTRAINT GLOBCGPAQUETECR
		FOREIGN KEY (PAQUETE_CR)
			REFERENCES PAQUETE_CR (PAQUETE)
go

ALTER TABLE $$COMPANIA$$.GLOBALES_CG
	ADD CONSTRAINT CTRCTAUTLLOCAL
		FOREIGN KEY (CTR_UTL_LOCAL,CTA_UTL_LOCAL)
			REFERENCES $$COMPANIA$$.CENTRO_CUENTA 
go
			
ALTER TABLE $$COMPANIA$$.GLOBALES_CG
	ADD CONSTRAINT CTRCTAUTLDOLAR
		FOREIGN KEY (CTR_UTL_DOLAR,CTA_UTL_DOLAR)
			REFERENCES $$COMPANIA$$.CENTRO_CUENTA 
go
			
ALTER TABLE $$COMPANIA$$.GLOBALES_CG
	ADD CONSTRAINT CTRCTAPERDLOCAL
		FOREIGN KEY (CTR_PERD_LOCAL,CTA_PERD_LOCAL)
			REFERENCES $$COMPANIA$$.CENTRO_CUENTA 
go
			
ALTER TABLE $$COMPANIA$$.GLOBALES_CG
	ADD CONSTRAINT CTRCTAPERDDOLAR
		FOREIGN KEY (CTR_PERD_DOLAR,CTA_PERD_DOLAR)
			REFERENCES $$COMPANIA$$.CENTRO_CUENTA 
go
 
ALTER TABLE HIST_CIERRE_CG
        ADD CONSTRAINT HCIEAUD
               FOREIGN KEY (MAYOR_AUDITORIA)
                              REFERENCES MAYOR_AUDITORIA
go
                              
 ALTER TABLE HIST_CIERRE_CG
        ADD CONSTRAINT HCIEPERCONT
               FOREIGN KEY (FECHA_CIERRE, CONTABILIDAD)
                              REFERENCES PERIODO_CONTABLE 
go                              
 

ALTER TABLE HIST_DIFCAM_CG 
         ADD CONSTRAINT USUARHISTDFCG
         	FOREIGN KEY  ( usuario_auditoria)
         		REFERENCES ERPADMIN.USUARIO(USUARIO)
go         		

 
 ALTER TABLE MAYOR
        ADD CONSTRAINT MAYTASNT
               FOREIGN KEY (TIPO_ASIENTO)
                              REFERENCES TIPO_ASIENTO
go
 
 
 ALTER TABLE MAYOR
        ADD CONSTRAINT MAYORASN
               FOREIGN KEY (ASIENTO)
                              REFERENCES ASIENTO_MAYORIZADO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE MAYOR
        ADD CONSTRAINT MAYCTAC
               FOREIGN KEY (CENTRO_COSTO, CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE MAYOR
        ADD CONSTRAINT MAYORNIT
               FOREIGN KEY (NIT)
                              REFERENCES NIT
go
 


ALTER TABLE MAYOR
        ADD CONSTRAINT MAYFASPY
               FOREIGN KEY (PROYECTO, FASE)
                              REFERENCES FASE_PY ( PROYECTO, FASE )
go                              


 
 ALTER TABLE MAYOR_AUDITORIA
        ADD CONSTRAINT AUDMYUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go


ALTER TABLE MAYOR_DIVISION_GEOGRAFICA
	ADD CONSTRAINT FKMAYORDIVGEODIVGEO2
		FOREIGN KEY(PAIS,DIVISION_GEOGRAFICA1,DIVISION_GEOGRAFICA2)
			REFERENCES DIVISION_GEOGRAFICA2(PAIS,DIVISION_GEOGRAFICA1,DIVISION_GEOGRAFICA2)
				ON DELETE CASCADE
go
				
				
 
 ALTER TABLE PAQUETE
        ADD CONSTRAINT PAQCREAD
               FOREIGN KEY (USUARIO_CREADOR)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE PAQUETE
        ADD CONSTRAINT PAQULTUS
               FOREIGN KEY (ULTIMO_USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 ALTER TABLE SALDO
        ADD CONSTRAINT SLDCTAC
               FOREIGN KEY (CENTRO_COSTO, CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go

ALTER TABLE SALDO_NIT
        ADD CONSTRAINT FK_SLDCTACNIT
               FOREIGN KEY (CENTRO_COSTO, CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go                              
 
 
 ALTER TABLE SECCION_REPORTES 
 	ADD  CONSTRAINT FK_SECCION_REPORTES_REPORTES_CONTABLES 
 		FOREIGN KEY(TIPO_R, CODIGO_R)
 			REFERENCES REPORTES_CONTABLES (TIPO_R, CODIGO_R)

go
 
 ALTER TABLE SUBSECCION_REPORTES 
 	ADD  CONSTRAINT FK_SUBSECCION_REPORTES_SECCION_REPORTES 
 		FOREIGN KEY(TIPO_R, CODIGO_R, SECCION_R)
 			REFERENCES SECCION_REPORTES (TIPO_R, CODIGO_R, SECCION_R)
go
 
 
ALTER TABLE $$COMPANIA$$.TIPO_DIFERIDO
	ADD CONSTRAINT FKIMPDIF 
		FOREIGN KEY (CONCEPTO_ME)
			REFERENCES $$COMPANIA$$.CONCEPTOS_ME (CONCEPTO)
go
 
 ALTER TABLE USUARIO_PAQUETE
        ADD CONSTRAINT USRPAQUS
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE USUARIO_PAQUETE
        ADD CONSTRAINT USRPAQPQ
               FOREIGN KEY (PAQUETE)
                              REFERENCES PAQUETE
                              ON DELETE CASCADE
go

ALTER TABLE $$COMPANIA$$.VALOR_ADICIONAL_ME
	ADD CONSTRAINT FKIMPVAM
		FOREIGN KEY (TIPO_IMPUESTO)
			REFERENCES $$COMPANIA$$.TIPO_IMPUESTO (TIPO_IMPUESTO)
go
 
 