
 
 CREATE TABLE ASIENTO_DE_DIARIO (
        ASIENTO              	VARCHAR(10) 	NOT NULL,
        PAQUETE              	VARCHAR(4) 		NOT NULL,
        TIPO_ASIENTO         	VARCHAR(4) 		NOT NULL,
        FECHA                	DATETIME 		NOT NULL,
        CONTABILIDAD         	VARCHAR(1) 		NOT NULL,
        ORIGEN               	VARCHAR(4) 		NOT NULL,
        CLASE_ASIENTO        	VARCHAR(1) 		NOT NULL,
        TOTAL_DEBITO_LOC     	DECIMAL(28,8) 	NOT NULL,
        TOTAL_DEBITO_DOL     	DECIMAL(28,8) 	NOT NULL,
        TOTAL_CREDITO_LOC    	DECIMAL(28,8) 	NOT NULL,
        TOTAL_CREDITO_DOL    	DECIMAL(28,8) 	NOT NULL,
        ULTIMO_USUARIO       	VARCHAR(25) 	NOT NULL,
        FECHA_ULT_MODIF      	DATETIME 		NOT NULL,
        MARCADO              	VARCHAR(1) 		NOT NULL,
        NOTAS                	TEXT 			NULL,
        TOTAL_CONTROL_LOC    	DECIMAL(28,8) 	NOT NULL,
        TOTAL_CONTROL_DOL    	DECIMAL(28,8) 	NOT NULL,
        USUARIO_CREACION     	VARCHAR(25) 	NOT NULL,
        FECHA_CREACION       	DATETIME 		NOT NULL,
        DEPENDENCIA 			VARCHAR(10) 	NULL,
        DOCUMENTO_GLOBAL 		VARCHAR(50) 	NULL
		
 )
go
 
 
 ALTER TABLE ASIENTO_DE_DIARIO
        ADD CONSTRAINT XPKASIENTO_DE_DIARIO PRIMARY KEY NONCLUSTERED (
               ASIENTO)
go
 
 
 CREATE TABLE ASIENTO_DIST_LINEA (
        TIPO_LINEA           	VARCHAR(1) 	NOT NULL,
        CONSECUTIVO          	int 		NOT NULL,
        ASIENTO_DISTRIBUID   	VARCHAR(10) 	NOT NULL,
        NIT                  	VARCHAR(20) 	NULL,
        CENTRO_COSTO         	VARCHAR(25) 	NOT NULL,
        CUENTA_CONTABLE      	VARCHAR(25) 	NOT NULL,
        REFERENCIA           	VARCHAR(249) 	NOT NULL,
        PORCENTAJE           	DECIMAL(28,8) 	NOT NULL,
        FUNCION              	VARCHAR(1) 	NOT NULL,
        DETALLE_FUNCION      	TEXT 		NULL,
        INDICE_FUNCION       	smallint 	NULL,
        COMENTARIO           	VARCHAR(254) 	NULL,
        MONTO_BASE           	DECIMAL(28,8) 	NULL,
        MONEDA_BASE          	VARCHAR(1) 	NOT NULL,
        USA_TCAMBIO_EXT      	VARCHAR(1) 	NOT NULL,
        PROYECTO 		VARCHAR(25) 	NULL,
	FASE 	   		VARCHAR(25) 	NULL
 )
go
 
 
 ALTER TABLE ASIENTO_DIST_LINEA
        ADD CONSTRAINT XPKASIENTO_DIST_LINEA PRIMARY KEY (TIPO_LINEA, 
               CONSECUTIVO, ASIENTO_DISTRIBUID)
go
 
 
 CREATE TABLE ASIENTO_DISTRIBUID (
        ASIENTO_DISTRIBUID   VARCHAR(10) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        TIPO_DISTRIBUCION    VARCHAR(1) NOT NULL,
        SALDO_DISTRIBUIR     VARCHAR(1) NOT NULL,
        MODO_DISTRIBUCION    VARCHAR(1) NOT NULL,
        SECUENCIA            smallint NULL,
        ACTIVO               VARCHAR(1) NOT NULL,
        MARCADO              VARCHAR(1) NOT NULL,
        MODALIDAD_APLIC      smallint NOT NULL,
        TIPO_ASIENTO         VARCHAR(4) NULL,
        PAQUETE              VARCHAR(4) NULL,
        FUENTE               VARCHAR(40) NULL,
        CONTABILIDAD         VARCHAR(1) NOT NULL,
        FCH_HORA_CREACION    DATETIME NULL,
        USUARIO_CREACION     VARCHAR(25) NULL,
        FCH_HORA_ULT_MODIF   DATETIME NULL,
        USUARIO_ULT_MODIF    VARCHAR(25) NULL,
        FCH_HORA_ULT_APLIC   DATETIME NULL,
        USUARIO_ULT_APLIC    VARCHAR(25) NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE ASIENTO_DISTRIBUID
        ADD CONSTRAINT XPKASIENTO_DISTRIBUID PRIMARY KEY (
               ASIENTO_DISTRIBUID)
go
 
 
 CREATE TABLE ASIENTO_MARCADO (
        USUARIO              VARCHAR(25) NOT NULL,
        PAQUETE              VARCHAR(4) NOT NULL,
        ASIENTO              VARCHAR(10) NOT NULL
 )
go
 
 
 ALTER TABLE ASIENTO_MARCADO
        ADD CONSTRAINT XPKASIENTO_MARCADO PRIMARY KEY (USUARIO, 
               PAQUETE, ASIENTO)
go
 
 
 CREATE TABLE ASIENTO_MAYORIZADO (
        ASIENTO              	VARCHAR(10) 	NOT NULL,
        MAYOR_AUDITORIA      	int 		NOT NULL,
        TIPO_ASIENTO         	VARCHAR(4) 	NOT NULL,
        FECHA                	DATETIME 	NOT NULL,
        CONTABILIDAD         	VARCHAR(1) 	NOT NULL,
        ORIGEN               	VARCHAR(4) 	NOT NULL,
        CLASE_ASIENTO        	VARCHAR(1) 	NOT NULL,
        ULTIMO_USUARIO       	VARCHAR(25) 	NOT NULL,
        FECHA_ULT_MODIF      	DATETIME 	NOT NULL,
        MONTO_TOTAL_LOCAL    	DECIMAL(28,8) 	NOT NULL,
        MONTO_TOTAL_DOLAR    	DECIMAL(28,8) 	NOT NULL,
        NOTAS                	TEXT 		NULL,
        USUARIO_CREACION     	VARCHAR(25) 	NOT NULL,
        FECHA_CREACION       	DATETIME 	NOT NULL,
        EXPORTADO            	VARCHAR(1) 	NOT NULL,
        TIPO_INGRESO_MAYOR   	VARCHAR(1) 	NOT NULL,
        DEPENDENCIA 		VARCHAR(10)	NULL,
        DOCUMENTO_GLOBAL 	VARCHAR(50) 	NULL
 )
go
 
 
 ALTER TABLE ASIENTO_MAYORIZADO
        ADD CONSTRAINT XPKASIENTO_MAYORIZ PRIMARY KEY (ASIENTO)
go
 
 
 CREATE TABLE ASIENTO_RECU_LINEA (
        ASIENTO_RECURRENTE   	VARCHAR(10) 	NOT NULL,
        ASIENTO_RECU_LINEA   	smallint 	NOT NULL,
        NIT                  	VARCHAR(20) 	NULL,
        CENTRO_COSTO         	VARCHAR(25) 	NOT NULL,
        CUENTA_CONTABLE      	VARCHAR(25) 	NOT NULL,
        DEBITO               	DECIMAL(28,8) 	NULL,
        CREDITO              	DECIMAL(28,8) 	NULL,
        USA_TCAMBIO_EXT      	VARCHAR(1) 	NOT NULL,
        REFERENCIA           	VARCHAR(249) 	NOT NULL,
        PROYECTO 		VARCHAR(25) 	NULL,
	FASE 	   		VARCHAR(25) 	NULL
 )
go
 
 
 ALTER TABLE ASIENTO_RECU_LINEA
        ADD CONSTRAINT ASIENTO_RECU_LIPK PRIMARY KEY NONCLUSTERED (
               ASIENTO_RECURRENTE, ASIENTO_RECU_LINEA)
go
 
 
 CREATE TABLE ASIENTO_RECURRENTE (
        ASIENTO_RECURRENTE   VARCHAR(10) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        TIPO                 VARCHAR(1) NOT NULL,
        MODALIDAD_APLIC      smallint NOT NULL,
        UNIDAD               VARCHAR(10) NULL,
        PAQUETE              VARCHAR(4) NULL,
        TIPO_ASIENTO         VARCHAR(4) NOT NULL,
        CONTABILIDAD         VARCHAR(1) NOT NULL,
        MONEDA               VARCHAR(1) NOT NULL,
        USUARIO_ULT_APLIC    VARCHAR(25) NULL,
        FCH_HORA_ULT_APLIC   DATETIME NULL,
        USUARIO              VARCHAR(25) NOT NULL,
        FECHA_HORA           DATETIME NOT NULL,
        MARCADO              VARCHAR(1) NOT NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE ASIENTO_RECURRENTE
        ADD CONSTRAINT ASIENTO_RECURREPK PRIMARY KEY NONCLUSTERED (
               ASIENTO_RECURRENTE)
go
 
 
 CREATE TABLE CENTRO_CUENTA (
        CENTRO_COSTO         VARCHAR(25) NOT NULL,
        CUENTA_CONTABLE      VARCHAR(25) NOT NULL,
        ESTADO               VARCHAR(1) NOT NULL,
        CENTRO_POZO          VARCHAR(25) NULL,
        CUENTA_POZO          VARCHAR(25) NULL,
        CENTRO_GASTO         VARCHAR(25) NULL,
        CUENTA_GASTO         VARCHAR(25) NULL,
        CENTRO_CONSOLIDA     VARCHAR(25) NULL,
        CUENTA_CONSOLIDA     VARCHAR(25) NULL
 )
go
 
 
 ALTER TABLE CENTRO_CUENTA
        ADD CONSTRAINT CENTRO_CUENTAPK PRIMARY KEY NONCLUSTERED (
               CENTRO_COSTO, CUENTA_CONTABLE)
go
 

CREATE TABLE CG_AUX 	(
	GUID_ORIGEN 	VARCHAR(48) 	NOT NULL,
	TABLA_ORIGEN 	VARCHAR(30) 	NOT NULL,
	ASIENTO 	VARCHAR(10) 	NOT NULL,
	LINEA		INT		NOT NULL,
	COMENTARIO	TEXT 		NULL	
 )
go

ALTER TABLE CG_AUX ADD CONSTRAINT XPKCG_AUX 
	PRIMARY KEY ( GUID_ORIGEN, TABLA_ORIGEN, ASIENTO, LINEA )
go	


CREATE TABLE CG_CERTIFICADO_RET
(
	GUID 				VARCHAR(48)  	NOT NULL,
	ASIENTO				VARCHAR(10)  	NULL,	
	CONSECUTIVO			INT  	 	NULL,
	CUENTA_CONTABLE			VARCHAR(25)  	NULL,
	DESCRIPCION_CUENTA		VARCHAR(60)  	NULL,
	NIT				VARCHAR(20)  	NULL,
	RAZON_SOCIAL			VARCHAR(80)  	NULL,
	FECHA				DATETIME	NULL,
	DEBITO_LOCAL			DECIMAL(28,8)  	NULL,
	CREDITO_LOCAL			DECIMAL(28,8)  	NULL,
	DEBITO_DOLAR			DECIMAL(28,8)  	NULL,
	CREDITO_DOLAR			DECIMAL(28,8)  	NULL,
	BASE_DOLAR			DECIMAL(28,8)  	NULL,
	BASE_LOCAL			DECIMAL(28,8)  	NULL,
	SALDO_NORMAL			VARCHAR(1)     	NULL,	
	PAIS				VARCHAR(4)    	NULL,
	DIV_GEO1			VARCHAR(12)   	NULL,
	DIV_GEO2			VARCHAR(12)   	NULL,
	UBICACION			VARCHAR(40)   	NULL,
	CONTABILIDAD 			VARCHAR(1) 	NOT NULL DEFAULT ('F')
)
go


 
 CREATE TABLE CORRIDA_AD (
        CORRIDA_AD           int NOT NULL,
        FECHA                DATETIME NOT NULL,
        USUARIO              VARCHAR(25) NOT NULL,
        CANT_PLANTILLAS      smallint NOT NULL
 )
go
 
 
 ALTER TABLE CORRIDA_AD
        ADD CONSTRAINT XPKCORRIDA_AD PRIMARY KEY (CORRIDA_AD)
go
 
 
 CREATE TABLE CTA_AJUSTE_INFL (
        CTA_AJUSTABLE        VARCHAR(25) NOT NULL,
        CTA_AJUSTE           VARCHAR(25) NOT NULL,
        CONTRA_CTA_AJUSTE    VARCHAR(25) NOT NULL
 )
go
 
 
 ALTER TABLE CTA_AJUSTE_INFL
        ADD CONSTRAINT XPKCTA_AJUSTE_INFL PRIMARY KEY (CTA_AJUSTABLE)
go


CREATE TABLE CUADRES_CG	(
	CUADRES_CG	INT	 	NOT NULL,
	DESCRIPCION 	VARCHAR(40) 	NOT NULL,
	MODULO 		VARCHAR(4) 	NOT NULL,
	FECHA		DATETIME 	NOT NULL,
	FECHA_DESDE	DATETIME 	NOT NULL,
	FECHA_HASTA	DATETIME 	NOT NULL,
	FILTROS		VARCHAR(254) 	NOT NULL,
	CUENTAS		TEXT	 	NOT NULL,
	OTROS		VARCHAR(254) 	NOT NULL,
	TAB		INT		NOT NULL)
go


ALTER TABLE CUADRES_CG 
	ADD CONSTRAINT XPKCUADRES_CG 
		PRIMARY KEY ( CUADRES_CG  )
go


CREATE TABLE CUADRE_AUX	(
	CUADRES_CG	INT	 	NOT NULL,
	TABLA_ORIGEN	VARCHAR(30) 	NOT NULL,
	GUID_ORIGEN	VARCHAR(48) 	NOT NULL,
	REFERENCIA	VARCHAR(249) 	NOT NULL,
	FECHA		DATETIME 	NOT NULL,
	CONCEPTO	VARCHAR(249) 	NOT NULL,
	ASIENTO		VARCHAR(10) 	NULL,
	DEBITO_LOC	DECIMAL(28,8) 	NOT NULL,
	DEBITO_DOL	DECIMAL(28,8) 	NOT NULL,
	CREDITO_LOC	DECIMAL(28,8) 	NOT NULL,
	CREDITO_DOL	DECIMAL(28,8) 	NOT NULL,
	ORIGEN          VARCHAR(4)      NOT NULL

 )
go

ALTER TABLE CUADRE_AUX
          ADD  CONSTRAINT XPKCUADRE_AUX 
          	PRIMARY KEY (CUADRES_CG,TABLA_ORIGEN,GUID_ORIGEN )
go

CREATE TABLE CUADRE_CONTA	(
	CUADRES_CG	INT	 	NOT NULL,
	ASIENTO		VARCHAR(10) 	NOT NULL,
	LINEA		INT	 	NOT NULL,
	UBICACION	VARCHAR(1) 	NOT NULL,
	ORIGEN		VARCHAR(4) 	NOT NULL,
	CONTABILIDAD	VARCHAR(1) 	NOT NULL,
	FECHA		DATETIME 	NOT NULL,
	CUENTA		VARCHAR(25) 	NOT NULL,
	CUENTA_DESC	VARCHAR(60) 	NULL,
	CENTRO		VARCHAR(25) 	NOT NULL,
	CENTRO_DESC	VARCHAR(60) 	NULL,
	NIT		VARCHAR(20) 	NULL,
	NIT_DESC	VARCHAR(80) 	NULL,
	FUENTE		VARCHAR(40) 	NOT NULL,
	REFERENCIA	VARCHAR(249) 	NOT NULL,
	DEBITO_LOC	DECIMAL(28,8) 	NULL,
	DEBITO_DOL	DECIMAL(28,8) 	NULL,
	CREDITO_LOC	DECIMAL(28,8) 	NULL,
	CREDITO_DOL	DECIMAL(28,8) 	NULL
 )
go



ALTER TABLE CUADRE_CONTA
          ADD CONSTRAINT XPKCUADRE_CONTA 
          	PRIMARY KEY ( CUADRES_CG, ASIENTO, LINEA, CUENTA, CENTRO, FUENTE)
go


			
CREATE TABLE CUADRE_CONTA_AUX	(
	CUADRES_CG		INT	 	NOT NULL,
	GUID_AUX		VARCHAR(48) 	NOT NULL,
	GUID_CONTA		VARCHAR(48) 	NOT NULL,
	ESTADO			VARCHAR(2)  	NULL	
 )
go
 
 
 CREATE TABLE CUENTA_CONTABLE (
        CUENTA_CONTABLE      	VARCHAR(25) 	NOT NULL,
        SECCION_CUENTA       	VARCHAR(4) 	NULL,
        UNIDAD               	VARCHAR(15) 	NULL,
        DESCRIPCION          	VARCHAR(200) 	NOT NULL,
        TIPO                 	VARCHAR(1) 	NOT NULL,
        TIPO_DETALLADO       	VARCHAR(1) 	NOT NULL,
        TIPO_OAF             	VARCHAR(1) 	NOT NULL,
        SALDO_NORMAL         	VARCHAR(1) 	NOT NULL,
        CONVERSION           	VARCHAR(1) 	NOT NULL,
        TIPO_CAMBIO          	VARCHAR(4) 	NOT NULL,
        ACEPTA_DATOS         	VARCHAR(1) 	NOT NULL,
        CONSOLIDA            	VARCHAR(1) 	NOT NULL,
        USA_CENTRO_COSTO     	VARCHAR(1) 	NOT NULL,
        NOTAS                	TEXT 		NULL,
        USUARIO              	VARCHAR(25) 	NOT NULL,
        FECHA_HORA           	DATETIME 	NOT NULL,
        USUARIO_ULT_MOD      	VARCHAR(25) 	NOT NULL,
        FCH_HORA_ULT_MOD     	DATETIME 	NOT NULL,
        ACEPTA_UNIDADES      	VARCHAR(1) 	NOT NULL,
        USO_RESTRINGIDO      	VARCHAR(1) 	NOT NULL,
        ORIGEN_CONVERSION    	VARCHAR(1)	NULL,
        VALIDA_PRESUP_CR		VARCHAR(1)	NOT NULL 	DEFAULT('N'),
        CUENTA_IFRS 			VARCHAR(25) 	NULL,
        USA_CONTA_ELECTRO 		VARCHAR(1) 	NOT NULL 	DEFAULT ('N'),
		VERSION					VARCHAR(5) 	NOT NULL     	DEFAULT ('1.0'),
		FECHA_INI_CE 			DATETIME        NULL,
		FECHA_FIN_CE 			DATETIME        NULL,
		COD_AGRUPADOR 			VARCHAR(15) 	NULL,
		DESC_COD_AGRUP 			VARCHAR(60) 	NULL,
		SUB_CTA_DE 				VARCHAR(100) 	NULL,
		DESC_SUB_CTA 			VARCHAR(100) 	NULL,
		NIVEL 					VARCHAR(5) 		NULL,
		DESCRIPCION_IFRS 		VARCHAR(200) 	NULL,
		MANEJA_TERCERO  		VARCHAR(1) 		NOT NULL DEFAULT 'S'
	 )
go
 
 
 ALTER TABLE CUENTA_CONTABLE
        ADD CONSTRAINT XPKCUENTA_CONTABLE PRIMARY KEY NONCLUSTERED (
               CUENTA_CONTABLE)
go

	
 
 CREATE TABLE CUENTA_SECCION(
 	CUENTA_CONTABLE 	VARCHAR(25) 	NOT NULL,
 	TIPO_R 			VARCHAR(2) 	NOT NULL,
 	CODIGO_R 		VARCHAR(4)	NOT NULL,
 	SECCION_R 		VARCHAR(4) 	NOT NULL,
 	SUBSECCION 		VARCHAR(4) 	NOT NULL
 )
 go

 ALTER TABLE CUENTA_SECCION  
 		ADD CONSTRAINT PK_CUENTA_SECCION PRIMARY KEY CLUSTERED ( CUENTA_CONTABLE,TIPO_R,CODIGO_R,SECCION_R,SUBSECCION)
 
 go 
 
 
 
 CREATE TABLE DETALLE_CORRIDA (
        CORRIDA_AD           int NOT NULL,
        ASIENTO_DISTRIBUID   VARCHAR(10) NOT NULL,
        ASIENTO_FISCAL       VARCHAR(10) NULL,
        ASIENTO_CORP         VARCHAR(10) NULL,
        CONSECUTIVO          smallint NULL
 )
go
 
 
 ALTER TABLE DETALLE_CORRIDA
        ADD CONSTRAINT XPKDETALLE_CORRIDA PRIMARY KEY (CORRIDA_AD, 
               ASIENTO_DISTRIBUID)
go
 
 
 CREATE TABLE DIARIO (
        ASIENTO              VARCHAR(10) 	NOT NULL,
        CONSECUTIVO          int 		NOT NULL,
        NIT                  VARCHAR(20) 	NULL,
        CENTRO_COSTO         VARCHAR(25)	NOT NULL,
        CUENTA_CONTABLE      VARCHAR(25) 	NOT NULL,
        FUENTE               VARCHAR(40) 	NOT NULL,
        REFERENCIA           VARCHAR(249) 	NOT NULL,
        DEBITO_LOCAL         DECIMAL(28,8) 	NULL,
        DEBITO_DOLAR         DECIMAL(28,8) 	NULL,
        CREDITO_LOCAL        DECIMAL(28,8) 	NULL,
        CREDITO_DOLAR        DECIMAL(28,8) 	NULL,
        DEBITO_UNIDADES      DECIMAL(28,8) 	NULL,
        CREDITO_UNIDADES     DECIMAL(28,8) 	NULL,
        TIPO_CAMBIO 	     DECIMAL(28,8) 	NULL,
        BASE_LOCAL           DECIMAL(28,8) 	NULL,
	BASE_DOLAR           DECIMAL(28,8) 	NULL,
	PROYECTO             VARCHAR(25) 	NULL,
	FASE 		     VARCHAR(25) 	NULL,
	DOCUMENTO_GLOBAL     VARCHAR(50) 	NULL
 )
go
 
 
 ALTER TABLE DIARIO
        ADD CONSTRAINT DIARIOPK PRIMARY KEY NONCLUSTERED (ASIENTO, 
               CONSECUTIVO)
go

CREATE TABLE DIFERIDO ( 
	DIFERIDO 		VARCHAR(53) 	NOT NULL,
  	DESCRIPCION 		VARCHAR(250) 	NOT NULL,
  	FECHA_INGRESO 		DATETIME 	NOT NULL,
  	FECHA_INICIO 		DATETIME 	NOT NULL,
  	MONTO_ORIGINAL		DECIMAL(28,8)	NOT NULL,
  	MONEDA 			VARCHAR(4) 	NULL,
  	AMORTIZADO		DECIMAL(28,8)	NOT NULL,
  	PENDIENTE_AMORTIZAR	DECIMAL(28,8)	NOT NULL,
  	ESTADO 			VARCHAR(1) 	NOT NULL,
  	ASIENTO			VARCHAR(10) 	NULL,
  	MODALIDAD		VARCHAR(1) 	NOT NULL,
  	VALOR_MODALIDAD		DECIMAL(28,8)	NOT NULL,
  	TIPO 			VARCHAR(1) 	NOT NULL,
  	PAQUETE			VARCHAR(4) 	NOT NULL,
  	TIPO_ASIENTO		VARCHAR(25)	NOT NULL,
	CTR_DIFERIDO		VARCHAR(25)	NOT NULL,
	CTA_DIFERIDO		VARCHAR(25)	NOT NULL,
	CTR_CONTRAASIENTO	VARCHAR(25)	NOT NULL,
	CTA_CONTRAASIENTO	VARCHAR(25)	NOT NULL,
	CTR_AMORTIZACION	VARCHAR(25)	NOT NULL,
	CTA_AMORTIZACION	VARCHAR(25)	NOT NULL,
	CTR_GASTOINGRESO	VARCHAR(25)	NOT NULL,
	CTA_GASTOINGRESO	VARCHAR(25)	NOT NULL,
  	FECHA_AUD_ING 		DATETIME 	NOT NULL,
  	USUARIO_AUD_ING		VARCHAR(25)	NOT NULL,
  	FECHA_ULT_MOD 		DATETIME 	NOT NULL,  		
  	USUARIO_ULT_MOD		VARCHAR(25)	NOT NULL,
	NOTAS			TEXT		NULL,
	NIT 			VARCHAR(20) 	NOT NULL DEFAULT 'ND',
	FECHA_HORA_ANULACION	DATETIME 	NULL,
	USUARIO_ANULACION	VARCHAR(25)   	NULL,
	DIFERIDO_ORIGEN 	VARCHAR(53)	NULL,
	COSTO_LOC_F 		DECIMAL(28,8)	NULL,
	COSTO_DOL_F 		DECIMAL(28,8) 	NULL,
	COSTO_LOC_C 		DECIMAL(28,8) 	NULL,
	COSTO_DOL_C 		DECIMAL(28,8) 	NULL,
	MODALIDAD_C 		VARCHAR(1) 	NULL,
	VALOR_MODALIDAD_C 	DECIMAL(28,8) 	NULL,
	AMORTIZACION_LOC_F 	DECIMAL(28,8) 	NULL,
	AMORTIZACION_DOL_F 	DECIMAL(28,8) 	NULL,
	AMORTIZACION_LOC_C 	DECIMAL(28,8) 	NULL,
	AMORTIZACION_DOL_C 	DECIMAL(28,8) 	NULL,
	AMORTIZADO_LOC_F 	DECIMAL(28,8) 	NULL,
	AMORTIZADO_DOL_F 	DECIMAL(28,8) 	NULL,
	AMORTIZADO_LOC_C 	DECIMAL(28,8) 	NULL,
	AMORTIZADO_DOL_C 	DECIMAL(28,8) 	NULL,
	PENDIENTE_AMORT_LOC_F 	DECIMAL(28,8) 	NULL,
	PENDIENTE_AMORT_DOL_F 	DECIMAL(28,8) 	NULL,
	PENDIENTE_AMORT_LOC_C 	DECIMAL(28,8) 	NULL,
	PENDIENTE_AMORT_DOL_C 	DECIMAL(28,8) 	NULL,
	ASIENTO_CORP 		VARCHAR(10)  	NULL,
	MARCADO  		VARCHAR(1)	NOT NULL DEFAULT 'N',
	USUARIO_MARCADO     	VARCHAR(25)     NULL,
	CONCEPTO_ME 		VARCHAR (4) 	NULL,
	DESGLOSE_IMP 		VARCHAR (1) 	NULL
) 
go

  
ALTER TABLE DIFERIDO 
	ADD CONSTRAINT XPK_DIFERIDO
		PRIMARY KEY (DIFERIDO) 
go

CREATE TABLE $$COMPANIA$$.DIFERIDOS_IMPUESTOS(
	 DIFERIDO 		VARCHAR (53) 	NOT NULL,
	 CONSECUTIVO 		INT 		NOT NULL,
	 IMPUESTO 		VARCHAR (4) 	NOT NULL,
	 CONCEPTO_ME 		VARCHAR (4) 	NOT NULL,
	 VALOR 			DECIMAL (28,8) 	NOT NULL,
	 PORCENTAJE 		DECIMAL (28,8) 	NOT NULL,
	 IMPUESTO_AFECTA_COSTO 	VARCHAR (1) 	NOT NULL,
	 TIPO_IMPUESTO 		VARCHAR(4) 	NOT NULL,
	 IMPUESTO_ASUMIDO 	VARCHAR(1) 	NOT NULL 
) 
go
 
ALTER TABLE $$COMPANIA$$.DIFERIDOS_IMPUESTOS  ADD CONSTRAINT PKDIFIMP 
		PRIMARY KEY (DIFERIDO,CONSECUTIVO) 
go


CREATE TABLE $$COMPANIA$$.DIFERIDO_DOC_CC
(
	DIFERIDO	VARCHAR(53)	NOT NULL,
	TIPO_DOC	VARCHAR(3)	NOT NULL,
	DOCUMENTO	VARCHAR(50)	NOT NULL
)
go

ALTER TABLE $$COMPANIA$$.DIFERIDO_DOC_CC 
	ADD CONSTRAINT XPK_DIFERIDO_DOC_CC
		PRIMARY KEY (DIFERIDO, TIPO_DOC, DOCUMENTO) 
go



CREATE TABLE $$COMPANIA$$.DIFERIDO_DOC_CP
(
	DIFERIDO	VARCHAR(53)	NOT NULL,
	PROVEEDOR	VARCHAR(20)	NOT NULL,
	TIPO_DOC	VARCHAR(3)	NOT NULL,
	DOCUMENTO	VARCHAR(50)	NOT NULL
)
go

ALTER TABLE $$COMPANIA$$.DIFERIDO_DOC_CP
	ADD CONSTRAINT XPK_DIFERIDO_DOC_CP
		PRIMARY KEY (DIFERIDO, PROVEEDOR, TIPO_DOC, DOCUMENTO)
go
 
 
 CREATE TABLE GLOBALES_CG (
        CTA_PERD_DIFCAMDOL   		VARCHAR(25) 	NULL,
        CTA_PERD_DIFCAMLOC   		VARCHAR(25) 	NULL,
        TIP_ASNT_CIERRE_AN   		VARCHAR(4) 	NULL,
        PATRON               		VARCHAR(25) 	NOT NULL,
        CTR_DIFCAMBIOLOCAL   		VARCHAR(25) 	NULL,
        CTA_DIFCAMBIOLOCAL   		VARCHAR(25) 	NULL,
        CTR_DIFCAMBIODOLAR   		VARCHAR(25) 	NULL,
        CTA_DIFCAMBIODOLAR   		VARCHAR(25) 	NULL,
        FECHA_DIFCAM_FISC    		DATETIME 	NOT NULL,
        FECHA_DIFCAM_CORP    		DATETIME 	NOT NULL,
        FECHA_CIERRE_FISC    		DATETIME 	NOT NULL,
        FECHA_CIERRE_CORP    		DATETIME 	NOT NULL,
        MES_CIERRE_FISCAL    		smallint 	NOT NULL,
        MES_CIERRE_CORP      		smallint 	NOT NULL,
        ULTIMO_ASIENTO       		VARCHAR(10) 	NOT NULL,
        NUM_ASIENTO_GLOBAL   		VARCHAR(1) 	NOT NULL,
        NOMBRE_ASIENTO       		VARCHAR(10) 	NOT NULL,
        CANT_DECIMALES       		smallint 	NOT NULL,
        TRUNCAR_CONVERSION   		VARCHAR(1) 	NOT NULL,
        CTR_CIERRE           		VARCHAR(25)	NULL,
        CTA_CIERRE           		VARCHAR(25)	NULL,
        USA_CIFRA_CONTROL    		VARCHAR(1) 	NOT NULL,
        AJUS_AN_FISC_PEND    		VARCHAR(1) 	NOT NULL,
        AJUS_AN_CORP_PEND    		VARCHAR(1) 	NOT NULL,
        PERMITE_MOV_ROJO     		VARCHAR(1) 	NOT NULL,
        AUX_REVER_MOV_ROJO   		VARCHAR(1) 	NOT NULL,
        USAR_NITS            		VARCHAR(1) 	NOT NULL,
        CTR_PERD_DIFCAMLOC   		VARCHAR(25)	NULL,
        CTR_PERD_DIFCAMDOL   		VARCHAR(25)	NULL,
        NIT_DEFAULT 				VARCHAR(1) 	NOT NULL 	DEFAULT 'S',
		NOMBRE_CONTA_FISCAL   		VARCHAR(15) 	NULL,
		INTEGRACION_CR				VARCHAR(1) 	NULL,
		REQUIERE_PRESUP				VARCHAR(1) 	NULL,
		PAQUETE_CR					VARCHAR(4)	NULL,
		PRESUPUESTO_CR				VARCHAR(20)	NULL,
		NOMBRE_CONTA_CORP 			VARCHAR(15) 	NULL,
		CTR_DIFCAMLOC_UTI_REALI  	VARCHAR(25) 	NULL,
		CTA_DIFCAMLOC_UTI_REALI  	VARCHAR(25) 	NULL,
		CTR_DIFCAMDOL_UTI_REALI  	VARCHAR(25) 	NULL,
		CTA_DIFCAMDOL_UTI_REALI  	VARCHAR(25) 	NULL,
		CTR_DIFCAMLOC_PER_REALI  	VARCHAR(25) 	NULL,
		CTA_DIFCAMLOC_PER_REALI  	VARCHAR(25) 	NULL,
		CTR_DIFCAMDOL_PER_REALI  	VARCHAR(25) 	NULL,
		CTA_DIFCAMDOL_PER_REALI  	VARCHAR(25) 	NULL,
		DOBLE_CONTROL 				VARCHAR(1) 		NOT NULL 	DEFAULT ('N'),
		P_NITS_INACTIVOS 			VARCHAR(1) 		NOT NULL 	DEFAULT ('N'),
		USA_CUENTAS_ESPBALANCEO		VARCHAR(1)  	NOT NULL 	DEFAULT 'N',
		CTR_UTL_LOCAL 				VARCHAR(25) 	NULL,
		CTA_UTL_LOCAL 				VARCHAR(25) 	NULL,
		CTR_UTL_DOLAR 				VARCHAR(25) 	NULL,
		CTA_UTL_DOLAR 				VARCHAR(25) 	NULL,
		CTR_PERD_LOCAL 				VARCHAR(25) 	NULL,
		CTA_PERD_LOCAL 				VARCHAR(25) 	NULL,
		CTR_PERD_DOLAR 				VARCHAR(25) 	NULL,
		CTA_PERD_DOLAR 				VARCHAR(25) 	NULL,
		NIT_CUENTA_CONTABLE  		VARCHAR(1) 		NOT NULL DEFAULT 'N',
		NOMBRE_CONTADOR         	VARCHAR(70) 	NULL,
        NOMBRE_REVISOR          	VARCHAR (70) 	NULL,
        NOMBRE_REPRESENTANTE    	VARCHAR (70) 	NULL,
        FIRMA_CONTADOR          	VARBINARY (MAX) NULL,
        FIRMA_REVISOR           	VARBINARY (MAX) NULL,
        FIRMA_REPRESENTANTE     	VARBINARY (MAX) NULL

 )
go

CREATE TABLE HISTORICO_DIFERIDO (
	HIST_DIFERIDO		INTEGER		NOT NULL,
	DIFERIDO 		VARCHAR(53) 	NOT NULL,
  	FECHA			DATETIME 	NOT NULL,
  	ASIENTO			VARCHAR(10) 	NULL,
  	USUARIO			VARCHAR(25)	NOT NULL,
  	AMORTIZACION_LOCAL	DECIMAL(28,8)	NOT NULL,
 	AMORTIZACION_DOLAR	DECIMAL(28,8)	NOT NULL
)
go



ALTER TABLE HISTORICO_DIFERIDO 
	ADD CONSTRAINT XPK_HISTDIFERIDO 
		PRIMARY KEY (HIST_DIFERIDO)
go		


CREATE TABLE HIST_CIERRE_CG (
        FECHA_CIERRE         DATETIME NOT NULL,
        CONTABILIDAD         VARCHAR(1) NOT NULL,
        ASIENTO		     VARCHAR(10) NOT NULL,
        USUARIO		     VARCHAR(25) NOT NULL,
        FECHA                DATETIME NOT NULL,
        MAYOR_AUDITORIA      int NULL,
        DOCUMENTO_GLOBAL     VARCHAR(50) NULL
)
go


ALTER TABLE HIST_CIERRE_CG
       ADD  CONSTRAINT XPKHIST_CIERRE_CG PRIMARY KEY 
       		(FECHA_CIERRE, CONTABILIDAD, ASIENTO) 
go



CREATE TABLE HIST_DIFCAM_CG(
        USUARIO_AUDITORIA 	VARCHAR(25)		NOT NULL,
	FECHA_AUDITORIA 	DATETIME        	NOT NULL,
	FECHA_PROC		DATETIME        	NOT NULL,
	TIPO_CAMBIO_PROC	DECIMAL(28,8) 		NOT NULL,
	ASIENTO_PROC		VARCHAR(10)		NOT NULL,
	ID_HIST 		UniqueIdentifier	NOT NULL
)
go


ALTER TABLE HIST_DIFCAM_CG 
	ADD CONSTRAINT IDDEF_HISTDCCG   
		DEFAULT (NEWID()) FOR [ID_HIST]
go		


ALTER TABLE HIST_DIFCAM_CG
         ADD CONSTRAINT HISTDFCGPK PRIMARY KEY NONCLUSTERED 
         (Id_hist)
go         
 
 
 CREATE TABLE MAYOR (
        ASIENTO              VARCHAR(10) 	NOT NULL,
        CONSECUTIVO          int 		NOT NULL,
        NIT                  VARCHAR(20) 	NULL,
        CENTRO_COSTO         VARCHAR(25) 	NOT NULL,
        CUENTA_CONTABLE      VARCHAR(25) 	NOT NULL,
        FECHA                DATETIME 		NOT NULL,
        TIPO_ASIENTO         VARCHAR(4) 	NOT NULL,
        FUENTE               VARCHAR(40) 	NOT NULL,
        REFERENCIA           VARCHAR(249) 	NOT NULL,
        ORIGEN               VARCHAR(4) 	NOT NULL,
        DEBITO_LOCAL         DECIMAL(28,8) 	NULL,
        CREDITO_LOCAL        DECIMAL(28,8) 	NULL,
        DEBITO_DOLAR         DECIMAL(28,8) 	NULL,
        CREDITO_DOLAR        DECIMAL(28,8) 	NULL,
        CONTABILIDAD         VARCHAR(1) 	NOT NULL,
        CLASE_ASIENTO        VARCHAR(1) 	NOT NULL,
        ESTADO_CONS_FISC     VARCHAR(1) 	NOT NULL,
        ASNT_CONS_FISC       VARCHAR(10) 	NULL,
        ESTADO_CONS_CORP     VARCHAR(1) 	NOT NULL,
        ASNT_CONS_CORP       VARCHAR(10) 	NULL,
        DEBITO_UNIDADES      DECIMAL(28,8) 	NULL,
        CREDITO_UNIDADES     DECIMAL(28,8) 	NULL,
        TIPO_CAMBIO 	     DECIMAL(28,8) 	NULL,
        BASE_LOCAL           DECIMAL(28,8) 	NULL,
		BASE_DOLAR           DECIMAL(28,8) 	NULL,
		PROYECTO             VARCHAR(25) 	NULL,
		FASE                 VARCHAR(25) 	NULL,
		DOCUMENTO_GLOBAL 	 VARCHAR(50) NULL		
 )
go
 
 
 ALTER TABLE MAYOR
        ADD CONSTRAINT MAYORPK PRIMARY KEY NONCLUSTERED (ASIENTO, 
               CONSECUTIVO)
go
 
 
 CREATE TABLE MAYOR_AUDITORIA (
        MAYOR_AUDITORIA      int NOT NULL,
        USUARIO              VARCHAR(25) NOT NULL,
        FECHA                DATETIME NOT NULL,
        COMENTARIO           VARCHAR(40) NOT NULL
 )
go
 
 
 ALTER TABLE MAYOR_AUDITORIA
        ADD CONSTRAINT MAYORAUDITPK PRIMARY KEY NONCLUSTERED (
               MAYOR_AUDITORIA)
go



CREATE TABLE MAYOR_DIVISION_GEOGRAFICA
(
	ASIENTO 		VARCHAR(10) 	NOT NULL,
	CONSECUTIVO 		INT		NOT NULL,
	PAIS			VARCHAR(4)	NULL,
	DIVISION_GEOGRAFICA1	VARCHAR(12) 	NULL,
	DIVISION_GEOGRAFICA2	VARCHAR(12) 	NULL
)
go

ALTER TABLE MAYOR_DIVISION_GEOGRAFICA
		ADD CONSTRAINT PKMAYORDIVGEO 
			PRIMARY KEY (ASIENTO,CONSECUTIVO)
go

	

 
 
 CREATE TABLE PAQUETE (
        PAQUETE              	VARCHAR(4) 	NOT NULL,
        DESCRIPCION          	VARCHAR(40) 	NOT NULL,
        USUARIO_CREADOR      	VARCHAR(25) 	NOT NULL,
        ULTIMO_USUARIO       	VARCHAR(25) 	NOT NULL,
        FECHA_ULT_ACCESO     	DATETIME 	NOT NULL,
        ULTIMO_ASIENTO       	VARCHAR(10) 	NOT NULL,
        DOBLE_ASIENTO        	VARCHAR(1) 	NOT NULL,
        MARCADO              	VARCHAR(1) 	NOT NULL,
        USA_DOBLE_ASIENTO    	VARCHAR(1) 	NOT NULL DEFAULT 'N',
        ULTIMO_ASIENTO_CORP 	VARCHAR(10) 	NULL
 )
go
 
 
 ALTER TABLE PAQUETE
        ADD CONSTRAINT PAQUETEPK PRIMARY KEY NONCLUSTERED (PAQUETE)
go
 
 
 CREATE TABLE REPORTES_CONTABLES(
 	TIPO_R 		VARCHAR(2) 	NOT NULL,
 	CODIGO_R 	VARCHAR(4) 	NOT NULL,
 	NOMBRE 		VARCHAR(60) 	NOT NULL,
 	REPORTE 	VARCHAR(150) 	NULL,
 	REPORTE_AMBAS 	VARCHAR(150) 	NULL
  )
 go
 
 ALTER TABLE REPORTES_CONTABLES  
 		ADD CONSTRAINT PK_REPORTES_CONTABLES PRIMARY KEY CLUSTERED ( TIPO_R,CODIGO_R)
go
 
 
 CREATE TABLE SALDO (
        CENTRO_COSTO         VARCHAR(25) NOT NULL,
        CUENTA_CONTABLE      VARCHAR(25) NOT NULL,
        FECHA                DATETIME NOT NULL,
        SALDO_FISC_LOCAL     DECIMAL(28,8) NOT NULL,
        SALDO_FISC_DOLAR     DECIMAL(28,8) NOT NULL,
        SALDO_CORP_LOCAL     DECIMAL(28,8) NOT NULL,
        SALDO_CORP_DOLAR     DECIMAL(28,8) NOT NULL,
        DEBITO_FISC_LOCAL    DECIMAL(28,8) NOT NULL,
        CREDITO_FISC_LOCAL   DECIMAL(28,8) NOT NULL,
        DEBITO_CORP_LOCAL    DECIMAL(28,8) NOT NULL,
        CREDITO_CORP_LOCAL   DECIMAL(28,8) NOT NULL,
        DEBITO_FISC_DOLAR    DECIMAL(28,8) NOT NULL,
        CREDITO_FISC_DOLAR   DECIMAL(28,8) NOT NULL,
        DEBITO_CORP_DOLAR    DECIMAL(28,8) NOT NULL,
        CREDITO_CORP_DOLAR   DECIMAL(28,8) NOT NULL,
        SALDO_FISC_UND       DECIMAL(28,8) NOT NULL,
        SALDO_CORP_UND       DECIMAL(28,8) NOT NULL,
        DEBITO_FISC_UND      DECIMAL(28,8) NOT NULL,
        CREDITO_FISC_UND     DECIMAL(28,8) NOT NULL,
        DEBITO_CORP_UND      DECIMAL(28,8) NOT NULL,
        CREDITO_CORP_UND     DECIMAL(28,8) NOT NULL
 )
go
 
 
 ALTER TABLE SALDO
        ADD CONSTRAINT SALDOCTACONTPK PRIMARY KEY NONCLUSTERED (
               CENTRO_COSTO, CUENTA_CONTABLE, FECHA)
go


CREATE TABLE SALDO_NIT (
        CENTRO_COSTO         VARCHAR(25) NOT NULL,
        CUENTA_CONTABLE      VARCHAR(25) NOT NULL,
	NIT		     VARCHAR(20) NOT NULL,	
        FECHA                DATETIME NOT NULL,
        SALDO_FISC_LOCAL     DECIMAL(28,8) NOT NULL,
        SALDO_FISC_DOLAR     DECIMAL(28,8) NOT NULL,
        SALDO_CORP_LOCAL     DECIMAL(28,8) NOT NULL,
        SALDO_CORP_DOLAR     DECIMAL(28,8) NOT NULL,
        DEBITO_FISC_LOCAL    DECIMAL(28,8) NOT NULL,
        CREDITO_FISC_LOCAL   DECIMAL(28,8) NOT NULL,
        DEBITO_CORP_LOCAL    DECIMAL(28,8) NOT NULL,
        CREDITO_CORP_LOCAL   DECIMAL(28,8) NOT NULL,
        DEBITO_FISC_DOLAR    DECIMAL(28,8) NOT NULL,
        CREDITO_FISC_DOLAR   DECIMAL(28,8) NOT NULL,
        DEBITO_CORP_DOLAR    DECIMAL(28,8) NOT NULL,
        CREDITO_CORP_DOLAR   DECIMAL(28,8) NOT NULL,
        SALDO_FISC_UND       DECIMAL(28,8) NOT NULL,
        SALDO_CORP_UND       DECIMAL(28,8) NOT NULL,
        DEBITO_FISC_UND      DECIMAL(28,8) NOT NULL,
        CREDITO_FISC_UND     DECIMAL(28,8) NOT NULL,
        DEBITO_CORP_UND      DECIMAL(28,8) NOT NULL,
        CREDITO_CORP_UND     DECIMAL(28,8) NOT NULL
 )
 go


 ALTER TABLE SALDO_NIT
        ADD CONSTRAINT XPK_SALDONITCTACON PRIMARY KEY NONCLUSTERED (
               CENTRO_COSTO, CUENTA_CONTABLE, NIT, FECHA)
go               
 
 
 CREATE TABLE SECCION_CUENTA (
        SECCION_CUENTA       VARCHAR(4) NOT NULL,
        TIPO_SECCION         VARCHAR(1) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        ACUMULADO            VARCHAR(40) NULL,
        SECUENCIA            smallint NOT NULL
 )
go
 
 
 ALTER TABLE SECCION_CUENTA
        ADD CONSTRAINT XPKSECCION_CUENTA PRIMARY KEY (SECCION_CUENTA)
go
 
 
 
 CREATE TABLE SECCION_REPORTES(
 	TIPO_R 		VARCHAR(2) 	NOT NULL,
 	CODIGO_R 	VARCHAR(4) 	NOT NULL,
 	SECCION_R 	VARCHAR(4) 	NOT NULL,
 	DESCRIPCION 	VARCHAR(40) 	NOT NULL,
 	TIPO 		VARCHAR(1) 	NOT NULL DEFAULT('A'),
 	ACUMULADO 	VARCHAR(40) 	NULL,
 	SECUENCIA 	SMALLINT 	NOT NULL
 )
 go
 
 ALTER TABLE SECCION_REPORTES  
 		ADD CONSTRAINT PK_SECCION_REPORTES PRIMARY KEY CLUSTERED ( TIPO_R,CODIGO_R,SECCION_R)
 go
 
 
 CREATE TABLE SUBSECCION_REPORTES(
 	TIPO_R 		VARCHAR(2) 	NOT NULL,
 	CODIGO_R 	VARCHAR(4) 	NOT NULL,
 	SECCION_R 	VARCHAR(4) 	NOT NULL,
 	SUBSECCION 	VARCHAR(4) 	NOT NULL,
 	DESCRIPCION 	VARCHAR(40) 	NOT NULL,
 	TIPO 		VARCHAR(1) 	NOT NULL DEFAULT('A'),
 	ACUMULADO 	VARCHAR(40) 	NULL,
 	SECUENCIA 	SMALLINT 	NOT NULL
 )
 go
 
 
 ALTER TABLE SUBSECCION_REPORTES  
 		ADD CONSTRAINT PK_SUBSECCION_REPORTES PRIMARY KEY CLUSTERED ( TIPO_R,CODIGO_R,SECCION_R,SUBSECCION)
 go
 
 
 
 
 CREATE TABLE TIPO_ASIENTO (
        TIPO_ASIENTO         VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL
 )
go
 
 
 ALTER TABLE TIPO_ASIENTO
        ADD CONSTRAINT TIPO_ASIENTOPK PRIMARY KEY NONCLUSTERED (
               TIPO_ASIENTO)
go
 



CREATE TABLE $$COMPANIA$$.TIPO_DIFERIDO   (
	TIPO_DIFERIDO 		VARCHAR(4) 	NOT NULL,
	DESCRIPCION 		VARCHAR(60) 	NOT NULL,
	MODALIDAD 		VARCHAR(1) 	NOT NULL 	DEFAULT 'P',
	VALOR 			DECIMAL(28,8) 	NOT NULL,
	TIPO 			VARCHAR(1)	NOT NULL 	DEFAULT 'I',
	PAQUETE 		VARCHAR(4) 	NOT NULL,
	TIPO_ASIENTO 		VARCHAR(4) 	NOT NULL,
	CTR_DIFERIDO 		VARCHAR(25)	NOT NULL,
	CTA_DIFERIDO 		VARCHAR(25) 	NOT NULL,
	CTR_CONTRAASIENTO 	VARCHAR(25)	NOT NULL,
	CTA_CONTRAASIENTO 	VARCHAR(25)	NOT NULL,
	CTR_AMORTIZACION 	VARCHAR(25)	NOT NULL,
	CTA_AMORTIZACION 	VARCHAR(25) 	NOT NULL,
	CTR_GASTOINGRESO 	VARCHAR(25)	NOT NULL,
	CTA_GASTOINGRESO	VARCHAR(25) 	NOT NULL,
	NIT 			VARCHAR(20) 	NULL,
	USUARIO_ULT_MOD 	VARCHAR(60) 	NOT NULL,
	FECHA_ULT_MOD 		DATETIME 	NOT NULL,
	USUARIO_INGRESO 	VARCHAR(60) 	NOT NULL,
	FECHA_INGRESO 		DATETIME 	NOT NULL,
	CONCEPTO_ME 		VARCHAR (4) 	NULL
)
go
 
 
 
 ALTER TABLE $$COMPANIA$$.TIPO_DIFERIDO
        ADD CONSTRAINT XPKTIPO_DIFERIDO PRIMARY KEY NONCLUSTERED (
               TIPO_DIFERIDO)
go
 


 CREATE TABLE  TRASLADO_IVA
( 
	MODULO					varchar(2)	NOT NULL,
	ENTIDAD                 varchar(40)	NULL,
	NIT                 	varchar(20)	NULL,
	TIPO_DOC				varchar(3)	NULL,
  	DOCUMENTO    			varchar(50) NULL,
  	FECHA_DOC	  			datetime	NULL,
	MONEDA_DOC          	varchar(4)	NULL,
	MONTO_DOC				decimal(28,8)	NULL,
	MONTO_LOCAL_DOC			decimal(28,8)	NULL,
	MONTO_DOLAR_DOC			decimal(28,8)	NULL,
	MONTO_APLICADO_DOC		decimal(28,8)	NULL,
	TIPO_CAMBIO_LOC_DOC		decimal(28,8)	NULL,
	TIPO_CAMBIO_DOL_DOC		decimal(28,8)	NULL,
	APLICACION_DOC		   	varchar(249)	NULL,
	TIPO_DOC2				varchar(3)	NULL,
	DOCUMENTO2     			varchar(50)	NULL,
  	FECHA_DOC2   			datetime	NULL,
	MONEDA_DOC2          	varchar(4)	NULL,
	MONTO_DOC2				decimal(28,8)	NULL,
	MONTO_LOCAL_DOC2		decimal(28,8)	NULL,
	MONTO_DOLAR_DOC2		decimal(28,8)	NULL,
	MONTO_APLICADO_DOC2		decimal(28,8)	NULL,
	IMPUESTO_DOC2			decimal(28,8)	NULL,
	TIPO_CAMBIO_LOC_DOC2	decimal(28,8)	NULL,
	TIPO_CAMBIO_DOL_DOC2	decimal(28,8)	NULL,
	APLICACION_DOC2		   	varchar(249)	NULL,
	ASIENTO       			varchar(10)	NULL,
	DOCUMENTO_FISCAL 		VARCHAR(50) 	NULL, 
	DOCUMENTO_FISCAL2 		VARCHAR(50) 	NULL,
	DOC_PAGO_RET  			VARCHAR(50) NULL,
	TIPO_PAGO_RET 			VARCHAR(3)  NULL
)
go



CREATE TABLE TRASLADO_IVA_RETENCIONES
( 
	CODIGO_RETENCION            varchar(4)	NOT NULL,
  	CUENTA_ORIGEN               varchar(25) NOT NULL,
  	CUENTA_DESTINO      	    varchar(25) NOT NULL,
	RET_DIFERENCIA_ACREDITABLE  varchar(1)  NOT NULL 	DEFAULT('N')
)
go




CREATE TABLE TRASLADO_IVA_CUENTAS
( 
	MODULO				varchar(2)  NOT NULL,
	CENTRO_ORIGEN			varchar(25) NOT NULL,
	CUENTA_ORIGEN			varchar(25) NOT NULL,
	CENTRO_DESTINO			varchar(25) NOT NULL,
	CUENTA_DESTINO			varchar(25) NOT NULL
)
go




CREATE TABLE TRASLADO_IVA_CTAS_IMPUESTOS
( 
	MODULO				varchar(2)  NOT NULL,
	IMPUESTO			varchar(4)  NOT NULL,
	CENTRO_ORIGEN			varchar(25) NOT NULL,
	CUENTA_ORIGEN			varchar(25) NOT NULL,
	CENTRO_DESTINO			varchar(25) NOT NULL,
	CUENTA_DESTINO			varchar(25) NOT NULL
)
go


CREATE TABLE $$COMPANIA$$.U_COD_AGRUPADOR
(
	U_CODIGO VARCHAR(6) 	NOT NULL,
	U_DESCRIP VARCHAR(249) 	NULL
)
go

ALTER TABLE $$COMPANIA$$.U_COD_AGRUPADOR
	ADD CONSTRAINT U_COD_AGRUPADORPK PRIMARY KEY (U_CODIGO)
go
 
 
 
 
 CREATE TABLE USUARIO_PAQUETE (
        PAQUETE         VARCHAR(4)  	NOT NULL,
        USUARIO         VARCHAR(25) 	NOT NULL,
	SOLO_LECTURA 	VARCHAR(1)  	NOT NULL,        
	APLICACION 	VARCHAR(1)  	NOT NULL,
	AGREGAR 	VARCHAR(1) 	NOT NULL DEFAULT 'N',
	ELIMINAR 	VARCHAR(1) 	NOT NULL DEFAULT 'N',
	TOTAL		VARCHAR(1) 	NOT NULL DEFAULT 'N'
 )
go
 
 
 ALTER TABLE USUARIO_PAQUETE
        ADD CONSTRAINT USUARIO_PAQUETEPK PRIMARY KEY (PAQUETE, 
               USUARIO)
go
 

CREATE TABLE VALOR_ADICIONAL_ME (
         ASIENTO         		VARCHAR(10)     NOT NULL,
         CONSECUTIVO         		INT     	NOT NULL,
         NIT				VARCHAR(20)	NULL,
         CENTRO_COSTO         		VARCHAR(25)     NOT NULL,
         CUENTA_CONTABLE       		VARCHAR(25)     NOT NULL,
         FECHA				DATETIME        NOT NULL,
         BASE_LOCAL         		DECIMAL(28,8)   NULL,
         BASE_DOLAR 			DECIMAL(28,8) 	NULL,
         CONCEPTO_ME			VARCHAR(4)  	NULL,
         MONTO_IVA	    		DECIMAL(28,8)   NULL,
         PORCENTAJE_IVA			DECIMAL(28,8)   NULL,
         IVA_MAYOR_VALOR_COSTO     	VARCHAR(1)   	NOT NULL DEFAULT 'N',
         ASUMIDO		     	VARCHAR(1)   	NOT NULL DEFAULT 'N',
         TIPO_IMPUESTO 			VARCHAR(4) 	NULL
) 
go



ALTER TABLE VALOR_ADICIONAL_ME ADD CONSTRAINT PK_VALORADICIONALME PRIMARY KEY NONCLUSTERED  ( ASIENTO,CONSECUTIVO )
go
         