
 CREATE INDEX ALIASPRODIFARTICUL ON ALIAS_PRODUCCION
 (
        ARTICULO
 )
go
 
 CREATE INDEX ARTUNDARTICULO ON ART_UND_DISTRIBUCI
 (
        ARTICULO
 )
go
 
 CREATE INDEX ARTUNDUNDMEDIDA ON ART_UND_DISTRIBUCI
 (
        UND_DISTRIBUCION
 )
go
 
 CREATE UNIQUE INDEX XIE1ARTACTTIPLOT ON ARTICULO
 (
        ARTICULO,
        ACTIVO,
        TIPO,
        USA_LOTES
 )
go
 
 CREATE UNIQUE INDEX XIE2ARTCFISCALTIP ON ARTICULO
 (
        ARTICULO,
        COSTO_FISCAL,
        TIPO
 )
go
 
 CREATE UNIQUE INDEX XIE3ARTCCOMPTIP ON ARTICULO
 (
        ARTICULO,
        COSTO_COMPARATIVO,
        TIPO
 )
go
 
 CREATE UNIQUE INDEX XAK5ARTICULO ON ARTICULO
 (
        COSTO_COMPARATIVO,
        ARTICULO,
        TIPO
 )
go
 
 CREATE INDEX FKARTICUPLSE ON ARTICULO
 (
        PLANTILLA_SERIE
 )
go

CREATE INDEX ARTICULOACT ON ARTICULO
(
	ACTIVO
)
WITH FILLFACTOR = 90 

go
 
CREATE INDEX ARTICULOIFCLASIF1 ON ARTICULO
 (
        CLASIFICACION_1
 )
go
 
 CREATE INDEX ARTICULOIFCLASIF2 ON ARTICULO
 (
        CLASIFICACION_2
 )
go
 
 CREATE INDEX ARTICULOIFCLASIF3 ON ARTICULO
 (
        CLASIFICACION_3
 )
go
 
 CREATE INDEX ARTICULOIFUNDALMAC ON ARTICULO
 (
        UNIDAD_ALMACEN
 )
go
 
 CREATE INDEX ARTICULOIFUNDEMPAQ ON ARTICULO
 (
        UNIDAD_EMPAQUE
 )
go
 
 CREATE INDEX ARTICULOIFUNDVENTA ON ARTICULO
 (
        UNIDAD_VENTA
 )
go
 
 CREATE INDEX ARTICULOIFPROVEED ON ARTICULO
 (
        PROVEEDOR
 )
go
 
 CREATE INDEX ARTICULOIFIMPUESTO ON ARTICULO
 (
        IMPUESTO
 )
go
 
 CREATE INDEX ARTICULOIFARTCTAS ON ARTICULO
 (
        ARTICULO_CUENTA
 )
go
 
 CREATE INDEX FKARTICUUSUM ON ARTICULO
 (
        USUARIO_ULT_MODIF
 )
go
 
 CREATE INDEX FKARTICUUSCR ON ARTICULO
 (
        USUARIO_CREACION
 )
go
 
 CREATE INDEX ARTICULOBARRAVNT ON ARTICULO
 (
        CODIGO_BARRAS_VENT
 )
go
 
 CREATE INDEX ARTICULOBARRAINV ON ARTICULO
 (
        CODIGO_BARRAS_INVT
 )
go
 
 CREATE INDEX ARTICULOIETIPO ON ARTICULO
 (
        TIPO
 )
go
 
 CREATE INDEX ARTICULOIEULTMOV ON ARTICULO
 (
        ULTIMO_MOVIMIENTO
 )
go
 
 CREATE INDEX ARTALTERIFARTICULO ON ARTICULO_ALTERNO
 (
        ARTICULO
 )
go
 
 CREATE INDEX ARTALTERIFALTERNO ON ARTICULO_ALTERNO
 (
        ALTERNO
 )
go
 
 CREATE INDEX ARTICULOCUENTIEDES ON ARTICULO_CUENTA
 (
        DESCRIPCION
 )
go
 
 CREATE INDEX ARTCTAIFCTADSCLINL ON ARTICULO_CUENTA
 (
        CTR_DESC_LINEA_LOC,
        CTA_DESC_LINEA_LOC
 )
go
 
 CREATE INDEX ARTCTAIFCTACMSVTAE ON ARTICULO_CUENTA
 (
        CTR_COMS_VENTA_EXP,
        CTA_COMS_VENTA_EXP
 )
go
 
 CREATE INDEX ARTCTAIFCTACSTDSCL ON ARTICULO_CUENTA
 (
        CTR_COST_DESC_LOC,
        CTA_COST_DESC_LOC
 )
go
 
 CREATE INDEX ARTCTAIFCTACMSCBRE ON ARTICULO_CUENTA
 (
        CTR_COMS_COBRO_EXP,
        CTA_COMS_COBRO_EXP
 )
go
 
 CREATE INDEX ARTCTAIFCTACSTDSCE ON ARTICULO_CUENTA
 (
        CTR_COST_DESC_EXP,
        CTA_COST_DESC_EXP
 )
go
 
 CREATE INDEX ARTCTAIFCTADSCLINE ON ARTICULO_CUENTA
 (
        CTR_DESC_LINEA_EXP,
        CTA_DESC_LINEA_EXP
 )
go
 
 CREATE INDEX ARTCTAIFCTASOBINVF ON ARTICULO_CUENTA
 (
        CTR_SOBR_INVENTFIS,
        CTA_SOBR_INVENTFIS
 )
go
 
 CREATE INDEX ARTCTAIFCTAFLTINVF ON ARTICULO_CUENTA
 (
        CTR_FALT_INVENTFIS,
        CTA_FALT_INVENTFIS
 )
go
 
 CREATE INDEX ARTCTAIFCTAVENCIM ON ARTICULO_CUENTA
 (
        CTR_VENCIMIENTO,
        CTA_VENCIMIENTO
 )
go
 
 CREATE INDEX ARTCTAIFCTAINVENT ON ARTICULO_CUENTA
 (
        CTR_INVENTARIO,
        CTA_INVENTARIO
 )
go
 
 CREATE INDEX ARTCTAIFCTAVTALOC ON ARTICULO_CUENTA
 (
        CTR_VENTAS_LOC,
        CTA_VENTAS_LOC
 )
go
 
 CREATE INDEX ARTCTAIFCTAVTAEXP ON ARTICULO_CUENTA
 (
        CTR_VENTAS_EXP,
        CTA_VENTAS_EXP
 )
go
 
 CREATE INDEX ARTCTAIFCTADESVTAL ON ARTICULO_CUENTA
 (
        CTR_DESC_VENTA_LOC,
        CTA_DESC_VENTA_LOC
 )
go
 
 CREATE INDEX ARTCTAIFCTACMPIMP ON ARTICULO_CUENTA
 (
        CTR_COMPRA_IMP,
        CTA_COMPRA_IMP
 )
go
 
 CREATE INDEX ARTCTAIFCTADESVTAE ON ARTICULO_CUENTA
 (
        CTR_DESC_VENTA_EXP,
        CTA_DESC_VENTA_EXP
 )
go
 
 CREATE INDEX ARTCTAIFCTACSTVTAL ON ARTICULO_CUENTA
 (
        CTR_COST_VENTA_LOC,
        CTA_COST_VENTA_LOC
 )
go

 CREATE UNIQUE INDEX XIE1ATIFECH ON AUDIT_TRANS_INV
 (
        AUDIT_TRANS_INV,
        FECHA_HORA
 )
go
 
 CREATE INDEX FKAUTRINCONS ON AUDIT_TRANS_INV
 (
        CONSECUTIVO
 )
go
 
 CREATE INDEX AUDITINVIFUSUARIO ON AUDIT_TRANS_INV
 (
        USUARIO
 )
go
 
 CREATE INDEX AUDITINVIEFECHORA ON AUDIT_TRANS_INV
 (
        FECHA_HORA
 )
go
 
 CREATE INDEX AUDITINVIEAPLICAC ON AUDIT_TRANS_INV
 (
        APLICACION
 )
go
 

 CREATE INDEX BOLETAIFLOCALIZAC ON BOLETA_INV_FISICO
 (
        BODEGA,
        LOCALIZACION
 )
go
 
CREATE  INDEX BOLETAIFLOTE ON BOLETA_INV_FISICO (
         ARTICULO,
         LOTE )
go
 
 CREATE INDEX BOLETAIFARTICULO ON BOLETA_INV_FISICO
 (
        ARTICULO
 )
go
 
 CREATE INDEX BOLETAIFUSUARIO ON BOLETA_INV_FISICO
 (
        USUARIO
 )
go
 
 CREATE INDEX BOLETAIEARTBDLCLT ON BOLETA_INV_FISICO
 (
        ARTICULO,
        BODEGA,
        LOCALIZACION,
        LOTE
 )
go
 
 CREATE INDEX BOLETAIEBODLCLOT ON BOLETA_INV_FISICO
 (
        BODEGA,
        LOCALIZACION,
        LOTE
 )
go
 
 CREATE INDEX CLASIFIFUNDMEDIDA ON CLASIFICACION
 (
        UNIDAD_MEDIDA
 )
go
 
 CREATE INDEX CLASIFIEAGRUPA ON CLASIFICACION
 (
        AGRUPACION
 )
go
 
 CREATE INDEX CLASIFIEDESCRIP ON CLASIFICACION
 (
        DESCRIPCION
 )
go
 

 CREATE INDEX COSTSTDBATCHIFUSR ON COST_STD_BATCH
 (
        USUARIO
 )
go
 
 CREATE INDEX COSTOSTDDESGLIFART ON COSTO_STD_DESGL
 (
        ARTICULO
 )
go
 
 CREATE INDEX COSTOSTDDESGLIFUSR ON COSTO_STD_DESGL
 (
        USUARIO
 )
go
 
 CREATE INDEX UEPSPEPSIFARTICULO ON COSTO_UEPS_PEPS
 (
        ARTICULO
 )
go

CREATE INDEX EXISTBODCANTDISP ON EXISTENCIA_BODEGA
(
	CANT_DISPONIBLE
) 
WITH FILLFACTOR = 90  

go 

CREATE UNIQUE INDEX EXISTBODIFBODEGA ON EXISTENCIA_BODEGA
 (
        BODEGA,
        ARTICULO
 )
go
 
 CREATE INDEX EXISTBODIFARTICULO ON EXISTENCIA_BODEGA
 (
        ARTICULO
 )
go
 
 CREATE INDEX EXISTBODIFBOD ON EXISTENCIA_BODEGA
 (
        BODEGA
 )
go
 
 CREATE INDEX EXISTLOTEIFLOCALIZ ON EXISTENCIA_LOTE
 (
        BODEGA,
        LOCALIZACION
 )
go
 
 CREATE INDEX EXISTLOTEIFEXTBOD ON EXISTENCIA_LOTE
 (
        BODEGA,
        ARTICULO
 )
go
 
CREATE  INDEX EXISTLOTEIFLOTE ON EXISTENCIA_LOTE (
         ARTICULO,
         LOTE )
go
 
 CREATE INDEX EXISTLOTEIEBDLCLT ON EXISTENCIA_LOTE
 (
        LOCALIZACION,
        BODEGA,
        LOTE
 )
go
 
 CREATE INDEX EXISTLOTEIELOTBDLC ON EXISTENCIA_LOTE
 (
        LOCALIZACION,
        LOTE,
        BODEGA
 )
go
 
 CREATE INDEX FKEXIRESSECA ON EXISTENCIA_RESERVA
 (
        SERIE_CADENA
 )
go
 
 CREATE INDEX FKEXIRESBOLO ON EXISTENCIA_RESERVA
 (
        BODEGA,
        LOCALIZACION
 )
go
 
 CREATE INDEX EXISTRESIFEXISTBOD ON EXISTENCIA_RESERVA
 (
        ARTICULO,
        BODEGA
 )
go
 
CREATE  INDEX EXISTRESIFLOTE ON EXISTENCIA_RESERVA (
         ARTICULO,
         LOTE )
go
 
 CREATE INDEX EXISTRESIEIFUSR ON EXISTENCIA_RESERVA
 (
        USUARIO
 )
go
 
 CREATE INDEX XAK1EXISTENCIA_SERIE ON EXISTENCIA_SERIE
 (
        ARTICULO
 )
go

CREATE  INDEX EXISTSEREILOTE ON EXISTENCIA_SERIE (
         ARTICULO,
         LOTE )
go
 
 CREATE INDEX XAK2EXISTENCIA_SERIE ON EXISTENCIA_SERIE
 (
        BODEGA
 )
go
 
 CREATE INDEX XAK3EXISTENCIA_SERIE ON EXISTENCIA_SERIE
 (
        LOCALIZACION
 )
go
 
 CREATE INDEX XAK4EXISTENCIA_SERIE ON EXISTENCIA_SERIE
 (
        TIPO
 )
go
 
CREATE INDEX FKEXISERARBO ON EXISTENCIA_SERIE
 (
        ARTICULO,
        BODEGA
 )
go
 
 
 CREATE INDEX FKEXISERBOLO ON EXISTENCIA_SERIE
 (
        BODEGA,
        LOCALIZACION
 )
go
 
 CREATE INDEX GLOBALESCIIFPAQUET ON GLOBALES_CI
 (
        PAQUETE
 )
go
 
 CREATE INDEX GLOBALESCIIFTPASNT ON GLOBALES_CI
 (
        TIPO_ASIENTO
 )
go
 
CREATE  INDEX INGLOTIFLOTE ON INGRESOS_LOTE (
         ARTICULO,
         LOTE )
go
 
 CREATE INDEX FKLINDINAJCO ON LINEA_DOC_INV
 (
        AJUSTE_CONFIG
 )
go
 
 CREATE INDEX FKLINDINSECA ON LINEA_DOC_INV
 (
        SERIE_CADENA
 )
go
 
 CREATE INDEX FKLINDINNIT ON LINEA_DOC_INV
 (
        NIT
 )
go
 
 CREATE INDEX FKLINDINPIDI ON LINEA_DOC_INV
 (
        PAQUETE_INVENTARIO,
        DOCUMENTO_INV
 )
go
 
 CREATE INDEX FKLINDINARTI ON LINEA_DOC_INV
 (
        ARTICULO
 )
go
 
 
 CREATE INDEX FKLINDINBOLO ON LINEA_DOC_INV
 (
        BODEGA,
        LOCALIZACION
 )
go
 
 CREATE INDEX FKLINDINBDLD ON LINEA_DOC_INV
 (
        BODEGA_DESTINO,
        LOCALIZACION_DEST
 )
go
 
 CREATE INDEX FKLINDINCTCO ON LINEA_DOC_INV
 (
        CENTRO_COSTO
 )
go
 
 CREATE INDEX LINEADOCUNDMEDIDA ON LINEA_DOC_INV
 (
        UNIDAD_DISTRIBUCIO
 )
go

CREATE  INDEX LINDOCINVIELOTE ON LINEA_DOC_INV (
         ARTICULO,
         LOTE )
go
 
 CREATE INDEX LOTEIFARTICULO ON LOTE
 (
        ARTICULO
 )
go
 
 CREATE INDEX LOTEIFPROVEEDOR ON LOTE
 (
        PROVEEDOR
 )
go
 
 CREATE INDEX LOTEIEARTVENCE ON LOTE
 (
        ARTICULO,
        FECHA_VENCIMIENTO,
        ESTADO
 )
go
 
 CREATE INDEX LOTEIEVENCEESTADO ON LOTE
 (
        ESTADO,
        FECHA_VENCIMIENTO
 )
go
 
 CREATE INDEX LOTEIECUARENESTADO ON LOTE
 (
        ESTADO,
        FECHA_CUARENTENA
 )
go
 

CREATE  INDEX LOTESPIFLOTE ON LOTE_ESPE (
         ARTICULO,
         LOTE )
go
 
 
 CREATE INDEX PISTAEXISTDETART ON PISTA_EXISTEN_DET
 (
        ARTICULO
 )
go
 
 CREATE INDEX PISTAEXISTDETBOD ON PISTA_EXISTEN_DET
 (
        BODEGA
 )
go

CREATE  INDEX PISEXDETIELOTE ON PISTA_EXISTEN_DET (
         ARTICULO,
         LOTE )
go
 

 CREATE INDEX XAK1SERIE_CADENA_DET ON SERIE_CADENA_DET
 (
        SERIE_CADENA
 )
go
 
 CREATE INDEX TIPOAJUSTEIEDESCR ON TIPO_AJUSTE
 (
        DESCRIPCION
 )
go
 
 CREATE INDEX TIPOAJUSTEIECANNEG ON TIPO_AJUSTE
 (
        AJUSTE_A_CANT,
        AJUSTE_NEGATIVO
 )
go

CREATE INDEX XIETRANSINVAUXORD ON TRANS_INV_AUX
( 
	ORDEN
)
go
 
 CREATE INDEX FKTRAINVSECA ON TRANSACCION_INV
 (
        SERIE_CADENA
 )
go
 
 CREATE INDEX FKTRAINVNIT ON TRANSACCION_INV
 (
        NIT
 )
go
 
 CREATE INDEX FKTRAINVAJCO ON TRANSACCION_INV
 (
        AJUSTE_CONFIG
 )
go
 
 CREATE INDEX FKTRAINVBOLO ON TRANSACCION_INV
 (
        BODEGA,
        LOCALIZACION
 )
go
 
 
 CREATE INDEX FKTRAINVAUTI ON TRANSACCION_INV
 (
        AUDIT_TRANS_INV
 )
go
 
 CREATE INDEX FKTRAINVARTI ON TRANSACCION_INV
 (
        ARTICULO
 )
go
 
 CREATE INDEX FKTRAINVCTCO ON TRANSACCION_INV
 (
        CENTRO_COSTO
 )
go
 
 CREATE INDEX TRANSACCUNDMEDIDA ON TRANSACCION_INV
 (
        UNIDAD_DISTRIBUCIO
 )
go

CREATE  INDEX TRANSINVIE ON TRANSACCION_INV (
         ARTICULO,
         LOTE )
go
 
 CREATE INDEX TRANSINVIEARBDLCLT ON TRANSACCION_INV
 (
        ARTICULO,
        BODEGA,
        LOCALIZACION,
        LOTE
 )
go
 
 CREATE INDEX TRANSINVIEBODLCLT ON TRANSACCION_INV
 (
        BODEGA,
        LOCALIZACION,
        LOTE
 )
go
 
 CREATE INDEX TRANSINVIELTBDLC ON TRANSACCION_INV
 (
        BODEGA,
        LOTE,
        LOCALIZACION
 )
go
 
 CREATE INDEX TRANSINVIEFCHCNTP ON TRANSACCION_INV
 (
        FECHA,
        CONTABILIZADA,
        TIPO
 )
go
 
 CREATE INDEX TRANSINVIEARFCHBOD ON TRANSACCION_INV
 (
        ARTICULO,
        BODEGA,
        FECHA,
        TIPO
 )
go
 
 CREATE INDEX TRANSINVIEARTFECHH ON TRANSACCION_INV
 (
        ARTICULO,
        FECHA_HORA_TRANSAC
 )
go

CREATE INDEX TRANSINVFECHTIPO ON TRANSACCION_INV
 (
        FECHA,
        TIPO
 )
 go
 
 CREATE INDEX UNDMEDIDAIEDESC ON UNIDAD_DE_MEDIDA
 (
        DESCRIPCION
 )
go



CREATE INDEX XIE1TINVARTNATFCHF ON TRANSACCION_INV 
	( ARTICULO, NATURALEZA, FECHA, FECHA_HORA_TRANSAC, AUDIT_TRANS_INV, CONSECUTIVO )
go

CREATE INDEX XIE1TINVARTNATFCHT ON TRANSACCION_INV 
	( ARTICULO,TIPO,FECHA_HORA_TRANSAC )
go

CREATE INDEX XIE1TINVARTNATFCH ON TRANSACCION_INV 
	( ARTICULO,TIPO,FECHA )
go	



CREATE NONCLUSTERED INDEX Articulo_Articulo ON $$COMPANIA$$.ARTICULO
(
	ARTICULO ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go


CREATE STATISTICS ArticuloEstad1 ON $$COMPANIA$$.ARTICULO(TIPO,ARTICULO)
go

CREATE STATISTICS ArticuloEstad2 ON $$COMPANIA$$.EXISTENCIA_CIERRE(TIPO_FECHA,FECHA_CIERRE, ARTICULO)
go

CREATE STATISTICS ArticuloEstad3 ON $$COMPANIA$$.EXISTENCIA_CIERRE(BODEGA,TIPO_FECHA, FECHA_CIERRE)
go

CREATE STATISTICS ArticuloEstad4 ON $$COMPANIA$$.EXISTENCIA_CIERRE(ARTICULO,BODEGA, TIPO_FECHA)
go

CREATE NONCLUSTERED INDEX ExistenciaCierre_Cierre ON $$COMPANIA$$.EXISTENCIA_CIERRE 
(
	ARTICULO ASC,
	FECHA_CIERRE ASC,
	BODEGA ASC,
	TIPO_FECHA ASC
)
INCLUDE ( CANT_DISPONIBLE,
CANT_RESERVADA,
CANT_NO_APROBADA,
CANT_VENCIDA,
CANT_REMITIDA) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE STATISTICS ExistenciaCierreEst1 ON $$COMPANIA$$.EXISTENCIA_CIERRE(ARTICULO,TIPO_FECHA)
go


CREATE NONCLUSTERED INDEX [TransaccionInvRepValora] ON $$COMPANIA$$.TRANSACCION_INV 
(
	ARTICULO ASC,
	BODEGA ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE STATISTICS TransaccionInvEstad1 ON $$COMPANIA$$.TRANSACCION_INV(BODEGA,TIPO)
go

CREATE STATISTICS TransaccionInvEstad2 ON $$COMPANIA$$.TRANSACCION_INV(TIPO,ARTICULO,BODEGA)
go

 