
 
 ALTER TABLE AJUSTE_SUBSUBTIPO
        ADD CONSTRAINT SUBSUBAJU
               FOREIGN KEY (AJUSTE_CONFIG)
                              REFERENCES AJUSTE_CONFIG
go
 
 
 ALTER TABLE AJUSTE_SUBTIPO
        ADD CONSTRAINT SUBAJU
               FOREIGN KEY (AJUSTE_CONFIG)
                              REFERENCES AJUSTE_CONFIG
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE ALIAS_PRODUCCION
        ADD CONSTRAINT ALIASART
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE ART_UND_DISTRIBUCI
        ADD CONSTRAINT ARTUNDUNDMEDIDA
               FOREIGN KEY (UND_DISTRIBUCION)
                              REFERENCES UNIDAD_DE_MEDIDA
go
 
 
 ALTER TABLE ART_UND_DISTRIBUCI
        ADD CONSTRAINT ARTUNDARTICULO
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE ARTICULO
        ADD CONSTRAINT ARTUSUCREA
               FOREIGN KEY (USUARIO_CREACION)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE ARTICULO
        ADD CONSTRAINT ARTUSUMODIF
               FOREIGN KEY (USUARIO_ULT_MODIF)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE ARTICULO
        ADD CONSTRAINT ARTCLSF2
               FOREIGN KEY (CLASIFICACION_2)
                              REFERENCES CLASIFICACION
go
 
 
 ALTER TABLE ARTICULO
        ADD CONSTRAINT ARTCLSF3
               FOREIGN KEY (CLASIFICACION_1)
                              REFERENCES CLASIFICACION
go
 
 
 ALTER TABLE ARTICULO
        ADD CONSTRAINT ARTCTART
               FOREIGN KEY (ARTICULO_CUENTA)
                              REFERENCES ARTICULO_CUENTA
go
 
 
 ALTER TABLE ARTICULO
        ADD CONSTRAINT ARTICIMP
               FOREIGN KEY (IMPUESTO)
                              REFERENCES IMPUESTO
go
 
 
 ALTER TABLE ARTICULO
        ADD CONSTRAINT ARTIPROV
               FOREIGN KEY (PROVEEDOR)
                              REFERENCES PROVEEDOR
go
 
 
 ALTER TABLE ARTICULO
        ADD CONSTRAINT AUNMDVNT
               FOREIGN KEY (UNIDAD_VENTA)
                              REFERENCES UNIDAD_DE_MEDIDA
go
 
 
 ALTER TABLE ARTICULO
        ADD CONSTRAINT AUNMDEMP
               FOREIGN KEY (UNIDAD_EMPAQUE)
                              REFERENCES UNIDAD_DE_MEDIDA
go
 
 
 ALTER TABLE ARTICULO
        ADD CONSTRAINT AUNMDALM
               FOREIGN KEY (UNIDAD_ALMACEN)
                              REFERENCES UNIDAD_DE_MEDIDA
go
 
 
 ALTER TABLE ARTICULO
        ADD CONSTRAINT ARTCLSF1
               FOREIGN KEY (CLASIFICACION_3)
                              REFERENCES CLASIFICACION
go
 
 
 ALTER TABLE ARTICULO
        ADD CONSTRAINT ARTPLSER
               FOREIGN KEY (PLANTILLA_SERIE)
                              REFERENCES SERIE_PLANTILLA
go

ALTER TABLE ARTICULO
        ADD CONSTRAINT ARTCODRET
               FOREIGN KEY (CODIGO_RETENCION)
                              REFERENCES RETENCIONES
go


ALTER TABLE ARTICULO
         ADD CONSTRAINT RECOMPMODRET
         	FOREIGN KEY  ( RETENCION_COMPRA )
         		REFERENCES RETENCIONES ( CODIGO_RETENCION )
go         		


ALTER TABLE ARTICULO 
        ADD CONSTRAINT ARTMODRET
               FOREIGN KEY (MODELO_RETENCION)
               		REFERENCES MODELO_RETENCION
go               		



ALTER TABLE ARTICULO ADD 
	CONSTRAINT ARTESTILO 
		FOREIGN KEY (ESTILO)
			REFERENCES ARTICULO_ESTILO(ESTILO)
go


ALTER TABLE ARTICULO ADD 
	CONSTRAINT ARTTALLA 
		FOREIGN KEY (TALLA)
			REFERENCES ARTICULO_TALLA(TALLA)
go
			

ALTER TABLE ARTICULO ADD 
	CONSTRAINT ARTCOLOR 
		FOREIGN KEY (COLOR)
			REFERENCES ARTICULO_COLOR(COLOR)
go


 ALTER TABLE ARTICULO_ALTERNO
        ADD CONSTRAINT ARTALTAL
               FOREIGN KEY (ALTERNO)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE ARTICULO_ALTERNO
        ADD CONSTRAINT ARTALTAR
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC24
               FOREIGN KEY (CTR_SOBRANTE_REMIS, CTA_SOBRANTE_REMIS)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC18
               FOREIGN KEY (CTR_VENCIMIENTO, CTA_VENCIMIENTO)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC14
               FOREIGN KEY (CTR_COMS_COBRO_EXP, CTA_COMS_COBRO_EXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTCT5
               FOREIGN KEY (CTR_DESC_VENTA_LOC, CTA_DESC_VENTA_LOC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTCT1
               FOREIGN KEY (CTR_COST_VENTA_LOC, CTA_COST_VENTA_LOC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC21
               FOREIGN KEY (CTR_SOBR_INVENTFIS, CTA_SOBR_INVENTFIS)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTCT4
               FOREIGN KEY (CTR_COMS_VENTA_LOC, CTA_COMS_VENTA_LOC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTCT3
               FOREIGN KEY (CTR_DESC_VENTA_EXP, CTA_DESC_VENTA_EXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC20
               FOREIGN KEY (CTR_FALT_INVENTFIS, CTA_FALT_INVENTFIS)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC19
               FOREIGN KEY (CTR_VARIA_COSTO, CTA_VARIA_COSTO)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTCT2
               FOREIGN KEY (CTR_COST_VENTA_EXP, CTA_COST_VENTA_EXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTCT9
               FOREIGN KEY (CTR_VENTAS_LOC, CTA_VENTAS_LOC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTCT8
               FOREIGN KEY (CTR_DESC_LINEA_LOC, CTA_DESC_LINEA_LOC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC10
               FOREIGN KEY (CTR_DESC_LINEA_EXP, CTA_DESC_LINEA_EXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTCT7
               FOREIGN KEY (CTR_VENTAS_EXP, CTA_VENTAS_EXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTCT6
               FOREIGN KEY (CTR_COMS_VENTA_EXP, CTA_COMS_VENTA_EXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC13
               FOREIGN KEY (CTR_COST_DESC_EXP, CTA_COST_DESC_EXP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC11
               FOREIGN KEY (CTR_INVENTARIO, CTA_INVENTARIO)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC12
               FOREIGN KEY (CTR_COST_DESC_LOC, CTA_COST_DESC_LOC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC16
               FOREIGN KEY (CTR_COMPRA_IMP, CTA_COMPRA_IMP)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC15
               FOREIGN KEY (CTR_COMS_COBRO_LOC, CTA_COMS_COBRO_LOC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC17
               FOREIGN KEY (CTR_COMPRA_LOC, CTA_COMPRA_LOC)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC22
               FOREIGN KEY (CTR_INV_REMITIDO, CTA_INV_REMITIDO)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC23
               FOREIGN KEY (CTR_FALTANTE_REMIS, CTA_FALTANTE_REMIS)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC25
               FOREIGN KEY (CTR_MAT_PROCESO, CTA_MAT_PROCESO)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC26
               FOREIGN KEY (CTR_CONS_NORMAL, CTA_CONS_NORMAL)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC27
               FOREIGN KEY (CTR_CONS_RETRABAJO, CTA_CONS_RETRABAJO)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC28
               FOREIGN KEY (CTR_CONS_GASTO, CTA_CONS_GASTO)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT CTARTC29
               FOREIGN KEY (CTR_CONS_DESPERDIC, CTA_CONS_DESPERDIC)
                              REFERENCES CENTRO_CUENTA
go
 

ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT ARCTADBLCTRCTA
               FOREIGN KEY (CTR_DESC_BONIF_LOC, CTA_DESC_BONIF_LOC)
                              REFERENCES CENTRO_CUENTA
go


ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT ARCTADBEXCTRCTA
               FOREIGN KEY (CTR_DESC_BONIF_EXP, CTA_DESC_BONIF_EXP)
                              REFERENCES CENTRO_CUENTA                              
go


ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT ARCTADVLCTRCTA
               FOREIGN KEY (CTR_DEV_VENTAS_LOC , CTA_DEV_VENTAS_LOC)
                              REFERENCES CENTRO_CUENTA
go


ALTER TABLE ARTICULO_CUENTA
        ADD CONSTRAINT ARCTADVEXCTRCTA
               FOREIGN KEY (CTR_DEV_VENTAS_EXP, CTA_DEV_VENTAS_EXP)
                              REFERENCES CENTRO_CUENTA
go


ALTER TABLE ARTICULO_CUENTA 
        ADD CONSTRAINT ARTCTA_CTACRETASUM
		FOREIGN KEY (CTR_CTO_RET_ASUM, CTA_CTB_RET_ASUM)
               		REFERENCES CENTRO_CUENTA
go


ALTER TABLE $$COMPANIA$$.ARTICULO_CUENTA
	ADD CONSTRAINT ARTCTAVENTEXENLOC 
		FOREIGN KEY (CTR_VENTAS_EXEN_LOC,CTA_VENTAS_EXEN_LOC)
			REFERENCES $$COMPANIA$$.CENTRO_CUENTA 
go
			
ALTER TABLE $$COMPANIA$$.ARTICULO_CUENTA
	ADD CONSTRAINT ARTCTAVENTEXENEXP 
		FOREIGN KEY (CTR_VENTAS_EXEN_EXP,CTA_VENTAS_EXEN_EXP)
			REFERENCES $$COMPANIA$$.CENTRO_CUENTA 
go

ALTER TABLE ARTICULO_ESPE
        ADD CONSTRAINT ALIASARTESP
               FOREIGN KEY (ARTICULO)
                              REFERENCES ALIAS_PRODUCCION
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE ARTICULO_ESPE
        ADD CONSTRAINT ESPART
               FOREIGN KEY (ATRIBUTO)
                              REFERENCES ATRIBUTO
go
 
 
 ALTER TABLE ARTICULO_FOTO
        ADD CONSTRAINT AFOTOART
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE AUDIT_TRANS_INV
        ADD CONSTRAINT AUDITUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE AUDIT_TRANS_INV
        ADD CONSTRAINT AUDCONS
               FOREIGN KEY (CONSECUTIVO)
                              REFERENCES CONSECUTIVO_CI
go


ALTER TABLE AUDIT_TRANS_INV
        ADD CONSTRAINT ATIUSRAPR
               FOREIGN KEY (USUARIO_APRO)
                              REFERENCES ERPADMIN.USUARIO
go                              
 
 
 ALTER TABLE AUTOR_VENTA 
 	ADD  CONSTRAINT FK_AUTOR_VENTA_CLIENTE FOREIGN KEY(CLIENTE)
			REFERENCES CLIENTE (CLIENTE)
go			
 
 
 ALTER TABLE BOLETA_INV_FISICO
        ADD CONSTRAINT INVFUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE BOLETA_INV_FISICO
        ADD CONSTRAINT INVFIART
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
ALTER TABLE BOLETA_INV_FISICO
         ADD CONSTRAINT INVFILOT
         FOREIGN KEY  ( ARTICULO, LOTE )
         REFERENCES LOTE ( ARTICULO, LOTE )
go
 
 
 ALTER TABLE BOLETA_INV_FISICO
        ADD CONSTRAINT INVFILOC
               FOREIGN KEY (BODEGA, LOCALIZACION)
                              REFERENCES LOCALIZACION
go
 
 
 ALTER TABLE BOLETA_INV_FISICO
        ADD CONSTRAINT BOLNXBSCAD
               FOREIGN KEY (SERIE_CADENA_NOAPR)
                              REFERENCES SERIE_CADENA
go
 
 
 ALTER TABLE BOLETA_INV_FISICO
        ADD CONSTRAINT BOLDXBSCAD
               FOREIGN KEY (SERIE_CADENA_DISP)
                              REFERENCES SERIE_CADENA
go
 
 
 ALTER TABLE BOLETA_INV_FISICO
        ADD CONSTRAINT BOLVXBSCAD
               FOREIGN KEY (SERIE_CADENA_VENC)
                              REFERENCES SERIE_CADENA
go
 
 
 ALTER TABLE CLASIFICACION
        ADD CONSTRAINT CLSUNMD
               FOREIGN KEY (UNIDAD_MEDIDA)
                              REFERENCES UNIDAD_DE_MEDIDA
go
 
 
 ALTER TABLE CLASIFICACION
        ADD CONSTRAINT CLASPLSE
               FOREIGN KEY (PLANTILLA_SERIE)
                              REFERENCES SERIE_PLANTILLA
go

ALTER TABLE CLASIFICACION_ADI_VALOR
        ADD CONSTRAINT CLASIFI_VALOR
               FOREIGN KEY (CLASIFICACION)
                              REFERENCES CLASIFICACION_ADI
                              ON DELETE CASCADE
go

ALTER TABLE CLASIFIC_ADI_ARTICULO
        ADD CONSTRAINT CLASIFI_ARTICULO
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
                              ON DELETE CASCADE
go                              

ALTER TABLE CLASIFIC_ADI_ARTICULO
        ADD CONSTRAINT CLASIFI_ART_VALOR
               FOREIGN KEY (CLASIFICACION,VALOR)
                              REFERENCES CLASIFICACION_ADI_VALOR
                              ON DELETE CASCADE
go  
 
 ALTER TABLE CLASIFICACION_COMPRA 
 	ADD  CONSTRAINT FK_AUTOR_COMPRA_CLASIF_COMPRA FOREIGN KEY(CODIGO)
 			REFERENCES AUTOR_COMPRA (CODIGO)
go 			
 
 ALTER TABLE CLASIFICACION_COMPRA 
 	ADD  CONSTRAINT FK_CLASIFICACION_CLASIF_COMPRA FOREIGN KEY(CODIGO_CLASIFICACION)
			REFERENCES CLASIFICACION (CLASIFICACION)
 go
 
 ALTER TABLE CLASIFICACION_VENTA 
 	ADD CONSTRAINT FK_AUTOR_VENTA_CLASIF_VENTA FOREIGN KEY(CODIGO)
 			REFERENCES AUTOR_VENTA (CODIGO)
go 			
 
 ALTER TABLE CLASIFICACION_VENTA 
 	ADD  CONSTRAINT FK_ARTICULO_CLASIF_VENTA FOREIGN KEY(CODIGO_ARTICULO)
			REFERENCES ARTICULO (ARTICULO)
go
 
 ALTER TABLE CONSEC_AJUSTE_CONF
        ADD CONSTRAINT CONSECON
               FOREIGN KEY (CONSECUTIVO)
                              REFERENCES CONSECUTIVO_CI
go
  
 ALTER TABLE CONSEC_AJUSTE_CONF
        ADD CONSTRAINT CONSEAJU
               FOREIGN KEY (AJUSTE_CONFIG)
                              REFERENCES AJUSTE_CONFIG
go
 
 
 ALTER TABLE CONSEC_USUARIO
        ADD CONSTRAINT CSECCON
               FOREIGN KEY (CONSECUTIVO)
                              REFERENCES CONSECUTIVO_CI
go
 
 
 ALTER TABLE CONSEC_USUARIO
        ADD CONSTRAINT CSECUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CONSECUTIVO_CI
        ADD CONSTRAINT CONSUSR
               FOREIGN KEY (ULTIMO_USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE COST_STD_BATCH
        ADD CONSTRAINT CSTDBART
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE COST_STD_BATCH
        ADD CONSTRAINT CSTBATUS
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
ALTER TABLE COST_STD_BATCH         
	ADD CONSTRAINT FKCOSTSTDBATCHBODEGA
		FOREIGN KEY ( BODEGA )
			REFERENCES BODEGA ( BODEGA )
go			
 
 
 ALTER TABLE COSTO_STD_DESGL
        ADD CONSTRAINT DSTDUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE COSTO_STD_DESGL
        ADD CONSTRAINT CTSTDART
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
ALTER TABLE COSTO_STD_DESGL 
	ADD CONSTRAINT FKCOSTSTDDESGLBODEGA
               FOREIGN KEY ( BODEGA ) 
               		REFERENCES BODEGA ( BODEGA )
go               		
 
 
 ALTER TABLE COSTO_UEPS_PEPS
        ADD CONSTRAINT UPEPSART
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE DOCUMENTO_INV
        ADD CONSTRAINT DOCUSUAR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE DOCUMENTO_INV
        ADD CONSTRAINT CIPAQDOC
               FOREIGN KEY (PAQUETE_INVENTARIO)
                              REFERENCES PAQUETE_INVENTARIO
go
 
 
 ALTER TABLE DOCUMENTO_INV
        ADD CONSTRAINT DOCCONS
               FOREIGN KEY (CONSECUTIVO)
                              REFERENCES CONSECUTIVO_CI
go


ALTER TABLE DOCUMENTO_INV 
        ADD CONSTRAINT DINVUSRAPR
               FOREIGN KEY (USUARIO_APRO)
                              REFERENCES ERPADMIN.USUARIO
go                          
 
 
 ALTER TABLE EXISTENCIA_BODEGA
        ADD CONSTRAINT EXTBODBD
               FOREIGN KEY (BODEGA)
                              REFERENCES BODEGA
go
 
 
 ALTER TABLE EXISTENCIA_BODEGA
        ADD CONSTRAINT EXBODART
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 

ALTER TABLE EXISTENCIA_CIERRE
	ADD CONSTRAINT FKEXISTCIERREARTICULO
		FOREIGN KEY ( ARTICULO )
			REFERENCES ARTICULO ( ARTICULO )
go
                              
ALTER TABLE EXISTENCIA_CIERRE
	ADD CONSTRAINT FKEXISTCIERREBODEGA
		FOREIGN KEY ( BODEGA )
			REFERENCES BODEGA ( BODEGA )
go 
 
 
 ALTER TABLE EXISTENCIA_LOTE
         ADD CONSTRAINT EXISLOTE
         FOREIGN KEY  ( ARTICULO, LOTE )
         REFERENCES LOTE ( ARTICULO, LOTE )
go
 
 
 ALTER TABLE EXISTENCIA_LOTE
        ADD CONSTRAINT EXLOTEXB
               FOREIGN KEY (ARTICULO, BODEGA)
                              REFERENCES EXISTENCIA_BODEGA
go
 
 
 ALTER TABLE EXISTENCIA_LOTE
        ADD CONSTRAINT EXLOTLOC
               FOREIGN KEY (BODEGA, LOCALIZACION)
                              REFERENCES LOCALIZACION
go
 
 
 ALTER TABLE EXISTENCIA_RESERVA
        ADD CONSTRAINT EXRESUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
ALTER TABLE EXISTENCIA_RESERVA
         ADD CONSTRAINT EXTRELOT
         FOREIGN KEY  ( ARTICULO, LOTE )
         REFERENCES LOTE ( ARTICULO, LOTE )
go
 
 
 ALTER TABLE EXISTENCIA_RESERVA
        ADD CONSTRAINT EXRESEXB
               FOREIGN KEY (ARTICULO, BODEGA)
                              REFERENCES EXISTENCIA_BODEGA
go
 
 
 ALTER TABLE EXISTENCIA_RESERVA
        ADD CONSTRAINT EXISTRELOC
               FOREIGN KEY (BODEGA, LOCALIZACION)
                              REFERENCES LOCALIZACION
go
 
 
 ALTER TABLE EXISTENCIA_RESERVA
        ADD CONSTRAINT EXISTRESRVSERIECAD
               FOREIGN KEY (SERIE_CADENA)
                              REFERENCES SERIE_CADENA
go
 
 
 ALTER TABLE EXISTENCIA_SERIE
        ADD CONSTRAINT EXSERLOC
               FOREIGN KEY (BODEGA, LOCALIZACION)
                              REFERENCES LOCALIZACION
go
 
 
ALTER TABLE EXISTENCIA_SERIE
         ADD CONSTRAINT EXSERLOTE
         FOREIGN KEY  ( ARTICULO, LOTE )
         REFERENCES LOTE ( ARTICULO, LOTE )
go
 
 
 ALTER TABLE EXISTENCIA_SERIE
        ADD CONSTRAINT EXSEREXBOD
               FOREIGN KEY (ARTICULO, BODEGA)
                              REFERENCES EXISTENCIA_BODEGA
go
 
 
 ALTER TABLE GLOBALES_CI
        ADD CONSTRAINT GBCITASN
               FOREIGN KEY (TIPO_ASIENTO)
                              REFERENCES TIPO_ASIENTO
go
 
 
 ALTER TABLE GLOBALES_CI
        ADD CONSTRAINT GBCIPAQ
               FOREIGN KEY (PAQUETE)
                              REFERENCES PAQUETE
go
 
 
ALTER TABLE INGRESOS_LOTE
         ADD CONSTRAINT LOTEINGR
         FOREIGN KEY  ( ARTICULO, LOTE )
         REFERENCES LOTE ( ARTICULO, LOTE )
go
 
 
 ALTER TABLE LINEA_DOC_INV
        ADD CONSTRAINT LINEADOCUNDMEDIDA
               FOREIGN KEY (UNIDAD_DISTRIBUCIO)
                              REFERENCES UNIDAD_DE_MEDIDA
go
 
 
 ALTER TABLE LINEA_DOC_INV
        ADD CONSTRAINT LNDOCLD
               FOREIGN KEY (BODEGA_DESTINO, LOCALIZACION_DEST)
                              REFERENCES LOCALIZACION
go
 
 
 ALTER TABLE LINEA_DOC_INV
        ADD CONSTRAINT LIDOCLOC
               FOREIGN KEY (BODEGA, LOCALIZACION)
                              REFERENCES LOCALIZACION
go
 
 
ALTER TABLE LINEA_DOC_INV
         ADD CONSTRAINT LNDOCLOT
         FOREIGN KEY  ( ARTICULO, LOTE )
         REFERENCES LOTE ( ARTICULO, LOTE )
go
 
 
 ALTER TABLE LINEA_DOC_INV
        ADD CONSTRAINT LNDOCART
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE LINEA_DOC_INV
        ADD CONSTRAINT CIDOCLIN
               FOREIGN KEY (PAQUETE_INVENTARIO, DOCUMENTO_INV)
                              REFERENCES DOCUMENTO_INV
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE LINEA_DOC_INV
        ADD CONSTRAINT LINDONIT
               FOREIGN KEY (NIT)
                              REFERENCES NIT
go
 
 
 ALTER TABLE LINEA_DOC_INV
        ADD CONSTRAINT LDOCINVSCAD
               FOREIGN KEY (SERIE_CADENA)
                              REFERENCES SERIE_CADENA
go
 
 
 ALTER TABLE LINEA_DOC_INV
        ADD CONSTRAINT LINDOCAJU
               FOREIGN KEY (AJUSTE_CONFIG)
                              REFERENCES AJUSTE_CONFIG
go
 
ALTER TABLE LINEA_DOC_INV   
        ADD CONSTRAINT CTRCTA_LINTR
               FOREIGN KEY (CENTRO_COSTO , CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go                              
 
 ALTER TABLE LOTE
        ADD CONSTRAINT LOTEPROV
               FOREIGN KEY (PROVEEDOR)
                              REFERENCES PROVEEDOR
go
 
 
 ALTER TABLE LOTE
        ADD CONSTRAINT LOTEART
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
ALTER TABLE LOTE_ESPE
         ADD CONSTRAINT LOTEESPE
         FOREIGN KEY  ( ARTICULO, LOTE )
         REFERENCES LOTE ( ARTICULO, LOTE )
go
 
 
 ALTER TABLE LOTE_ESPE
        ADD CONSTRAINT LOTESPATR
               FOREIGN KEY (ATRIBUTO)
                              REFERENCES ATRIBUTO
go
 
 
 ALTER TABLE PAQUETE_INVENTARIO
        ADD CONSTRAINT PAQUSR1
               FOREIGN KEY (USUARIO_CREADOR)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE PAQUETE_INVENTARIO
        ADD CONSTRAINT PAQUSR2
               FOREIGN KEY (ULTIMO_USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 

ALTER TABLE PEDIMENTO
         ADD CONSTRAINT PEDADU
         FOREIGN KEY  ( ADUANA )
         REFERENCES ADUANA ( ADUANA )
go
         
ALTER TABLE PEDIMENTO
         ADD CONSTRAINT PEDAGADU
         FOREIGN KEY  ( AGENTE_ADUANAL )
         REFERENCES AGENTE_ADUANAL ( AGENTE_ADUANAL )
go

ALTER TABLE PEDIMENTO_LOTE
         ADD CONSTRAINT PELOPEDI
         FOREIGN KEY  ( PEDIMENTO )
         REFERENCES PEDIMENTO ( PEDIMENTO )
go

ALTER TABLE PEDIMENTO_LOTE
         ADD CONSTRAINT PELOLOTE
         FOREIGN KEY  ( ARTICULO, LOTE )
         REFERENCES LOTE ( ARTICULO, LOTE )
go
 
ALTER TABLE PISTA_EXISTEN_DET
         ADD CONSTRAINT EXDETLOT
         FOREIGN KEY  ( ARTICULO, LOTE )
         REFERENCES LOTE ( ARTICULO, LOTE )
go
 
 
 ALTER TABLE PISTA_EXISTEN_DET
        ADD CONSTRAINT EDETEBOD
               FOREIGN KEY (ARTICULO, BODEGA)
                              REFERENCES EXISTENCIA_BODEGA
go
 
 
 ALTER TABLE PISTA_EXISTEN_DET
        ADD CONSTRAINT EXDETLOC
               FOREIGN KEY (BODEGA, LOCALIZACION)
                              REFERENCES LOCALIZACION
go
 
 
 ALTER TABLE PISTA_EXISTEN_DET
        ADD CONSTRAINT DETPTAEX
               FOREIGN KEY (FECHA)
                              REFERENCES PISTA_EXISTENCIA
go
 
 
 ALTER TABLE PISTA_EXISTENCIA
        ADD CONSTRAINT PTAEXUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 

ALTER TABLE PRESUPUESTO_CI_CR 
	ADD CONSTRAINT FK_AUDITTRANS
		FOREIGN KEY (AUDIT_TRANS_INV)
				REFERENCES AUDIT_TRANS_INV(AUDIT_TRANS_INV)
go


 
ALTER TABLE PRESUPUESTO_CI_CR 
	ADD CONSTRAINT FK_PAQUETINVENTARIO
		FOREIGN KEY (PAQUETE_INVENTARIO)
				REFERENCES PAQUETE_INVENTARIO(PAQUETE_INVENTARIO)
go


ALTER TABLE PRESUPUESTO_CI_CR 
	ADD CONSTRAINT FK_PRESUPUESTOCR
		FOREIGN KEY (PRESUPUESTO)
				REFERENCES PRESUPUESTO_CR(PRESUPUESTO)
go
 
 ALTER TABLE SERIE_CADENA
        ADD CONSTRAINT SECADUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE SERIE_CADENA_DET
        ADD CONSTRAINT SCADDETSCAD
               FOREIGN KEY (SERIE_CADENA)
                              REFERENCES SERIE_CADENA
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE TRANS_INV_AUX
        ADD CONSTRAINT TRANSAUX
               FOREIGN KEY (AUDIT_TRANS_INV, CONSECUTIVO)
                              REFERENCES TRANSACCION_INV
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE TRANSACCION_INV
        ADD CONSTRAINT TRANSACCUNDMEDIDA
               FOREIGN KEY (UNIDAD_DISTRIBUCIO)
                              REFERENCES UNIDAD_DE_MEDIDA
go
 
 

 ALTER TABLE TRANSACCION_INV
        ADD CONSTRAINT TRANSART
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE TRANSACCION_INV
        ADD CONSTRAINT TRANSAUD
               FOREIGN KEY (AUDIT_TRANS_INV)
                              REFERENCES AUDIT_TRANS_INV
go
 
 
ALTER TABLE TRANSACCION_INV
         ADD CONSTRAINT TRANSLOT
         FOREIGN KEY  ( ARTICULO, LOTE )
         REFERENCES LOTE ( ARTICULO, LOTE )
go
 
 
 ALTER TABLE TRANSACCION_INV
        ADD CONSTRAINT TRANSLOC
               FOREIGN KEY (BODEGA, LOCALIZACION)
                              REFERENCES LOCALIZACION
go
 
 
 ALTER TABLE TRANSACCION_INV
        ADD CONSTRAINT TRANAJU
               FOREIGN KEY (AJUSTE_CONFIG)
                              REFERENCES AJUSTE_CONFIG
go
 
 
 ALTER TABLE TRANSACCION_INV
        ADD CONSTRAINT TRAINNIT
               FOREIGN KEY (NIT)
                              REFERENCES NIT
go
 
 
 ALTER TABLE TRANSACCION_INV
        ADD CONSTRAINT TINVSCAD
               FOREIGN KEY (SERIE_CADENA)
                              REFERENCES SERIE_CADENA
go


ALTER TABLE TRANSACCION_INV 
        ADD CONSTRAINT CTRCTA_TRANS
               FOREIGN KEY (CENTRO_COSTO , CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go                              
 
 ALTER TABLE USUARIO_AJUSTE
        ADD CONSTRAINT AJUUSUARIO
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE USUARIO_AJUSTE
        ADD CONSTRAINT USRAJU
               FOREIGN KEY (AJUSTE_CONFIG)
                              REFERENCES AJUSTE_CONFIG
                              ON DELETE CASCADE
go
 
 
ALTER TABLE ARTICULO
         ADD CONSTRAINT ARTCLASIF4
         	FOREIGN KEY  ( CLASIFICACION_4 )
         		REFERENCES CLASIFICACION ( CLASIFICACION )
go

ALTER TABLE ARTICULO
         ADD CONSTRAINT ARTCLASIF5
         	FOREIGN KEY  ( CLASIFICACION_5 )
         		REFERENCES CLASIFICACION ( CLASIFICACION )
go

ALTER TABLE ARTICULO
         ADD CONSTRAINT ARTCLASIF6
        	 FOREIGN KEY  ( CLASIFICACION_6 )
         		REFERENCES CLASIFICACION ( CLASIFICACION )
go




ALTER TABLE $$COMPANIA$$.ARTICULO_CUENTA
        ADD CONSTRAINT ACCCAJU
               FOREIGN KEY (CTR_CTO_AJU, CTA_CTB_AJU)
                              REFERENCES $$COMPANIA$$.CENTRO_CUENTA
                              
go
                              
                              
                              
 
 ALTER TABLE $$COMPANIA$$.ARTICULO_CUENTA
        ADD CONSTRAINT ACCCAJUCMV
               FOREIGN KEY (CTR_CTO_AJU_CMV, CTA_CTB_AJU_CMV)
                              REFERENCES $$COMPANIA$$.CENTRO_CUENTA
                             
      
go