ALTER TABLE ADICIONALEMPLEADO
	ADD CONSTRAINT FKADICIONALEMPADICIONAL 
		FOREIGN KEY (ADICIONAL)
			REFERENCES ADICIONAL (ADICIONAL)
				ON DELETE CASCADE
go
				
				
ALTER TABLE ADICIONALEMPLEADO
	ADD	CONSTRAINT FKADCIONALEMPEMPLEADO
		FOREIGN KEY (EMPLEADO)
			REFERENCES EMPLEADO (EMPLEADO)
				ON DELETE CASCADE
go


ALTER TABLE $$COMPANIA$$.ADICIONALNOMINA 
	ADD CONSTRAINT FKADICIONALNOMINA
		FOREIGN KEY ( ADICIONAL ) 
			REFERENCES $$COMPANIA$$.ADICIONAL_NOMINA ( ADICIONAL )
go


ALTER TABLE $$COMPANIA$$.ADICIONAL_NOMINA_VALOR
	ADD CONSTRAINT FKADICIONALNOMINAVALOR
		FOREIGN KEY ( ADICIONAL ) 
			REFERENCES $$COMPANIA$$.ADICIONAL_NOMINA ( ADICIONAL )
go

ALTER TABLE ADICIONAL_VALOR
	ADD CONSTRAINT FKADCIONALVALORADICIONAL
		FOREIGN KEY(ADICIONAL)
			REFERENCES ADICIONAL(ADICIONAL)
				ON DELETE CASCADE
go


ALTER TABLE  ADMIN_COTIZANTE
         ADD CONSTRAINT ADCOTEM
         	FOREIGN KEY  ( EMPLEADO )
         		REFERENCES COTIZANTE ( EMPLEADO )
go

ALTER TABLE  ADMIN_COTIZANTE
         ADD CONSTRAINT ADCOTADMIN
         	FOREIGN KEY  ( ADMINISTRADORA )
         		REFERENCES ADMINISTRADORA ( ADMINISTRADORA )
go   


ALTER TABLE ADMIN_COTIZANTE
	ADD CONSTRAINT COTZADMACCION
		FOREIGN KEY (NUMERO_ACCION)
			REFERENCES EMPLEADO_ACC_PER (NUMERO_ACCION)
go			


ALTER TABLE ADMIN_CONCEPTO
        ADD CONSTRAINT ADMINCONCONCEPTO
               FOREIGN KEY (CONCEPTO)
                              REFERENCES CONCEPTO
go   

ALTER TABLE  ADMIN_CONCEPTO
         ADD CONSTRAINT ADMINCONCADMINIST
         	FOREIGN KEY  ( ADMINISTRADORA )
         		REFERENCES ADMINISTRADORA ( ADMINISTRADORA )
go   

 
 ALTER TABLE CENTRO_CONCEPTO
        ADD CONSTRAINT CTCOCTA1
               FOREIGN KEY (CUENTA_CONTABLE)
                              REFERENCES CUENTA_CONTABLE
go
 
 
 ALTER TABLE CENTRO_CONCEPTO
        ADD CONSTRAINT CECOCTRC
               FOREIGN KEY (CENTRO_COSTO)
                              REFERENCES CENTRO_COSTO
go
 
 
 ALTER TABLE CENTRO_CONCEPTO
        ADD CONSTRAINT CTRCOCON
               FOREIGN KEY (CONCEPTO)
                              REFERENCES CONCEPTO
go
 
ALTER TABLE $$COMPANIA$$.CODING_CARTA_RENTA ADD 
	CONSTRAINT FK_CODING_CARTA_RENTA
		FOREIGN KEY (COD_INGRESO)
			REFERENCES $$COMPANIA$$.COD_INGRESO (COD_INGRESO)
go
 
 ALTER TABLE CENTRO_CONCEPTO
        ADD CONSTRAINT CTRCCTA
               FOREIGN KEY (CUENTA_CONTRA)
                              REFERENCES CUENTA_CONTABLE
go
 
 
  ALTER TABLE COD_OBSERVA_ISSS
         ADD CONSTRAINT FKTIPOACC
                FOREIGN KEY (ACCION_PERSONAL)
                               REFERENCES $$COMPANIA$$.TIPO_ACCION
go                               
 
  ALTER TABLE COD_OBSERVA_ISSS
         ADD CONSTRAINT FKCONCEP
                FOREIGN KEY (CONCEPTO)
                              REFERENCES $$COMPANIA$$.CONCEPTO
 go
 
 
 
 ALTER TABLE CONCEPTO_PUESTO
 	ADD CONSTRAINT CONPUESCON 
 		FOREIGN KEY (CONCEPTO)
 			REFERENCES CONCEPTO (CONCEPTO)
 				ON DELETE CASCADE
 go
 
 
 ALTER TABLE CONCEPTO_PUESTO
 	ADD CONSTRAINT CONPUESPUES
 		FOREIGN KEY (PUESTO)
 			REFERENCES PUESTO (PUESTO)
				ON DELETE CASCADE
go
 
 
 ALTER TABLE CONC_FORM_CONCEPTO
        ADD CONSTRAINT COFOCOCO
               FOREIGN KEY (CONCEPTO_USA)
                              REFERENCES CONCEPTO
go
 
 
 ALTER TABLE CONC_FORM_CONCEPTO
        ADD CONSTRAINT COFOCOCF
               FOREIGN KEY (CONCEPTO, SECUENCIA)
                              REFERENCES CONCEPTO_FORMULA
go
 
 
 ALTER TABLE CONC_FORM_RUBRO
        ADD CONSTRAINT COFORUCF
               FOREIGN KEY (CONCEPTO, SECUENCIA)
                              REFERENCES CONCEPTO_FORMULA
go
 

ALTER TABLE CONCEPTO
	ADD CONSTRAINT CONCPROV
		FOREIGN KEY (PROVEEDOR)
			REFERENCES PROVEEDOR ( PROVEEDOR )
go	
	
 
 ALTER TABLE CONCEPTO_FORMULA
        ADD CONSTRAINT COFOCONC
               FOREIGN KEY (CONCEPTO)
                              REFERENCES CONCEPTO
go
 
 
ALTER TABLE CONCEPTO_LIQUIDAC
        ADD CONSTRAINT COLIMONE
               FOREIGN KEY (MONEDA)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE CONCEPTO_LIQUIDAC
        ADD CONSTRAINT COLICONC
               FOREIGN KEY (CONCEPTO)
                              REFERENCES CONCEPTO
go
 
 
 ALTER TABLE CONCEPTO_LIQUIDAC
        ADD CONSTRAINT COLICTBA
               FOREIGN KEY (CUENTA_BANCARIA)
                              REFERENCES CUENTA_BANCARIA
go
 
 
 ALTER TABLE CONCEPTO_LIQUIDAC
        ADD CONSTRAINT COLIUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CONCEPTO_USUARIO
        ADD CONSTRAINT CONUSUS
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CONCEPTO_USUARIO
        ADD CONSTRAINT CONUSNOM
               FOREIGN KEY (NOMINA)
                              REFERENCES NOMINA
go
 
 
 ALTER TABLE CONCEPTO_USUARIO
        ADD CONSTRAINT CONUSCON
               FOREIGN KEY (CONCEPTO)
                              REFERENCES CONCEPTO
go



ALTER TABLE CONSTANTE_CALC_VALOR
         ADD CONSTRAINT FKVALORCONSTANTE
         	FOREIGN KEY  ( CONSTANTE )
         		REFERENCES CONSTANTE_CALCULO ( CONSTANTE )
	 			ON DELETE CASCADE
go




ALTER TABLE COTIZANTE
        ADD CONSTRAINT COTIZAEMP
               FOREIGN KEY (EMPLEADO)
               		REFERENCES EMPLEADO ( EMPLEADO )
go

ALTER TABLE COTIZANTE
        ADD CONSTRAINT TIPOCOTCOT
               FOREIGN KEY (TIPO_COTIZANTE)
               		REFERENCES TIPO_COTIZANTE (TIPO_COTIZANTE )
go

ALTER TABLE COTIZANTE
        ADD CONSTRAINT SUBTICOTCOT
               FOREIGN KEY (SUBTIPO_COTIZANTE)
               		REFERENCES SUBTIPO_COTIZANTE (SUBTIPO_COTIZANTE)
go               		


ALTER TABLE COTIZANTE
        ADD CONSTRAINT CTRTRAB_COTI
               FOREIGN KEY (CENTRO_TRABAJO)
                              REFERENCES CENTRO_TRABAJO
go

  ALTER TABLE COTIZANTE 
		ADD CONSTRAINT FK_COTIZANTE_DIVISION_G
			FOREIGN KEY (PAIS,DIVISION_GEOGRAFICA,MUNICIPIO) 
				REFERENCES DIVISION_GEOGRAFICA2 (PAIS,DIVISION_GEOGRAFICA1,DIVISION_GEOGRAFICA2)
go

	ALTER TABLE COTIZANTE 
		ADD CONSTRAINT FK_COTIZANTE_DIVISION_G2
			FOREIGN KEY (PAIS,DEPARTAMENTO) 
					REFERENCES DIVISION_GEOGRAFICA1 (PAIS,DIVISION_GEOGRAFICA1)
go			


	ALTER TABLE CONTROL_HORAS_INCAP
		ADD CONSTRAINT FKINCEMP 
			FOREIGN KEY (EMPLEADO)
				REFERENCES EMPLEADO
go

	ALTER TABLE CONTROL_HORAS_INCAP
		ADD CONSTRAINT FKINCNOM 
			FOREIGN KEY (NOMINA)
				REFERENCES NOMINA
go

		
 
	ALTER TABLE DETALLE_PREASIENTO
		ADD CONSTRAINT FKDETPREASIENTO
			FOREIGN KEY (ASIENTO)
				REFERENCES PREASIENTO(ASIENTO)
			ON DELETE CASCADE
go			
 
 ALTER TABLE EMP_CONC_LIQUIDAC
        ADD CONSTRAINT COLIEMCL
               FOREIGN KEY (CONCEPTO, MONEDA, FECHA_LIQUIDAC)
                              REFERENCES CONCEPTO_LIQUIDAC
go
 
 
 ALTER TABLE EMP_CONC_LIQUIDAC
        ADD CONSTRAINT EMCOLIUS
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE EMP_CONC_LIQUIDAC
        ADD CONSTRAINT EMCLIEMP
               FOREIGN KEY (EMPLEADO)
                              REFERENCES EMPLEADO
go
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT EMPNOMI
               FOREIGN KEY (NOMINA)
                              REFERENCES NOMINA
go
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT PLAZAEMP
               FOREIGN KEY (PUESTO, PLAZA)
                              REFERENCES PLAZA
go
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT HOREMPL
               FOREIGN KEY (HORARIO)
                              REFERENCES HORARIO
go
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT EMPENTFI
               FOREIGN KEY (ENTIDAD_FINANCIERA)
                              REFERENCES ENTIDAD_FINANCIERA
go
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT EMPUBICA
               FOREIGN KEY (UBICACION)
                              REFERENCES UBICACION
go
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT EMPCCOST
               FOREIGN KEY (CENTRO_COSTO)
                              REFERENCES CENTRO_COSTO
go
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT PAISEMP
               FOREIGN KEY (PAIS)
                              REFERENCES PAIS
go
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT DEPAREMP
               FOREIGN KEY (DEPARTAMENTO)
                              REFERENCES DEPARTAMENTO
go
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT ESTADEMP
               FOREIGN KEY (ESTADO_EMPLEADO)
                              REFERENCES ESTADO_EMPLEADO
go
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT EMPDETDIRHAB
               FOREIGN KEY (DETALLE_DIR_HAB)
                              REFERENCES DETALLE_DIRECCION
go
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT EMPDETDIRPOS
               FOREIGN KEY (DETALLE_DIR_POSTAL)
                              REFERENCES DETALLE_DIRECCION
go
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT EMPLENIT
               FOREIGN KEY (NIT)
                              REFERENCES NIT
go
 

ALTER TABLE EMPLEADO
         ADD CONSTRAINT EMCLASEG
         FOREIGN KEY  ( CLASE_SEGURO )
         REFERENCES CLASE_SEGURO ( CLASE_SEGURO )
go


ALTER TABLE EMPLEADO
        ADD CONSTRAINT EMPLEADOUSRC
		FOREIGN KEY ( USUARIO_CREACION )
			REFERENCES ERPADMIN.USUARIO
go

ALTER TABLE EMPLEADO
        ADD CONSTRAINT EMPLEADOUSRM
		FOREIGN KEY ( USUARIO_ULT_MOD )
			REFERENCES ERPADMIN.USUARIO
go


ALTER TABLE EMPLEADO
         ADD CONSTRAINT FKEMPTIPOCUENTA
         	FOREIGN KEY  ( TIPO_CUENTA_ENTIDAD )
         		REFERENCES TIPO_CUENTA ( TIPO_CUENTA )
go



ALTER TABLE EMPLEADO 
	ADD CONSTRAINT FKEMPDIRECPAIS FOREIGN KEY ( PAIS_DIREC ) 
			REFERENCES PAIS ( PAIS )
go


ALTER TABLE EMPLEADO_AUDITORIA
        ADD CONSTRAINT EMAUDUS
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go

ALTER TABLE EMPLEADO_CENTRO
         ADD CONSTRAINT EMCTOEMP
         FOREIGN KEY  ( EMPLEADO )
         REFERENCES EMPLEADO ( EMPLEADO )
go

ALTER TABLE EMPLEADO_CENTRO
         ADD CONSTRAINT EMPCTOCTO
         FOREIGN KEY  ( CENTRO_COSTO )
         REFERENCES CENTRO_COSTO ( CENTRO_COSTO )
go
 

 ALTER TABLE EMPLEADO_COMPROBANTE ADD 
	CONSTRAINT FK_EMPLEADO_COMPROBANTE
		FOREIGN KEY (EMPLEADO) 
			REFERENCES EMPLEADO (EMPLEADO)
go


ALTER TABLE EMPLEADO_COMPROBANTE ADD 
	CONSTRAINT FK_EMPL_COMP_USUARIO 
		FOREIGN KEY ( USUARIO ) 
			REFERENCES ERPADMIN.USUARIO ( USUARIO )
			
go


 ALTER TABLE EMPLEADO_CONC_NOMI
        ADD CONSTRAINT ECNNOHIS
               FOREIGN KEY (NOMINA, NUMERO_NOMINA)
                              REFERENCES NOMINA_HISTORICO
go
 
 
 ALTER TABLE EMPLEADO_CONC_NOMI
        ADD CONSTRAINT ECNCTRCO
               FOREIGN KEY (CENTRO_COSTO, CONCEPTO)
                              REFERENCES CENTRO_CONCEPTO
go
 
 
 ALTER TABLE EMPLEADO_CONC_NOMI
        ADD CONSTRAINT ECNNOCO
               FOREIGN KEY (NOMINA, CONCEPTO)
                              REFERENCES NOMINA_CONCEPTO
go
 
 
 ALTER TABLE EMPLEADO_CONC_NOMI
        ADD CONSTRAINT EMCONOUS
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE EMPLEADO_CONC_NOMI
        ADD CONSTRAINT ECNEMP
               FOREIGN KEY (EMPLEADO)
                              REFERENCES EMPLEADO
go
 

 
 ALTER TABLE EMPLEADO_CONCEPTO
        ADD CONSTRAINT EMCONEMP
               FOREIGN KEY (EMPLEADO)
                              REFERENCES EMPLEADO
go
 
 
 ALTER TABLE EMPLEADO_CONCEPTO
        ADD CONSTRAINT EMCONCON
               FOREIGN KEY (CONCEPTO)
                              REFERENCES CONCEPTO
go
 

ALTER TABLE EMPLEADO_JERARQUIA
         ADD CONSTRAINT EMPJEREM
         	FOREIGN KEY  ( SUPERIOR )
         		REFERENCES EMPLEADO ( EMPLEADO )
go


ALTER TABLE EMPLEADO_JERARQUIA
         ADD CONSTRAINT EMPJEEMP
         	FOREIGN KEY  ( SUBORDINADO )
         		REFERENCES EMPLEADO ( EMPLEADO )
go

 
 ALTER TABLE EMPLEADO_NOMI_NETO
        ADD CONSTRAINT ENNCTABA
               FOREIGN KEY (CUENTA_BANCO_DOC)
                              REFERENCES CUENTA_BANCARIA
go
 
 
 ALTER TABLE EMPLEADO_NOMI_NETO
        ADD CONSTRAINT ENNEMP
               FOREIGN KEY (EMPLEADO)
                              REFERENCES EMPLEADO
go
 
 
 ALTER TABLE EMPLEADO_NOMI_NETO
        ADD CONSTRAINT ENNNOHIS
               FOREIGN KEY (NOMINA, NUMERO_NOMINA)
                              REFERENCES NOMINA_HISTORICO
go
 
 
 ALTER TABLE EMPLEADO_NOTAS
        ADD CONSTRAINT EMPEMPNO
               FOREIGN KEY (EMPLEADO)
                              REFERENCES EMPLEADO
go
 
 
ALTER TABLE FILTRO_EMPLEADO_REPORTES
	ADD CONSTRAINT FK_EMPL_REP_EMPLEADO
		FOREIGN KEY ( EMPLEADO ) 
			REFERENCES EMPLEADO ( EMPLEADO )
go
 
 ALTER TABLE GLOBALES_CN
        ADD CONSTRAINT GLCNPAQ
               FOREIGN KEY (PAQUETE)
                              REFERENCES PAQUETE
go
 
 
 ALTER TABLE GLOBALES_CN
        ADD CONSTRAINT GLCNTASN
               FOREIGN KEY (TIPO_ASIENTO)
                              REFERENCES TIPO_ASIENTO
go

ALTER TABLE GRUPO_CONCEPTO_DET
         ADD CONSTRAINT GRCODEGRCO
         	FOREIGN KEY  ( GRUPO_CONCEPTO )
         		REFERENCES GRUPO_CONCEPTO ( GRUPO_CONCEPTO )
	 			ON DELETE CASCADE
go	 			


ALTER TABLE GRUPO_CONCEPTO_DET
         ADD CONSTRAINT GRCODECO
         	FOREIGN KEY  ( CONCEPTO )
         		REFERENCES CONCEPTO ( CONCEPTO )
go         		
 
ALTER TABLE HORA_LABORADA
	ADD CONSTRAINT HORAEMP
        	FOREIGN KEY  ( EMPLEADO )
         		REFERENCES EMPLEADO ( EMPLEADO )
go         		

ALTER TABLE HORA_LABORADA
	ADD CONSTRAINT HORACONC
        	FOREIGN KEY  ( CONCEPTO )
         		REFERENCES CONCEPTO ( CONCEPTO )
go         		

ALTER TABLE HORA_LABORADA
	ADD CONSTRAINT HORACCOS
        	FOREIGN KEY  ( CENTRO_COSTO )
         		REFERENCES CENTRO_COSTO ( CENTRO_COSTO )
go         		

ALTER TABLE HORA_LABORADA
	ADD CONSTRAINT HORAUS
        	FOREIGN KEY  ( USUARIO_CARGA )
         		REFERENCES ERPADMIN.USUARIO ( USUARIO )
go         		

ALTER TABLE HORA_LABORADA
	ADD CONSTRAINT HORANOHI
        	FOREIGN KEY  ( NOMINA, NUMERO_NOMINA )
         		REFERENCES NOMINA_HISTORICO ( NOMINA, NUMERO_NOMINA )
go    
 

ALTER TABLE HORA_LABORADA 
            ADD CONSTRAINT HORALABFASEPY
                  FOREIGN KEY  ( PROYECTO, FASE )
                     REFERENCES FASE_PY ( PROYECTO , FASE)
go                     
 
 
 ALTER TABLE HORARIO_CONCEPTO
        ADD CONSTRAINT CONHORCO
               FOREIGN KEY (CONCEPTO)
                              REFERENCES CONCEPTO
go
 
 
 ALTER TABLE HORARIO_CONCEPTO
        ADD CONSTRAINT HORHORCO
               FOREIGN KEY (HORARIO)
                              REFERENCES HORARIO
go

ALTER TABLE LIQUIDACION_PAGO 
	ADD CONSTRAINT LIQMONEDAFK
		FOREIGN KEY (MONEDA)
			REFERENCES MONEDA(MONEDA)
go			

ALTER TABLE LIQUIDACION_PAGO 
	ADD CONSTRAINT LIQSUBTIPODOCFK
		FOREIGN KEY (SUBTIPO, TIPO)
			REFERENCES SUBTIPO_DOC_CP
go

ALTER TABLE LIQUIDACION_PAGO_DET 
	ADD CONSTRAINT LIQLIQDETFK
		FOREIGN KEY (LIQUIDACION)
			REFERENCES LIQUIDACION_PAGO(LIQUIDACION)
				ON DELETE CASCADE
go				

ALTER TABLE LIQUIDACION_PAGO_DET
	ADD CONSTRAINT LIQPAGODETPROVFK
		FOREIGN KEY (PROVEEDOR)
			REFERENCES PROVEEDOR(PROVEEDOR)
go			
 
 
 ALTER TABLE MARCA_RELOJ
        ADD CONSTRAINT USRMARCARELOJ
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE MARCA_RELOJ
        ADD CONSTRAINT EMPMARCA
               FOREIGN KEY (EMPLEADO)
                              REFERENCES EMPLEADO
go
 
 
 ALTER TABLE MARCA_RELOJ
        ADD CONSTRAINT MARCAHOR
               FOREIGN KEY (HORARIO)
                              REFERENCES HORARIO
go
 
 
 ALTER TABLE NOMINA
        ADD CONSTRAINT NOMICTRC
               FOREIGN KEY (CTR_NOMINA, CTA_NOMINA)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE NOMINA
        ADD CONSTRAINT NOMIMONE
               FOREIGN KEY (MONEDA)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE NOMINA
        ADD CONSTRAINT NOMICTAB
               FOREIGN KEY (CUENTA_BANCO)
                              REFERENCES CUENTA_BANCARIA
go
 
 
 ALTER TABLE NOMINA
         ADD CONSTRAINT CONCTIPOCAMFK
                FOREIGN KEY (CONCEPTO_TIPO_CAMBIO)
   			REFERENCES CONCEPTO
go

ALTER TABLE NOMINA
        ADD CONSTRAINT CONCDIASLABFK
               FOREIGN KEY (CONCEPTO_DIAS_LABOR)
   			REFERENCES CONCEPTO
go   			
 
 
ALTER TABLE NOMINA
	ADD CONSTRAINT NOMINAPRESUPCR
              	FOREIGN KEY (PRESUPUESTO_CR)
			REFERENCES PRESUPUESTO_CR (PRESUPUESTO)
go

ALTER TABLE NOMINA
	ADD CONSTRAINT NOMINAPAQUETECR
		FOREIGN KEY (PAQUETE_CR)
			REFERENCES PAQUETE_CR (PAQUETE)
go 
 
 
 
 ALTER TABLE NOMINA_CONCEPTO
        ADD CONSTRAINT NOCOCONC
               FOREIGN KEY (CONCEPTO)
                              REFERENCES CONCEPTO
go
 
 
 ALTER TABLE NOMINA_CONCEPTO
        ADD CONSTRAINT NOCONOMI
               FOREIGN KEY (NOMINA)
                              REFERENCES NOMINA
go
 
ALTER TABLE NOMINA_BANCO
	ADD CONSTRAINT NOMBANNOM
		FOREIGN KEY (NOMINA)
			REFERENCES NOMINA(NOMINA)
				ON DELETE CASCADE 
go

ALTER TABLE NOMINA_BANCO
	ADD CONSTRAINT NOMBANCTA
		FOREIGN KEY (CUENTA_BANCO)
			REFERENCES CUENTA_BANCARIA(CUENTA_BANCO)
				ON DELETE CASCADE 
go
 
 
 
 ALTER TABLE NOMINA_HISTORICO
        ADD CONSTRAINT NOHISUSR
               FOREIGN KEY (APROBADA_POR)
                              REFERENCES ERPADMIN.USUARIO
go

ALTER TABLE NOMINA_HISTORICO 
	ADD CONSTRAINT NOMHISTUSAPL 
        	FOREIGN KEY  ( USUARIO_APLICACION )
         		REFERENCES ERPADMIN.USUARIO (USUARIO )
go
 
 
ALTER TABLE NOMINA_HISTORICO
        ADD CONSTRAINT NOHINOMI
               FOREIGN KEY (NOMINA)
                              REFERENCES NOMINA
go
 
 
 ALTER TABLE NOMINA_USUARIO
        ADD CONSTRAINT NOUSUSUA
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE NOMINA_USUARIO
        ADD CONSTRAINT NOUSNOMI
               FOREIGN KEY (NOMINA)
                              REFERENCES NOMINA
go

ALTER TABLE $$COMPANIA$$.PILA_HISTORICO
	ADD CONSTRAINT PILANOM 
		FOREIGN KEY (NOMINA,NUMERO_NOMINA)
			REFERENCES $$COMPANIA$$.NOMINA_HISTORICO (NOMINA,NUMERO_NOMINA)
go
	
ALTER TABLE $$COMPANIA$$.PILA_HISTORICO_DET
	ADD CONSTRAINT PILADETNOM 
		FOREIGN KEY (NOMINA,NUMERO_NOMINA)
			REFERENCES $$COMPANIA$$.NOMINA_HISTORICO (NOMINA,NUMERO_NOMINA)
go

ALTER TABLE $$COMPANIA$$.PILA_HISTORICO_DET
	ADD CONSTRAINT PILADETEMP
		FOREIGN KEY (EMPLEADO)
			REFERENCES $$COMPANIA$$.EMPLEADO (EMPLEADO)
go

 
 ALTER TABLE PLAZA
        ADD CONSTRAINT PLAZUSUA
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE PLAZA
        ADD CONSTRAINT PLAZDEPT
               FOREIGN KEY (DEPARTAMENTO)
                              REFERENCES DEPARTAMENTO
go
 
 
 ALTER TABLE PLAZA
        ADD CONSTRAINT PLAZPUES
               FOREIGN KEY (PUESTO)
                              REFERENCES PUESTO
go


ALTER TABLE PUESTO_EXTERNO
         ADD CONSTRAINT PTEXCAPT
         FOREIGN KEY  ( CAT_PUESTO_EXTERNO )
         REFERENCES CAT_PUESTO_EXTERNO ( CAT_PUESTO_EXTERNO )
go         
 

ALTER TABLE PTO_EXTERNO_PUESTO
         ADD CONSTRAINT PTEXPUES
         FOREIGN KEY  ( PUESTO )
         REFERENCES PUESTO ( PUESTO )
go         

ALTER TABLE PTO_EXTERNO_PUESTO
         ADD CONSTRAINT PTEXPTEXT
         FOREIGN KEY  ( CAT_PUESTO_EXTERNO, PUESTO_EXTERNO )
         REFERENCES PUESTO_EXTERNO ( CAT_PUESTO_EXTERNO, PUESTO_EXTERNO )
go         
  
 
 ALTER TABLE PUESTO_FUNCIONES
        ADD CONSTRAINT PUESTFUN
               FOREIGN KEY (PUESTO)
                              REFERENCES PUESTO
go
 
 
 ALTER TABLE PUESTO_SALARIO
        ADD CONSTRAINT PUEPUSAL
               FOREIGN KEY (PUESTO)
                              REFERENCES PUESTO
go
 


      		