CREATE TABLE ADICIONAL
(
	ADICIONAL 		VARCHAR(40) 	NOT NULL,
	TIPO 			VARCHAR(1) 	NOT NULL,
	LONGITUD 		INT		NULL,
	DECIMALES 		INT		NULL,
	MODIFICABLE 		VARCHAR(1) 	NOT NULL
)
go


ALTER TABLE ADICIONAL 
	ADD CONSTRAINT PKADICIONAL PRIMARY KEY (ADICIONAL)
go



CREATE TABLE ADICIONALEMPLEADO
(
	ADICIONAL		VARCHAR(40)	NOT NULL,
	EMPLEADO		VARCHAR(20)	NOT NULL,
	VALOR			VARCHAR(60)	NOT NULL	
)
go


ALTER TABLE ADICIONALEMPLEADO 
	ADD CONSTRAINT PKADICIONALEMPLEADO PRIMARY KEY (ADICIONAL,EMPLEADO)
go


CREATE TABLE $$COMPANIA$$.ADICIONAL_NOMINA
(
	ADICIONAL 		VARCHAR(40) 	NOT NULL,
	TIPO 			VARCHAR(1) 		NOT NULL,
	LONGITUD 		INT				NULL,
	DECIMALES 		INT				NULL,
	MODIFICABLE 	VARCHAR(1) 	NOT NULL
)
go


ALTER TABLE $$COMPANIA$$.ADICIONAL_NOMINA
	ADD CONSTRAINT PKADICIONALNOM PRIMARY KEY (ADICIONAL)
go

CREATE TABLE $$COMPANIA$$.ADICIONALNOMINA
(
	ADICIONAL		VARCHAR(40)	NOT NULL,
	NOMINA			VARCHAR(4)	NOT NULL,
	VALOR			VARCHAR(60)	NOT NULL	
)
go

ALTER TABLE $$COMPANIA$$.ADICIONALNOMINA 
	ADD CONSTRAINT PKADICIONALNOMINA PRIMARY KEY (ADICIONAL,NOMINA)
go

CREATE TABLE ADICIONAL_VALOR
(
	ADICIONAL 		VARCHAR(40)	NOT NULL,
	VALOR			VARCHAR(60)	NOT NULL	
)
go

ALTER TABLE ADICIONAL_VALOR 
	ADD CONSTRAINT PKADICIONALVALOR PRIMARY KEY (ADICIONAL,VALOR)
go

CREATE TABLE $$COMPANIA$$.ADICIONAL_NOMINA_VALOR
(
	ADICIONAL 		VARCHAR(40)	NOT NULL,
	VALOR			VARCHAR(60)	NOT NULL	
)
go

ALTER TABLE $$COMPANIA$$.ADICIONAL_NOMINA_VALOR 
	ADD CONSTRAINT PKADICIONALNOMVALOR PRIMARY KEY (ADICIONAL,VALOR)
go


CREATE TABLE ADMINISTRADORA(
         ADMINISTRADORA		VARCHAR(10)	NOT NULL,
         DESCRIPCION		VARCHAR(40)	NOT NULL,
         TIPO_ADMINISTRADORA	VARCHAR(4)	NOT NULL,
         NIT			VARCHAR(20)	NOT NULL,
         DV_NIT_ADMINISTRA	VARCHAR(1)	NOT NULL,
         SUCURSAL		VARCHAR(10)	NOT NULL,
         DESC_SUCURSAL		VARCHAR(40)	NOT NULL,
         MUNICIPIO		VARCHAR(4)	NOT NULL,
         DEPARTAMENTO		VARCHAR(4)	NOT NULL,
         DIRECCION		VARCHAR(254)	NULL,
         AGRUPA_APORTE		VARCHAR(1)	NULL
)
go
         

ALTER TABLE ADMINISTRADORA
         ADD CONSTRAINT ADMINISTRADORAPK 
         	PRIMARY KEY NONCLUSTERED (ADMINISTRADORA )
go


CREATE TABLE ADMIN_CONCEPTO (
        ADMINISTRADORA      VARCHAR(10)	NOT NULL,
        CONCEPTO            VARCHAR(20) NOT NULL)
go


CREATE TABLE ADMIN_COTIZANTE(
         CONSECUTIVO		int 		NOT NULL,
         EMPLEADO		VARCHAR(20)	NOT NULL,
         ADMINISTRADORA		VARCHAR(10)	NOT NULL,
         FECHA_INGRESO		DATETIME	NOT NULL,
         FECHA_SALIDA		DATETIME	NULL,
         NUMERO_ACCION		INT		NULL
)
go
         
ALTER TABLE ADMIN_COTIZANTE
         ADD CONSTRAINT ADMIN_COTIZANTEPK 
         	PRIMARY KEY NONCLUSTERED (CONSECUTIVO )
go         	

CREATE TABLE AUDIT_AJUSTES_NOMI
(
  CONSECUTIVO INT IDENTITY(1,1) NOT NULL,
  NOMINA VARCHAR(4) NOT NULL,
  NUMERO_NOMINA INT	NOT NULL,
  EMPLEADO VARCHAR(20) NOT NULL,
  NETO_ANTERIOR DECIMAL(28,8),
  RAZON_DEFAULT VARCHAR(4),
  RAZON_USUARIO VARCHAR(500),
  USUARIO_MODIF VARCHAR (25) NOT NULL,
  USUARIO_APLICA VARCHAR (25) NOT NULL,
  ASIENTO VARCHAR(10) NULL
)
go

CREATE TABLE $$COMPANIA$$.AJUSTE_ACC_SALDO
(
 CONSECUTIVO INT 	NOT NULL,
 NUMERO_ACCION INT NOT NULL,
 NOMINA VARCHAR(4),
 NUMERO_NOMINA INT,
 DIAS_APLICADOS DECIMAL(28,8)
)
go


CREATE TABLE CAT_PUESTO_EXTERNO (
         CAT_PUESTO_EXTERNO         VARCHAR(12)         NOT NULL,
         DESCRIPCION         	    VARCHAR(254)         NOT NULL )
go

ALTER TABLE CAT_PUESTO_EXTERNO
         ADD CONSTRAINT CATPUESTOEXTERNOPK PRIMARY KEY NONCLUSTERED
         (CAT_PUESTO_EXTERNO )
go
 
 CREATE TABLE CENTRO_CONCEPTO (
        CENTRO_COSTO         VARCHAR(25) NOT NULL,
        CONCEPTO             VARCHAR(20) NOT NULL,
        ACTIVO               VARCHAR(1) NOT NULL,
        CUENTA_CONTABLE      VARCHAR(25) NULL,
        CUENTA_CONTRA        VARCHAR(25) NULL
 )
go
 
 
 ALTER TABLE CENTRO_CONCEPTO
        ADD CONSTRAINT CENTROCONCEPTOPK PRIMARY KEY NONCLUSTERED (
               CENTRO_COSTO, CONCEPTO)
go
 
 
 
CREATE TABLE CENTRO_TRABAJO (
        CENTRO_TRABAJO	     VARCHAR(12) 	NOT NULL,
        DESCRIPCION          VARCHAR(40)	NOT NULL,
        PORCENTAJE           DECIMAL(28,8)    	NOT NULL        
 )
 go
 


ALTER TABLE CENTRO_TRABAJO
        ADD CONSTRAINT XPKCENTRO_TRABAJO PRIMARY KEY (CENTRO_TRABAJO)
go        
        
        

CREATE TABLE CLASE_SEGURO (
         CLASE_SEGURO         VARCHAR(4)         NOT NULL,
         DESCRIPCION         VARCHAR(40)         NOT NULL )
go

ALTER TABLE CLASE_SEGURO
         ADD CONSTRAINT CLASE_SEGUROPK PRIMARY KEY NONCLUSTERED
         (CLASE_SEGURO )
go

CREATE TABLE $$COMPANIA$$.CODING_CARTA_RENTA
(
	COD_INGRESO varchar(4) 		not null,
	CONCEPTO 	varchar(4000) 	null,
	RUBRO 		varchar(40) 	null

)
go

ALTER TABLE $$COMPANIA$$.CODING_CARTA_RENTA ADD 
	CONSTRAINT PK_CODING_CARTA_RENTA
		PRIMARY KEY (COD_INGRESO)
go

Create table $$COMPANIA$$.COD_INGRESO
(
	COD_INGRESO varchar(4) not null,
	DESCRIPCION varchar(200) not null,
	GRAVADO 	varchar(1) not null default 'N'
)

go

alter table $$COMPANIA$$.COD_INGRESO ADD 
	CONSTRAINT PK_COD_INGRESO
		PRIMARY KEY (COD_INGRESO)

go


CREATE TABLE COD_OBSERVA_ISSS
(
	CODIGO 		VARCHAR(2) 	NOT NULL,
	DESCRIPCION 	VARCHAR(250) 	NOT NULL,
	PRIORIDAD 	INT 		NOT NULL,
	ACCION_PERSONAL VARCHAR(4)  	NULL,
	CONCEPTO 	VARCHAR(20) 	NULL
)
go



CREATE TABLE CONCEPTO_PUESTO
(
	CONCEPTO		VARCHAR(20) 	NOT NULL,
	PUESTO 			VARCHAR(8) 	NOT NULL
)

go

		

ALTER TABLE CONCEPTO_PUESTO 
	ADD CONSTRAINT CONCEPTOPUESTOPK PRIMARY KEY NONCLUSTERED (CONCEPTO,PUESTO)
go

 
 CREATE TABLE CONC_FORM_CONCEPTO (
        CONCEPTO             VARCHAR(20) NOT NULL,
        SECUENCIA            smallint NOT NULL,
        CONCEPTO_USA         VARCHAR(20) NOT NULL
 )
go
 
 
 ALTER TABLE CONC_FORM_CONCEPTO
        ADD CONSTRAINT CONC_FORM_CONCEPK PRIMARY KEY NONCLUSTERED (
               CONCEPTO, SECUENCIA, CONCEPTO_USA)
go
 
 
 CREATE TABLE CONC_FORM_RUBRO (
        CONCEPTO             VARCHAR(20) NOT NULL,
        SECUENCIA            smallint NOT NULL,
        RUBRO                VARCHAR(17) NOT NULL
 )
go
 
 
 ALTER TABLE CONC_FORM_RUBRO
        ADD CONSTRAINT CONC_FORM_RUBROPK PRIMARY KEY NONCLUSTERED (
               CONCEPTO, SECUENCIA, RUBRO)
go
 
 
 CREATE TABLE CONCEPTO (
        CONCEPTO             		VARCHAR(20) 	NOT NULL,
        ALIAS                		VARCHAR(15) 	NOT NULL,
        TIPO_CONCEPTO        		VARCHAR(1) 	NOT NULL,
        DESCRIPCION          		VARCHAR(40) 	NOT NULL,
        UNIDADES             		VARCHAR(10) 	NULL,
        SALARIAL             		VARCHAR(1) 	NOT NULL,
        FIJO                 		VARCHAR(1) 	NOT NULL,
        LIQUIDABLE           		VARCHAR(1) 	NOT NULL,
        EXCLUYENTE           		VARCHAR(1) 	NOT NULL,
        VARIABLE_DECISION    		VARCHAR(15)	NULL,
        CANT_EDITABLE        		VARCHAR(1) 	NOT NULL,
        MONTO_EDITABLE       		VARCHAR(1) 	NOT NULL,
        USA_CANTIDAD         		VARCHAR(1) 	NOT NULL,
        USA_MONTO            		VARCHAR(1) 	NOT NULL,
        PERIODICIDAD         		VARCHAR(1) 	NOT NULL,
        DIAS_PERIODO         		smallint 	NOT NULL,
        MAX_NIVEL            		smallint 	NOT NULL,
        CARGA_POR_DLL        		VARCHAR(1) 	NOT NULL,
        CALCULO_POR_DLL      		VARCHAR(1) 	NOT NULL,
        FACTOR_REDONDEO      		DECIMAL(28,8) 	NOT NULL,
        FORMULA_DEFINIDA     		VARCHAR(1) 	NOT NULL,
        IMPRIMIR_COMP_PAGO   		VARCHAR(1) 	NOT NULL,
        IMPRIMIR_ACUMULADO   		VARCHAR(1) 	NOT NULL,
        IMPRIMIR_COND_PAGO   		VARCHAR(1) 	NOT NULL,
        ELIMINAR_CONC_CERO   		VARCHAR(1) 	NOT NULL,
        SDI_CALC_ACUMULADO   		VARCHAR(1) 	NOT NULL,
        SDI_CALC_FORMULA     		VARCHAR(1) 	NOT NULL,
        DISTRIBUYE_CENTROS   		VARCHAR(1) 	NOT NULL,
        PROVEEDOR 	     		VARCHAR(20)   	NULL,
        CARGA_HORAS          		VARCHAR(1)    	NOT NULL,
        INCLUIR_DOC_RH       		VARCHAR(1)    	NOT NULL,
        NOTAS 		     		TEXT          	NULL,
        CALCULO_SPD	    		VARCHAR(1)    	NOT NULL DEFAULT 'N',
        CODIGO_ANEXO	     		VARCHAR(20) 	NULL,
        PERIODO_INICIAL_EXCLUYENTE 	DATETIME 	NULL,
	PERIODO_FINAL_EXCLUYENTE 	DATETIME 	NULL,
	OMITIR_MONT_CANT_CERO 		VARCHAR(1) 	NOT NULL DEFAULT 'N',
	FUNCION_INTERFAZ 		VARCHAR(40) 	NULL,
	CONTABILIZACION			VARCHAR(1)    	NULL,
	NIT        			VARCHAR(20)	NULL
	
 )
go
 
 
 ALTER TABLE CONCEPTO
        ADD CONSTRAINT CONCEPTOPK PRIMARY KEY NONCLUSTERED (CONCEPTO)
go
 
 
 CREATE TABLE CONCEPTO_FORMULA (
        CONCEPTO             VARCHAR(20) NOT NULL,
        SECUENCIA            smallint NOT NULL,
        VALOR_INICIAL        DECIMAL(28,8) NOT NULL,
        VALOR_FINAL          DECIMAL(28,8) NOT NULL,
        CANTIDAD             DECIMAL(28,8) NOT NULL,
        MONTO                DECIMAL(28,8) NOT NULL,
        FORMULA              TEXT NOT NULL,
        NIVEL_FORMULA        smallint NOT NULL,
        USA_CANTIDAD         VARCHAR(1) NOT NULL,
        USA_MONTO            VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE CONCEPTO_FORMULA
        ADD CONSTRAINT CONCEPTOFORMULAPK PRIMARY KEY NONCLUSTERED (
               CONCEPTO, SECUENCIA)
go
 
 
 CREATE TABLE CONCEPTO_LIQUIDAC (
        CONCEPTO             VARCHAR(20) NOT NULL,
        MONEDA               VARCHAR(4) NOT NULL,
        FECHA_LIQUIDAC       DATETIME NOT NULL,
        USUARIO              VARCHAR(25) NOT NULL,
        DOCS_POR_GENERAR     VARCHAR(1) NOT NULL,
        NOTAS                TEXT NULL,
        CUENTA_BANCARIA      VARCHAR(20) NOT NULL,
        PDO_FINAL            DATETIME NOT NULL,
        NUMERO_LIQUIDAC      smallint NOT NULL,
        DOCS_POR_IMPRIMIR    VARCHAR(1) NOT NULL,
        FECHA_HORA           DATETIME NOT NULL,
        SUBTIPODOC_CHEQUE    smallint NULL,
        SUBTIPODOC_TEF       smallint NULL
 )
go
 
 
 ALTER TABLE CONCEPTO_LIQUIDAC
        ADD CONSTRAINT XPKCONCEPTO_LIQUID PRIMARY KEY (CONCEPTO, 
               MONEDA, FECHA_LIQUIDAC)
go
 
 
 CREATE TABLE CONCEPTO_USUARIO (
        CONCEPTO             VARCHAR(20) 	NOT NULL,
        NOMINA               VARCHAR(4) 	NOT NULL,
        USUARIO              VARCHAR(25) 	NOT NULL,
        PRIVILEGIO           VARCHAR(1)		NOT NULL
 )
go
 
 
 ALTER TABLE CONCEPTO_USUARIO
        ADD CONSTRAINT XPKCONCEPTO_USUARIO PRIMARY KEY (CONCEPTO, 
               NOMINA, USUARIO)
go



CREATE TABLE CONSTANTE_CALCULO (
        CONSTANTE       VARCHAR(12)  NOT NULL,
        DESCRIPCION     VARCHAR(40) NOT NULL 
)
go
 
 
ALTER TABLE CONSTANTE_CALCULO
        ADD CONSTRAINT PKCONSTANTECALCULO PRIMARY KEY (
               CONSTANTE )
go




CREATE TABLE CONSTANTE_CALC_VALOR (
        VARIABLE	VARCHAR(12) NOT NULL,
        CONSTANTE	VARCHAR(12) NOT NULL, 
        DESCRIPCION     VARCHAR(40) NOT NULL, 
        VALOR           DECIMAL(28,8) NOT NULL
)
go
        
  
ALTER TABLE CONSTANTE_CALC_VALOR
        ADD CONSTRAINT PKPCONSTANTECALCVALOR PRIMARY KEY (
               VARIABLE, CONSTANTE )
go     



CREATE TABLE COTIZANTE(
         EMPLEADO		VARCHAR(20)	NOT NULL,
         TIPO_COTIZANTE		VARCHAR(2)	NOT NULL,
         SUBTIPO_COTIZANTE	VARCHAR(2)	NOT NULL,
         COTIZA_PENSION		VARCHAR(1)	NOT NULL,
         RESIDE_EXTERIOR	VARCHAR(1)	NOT NULL,
         CENTRO_TRABAJO		VARCHAR(12)	NOT NULL,
         MUNICIPIO 			VARCHAR(12) NOT NULL,
         DEPARTAMENTO 		VARCHAR(12) NOT NULL,
         DEV_SAL_INTEGRAL       VARCHAR(1) 	NOT NULL DEFAULT ('N'),
         ACTIVIDAD_ALTO_RIESGO 	VARCHAR(1) 	NOT NULL DEFAULT('N'),
		 PAIS 					VARCHAR(4) NULL,
		 DIVISION_GEOGRAFICA 	VARCHAR(12) NULL,
		 TIPO_VINCULACION 		VARCHAR(2) NULL, 
		 CONDICION_ESPECIAL 	VARCHAR(2) NULL,
		 FECHA_EXTERIOR DATETIME NULL
)
go

ALTER TABLE COTIZANTE
         ADD CONSTRAINT COTIZANTEPK 
         	PRIMARY KEY NONCLUSTERED  (EMPLEADO )
go 


CREATE TABLE CONTROL_HORAS_INCAP(
		EMPLEADO VARCHAR(20) NOT NULL,
		CONSECUTIVO INT NOT NULL,
		NOMINA VARCHAR(4) NOT NULL,
		NUMERO_NOMINA SMALLINT NOT NULL,
		SALDO_INICIAL DECIMAL (28,8) NOT NULL,
		HORAS_VENCIDAS DECIMAL (28,8) NOT NULL,
		HORAS_CONSUMIDAS DECIMAL (28,8) NOT NULL,
		HORAS_CAUSADAS DECIMAL (28,8) NOT NULL,
		SALDO DECIMAL (28,8) NOT NULL,
		ACEPTADO VARCHAR(1) NOT NULL,
		ACCION int NULL
)
go


ALTER TABLE CONTROL_HORAS_INCAP
	ADD CONSTRAINT PKHRINCAP
		PRIMARY KEY (EMPLEADO,NOMINA,NUMERO_NOMINA)
go


CREATE TABLE DETALLE_PREASIENTO (
	ASIENTO           	VARCHAR(10) 	NOT NULL,
        CONSECUTIVO		int 		NOT NULL,
        NIT                  	VARCHAR(20) 	NULL,
        CENTRO_COSTO         	VARCHAR(25)	NOT NULL,
        CUENTA_CONTABLE      	VARCHAR(25) 	NOT NULL,
        FUENTE               	VARCHAR(40) 	NOT NULL,
        REFERENCIA           	VARCHAR(249) 	NOT NULL,
        DEBITO_LOCAL         	DECIMAL(28,8) 	NULL,
        DEBITO_DOLAR         	DECIMAL(28,8) 	NULL,
        CREDITO_LOCAL        	DECIMAL(28,8) 	NULL,
        CREDITO_DOLAR        	DECIMAL(28,8) 	NULL,
        DEBITO_UNIDADES      	DECIMAL(28,8) 	NULL,
        CREDITO_UNIDADES     	DECIMAL(28,8) 	NULL,
        TIPO_CAMBIO 	     	DECIMAL(28,8) 	NULL,
        BASE_LOCAL           	DECIMAL(28,8) 	NULL,
	BASE_DOLAR           	DECIMAL(28,8) 	NULL,
	PROYECTO             	VARCHAR(25) 	NULL,
	FASE 		     	VARCHAR(25) 	NULL,
	PROCESO			VARCHAR(10) 	NOT NULL
 )
go
 
ALTER TABLE DETALLE_PREASIENTO
	ADD CONSTRAINT PREASIENTOPK PRIMARY KEY NONCLUSTERED (PROCESO, ASIENTO, CONSECUTIVO)
go

 
 CREATE TABLE EMP_CONC_LIQUIDAC (
        CONCEPTO             VARCHAR(20) 	NOT NULL,
        MONEDA               VARCHAR(4) 	NOT NULL,
        EMPLEADO             VARCHAR(20) 	NOT NULL,
        FECHA_LIQUIDAC       DATETIME 		NOT NULL,
        NUMERO_DOCUMENTO     decimal(28,0)	NULL,
        ASIENTO_DOCUMENTO    VARCHAR(10) 	NULL,
        DOCUMENTO_IMPRESO    VARCHAR(1) 	NULL,
        DOCUMENTO_SELECCIO   VARCHAR(1) 	NULL,
        DOCUMENTO_GENERADO   VARCHAR(1) 	NOT NULL,
        MONTO_CALCULADO      DECIMAL(28,8) 	NOT NULL,
        MONTO_A_PAGAR        DECIMAL(28,8) 	NOT NULL,
        NOTAS                TEXT 		NULL,
        USUARIO              VARCHAR(25) 	NULL,
        FECHA_HORA           DATETIME 		NOT NULL,
        FORMA_PAGO           VARCHAR(1) 	NULL
 )
go
 
 
 ALTER TABLE EMP_CONC_LIQUIDAC
        ADD CONSTRAINT XPKEMP_CONC_LIQUID PRIMARY KEY (CONCEPTO, 
               MONEDA, EMPLEADO, FECHA_LIQUIDAC)
go
 
 
 CREATE TABLE EMPLEADO (
        EMPLEADO             	VARCHAR(20) NOT NULL,
        DETALLE_DIR_HAB      	int 		NULL,
        NOMBRE               	VARCHAR(70) NOT NULL,
        SEXO                 	VARCHAR(1) 	NOT NULL,
        TIPO_SANGRE          	VARCHAR(4) 	NULL,
        ESTADO_EMPLEADO      	VARCHAR(4) 	NOT NULL,
        ACTIVO               	VARCHAR(1) 	NOT NULL,
        IDENTIFICACION       	VARCHAR(20) NULL,
        PASAPORTE            	VARCHAR(20) NULL,
        FECHA_INGRESO        	DATETIME 	NOT NULL,
        FECHA_SALIDA         	DATETIME 	NULL,
        DEPARTAMENTO         	VARCHAR(10) NOT NULL,
        PUESTO               	VARCHAR(8) 	NOT NULL,
        PLAZA                	VARCHAR(8) 	NOT NULL,
        NOMINA               	VARCHAR(4) 	NOT NULL,
        CENTRO_COSTO         	VARCHAR(25) NOT NULL,
        FECHA_NACIMIENTO     	DATETIME 	NOT NULL,
        UBICACION            	VARCHAR(8) 	NOT NULL,
        PAIS                 	VARCHAR(4) 	NOT NULL,
        ESTADO_CIVIL         	VARCHAR(1) 	NOT NULL,
        DEPENDIENTES         	smallint 	NULL,
        ASEGURADO            	VARCHAR(20) NULL,
        CLASE_SEGURO         	VARCHAR(4) 	NULL,
        PERMISO_CONDUCIR     	VARCHAR(20) NULL,
        PERMISO_SALUD        	VARCHAR(20) NULL,
        NIT                  	VARCHAR(20) NULL,
        VACS_PENDIENTES      	DECIMAL(28,8) 	NOT NULL,
        VACS_ULT_CALCULO     	DATETIME 	  	NOT NULL,
        FECHA_PROX_EVAL      	DATETIME 		NULL,
        SALARIO_REFERENCIA   	DECIMAL(28,8) 	NOT NULL,
        FORMA_PAGO           	VARCHAR(1) 		NOT NULL,
        CUENTA_ENTIDAD       	VARCHAR(50) 	NULL,
        ENTIDAD_FINANCIERA   	VARCHAR(8) 	NULL,
        HORARIO              	VARCHAR(4) 	NOT NULL,
        DIRECCION_HAB        	TEXT 		NULL,
        DIRECCION_POSTAL     	TEXT 		NULL,
        TELEFONO1            	VARCHAR(20) NULL,
        NOTAS_TEL1           	VARCHAR(40) NULL,
        TELEFONO2            	VARCHAR(20) NULL,
        NOTAS_TEL2           	VARCHAR(40) NULL,
        TELEFONO3            	VARCHAR(20) NULL,
        NOTAS_TEL3           	VARCHAR(40) NULL,
        FOTOGRAFIA           	IMAGE 		NULL,
        RUBRO1               	VARCHAR(40) NULL,
        RUBRO2               	VARCHAR(40) NULL,
        RUBRO3               	VARCHAR(40) NULL,
        RUBRO4               	VARCHAR(40) NULL,
        RUBRO5               	VARCHAR(40) NULL,
        RUBRO6               	VARCHAR(40) NULL,
        RUBRO7               	VARCHAR(40) NULL,
        RUBRO8               	VARCHAR(40) NULL,
        RUBRO9               	VARCHAR(40) NULL,
        RUBRO10              	VARCHAR(40) NULL,
        RUBRO11              	VARCHAR(40) NULL,
        RUBRO12              	VARCHAR(40) NULL,
        RUBRO13              	VARCHAR(40) NULL,
        RUBRO14              	VARCHAR(40) NULL,
        RUBRO15              	VARCHAR(40) NULL,
        FECHA_NO_PAGO        	DATETIME 	NOT NULL,
        TIPO_SALARIO_AUMEN   	VARCHAR(1) 	NOT NULL,
        FECHA_ANTIG_EMP      	DATETIME 	NULL,
        FECHA_ANTIG_GOB      	DATETIME 	NULL,
        SALARIO_DIARIO_INT   	DECIMAL(28,8) 	NULL,
        PRIMER_APELLIDO      	VARCHAR(20) 	NULL,
        SEGUNDO_APELLIDO     	VARCHAR(20) 	NULL,
        NOMBRE_PILA          	VARCHAR(30) 	NULL,
        E_MAIL               	VARCHAR(249) 	NULL,
        DETALLE_DIR_POSTAL   	int 			NULL,
        VACS_ADICIONALES     	DECIMAL(28,8) 	NOT NULL,
        RUBRO16              	VARCHAR(40) 	NULL,
		RUBRO17              	VARCHAR(40) 	NULL,
		RUBRO18              	VARCHAR(40) 	NULL,
		RUBRO19              	VARCHAR(40) 	NULL,
		RUBRO20              	VARCHAR(40) 	NULL,
		RUBRO21              	VARCHAR(40) 	NULL,
		RUBRO22              	VARCHAR(40) 	NULL,
		RUBRO23              	VARCHAR(40) 	NULL,
		RUBRO24              	VARCHAR(40) 	NULL,
		RUBRO25              	VARCHAR(40) 	NULL,
		SALARIOPD_LOCAL	     	DECIMAL(28,8) 	NULL,
		SALARIOPD_DOLAR	     	DECIMAL(28,8) 	NULL,
		SALARIOPD_NOMINA     	DECIMAL(28,8) 	NULL,
		DIAS_DISP_INCAP 		DECIMAL(28,8) 	NULL,
		USUARIO_CREACION		VARCHAR(25)		NULL,
		FECHA_HORA_CREACION		DATETIME		NULL,
		USUARIO_ULT_MOD			VARCHAR(25)		NULL,
		FCH_HORA_ULT_MOD		DATETIME		NULL,
		TIPO_CUENTA_ENTIDAD 	VARCHAR(12) 	NULL,
		CTA_ELECTRONICA 		VARCHAR(50) 	NULL,
		DIVISION_GEOGRAFICA1 	VARCHAR(12) 	NULL,
		DIVISION_GEOGRAFICA2 	VARCHAR(12) 	NULL,
		PAIS_DIREC				VARCHAR(4)  	NULL,
		TIPO_SALARIO 			VARCHAR(1) 		NULL,
		BENEFICIO_COLECTIVO 	VARCHAR(2) 		NULL,
		TIPO_MEDIDAS_CERTIFICADAS int NULL,
		TIPO_NIVEL_EDUCATIVO int NULL
 )	
go	
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT EMPLEADOPK PRIMARY KEY NONCLUSTERED (EMPLEADO)
go
 
CREATE TABLE EMPLEADO_AUDITORIA (
        ATRIBUTO             VARCHAR(40) 	NOT NULL,
        USUARIO              VARCHAR(25) 	NOT NULL,
        TIPO_ACCION          VARCHAR(4) 	NOT NULL,
        FECHA                DATETIME 		NOT NULL
 )
go
 
 
ALTER TABLE EMPLEADO_AUDITORIA
        ADD CONSTRAINT EMPLEADOAUDITORPK PRIMARY KEY (ATRIBUTO)
go

CREATE TABLE $$COMPANIA$$.CALCULO_AJUSTES_NOMI
(
 CONSECUTIVO INT IDENTITY(1,1) 	NOT NULL,
 EMPLEADO VARCHAR(20) NOT NULL,
 NOMINA VARCHAR(4) NOT NULL,
 NUMERO_NOMINA INT	NOT NULL,
 CONCEPTO VARCHAR(20) NOT NULL,
 CENTRO_COSTO VARCHAR(25) NOT NULL,
 FORMA_APLICACION VARCHAR(1) NULL,
 CANTIDAD DECIMAL(28,8) NOT NULL,
 MONTO DECIMAL(28,8) NOT NULL,
 TOTAL DECIMAL(28,8) NOT NULL,
 FASE VARCHAR(25) NULL,
 PROYECTO VARCHAR(25) NULL,
 TIPO_REGISTRO VARCHAR(1) NOT NULL DEFAULT 'O'
)
go


 
CREATE TABLE EMPLEADO_CENTRO (
         EMPLEADO    	VARCHAR(20)     NOT NULL,
         CENTRO_COSTO	VARCHAR(25)     NOT NULL,
         PORCENTAJE    	DECIMAL(28,8)	NOT NULL )
go


ALTER TABLE EMPLEADO_CENTRO
         ADD CONSTRAINT XPKEMPLEADO_CENTRO PRIMARY KEY NONCLUSTERED
         (EMPLEADO, CENTRO_COSTO )
go 

CREATE TABLE EMPLEADO_COMPROBANTE(

EMPLEADO VARCHAR(20) NOT NULL,
	NOMINA VARCHAR(4) NOT NULL, 				
	NUMERO_NOMINA SMALLINT NOT NULL, 
	USUARIO VARCHAR(25) NOT NULL )

go

ALTER TABLE EMPLEADO_COMPROBANTE ADD 
	CONSTRAINT PK_EMPLEADO_COMPROBANTE
		PRIMARY KEY (EMPLEADO, NOMINA, NUMERO_NOMINA, USUARIO)	
		
go
 
 CREATE TABLE EMPLEADO_CONC_NOMI (
 	CONSECUTIVO 	     INT       IDENTITY NOT NULL,
        EMPLEADO             VARCHAR(20) 	NOT NULL,
        CONCEPTO             VARCHAR(20) 	NOT NULL,
        NOMINA               VARCHAR(4) 	NOT NULL,
        NUMERO_NOMINA        smallint 		NOT NULL,
        CENTRO_COSTO         VARCHAR(25) 	NOT NULL,
        FORMA_APLICACION     VARCHAR(1) 	NOT NULL,
        CANTIDAD             DECIMAL(28,8) 	NOT NULL,
        MONTO                DECIMAL(28,8) 	NOT NULL,
        TOTAL                DECIMAL(28,8) 	NOT NULL,
        NUMERO_LIQUIDAC      smallint 		NULL,
        USUARIO              VARCHAR(25) 	NULL,
        FECHA_MODIFICACION   DATETIME 		NULL,
        FASE 		     VARCHAR(25) 	NULL,
		PROYECTO 	     VARCHAR(25) 	NULL,
		TIPO_REGISTRO VARCHAR(1) NOT NULL DEFAULT 'O'
) 	
go
 
 
 ALTER TABLE EMPLEADO_CONC_NOMI
        ADD CONSTRAINT EMPLEADOCONCNOMIPK PRIMARY KEY NONCLUSTERED (CONSECUTIVO)
go


CREATE TABLE EMPLEADO_CONC_NOMI_CALC (
	CONSECUTIVO 	     INT		NOT NULL,
	EMPLEADO             VARCHAR(20) 	NOT NULL,
        CONCEPTO             VARCHAR(20) 	NOT NULL,
        NOMINA               VARCHAR(4) 	NOT NULL,
        NUMERO_NOMINA        SMALLINT 		NOT NULL,
        CENTRO_COSTO         VARCHAR(25) 	NOT NULL,
        TOTAL                DECIMAL(28,8) 	NOT NULL
)
go


ALTER TABLE EMPLEADO_CONC_NOMI_CALC 
	ADD CONSTRAINT EMPLEADOCONCNOMICALCPK 
 		PRIMARY KEY NONCLUSTERED (CONSECUTIVO,EMPLEADO, CONCEPTO, NOMINA, NUMERO_NOMINA, CENTRO_COSTO)
 go
 
 
 CREATE TABLE EMPLEADO_CONCEPTO (
        EMPLEADO             VARCHAR(20) 	NOT NULL,
        CONCEPTO             VARCHAR(20) 	NOT NULL,
        ACTIVO               VARCHAR(1) 	NOT NULL,
        FORMA_APLICACION     VARCHAR(1) 	NOT NULL,
        NUMERO_CUOTAS        smallint 		NOT NULL,
        CUOTAS_APLICADAS     smallint 		NOT NULL,
        SALDO_INICIAL        DECIMAL(28,8) 	NOT NULL,
        SALDO                DECIMAL(28,8) 	NOT NULL,
        ACUMULADO            DECIMAL(28,8) 	NOT NULL,
        FECHA_ULT_APLIC      DATETIME 		NOT NULL,
        FECHA_PROX_APLIC     DATETIME 		NOT NULL,
        FECHA_VENCE          DATETIME 		NOT NULL,
        CANTIDAD             DECIMAL(28,8) 	NOT NULL,
        MONTO                DECIMAL(28,8) 	NOT NULL,
        VERIFICADO           VARCHAR(1) 	NOT NULL,
        NOTAS                TEXT 		NULL,
        PERIODIC_LIQ_PROV    VARCHAR(1) 	NULL
 )
go
 
 
 ALTER TABLE EMPLEADO_CONCEPTO
        ADD CONSTRAINT EMPLEADOCONCEPTOPK PRIMARY KEY NONCLUSTERED (
               EMPLEADO, CONCEPTO)
go
 

CREATE TABLE EMPLEADO_JERARQUIA (
         SUPERIOR         VARCHAR(20)         NOT NULL,
         SUBORDINADO      VARCHAR(20)         NOT NULL )
go


ALTER TABLE EMPLEADO_JERARQUIA
         ADD CONSTRAINT EMPJERARQUIAPK PRIMARY KEY NONCLUSTERED
         	(SUPERIOR, SUBORDINADO )
go

 
 CREATE TABLE EMPLEADO_NOMI_NETO (
        EMPLEADO             	VARCHAR(20) 	NOT NULL,
        NOMINA               	VARCHAR(4) 	NOT NULL,
        NUMERO_NOMINA        	smallint 	NOT NULL,
        TOTAL_BENEFICIOS     	DECIMAL(28,8) 	NOT NULL,
        TOTAL_DEDUCCION      	DECIMAL(28,8) 	NOT NULL,
        TOTAL_ANTICIPOS      	DECIMAL(28,8) 	NOT NULL,
        TOTAL_APORTES        	DECIMAL(28,8) 	NOT NULL,
        NETO                 	DECIMAL(28,8) 	NOT NULL,
        DOCUMENTO_IMPRESO    	VARCHAR(1) 	NULL,
        NUMERO_DOCUMENTO     	decimal(28,0) 	NULL,
        DOCUMENTO_SELECCIO   	VARCHAR(1) 	NULL,
        CUENTA_BANCO_DOC     	VARCHAR(20) 	NULL,
        ASIENTO_DOCUMENTO    	VARCHAR(10) 	NULL,
        NOTAS                	TEXT 		NULL,
        CALCULADO            	VARCHAR(1) 	NOT NULL,
        FORMA_PAGO           	VARCHAR(1) 	NULL,
        DIAS_LABORADOS		SMALLINT	NULL,
		SALARIOPD_LOCAL		DECIMAL(28,8)	NULL,
		SALARIOPD_DOLAR		DECIMAL(28,8)	NULL,
		SALARIOPD_NOMINA	DECIMAL(28,8)	NULL,
		SALARIOPD_CALCULO	VARCHAR(1)	NULL,
		TIPO_CAMBIO			DECIMAL(28,8)	NULL,
		ESTADO_NOMINA		VARCHAR(1)	NULL,
		FECHA_CALCULO_SPD	DATETIME	NULL,
		LIQUIDACION 		INT 		NULL,
		FICHA_SIPE 			VARCHAR(10) NULL
 )
go
 
 
 ALTER TABLE EMPLEADO_NOMI_NETO
        ADD CONSTRAINT EMPLEADONOMINETOPK PRIMARY KEY NONCLUSTERED (
               EMPLEADO, NOMINA, NUMERO_NOMINA)
go



CREATE TABLE $$COMPANIA$$.EMPLEADO_NOMINA_CFDI
(
EMPLEADO 			VARCHAR(20) 	NOT NULL,
NOMINA 				VARCHAR(4) 	NOT NULL,
NUMERO_NOMINA 			SMALLINT 	NOT NULL,
ARCHIVO_XML 			VARCHAR (MAX) 	NULL,
ENVIADO 			VARCHAR(1) 	NULL,
ERROR 				VARCHAR(MAX) 	NULL,
UUID 				VARCHAR(50) 	NULL,
CADENA_ORIGINAL 		VARCHAR(MAX) 	NULL,
NUMERO_CERTIFICADO_CIA 		VARCHAR(20) 	NULL,
FECHA_TIMBRADO 			VARCHAR(20) 	NULL,
NUMERO_CERTIFICADO_SAT 		VARCHAR(20) 	NULL,
SELLO_SAT 			VARCHAR(MAX) 	NULL,
SELLO_CFD 			VARCHAR(MAX) 	NULL,
ARCHIVO_PDF 			VARBINARY(MAX) 	NULL,
RECIBO 				VARCHAR(255) 	NOT NULL,
REG_PATRONAL 			VARCHAR(255) 	NULL,
FALTAS_PERIODO 			DECIMAL(28,8) 	NULL,
DIAS_VAC 			DECIMAL(28,8) 	NULL,
DIAS_INCAP 			DECIMAL(28,8) 	NULL,
CURP 				VARCHAR(255) 	NULL,
HORAS_EXTRA 			DECIMAL(28,8)	NULL,
DIAS_PAGADOS 			DECIMAL(28,8) 	NULL,
XML_TEMP 			VARCHAR(MAX) 	NULL,
CONSECUTIVO 			INT 		NULL,
TOTAL DECIMAL(28,8) NULL,
SUBTOTAL DECIMAL(28,8) NULL,
DESCUENTOS DECIMAL(28,8) NULL,
IMPUESTOS DECIMAL(28,8) NULL,
ENVIADO_SCH VARCHAR(1) NOT NULL DEFAULT 'N'
)
go

ALTER TABLE $$COMPANIA$$.EMPLEADO_NOMINA_CFDI
	ADD CONSTRAINT EMPLEADO_PK 
		PRIMARY KEY (EMPLEADO,NOMINA,NUMERO_NOMINA)
go



CREATE TABLE $$COMPANIA$$.EMPLEADO_NOMINA_CFDI_CONCEPTO
(
ID 				INT IDENTITY(1,1)	NOT NULL,
EMPLEADO 			VARCHAR(20) 		NOT NULL,
NOMINA 				VARCHAR(4) 		NOT NULL,
NUMERO_NOMINA 			SMALLINT 		NOT NULL,
RECIBO 				VARCHAR (255) 		NOT NULL,
CLASE 				VARCHAR(20) 		NOT NULL,
TIPO 				VARCHAR(255) 		NULL,
CLAVE 				VARCHAR(255) 		NULL,
CONCEPTO 			VARCHAR(MAX) 		NULL,
TOTAL_GRAVADO 			DECIMAL(28,8) 		NULL,
TOTAL_EXENTO 			DECIMAL(28,8) 		NULL,
DIAS 				VARCHAR(5) 		NULL,
DESCUENTO 			DECIMAL(28,8) 		NULL,
HORAS 				VARCHAR(5) 		NULL,
IMPORTE 			DECIMAL(28,8) 		NULL
)
go

ALTER TABLE $$COMPANIA$$.EMPLEADO_NOMINA_CFDI_CONCEPTO
	ADD CONSTRAINT CONCEPTO_PK 
		PRIMARY KEY (ID,EMPLEADO,NOMINA,NUMERO_NOMINA,RECIBO)
go


 
 
 CREATE TABLE EMPLEADO_NOTAS (
        EMPLEADO             VARCHAR(20) NOT NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE EMPLEADO_NOTAS
        ADD CONSTRAINT EMPLEADO_NOTASPK PRIMARY KEY NONCLUSTERED (
               EMPLEADO)
go


CREATE TABLE EMPLEADOS_X_RANGO
(
    EMPLEADO            VARCHAR(20) 	NOT NULL,
    VARIABLE_DESICION   DECIMAL(28,8) 	NOT NULL,
    CENTRO_COSTO 	VARCHAR(25) 	NOT NULL,
    FASE 	 	VARCHAR(25) 	NULL,
    PROYECTO 	 	VARCHAR(25) 	NULL
)
go



ALTER TABLE EMPLEADOS_X_RANGO 
         ADD CONSTRAINT EMPLEADOS_X_RANGOPK PRIMARY KEY (EMPLEADO,CENTRO_COSTO)
go
 
 
 CREATE TABLE ESTADO_EMPLEADO (
        ESTADO_EMPLEADO      VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        ACTIVO               VARCHAR(1) NOT NULL,
        PAGO                 VARCHAR(1) NOT NULL,
        TEMPORAL             VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE ESTADO_EMPLEADO
        ADD CONSTRAINT ESTEMPPKESTEMP PRIMARY KEY NONCLUSTERED (
               ESTADO_EMPLEADO)
go


CREATE TABLE FILTRO_EMPLEADO_REPORTES(
	PROCESO VARCHAR(150) NOT NULL,
	EMPLEADO VARCHAR(20) NOT NULL
)
go

ALTER TABLE FILTRO_EMPLEADO_REPORTES ADD
	CONSTRAINT PK_FILTRO_EMPLEADO_REPORTES
		PRIMARY KEY (PROCESO, EMPLEADO)
go


 
 CREATE TABLE GLOBALES_CN (
        TIPO_ASIENTO         VARCHAR(4) NULL,
        PAQUETE              VARCHAR(4) NULL,
        CEDULA_JURIDICA      VARCHAR(25) NULL,
        NUMERO_PATRONAL      VARCHAR(25) NOT NULL,
        FACTOR_REDONDEO      DECIMAL(28,8) NOT NULL,
        INTEGRACION_CONTA    VARCHAR(1) NOT NULL,
        MOD_APLIC_ASIENTO    smallint NOT NULL,
        TIPO_CONTA_OMISION   VARCHAR(1) NOT NULL,
        USA_RUBROS_NOMINA    VARCHAR(1) NOT NULL,
        USA_RUBROS_EMP       VARCHAR(1) NOT NULL,
        PERMITE_NETOS_CERO   VARCHAR(1) NOT NULL,
        NOMB_RUBRO1_NOMI     VARCHAR(60) NULL,
        NOMB_RUBRO2_NOMI     VARCHAR(60) NULL,
        NOMB_RUBRO3_NOMI     VARCHAR(60) NULL,
        NOMB_RUBRO4_NOMI     VARCHAR(60) NULL,
        NOMB_RUBRO5_NOMI     VARCHAR(60) NULL,
        NOMB_RUBRO6_NOMI     VARCHAR(60) NULL,
        NOMB_RUBRO7_NOMI     VARCHAR(60) NULL,
        NOMB_RUBRO8_NOMI     VARCHAR(60) NULL,
        NOMB_RUBRO9_NOMI     VARCHAR(60) NULL,
        NOMB_RUBRO10_NOMI    VARCHAR(60) NULL,
        NOMB_RUBRO6_EMP      VARCHAR(60) NULL,
        NOMB_RUBRO7_EMP      VARCHAR(60) NULL,
        NOMB_RUBRO8_EMP      VARCHAR(60) NULL,
        NOMB_RUBRO9_EMP      VARCHAR(60) NULL,
        NOMB_RUBRO10_EMP     VARCHAR(60) NULL,
        NOMB_RUBRO11_EMP     VARCHAR(60) NULL,
        NOMB_RUBRO12_EMP     VARCHAR(60) NULL,
        NOMB_RUBRO13_EMP     VARCHAR(60) NULL,
        NOMB_RUBRO14_EMP     VARCHAR(60) NULL,
        NOMB_RUBRO15_EMP     VARCHAR(60) NULL,
        USA_FECHAS_ANTIG     VARCHAR(1) NOT NULL,
        SEG_NOMINA_REP       VARCHAR(1) NOT NULL,
        SEGURIDAD_CONCEPTO   VARCHAR(1) NOT NULL,
        SEG_CONCEPTO_REP     VARCHAR(1) NOT NULL,
        SEG_NOMINA_EMP       VARCHAR(1) NOT NULL,
        NOMB_RUBRO16_EMP     VARCHAR(60) NULL,
	NOMB_RUBRO17_EMP     VARCHAR(60) NULL,
	NOMB_RUBRO18_EMP     VARCHAR(60) NULL,
	NOMB_RUBRO19_EMP     VARCHAR(60) NULL,
	NOMB_RUBRO20_EMP     VARCHAR(60) NULL,
	NOMB_RUBRO21_EMP     VARCHAR(60) NULL,
	NOMB_RUBRO22_EMP     VARCHAR(60) NULL,
	NOMB_RUBRO23_EMP     VARCHAR(60) NULL,
	NOMB_RUBRO24_EMP     VARCHAR(60) NULL,
        NOMB_RUBRO25_EMP     VARCHAR(60) NULL,
	INTEGRACION_CR		VARCHAR(1) 	NULL,
	REQUIERE_PRESUP		VARCHAR(1) 	NULL        
 )
go

CREATE TABLE GRUPO_CONCEPTO (
        GRUPO_CONCEPTO       VARCHAR(12)  NOT NULL,
        DESCRIPCION          VARCHAR(254) NOT NULL,
        TIPO 		     VARCHAR(1)   NOT NULL 	DEFAULT('R')
)
go
 
 
ALTER TABLE GRUPO_CONCEPTO
        ADD CONSTRAINT PKGRUPOCONCEPTO PRIMARY KEY (
               GRUPO_CONCEPTO )
go

CREATE TABLE GRUPO_CONCEPTO_DET (
        GRUPO_CONCEPTO       VARCHAR(12) NOT NULL,
        CONCEPTO             VARCHAR(20) NOT NULL, 
        SECUENCIA            smallint 	 NOT NULL,
        OPERADOR 	     VARCHAR(1)  NOT NULL 	DEFAULT('S')
)
go
        
  
ALTER TABLE GRUPO_CONCEPTO_DET
        ADD CONSTRAINT PKGRUPOCONCEPTODET PRIMARY KEY (
               GRUPO_CONCEPTO, CONCEPTO )
go               


CREATE TABLE HORA_LABORADA (
         CONSECUTIVO 	  INT 	IDENTITY NOT NULL,
	 EMPLEADO         VARCHAR(20)    NOT NULL, 
         CONCEPTO         VARCHAR(20)    NOT NULL, 
         CENTRO_COSTO     VARCHAR(25)    NOT NULL,
         FECHA_LABORADA   DATETIME       NOT NULL,
         CANTIDAD_HORAS   DECIMAL(28,8)  NOT NULL,
         OBSERVACIONES    TEXT           NULL,
         CARGADO          VARCHAR(1)     NOT NULL,
         USUARIO_CARGA    VARCHAR(25)    NULL,
         FECHA_CARGA      DATETIME       NULL,
         NOMINA           VARCHAR(4)     NULL,
         NUMERO_NOMINA    smallint       NULL,
         FASE 		  VARCHAR(25)    NULL,
 	 PROYECTO	  VARCHAR(25)    NULL
) 	 
go


ALTER TABLE HORA_LABORADA
         ADD CONSTRAINT HORALABORADAPK PRIMARY KEY NONCLUSTERED
         (CONSECUTIVO, EMPLEADO, CONCEPTO, CENTRO_COSTO, FECHA_LABORADA )
go  
 
 
 CREATE TABLE HORARIO (
        HORARIO              VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        TOLERA_ENTRADA       smallint NOT NULL,
        TOLERA_SALIDA        smallint NOT NULL,
        REDONDEO_ENTRAD      smallint NOT NULL,
        REDONDEO_SALIDA      smallint NOT NULL,
		HORAS_INCAPACIDAD 	DECIMAL (28,8) NULL
 )
go
 
 
 ALTER TABLE HORARIO
        ADD CONSTRAINT HORARIOPK PRIMARY KEY NONCLUSTERED (HORARIO)
go
 
 
 CREATE TABLE HORARIO_CONCEPTO (
        HORARIO              VARCHAR(4) NOT NULL,
        DIA                  smallint NOT NULL,
        HORA_INICIO          DATETIME NOT NULL,
        HORA_FINAL           DATETIME NOT NULL,
        CONCEPTO             VARCHAR(20) NULL
 )
go
 
 
 ALTER TABLE HORARIO_CONCEPTO
        ADD CONSTRAINT TURNO_CONCEPTOPK PRIMARY KEY NONCLUSTERED (
               HORARIO, DIA, HORA_INICIO)
go

CREATE TABLE LIQUIDACION_PAGO ( 
	LIQUIDACION			smallint	NOT NULL,
	MONEDA 				VARCHAR(4)	NOT NULL,
	PERIODO		 		DATETIME	NOT NULL,
	TIPO				VARCHAR(3) 	NOT NULL,
	SUBTIPO             		smallint	NOT NULL,
	NOTAS				TEXT		NULL
)
go

ALTER TABLE LIQUIDACION_PAGO 
	ADD CONSTRAINT LIQUIDACIONPAGOPK
		PRIMARY KEY NONCLUSTERED (LIQUIDACION)
go

CREATE TABLE LIQUIDACION_PAGO_DET ( 
	LIQUIDACION			smallint	NOT NULL,
	PROVEEDOR 			VARCHAR(20) 	NOT NULL,
	DOCUMENTO		 	VARCHAR(50)	NULL,
	MONTO_CALCULADO			DECIMAL(28,8) 	NOT NULL,
	MONTO_GENERADO			DECIMAL(28,8) 	NOT NULL
)
go

ALTER TABLE LIQUIDACION_PAGO_DET 
	ADD CONSTRAINT LIQPAGODETPK
		PRIMARY KEY (LIQUIDACION,PROVEEDOR) 
go		
 
 
 CREATE TABLE MARCA_RELOJ (
        EMPLEADO             VARCHAR(20) 	NOT NULL,
        FCH_HORA_ENTRADA     DATETIME 		NOT NULL,
        USUARIO              VARCHAR(25) 	NOT NULL,
        HORARIO              VARCHAR(4) 	NOT NULL,
        FCH_HORA_SALIDA      DATETIME 		NULL,
        CARGADO              VARCHAR(1) 	NOT NULL,
        CONSISTENTE          VARCHAR(1) 	NOT NULL,
        FECHA_HORA           DATETIME 		NOT NULL
 )
go
 
 
 ALTER TABLE MARCA_RELOJ
        ADD CONSTRAINT MARCARELOJPK PRIMARY KEY NONCLUSTERED (
               EMPLEADO, FCH_HORA_ENTRADA)
go
 
 
 CREATE TABLE NOMINA (
        NOMINA               	VARCHAR(4) 	NOT NULL,
        RUBRO9               	VARCHAR(40)	NULL,
        CTR_NOMINA           	VARCHAR(25)	NULL,
        CTA_NOMINA           	VARCHAR(25)	NULL,
        DESCRIPCION          	VARCHAR(40)	NOT NULL,
        TIPO_NOMINA          	VARCHAR(1) 	NOT NULL,
        CONSECUTIVO          	smallint 	NOT NULL,
        NUMERO_PATRONAL      	VARCHAR(25) 	NULL,
        ESTADO               	VARCHAR(1) 	NOT NULL,
        CUENTA_BANCO         	VARCHAR(20)	NULL,
        MONEDA               	VARCHAR(4) 	NOT NULL,
        IMP_ACUM_CONCEPTOS   	VARCHAR(1) 	NOT NULL,
        IMP_COND_CONCEPTOS   	VARCHAR(1) 	NOT NULL,
        ELIMINAR_CONC_CERO   	VARCHAR(1) 	NOT NULL,
        RUBRO1               	VARCHAR(40) 	NULL,
        RUBRO2               	VARCHAR(40) 	NULL,
        RUBRO7               	VARCHAR(40) 	NULL,
        RUBRO6               	VARCHAR(40) 	NULL,
        RUBRO5               	VARCHAR(40) 	NULL,
        RUBRO3               	VARCHAR(40) 	NULL,
        RUBRO4               	VARCHAR(40) 	NULL,
        RUBRO8               	VARCHAR(40) 	NULL,
        RUBRO10              	VARCHAR(40) 	NULL,
        SUBTIPODOC_CHEQUE    	smallint 		NULL,
        SUBTIPODOC_TEF       	smallint 		NULL,
        MODALIDAD_ASIENTO    	VARCHAR(1) 		NULL,
        CONCEPTO_TIPO_CAMBIO	VARCHAR(20)		NULL,
		CONCEPTO_DIAS_LABOR		VARCHAR(20)		NULL,
		REPORTE 				VARCHAR(100)	NULL,
		PAQUETE_CR				VARCHAR(4) 		NULL,
		PRESUPUESTO_CR			VARCHAR(20)	 	NULL,
		INICIALIZAR_POR_PUESTO	VARCHAR(1) 		NOT NULL DEFAULT 'N',
		NUMSERIE 				VARCHAR(25)		NULL,
		ES_PILA 				VARCHAR(1)		NOT NULL DEFAULT 'N',
		NIT_CIA_ASNT 			VARCHAR(1) 		NOT NULL DEFAULT ('N')
	 )
go
 
 
 ALTER TABLE NOMINA
        ADD CONSTRAINT NOMINAPK PRIMARY KEY NONCLUSTERED (NOMINA)
go
 
 
 CREATE TABLE NOMINA_CONCEPTO (
        NOMINA               VARCHAR(4) NOT NULL,
        CONCEPTO             VARCHAR(20) NOT NULL,
        ACTIVO               VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE NOMINA_CONCEPTO
        ADD CONSTRAINT NOMINACONCEPTOPK PRIMARY KEY NONCLUSTERED (
               NOMINA, CONCEPTO)
go
 
 
CREATE TABLE NOMINA_BANCO(
	NOMINA 			VARCHAR(4) NOT NULL,
	CUENTA_BANCO 	VARCHAR(20) NOT NULL,
	CTA_DEFAULT 	VARCHAR(1) NULL
)
go

ALTER TABLE NOMINA_BANCO
	ADD CONSTRAINT NOMBANPK
		PRIMARY KEY (NOMINA,CUENTA_BANCO)
go
 
 CREATE TABLE NOMINA_HISTORICO (
        NOMINA               VARCHAR(4) 	NOT NULL,
        NUMERO_NOMINA        smallint 		NOT NULL,
        FECHA_INICIO         DATETIME 		NOT NULL,
        FECHA_FIN            DATETIME 		NOT NULL,
        PERIODO              DATETIME 		NOT NULL,
        FECHA_APROBACION     DATETIME 		NULL,
        FECHA_PAGO           DATETIME 		NOT NULL,
        APROBADA_POR         VARCHAR(25) 	NULL,
        ASIENTO              VARCHAR(10) 	NULL,
        FECHA_APLICACION     DATETIME 		NULL,
        USUARIO_APLICACION   VARCHAR(25) 	NULL,
        FECHA_CALCULO        DATETIME 		NULL,
       	PRESUPUESTO	     VARCHAR(20)     	NULL,
        UNIDAD_OPERATIVA     VARCHAR(4)      	NULL,
        NUMERO_APARTADO	     INT         	NULL,
        NUMERO_EJERCIDO	     INT         	NULL
 )
go
 
 
 ALTER TABLE NOMINA_HISTORICO
        ADD CONSTRAINT NOMINAHISTORICOPK PRIMARY KEY NONCLUSTERED (
               NOMINA, NUMERO_NOMINA)
go
 
 
 CREATE TABLE NOMINA_USUARIO (
        NOMINA               VARCHAR(4) 	NOT NULL,
        USUARIO              VARCHAR(25) 	NOT NULL,
        PRIVILEGIO           VARCHAR(1) 	NOT NULL
 )
go
 
 
 ALTER TABLE NOMINA_USUARIO
        ADD CONSTRAINT NOMINAUSUARIOPK PRIMARY KEY NONCLUSTERED (
               NOMINA, USUARIO)
go



CREATE TABLE PILA_HISTORICO(
	NOMINA varchar(4) NOT NULL,
	NUMERO_NOMINA smallint NOT NULL,
	TIPO_REGISTRO varchar(2) NOT NULL,
	ECN_MODALIDAD varchar(1) NULL,
	SECUENCIA varchar(4) NOT NULL,
	ECN_RAZON_SOCIAL varchar(200) NULL,
	ECN_TIPO_DOC_APORTANTE varchar(2) NULL,
	ECN_ID_APORTANTE varchar(16) NULL,
	ECN_DIGITO_VERIFICADOR varchar(1) NULL,
	ECN_TIPO_PLANILLA varchar(1) NULL,
	ECN_NUMERO_PLANILLA varchar(10) NULL,
	ECN_FECHA_PAGO_PLANILLA varchar(10) NULL,
	ECN_FORMA_PRESENTA varchar(1) NULL,
	ECN_CODIGO_SUCURSAL varchar(10) NULL,
	ECN_NOMBRE_SUCURSAL varchar(40) NULL,
	ECN_CODIGO_ARL varchar(6) NULL,
	ECN_PERIODO_DIF_SALUD varchar(7) NULL,
	ECN_PERIODO_SALUD varchar(7) NULL,
	ECN_NUMERO_RADICACION varchar(10) NULL,
	ECN_FECHA_PAGO varchar(10) NULL,
	ECN_TOTAL_EMPLEADOS int NULL,
	ECN_VALOR_TOTAL_NOM decimal(28, 8) NULL,
	ECN_TIPO_APORTANTE varchar(2) NULL,
	ECN_CODIGO_OPERADOR varchar(2) NULL,
	AP_CODIGO_ADMIN varchar(6) NULL,
	AP_NIT_ADMIN varchar(16) NULL,
	AP_DIGITO_VERIFICADOR varchar(1) NULL,
	AP_COT_OBLIGATORIAS decimal(28, 8) NULL,
	AP_COT_VOL_AFILIADOS decimal(28, 8) NULL,
	AP_COT_VOL_APORTANTE decimal(28, 8) NULL,
	AP_APORTE_FON_SUB_SOL decimal(28, 8) NULL,
	AP_APORTE_FON_SUB_SUB decimal(28, 8) NULL,
	AP_DIAS_MORA_LIQ decimal(28, 8) NULL,
	AP_INT_MORA_LIQ decimal(28, 8) NULL,
	AP_INT_MORA_SOL decimal(28, 8) NULL,
	AP_INT_MORA_SUB decimal(28, 2) NULL,
	TOTAL_PAGAR_ADMIN decimal(28, 8) NULL,
	TOTAL_PAGAR_AFILIADOS decimal(28, 8) NULL,
	ARP_CODIGO_ARL varchar(6) NULL,
	ARP_NIT_ARL varchar(16) NULL,
	ARP_DIGITO_VERIFICADOR varchar(1) NULL,
	ARP_TOTAL_COTIZACIONES decimal(28, 8) NULL,
	ARP_NUM_AUTORIZACION decimal(28, 8) NULL,
	ARP_TOTAL_INCAP_PAG decimal(28, 8) NULL,
	ARP_APOR_OTROS_SIST decimal(28, 8) NULL,
	ARP_NETOS_APORTES decimal(28, 8) NULL,
	ARP_DIAS_MORA_LIQ decimal(28, 8) NULL,
	ARP_INT_MORA decimal(28, 8) NULL,
	ARP_SUBTOTAL_APORTES decimal(28, 8) NULL,
	ARP_FORMULARIO varchar(10) NULL,
	ARP_SALDO_FAVOR decimal(28, 8) NULL,
	ARP_TOTAL_PAGAR_ADM decimal(28, 8) NULL,
	ARP_RIESGOS_LABORALES decimal(28, 8) NULL,
	ARP_TOTAL_AFILIADOS decimal(28, 8) NULL,
	EPS_CODIGO varchar(6) NULL,
	EPS_NIT varchar(16) NULL,
	EPS_DIGITO_VERIFICADOR varchar(1) NULL,
	EPS_COTIZACIONES_OBLIG decimal(28, 8) NULL,
	EPS_UPC_ADICIONAL decimal(28, 8) NULL,
	EPS_NUM_AUTOR_INC decimal(28, 8) NULL,
	EPS_INCAPAC_PAG decimal(28, 8) NULL,
	EPS_NUM_AUTORIZACION_MAT decimal(28, 8) NULL,
	EPS_LIC_MATERNIDAD_PAG decimal(28, 8) NULL,
	EPS_NETO_APORTES_COT decimal(28, 8) NULL,
	EPS_DIAS_MORA_LIQ decimal(28, 8) NULL,
	EPS_INT_MORA decimal(28, 8) NULL,
	EPS_INT_MORA_UPC decimal(28, 8) NULL,
	EPS_SUB_APORTES decimal(28, 8) NULL,
	EPS_SUB_UPC decimal(28, 8) NULL,
	EPS_NUM_FORMULARIO varchar(10) NULL,
	EPS_SALDO_FAVOR_ANTERIOR decimal(28, 8) NULL,
	EPS_SALDOS_FAVOR_UPC decimal(28, 8) NULL,
	EPS_TOTAL_PAGAR decimal(28, 8) NULL,
	EPS_TOTAL_PAGAR_UPC decimal(28, 8) NULL,
	EPS_TOTAL_PAGAR_ADMIN decimal(28, 8) NULL,
	EPS_FONDO_SOLID_GARAN decimal(28, 8) NULL,
	EPS_TOTAL_AFILIADOS int NULL,
	CCF_CODIGO varchar(6) NULL,
	CCF_NIT varchar(16) NULL,
	CCF_DIGITO_VERIFICADOR varchar(1) NULL,
	CCF_VALOR_APORTES decimal(28, 8) NULL,
	CCF_DIAS_MORA_LIQ decimal(28, 8) NULL,
	CCF_INT_MORA decimal(28, 8) NULL,
	CCF_TOTAL_PAGAR decimal(28, 8) NULL,
	CCF_TOTAL_AFILIADOS int NULL,
	SENA_NIT varchar(16) NULL,
	SENA_DIGITO_VERIFICADOR varchar(1) NULL,
	SENA_VALOR_APORTE decimal(28, 8) NULL,
	SENA_DIAS_MORA_LIQ decimal(28, 8) NULL,
	SENA_INT_MORA decimal(28, 8) NULL,
	SENA_TOTAL_PAGAR decimal(28, 8) NULL,
	SENA_TOTAL_AFILIADOS int NULL,
	ICBF_NIT varchar(16) NULL,
	ICBF_DIGITO_VERIFICADOR varchar(1) NULL,
	ICBF_VALOR_APORTE decimal(28, 8) NULL,
	ICBF_DIAS_MORA_LIQ decimal(28, 8) NULL,
	ICBF_INT_MORA decimal(28, 8) NULL,
	ICBF_TOTAL_PAGAR decimal(28, 8) NULL,
	ICBF_TOTAL_AFILIADOS int NULL,
	ESAP_NIT varchar(16) NULL,
	ESAP_DIGITO_VERIFICADOR varchar(1) NULL,
	ESAP_VALOR_PAGAR decimal(28, 8) NULL,
	ESAP_DIAS_MORA_LIQ decimal(28, 8) NULL,
	ESAP_INT_MORA decimal(28, 8) NULL,
	ESAP_TOTAL_PAGAR decimal(28, 8) NULL,
	MEN_NIT varchar(16) NULL,
	MEN_DIGITO_VERIFICADOR varchar(1) NULL,
	MEN_VALOR_PAGAR decimal(28, 8) NULL,
	MEN_DIAS_MORA_LIQ decimal(28, 8) NULL,
	MEN_INT_MORA decimal(28, 8) NULL,
	MEN_TOTAL_PAGAR decimal(28, 8) NULL,
	TOTAL_PENSIONES decimal(28, 8) NULL,
	TOTAL_FON_SOL_PEN decimal(28, 8) NULL,
	TOTAL_SALUD decimal(28, 8) NULL,
	TOTAL_RIESGOS_LAB decimal(28,8) NULL,
	TOTAL_CCF decimal(28, 8) NULL,
	TOTAL_SENA decimal(28, 8) NULL,
	TOTAL_ICBF decimal(28, 8) NULL,
	TOTAL_ESAP decimal(28, 8) NULL,
	TOTAL_MEN decimal(28, 8) NULL,
	TOTAL_GRAN_TOTAL decimal(28, 8) NULL,
	TOTAL_NUM_ADMIN_PEN int NULL,
	TOTAL_NUM_ADMIN_EPS int NULL,
	TOTAL_NUM_ADMIN_ARL int NULL,
	TOTAL_NUM_ADMIN_CCF int NULL
)

go

ALTER TABLE PILA_HISTORICO 
	ADD CONSTRAINT PILAENCPK PRIMARY KEY (NOMINA,NUMERO_NOMINA,TIPO_REGISTRO,SECUENCIA)

go

CREATE TABLE PILA_HISTORICO_DET(
	NOMINA varchar(4) NOT NULL,
	NUMERO_NOMINA smallint NOT NULL,
	EMPLEADO varchar(20) NOT NULL,
	TIPO_REGISTRO varchar(2) NOT NULL,
	SECUENCIA int NOT NULL,
	TIPO_DOC varchar(2) NULL,
	ID_COTIZANTE varchar(16) NULL,
	TIPO_COTIZANTE varchar(2) NULL,
	SUBTIPO_COTIZANTE varchar(2) NULL,
	EXTRANJERO varchar(1) NULL,
	COLOMBIANO_EXTERIOR varchar(1) NULL,
	CODIGO_DEPTO varchar(2) NULL,
	CODIGO_MUNICIPIO varchar(3) NULL,
	ING varchar(1) NULL,
	RET varchar(1) NULL,
	EPS varchar(1) NULL,
	TAE varchar(1) NULL,
	TDP varchar(1) NULL,
	TAP varchar(1) NULL,
	VSP varchar(1) NULL,
	CORRECCIONES varchar(1) NULL,
	VST varchar(1) NULL,
	SLN varchar(1) NULL,
	IGE varchar(1) NULL,
	LMA varchar(1) NULL,
	VAC varchar(1) NULL,
	AVP varchar(1) NULL,
	VCT varchar(1) NULL,
	IRP int NULL,
	ADM_PENSIONES varchar(6) NULL,
	ADM_TRASLADO varchar(6) NULL,
	EPS_PERTENECE varchar(6) NULL,
	EPS_TRASLADA varchar(6) NULL,
	CCF_PERTENECE varchar(6) NULL,
	DIAS_PENSION int NULL,
	DIAS_SALUD int NULL,
	DIAS_RIESGOS int NULL,
	DIAS_COMPENSA int NULL,
	SALARIO_BASICO decimal(28, 8) NULL,
	SALARIO_INTEGRAL varchar(1) NULL,
	IBC_PENSION decimal(28, 8) NULL,
	IBC_SALUD decimal(28, 8) NULL,
	IBC_RIESGOS decimal(28, 8) NULL,
	IBC_CCF decimal(28, 8) NULL,
	TARIFA_PENSIONES decimal(28, 8) NULL,
	COT_OBLIG_PENSIONES decimal(28, 8) NULL,
	APORTE_VOL_AFIL_PEN decimal(28, 8) NULL,
	APORTE_VOL_APOR_PEN decimal(28, 8) NULL,
	COT_SIST_PENSIONES decimal(28, 8) NULL,
	APOR_FON_SOLI decimal(28, 8) NULL,
	APOR_FON_SUBS decimal(28, 8) NULL,
	NO_RET_APOR_VOL decimal(28, 8) NULL,
	TAR_APOR_SALUD decimal(28, 8) NULL,
	COT_OBLI_SALUD decimal(28, 8) NULL,
	UPC_ADICIONAL decimal(28, 8) NULL,
	AUTOR_IEG varchar(15) NULL,
	VALOR_IEG decimal(28, 8) NULL,
	AUTOR_LMA varchar(15) NULL,
	VALOR_LMA decimal(28, 8) NULL,
	TAR_APOR_RIESGOS decimal(28, 8) NULL,
	CENTRO_TRABAJO decimal(28, 8) NULL,
	COT_OBLI_SIST_RIESGOS decimal(28, 8) NULL,
	TAR_APORT_CCF decimal(28, 8) NULL,
	VALOR_APORTE_CCF decimal(28, 8) NULL,
	TAR_APOR_SENA decimal(28, 8) NULL,
	VALOR_APOR_SENA decimal(28, 8) NULL,
	TAR_APOR_ICBF decimal(28, 8) NULL,
	VALOR_APOR_ICBF decimal(28, 8) NULL,
	TAR_APOR_ESAP decimal(28, 8) NULL,
	VALOR_APOR_ESAP decimal(28, 8) NULL,
	TAR_APOR_MEN decimal(28, 8) NULL,
	VALOR_APOR_MEN decimal(28, 8) NULL,
	TIPO_DOC_COT_PRIN varchar(2) NULL,
	NIT_COT_PRIN varchar(16) NULL,
	COT_EXONERADO varchar(1) NULL,
	ADM_RIESGOS_PROF varchar(6) NULL,
	CLASE_RIESGO varchar(1) NULL,
	TAR_ESP_PEN varchar(1) NULL,
	FECHA_INGRESO datetime NULL,
	FECHA_RETIRO datetime NULL,
	INICIO_VSP datetime NULL,
	INICIO_SLN datetime NULL,
	FIN_SLN datetime NULL,
	INICIO_IGE datetime NULL,
	FINAL_IGE datetime NULL,
	INICIO_LMA datetime NULL,
	FINAL_LMA datetime NULL,
	INICIO_VAC datetime NULL,
	FINAL_VAC datetime NULL,
	INICIO_VCT datetime NULL,
	FIN_VCT datetime NULL,
	INICIO_IRL datetime NULL,
	FINAL_IRL datetime NULL,
	IBC_OTROS_PARA decimal(28, 8) NULL,
	HORAS_LABORADAS decimal(28, 8) NULL,
	FECHA_EXTERIOR datetime NULL
)
	
go

ALTER TABLE PILA_HISTORICO_DET
	ADD CONSTRAINT PILADETPK PRIMARY KEY (NOMINA, NUMERO_NOMINA,SECUENCIA)

go
 
 CREATE TABLE PLAZA (
        PUESTO               VARCHAR(8) 	NOT NULL,
        PLAZA                VARCHAR(8) 	NOT NULL,
        DEPARTAMENTO         VARCHAR(10) 	NOT NULL,
        COMPARTIDA           VARCHAR(1) 	NOT NULL,
        TIPO                 VARCHAR(1) 	NOT NULL,
        ESTADO               VARCHAR(1) 	NOT NULL,
        CANTIDAD_EMPLEADOS   int 		NOT NULL,
        FECHA_VACANTE        DATETIME 		NULL,
        RIGE_DESDE           DATETIME 		NULL,
        RIGE_HASTA           DATETIME 		NULL,
        NOTAS                TEXT 		NULL,
        USUARIO              VARCHAR(25) 	NOT NULL,
        FECHA_HORA_MOD       DATETIME 		NOT NULL
 )
go
 
 
 ALTER TABLE PLAZA
        ADD CONSTRAINT XPKPLAZA PRIMARY KEY NONCLUSTERED (PUESTO, 
               PLAZA)
go



CREATE TABLE PREASIENTO (
	ASIENTO              	VARCHAR(10) 	NOT NULL,
        PAQUETE              	VARCHAR(4) 	NOT NULL,
        TIPO_ASIENTO         	VARCHAR(4) 	NOT NULL,
        FECHA                	DATETIME 	NOT NULL,
        CONTABILIDAD         	VARCHAR(1) 	NOT NULL,
        ORIGEN               	VARCHAR(4) 	NOT NULL,
        CLASE_ASIENTO        	VARCHAR(1) 	NOT NULL,
        TOTAL_DEBITO_LOC     	DECIMAL(28,8) 	NOT NULL,
        TOTAL_DEBITO_DOL     	DECIMAL(28,8) 	NOT NULL,
        TOTAL_CREDITO_LOC    	DECIMAL(28,8) 	NOT NULL,
        TOTAL_CREDITO_DOL    	DECIMAL(28,8) 	NOT NULL,
        ULTIMO_USUARIO       	VARCHAR(25) 	NOT NULL,
        FECHA_ULT_MODIF      	DATETIME 	NOT NULL,
        NOTAS                	TEXT 		NULL,
        TOTAL_CONTROL_LOC    	DECIMAL(28,8) 	NOT NULL,
        TOTAL_CONTROL_DOL    	DECIMAL(28,8) 	NOT NULL,
        USUARIO_CREACION     	VARCHAR(25) 	NOT NULL,
        FECHA_CREACION       	DATETIME 	NOT NULL,
        DEPENDENCIA 		VARCHAR(10) 	NULL,
	PROCESO			VARCHAR(10) 	NOT NULL,
	NOMINA			VARCHAR(4) 	NULL
	
 )
go 
 
ALTER TABLE PREASIENTO 	
	ADD CONSTRAINT XPKPREASIENTO PRIMARY KEY NONCLUSTERED ( ASIENTO )
go
 
 
 CREATE TABLE PUESTO (
        PUESTO               VARCHAR(8) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        SALARIO_MINIMO       DECIMAL(28,8) NULL,
        SALARIO_INTERM1      DECIMAL(28,8) NULL,
        SALARIO_INTERM2      DECIMAL(28,8) NULL,
        SALARIO_MAXIMO       DECIMAL(28,8) NULL,
        SALARIO_ACTUAL       DECIMAL(28,8) NULL,
        CONSECUTIVO_PLAZA    VARCHAR(8) NOT NULL,
        NOTAS                TEXT NULL,
        ACTIVO 		     VARCHAR(1) NOT NULL DEFAULT('S')
 )
go
 
 
 ALTER TABLE PUESTO
        ADD CONSTRAINT PUESTOPKPUESTO PRIMARY KEY NONCLUSTERED (
               PUESTO)
go

CREATE TABLE PTO_EXTERNO_PUESTO (
         PUESTO         VARCHAR(8)         NOT NULL,
         CAT_PUESTO_EXTERNO         VARCHAR(12)         NOT NULL,
         PUESTO_EXTERNO         VARCHAR(12)         NOT NULL )
go         

ALTER TABLE PTO_EXTERNO_PUESTO
         ADD CONSTRAINT PTOEXTERNOPUESTOPK PRIMARY KEY NONCLUSTERED
         (PUESTO, CAT_PUESTO_EXTERNO )
go         
 
 
 CREATE TABLE PUESTO_EXTERNO (
          CAT_PUESTO_EXTERNO         VARCHAR(12)         NOT NULL,
          PUESTO_EXTERNO         VARCHAR(12)         NOT NULL,
          DESCRIPCION         VARCHAR(254)         NOT NULL )
go

 
 ALTER TABLE PUESTO_EXTERNO
          ADD CONSTRAINT PUESTOEXTERNOPK PRIMARY KEY NONCLUSTERED
         (CAT_PUESTO_EXTERNO, PUESTO_EXTERNO )
go        


 
 CREATE TABLE PUESTO_FUNCIONES (
        PUESTO               VARCHAR(8) NOT NULL,
        PUESTO_FUNCIONES     TEXT NULL
 )
go
 
 
 ALTER TABLE PUESTO_FUNCIONES
        ADD CONSTRAINT XPKPUESTO_FUNCIONE PRIMARY KEY (PUESTO)
go
 
 
 CREATE TABLE PUESTO_SALARIO (
        PUESTO               VARCHAR(8) NOT NULL,
        FECHA                DATETIME NOT NULL,
        MERCADO_MINIMO       DECIMAL(28,8) NULL,
        MERCADO_CUARTIL1     DECIMAL(28,8) NULL,
        MERCADO_CUARTIL2     DECIMAL(28,8) NULL,
        MERCADO_CUARTIL3     DECIMAL(28,8) NULL,
        MERCADO_MAXIMO       DECIMAL(28,8) NULL,
        SALARIO_COMPANIA     DECIMAL(28,8) NULL,
        MERCADO_PROMEDIO     DECIMAL(28,8) NULL,
        MERCADO_MODA         DECIMAL(28,8) NULL,
        MINIMO_LEY           DECIMAL(28,8) NULL
 )
go
 
 
 ALTER TABLE PUESTO_SALARIO
        ADD CONSTRAINT PTOSALPKPTOFECHA PRIMARY KEY NONCLUSTERED (
               PUESTO, FECHA)
go

CREATE TABLE TEMP_PRIMITIVA_HISTORICA
(
	empleado 	varchar(20) 	NOT NULL,
	nomina 		varchar(4) 	NOT NULL,
	centro_costo 	varchar(25) 	NULL,
	total 		decimal(28,8) 	NULL
)
go


CREATE TABLE TIPO_COTIZANTE(
         TIPO_COTIZANTE		VARCHAR(2)	NOT NULL,
         DESCRIPCION		VARCHAR(254)	NOT NULL
)
go

ALTER TABLE TIPO_COTIZANTE
         ADD CONSTRAINT TIPO_COTIZANTEPK 
         	PRIMARY KEY NONCLUSTERED (TIPO_COTIZANTE )
go

CREATE TABLE SUBTIPO_COTIZANTE(
         SUBTIPO_COTIZANTE	VARCHAR(2)	NOT NULL,
         DESCRIPCION		VARCHAR(254)	NOT NULL
)
go

ALTER TABLE SUBTIPO_COTIZANTE
         ADD CONSTRAINT SUBTIPO_COTIZANTEPK 
         	PRIMARY KEY NONCLUSTERED (SUBTIPO_COTIZANTE )
go         	

       