
 
 CREATE TABLE ARANCEL_IMPUESTO (
        CODIGO_ARANCEL       VARCHAR(15) NOT NULL,
        IMPUESTO_COMPRA      VARCHAR(20) NOT NULL,
        UTILIZADO_SIEMPRE    VARCHAR(1)  NOT NULL DEFAULT ( 'S' )
 )
go
 
 
 ALTER TABLE ARANCEL_IMPUESTO
        ADD CONSTRAINT XPKARANCEL_IMPUESTO PRIMARY KEY (
               CODIGO_ARANCEL, IMPUESTO_COMPRA)
go
 
 
 CREATE TABLE ARTICULO_COMPRA (
        ARTICULO             	VARCHAR(20) 	NOT NULL,
        ULT_PROVEEDOR        	VARCHAR(20) 	NULL,
        ULT_MONEDA           	VARCHAR(4) 	NULL,
        IMPUESTO             	VARCHAR(4) 	NOT NULL,
        CODIGO_ARANCEL       	VARCHAR(15) 	NULL,
        DESCRIPCION          	VARCHAR(254) 	NOT NULL,
        CODIGO_CORPORATIVO      VARCHAR(20) 	NULL,
        IMP1_AFECTA_COSTO    	VARCHAR(1) 	NOT NULL,
        PORC_VARIAC_CANT     	DECIMAL(28,8) 	NULL,
        ULT_PREC_UNITARIO    	DECIMAL(28,8)	NULL,
        ULT_FECHA_COTIZA     	DATETIME 	NULL,
        RECIBIR_MAS          	VARCHAR(1) 	NOT NULL,
        BODEGA         			VARCHAR(4)      NULL,
        USA_CTA_TRANSITO		VARCHAR(1) 	NOT NULL DEFAULT('N'),
        ACEPTA_BACKORDER_MONTO 	VARCHAR(1) 	NULL
		
 )
go
 
 
 ALTER TABLE ARTICULO_COMPRA
        ADD CONSTRAINT XPKDATO_COMPRA PRIMARY KEY NONCLUSTERED (
               ARTICULO)
go
 
 
 CREATE TABLE ARTICULO_PROVEEDOR (
        ARTICULO             VARCHAR(20) 	NOT NULL,
        PROVEEDOR            VARCHAR(20) 	NOT NULL,
        CODIGO_CATALOGO      VARCHAR(20) 	NULL,
        LOTE_MINIMO          DECIMAL(28,8) 	NOT NULL,
        LOTE_ESTANDAR        DECIMAL(28,8) 	NOT NULL,
        PESO_MINIMO_ORDEN    DECIMAL(28,8) 	NOT NULL,
        MULTIPLO_COMPRA      DECIMAL(28,8) 	NOT NULL,
        CANT_ECONOMICA_COM   DECIMAL(28,8) 	NOT NULL,
        UNIDAD_MEDIDA_COMP   VARCHAR(10) 	NOT NULL,
        FACTOR_CONVERSION    DECIMAL(28,8) 	NOT NULL,
        PLAZO_REABASTECIMI   smallint 		NOT NULL,
        PORC_AJUSTE_COSTO    DECIMAL(28,8) 	NOT NULL,
        FECHA_ULT_COTIZACI   DATETIME 		NULL,
        NOTAS                TEXT 		NULL,
        DESCRIP_CATALOGO     VARCHAR(254) 	NULL,
        PAIS 		     VARCHAR(4) 	NOT NULL DEFAULT ('ND'),
	TIPO		     VARCHAR(1) 	NOT NULL DEFAULT ('P'),
	IMPUESTO 	     VARCHAR(4) 	NULL
 )
go
 
 
 ALTER TABLE ARTICULO_PROVEEDOR
        ADD CONSTRAINT XPKARTICULO_PROVEE PRIMARY KEY NONCLUSTERED (
               ARTICULO, PROVEEDOR)
go
 
CREATE TABLE BODEGA_ENCARGADO (
         BODEGA         VARCHAR(4)  NOT NULL,
         ENCARGADO      VARCHAR(70) NOT NULL,
         EMPLEADO       VARCHAR(20) NULL,
         E_MAIL         VARCHAR(250) NOT NULL )
go

ALTER TABLE BODEGA_ENCARGADO
         ADD CONSTRAINT XPKBODEGA_ENCARGAD PRIMARY KEY NONCLUSTERED
         (BODEGA, ENCARGADO )
go         
 
 CREATE TABLE CODIGO_ARANCEL (
        CODIGO_ARANCEL       VARCHAR(15) NOT NULL,
        DESCRIPCION          VARCHAR(50) NOT NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE CODIGO_ARANCEL
        ADD CONSTRAINT XPKTARIFA_IMPORTAC PRIMARY KEY NONCLUSTERED (
               CODIGO_ARANCEL)
go
 

CREATE TABLE DET_DOCUMENTO_EMBARQUE (
	DOCUMENTO			VARCHAR(50)	NOT NULL,
	PROVEEDOR			VARCHAR(20)	NOT NULL,
	TIPO_DOCUMENTO			VARCHAR(1)	NOT NULL,
	EMBARQUE			VARCHAR(10)	NOT NULL,
	MONTO_APLICAR			DECIMAL(28,8)	NOT NULL )
go	
	
ALTER TABLE DET_DOCUMENTO_EMBARQUE 
	ADD CONSTRAINT XPKDETDOCEMBT PRIMARY KEY NONCLUSTERED
		( PROVEEDOR, DOCUMENTO, TIPO_DOCUMENTO, EMBARQUE )
go 

CREATE TABLE DET_DOCUMENTO_ORDEN  (
	DOCUMENTO  	VARCHAR  (50) NOT NULL,
	PROVEEDOR  	VARCHAR  (20) NOT NULL,
	TIPO_DOCUMENTO 	VARCHAR  (1)  NOT NULL,
	ORDEN_COMPRA  	VARCHAR  (10) NOT NULL	)
go	

ALTER TABLE DET_DOCUMENTO_ORDEN  
	ADD CONSTRAINT XPKDETDOCORD
		PRIMARY KEY  NONCLUSTERED (PROVEEDOR ,DOCUMENTO ,TIPO_DOCUMENTO ,ORDEN_COMPRA )
go		

   
 CREATE TABLE DET_LIN_EMBARQUE (
        EMBARQUE             VARCHAR(10) NOT NULL,
        EMBARQUE_LINEA       smallint NOT NULL,
        SECUENCIA            smallint NOT NULL,
        SERIE_CADENA         int NULL,
        LOTE                 VARCHAR(15) NULL,
        BODEGA               VARCHAR(4) NULL,
        LOCALIZACION         VARCHAR(8) NULL,
        CANT_RECIBIDA        DECIMAL(28,8) NOT NULL,
        CANT_RECHAZADA       DECIMAL(28,8) NOT NULL,
        CANT_RECIBIDA_UA     DECIMAL(28,8) NULL,
        CANT_RECHAZADA_UA    DECIMAL(28,8) NULL
 )
go
 
 
 ALTER TABLE DET_LIN_EMBARQUE
        ADD CONSTRAINT XPKE_336 PRIMARY KEY (EMBARQUE, EMBARQUE_LINEA, 
               SECUENCIA)
go
 
CREATE TABLE DETALLE_RETENCION_CO (
        PROVEEDOR            VARCHAR(20) 	NOT NULL,
        DOCUMENTO            VARCHAR(50) 	NOT NULL,
        TIPO_DOCUMENTO 	     VARCHAR(1) 	NOT NULL,
        CODIGO_RETENCION     VARCHAR(4) 	NOT NULL,
        MONTO                DECIMAL(28,8) 	NOT NULL,
		BASE                 DECIMAL(28,8) 	NOT NULL,
		AUTORETENEDORA 	     VARCHAR(1) 	DEFAULT ('N') NOT NULL,
		CALCULA_PROVEEDOR    VARCHAR(1) 	NOT NULL,
		FECHA_DOCUMENTO 	 DATETIME 		NULL,
		CONSECUTIVO			 VARCHAR(50) 	NULL,
		FECHA_RIGE 			 DATETIME NULL,
		FECHA_CONTABLE 		 DATETIME NULL
)
go 

ALTER TABLE DETALLE_RETENCION_CO
        ADD CONSTRAINT XPKDETRETCO
		PRIMARY KEY ( PROVEEDOR, DOCUMENTO, TIPO_DOCUMENTO, CODIGO_RETENCION )
go 
 
 CREATE TABLE DEVOL_LIN_EMBARQUE (
        DEVOLUCION           VARCHAR(50) NOT NULL,
        DEVOLUCION_LINEA     smallint NOT NULL,
        SERIE_CADENA         int NULL,
        ORDEN_COMPRA         VARCHAR(10) NULL,
        BODEGA               VARCHAR(4) NOT NULL,
        LOCALIZACION         VARCHAR(8) NULL,
        LOTE                 VARCHAR(15) NULL,
        EMBARQUE             VARCHAR(10) NOT NULL,
        EMBARQUE_LINEA       smallint NOT NULL,
        CANT_DEVUELTA        DECIMAL(28,8) NOT NULL,
        CANT_DEVUELTAUA      DECIMAL(28,8) NOT NULL,
        MONTO_DEBITO         DECIMAL(28,8) NULL,
        MONTO_UN_LOCAL       DECIMAL(28,8) NULL,
        MONTO_UN_DOLAR       DECIMAL(28,8) NULL,
        ORDEN_COMPRA_LINEA   smallint NULL,
        IMPORTE              DECIMAL(28,8) NULL,
        DESCUENTO            DECIMAL(28,8) NULL,
        IMPUESTO1            DECIMAL(28,8) NULL,
        IMPUESTO2            DECIMAL(28,8) NULL,
        RUBRO1               DECIMAL(28,8) NULL,
        RUBRO2               DECIMAL(28,8) NULL,
        IMP1_AFECTACOSTO     VARCHAR(1) NOT NULL,
        IMP2_AFECTACOSTO     VARCHAR(1) NOT NULL,
        RUBRO1_AFECTACOSTO   VARCHAR(1) NOT NULL,
        RUBRO2_AFECTACOSTO   VARCHAR(1) NOT NULL,
        DESCUENTO_LINEA	     DECIMAL(28,8) NULL,
        BASE_IMPUESTO1	     DECIMAL(28,8) 	NULL,
	BASE_IMPUESTO2	     DECIMAL(28,8) 	NULL,
	IMP1_ASUMIDO_DESC	DECIMAL(28,8) 	NULL,
	IMP1_ASUMIDO_NODESC	DECIMAL(28,8) 	NULL,
	IMP1_RETENIDO_DESC	DECIMAL(28,8) 	NULL,
	IMP1_RETENIDO_NODESC	DECIMAL(28,8) 	NULL
)
go
 
 
 ALTER TABLE DEVOL_LIN_EMBARQUE
        ADD CONSTRAINT XPKDEVOL_LIN_EMBARQUE PRIMARY KEY (DEVOLUCION, 
               DEVOLUCION_LINEA)
go
 

CREATE TABLE DIRECCION_EMBARQUE (
         CODIGO_DIRECCION         VARCHAR(4)         NOT NULL,
         DESCRIPCION         VARCHAR(40)         NOT NULL,
         DIRECCION         TEXT         NOT NULL )
go         

ALTER TABLE DIRECCION_EMBARQUE
         ADD CONSTRAINT XPKDIRECCION_EMBAR PRIMARY KEY NONCLUSTERED
         (CODIGO_DIRECCION )
go  

 
 CREATE TABLE DEVOLUCION (
        DEVOLUCION           VARCHAR(50) NOT NULL,
        USUARIO_CREADO       VARCHAR(25) NOT NULL,
        AJUSTE_CONFIG        VARCHAR(4) NOT NULL,
        EMBARQUE             VARCHAR(10) NOT NULL,
        ESTADO               VARCHAR(1) NOT NULL,
        AUDIT_TRANS_INV      int NULL,
        TIPO_DEVOLUCION      VARCHAR(1) NOT NULL,
        FECHA_DEVOLUCION     DATETIME NOT NULL,
        AFECTA_ORDEN         VARCHAR(1) NOT NULL,
        DOCUMENTO_DEBITO     VARCHAR(1) NOT NULL,
        ASIENTO              VARCHAR(10) NULL,
        NOTAS                TEXT NULL,
        NUMERO_DEBITO        VARCHAR(20) NULL,
        SUBTIPO              smallint NULL,
        FECHA_DOCDEBITO     DATETIME NULL,
        APLICACION           VARCHAR(40) NULL,
        FECHA_HORA_CREADO    DATETIME NOT NULL,
        FECHA_HORA_APLIC     DATETIME NULL,
        FECHA_HORA_CANCELA   DATETIME NULL,
        USUARIO_APLICADO     VARCHAR(25) NULL,
        USUARIO_CANCELA      VARCHAR(25) NULL,
        MONEDA_DDEB	VARCHAR(4)	NULL,
		PROVEEDOR_DDEB	VARCHAR(20)	NULL,
		TC_MONEDA_LOCAL	DECIMAL(28,8)	NULL,
		TC_MONEDA_DOLAR	DECIMAL(28,8)	NULL,
		FECHA_CAI DATETIME NULL,
		CAI VARCHAR(50) NULL
 )
go
 
 
 ALTER TABLE DEVOLUCION
        ADD CONSTRAINT XPKDEVOLUCION PRIMARY KEY (DEVOLUCION)
go


CREATE TABLE DOCUMENTO_EMBARQUE (
	DOCUMENTO		VARCHAR(50)	NOT NULL,
	PROVEEDOR		VARCHAR(20)	NOT NULL,
	TIPO_DOCUMENTO		VARCHAR(1)	NOT NULL,
	PROCESADO_CP		VARCHAR(1)	NOT NULL,
	APLICACION		VARCHAR(249)	NOT NULL,
	CONDICION_PAGO		VARCHAR(4)	NOT NULL,
	FECHA_DOCUMENTO		DATETIME	NOT NULL,
	FECHA_RIGE		DATETIME	NOT NULL,
	MONEDA			VARCHAR(4)	NOT NULL,
	MONTO_DOCUMENTO		DECIMAL(28,8)	NOT NULL,
	SUBTIPO			SMALLINT	NOT NULL,
	FACTURA_CP		VARCHAR(50)	NULL,
	PORC_DESCUENTO		DECIMAL(28,8)	NULL,
	MONTO_IMPORTE		DECIMAL(28,8)	NULL,
	MONTO_DESCUENTO		DECIMAL(28,8)	NULL,
	MONTO_IMPUESTO1		DECIMAL(28,8)	NULL,
	MONTO_IMPUESTO2		DECIMAL(28,8)	NULL,
	TIPO_PRORRATEO		VARCHAR(2)	NULL,
	MONTO_FLETE		DECIMAL(28,8)	NULL,
	MONTO_SEGURO		DECIMAL(28,8)	NULL,
	MONTO_DOCUMENTACION	DECIMAL(28,8)	NULL,
	NOTAS 			TEXT		NULL,
	PAIS			VARCHAR(4) 	NULL,
	DIVISION_GEOGRAFICA1	VARCHAR(12)	NULL,
	DIVISION_GEOGRAFICA2	VARCHAR(12)	NULL,
	BASE_IMPUESTO1		DECIMAL(28,8) 	NULL,
	BASE_IMPUESTO2		DECIMAL(28,8) 	NULL,
	IMP1_ASUMIDO_DESC	DECIMAL(28,8) 	NULL,
	IMP1_ASUMIDO_NODESC	DECIMAL(28,8) 	NULL,
	IMP1_RETENIDO_DESC	DECIMAL(28,8) 	NULL,
	IMP1_RETENIDO_NODESC	DECIMAL(28,8) 	NULL,
	DOCUMENTO_FISCAL 	VARCHAR(50) 	NULL,
	CLASE_DOCUMENTO      	VARCHAR(1) 	NOT NULL DEFAULT 'N',
	PORC_INTCTE          	DECIMAL(28,8)	NOT NULL DEFAULT 0,
	CONTRATO             	VARCHAR(20)	NULL,
	NUM_PARCIALIDADES    	SMALLINT 	NOT NULL DEFAULT 0,
	TASA_IMPOSITIVA		VARCHAR(4)	NULL,
	TASA_IMPOSITIVA_PORC	DECIMAL(28,8)	NULL,
	TASA_CREE1		VARCHAR(4)	NULL,
	TASA_CREE1_PORC		DECIMAL(28,8)	NULL,
	TASA_CREE2		VARCHAR(4)	NULL,
	TASA_CREE2_PORC		DECIMAL(28,8)	NULL,
	TASA_GAN_OCASIONAL_PORC DECIMAL(28,8)	NULL,
	ASIENTO_FINANCIERO	VARCHAR(10)	NULL,
	FECHA_CONTA_FINANCIERA  DATETIME	NULL,
	FECHA_CONTA_FISCAL	DATETIME	NULL,
	TIPO_CAMBIO_MONEDA	DECIMAL(28,8)	NULL,
	TIPO_CAMBIO_DOLAR	DECIMAL(28,8)	NULL,
	TIPO_CAMBIO_PROV	DECIMAL(28,8)	NULL,
	MONEDA_CALCULADA	VARCHAR(4)	NULL,
	TC_MODIFICADO		VARCHAR(1)	NULL,
	FECHA_CAI DATETIME NULL,
	CAI VARCHAR(50) NULL
 )
 go
 
 ALTER TABLE DOCUMENTO_EMBARQUE 
 	ADD CONSTRAINT XPKEMBARQUEFACT PRIMARY KEY NONCLUSTERED (
 		PROVEEDOR, DOCUMENTO, TIPO_DOCUMENTO )
go 
 
 
 CREATE TABLE EMBARQUE (
        EMBARQUE             VARCHAR(10) NOT NULL,
        LIQUIDAC_COMPRA      VARCHAR(15) NULL,
        PROVEEDOR            VARCHAR(20) NULL,
        CRM                  VARCHAR(10) NULL,
        FECHA_REQUERIDA      DATETIME NULL,
        FECHA_OFRECIDA       DATETIME NULL,
        FECHA_EMBARQUE       DATETIME NULL,
        FECHA_A_CONSOL       DATETIME NULL,
        FECHA_DESDE_CONS     DATETIME NULL,
        FECHA_ADUANA         DATETIME NULL,
        FECHA_AGENCIA        DATETIME NULL,
        FECHA_TRAMITE        DATETIME NULL,
        FECHA_PLANTA         DATETIME NULL,
        ASIENTO_RECIBO       VARCHAR(1) NOT NULL,
        ASIENTO_LIQUIDACIO   VARCHAR(1) NOT NULL,
        NOTAS                TEXT NULL,
        ESTADO               VARCHAR(1) NOT NULL,
        USUARIO_CREADO       VARCHAR(25) NOT NULL,
        FECHA_HORA_CREADO    DATETIME NOT NULL,
        USUARIO_APLICADO     VARCHAR(25) NULL,
        FECHA_HORA_APLICAC   DATETIME NULL,
        ASIENTO              VARCHAR(10) NULL,
        LIQUIDADO            VARCHAR(1) NOT NULL,
        FECHA_HORA_LIQUIDA   DATETIME NULL,
        USUARIO_LIQUIDACIO   VARCHAR(25) NULL,
        ASIENTO_LIQ          VARCHAR(10) NULL,
        AUDIT_TRANS_INV      int NULL,
        AUDIT_TRANS_LIQ      int NULL,
        FECHA_CRM            DATETIME NULL,
        REFERENCIA           VARCHAR(20) NULL,
        TIENE_FACTURA        VARCHAR(1) NOT NULL,
        RECMAS_AFECTABACK    VARCHAR(1) NOT NULL,
        DEMAS_SEPAGA         VARCHAR(1) NOT NULL,
        RECIBIDO_DE_MAS      VARCHAR(1) NOT NULL,
        PEDIMENTO            VARCHAR(15) NULL,
        RUBRO1               VARCHAR(50) NULL,
        RUBRO2               VARCHAR(50) NULL,
        RUBRO3               VARCHAR(50) NULL,
        RUBRO4               VARCHAR(50) NULL,
        RUBRO5               VARCHAR(50) NULL,
        MULTIMONEDA	     VARCHAR(1)	 DEFAULT ('N')	NULL
              
 )
go
 
 
 ALTER TABLE EMBARQUE
        ADD CONSTRAINT EMBARQUEPK PRIMARY KEY NONCLUSTERED (EMBARQUE)
go
 
 
 CREATE TABLE EMBARQUE_IMP (
        EMBARQUE             VARCHAR(10) NOT NULL,
        USUARIO              VARCHAR(25) NOT NULL
 )
go
 
 
 ALTER TABLE EMBARQUE_IMP
        ADD CONSTRAINT XPKEMBARQUE_IMP PRIMARY KEY (EMBARQUE, USUARIO)
go
 
 
 CREATE TABLE EMBARQUE_LINEA (
        EMBARQUE             		VARCHAR(10) 	NOT NULL,
        EMBARQUE_LINEA       		smallint 	NOT NULL,
        ORDEN_COMPRA         		VARCHAR(10) 	NULL,
        ORDEN_COMPRA_LINEA   		smallint 	NULL,
        ARTICULO             		VARCHAR(20)	NOT NULL,
        BODEGA               		VARCHAR(4) 	NOT NULL,
        CANTIDAD_EMBARCADA   		DECIMAL(28,8) 	NOT NULL,
        CANTIDAD_RECIBIDA    		DECIMAL(28,8) 	NOT NULL,
        CANTIDAD_RECHAZADA   		DECIMAL(28,8) 	NOT NULL,
        PRECIO_UNITARIO      		DECIMAL(28,8) 	NOT NULL,
        COST_UN_FISC_LOCAL   		DECIMAL(28,8) 	NOT NULL,
        COST_UN_FISC_DOLAR   		DECIMAL(28,8) 	NOT NULL,
        COST_UN_ESTI_LOCAL   		DECIMAL(28,8) 	NOT NULL,
        COST_UN_ESTI_DOLAR   		DECIMAL(28,8) 	NOT NULL,
        COST_UN_REAL_LOCAL   		DECIMAL(28,8) 	NOT NULL,
        COST_UN_REAL_DOLAR   		DECIMAL(28,8) 	NOT NULL,
        PLAZO_REABAST        		smallint 	NOT NULL,
        PORC_AJUSTE_COSTO    		DECIMAL(28,8) 	NOT NULL,
        EXISTENCIA_TOT_ING   		DECIMAL(28,8) 	NOT NULL,
        CANT_RECIBIDA_UA     		DECIMAL(28,8) 	NULL,
        CANT_RECHAZADA_UA    		DECIMAL(28,8) 	NULL,
        CODIGO_ARANCEL       		VARCHAR(15) 	NULL,
        SUBTOTAL             		DECIMAL(28,8) 	NULL,
        DESCUENTO            		DECIMAL(28,8) 	NULL,
        IMPUESTO1            		DECIMAL(28,8) 	NULL,
        IMPUESTO2            		DECIMAL(28,8) 	NULL,
        RUBRO1               		DECIMAL(28,8) 	NULL,
        RUBRO2               		DECIMAL(28,8) 	NULL,
        IMP1_AFECTACOSTO     		VARCHAR(1) 	NULL,
        IMP2_AFECTACOSTO     		VARCHAR(1) 	NULL,
        RUBRO1_AFECTACOSTO   		VARCHAR(1) 	NULL,
        RUBRO2_AFECTACOSTO   		VARCHAR(1) 	NULL,
        RECIBIDO_DE_MAS      		VARCHAR(1) 	NOT NULL,
        SERIE_CADENA         		int 		NULL,
        CANTIDAD_DEVUELTA    		DECIMAL(28,8) 	NULL,
        CANT_DEVUELTAUA      		DECIMAL(28,8) 	NULL,
        UNIDAD_DISTRIBUCIO   		VARCHAR(6) 	NULL,
        CENTRO_COSTO         		VARCHAR(25)	NULL,
        CUENTA_CONTABLE      		VARCHAR(25)	NULL,
        UNIDAD_OPERATIVA     		VARCHAR(4) 	NULL,
        NUMERO         	     		int        	NULL,
        LINEA_APARTADO	     		int		NULL,
        CAMBIO_PRESUP        		VARCHAR(1) 	NULL,
        SECUENCIA            		DATETIME 	NULL,
        PROVEEDOR 	     		VARCHAR(20)	NULL,
	DOCUMENTO            		VARCHAR(50)	NULL,
	TIPO_DOCUMENTO       		VARCHAR(1) 	NULL,
	MONEDA_OC			VARCHAR(4)	NOT NULL,
	PRECIO_UNIT_OC_LOCAL		DECIMAL(28,8)	NULL,
	PRECIO_UNIT_OC_DOLAR		DECIMAL(28,8)	NULL,
	TC_PRECIO_OC_LOCAL		DECIMAL(28,8)	NULL,
	TC_PRECIO_OC_DOLAR		DECIMAL(28,8)	NULL,
	PRECIO_UNIT_DOC			DECIMAL(28,8)	NULL,
	TC_PRECIO_DOC_LOCAL		DECIMAL(28,8)	NULL,
	TC_PRECIO_DOC_DOLAR		DECIMAL(28,8)	NULL,
	PORC_DESC_UNITARIO		DECIMAL(28,8)   DEFAULT 0 NOT NULL, 
	MONTO_DESC_UNITARIO		DECIMAL(28,8)   DEFAULT 0 NOT NULL,
	DESCUENTO_LINEA			DECIMAL(28,8)   NULL,
	FASE                    	VARCHAR(25) 	NULL,
	PROYECTO                	VARCHAR(25) 	NULL,
	PAIS 				VARCHAR(4) 	NULL,
	TIPO 				VARCHAR(1) 	NULL,
	BASE_IMPUESTO1			DECIMAL(28,8) 	NULL,
	BASE_IMPUESTO2			DECIMAL(28,8) 	NULL,
	ORDEN_CAMBIO 			int 		NULL,
	IMP1_ASUMIDO_DESC		DECIMAL(28,8) 	NULL,
	IMP1_ASUMIDO_NODESC		DECIMAL(28,8) 	NULL,
	IMP1_RETENIDO_DESC		DECIMAL(28,8) 	NULL,
	IMP1_RETENIDO_NODESC		DECIMAL(28,8) 	NULL,
        CONCEPTO_ME			VARCHAR(4)  	NULL,
        COST_UN_COMP_LOCAL		DECIMAL(28,8)	NULL,
        COST_UN_COMP_DOLAR		DECIMAL(28,8)	NULL,
        COST_UN_ESTI_COMP_LOCAL		DECIMAL(28,8)	NULL,
        COST_UN_ESTI_COMP_DOLAR		DECIMAL(28,8)	NULL,
        COST_UN_REAL_COMP_LOCAL		DECIMAL(28,8)	NULL,
        COST_UN_REAL_COMP_DOLAR		DECIMAL(28,8)	NULL,
        MONTO_APLICADO_OC 		DECIMAL(28,8) 	NULL,
	BACKORDER_MONTO	  		VARCHAR(1)	NULL
 )
go
 
 
 ALTER TABLE EMBARQUE_LINEA
        ADD CONSTRAINT XPKEMBARQUE_DETALL PRIMARY KEY NONCLUSTERED (
               EMBARQUE, EMBARQUE_LINEA)
go


CREATE TABLE EMBARQUE_MOV_PRES(
	EMBARQUE 		VARCHAR (10) 	NOT NULL,
	ASIENTO 		VARCHAR (10) 	NULL,
	APARTADO 		INT 		NOT NULL,
	EJERCIDO 		INT 		NOT NULL
)
go
	
ALTER TABLE EMBARQUE_MOV_PRES ADD CONSTRAINT XPKEMBARQUE_MOV_PRES PRIMARY KEY NONCLUSTERED (EMBARQUE)
go


CREATE TABLE EVALPROV   (	
	PROVEEDOR 		VARCHAR(20) 	NOT NULL,
	NOTA_CRITERIO1 		DECIMAL(28,8) 	NULL,
	NOTA_CRITERIO2 		DECIMAL(28,8) 	NULL,
	NOTA_CRITERIO3 		DECIMAL(28,8) 	NULL,
	NOTA_CRITERIO4 		DECIMAL(28,8) 	NULL,
	NOTA_CRITERIO5 		DECIMAL(28,8) 	NULL,
	NOTA_CRITERIO6 		DECIMAL(28,8) 	NULL,
	NOTA_CRITERIO7 		DECIMAL(28,8) 	NULL,
	NOTA_CRITERIO8 		DECIMAL(28,8) 	NULL,
	NOTA_CRITERIO9 		DECIMAL(28,8) 	NULL,
	NOTA_CRITERIO10		DECIMAL(28,8) 	NULL,
	NOTA_PROVEEDOR 		DECIMAL(28,8) 	NULL,
	FECHA_APLICO_EVAL 	DATETIME 	NOT NULL,
	FECHA_PROX_APLICA 	DATETIME 	NOT NULL,
	COMENTARIO_PROV 	VARCHAR(200) 	NULL
)
go


ALTER TABLE EVALPROV  ADD CONSTRAINT PK_EVALPROV PRIMARY KEY NONCLUSTERED  ( PROVEEDOR )
go
	


CREATE TABLE EXCEPCION_ARANCEL_PAIS(
	CODIGO_ARANCEL 	VARCHAR(15) 	NOT NULL,
	PAIS 		VARCHAR(4) 	NOT NULL,
	TIPO 		VARCHAR(1) 	NOT NULL DEFAULT 'P'
)
go
	
ALTER TABLE EXCEPCION_ARANCEL_PAIS
	ADD CONSTRAINT PK_EXCEPCIONARANCELPAIS 
		PRIMARY KEY NONCLUSTERED ( CODIGO_ARANCEL, PAIS, TIPO )
go

CREATE TABLE EXCEPCION_ARANCEL_IMP(
	CODIGO_ARANCEL 	VARCHAR(15) 	NOT NULL,
	PAIS 		VARCHAR(4) 	NOT NULL,
	TIPO 		VARCHAR(1) 	NOT NULL,
	IMPUESTO_COMPRA VARCHAR(20) 	NOT NULL
)
go

ALTER TABLE EXCEPCION_ARANCEL_IMP
	ADD CONSTRAINT PK_EXCEPCIONARANCELIMP 
		PRIMARY KEY NONCLUSTERED ( CODIGO_ARANCEL, PAIS, TIPO, IMPUESTO_COMPRA )
go		


CREATE TABLE FACTURA_ADUANA_CMP (
	PROVEEDOR 		VARCHAR(20) 	NOT NULL,
	TIPO_DOCUMENTO 		VARCHAR(1) 	NOT NULL DEFAULT ('F'),
	FACTURA 		VARCHAR(50) 	NOT NULL,
	NUMERO_DUA 		VARCHAR(50) 	NULL,
	FECHA_DUA 		DATETIME 	NULL,
	PARTIDA_ARANCEL 	VARCHAR(50) 	NULL,
	DESC_PARTIDA_ARANCEL 	VARCHAR(80) 	NULL,
	ADUANA 			VARCHAR(80) 	NULL,
	NOMBRE_AGEN_ADUANA 	VARCHAR(80) 	NULL,
	PROVEEDOR_ADU	 	VARCHAR(20) 	NULL,
	NIT_AGEN_ADUANA 	VARCHAR(20) 	NULL,
	VALOR_ADUANA 		DECIMAL(28,8) 	NULL
)
go

ALTER TABLE FACTURA_ADUANA_CMP  
	ADD CONSTRAINT PK_FACTURA_ADUANA_CMP PRIMARY KEY CLUSTERED ( PROVEEDOR,TIPO_DOCUMENTO,FACTURA)
go


CREATE TABLE FIADORES_DOC_CO (
	FIADOR_ID        	VARCHAR(20)		NOT NULL,
	PROVEEDOR		VARCHAR(20)		NOT NULL,
	DOCUMENTO		VARCHAR(50)		NOT NULL,
	TIPO			VARCHAR(1)		NOT NULL  DEFAULT 'F',
	NOMBRE_FIADOR		VARCHAR(80)		NOT NULL,
	OCUPAC_FIADOR  		VARCHAR(30)		NULL,
	TIPO_FIADOR 		VARCHAR(20)		NULL,
	DIREC_FIADOR 		VARCHAR(80)		NULL,
	TEL_DOM_FIADOR 		VARCHAR(10)		NULL,
	LUG_TRAB_FIADOR 	VARCHAR(80)		NULL,
	DIR_TRAB_FIADOR  	VARCHAR(80)		NULL,
	TEL_TRAB_FIADOR 	VARCHAR(10)		NULL,
	CONTRATO_FIADOR  	VARCHAR(20)		NULL,
	OBS_FIADOR   		VARCHAR(200)		NULL 
)
go

ALTER TABLE FIADORES_DOC_CO
	ADD CONSTRAINT XPKFIADORCO PRIMARY KEY NONCLUSTERED 
         ( FIADOR_ID, PROVEEDOR, DOCUMENTO, TIPO )
go

CREATE TABLE FORMATO_PLANIFICACION(
	PLANIFICADOR				VARCHAR(10) NOT NULL,
	DESCRIPCION				VARCHAR(50) NULL,
	CONJUNTO				VARCHAR(10) NOT NULL,
	TIPO_PERIODO				VARCHAR(1) NOT NULL DEFAULT ('M'),
	FECHA_TRANSACCIONES			DATETIME NULL,
	BASE_SUGERENCIA				VARCHAR(1) NOT NULL DEFAULT ('M'),
	MOVIMIENTOS				VARCHAR(1) NOT NULL DEFAULT ('V'),
	TIEMPO_REAPROVISIONAMIENTO		INT NOT NULL,
	FRECUENCIA_PEDIDO			INT NOT NULL,
	INVENTARIO_SEGURIDAD			INT NOT NULL,
	CANTIDAD_PERIODOS			INT NOT NULL,
	ARTIC_CON_MOVIMIENTOS			VARCHAR(1) NOT NULL DEFAULT ('N'),
	DESPLEGAR_SIN_SUGERENCIA		VARCHAR(1) NOT NULL DEFAULT ('N'),
	SOLO_CON_EXISTENCIA			VARCHAR(1) NOT NULL DEFAULT ('N'),
	FECHA_BASE				VARCHAR(1) NOT NULL DEFAULT ('A'),
	CALCULAR_HASTA				VARCHAR(1) NOT NULL DEFAULT ('P'),
	COSTO					VARCHAR(1) NOT NULL DEFAULT ('F'),
	MONEDA					VARCHAR(1) NOT NULL DEFAULT ('L'),
	INCLUIR_CANT_TRANS			VARCHAR(1) NOT NULL DEFAULT ('S'),
	BODEGA_DESDE				VARCHAR(4) NULL,
	BODEGA_DESDE_DESC			VARCHAR(40) NULL,
	BODEGA_HASTA				VARCHAR(4) NULL,
	BODEGA_HASTA_DESC			VARCHAR(40) NULL,
	ESTADO					VARCHAR(1) NOT NULL DEFAULT ('N'),
	PERIODO_LEAD_TIME			VARCHAR(1) NOT NULL DEFAULT ('T'),
	ARTICULO_DESDE				VARCHAR(20) NULL,
	ARTICULO_DESDE_DESC			VARCHAR(254) NULL,
	ARTICULO_HASTA				VARCHAR(20) NULL,
	ARTICULO_HASTA_DESC			VARCHAR(254) NULL,
	PRONOSTICO_VENTAS			VARCHAR(20) NULL,
	PRONOSTICO_VENTAS_DESC			VARCHAR(40) NULL,
	GENERACION				VARCHAR(1) NOT NULL DEFAULT ('S'),
	TIPO_GRAFICO				VARCHAR(1) NOT NULL DEFAULT ('B'),
	SUGERIDO_EN_CERO			VARCHAR(1) NOT NULL DEFAULT ('N'),
	 PROVEEDOR_DESDE 		VARCHAR(20) NULL,
 PROVEEDOR_HASTA 		VARCHAR(20) NULL,
 PROVEEDOR_DESDE_DESC VARCHAR(254) NULL,
 PROVEEDOR_HASTA_DESC VARCHAR(254) NULL,
 CLASIFICACION_1_DESDE VARCHAR(12) NULL,
 CLASIFICACION_1_HASTA VARCHAR(12) NULL,
 CLASIFICACION_2_DESDE VARCHAR(12) NULL,
 CLASIFICACION_2_HASTA VARCHAR(12) NULL,
 CLASIFICACION_3_DESDE VARCHAR(12) NULL,
 CLASIFICACION_3_HASTA VARCHAR(12) NULL,
 CLASIFICACION_4_DESDE VARCHAR(12) NULL,
 CLASIFICACION_4_HASTA VARCHAR(12) NULL,
 CLASIFICACION_5_DESDE VARCHAR(12) NULL,
 CLASIFICACION_5_HASTA VARCHAR(12) NULL,
 CLASIFICACION_6_DESDE VARCHAR(12) NULL,
 CLASIFICACION_6_HASTA VARCHAR(12) NULL
)
go

ALTER TABLE FORMATO_PLANIFICACION  
	ADD CONSTRAINT PK_FORMATO_PLANIFICACION PRIMARY KEY NONCLUSTERED (PLANIFICADOR)
go

CREATE TABLE GARANTIAS_DOC_CO (
	GARANTIA_ID		VARCHAR(20)		NOT NULL,
	PROVEEDOR		VARCHAR(20)		NOT NULL,
	DOCUMENTO		VARCHAR(50)		NOT NULL,
	TIPO			VARCHAR(1)		NOT NULL DEFAULT 'F',
	TIPO_GARANTIA		VARCHAR(20)		NULL,
	DESC_GARANTIA		VARCHAR(40)		NULL,
	OBS_GARANTIA		VARCHAR(200)		NULL,
	ART_GARANTIA		VARCHAR(20)		NULL 
)
go

ALTER TABLE GARANTIAS_DOC_CO
	ADD CONSTRAINT XPKGARANTIACO PRIMARY KEY NONCLUSTERED
         ( GARANTIA_ID, PROVEEDOR, DOCUMENTO, TIPO )
go



 
 CREATE TABLE GASTO_COMPRA (
        GASTO_COMPRA         VARCHAR(10) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        TIPO_PRORRATEO       VARCHAR(2) NOT NULL
 )
go
 
 
 ALTER TABLE GASTO_COMPRA
        ADD CONSTRAINT XPKGASTO_COMPRA PRIMARY KEY (GASTO_COMPRA)
go
 
 
 CREATE TABLE GLOBALES_CO (
        DETALLE_DIR_EMB      	int 		NULL,
        TIPO_CAMBIO          	VARCHAR(4) 	NOT NULL,
        BODEGA_DEFAULT       	VARCHAR(4) 	NULL,
        ULT_SOLICITUD        	VARCHAR(10) 	NULL,
        ULT_ORDEN_COMPRA     	VARCHAR(10) 	NULL,
        ULT_EMBARQUE         	VARCHAR(10) 	NULL,
        ULT_CRM              	VARCHAR(10) 	NULL,
        ULT_SOLICITUD_M      	VARCHAR(10) 	NULL,
        ULT_ORDEN_COMPRA_M   	VARCHAR(10) 	NULL,
        ULT_EMBARQUE_M       	VARCHAR(10) 	NULL,
        USAR_RUBROS          	VARCHAR(1) 	NULL,
        RUBRO1_NOMBRE        	VARCHAR(15) 	NULL,
        RUBRO2_NOMBRE        	VARCHAR(15) 	NULL,
        RUBRO3_NOMBRE        	VARCHAR(15) 	NULL,
        RUBRO4_NOMBRE        	VARCHAR(15) 	NULL,
        RUBRO5_NOMBRE        	VARCHAR(15) 	NULL,
        PRECIO_DEC           	smallint 	NOT NULL,
        CANTIDAD_DEC         	smallint 	NOT NULL,
        MAX_PORC_AUMENTO     	DECIMAL(28,8) 	NOT NULL,
        IMP1_AFECTA_DESCTO   	VARCHAR(1) 	NOT NULL,
        FACTOR_REDONDEO      	DECIMAL(28,8) 	NOT NULL,
        DIRECCION_EMBARQUE   	TEXT 		NULL,
        DIRECCION_COBRO      	TEXT 		NULL,
        TRAER_LINEAS_NULAS   	VARCHAR(1) 	NULL,
        RECHAZ_AUMEN_BKORD   	VARCHAR(1) 	NULL,
        CONSOLIDAR_LINEAS    	VARCHAR(1) 	NULL,
        AGREGAR_INTERSECCI   	VARCHAR(1) 	NULL,
        TIPO_ASIENTO         	VARCHAR(4) 	NULL,
        PAQUETE              	VARCHAR(4) 	NULL,
        MOD_APLIC_ASIENTO    	smallint 	NOT NULL,
        INTEGRACION_CONTA    	VARCHAR(1) 	NOT NULL,
        TIPO_CONTA_OMISION   	VARCHAR(1) 	NOT NULL,
        CTR_TRANSITO_LOCAL   	VARCHAR(25) 	NULL,
        CTA_TRANSITO_LOCAL   	VARCHAR(25) 	NULL,
        CTR_TRANSITO_EXT     	VARCHAR(25) 	NULL,
        CTA_TRANSITO_EXT     	VARCHAR(25) 	NULL,
        TIPO_LIQ_OMISION     	VARCHAR(1) 	NOT NULL,
        POR_VARIAC_COSTO     	DECIMAL(28,8) 	NULL,
        PEDIDOS_SOLICITUD    	VARCHAR(1) 	NULL,
        PEDIDOS_ORDEN        	VARCHAR(1) 	NULL,
        PEDIDOS_EMBARQUE     	VARCHAR(1) 	NULL,
        EMBARQUE_PREVIO      	VARCHAR(1) 	NULL,
        ULT_LIQUIDACION      	VARCHAR(15) 	NULL,
        ULT_LIQUIDACION_M    	VARCHAR(15) 	NULL,
        OC_EN_DOS_MONEDAS    	VARCHAR(1) 	NOT NULL,
        ORDEN_OBSERVACION    	TEXT 		NULL,
        DETALLE_DIR_COB      	int 		NULL,
        PORCOSTO_ANTESIMP    	VARCHAR(1) 	NOT NULL,
        CP_EN_LINEA          	VARCHAR(1) 	NOT NULL,
        TIPO_PRORRATEO       	VARCHAR(2) 	NOT NULL,
        RECMAS_AFECTABACK    	VARCHAR(1) 	NOT NULL,
        DEMAS_SEPAGA         	VARCHAR(1) 	NOT NULL,
        ULT_DEVOLUCION       	VARCHAR(50) 	NULL,
        ULT_DEVOLUCION_M     	VARCHAR(50) 	NULL,
        CODIGO_DEVOLUCION    	VARCHAR(10) 	NULL,
        CONSECUTIVO_CI       	VARCHAR(1) 	NOT NULL,
        INTEGRACION_CR       	VARCHAR(1) 	NOT NULL,
        PAQUETE_CR   	     	VARCHAR(4) 	NULL,
        PRESUPUESTO_CR       	VARCHAR(20) 	NULL,
        CTR_CTA_COMPRAS      	VARCHAR(1) 	NOT NULL,
        PRORRATEO_OC_CR      	VARCHAR(2) 	NOT NULL,
        UNICO_CTR_OC         	VARCHAR(1) 	NOT NULL,
        PERMITE_SOBREGIRO    	VARCHAR(1) 	NOT NULL,
        RUBRO1_SOLNOM        	VARCHAR(15) 	NULL,
        RUBRO2_SOLNOM        	VARCHAR(15) 	NULL,
        RUBRO3_SOLNOM        	VARCHAR(15) 	NULL,
        RUBRO4_SOLNOM        	VARCHAR(15) 	NULL,
        RUBRO5_SOLNOM        	VARCHAR(15) 	NULL,
        RUBRO1_EMBNOM        	VARCHAR(15) 	NULL,
        RUBRO2_EMBNOM        	VARCHAR(15) 	NULL,
        RUBRO3_EMBNOM        	VARCHAR(15) 	NULL,
        RUBRO4_EMBNOM        	VARCHAR(15) 	NULL,
        RUBRO5_EMBNOM        	VARCHAR(15) 	NULL,
        APLICAR_NC           	VARCHAR(1)  	NULL,
        TIENE_FACTURA        	VARCHAR(1)  	NULL,
        MAXIMO_LINORDEN      	int 	 	NULL,
        IMP2_SE_AFECTA 	     	VARCHAR(1)  	NULL,
        PROM_RECALC_COSTO 	VARCHAR(1) 	NULL,
	PROM_RECALC_SIN_COSTO 	VARCHAR(1) 	NULL,
	CAPAS_CONT_VARIACION 	VARCHAR(1) 	NULL,
	CAPAS_APLIC_VARIACION 	VARCHAR(1) 	NULL,
	CAPAS_AFEC_CAPA_RESPEC 	VARCHAR(1) 	NULL,
	CAPAS_AFEC_PRIMER_CAPA 	VARCHAR(1) 	NULL,
        CAPAS_AFEC_OTRAS_CAPAS 	VARCHAR(1) 	NULL,
        SIMPLIFICA_COMPRA       VARCHAR(1) 	NULL,
        OC_TIPO_SUG_MONTOS 	VARCHAR(1) 	NULL,
	OC_PRORRATEAR_DIF_EMB 	VARCHAR(1) 	NULL,
	OC_DIFERENCIA_EN_OC 	VARCHAR(1) 	NULL,
	OC_ARTICULO_COMODIN 	VARCHAR(20) 	NULL,
	OC_PORC_VAR_ADV 	decimal(28, 8) 	NULL,
	OC_PORC_VAR_ERROR 	decimal(28, 8) 	NULL,
	OC_CONSOLI_VAL_LINEA	VARCHAR(1)	DEFAULT ('N')	NULL,
	OC_CONSOLI_VAL_GUARDAR	VARCHAR(1)	DEFAULT ('N')	NULL,
	OC_TIPO_SUG_TCANT	VARCHAR(1)	DEFAULT ('A')	NULL,
	APROBAR_OC_JERARQUIA	VARCHAR(1)	DEFAULT ('N')	NOT NULL,
	CANT_DIAS_ENV_NOTIF	int		DEFAULT (0)	NOT NULL,
	CRIT_EVAL_PROV1 	VARCHAR(25) 	NULL,
	CRIT_EVAL_PROV2 	VARCHAR(25) 	NULL,
	CRIT_EVAL_PROV3 	VARCHAR(25) 	NULL,
	CRIT_EVAL_PROV4 	VARCHAR(25) 	NULL,
	CRIT_EVAL_PROV5 	VARCHAR(25) 	NULL,
	CRIT_EVAL_PROV6 	VARCHAR(25) 	NULL,
	CRIT_EVAL_PROV7 	VARCHAR(25) 	NULL,
	CRIT_EVAL_PROV8 	VARCHAR(25) 	NULL,
	CRIT_EVAL_PROV9 	VARCHAR(25) 	NULL,
	CRIT_EVAL_PROV10 	VARCHAR(25) 	NULL,
	PESO_CRIT_EVAL_PROV1 	DECIMAL(28,8) 	NULL,
	PESO_CRIT_EVAL_PROV2 	DECIMAL(28,8) 	NULL,
	PESO_CRIT_EVAL_PROV3 	DECIMAL(28,8) 	NULL,
	PESO_CRIT_EVAL_PROV4 	DECIMAL(28,8) 	NULL,
	PESO_CRIT_EVAL_PROV5 	DECIMAL(28,8) 	NULL,
	PESO_CRIT_EVAL_PROV6 	DECIMAL(28,8) 	NULL,
	PESO_CRIT_EVAL_PROV7 	DECIMAL(28,8) 	NULL,
	PESO_CRIT_EVAL_PROV8 	DECIMAL(28,8) 	NULL,
	PESO_CRIT_EVAL_PROV9 	DECIMAL(28,8) 	NULL,
	PESO_CRIT_EVAL_PROV10 	DECIMAL(28,8) 	NULL,
	FREC_APLICA_EVAL_PROV 	DECIMAL(28,8) 	NULL,
	CRIT_PERMANENCIA 	DECIMAL(28,8) 	NULL,
	ESCALA_EVALUACION 	DECIMAL(28,8) 	NULL,
	SUGERIR_FECHA 		VARCHAR(1)	NOT NULL DEFAULT ('N')
 )
go

CREATE TABLE GLOBALES_SP(
	FORMULA				VARCHAR(1) 	NOT NULL DEFAULT 'S',
	ULT_FACTURA_LINEA 		DATETIME 	NOT NULL DEFAULT DATEADD(YEAR, -1, ERPADMIN.SF_GETDATE()),
	ULT_TRANSACCION_INV 		DATETIME 	NOT NULL DEFAULT DATEADD(YEAR, -1, ERPADMIN.SF_GETDATE()), 
	ULT_ORDEN_COMPRA 		DATETIME 	NOT NULL DEFAULT DATEADD(YEAR, -1, ERPADMIN.SF_GETDATE()), 
	ULT_ORDEN_COMPRA_LINEA 		DATETIME 	NOT NULL DEFAULT DATEADD(YEAR, -1, ERPADMIN.SF_GETDATE()),
	ULT_AUDIT_TRANS_INV 		DATETIME 	NOT NULL DEFAULT DATEADD(YEAR, -1, ERPADMIN.SF_GETDATE()),
	ULT_EMBARQUE 			DATETIME 	NOT NULL DEFAULT DATEADD(YEAR, -1, ERPADMIN.SF_GETDATE()),
	ULT_EMBARQUE_LINEA 		DATETIME 	NOT NULL DEFAULT DATEADD(YEAR, -1, ERPADMIN.SF_GETDATE()),
	USA_CONSUMO			VARCHAR(1) 	NOT NULL DEFAULT 'N',
	USA_ROTACION			VARCHAR(1) 	NOT NULL DEFAULT 'N',
	USA_FRECUENCIA			VARCHAR(1) 	NOT NULL DEFAULT 'N',
	USA_MARGEN			VARCHAR(1) 	NOT NULL DEFAULT 'N',
	PERIODICIDAD_ABC		VARCHAR(1) 	NOT NULL DEFAULT 'T',
	CATEG_CONSUMO			VARCHAR(1) 	NOT NULL DEFAULT 'A',
	CATEG_FRECUENCIA		VARCHAR(1) 	NOT NULL DEFAULT 'B',
	CATEG_ROTACION			VARCHAR(1) 	NOT NULL DEFAULT 'C',
	CATEG_MARGEN			VARCHAR(1) 	NOT NULL DEFAULT 'D',
	PORC_CONSUMO_A			INT 		NOT NULL DEFAULT 0,
	PORC_CONSUMO_B			INT 		NOT NULL DEFAULT 0,
	PORC_CONSUMO_C			INT 		NOT NULL DEFAULT 0,
	PORC_FRECUENCIA_A		INT 		NOT NULL DEFAULT 0,
	PORC_FRECUENCIA_B		INT 		NOT NULL DEFAULT 0,
	PORC_FRECUENCIA_C		INT 		NOT NULL DEFAULT 0,
	PORC_ROTACION_A			INT 		NOT NULL DEFAULT 0,
	PORC_ROTACION_B			INT 		NOT NULL DEFAULT 0,
	PORC_ROTACION_C			INT 		NOT NULL DEFAULT 0,
	PORC_MARGEN_A			INT 		NOT NULL DEFAULT 0,
	PORC_MARGEN_B			INT 		NOT NULL DEFAULT 0,
	PORC_MARGEN_C			INT 		NOT NULL DEFAULT 0,
	MODULO_INICIALIZADO		VARCHAR(1) 	NOT NULL DEFAULT 'N'
)
go
 
 CREATE TABLE IMPUESTO_COMPRA (
        IMPUESTO_COMPRA      VARCHAR(20) NOT NULL,
        DESCRIPCION          VARCHAR(40) NULL,
        FORMULA_OK           VARCHAR(1) NOT NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE IMPUESTO_COMPRA
        ADD CONSTRAINT XPKIMPUESTO_COMPRA PRIMARY KEY (
               IMPUESTO_COMPRA)
go
 
 
 CREATE TABLE IMPUESTO_DONDE (
        IMPUESTO_COMPRA      VARCHAR(20) NOT NULL,
        FORMULA_DONDE        TEXT NULL
 )
go
 
 
 ALTER TABLE IMPUESTO_DONDE
        ADD CONSTRAINT XPKIMPUESTODONDE PRIMARY KEY (IMPUESTO_COMPRA)
go
 
 
 CREATE TABLE IMPUESTO_EXPAND (
        IMPUESTO_COMPRA      VARCHAR(20) NOT NULL,
        FORMULA_EXPANDIDA    TEXT NOT NULL
 )
go
 
 
 ALTER TABLE IMPUESTO_EXPAND
        ADD CONSTRAINT XPKIMPUESTO_EXPAND PRIMARY KEY (
               IMPUESTO_COMPRA)
go
 
 
 CREATE TABLE IMPUESTO_FORMULA (
        IMPUESTO_COMPRA      VARCHAR(20) NOT NULL,
        FORMULA_ORIGINAL     TEXT NULL
 )
go
 
 
 ALTER TABLE IMPUESTO_FORMULA
        ADD CONSTRAINT XPKIMPUESTO_FORMULA PRIMARY KEY (
               IMPUESTO_COMPRA)
go
 
 
 CREATE TABLE LIQUIDAC_COMPRA (
        LIQUIDAC_COMPRA      VARCHAR(15) NOT NULL,
        PROVEEDOR_LIQUIDAC   VARCHAR(20) NULL,
        ESTADO_LIQUIDAC      VARCHAR(2) NOT NULL,
        FECHA_LIQUIDAC       DATETIME NOT NULL,
        REFERENCIA_LIQUID    VARCHAR(15) NULL,
        PRORRATEO_LIQUIDAC   VARCHAR(2) NOT NULL,
        TIPO_CAMBIO_DOLAR    DECIMAL(28,8) NULL,
        USUARIO_CREACION     VARCHAR(25) NOT NULL,
        FECHA_HORA_CREAC     DATETIME NOT NULL,
        USUARIO_CALCULO      VARCHAR(25) NULL,
        FECHA_HORA_CALCULO   DATETIME NULL,
        USUARIO_ULT_MODIF    VARCHAR(25) NULL,
        FEC_HORA_ULT_MODIF   DATETIME NULL,
        USUARIO_APROBACION   VARCHAR(25) NULL,
        FECHA_HORA_APROBAC   DATETIME NULL,
        USUARIO_CANCELA      VARCHAR(25) NULL,
        FECHA_HORA_CANCELA   DATETIME NULL,
        NOTAS                TEXT NULL,
        CALCULA_ARANCEL	     VARCHAR(1) NOT NULL,
        MONTO_FLETE_LOCAL    DECIMAL(28,8) NULL,
        MONTO_FLETE_DOLAR    DECIMAL(28,8) NULL,
        MONTO_SEGURO_LOCAL   DECIMAL(28,8) NULL,
        MONTO_SEGURO_DOLAR   DECIMAL(28,8) NULL,
        MONTO_OTROS_LOCAL    DECIMAL(28,8) NULL,
        MONTO_OTROS_DOLAR    DECIMAL(28,8) NULL,
        IMP_REAL_LOCAL       DECIMAL(28,8) NULL,
        IMP_REAL_DOLAR       DECIMAL(28,8) NULL        
 ) 
go
 
 
 ALTER TABLE LIQUIDAC_COMPRA
        ADD CONSTRAINT XPKLIQUIDAC_COMPRA PRIMARY KEY (
               LIQUIDAC_COMPRA)
go
 
 
 CREATE TABLE LIQUIDAC_DETALLE (
        LIQUIDAC_COMPRA      VARCHAR(15) NOT NULL,
        EMBARQUE             VARCHAR(10) NOT NULL,
        EMBARQUE_LINEA       smallint NOT NULL,
        LINEA                smallint NOT NULL,
        RUBRO                VARCHAR(20) NOT NULL,
        ETIQUETA             VARCHAR(20) NOT NULL,
        MONTO_LOCAL          DECIMAL(28,8) NOT NULL,
        MONTO_DOLAR          DECIMAL(28,8) NOT NULL
 )
go
 
 
 ALTER TABLE LIQUIDAC_DETALLE
        ADD CONSTRAINT XPKLIQUIDAC_DETALLE PRIMARY KEY (
               LIQUIDAC_COMPRA, EMBARQUE, EMBARQUE_LINEA, LINEA)
go
 
 
 CREATE TABLE LIQUIDAC_GASTO (
        LIQUIDAC_COMPRA      VARCHAR(15) 	NOT NULL,
        LINEA_GASTO          smallint 		NOT NULL,
        NIT                  VARCHAR(20) 	NULL,
        ARTICULO             VARCHAR(20) 	NULL,
        MONEDA               VARCHAR(4) 	NOT NULL,
        EMBARQUE             VARCHAR(10) 	NULL,
        GASTO_COMPRA         VARCHAR(10) 	NULL,
        SECUENCIA            smallint 		NULL,
        FECHA_GASTO          DATETIME 		NULL,
        DESCRIPCION          VARCHAR(40) 	NOT NULL,
        TIPO_PRORRATEO       VARCHAR(2) 	NULL,
        MONTO_GASTO          DECIMAL(28,8) 	NOT NULL,
        TIPO_CAMBIO_LOCAL    DECIMAL(28,8) 	NOT NULL,
        TIPO_CAMBIO_DOLAR    DECIMAL(28,8) 	NOT NULL,
        DESTINO              VARCHAR(2) 	NOT NULL,
        ETIQUETA             VARCHAR(20) 	NULL,
        LINEA_EMBARQUE       smallint 		NULL,
        TIPO_DOCUMENTO       VARCHAR(2)  	NOT NULL,
        FACTURA              VARCHAR(50) 	NULL,
        PROVEEDOR_FACTURA    VARCHAR(20) 	NULL        
 )
go
 
 
 ALTER TABLE LIQUIDAC_GASTO
        ADD CONSTRAINT XPKLIQUIDAC_GASTO PRIMARY KEY (LIQUIDAC_COMPRA, 
               LINEA_GASTO)
go
 
 
 CREATE TABLE LIQUIDAC_MENSAJE (
        LIQUIDAC_COMPRA      VARCHAR(15) NOT NULL,
        MENSAJE              TEXT NOT NULL
 )
go
 
 
 ALTER TABLE LIQUIDAC_MENSAJE
        ADD CONSTRAINT XPKLIQUIDAC_MENSAJE PRIMARY KEY (
               LIQUIDAC_COMPRA)
go
 
 
 CREATE TABLE ORDEN_COMPRA (
        ORDEN_COMPRA         	VARCHAR(10) 	NOT NULL,
        USUARIO              	VARCHAR(25) 	NULL,
        PROVEEDOR            	VARCHAR(20) 	NOT NULL,
        BODEGA               	VARCHAR(4) 	NOT NULL,
        CONDICION_PAGO       	VARCHAR(4) 	NOT NULL,
        MONEDA               	VARCHAR(4) 	NOT NULL,
        PAIS                 	VARCHAR(4) 	NOT NULL,
        RESPON_SEGUIMIENTO   	VARCHAR(10) 	NULL,
        MODULO_ORIGEN        	VARCHAR(4) 	NOT NULL,
        FECHA                	DATETIME 	NOT NULL,
        FECHA_COTIZACION     	DATETIME 	NULL,
        FECHA_OFRECIDA       	DATETIME 	NULL,
        FECHA_EMISION        	DATETIME 	NULL,
        FECHA_REQ_EMBARQUE   	DATETIME 	NULL,
        FECHA_REQUERIDA      	DATETIME 	NOT NULL,
        DIRECCION_EMBARQUE   	VARCHAR(250) 	NULL,
        DIRECCION_COBRO      	VARCHAR(250) 	NULL,
        TIPO_DESCUENTO       	VARCHAR(1) 	NOT NULL,
        PORC_DESCUENTO       	Decimal(28,8) 	NOT NULL,
        MONTO_DESCUENTO      	DECIMAL(28,8) 	NULL,
        TOTAL_MERCADERIA     	DECIMAL(28,8) 	NOT NULL,
        TOTAL_IMPUESTO1      	DECIMAL(28,8) 	NOT NULL,
        TOTAL_IMPUESTO2      	DECIMAL(28,8) 	NOT NULL,
        MONTO_FLETE          	DECIMAL(28,8) 	NOT NULL,
        MONTO_SEGURO         	DECIMAL(28,8) 	NOT NULL,
        MONTO_DOCUMENTACIO   	DECIMAL(28,8) 	NOT NULL,
        MONTO_ANTICIPO       	DECIMAL(28,8) 	NOT NULL,
        TOTAL_A_COMPRAR      	DECIMAL(28,8) 	NOT NULL,
        RUBRO1               	VARCHAR(50) 	NULL,
        RUBRO2               	VARCHAR(50) 	NULL,
        RUBRO3               	VARCHAR(50) 	NULL,
        RUBRO4               	VARCHAR(50) 	NULL,
        RUBRO5               	VARCHAR(50) 	NULL,
        PRIORIDAD            	VARCHAR(1) 	NOT NULL,
        ESTADO               	VARCHAR(1) 	NOT NULL,
        IMPRESA              	VARCHAR(1) 	NOT NULL,
        NUM_FORMULARIO       	VARCHAR(10) 	NULL,
        INSTRUCCIONES        	VARCHAR(250) 	NULL,
        COMENTARIO_CXP       	VARCHAR(40) 	NULL,
        FECHA_HORA           	DATETIME 	NOT NULL,
        OBSERVACIONES        	TEXT 		NULL,
        REQUIERE_CONFIRMA    	VARCHAR(1) 	NOT NULL,
        CONFIRMADA           	VARCHAR(1) 	NOT NULL,
        USUARIO_CONFIRMA     	VARCHAR(25) 	NULL,
        FECHA_HORA_CONFIR    	DATETIME 	NULL,
        USUARIO_CIERRE       	VARCHAR(25) 	NULL,
        FECHA_HORA_CIERRE    	DATETIME 	NULL,
        ASIENTO_CIERRE       	VARCHAR(10) 	NULL,
        ORDEN_PROGRAMADA     	VARCHAR(1) 	NOT NULL,
        RECIBIDO_DE_MAS      	VARCHAR(1) 	NOT NULL,
        FECHA_HORA_CANCELA   	DATETIME 	NULL,
        USUARIO_CANCELA      	VARCHAR(25) 	NULL,
        TIPO_PRORRATEO_OC    	VARCHAR(2) 	NULL,
        PRESUPUESTO_CR       	VARCHAR(20) 	NULL,
        COD_DIREC_EMB        	VARCHAR(4) 	NULL,
        NOTAS_NOAPROBAR      	VARCHAR(250) 	NULL,
        DEPARTAMENTO	     	VARCHAR(10)	NULL,
	FECHA_ULT_NOTIF	     	DATETIME	NULL,
	BASE_IMPUESTO1	     	DECIMAL(28,8) 	NULL,
	BASE_IMPUESTO2	     	DECIMAL(28,8) 	NULL,
	TOT_IMP1_ASUM_DESC	DECIMAL(28,8) 	NULL,
	TOT_IMP1_ASUM_NODESC	DECIMAL(28,8) 	NULL,
	TOT_IMP1_RETE_DESC	DECIMAL(28,8) 	NULL,
	TOT_IMP1_RETE_NODESC	DECIMAL(28,8) 	NULL,
	FECHA_NO_APRUEBA 	DATETIME 	NULL,
	USUARIO_NO_APRUEBA 	VARCHAR(25) 	NULL
 )
go
 
 
 ALTER TABLE ORDEN_COMPRA
        ADD CONSTRAINT XPKORDEN_COMPRA PRIMARY KEY NONCLUSTERED (
               ORDEN_COMPRA)
go
 
 
 CREATE TABLE ORDEN_COMPRA_IMP (
        ORDEN_COMPRA         VARCHAR(10) NOT NULL,
        USUARIO              VARCHAR(25) NOT NULL
 )
go
 
 
 ALTER TABLE ORDEN_COMPRA_IMP
        ADD CONSTRAINT XPKE_319 PRIMARY KEY (ORDEN_COMPRA, USUARIO)
go
 
 
 CREATE TABLE ORDEN_COMPRA_LINEA (
        ORDEN_COMPRA         		VARCHAR(10) 	NOT NULL,
        ORDEN_COMPRA_LINEA   		smallint 	NOT NULL,
        ARTICULO             		VARCHAR(20) 	NOT NULL,
        BODEGA               		VARCHAR(4) 	NOT NULL,
        LINEA_USUARIO        		smallint 	NOT NULL,
        DESCRIPCION          		TEXT 		NULL,
        CANTIDAD_ORDENADA    		DECIMAL(28,8) 	NOT NULL,
        CANTIDAD_EMBARCADA   		DECIMAL(28,8) 	NOT NULL,
        CANTIDAD_RECIBIDA    		DECIMAL(28,8) 	NOT NULL,
        CANTIDAD_RECHAZADA   		DECIMAL(28,8) 	NOT NULL,
        PRECIO_UNITARIO      		DECIMAL(28,8) 	NOT NULL,
        IMPUESTO1            		DECIMAL(28,8) 	NOT NULL,
        IMPUESTO2            		DECIMAL(28,8) 	NOT NULL,
        TIPO_DESCUENTO       		VARCHAR(1) 	NOT NULL,
        PORC_DESCUENTO       		Decimal(28,8) 	NOT NULL,
        MONTO_DESCUENTO      		DECIMAL(28,8) 	NOT NULL,
        FECHA                		DATETIME 	NOT NULL,
        ESTADO               		VARCHAR(1) 	NOT NULL,
        COMENTARIO           		VARCHAR(250) 	NULL,
        FACTOR_CONVERSION    		DECIMAL(28,8) 	NULL,
        FECHA_REQUERIDA      		DATETIME 	NOT NULL,
        FEC_EMBARQUE_PROV    		DATETIME 	NULL,
        DIAS_PARA_ENTREGA    		smallint 	NULL,
        FACTURA              		VARCHAR(50) 	NULL,
        UNIDAD_DISTRIBUCIO   		VARCHAR(6) 	NULL,
        USUARIO_CANCELA      		VARCHAR(25) 	NULL,
        FECHA_HORA_CANCELA   		DATETIME 	NULL,
        FECHA_HORA_CIERRE    		DATETIME 	NULL,
        USUARIO_CIERRE       		VARCHAR(25) 	NULL,
        CENTRO_COSTO         		VARCHAR(25)  	NULL,
        CUENTA_CONTABLE      		VARCHAR(25)  	NULL,
        E_MAIL         	     		VARCHAR(250) 	NULL,
        CANTIDAD_ACEPTADA    		DECIMAL(28,8)	NULL,
        LOCALIZACION 	     		VARCHAR(8) 	NULL,
	LOTE	 	     		VARCHAR(15) 	NULL,
	IMP2_POR_CANTIDAD    		VARCHAR(1) 	NULL,
	FASE                 		VARCHAR(25) 	NULL,
	PROYECTO             		VARCHAR(25) 	NULL,
	SERIE_CADENA 	     		int 		NULL,
	IMP1_AFECTA_COSTO		VARCHAR(1) 	NOT NULL DEFAULT('N'),
	IMP1_ASUMIDO_DESC		DECIMAL(28,8) 	NULL,
	IMP1_ASUMIDO_NODESC		DECIMAL(28,8) 	NULL,
	IMP1_RETENIDO_DESC		DECIMAL(28,8) 	NULL,
	IMP1_RETENIDO_NODESC		DECIMAL(28,8) 	NULL,
	ORDEN_CAMBIO 			INT 		NULL,
	PRECIO_ART_PROV 		DECIMAL(28,8) 	NOT NULL DEFAULT (0),
        CONCEPTO_ME			VARCHAR(4)  	NULL,
        MONTO_APLICADO 			DECIMAL(28,8) 	NULL
 )
go
 
 
 ALTER TABLE ORDEN_COMPRA_LINEA
        ADD CONSTRAINT XPKORDEN_DETALLE PRIMARY KEY NONCLUSTERED (
               ORDEN_COMPRA, ORDEN_COMPRA_LINEA)
go
 
 
CREATE TABLE ORDEN_MOV_PRES (
         ORDEN_COMPRA         	VARCHAR(10)	NOT NULL,
         PRESUPUESTO         	VARCHAR(20)     NOT NULL,
         UNIDAD_OPERATIVA	VARCHAR(4)      NOT NULL,
         NUMERO         	int         	NOT NULL )
go


ALTER TABLE ORDEN_MOV_PRES
         ADD CONSTRAINT XPKORDEN_MOV_PRES PRIMARY KEY NONCLUSTERED
         (ORDEN_COMPRA, NUMERO )
go   


CREATE TABLE PARCIALIDADES_CO (
	PROVEEDOR			VARCHAR(20)	NOT NULL,
	TIPO_DOC_ORIGEN			VARCHAR(1)	NOT NULL 	DEFAULT 'F',
	DOCUMENTO_ORIGEN		VARCHAR(50)	NOT NULL,
	PARCIALIDAD			SMALLINT	NOT NULL,
	FECHA_RIGE			DATETIME	NOT NULL,
	FECHA_VENCE			DATETIME	NOT NULL,
	PORCENTAJE			DECIMAL(28,8)	NOT NULL,
	SALDO				DECIMAL(28,8)	NOT NULL,
	SALDO_LOCAL			DECIMAL(28,8)	NOT NULL,
	SALDO_DOLAR			DECIMAL(28,8)	NOT NULL,
	MONTO_PRINCIPAL			DECIMAL(28,8)	NULL,
	MONTO_PRINCIPAL_LOC		DECIMAL(28,8)	NULL,
	MONTO_PRINCIPAL_DOL		DECIMAL(28,8)	NULL,
	MONTO_AMORTIZA			DECIMAL(28,8)	NULL,
	MONTO_AMORTIZA_LOC		DECIMAL(28,8)	NULL,
	MONTO_AMORTIZA_DOL		DECIMAL(28,8)	NULL,
	SALDO_AMORTIZA			DECIMAL(28,8)	NULL,
	SALDO_AMORTIZA_LOC		DECIMAL(28,8)	NULL,
	SALDO_AMORTIZA_DOL		DECIMAL(28,8)	NULL,
	MONTO_INTERES			DECIMAL(28,8)	NULL,
	MONTO_INTERES_LOC		DECIMAL(28,8)	NULL,
	MONTO_INTERES_DOL		DECIMAL(28,8)	NULL,
	SALDO_INTERES			DECIMAL(28,8)	NULL,
	SALDO_INTERES_LOC		DECIMAL(28,8)	NULL,
	SALDO_INTERES_DOL		DECIMAL(28,8)	NULL,
	MONTO_CUOTA			DECIMAL(28,8)	NULL,
	MONTO_CUOTA_LOC			DECIMAL(28,8)	NULL,
	MONTO_CUOTA_DOL			DECIMAL(28,8)	NULL,
	SALDO_CUOTA			DECIMAL(28,8)	NULL,
	SALDO_CUOTA_LOC			DECIMAL(28,8)	NULL,
	SALDO_CUOTA_DOL			DECIMAL(28,8)	NULL,
	SALDO_PRINCIPAL			DECIMAL(28,8)	NULL,
	SALDO_PRINCIPAL_LOC		DECIMAL(28,8)	NULL,
	SALDO_PRINCIPAL_DOL		DECIMAL(28,8)	NULL,
	FECHA_PROYECTADA		DATETIME	NULL,
	MONTO_IMP_RENTA			DECIMAL(28, 8)	NULL,
	MONTO_IMP_RENTA_LOCAL		DECIMAL(28, 8)	NULL,
	MONTO_IMP_RENTA_DOLAR		DECIMAL(28, 8)	NULL,
	MONTO_IMP_CREE1			DECIMAL(28, 8)	NULL,
	MONTO_IMP_CREE1_LOCAL		DECIMAL(28, 8)	NULL,
	MONTO_IMP_CREE1_DOLAR		DECIMAL(28, 8)	NULL,
	MONTO_IMP_CREE2			DECIMAL(28, 8)	NULL,
	MONTO_IMP_CREE2_LOCAL		DECIMAL(28, 8)	NULL,
	MONTO_IMP_CREE2_DOLAR		DECIMAL(28, 8)	NULL,
	MONTO_GAN_OCASIONAL		DECIMAL(28, 8)	NULL,
	MONTO_GAN_OCASIONAL_LOCAL 	DECIMAL(28, 8) 	NULL,
	MONTO_GAN_OCASIONAL_DOLAR 	DECIMAL(28, 8) 	NULL
 )
go

 ALTER TABLE PARCIALIDADES_CO
        ADD CONSTRAINT XPKPARCIALIDADES_CO PRIMARY KEY ( PROVEEDOR, TIPO_DOC_ORIGEN, DOCUMENTO_ORIGEN, PARCIALIDAD )
go



 CREATE TABLE PEDIDO_SUGERIDO (
        PROVEEDOR            VARCHAR(20) 	NOT NULL,
        ARTICULO             VARCHAR(20) 	NOT NULL,
        FECHA_HORA_GENERAC   DATETIME 		NOT NULL,
        ESTADO               VARCHAR(1) 	NOT NULL,
        CLASIFICACION1       VARCHAR(12) 	NULL,
        CLASIFICACION2       VARCHAR(12) 	NULL,
        CLASIFICACION3       VARCHAR(12) 	NULL,
        CLASIFICACION4       VARCHAR(12) 	NULL,
        CLASIFICACION5       VARCHAR(12) 	NULL,
        CLASIFICACION6       VARCHAR(12) 	NULL,
        CONSUMO_PROMEDIO     DECIMAL(28,8) 	NOT NULL,
        INVENTARIO_ACTUAL    DECIMAL(28,8) 	NOT NULL,
        INVENTARIO_MAXIMO    DECIMAL(28,8) 	NOT NULL,
        INVENTARIO_TRANSIT   DECIMAL(28,8) 	NOT NULL,
        PRECIO_UNITARIO      DECIMAL(28,8) 	NOT NULL,
        REFERENCIA_PEDIDO    DECIMAL(28,8) 	NOT NULL,
        PRECIO_TOTAL         DECIMAL(28,8) 	NOT NULL,
        CANTIDAD_SUGERIDA    DECIMAL(28,8) 	NOT NULL,
	CANT_SUG_AJUSTADA    DECIMAL(28,8) 	NOT NULL, 
        USUARIO_GENERACION   VARCHAR(25) 	NOT NULL,
        USUARIO_SOLICITUD    VARCHAR(25) 	NULL,
        FECHA_HORA_SOLICIT   DATETIME 		NULL,
        SOLICITUD_OC         VARCHAR(10) 	NULL
 )
 go
 
       
ALTER TABLE PEDIDO_SUGERIDO
         ADD CONSTRAINT XPKPEDIDO_SUGERIDO PRIMARY KEY NONCLUSTERED
         (PROVEEDOR, ARTICULO, FECHA_HORA_GENERAC )     
go

CREATE TABLE PRECIO_ART_PROV (
         ARTICULO        VARCHAR(20)         NOT NULL,
         PROVEEDOR       VARCHAR(20)         NOT NULL,
         LINEA           SMALLINT            NOT NULL,
         CANTIDAD_HASTA  DECIMAL(28,8)       NOT NULL,
         PRECIO          DECIMAL(28,8)       NOT NULL )
go



ALTER TABLE PRECIO_ART_PROV
         ADD CONSTRAINT XPKPRECIO_ART_PROV PRIMARY KEY NONCLUSTERED
         (ARTICULO, PROVEEDOR, LINEA )
go         
 
 CREATE TABLE PROVEEDOR (
        PROVEEDOR            VARCHAR(20) 	NOT NULL,
        DETALLE_DIRECCION    int 		NULL,
        NOMBRE 				 VARCHAR(150) NOT NULL,
        ALIAS 				 VARCHAR(150) NULL,
        CONTACTO             VARCHAR(30) 	NOT NULL,
        CARGO                VARCHAR(30) 	NOT NULL,
        DIRECCION            TEXT 		NOT NULL,
        E_MAIL               VARCHAR(249) 	NULL,
        FECHA_INGRESO        DATETIME 		NOT NULL,
        FECHA_ULT_MOV        DATETIME 		NOT NULL,
        TELEFONO1            VARCHAR(50) 	NOT NULL,
        TELEFONO2            VARCHAR(50) 	NOT NULL,
        FAX                  VARCHAR(50) 	NOT NULL,
        ORDEN_MINIMA         DECIMAL(28,8) 	NOT NULL,
        DESCUENTO            DECIMAL(28,8) 	NOT NULL,
        TASA_INTERES_MORA    DECIMAL(28,8) 	NULL,
        LOCAL                VARCHAR(1) 	NOT NULL,
        CONGELADO            VARCHAR(1) 	NOT NULL,
        CONTRIBUYENTE        VARCHAR(20) 	NOT NULL,
        CONDICION_PAGO       VARCHAR(4) 	NOT NULL,
        MONEDA               VARCHAR(4) 	NOT NULL,
        PAIS                 VARCHAR(4) 	NOT NULL,
        CATEGORIA_PROVEED    VARCHAR(8) 	NOT NULL,
        MULTIMONEDA          VARCHAR(1) 	NOT NULL,
        SALDO                DECIMAL(28,8) 	NOT NULL,
        SALDO_LOCAL          DECIMAL(28,8) 	NOT NULL,
        SALDO_DOLAR          DECIMAL(28,8) 	NOT NULL,
        NOTAS                TEXT        	NULL,
        RUBRO1_PROV          VARCHAR(50) 	NULL,
        RUBRO2_PROV          VARCHAR(50) 	NULL,
        RUBRO3_PROV          VARCHAR(50) 	NULL,
        RUBRO4_PROV          VARCHAR(50) 	NULL,
        RUBRO5_PROV          VARCHAR(50) 	NULL,
        RUBRO1_PROVEEDOR     VARCHAR(40) 	NULL,
        RUBRO2_PROVEEDOR     VARCHAR(40) 	NULL,
        RUBRO3_PROVEEDOR     VARCHAR(40) 	NULL,
        RUBRO4_PROVEEDOR     VARCHAR(40) 	NULL,
        RUBRO5_PROVEEDOR     VARCHAR(40) 	NULL,
		GLN 		     VARCHAR(13) 	NULL,
		UBICACION 	     VARCHAR(50) 	NULL,
		ACTIVO		     VARCHAR(1)  	NOT NULL,
		TIPO_CONTRIBUYENTE   VARCHAR(1)  	NULL,
		RUBRO6_PROVEEDOR     VARCHAR(40) 	NULL,
		RUBRO7_PROVEEDOR     VARCHAR(40) 	NULL,
		RUBRO8_PROVEEDOR     VARCHAR(40) 	NULL,
		RUBRO9_PROVEEDOR     VARCHAR(40) 	NULL,
		RUBRO10_PROVEEDOR    VARCHAR(40) 	NULL,
		MODELO_RETENCION     VARCHAR(4)  	NULL,
		CODIGO_IMPUESTO      VARCHAR(4)         NULL,
		DIVISION_GEOGRAFICA1	VARCHAR(12)	NULL,
		DIVISION_GEOGRAFICA2	VARCHAR(12)	NULL,
		AUTORETENEDOR		VARCHAR(1)	NOT NULL DEFAULT 'N',
		REGIMEN_TRIB		VARCHAR(12)	NULL,
		SALDO_TRANS 		DECIMAL(28,8) 	DEFAULT 0 	NOT NULL,
		SALDO_TRANS_LOCAL 	DECIMAL(28,8) 	DEFAULT 0 	NOT NULL,
		SALDO_TRANS_DOLAR 	DECIMAL(28,8) 	DEFAULT 0 	NOT NULL,
		PERMITE_DOC_GP		VARCHAR(1) 	DEFAULT 'N' 	NOT NULL,
		PARTICIPA_FLUJOCAJA	VARCHAR(1)	DEFAULT 'N'	NOT NULL, 
		CURP  			VARCHAR(18)   	NULL,
		USUARIO_CREACION	VARCHAR(25)	NULL,
		FECHA_HORA_CREACION	DATETIME	NULL,
		USUARIO_ULT_MOD		VARCHAR(25)	NULL,
		FCH_HORA_ULT_MOD	DATETIME	NULL,
		IMPUESTO1_INCLUIDO 	VARCHAR(1) 	NOT NULL DEFAULT ('N'),
		XSLT_PERSONALIZADO 		VARCHAR(50) 	NULL,
		UBICACIONDOCELECTRONICO 	VARCHAR(10)	NULL,
		EMAIL_DOC_ELECTRONICO 		VARCHAR(249) 	NULL,
		EMAIL_DOC_ELECTRONICO_COPIA 	VARCHAR(249) 	NULL,
		ACEPTA_DOC_ELECTRONICO 		VARCHAR(1) 	DEFAULT ('N') NOT NULL,
		INTERNACIONES VARCHAR(1) NOT NULL DEFAULT 'N'
 )
go
 
 
 ALTER TABLE PROVEEDOR
        ADD CONSTRAINT PROVEEDORPK PRIMARY KEY NONCLUSTERED (
               PROVEEDOR)
go
 
 
 CREATE TABLE PROVEEDOR_ENTIDAD (
        PROVEEDOR            VARCHAR(20) NOT NULL,
        ENTIDAD_FINANCIERA   VARCHAR(8)  NOT NULL,
        CUENTA_BANCO         VARCHAR(20) NOT NULL,
        NOTAS                TEXT 	 NULL,
        MONEDA               VARCHAR(4)  NOT NULL,
        CTA_DEFAULT 	     VARCHAR(1)  NULL,
        TIPO_CUENTA	     	 VARCHAR(12) NULL,
        CTA_ELECTRONICA 	 VARCHAR(50) NULL
 )
go
 
 
 ALTER TABLE PROVEEDOR_ENTIDAD
        ADD CONSTRAINT PROVEEDOR_ENTIDPK PRIMARY KEY NONCLUSTERED (
               PROVEEDOR, ENTIDAD_FINANCIERA, MONEDA)
go
 
 
CREATE TABLE RANGOS_AUTORIZA_DEP(
	DEPARTAMENTO 		VARCHAR(10) 		NOT NULL,
	CONSEC_DEP		INTEGER IDENTITY(1,1) 	NOT NULL,
	MONTO_MAX_COMPRA 	DECIMAL(28, 8) 		NOT NULL DEFAULT (0),
	CANT_AUTORIZ_REQ 	INT 			NOT NULL DEFAULT (1)	
)
go

ALTER TABLE RANGOS_AUTORIZA_DEP
        ADD CONSTRAINT PK_RANGOS_AUTORIZA_DEP 
        	PRIMARY KEY NONCLUSTERED (DEPARTAMENTO, CONSEC_DEP)
go

 
 CREATE TABLE RESPON_SEGUIMIENTO (
        RESPON_SEGUIMIENTO   	VARCHAR(10) 		NOT NULL,
        EMPLEADO             	VARCHAR(20) 		NULL,
        ESTADO               	VARCHAR(1) 		NOT NULL,
        NOTAS                	TEXT 			NULL,
	TELEFONO 	     	VARCHAR(20)  		NULL,
	CORREO_ELECT 	     	VARCHAR(250) 		NULL      
 )
go
 
 
 ALTER TABLE RESPON_SEGUIMIENTO
        ADD CONSTRAINT XPKENCARGADO_COMPR PRIMARY KEY NONCLUSTERED (
               RESPON_SEGUIMIENTO)
go
 
 
CREATE TABLE SEGUIMIENTO_ORDEN (
         CONSECUTIVO    INT          NOT NULL,
         ORDEN_COMPRA   VARCHAR(10)  NOT NULL,
         ESTADO         VARCHAR(1)   NOT NULL,
         DESCRIPCION    VARCHAR(50)  NULL,
         MEDIO          VARCHAR(1)   NOT NULL,
         FUENTE         VARCHAR(25)  NOT NULL 
)
go


 CREATE TABLE SOLICITUD_OC (
        SOLICITUD_OC         VARCHAR(10) 	NOT NULL,
        DEPARTAMENTO         VARCHAR(10) 	NOT NULL,
        FECHA_SOLICITUD      DATETIME 		NOT NULL,
        FECHA_REQUERIDA      DATETIME 		NOT NULL,
        AUTORIZADA_POR       VARCHAR(25) 	NULL,
        FECHA_AUTORIZADA     DATETIME 		NULL,
        PRIORIDAD            VARCHAR(1) 	NOT NULL,
        LINEAS_NO_ASIG       smallint 		NOT NULL,
        ESTADO               VARCHAR(1) 	NOT NULL,
        COMENTARIO           TEXT 		NULL,
        FECHA_HORA           DATETIME 		NOT NULL,
        USUARIO              VARCHAR(25)	NULL,
        USUARIO_CANCELA      VARCHAR(25)	NULL,
        FECHA_HORA_CANCELA   DATETIME 		NULL,
        RUBRO1               VARCHAR(50)	NULL,
        RUBRO2               VARCHAR(50)	NULL,
        RUBRO3               VARCHAR(50)	NULL,
        RUBRO4               VARCHAR(50)	NULL,
        RUBRO5               VARCHAR(50)	NULL        
 )
go
 
 
 ALTER TABLE SOLICITUD_OC
        ADD CONSTRAINT XPKSOLICITUD_OC PRIMARY KEY NONCLUSTERED (
               SOLICITUD_OC)
go
 
 
 CREATE TABLE SOLICITUD_OC_IMP (
        SOLICITUD_OC         VARCHAR(10) NOT NULL,
        USUARIO              VARCHAR(25) NOT NULL
 )
go
 
 
 ALTER TABLE SOLICITUD_OC_IMP
        ADD CONSTRAINT XPKSOLICITUDES_IMP PRIMARY KEY NONCLUSTERED (
               SOLICITUD_OC, USUARIO)
go
 
 
 CREATE TABLE SOLICITUD_OC_LINEA (
        SOLICITUD_OC         	VARCHAR(10) 	NOT NULL,
        SOLICITUD_OC_LINEA   	smallint 	NOT NULL,
        USUARIO_CANCELA      	VARCHAR(25) 	NULL,
        ARTICULO             	VARCHAR(20) 	NOT NULL,
        DESCRIPCION          	TEXT 		NULL,
        CANTIDAD             	DECIMAL(28,8) 	NOT NULL,
        SALDO                	DECIMAL(28,8) 	NULL,
        ESTADO               	VARCHAR(1) 	NOT NULL,
        COMENTARIO           	VARCHAR(250) 	NULL,
        FECHA_REQUERIDA      	DATETIME 	NOT NULL,
        UNIDAD_DISTRIBUCIO   	VARCHAR(6) 	NULL,
        FECHA_HORA_CANCELA   	DATETIME 	NULL,
        CENTRO_COSTO         	VARCHAR(25) 	NULL,
        CUENTA_CONTABLE      	VARCHAR(25) 	NULL,
	E_MAIL         	     	VARCHAR(250) 	NULL,
	FASE                 	VARCHAR(25) 	NULL,
	PROYECTO             	VARCHAR(25) 	NULL,
	ORDEN_CAMBIO 		INT 		NULL
 )
go
 

CREATE TABLE SP_ARTICULO(
	ARTICULO 		VARCHAR(20) NOT NULL,
	DESCRIPCION 		VARCHAR(254) NOT NULL,
	CLASIFICACION_1 	VARCHAR(12) NULL,
	CLASIFICACION_2 	VARCHAR(12) NULL,
	CLASIFICACION_3 	VARCHAR(12) NULL,
	CLASIFICACION_4 	VARCHAR(12) NULL,
	CLASIFICACION_5 	VARCHAR(12) NULL,
	CLASIFICACION_6 	VARCHAR(12) NULL,
	TIPO 			VARCHAR(1) NOT NULL,
	IMPUESTO 		VARCHAR(4) NOT NULL,
	EXISTENCIA_MINIMA 	DECIMAL(28, 8) NOT NULL,
	EXISTENCIA_MAXIMA 	DECIMAL(28, 8) NOT NULL,
	PUNTO_DE_REORDEN 	DECIMAL(28, 8) NOT NULL,
	COSTO_PROM_LOC 		DECIMAL(28, 8) NOT NULL,
	COSTO_PROM_DOL 		DECIMAL(28, 8) NOT NULL,
	CLASE_ABC 		VARCHAR(1) NOT NULL,
	FRECUENCIA_CONTEO 	SMALLINT NOT NULL,
	ACTIVO 			VARCHAR(1) NOT NULL,
	PROVEEDOR 		VARCHAR(20) NULL,
	UNIDAD_ALMACEN 		VARCHAR(6) NOT NULL,
	UNIDAD_EMPAQUE 		VARCHAR(6) NOT NULL,
	 ULTIMO_INGRESO  	DATETIME 	 NULL,
	 ARTICULO_DEL_PROV VARCHAR(30) NULL,
	 LOTE_MULTIPLO  	DECIMAL(28,8)  NULL,
	 ORDEN_MINIMA  	DECIMAL(28,8) 	 NULL,
	 PLAZO_REABAST  	smallint  NULL,
	 COSTO_FISCAL 		VARCHAR(1) NULL,
	 COSTO_COMPARATIVO VARCHAR(1) NULL,
	 FACTOR_EMPAQUE 	DECIMAL(28,8)  NULL
)

go
	
	
	
CREATE TABLE SP_ARTICULO_PROVEEDOR(
	ARTICULO 		VARCHAR(20) NOT NULL,
	PROVEEDOR 		VARCHAR(20) NOT NULL,
	CODIGO_CATALOGO	 	VARCHAR(20) NULL,
	LOTE_MINIMO 		DECIMAL(28, 8) NOT NULL,
	LOTE_ESTANDAR 		DECIMAL(28, 8) NOT NULL,
	PESO_MINIMO_ORDEN 	DECIMAL(28, 8) NOT NULL,
	MULTIPLO_COMPRA 	DECIMAL(28, 8) NOT NULL,
	CANT_ECONOMICA_COM 	DECIMAL(28, 8) NOT NULL,
	UNIDAD_MEDIDA_COMP 	VARCHAR(10) NOT NULL,
	FACTOR_CONVERSION 	DECIMAL(28, 8) NOT NULL,
	PLAZO_REABASTECIMI 	SMALLINT NOT NULL,
	PORC_AJUSTE_COSTO 	DECIMAL(28, 8) NOT NULL,
	FECHA_ULT_COTIZACI 	DATETIME NULL,
	NOTAS 			TEXT NULL,
	DESCRIP_CATALOGO 	VARCHAR(254) NULL,
	PAIS VARCHAR(4) 	NOT NULL DEFAULT ('ND'),
	TIPO VARCHAR(1) 	NOT NULL DEFAULT ('P')
)

go



CREATE TABLE SP_FACTURA_LINEA(
	FACTURA 		VARCHAR(50) NOT NULL,
	TIPO_DOCUMENTO 		VARCHAR(1) NOT NULL,
	LINEA 			SMALLINT NOT NULL,
	BODEGA 			VARCHAR(4) NOT NULL,
	COSTO_TOTAL_DOLAR 	DECIMAL(28, 8) NOT NULL,
	PEDIDO 			VARCHAR(50) NULL,
	ARTICULO 		VARCHAR(20) NOT NULL,	
	ANULADA 		VARCHAR(1) NOT NULL,
	FECHA_FACTURA 		DATETIME NOT NULL,
	CANTIDAD 		DECIMAL(28, 8) NOT NULL,
	PRECIO_UNITARIO 	DECIMAL(28, 8) NOT NULL,
	TOTAL_IMPUESTO1 	DECIMAL(28, 8) NOT NULL,
	TOTAL_IMPUESTO2 	DECIMAL(28, 8) NOT NULL,
	DESC_TOT_LINEA 		DECIMAL(28, 8) NOT NULL,
	DESC_TOT_GENERAL 	DECIMAL(28, 8) NOT NULL,
	COSTO_TOTAL 		DECIMAL(28, 8) NOT NULL,
	PRECIO_TOTAL 		DECIMAL(28, 8) NOT NULL,
	COMENTARIO 		VARCHAR(100) NULL,
	COSTO_TOTAL_LOCAL 	DECIMAL(28, 8) NOT NULL,
	PEDIDO_LINEA 		SMALLINT NULL,
	DOCUMENTO_ORIGEN 	VARCHAR(50) NULL,
	COSTO_ESTIM_LOCAL 	DECIMAL(28, 8) NOT NULL,
	COSTO_ESTIM_DOLAR 	DECIMAL(28, 8) NOT NULL,
	MONTO_RETENCION 	DECIMAL(28, 8) NOT NULL,
	BASE_IMPUESTO1 		DECIMAL(28, 8) NULL,
	BASE_IMPUESTO2 		DECIMAL(28, 8) NULL
)

go	
	
	
	
CREATE TABLE SP_PROVEEDOR(
	PROVEEDOR 		VARCHAR(20) NOT NULL,
	NOMBRE 			VARCHAR(150) NOT NULL,
	CONDICION_PAGO 		VARCHAR(4) NOT NULL,
	LOCAL 			VARCHAR(1) NOT NULL,
	IMPUESTO1_INCLUIDO 	VARCHAR(1) NOT NULL,
	CONTACTO 		VARCHAR(30) NOT NULL,
	DIRECCION 		TEXT NOT NULL,
	TELEFONO1 		VARCHAR(50) NULL,
	ORDEN_MINIMA 		DECIMAL(28, 8) NOT NULL,
	MONEDA 			VARCHAR(4) NOT NULL,
	PAIS 			VARCHAR(4) NOT NULL,
	SALDO 			DECIMAL(28, 8) NOT NULL
)

go



CREATE TABLE SP_TRANSACCION_INV(
	AUDIT_TRANS_INV 	INT NOT NULL,
	CONSECUTIVO 		INT NOT NULL,
	FECHA_HORA_TRANSAC 	DATETIME NULL,
	NIT 			VARCHAR(20) NULL,
	SERIE_CADENA 		INT NULL,
	AJUSTE_CONFIG 		VARCHAR(4) NULL,
	ARTICULO 		VARCHAR(20) NOT NULL,
	BODEGA 			VARCHAR(4) NULL,
	LOCALIZACION 		VARCHAR(8) NULL,
	LOTE 			VARCHAR(15) NULL,
	TIPO 			VARCHAR(1) NOT NULL,
	SUBTIPO 		VARCHAR(1) NOT NULL,
	SUBSUBTIPO 		VARCHAR(1) NOT NULL,
	NATURALEZA 		VARCHAR(1) NOT NULL,
	CANTIDAD 		DECIMAL(28, 8) NOT NULL,
	COSTO_TOT_FISC_LOC 	DECIMAL(28, 8) NOT NULL,
	COSTO_TOT_FISC_DOL 	DECIMAL(28, 8) NOT NULL,
	COSTO_TOT_COMP_LOC 	DECIMAL(28, 8) NOT NULL,
	COSTO_TOT_COMP_DOL 	DECIMAL(28, 8) NOT NULL,
	PRECIO_TOTAL_LOCAL 	DECIMAL(28, 8) NOT NULL,
	PRECIO_TOTAL_DOLAR 	DECIMAL(28, 8) NOT NULL,
	CONTABILIZADA 		VARCHAR(1) NOT NULL,
	FECHA 			DATETIME NOT NULL,
	CENTRO_COSTO 		VARCHAR(25) NULL,
	UNIDAD_DISTRIBUCIO 	VARCHAR(6) NULL,
	CUENTA_CONTABLE 	VARCHAR(25) NULL,
	ASIENTO_CARDEX 		VARCHAR(10) NULL
)

go	
	
	
	
CREATE TABLE SP_PRECIO_ART_PROV(
	ARTICULO 	VARCHAR(20) NOT NULL,
	PROVEEDOR 	VARCHAR(20) NOT NULL,
	LINEA 		SMALLINT NOT NULL,
	CANTIDAD_HASTA 	DECIMAL(28, 8) NOT NULL,
	PRECIO 		DECIMAL(28, 8) NOT NULL
)

go



CREATE TABLE SP_EXISTENCIA_BODEGA(
	ARTICULO 			VARCHAR(20) NOT NULL,
	BODEGA 				VARCHAR(4) NOT NULL,
	EXISTENCIA_MINIMA 		DECIMAL(28, 8) NOT NULL,
	EXISTENCIA_MAXIMA 		DECIMAL(28, 8) NOT NULL,
	PUNTO_DE_REORDEN 		DECIMAL(28, 8) NOT NULL,
	CANT_DISPONIBLE 		DECIMAL(28, 8) NOT NULL,
	CANT_RESERVADA 			DECIMAL(28, 8) NOT NULL,
	CANT_NO_APROBADA 		DECIMAL(28, 8) NOT NULL,
	CANT_VENCIDA 			DECIMAL(28, 8) NOT NULL,
	CANT_TRANSITO 			DECIMAL(28, 8) NOT NULL,
	CANT_PRODUCCION 		DECIMAL(28, 8) NOT NULL,
	CANT_PEDIDA 			DECIMAL(28, 8) NOT NULL,
	CANT_REMITIDA 			DECIMAL(28, 8) NOT NULL,
	CONGELADO 			VARCHAR(1) NOT NULL,
	FECHA_CONG 			DATETIME NULL,
	BLOQUEA_TRANS 			VARCHAR(1) NOT NULL,
	FECHA_DESCONG 			DATETIME NULL,
	COSTO_UNT_PROMEDIO_LOC 		DECIMAL(28, 8) NOT NULL,
	COSTO_UNT_PROMEDIO_DOL 		DECIMAL(28, 8) NOT NULL,
	COSTO_UNT_ESTANDAR_LOC 		DECIMAL(28, 8) NOT NULL,
	COSTO_UNT_ESTANDAR_DOL 		DECIMAL(28, 8) NOT NULL,
	COSTO_PROM_COMPARATIVO_LOC 	DECIMAL(28, 8) NOT NULL,
	COSTO_PROM_COMPARATIVO_DOLAR 	DECIMAL(28, 8) NOT NULL
)

go
	
	
	
CREATE TABLE SP_ORDEN_COMPRA(
	ORDEN_COMPRA		VARCHAR(10) NOT NULL,
	USUARIO			VARCHAR(25) NULL,
	PROVEEDOR		VARCHAR(20) NOT NULL,
	BODEGA			VARCHAR(4) NOT NULL,
	CONDICION_PAGO		VARCHAR(4) NOT NULL,
	FECHA 			DATETIME NOT NULL,
	FECHA_COTIZACION	DATETIME NULL,
	FECHA_OFRECIDA		DATETIME NULL,
	FECHA_EMISION		DATETIME NULL,
	FECHA_REQ_EMBARQUE	DATETIME NULL,
	FECHA_REQUERIDA		DATETIME NOT NULL,
	MONTO_DESCUENTO		DECIMAL(28, 8) NULL,
	TOTAL_MERCADERIA	DECIMAL(28, 8) NOT NULL,
	TOTAL_IMPUESTO1		DECIMAL(28, 8) NOT NULL,
	TOTAL_IMPUESTO2		DECIMAL(28, 8) NOT NULL,
	TOTAL_A_COMPRAR		DECIMAL(28, 8) NOT NULL,
	PRIORIDAD		VARCHAR(1) NOT NULL,
	ESTADO			VARCHAR(1) NOT NULL,
	FECHA_HORA		DATETIME NOT NULL
)

go	
	
	
	
CREATE TABLE SP_ORDEN_COMPRA_LINEA(
	ORDEN_COMPRA 			VARCHAR(10) NOT NULL,
	ORDEN_COMPRA_LINEA 		SMALLINT NOT NULL,
	ARTICULO VARCHAR(20) 		NOT NULL,
	BODEGA VARCHAR(4) 		NOT NULL,
	DESCRIPCION TEXT 		NULL,
	CANTIDAD_ORDENADA 		DECIMAL(28, 8) NOT NULL,
	CANTIDAD_EMBARCADA 		DECIMAL(28, 8) NOT NULL,
	CANTIDAD_RECIBIDA 		DECIMAL(28, 8) NOT NULL,
	CANTIDAD_RECHAZADA		DECIMAL(28, 8) NOT NULL,
	PRECIO_UNITARIO			DECIMAL(28, 8) NOT NULL,
	IMPUESTO1			DECIMAL(28, 8) NOT NULL,
	IMPUESTO2			DECIMAL(28, 8) NOT NULL,
	MONTO_DESCUENTO			DECIMAL(28, 8) NOT NULL,
	FECHA				DATETIME NOT NULL,
	ESTADO				VARCHAR(1) NOT NULL,
	FECHA_REQUERIDA			DATETIME NOT NULL,
	FACTURA				VARCHAR(50) NULL,
	E_MAIL				VARCHAR(250) NULL,
	PRECIO_ART_PROV			DECIMAL(28, 8) NOT NULL
)

go
	
	
	
CREATE TABLE SP_AUDIT_TRANS_INV(
	AUDIT_TRANS_INV 	INT NOT NULL,
	CONSECUTIVO 		VARCHAR(10) NULL,
	USUARIO 		VARCHAR(25) NOT NULL,
	FECHA_HORA 		DATETIME NOT NULL,
	MODULO_ORIGEN 		VARCHAR(4) NOT NULL,
	APLICACION 		VARCHAR(249) NOT NULL,
	REFERENCIA 		VARCHAR(200) NOT NULL,
	ASIENTO 		VARCHAR(10) NULL,
	USUARIO_APRO 		VARCHAR(25) NULL,
	FECHA_HORA_APROB 	DATETIME NULL,
	PAQUETE_INVENTARIO 	VARCHAR(4) NULL
)

go
	


CREATE TABLE SP_EMBARQUE(
	EMBARQUE 		VARCHAR(10) NOT NULL,
	LIQUIDAC_COMPRA 	VARCHAR(15) NULL,
	PROVEEDOR 		VARCHAR(20) NULL,
	FECHA_REQUERIDA 	DATETIME NULL,
	FECHA_OFRECIDA 		DATETIME NULL,
	FECHA_EMBARQUE 		DATETIME NULL,
	ESTADO 			VARCHAR(1) NOT NULL,
	USUARIO_CREADO 		VARCHAR(25) NOT NULL,
	FECHA_HORA_CREADO 	DATETIME NOT NULL,
	USUARIO_APLICADO 	VARCHAR(25) NULL,
	FECHA_HORA_APLICAC 	DATETIME NULL,
	ASIENTO 		VARCHAR(10) NULL,
	AUDIT_TRANS_INV 	INT NULL,
	AUDIT_TRANS_LIQ 	INT NULL,
	FECHA_CRM 		DATETIME NULL,
	TIENE_FACTURA 		VARCHAR(1) NOT NULL
)

go
	

CREATE TABLE SP_EMBARQUE_LINEA(
	EMBARQUE 		VARCHAR(10) NOT NULL,
	EMBARQUE_LINEA 		SMALLINT NOT NULL,
	ORDEN_COMPRA 		VARCHAR(10) NULL,
	ORDEN_COMPRA_LINEA 	SMALLINT NULL,
	ARTICULO 		VARCHAR(20) NOT NULL,
	BODEGA 			VARCHAR(4) NOT NULL,
	CANTIDAD_EMBARCADA 	DECIMAL(28, 8) NOT NULL,
	CANTIDAD_RECIBIDA 	DECIMAL(28, 8) NOT NULL,
	CANTIDAD_RECHAZADA 	DECIMAL(28, 8) NOT NULL,
	PRECIO_UNITARIO 	DECIMAL(28, 8) NOT NULL,
	SUBTOTAL 		DECIMAL(28, 8) NULL,
	DESCUENTO 		DECIMAL(28, 8) NULL,
	IMPUESTO1 		DECIMAL(28, 8) NULL,
	IMPUESTO2 		DECIMAL(28, 8) NULL,
	DOCUMENTO 		VARCHAR(50) NULL,
	TIPO_DOCUMENTO 		VARCHAR(1) NULL
)

go



CREATE TABLE SP_DEPARTAMENTO(
	DEPARTAMENTO		VARCHAR(10) NOT NULL,
	DESCRIPCION		VARCHAR(40) NOT NULL
)

go



CREATE TABLE SP_BODEGA(
	BODEGA		VARCHAR(4) NOT NULL,
	NOMBRE		VARCHAR(40) NOT NULL,
	TIPO		VARCHAR(1) NOT NULL,
	TELEFONO	VARCHAR(15) NOT NULL,
	DIRECCION	VARCHAR(120) NULL
)

go
	
	
	
CREATE TABLE SP_PRONOSTICO(
	PRONOSTICO		VARCHAR(20) NOT NULL,
	DESCRIPCION		VARCHAR(40) NOT NULL,
	PDO_INI_PRONOST		DATETIME NOT NULL,
	PDO_FIN_PRONOST		DATETIME NOT NULL
)

go
	
ALTER TABLE SP_PRONOSTICO 
	ADD  CONSTRAINT XPKSPPRONOSTICO PRIMARY KEY NONCLUSTERED (PRONOSTICO)

go
	
	
CREATE TABLE SP_PRONOSTICO_DETALLE(
	ID			INT	IDENTITY(1,1) NOT NULL,
	PRONOSTICO		VARCHAR(20) NOT NULL,
	PERIODO			DATETIME NOT NULL,
	ITEM_PRONOSTICADO	SMALLINT NOT NULL,
	ARTICULO		VARCHAR(20) NOT NULL,
	BODEGA			VARCHAR(4) NULL,
	CANTIDAD_PRONOSTICADA		DECIMAL(28, 8) NOT NULL
)

go
		
ALTER TABLE SP_PRONOSTICO_DETALLE 
	ADD  CONSTRAINT XPKSPPRONOSTICODET PRIMARY KEY NONCLUSTERED (ID)

go
     
     
 CREATE TABLE SP_PROBABILIDAD(
	COMBINACION	VARCHAR(4) NULL,
	PORCENTAJE	VARCHAR(3) NULL
)

go


CREATE TABLE SP_PROB_DETALLE(
	COMBINACION 	VARCHAR(4) NULL,
	PORCENTAJE 	VARCHAR(3) NULL
)

go


CREATE TABLE SP_HISTORIAL(
	ID					INT IDENTITY(1,1) NOT NULL,
	PLANIFICADOR		VARCHAR(10) NOT NULL,
	CONJUNTO			VARCHAR(10) NOT NULL,
	CONSECUTIVO			VARCHAR(10) NOT NULL,
	ARTICULO			VARCHAR(20) NOT NULL,
	DESCRIPCION			VARCHAR(254) NOT NULL,
	ARTICULO_PROVEEDOR		VARCHAR(20) NOT NULL,
	CONSUMO_PROMEDIO		DECIMAL(28, 8) NOT NULL,
	INV_MAXIMO				DECIMAL(28, 8) NOT NULL,
	INV_TRANSITO			DECIMAL(28, 8) NOT NULL,
	INV_ACTUAL				DECIMAL(28, 8) NOT NULL,
	REFERENCIA_PEDIDO		DECIMAL(28, 8) NOT NULL,
	PRECIO_UNITARIO			DECIMAL(28, 8) NOT NULL,
	PRECIO_TOTAL			DECIMAL(28, 8) NOT NULL,
	SUGERENCIA_PEDIDO		DECIMAL(28, 8) NOT NULL,
	CANTIDAD_COMPRADA		DECIMAL(28, 8) NOT NULL,
	USUARIO					VARCHAR(30) NOT NULL,
	FECHA_HORA				DATETIME NULL,
	NOTAS 					VARCHAR(250) NULL,
	FKVERSION 				INT DEFAULT 0 NOT NULL
)
go



CREATE TABLE SP_ARTICULO_TEMP(
PKSP_ARTICULO_TEMP 	int IDENTITY(1,1), 
PLANIFICADOR 		NVARCHAR(10) NOT NULL,
FKVERSION 			INT  NOT NULL,
FKSP_HISTORIAL 		int  NOT NULL,
CODIGO 				NVARCHAR(20) NOT NULL,
DESCRIPCION 		NVARCHAR(254) NOT NULL,
SUGERIDO 			DECIMAL(28,8) NOT NULL,
CLASE_TOTAL 		NVARCHAR(10) NOT NULL, 
CONSUMO_PROMEDIO 	DECIMAL(28,8) NOT NULL,
INV_MAXIMO 			DECIMAL(28,8) NOT NULL,
INV_TRANSITO 		DECIMAL(28,8) NOT NULL, 
INV_ACTUAL 			DECIMAL(28,8) NOT NULL, 
REFERENCIA_PEDIDO 	DECIMAL(28,8) NOT NULL,
SUGERENCIA_PEDIDO 	DECIMAL(28,8) NOT NULL, 
PROVEEDOR 			NVARCHAR(20)  NULL, 
PRECIO_UNITARIO 	DECIMAL(28,8) NOT NULL,
PRECIO_TOTAL 		DECIMAL(28,8) NOT NULL
)

go

ALTER TABLE SP_ARTICULO_TEMP ADD CONSTRAINT XARTICULOEMP PRIMARY KEY NONCLUSTERED (PKSP_ARTICULO_TEMP)

go

CREATE TABLE SP_VERSION_PLANIFICADOR_TEMP(
PKSP_VERSION_TEMP 		int IDENTITY(1,1) ,
FKPLANIFICADOR 			NVARCHAR(10) NOT NULL,
FECHA_INI_PLANIFICADOR 	DATETIME NOT NULL,
FECHA_FIN_PLANIFICADOR 	DATETIME NOT NULL,
VERSION_PLANIFICADOR 	INT  NOT NULL
)

go

ALTER TABLE SP_VERSION_PLANIFICADOR_TEMP 
	ADD CONSTRAINT XVERSIONPLANIFICADOR 
		PRIMARY KEY NONCLUSTERED (PKSP_VERSION_TEMP)
 
 
 ALTER TABLE SOLICITUD_OC_LINEA
        ADD CONSTRAINT XPKSOLICITUD_DETAL PRIMARY KEY NONCLUSTERED (
               SOLICITUD_OC, SOLICITUD_OC_LINEA)
go
 
 
 CREATE TABLE SOLICITUD_ORDEN_CO (
        SOLICITUD_OC         VARCHAR(10) NOT NULL,
        SOLICITUD_OC_LINEA   smallint NOT NULL,
        ORDEN_COMPRA         VARCHAR(10) NOT NULL,
        ORDEN_COMPRA_LINEA   smallint NOT NULL,
        CANTIDAD             DECIMAL(28,8) NOT NULL
 )
go
 
 
 ALTER TABLE SOLICITUD_ORDEN_CO
        ADD CONSTRAINT XPKSOLICITUD_ORDEN PRIMARY KEY (SOLICITUD_OC, 
               SOLICITUD_OC_LINEA, ORDEN_COMPRA, ORDEN_COMPRA_LINEA)
go


CREATE TABLE USUARIOS_APROB_OC(
	ORDEN_COMPRA		VARCHAR(10) 	NOT NULL,
	USUARIO			VARCHAR(25) 	NOT NULL,
	FECHA_APROB		DATETIME	NOT NULL
)
go

ALTER TABLE USUARIOS_APROB_OC
        ADD CONSTRAINT PK_USUARIOS_APROBOC 
        	PRIMARY KEY NONCLUSTERED (ORDEN_COMPRA, USUARIO)
go        	

CREATE TABLE USUARIOS_DEPARTAMENTO(
	DEPARTAMENTO		VARCHAR(10) 	NOT NULL,
	USUARIO			VARCHAR(25) 	NOT NULL,
	MONTO_MAX_APROB_USR 	DECIMAL(28, 8) 	NOT NULL DEFAULT (0)
)
go

ALTER TABLE USUARIOS_DEPARTAMENTO
        ADD CONSTRAINT PK_USUARIOS_DEPARTAMENTO 
        	PRIMARY KEY NONCLUSTERED (DEPARTAMENTO, USUARIO)
go


CREATE TABLE USUARIOS_X_CENTRO ( 	
	USUARIO 	VARCHAR(25) NOT NULL,
	CENTRO_COSTO	VARCHAR(25) NOT NULL
)
go

ALTER TABLE USUARIOS_X_CENTRO
	ADD CONSTRAINT XPKUSUARIOSXCENTRO 
		PRIMARY KEY (USUARIO, CENTRO_COSTO)
go




