
 
 ALTER TABLE AUXILIAR_CP
        ADD CONSTRAINT AUXCPPRO
               FOREIGN KEY (PROVEEDOR)
                              REFERENCES PROVEEDOR
go
 
 
 ALTER TABLE AUXILIAR_CP
        ADD CONSTRAINT AUXCPDBD
               FOREIGN KEY (PROVEEDOR, DEBITO, TIPO_DEBITO)
                              REFERENCES DOCUMENTOS_CP
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE AUXILIAR_CP
        ADD CONSTRAINT AUXMONCR
               FOREIGN KEY (MONEDA_CREDITO)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE AUXILIAR_CP
        ADD CONSTRAINT AUXMONDE
               FOREIGN KEY (MONEDA_DEBITO)
                              REFERENCES MONEDA
go


 ALTER TABLE AUXILIAR_CP
        ADD CONSTRAINT AUXCPCRD
               FOREIGN KEY (PROVEEDOR, CREDITO, TIPO_CREDITO )
                              REFERENCES DOCUMENTOS_CP  (PROVEEDOR, DOCUMENTO, TIPO)
go 
 
ALTER TABLE $$COMPANIA$$.CODING_CARTA_RENTA ADD 
	CONSTRAINT FK_CODING_CARTA_RENTA
		FOREIGN KEY (COD_INGRESO)
			REFERENCES $$COMPANIA$$.COD_INGRESO (COD_INGRESO)
 
go

ALTER TABLE CONTRAREC_MOV_PRES
         ADD CONSTRAINT CONTRAMOVPRESCONTRA
         	FOREIGN KEY  ( CONTRARECIBO )
         		REFERENCES CONTRARECIBOS ( CONTRARECIBO )
			ON DELETE CASCADE
go 



ALTER TABLE CONTRAREC_MOV_PRES
         ADD CONSTRAINT CONTRMOVPRESPRESUPCR
         	FOREIGN KEY  ( PRESUPUESTO )
         		REFERENCES PRESUPUESTO_CR ( PRESUPUESTO )
			ON DELETE CASCADE
go 
         		


 ALTER TABLE CONTRARECIBOS
        ADD CONSTRAINT CRECUSER
               FOREIGN KEY (USUARIO_ULT_MOD)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CONTRARECIBOS
        ADD CONSTRAINT CRECCOND
               FOREIGN KEY (CONDICION_PAGO)
                              REFERENCES CONDICION_PAGO
go
 
 
 ALTER TABLE CONTRARECIBOS
        ADD CONSTRAINT CRECPROV
               FOREIGN KEY (PROVEEDOR)
                              REFERENCES PROVEEDOR
go
 

ALTER TABLE CONTRARECIBOS
         ADD CONSTRAINT PRESUPUESTOCRCONTRA
         	FOREIGN KEY  ( PRESUPUESTO_CR )
         		REFERENCES PRESUPUESTO_CR ( PRESUPUESTO )
go
 
 
 


ALTER TABLE CP_DET_RETENCION_PAR
	ADD CONSTRAINT	FKDETRETCPDETRETPAR
		FOREIGN KEY (TIPO,PROVEEDOR,DOCUMENTO,RETENCION) 
			REFERENCES DETALLE_RETENCION (TIPO,PROVEEDOR,DOCUMENTO,CODIGO_RETENCION)
go
						
						

ALTER TABLE CP_DET_RETENCION_PAR 
	ADD CONSTRAINT	FKDETRETCPDOCCP
		FOREIGN KEY (PROVEE_CAN,DOC_CAN,TIPO_CAN) 
			REFERENCES DOCUMENTOS_CP (PROVEEDOR,DOCUMENTO,TIPO)
go					
						 
 
 
 
 ALTER TABLE DETALLE_RETENCION
        ADD CONSTRAINT DRETDOCP
               FOREIGN KEY (PROVEEDOR, DOCUMENTO, TIPO)
                              REFERENCES DOCUMENTOS_CP
go
 
 
 ALTER TABLE DETALLE_RETENCION
        ADD CONSTRAINT DRETRET
               FOREIGN KEY (CODIGO_RETENCION)
                              REFERENCES RETENCIONES
go
 
 
ALTER TABLE DET_TIPOSERVICIO_CP
        ADD CONSTRAINT DETTIPOSERVICCPFASEPY
               FOREIGN KEY (PROYECTO,FASE)
                              REFERENCES FASE_PY
go                              

							  
ALTER TABLE DET_TIPOSERVICIO_CP
        ADD CONSTRAINT DETTIPOSERVICCPDOCUMCP
               FOREIGN KEY (PROVEEDOR,DOCUMENTO,TIPO)
                              REFERENCES DOCUMENTOS_CP
                              ON DELETE CASCADE
go  


ALTER TABLE DIFERIDO 
	ADD  CONSTRAINT FK_CENTRO_CUENTA_DIFERIDO 
		FOREIGN KEY(CTR_DIFERIDO, CTA_DIFERIDO)
			REFERENCES  CENTRO_CUENTA (CENTRO_COSTO, CUENTA_CONTABLE)
go

ALTER TABLE DIFERIDO 
	ADD  CONSTRAINT FK_CENTRO_CUENTA_CONTRAASIENTO 
		FOREIGN KEY(CTR_CONTRAASIENTO, CTA_CONTRAASIENTO)
			REFERENCES  CENTRO_CUENTA (CENTRO_COSTO, CUENTA_CONTABLE)
go

ALTER TABLE DIFERIDO 
	ADD  CONSTRAINT FK_CENTRO_CUENTA_AMORTIZACION 
		FOREIGN KEY(CTR_AMORTIZACION, CTA_AMORTIZACION)
			REFERENCES  CENTRO_CUENTA (CENTRO_COSTO, CUENTA_CONTABLE)
go

ALTER TABLE DIFERIDO 
	ADD  CONSTRAINT FK_CENTRO_CUENTA_GASTOINGRESO 
		FOREIGN KEY(CTR_GASTOINGRESO, CTA_GASTOINGRESO)
			REFERENCES  CENTRO_CUENTA (CENTRO_COSTO, CUENTA_CONTABLE)
go


 
 ALTER TABLE DOCUMENTOS_CP
        ADD CONSTRAINT DOCSUBTD
               FOREIGN KEY (SUBTIPO, TIPO)
                              REFERENCES SUBTIPO_DOC_CP
go
 
 
 ALTER TABLE DOCUMENTOS_CP
        ADD CONSTRAINT USMODUSR
               FOREIGN KEY (USUARIO_ULT_MOD)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE DOCUMENTOS_CP
        ADD CONSTRAINT DCPCTACB
               FOREIGN KEY (CHEQUE_CUENTA)
                              REFERENCES CUENTA_BANCARIA
go
 
 
 ALTER TABLE DOCUMENTOS_CP
        ADD CONSTRAINT DOCCPMON
               FOREIGN KEY (MONEDA)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE DOCUMENTOS_CP
        ADD CONSTRAINT DOCCPCON
               FOREIGN KEY (CONDICION_PAGO)
                              REFERENCES CONDICION_PAGO
go
 
 
 ALTER TABLE DOCUMENTOS_CP
        ADD CONSTRAINT DOCSCPLIQCOMPRA
               FOREIGN KEY (LIQUIDAC_COMPRA)
                              REFERENCES LIQUIDAC_COMPRA
go
 
 
 ALTER TABLE DOCUMENTOS_CP
        ADD CONSTRAINT DOCCPPRO
               FOREIGN KEY (PROVEEDOR)
                              REFERENCES PROVEEDOR
go
 
 
 ALTER TABLE DOCUMENTOS_CP
        ADD CONSTRAINT DOCPCREC
               FOREIGN KEY (CONTRARECIBO)
                              REFERENCES CONTRARECIBOS
go

ALTER TABLE DOCUMENTOS_CP  
	ADD CONSTRAINT USUARAPROBDOCCP
		FOREIGN KEY  ( USUARIO_APROBACION ) 
			REFERENCES ERPADMIN.USUARIO
go	

ALTER TABLE DOCUMENTOS_CP
	ADD CONSTRAINT FKUSUDOC
		FOREIGN KEY  ( USUARIO )
			REFERENCES ERPADMIN.USUARIO
go			

ALTER TABLE DOCUMENTOS_CP
	ADD CONSTRAINT FKCTABANDOC
		FOREIGN KEY  ( CUENTA_BANCO)
			REFERENCES CUENTA_BANCARIA
go 

ALTER TABLE DOCUMENTOS_CP
        ADD CONSTRAINT DOCCPCODIMP
               FOREIGN KEY (CODIGO_IMPUESTO)
                              REFERENCES IMPUESTO
go                              


ALTER TABLE DOCUMENTOS_CP 
        ADD CONSTRAINT DOCCPDIVGEO
               FOREIGN KEY (PAIS,DIVISION_GEOGRAFICA1,DIVISION_GEOGRAFICA2 )
                              REFERENCES DIVISION_GEOGRAFICA2
go                              


ALTER TABLE DOCUMENTOS_CP
	ADD CONSTRAINT DOCUMENCPTIPOASNT
		FOREIGN KEY (TIPO_ASIENTO)
			REFERENCES TIPO_ASIENTO(TIPO_ASIENTO)
go			
			
ALTER TABLE DOCUMENTOS_CP
	ADD CONSTRAINT DOCUMENCPPAQUETE
		FOREIGN KEY (PAQUETE)
			REFERENCES PAQUETE(PAQUETE)
go			

 
 ALTER TABLE EMBARQUE_DOC_CP
        ADD CONSTRAINT EMDOCEMB
               FOREIGN KEY (EMBARQUE)
                              REFERENCES EMBARQUE
go
 
 
 ALTER TABLE EMBARQUE_DOC_CP
        ADD CONSTRAINT EMDOCDCP
               FOREIGN KEY (PROVEEDOR, DOCUMENTO, TIPO)
                              REFERENCES DOCUMENTOS_CP
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE EMBARQUE_DOC_CP
        ADD CONSTRAINT FKEMBDOCCPLIQCMPR
               FOREIGN KEY ( LIQUIDAC_COMPRA )
                              REFERENCES LIQUIDAC_COMPRA
go   


ALTER TABLE $$COMPANIA$$.FIADORES_DOC_CP
         ADD CONSTRAINT FIADORDOCCP
         	FOREIGN KEY  ( PROVEEDOR, DOCUMENTO, TIPO)
         		REFERENCES $$COMPANIA$$.DOCUMENTOS_CP ( PROVEEDOR, DOCUMENTO, TIPO )
go


ALTER TABLE $$COMPANIA$$.GARANTIAS_DOC_CP
         ADD CONSTRAINT GARANDOCCCP
         	FOREIGN KEY  ( PROVEEDOR, DOCUMENTO, TIPO)
         		REFERENCES $$COMPANIA$$.DOCUMENTOS_CP ( PROVEEDOR, DOCUMENTO, TIPO )
go        		

ALTER TABLE $$COMPANIA$$.GARANTIAS_DOC_CP
         ADD CONSTRAINT GARANCPART
         	FOREIGN KEY  ( ART_GARANTIA)
         		REFERENCES $$COMPANIA$$.ARTICULO ( ARTICULO )
go
 
 
 ALTER TABLE GLOBALES_CP
        ADD CONSTRAINT GLBCPIMP
               FOREIGN KEY (IMPUESTO_X_OMISION)
                              REFERENCES IMPUESTO
go
 
 
 ALTER TABLE GLOBALES_CP
        ADD CONSTRAINT GBCPTADB
               FOREIGN KEY (TIPO_ASIENTO_DEB)
                              REFERENCES TIPO_ASIENTO
go
 
 
 ALTER TABLE GLOBALES_CP
        ADD CONSTRAINT GBCPPQDB
               FOREIGN KEY (PAQUETE_DEB)
                              REFERENCES PAQUETE
go
 
 
 ALTER TABLE GLOBALES_CP
        ADD CONSTRAINT GBCPPQCR
               FOREIGN KEY (PAQUETE_CRE)
                              REFERENCES PAQUETE
go
 
 
 ALTER TABLE GLOBALES_CP
        ADD CONSTRAINT GBCPTACR
               FOREIGN KEY (TIPO_ASIENTO_CRE)
                              REFERENCES TIPO_ASIENTO
go
 

ALTER TABLE GLOBALES_CP
       ADD CONSTRAINT GLOBCPPRESUPCR
              FOREIGN KEY (PRESUPUESTO_CR)
                             REFERENCES PRESUPUESTO_CR (PRESUPUESTO)
go


ALTER TABLE GLOBALES_CP
       ADD CONSTRAINT GLOBCPPAQUETECR
              FOREIGN KEY (PAQUETE_CR)
                             REFERENCES PAQUETE_CR (PAQUETE)
go
 
ALTER TABLE HIST_DIFCAM_CP
         ADD CONSTRAINT USUARHISTDFCP
         	FOREIGN KEY  ( usuario_auditoria)
         		REFERENCES ERPADMIN.USUARIO(USUARIO) 
go  


ALTER TABLE $$COMPANIA$$.PARCIALIDADES_CP
        ADD CONSTRAINT PARCCDOCCP
               FOREIGN KEY ( PROVEEDOR, DOCUMENTO_ORIGEN, TIPO_DOC_ORIGEN )
                              REFERENCES $$COMPANIA$$.DOCUMENTOS_CP
                              ON DELETE CASCADE
go

 
 ALTER TABLE PROV_RETENCION
        ADD CONSTRAINT PRRETRET
               FOREIGN KEY (CODIGO_RETENCION)
                              REFERENCES RETENCIONES
go
 
 
 ALTER TABLE PROV_RETENCION
        ADD CONSTRAINT PRETPROV
               FOREIGN KEY (PROVEEDOR)
                              REFERENCES PROVEEDOR
go
 
 
ALTER TABLE PROV_VALORES_CERTIF
	ADD CONSTRAINT 	PROVVALCERTIFPROV
		FOREIGN KEY (PROVEEDOR)
			REFERENCES PROVEEDOR
				ON DELETE CASCADE
go


ALTER TABLE PROV_VALORES_CERTIF
	ADD CONSTRAINT CTRCTA383
		FOREIGN KEY (CENTRO_COSTO383 ,CUENTA_CONTABLE383 )
			REFERENCES CENTRO_CUENTA (CENTRO_COSTO, CUENTA_CONTABLE)
go


ALTER TABLE PROV_VALORES_CERTIF
	ADD CONSTRAINT CTRCTA384
		FOREIGN KEY (CENTRO_COSTO384 ,CUENTA_CONTABLE384 )
			REFERENCES CENTRO_CUENTA (CENTRO_COSTO, CUENTA_CONTABLE)
go
 
 
 ALTER TABLE PROVEEDOR
        ADD CONSTRAINT PROVCOND
               FOREIGN KEY (CONDICION_PAGO)
                              REFERENCES CONDICION_PAGO
go
 
 
 ALTER TABLE PROVEEDOR
        ADD CONSTRAINT PROVPAIS
               FOREIGN KEY (PAIS)
                              REFERENCES PAIS
go
 
 
 ALTER TABLE PROVEEDOR
        ADD CONSTRAINT PROVEEDORNIT
               FOREIGN KEY (CONTRIBUYENTE)
                              REFERENCES NIT
go
 
 
 ALTER TABLE PROVEEDOR
        ADD CONSTRAINT PROVCATG
               FOREIGN KEY (CATEGORIA_PROVEED)
                              REFERENCES CATEGORIA_PROVEED
go
 
 
 ALTER TABLE PROVEEDOR
        ADD CONSTRAINT PROVMON
               FOREIGN KEY (MONEDA)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE PROVEEDOR
        ADD CONSTRAINT PROVDETDIR
               FOREIGN KEY (DETALLE_DIRECCION)
                              REFERENCES DETALLE_DIRECCION
go
 
ALTER TABLE PROVEEDOR
	ADD CONSTRAINT FTK_MODRETCP
		FOREIGN KEY (MODELO_RETENCION)
			REFERENCES MODELO_RETENCION(MODELO_RETENCION)
go	

 ALTER TABLE PROVEEDOR
        ADD CONSTRAINT PROCODIMP
               FOREIGN KEY (CODIGO_IMPUESTO)
                              REFERENCES IMPUESTO
go   



ALTER TABLE PROVEEDOR
        ADD CONSTRAINT PROVEEDORUSRC
		FOREIGN KEY ( USUARIO_CREACION )
			REFERENCES ERPADMIN.USUARIO 
go

ALTER TABLE PROVEEDOR
        ADD CONSTRAINT PROVEEDORUSRM
		FOREIGN KEY ( USUARIO_ULT_MOD )
			REFERENCES ERPADMIN.USUARIO 
go

 ALTER TABLE PROVEEDOR_ENTIDAD
        ADD CONSTRAINT PRENTENT
               FOREIGN KEY (ENTIDAD_FINANCIERA)
                              REFERENCES ENTIDAD_FINANCIERA
go
 
 
 ALTER TABLE PROVEEDOR_ENTIDAD
        ADD CONSTRAINT PRENTPR
               FOREIGN KEY (PROVEEDOR)
                              REFERENCES PROVEEDOR
go
 
 
 ALTER TABLE PROVEEDOR_ENTIDAD
        ADD CONSTRAINT PROVENTMON
               FOREIGN KEY (MONEDA)
                              REFERENCES MONEDA
go
 
ALTER TABLE PROVEEDOR_ENTIDAD 
        ADD CONSTRAINT PROVTIPCTA_TCTA
               FOREIGN KEY (TIPO_CUENTA)
                              REFERENCES TIPO_CUENTA
go                              

 ALTER TABLE SUBTIPO_DOC_CP
        ADD CONSTRAINT ASOC_SUBTCB_SUBTCP
               FOREIGN KEY (TIPO_CB, SUBTIPO_CB)
                              REFERENCES SUBTIPO_DOC_CB
go

ALTER TABLE SUBTIPO_DOC_CP
        ADD CONSTRAINT SUBDOCCP_CTAC
               FOREIGN KEY (CENTRO_COSTO, CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go                              


ALTER TABLE SUBTIPO_DOC_CP
	ADD CONSTRAINT SUBDOCCPTIPOASNT
		FOREIGN KEY (TIPO_ASIENTO)
			REFERENCES TIPO_ASIENTO(TIPO_ASIENTO)
go			
			
ALTER TABLE SUBTIPO_DOC_CP
	ADD CONSTRAINT SUBDOCCPPAQUETE
		FOREIGN KEY (PAQUETE)
			REFERENCES PAQUETE(PAQUETE)
go			


ALTER TABLE TIPO_SERVICIO_CP
         ADD CONSTRAINT TIPOSERVICPCTRCTA
                FOREIGN KEY (CENTRO_COSTO,CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go                              
 