
 
 CREATE TABLE ASIENTO_MOV_PRES (
        ASIENTO              		VARCHAR(10) 	NOT NULL,
        PRESUPUESTO          		VARCHAR(20) 	NULL,
        UNIDAD_OPERATIVA     		VARCHAR(4) 	NULL,
        NUMERO               		int 		NULL,
	UNIDAD_OPERATIVA_EJERCIDA 	VARCHAR(4) 	NULL,
	NUMERO_EJERCIDO			INT		NULL        
 )
go
 
 
 ALTER TABLE ASIENTO_MOV_PRES
        ADD CONSTRAINT XPKASIENTO_MOV_PRES PRIMARY KEY (ASIENTO)
go
 
 
 CREATE TABLE CENTRO_COSTO_CR (
        CENTRO_COSTO         VARCHAR(25) 	NOT NULL,
        DESCRIPCION          VARCHAR(200) 	NOT NULL,
        ACEPTA_DATOS         VARCHAR(1) 	NOT NULL,
        USR_CREACION         VARCHAR(25) 	NOT NULL,
        FCH_HR_CREACION      DATETIME 		NOT NULL,
        USR_ULT_MOD          VARCHAR(25) 	NULL,
        FCH_HR_ULT_MOD       DATETIME		NULL,
        NOTAS                TEXT 		NULL
 )
go
 
 
 ALTER TABLE CENTRO_COSTO_CR
        ADD CONSTRAINT XPKCENTRO_COSTO PRIMARY KEY NONCLUSTERED (
               CENTRO_COSTO)
go
 
 
 CREATE TABLE CENTRO_PARTIDA (
        CENTRO_COSTO         VARCHAR(25) NOT NULL,
        PARTIDA              VARCHAR(25) NOT NULL,
        UNIDAD_OPERATIVA     VARCHAR(4) NULL,
        CONCEPTO_FLUJO       VARCHAR(4) NULL,
        REFERENCIA           VARCHAR(20) NULL,
        ACEPTA_DATOS         VARCHAR(1) NOT NULL,
        ACTIVA               VARCHAR(1) NULL,
        USR_CREACION         VARCHAR(25) NOT NULL,
        FCH_HR_CREACION      DATETIME NOT NULL,
        USR_ULT_MOD          VARCHAR(25) NULL,
        FCH_HR_ULT_MOD       DATETIME NULL
 )
go
 
 
 ALTER TABLE CENTRO_PARTIDA
        ADD CONSTRAINT XPKCENTRO_PARTIDA PRIMARY KEY NONCLUSTERED (
               CENTRO_COSTO, PARTIDA)
go
 
 
 CREATE TABLE CONCEPTO_FLUJO (
        CONCEPTO_FLUJO       VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(50) NOT NULL,
        TIPO                 VARCHAR(1) NOT NULL,
        USR_CREACION         VARCHAR(25) NOT NULL,
        FCH_HR_CREACION      DATETIME NOT NULL,
        USR_ULT_MOD          VARCHAR(25) NULL,
        FECHA_ULT_MOD        DATETIME NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE CONCEPTO_FLUJO
        ADD CONSTRAINT XPKCONCEPTO_FLUJO PRIMARY KEY NONCLUSTERED (
               CONCEPTO_FLUJO)
go
 
 
 CREATE TABLE DESGLOSE_PRESUP (
        PRESUPUESTO          VARCHAR(20) NOT NULL,
        CENTRO_COSTO         VARCHAR(25) NOT NULL,
        PARTIDA              VARCHAR(25) NOT NULL,
        CONCEPTO_FLUJO       VARCHAR(4) NULL,
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        MODO_FORMULACION     smallint NOT NULL
 )
go
 
 
 ALTER TABLE DESGLOSE_PRESUP
        ADD CONSTRAINT XPKDESGLOSE_PRESUP PRIMARY KEY NONCLUSTERED (
               PRESUPUESTO, CENTRO_COSTO, PARTIDA)
go
 
 
 CREATE TABLE DESTINO (
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        NUMERO               int NOT NULL,
        LINEA                int NOT NULL,
        UNIDAD_DESTINO       VARCHAR(4) NOT NULL,
        ESTADO               VARCHAR(1) NOT NULL,
        USR_EXPORTACION      VARCHAR(25) NULL,
        FCH_HR_EXPORTACION   DATETIME NULL,
        ARCHIVO              VARCHAR(25) NULL
 )
go
 
 
 ALTER TABLE DESTINO
        ADD CONSTRAINT XPKDESTINO PRIMARY KEY NONCLUSTERED (
               UNIDAD_OPERATIVA, NUMERO, LINEA, UNIDAD_DESTINO)
go
 
 
 CREATE TABLE DET_MOV_APLICADO (
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        NUMERO               int NOT NULL,
        LINEA                int NOT NULL,
        PRESUPUESTO          VARCHAR(20) NOT NULL,
        CENTRO_COSTO         VARCHAR(25) NOT NULL,
        PARTIDA              VARCHAR(25) NOT NULL,
        FECHA                DATETIME NOT NULL,
        PERIODO              DATETIME NOT NULL,
        TRANSACCION          VARCHAR(2) NOT NULL,
        GRUPO                smallint NULL,
        BALANCE              VARCHAR(1) NULL,
        MONTO_LOCAL          DECIMAL(28,8) NOT NULL,
        UNIDADES             DECIMAL(28,8) NULL,
        UND_OPER_AFECTADA    VARCHAR(4) NOT NULL,
        RUBRO1               VARCHAR(15) NULL,
        RUBRO2               VARCHAR(15) NULL,
        RUBRO3               VARCHAR(15) NULL,
        CONTRAPARTIDA        VARCHAR(1) NOT NULL,
        COMENTARIO           VARCHAR(254) NULL
 )
go
 
 
 ALTER TABLE DET_MOV_APLICADO
        ADD CONSTRAINT XPKDET_MOV_APLICAD PRIMARY KEY NONCLUSTERED (
               UNIDAD_OPERATIVA, NUMERO, LINEA)
go
 
 
 CREATE TABLE DET_MOV_NOAPLICADO (
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        NUMERO               int NOT NULL,
        LINEA                int NOT NULL,
        CENTRO_COSTO         VARCHAR(25) NOT NULL,
        PARTIDA              VARCHAR(25) NOT NULL,
        PERIODO              DATETIME NOT NULL,
        TRANSACCION          VARCHAR(2) NOT NULL,
        GRUPO                smallint NULL,
        BALANCE              VARCHAR(1) NULL,
        MONTO_LOCAL          DECIMAL(28,8) NOT NULL,
        UNIDADES             DECIMAL(28,8) NULL,
        UND_OPER_AFECTADA    VARCHAR(4) NOT NULL,
        RUBRO1               VARCHAR(15) NULL,
        RUBRO2               VARCHAR(15) NULL,
        RUBRO3               VARCHAR(15) NULL,
        COMENTARIO           VARCHAR(254) NULL
 )
go
 
 
 ALTER TABLE DET_MOV_NOAPLICADO
        ADD CONSTRAINT XPKDET_MOV_NOAPLIC PRIMARY KEY NONCLUSTERED (
               UNIDAD_OPERATIVA, NUMERO, LINEA)
go
 
 
 CREATE TABLE DETALLE_FLUJO (
        PRESUPUESTO          VARCHAR(20) NOT NULL,
        CONCEPTO_FLUJO       VARCHAR(4) NOT NULL,
        PERIODO              DATETIME NOT NULL,
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        MONTO_LOCAL          DECIMAL(28,8) NULL,
        MONTO_UDS            DECIMAL(28,8) NULL,
        AMPLIACION_LOCAL     DECIMAL(28,8) NULL,
        AMPLIACION_UDS       DECIMAL(28,8) NULL,
        REDUCCION_LOCAL      DECIMAL(28,8) NULL,
        REDUCCION_UDS        DECIMAL(28,8) NULL,
        COMPR_LOCAL          DECIMAL(28,8) NULL,
        COMPR_UDS            DECIMAL(28,8) NULL,
        EJEDEV_LOCAL_FEB     DECIMAL(28,8) NULL,
        EJEDEV_UDS_FEB       DECIMAL(28,8) NULL,
        PAGCOB_LOCAL_FEB     DECIMAL(28,8) NULL,
        PAGCOB_UDS_FEB       DECIMAL(28,8) NULL,
        PAGCOB_LOCAL_FEC     DECIMAL(28,8) NULL,
        PAGCOB_UDS_FEC       DECIMAL(28,8) NULL
 )
go
 
 
 ALTER TABLE DETALLE_FLUJO
        ADD CONSTRAINT XPKDETALLE_FLUJO PRIMARY KEY NONCLUSTERED (
               PRESUPUESTO, CONCEPTO_FLUJO, PERIODO, UNIDAD_OPERATIVA)
go
 
 
 CREATE TABLE DETALLE_PRESUP (
        PRESUPUESTO          VARCHAR(20) NOT NULL,
        CENTRO_COSTO         VARCHAR(25) NOT NULL,
        PARTIDA              VARCHAR(25) NOT NULL,
        PERIODO              DATETIME NOT NULL,
        MONTO_LOCAL          DECIMAL(28,8) NULL,
        MONTO_UDS            DECIMAL(28,8) NULL,
        AMPLIACION_LOCAL     DECIMAL(28,8) NULL,
        AMPLIACION_UDS       DECIMAL(28,8) NULL,
        REDUCCION_LOCAL      DECIMAL(28,8) NULL,
        REDUCCION_UDS        DECIMAL(28,8) NULL,
        COMPR_LOCAL          DECIMAL(28,8) NULL,
        COMPR_UDS            DECIMAL(28,8) NULL,
        EJEDEV_LOCAL         DECIMAL(28,8) NULL,
        EJEDEV_UDS           DECIMAL(28,8) NULL,
        PAGCOB_LOCAL         DECIMAL(28,8) NULL,
        PAGCOB_UDS           DECIMAL(28,8) NULL
 )
go
 
 
 ALTER TABLE DETALLE_PRESUP
        ADD CONSTRAINT XPKDETALLE_PRESUP PRIMARY KEY NONCLUSTERED (
               PRESUPUESTO, CENTRO_COSTO, PARTIDA, PERIODO)
go
 
 
 CREATE TABLE DOCCP_MOVEJERCIDO (
        PROVEEDOR            VARCHAR(20) NOT NULL,
        DOCUMENTO            VARCHAR(50) NOT NULL,
        TIPO                 VARCHAR(3) NOT NULL,
        UNIDAD_OPERATIVA     VARCHAR(4) NULL,
        NUMERO               int NULL,
        PRESUPUESTO          VARCHAR(20) NULL
 )
go
 
 
 ALTER TABLE DOCCP_MOVEJERCIDO
        ADD CONSTRAINT XPKDOCCP_MOVEJERCIDO PRIMARY KEY (PROVEEDOR, 
               DOCUMENTO, TIPO)
go
 
 
 CREATE TABLE DOCCP_MOVPAGO (
        PROVEEDOR            VARCHAR(20) NOT NULL,
        TIPO_DEBITO          VARCHAR(3) NOT NULL,
        DEBITO               VARCHAR(50) NOT NULL,
        FECHA                DATETIME NOT NULL,
        TIPO_CREDITO         VARCHAR(3) NOT NULL,
        CREDITO              VARCHAR(50) NOT NULL,
        UNIDAD_OPERATIVA     VARCHAR(4) NULL,
        NUMERO               int NULL
 )
go
 
 
 ALTER TABLE DOCCP_MOVPAGO
        ADD CONSTRAINT XPKDOCCP_MOVPAGO PRIMARY KEY (PROVEEDOR, 
               TIPO_DEBITO, DEBITO, FECHA, TIPO_CREDITO, CREDITO)
go
 
 
 CREATE TABLE ENC_MOV_APLICADO (
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        NUMERO               int NOT NULL,
        FECHA                DATETIME NOT NULL,
        PRESUPUESTO          VARCHAR(20) NULL,
        TRANSACCION          VARCHAR(2) NOT NULL,
        ESTADO               VARCHAR(1) NOT NULL,
        AFECTACION_DOBLE     VARCHAR(1) NOT NULL,
        REQUIERE_FONDOS      VARCHAR(1) NOT NULL,
        MODULO_ORIGEN        VARCHAR(4) NOT NULL,
        MOV_CONTABLE         VARCHAR(10) NULL,
        COMENTARIO           VARCHAR(254) NULL,
        MOV_INICIAL          VARCHAR(1) NOT NULL,
        USR_CREACION         VARCHAR(25) NOT NULL,
        FCH_HR_CREACION      DATETIME NOT NULL,
        USR_ULT_MOD          VARCHAR(25) NULL,
        FCH_HR_ULT_MOD       DATETIME NULL,
        USR_APLICACION       VARCHAR(25) NULL,
        FCH_HR_APLICACION    DATETIME NULL,
        USR_IMPORTACION      VARCHAR(25) NULL,
        FCH_HR_IMPORTACION   DATETIME NULL,
        USR_ANULACION        VARCHAR(25) NULL,
        FCH_HR_ANULACION     DATETIME NULL,
        NOTAS                TEXT NULL,
        TRASPASO             VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE ENC_MOV_APLICADO
        ADD CONSTRAINT XPKENC_MOV_APLICAD PRIMARY KEY NONCLUSTERED (
               UNIDAD_OPERATIVA, NUMERO)
go
 
 
 CREATE TABLE ENC_MOV_NOAPLICADO (
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        NUMERO               int NOT NULL,
        FECHA                DATETIME NOT NULL,
        PRESUPUESTO          VARCHAR(20) NOT NULL,
        PAQUETE              VARCHAR(4) NOT NULL,
        TRANSACCION          VARCHAR(2) NOT NULL,
        ESTADO               VARCHAR(1) NOT NULL,
        MODULO_ORIGEN        VARCHAR(4) NOT NULL,
        AFECTACION_DOBLE     VARCHAR(1) NOT NULL,
        REQUIERE_FONDOS      VARCHAR(1) NOT NULL,
        SELECCIONADO         VARCHAR(1) NOT NULL,
        MOV_CONTABLE         VARCHAR(10) NULL,
        COMENTARIO           VARCHAR(254) NULL,
        USR_CREACION         VARCHAR(25) NOT NULL,
        FCH_HR_CREACION      DATETIME NOT NULL,
        USR_ULT_MOD          VARCHAR(25) NULL,
        FCH_HR_ULT_MOD       DATETIME NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE ENC_MOV_NOAPLICADO
        ADD CONSTRAINT XPKENC_MOV_NOAPLIC PRIMARY KEY (
               UNIDAD_OPERATIVA, NUMERO)
go
 
 
 CREATE TABLE EXT_MOV_APLICADO (
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        NUMERO               int NOT NULL,
        MONEDA               VARCHAR(4) NULL,
        MOVBASE_UNIDAD       VARCHAR(4) NULL,
        MOVBASE_NUMERO       int NULL,
        ORIGEN_MOVIMIENTO    VARCHAR(2) NULL,
        CODIGO_ORIGEN        VARCHAR(20) NULL,
        BENEFICIARIO         VARCHAR(150) NULL,
        REFERENCIA           VARCHAR(50) NULL,
        MONTO_LOCAL          DECIMAL(28,8) NOT NULL,
        SALDO_LOCAL          DECIMAL(28,8) NULL,
        OPERACION_EXTRANJ    VARCHAR(1) NOT NULL,
        TIPO_CAMBIO          DECIMAL(28,8) NULL,
        MONTO_OTRA_MONEDA    DECIMAL(28,8) NULL,
        SALDO_OTRA_MONEDA    DECIMAL(28,8) NULL,
        CTA_BCO_FUENTE       VARCHAR(20) NULL,
        CTA_BCO_DESTINO      VARCHAR(20) NULL
 )
go
 
 
 ALTER TABLE EXT_MOV_APLICADO
        ADD CONSTRAINT XPKEXT_MOV_APLICAD PRIMARY KEY NONCLUSTERED (
               UNIDAD_OPERATIVA, NUMERO)
go
 
 
 CREATE TABLE EXT_MOV_NOAPLICADO (
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        NUMERO               int NOT NULL,
        MONEDA               VARCHAR(4) NULL,
        MOVBASE_UNIDAD       VARCHAR(4) NULL,
        MOVBASE_NUMERO       int NULL,
        ORIGEN_MOVIMIENTO    VARCHAR(2) NULL,
        CODIGO_ORIGEN        VARCHAR(20) NULL,
        BENEFICIARIO         VARCHAR(150) NULL,
        REFERENCIA           VARCHAR(50) NULL,
        MONTO_LOCAL          DECIMAL(28,8) NOT NULL,
        OPERACION_EXTRANJ    VARCHAR(1) NOT NULL,
        TIPO_CAMBIO          DECIMAL(28,8) NULL,
        MONTO_OTRA_MONEDA    DECIMAL(28,8) NULL,
        CTA_BCO_FUENTE       VARCHAR(20) NULL,
        CTA_BCO_DESTINO      VARCHAR(20) NULL
 )
go
 
 
 ALTER TABLE EXT_MOV_NOAPLICADO
        ADD CONSTRAINT XPKEXT_MOV_NOAPLIC PRIMARY KEY NONCLUSTERED (
               UNIDAD_OPERATIVA, NUMERO)
go
 
 
 CREATE TABLE GLOBALES_CR (
        UNIDAD_PARTIDA       		VARCHAR(15)	NULL,
        UNIDAD_LOCAL         		VARCHAR(4) 	NOT NULL,
        UNIDAD_CENTRAL       		VARCHAR(4) 	NOT NULL,
        USAR_CENTROS         		VARCHAR(1) 	NOT NULL,
        REF_EN_PARTIDAS      		VARCHAR(1) 	NOT NULL,
        NOMBRE_REFERENCIA    		VARCHAR(25)	NULL,
        REF_EN_INGRESOS      		VARCHAR(1) 	NULL,
        REF_EN_EGRESOS       		VARCHAR(1) 	NULL,
        RUBROS_EN_LINMOV     		VARCHAR(1) 	NOT NULL,
        NOMBRE_RUBRO1        		VARCHAR(15)	NULL,
        AYUDA_RUBRO1         		VARCHAR(1) 	NULL,
        NOMBRE_RUBRO2        		VARCHAR(15)	NULL,
        AYUDA_RUBRO2         		VARCHAR(1) 	NULL,
        NOMBRE_RUBRO3        		VARCHAR(15)	NULL,
        AYUDA_RUBRO3         		VARCHAR(1) 	NULL,
        PATRON_CENTRO        		VARCHAR(25)	NULL,
        PATRON_PARTIDA       		VARCHAR(25)	NOT NULL,
        NOMBRE_MOV           		VARCHAR(15)	NOT NULL,
        ULTIMO_MOV           		int 		NOT NULL,
        SOLIC_FONDOS_OBLIG   		VARCHAR(1) 	NOT NULL,
        EJERCER_APART_AUX    		VARCHAR(1)	NOT NULL DEFAULT 'N',
        EJERCER_PARCIAL_APART_CO	VARCHAR(1)	NOT NULL DEFAULT 'N'
 )
go
 
 
 CREATE TABLE GLOBALES_CRGMVPRP (
        NOMBRE               VARCHAR(30) NOT NULL,
        TIPO                 VARCHAR(1) NOT NULL,
        LONGITUD             int NULL,
        VALOR_NUMERO         DECIMAL(28,8) NULL,
        VALOR_FECHA          DATETIME NULL,
        VALOR_SINO           VARCHAR(1) NULL,
        VALOR_TEXTO          VARCHAR(254) NULL,
        VALOR_OPCION         VARCHAR(1) NULL
 )
go
 
ALTER TABLE GLOBALES_CRGMVPRP
	ADD CONSTRAINT XPKGLOBALES_CRGMVPRP
		PRIMARY KEY (NOMBRE)
go
 
 
 CREATE TABLE INDICADOR_CR (
        INDICADOR            VARCHAR(18) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        CLASE                VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE INDICADOR_CR
        ADD CONSTRAINT XPKINDICADOR_CR PRIMARY KEY (INDICADOR)
go
 
 
 CREATE TABLE INDICADOR_VALOR_CR (
        INDICADOR            VARCHAR(18) NOT NULL,
        FECHA_FINAL          DATETIME NOT NULL,
        VALOR                DECIMAL(28,8) NOT NULL
 )
go
 
 
 ALTER TABLE INDICADOR_VALOR_CR
        ADD CONSTRAINT XPKINDICADOR_VALOR_CR PRIMARY KEY (INDICADOR, 
               FECHA_FINAL)
go
 
 
 CREATE TABLE MAPEO_CONTABLE (
        CTR_CONTABLE         VARCHAR(25) NOT NULL,
        CTA_CONTABLE         VARCHAR(25) NOT NULL,
        CENTRO_COSTO         VARCHAR(25) NOT NULL,
        TIPO_ASOCIACION      VARCHAR(1) NOT NULL,
        PARTIDA              VARCHAR(25) NOT NULL
 )
go
 
 
 ALTER TABLE MAPEO_CONTABLE
         ADD CONSTRAINT PKCTRCTAPARTIDAS PRIMARY KEY NONCLUSTERED
         	(CTR_CONTABLE , CTA_CONTABLE, CENTRO_COSTO, PARTIDA, TIPO_ASOCIACION )
go

 
 CREATE TABLE MAYOR_LINEA_PRES (
        ASIENTO              VARCHAR(10) NOT NULL,
        CONSECUTIVO          int NOT NULL,
        UNIDAD_OPERATIVA     VARCHAR(4) NULL,
        NUMERO               int NULL,
        ESTADO_MOV_PRESUP    VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE MAYOR_LINEA_PRES
        ADD CONSTRAINT XPKMAYOR_LINEA_PRES PRIMARY KEY (ASIENTO, 
               CONSECUTIVO)
go
 
 
 CREATE TABLE MEN_MOV_NOAPLICADO (
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        NUMERO               int NOT NULL,
        MENSAJE              TEXT NULL
 )
go
 
 
 ALTER TABLE MEN_MOV_NOAPLICADO
        ADD CONSTRAINT XPKMEN_MOV_NOAPLIC PRIMARY KEY (
               UNIDAD_OPERATIVA, NUMERO)
go
 
 
 CREATE TABLE MOV_PRESUPUESTAL (
        ASIENTO              VARCHAR(10) NOT NULL,
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        NUMERO               int NOT NULL,
        PRESUPUESTO          VARCHAR(20) NULL
 )
go
 
 
 ALTER TABLE MOV_PRESUPUESTAL
        ADD CONSTRAINT XPKMOV_PRESUPUESTAL PRIMARY KEY (ASIENTO, 
               UNIDAD_OPERATIVA, NUMERO)
go
 
 
 CREATE TABLE MOVIMIENTO_BASE (
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        NUMERO               int NOT NULL,
        LINEA                int NOT NULL,
        MOVBASE_UNIDAD       VARCHAR(4) NOT NULL,
        MOVBASE_NUMERO       int NOT NULL,
        MOVBASE_LINEA        int NOT NULL,
        MONTO                DECIMAL(28,8) NOT NULL,
        UNIDADES             DECIMAL(28,8) NULL
 )
go
 
 
 ALTER TABLE MOVIMIENTO_BASE
        ADD CONSTRAINT XPKMOVIMIENTO_BASE PRIMARY KEY (
               UNIDAD_OPERATIVA, NUMERO, LINEA, MOVBASE_UNIDAD, 
               MOVBASE_NUMERO, MOVBASE_LINEA)
go
 
 
 CREATE TABLE PAQUETE_CR (
        PAQUETE              VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        USR_CREACION         VARCHAR(25) NOT NULL,
        FCH_HR_CREACION      DATETIME NOT NULL
 )
go
 
 
 ALTER TABLE PAQUETE_CR
        ADD CONSTRAINT XPKPAQUETE_CPR PRIMARY KEY NONCLUSTERED (
               PAQUETE)
go
 
 
 CREATE TABLE PARTIDA_CR (
        PARTIDA              VARCHAR(25) 	NOT NULL,
        DESCRIPCION          VARCHAR(200) 	NOT NULL,
        CLASE                VARCHAR(1) 	NOT NULL,
        USA_CENTROS          VARCHAR(1) 	NOT NULL,
        ACEPTA_DATOS         VARCHAR(1) 	NOT NULL,
        ACEPTA_UNIDADES      VARCHAR(1) 	NOT NULL,
        TIPO_MODIFICACION    VARCHAR(1) 	NOT NULL,
        UNIDAD               VARCHAR(15) 	NULL,
        USR_CREACION         VARCHAR(25) 	NOT NULL,
        FCH_HR_CREACION      DATETIME 		NOT NULL,
        USR_ULT_MOD          VARCHAR(25) 	NULL,
        FCH_HR_ULT_MOD       DATETIME 		NULL,
        NOTAS                TEXT 		NULL
 )
go
 
 
 ALTER TABLE PARTIDA_CR
        ADD CONSTRAINT XPKPARTIDA PRIMARY KEY (PARTIDA)
go
 
 
 CREATE TABLE PERIODO_PRESUP (
        PRESUPUESTO          VARCHAR(20) NOT NULL,
        PERIODO              DATETIME NOT NULL,
        ESTADO               VARCHAR(1) NOT NULL,
        RECALCULAR_FLUJO     VARCHAR(1) NOT NULL,
        USUARIO_CIERRE       VARCHAR(25) NULL,
        FECHA_HORA_CIERRE    DATETIME NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE PERIODO_PRESUP
        ADD CONSTRAINT XPKPERIODO_PRESUP PRIMARY KEY NONCLUSTERED (
               PRESUPUESTO, PERIODO)
go
 
 
 CREATE TABLE PRESUPUESTO_CR (
        PRESUPUESTO          VARCHAR(20) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        PERIODO_INICIAL      DATETIME NOT NULL,
        PERIODO_FINAL        DATETIME NOT NULL,
        PERIODO_PRECIERRE    DATETIME NULL,
        PERIODO_LIQUIDAC     DATETIME NULL,
        CONTABILIDAD         VARCHAR(1) NOT NULL,
        ESTADO               VARCHAR(1) NOT NULL,
        FLUJO_EFECTIVO       VARCHAR(1) NOT NULL,
        CONTROL_PRESUP       VARCHAR(1) NOT NULL,
        ARRASTRE_EN_CIERRE   VARCHAR(1) NOT NULL,
        CIFRA_CTRL_CIERRE    DECIMAL(28,8) NULL,
        USR_CREACION         VARCHAR(25) NOT NULL,
        FCH_HR_CREACION      DATETIME NOT NULL,
        USR_ULT_MOD          VARCHAR(25) NULL,
        FCH_HR_ULT_MOD       DATETIME NULL,
        USR_APROBACION       VARCHAR(25) NULL,
        FCH_HR_APROBACION    DATETIME NULL,
        USR_LIBERACION       VARCHAR(25) NULL,
        FCH_HR_LIBERACION    DATETIME NULL,
        USR_CIERRE           VARCHAR(25) NULL,
        FCH_HR_CIERRE        DATETIME NULL,
        USR_CANCELACION      VARCHAR(25) NULL,
        FCH_HR_CANCELACION   DATETIME NULL,
        MONEDA               VARCHAR(4) NULL,
        VALIDA_DISPONIBLE    VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE PRESUPUESTO_CR
        ADD CONSTRAINT XPKPRESUPUESTO PRIMARY KEY NONCLUSTERED (
               PRESUPUESTO)
go
 
 
 CREATE TABLE REFERENCIA (
        REFERENCIA           VARCHAR(20) NOT NULL,
        DESCRIPCION          VARCHAR(50) NOT NULL
 )
go
 
 
 ALTER TABLE REFERENCIA
        ADD CONSTRAINT XPKREFERENCIA PRIMARY KEY NONCLUSTERED (
               REFERENCIA)
go
 
 
 CREATE TABLE REQ_EXP_TRANS (
        PRESUPUESTO          VARCHAR(20) NOT NULL,
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        EXPORTACION_PEND     VARCHAR(1) NOT NULL,
        CANTIDAD_MOV         int NULL
 )
go
 
 
 ALTER TABLE REQ_EXP_TRANS
        ADD CONSTRAINT XPKREQ_EXP_PEND PRIMARY KEY NONCLUSTERED (
               PRESUPUESTO, UNIDAD_OPERATIVA)
go
 
 
 CREATE TABLE RUBRO (
        RUBRO                VARCHAR(20) NOT NULL,
        DESCRIPCION          VARCHAR(50) NOT NULL,
        TIPO_RUBRO           VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE RUBRO
        ADD CONSTRAINT XPKRUBRO PRIMARY KEY NONCLUSTERED (RUBRO)
go
 
 
 CREATE TABLE TEXTO_PRESUPUESTO (
        PRESUPUESTO          VARCHAR(20) NOT NULL,
        IDENTIFICADOR        VARCHAR(1) NOT NULL,
        TEXTO                TEXT NOT NULL
 )
go
 
 
 ALTER TABLE TEXTO_PRESUPUESTO
        ADD CONSTRAINT XPKTEXTOS_PRESUP PRIMARY KEY NONCLUSTERED (
               PRESUPUESTO, IDENTIFICADOR)
go
 
 
 CREATE TABLE UNIDAD_OPERATIVA (
        UNIDAD_OPERATIVA     VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        LOCAL                VARCHAR(1) NOT NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE UNIDAD_OPERATIVA
        ADD CONSTRAINT XPKUNIDAD_OPERATIV PRIMARY KEY NONCLUSTERED (
               UNIDAD_OPERATIVA)
go
 
 
 CREATE TABLE USUARIO_PAQUETE_CR (
        PAQUETE              VARCHAR(4) NOT NULL,
        USUARIO              VARCHAR(25) NOT NULL
 )
go
 
 
 ALTER TABLE USUARIO_PAQUETE_CR
        ADD CONSTRAINT XPKUSUARIO_PAQUETE PRIMARY KEY NONCLUSTERED (
               PAQUETE, USUARIO)
go
 
 
 CREATE TABLE USUARIO_PRESUP (
        PRESUPUESTO          VARCHAR(20)	NOT NULL,
        USUARIO              VARCHAR(25)	NOT NULL,
        PRIV_LECTURA         VARCHAR(1) 	NOT NULL,
        PRIV_MODIFICACION    VARCHAR(1) 	NOT NULL,
        PRIV_EJECUCION       VARCHAR(1) 	NOT NULL,
        USR_ULT_MOD          VARCHAR(25)	NULL,
        FCH_HR_ULT_MOD       DATETIME 		NULL
 )
go
 
 
 ALTER TABLE USUARIO_PRESUP
        ADD CONSTRAINT XPKUSR_PRESUPUESTO PRIMARY KEY NONCLUSTERED (
               PRESUPUESTO, USUARIO)
go
 
 