ALTER TABLE ANTICIPO_MARCA_FACT
        ADD CONSTRAINT FKANTICIPO_MARCA_FACT
               	FOREIGN KEY ( DOCUMENTO_CC, TIPO )
			REFERENCES DOCUMENTOS_CC ( DOCUMENTO, TIPO )
go

ALTER TABLE APERTURA_CAJA
         ADD CONSTRAINT FKUSR_APCAJA
         	FOREIGN KEY  ( USUARIO )
         		REFERENCES ERPADMIN.USUARIO ( USUARIO )
go

ALTER TABLE APERTURA_CAJA
         ADD CONSTRAINT FKCAJA_APCAJA
         	FOREIGN KEY  ( CAJA )
        		 REFERENCES CAJA ( CAJA )
go
 
 ALTER TABLE ARTICULO_ENSAMBLE
        ADD CONSTRAINT ARHIARTI
               FOREIGN KEY (ARTICULO_HIJO)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE ARTICULO_ENSAMBLE
        ADD CONSTRAINT ARPAARTI
               FOREIGN KEY (ARTICULO_PADRE)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE ARTICULO_PRECIO
        ADD CONSTRAINT ARTPRECVERSNIV
               FOREIGN KEY (NIVEL_PRECIO, MONEDA, VERSION)
                              REFERENCES VERSION_NIVEL
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE ARTICULO_PRECIO
        ADD CONSTRAINT ARPRARTI
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE BLOQUEO_IMPRESO
        ADD CONSTRAINT BLIMUSUA
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
ALTER TABLE CAJA
         ADD CONSTRAINT FKACT_CAJA
         	FOREIGN KEY  ( ACTIVO_FIJO )
         		REFERENCES ACTIVO_FIJO ( ACTIVO_FIJO )
go         		
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIVEND
               FOREIGN KEY (VENDEDOR)
                              REFERENCES VENDEDOR
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIZONA
               FOREIGN KEY (ZONA)
                              REFERENCES ZONA
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIPAIS
               FOREIGN KEY (PAIS)
                              REFERENCES PAIS
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLICONDP
               FOREIGN KEY (CONDICION_PAGO)
                              REFERENCES CONDICION_PAGO
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIENTEMONEDA
               FOREIGN KEY (MONEDA)
                              REFERENCES MONEDA
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIETTAR
               FOREIGN KEY (TIPO_TARJETA)
                              REFERENCES TIPO_TARJETA
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIECATG
               FOREIGN KEY (CATEGORIA_CLIENTE)
                              REFERENCES CATEGORIA_CLIENTE
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIECOBR
               FOREIGN KEY (COBRADOR)
                              REFERENCES COBRADOR
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIERUTA
               FOREIGN KEY (RUTA)
                              REFERENCES RUTA
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIENIPR
               FOREIGN KEY (NIVEL_PRECIO, MONEDA_NIVEL)
                              REFERENCES NIVEL_PRECIO
go
 
 

 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIDETDIR
               FOREIGN KEY (DETALLE_DIRECCION)
                              REFERENCES DETALLE_DIRECCION
go


ALTER TABLE CLIENTE
	ADD CONSTRAINT CLIENTENIT
		FOREIGN KEY (CONTRIBUYENTE)
			REFERENCES NIT
go  



 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIENTECLICORPASOC
               FOREIGN KEY (CLI_CORPORAC_ASOC)
                              REFERENCES CLIENTE
go

ALTER TABLE CLIENTE 
	ADD CONSTRAINT FTK_MODRETCC
		FOREIGN KEY (MODELO_RETENCION)
			REFERENCES MODELO_RETENCION(MODELO_RETENCION)
go

ALTER TABLE CLIENTE
        ADD CONSTRAINT CLICODIMP
               FOREIGN KEY (CODIGO_IMPUESTO)
                              REFERENCES IMPUESTO
go  


ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIENTEUSRC
		FOREIGN KEY ( USUARIO_CREACION )
			REFERENCES ERPADMIN.USUARIO
go

ALTER TABLE CLIENTE
	ADD CONSTRAINT CLIENTEUSRM
		FOREIGN KEY ( USUARIO_ULT_MOD )
			REFERENCES ERPADMIN.USUARIO
go

 ALTER TABLE CLIENTE_RETENCION
        ADD CONSTRAINT CLRETRET
               FOREIGN KEY (CODIGO_RETENCION)
                              REFERENCES RETENCIONES
go
 
 
 ALTER TABLE CLIENTE_RETENCION
        ADD CONSTRAINT PRETCL
               FOREIGN KEY (CLIENTE)
                              REFERENCES CLIENTE
go 

 
 ALTER TABLE CLIENTE_VENDEDOR
        ADD CONSTRAINT CLVDCLIE
               FOREIGN KEY (CLIENTE)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE CLIENTE_VENDEDOR
        ADD CONSTRAINT CLVDVEND
               FOREIGN KEY (VENDEDOR)
                              REFERENCES VENDEDOR
go


ALTER TABLE CONSECUFA_USUARIO
         ADD CONSTRAINT FKUSRCONSECUFA
         	FOREIGN KEY  ( USUARIO )
         		REFERENCES ERPADMIN.USUARIO ( USUARIO )
go

ALTER TABLE CONSECUFA_USUARIO
         ADD CONSTRAINT FKCONSE_CONSECUFA
         	FOREIGN KEY  ( CODIGO_CONSECUTIVO )
         		REFERENCES CONSECUTIVO_FA ( CODIGO_CONSECUTIVO )
go 
 
 ALTER TABLE CONSECUTIVO_FA
        ADD CONSTRAINT CONSECUUSUA
               FOREIGN KEY (USUARIO_ULT)
                              REFERENCES ERPADMIN.USUARIO
go

ALTER TABLE CONSECUTIVO_FA
	ADD CONSTRAINT CONFARESOLDOCELEC
		FOREIGN KEY (RESOLUCION)
			REFERENCES RESOLUCION_DOC_ELECTRONICO
go

ALTER TABLE $$COMPANIA$$.DES_BON_ESPECIFICACION_GRUPO  WITH CHECK 
	ADD  CONSTRAINT FK_ESPECIFICACION_GRUPO_REGLA 
		FOREIGN KEY(REGLA)
			REFERENCES DES_BON_REGLA ( REGLA)
go

ALTER TABLE DES_BON_PAQUETE_TIENDA
	ADD CONSTRAINT FK_DESBONPAQTIENDA_PAQUETE
		FOREIGN KEY(PAQUETE) 
			REFERENCES DES_BON_PAQUETE (PAQUETE)
go


ALTER TABLE DES_BON_PAQUETE_TIENDA
	ADD CONSTRAINT FK_DESBONPAQTIENDA_TIENDA
		FOREIGN KEY(TIENDA) 
			REFERENCES GRUPO (GRUPO)
go


ALTER TABLE DES_BON_PAQUETE_REGLA
	ADD CONSTRAINT FK_PAQUETE_REGLA_PAQUETE
		FOREIGN KEY(PAQUETE) 
			REFERENCES DES_BON_PAQUETE (PAQUETE)
go
			
ALTER TABLE DES_BON_PAQUETE_REGLA
	ADD CONSTRAINT FK_PAQUETE_REGLA_REGLA
		FOREIGN KEY(REGLA) 
			REFERENCES DES_BON_REGLA (REGLA)
go


ALTER TABLE DES_BON_REGLA
	ADD CONSTRAINT FK_DES_BON_REGLA_FORMA_PAGO
		FOREIGN KEY(FORMA_PAGO) 
			REFERENCES FORMA_PAGO (FORMA_PAGO)
go



ALTER TABLE DES_BON_REGLA_LOTE 
	ADD CONSTRAINT DESBONREGLALOTE
		FOREIGN KEY (REGLA)
			REFERENCES DES_BON_REGLA(REGLA) 
go


ALTER TABLE DES_BON_PAQUETE_RUTA
	ADD CONSTRAINT FK_DESBONPAQRUTA_PAQUETE
		FOREIGN KEY(PAQUETE) 
			REFERENCES DES_BON_PAQUETE (PAQUETE)
go

ALTER TABLE DES_BON_PAQUETE_RUTA
	ADD CONSTRAINT FK_DESBONPAQRUTA_RUTA
		FOREIGN KEY(RUTA) 
			REFERENCES ERPADMIN.RUTA_RT (RUTA)
go



ALTER TABLE DES_BON_ESCALA_BONIFICACION
	ADD CONSTRAINT FK_ESCALA_BONIFICACION_REGLA
		FOREIGN KEY(REGLA) 
			REFERENCES DES_BON_REGLA (REGLA)
go


ALTER TABLE DESPACHO
       ADD CONSTRAINT DESPCLIE
              FOREIGN KEY (CLIENTE)
                             REFERENCES CLIENTE
go

ALTER TABLE DESPACHO
       ADD CONSTRAINT DESPCONSECU
              FOREIGN KEY (CONSECUTIVO)
                             REFERENCES CONSECUTIVO_FA (CODIGO_CONSECUTIVO)
go



ALTER TABLE DESPACHO
       ADD CONSTRAINT DESPAUDTRAN
              FOREIGN KEY (AUDIT_TRANS_INV)
                             REFERENCES AUDIT_TRANS_INV
go


ALTER TABLE DESPACHO_DETALLE
       ADD CONSTRAINT DESPDETADESPA
              FOREIGN KEY (DESPACHO)
                             REFERENCES DESPACHO
                             ON DELETE CASCADE
go

ALTER TABLE DESPACHO_DETALLE
       ADD CONSTRAINT DESPDETFACTLIN
              FOREIGN KEY ( DOCUM_ORIG, TIPO_DOCUM_ORIG, LINEA_DOCUM_ORIG)
                             REFERENCES FACTURA_LINEA ( FACTURA, TIPO_DOCUMENTO, LINEA)
go

ALTER TABLE DESPACHO_DETALLE
       ADD CONSTRAINT DESPDETBOD
              FOREIGN KEY (BODEGA)
                             REFERENCES BODEGA
go

ALTER TABLE DESPACHO_DETALLE
       ADD CONSTRAINT DESPDETARTIC
              FOREIGN KEY (ARTICULO)
                             REFERENCES ARTICULO
go


ALTER TABLE DESPACHO_DETALLE
       ADD CONSTRAINT DESPDETSERIECADENA
              FOREIGN KEY (SERIE_CADENA)
                             REFERENCES SERIE_CADENA
go
 
 
 ALTER TABLE DIRECC_EMBARQUE
        ADD CONSTRAINT DIRECLIE
               FOREIGN KEY (CLIENTE)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE DIRECC_EMBARQUE
        ADD CONSTRAINT DIREMBDETDIR
               FOREIGN KEY (DETALLE_DIRECCION)
                              REFERENCES DETALLE_DIRECCION
go


ALTER TABLE DOCUMENTO_ANTICIPO
        ADD CONSTRAINT FKDocAnticipoDocCC
               	FOREIGN KEY ( DOCUMENTO_CC, TIPO_CC )
			REFERENCES DOCUMENTOS_CC ( DOCUMENTO, TIPO )
go
			
 
 ALTER TABLE ESCALA_BONIF
        ADD CONSTRAINT ESCBONIFARTBONIF
               FOREIGN KEY (ARTICULO_BONIF)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE ESCALA_BONIF
        ADD CONSTRAINT ESCBONIFART
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE ESCALA_BONIF
        ADD CONSTRAINT ESCBONIFVERSNIV
               FOREIGN KEY (NIVEL_PRECIO, MONEDA, VERSION)
                              REFERENCES VERSION_NIVEL
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE ESCALA_DCTO
        ADD CONSTRAINT ESCDCTOART
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE ESCALA_DCTO
        ADD CONSTRAINT ESCDCTOVERSNIV
               FOREIGN KEY (NIVEL_PRECIO, MONEDA, VERSION)
                              REFERENCES VERSION_NIVEL
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FACTNIPR
               FOREIGN KEY (NIVEL_PRECIO, MONEDA)
                              REFERENCES NIVEL_PRECIO
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT SUBTIPODOC_FACTURA
               FOREIGN KEY (TIPO_DOC_CXC, SUBTIPO_DOC_CXC)
                              REFERENCES SUBTIPO_DOC_CC
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FAUSANUL
               FOREIGN KEY (USUARIO_ANULA)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FAUSFACT
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FACTCNPG
               FOREIGN KEY (CONDICION_PAGO)
                              REFERENCES CONDICION_PAGO
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FACTDOCC
               FOREIGN KEY (DOC_CREDITO_CXC, TIPO_CREDITO_CXC)
                              REFERENCES DOCUMENTOS_CC
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FACTVEND
               FOREIGN KEY (VENDEDOR)
                              REFERENCES VENDEDOR
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FACTZONA
               FOREIGN KEY (ZONA)
                              REFERENCES ZONA
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FACTPAIS
               FOREIGN KEY (PAIS)
                              REFERENCES PAIS
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FACTCOBR
               FOREIGN KEY (COBRADOR)
                              REFERENCES COBRADOR
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FACTRUTA
               FOREIGN KEY (RUTA)
                              REFERENCES RUTA
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FACTCLIE
               FOREIGN KEY (CLIENTE)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FACTUCLIEORIGEN
               FOREIGN KEY (CLIENTE_ORIGEN)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FACTUCLIECORPORAC
               FOREIGN KEY (CLIENTE_CORPORAC)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FACTUCLIEDIRECCION
               FOREIGN KEY (CLIENTE_DIRECCION)
                              REFERENCES CLIENTE
go

 ALTER TABLE FACTURA_ADUANA 
	ADD  CONSTRAINT FK_FACTURA_FACTURA_ADUANA FOREIGN KEY( TIPO_DOCUMENTO,FACTURA)
		REFERENCES FACTURA ( TIPO_DOCUMENTO,FACTURA)
go


 ALTER TABLE FACTURA_ADUANA 
	ADD  CONSTRAINT FK_CLIENTE_FACTURA_ADUANA FOREIGN KEY( CLIENTE)
		REFERENCES CLIENTE ( CLIENTE)
go


ALTER TABLE FACTURA_CANCELA
         ADD CONSTRAINT FKFAC_FACCANCE
         	FOREIGN KEY  ( TIPO_DOCUMENTO, FACTURA )
         		REFERENCES FACTURA ( TIPO_DOCUMENTO, FACTURA )
go

ALTER TABLE FACTURA_CANCELA
         ADD CONSTRAINT FKENT_FACCANCE
         	FOREIGN KEY  ( ENTIDAD_FINANCIERA )
         		REFERENCES ENTIDAD_FINANCIERA ( ENTIDAD_FINANCIERA )
go

ALTER TABLE FACTURA_CANCELA
         ADD CONSTRAINT FKTARJ_FACCANCE
         	FOREIGN KEY  ( TIPO_TARJETA )
         		REFERENCES TIPO_TARJETA ( TIPO_TARJETA )
go

ALTER TABLE FACTURA_CANCELA
         ADD CONSTRAINT FKUSR_FACCANCE
         	FOREIGN KEY  ( USUARIO )
         		REFERENCES ERPADMIN.USUARIO ( USUARIO )
go

ALTER TABLE FACTURA_CANCELA
         ADD CONSTRAINT FKCAJA_FACANCE
         	FOREIGN KEY  ( CAJA )
         		REFERENCES CAJA ( CAJA )
go


ALTER TABLE FACTURA_DOC_CC
        ADD CONSTRAINT FK_FACT_DOC_CC_FACTLIN
               FOREIGN KEY ( FACTURA, TIPO_DOCUMENTO, LINEA )
                              REFERENCES FACTURA_LINEA ( FACTURA, TIPO_DOCUMENTO, LINEA )
go



ALTER TABLE FACTURA_DOC_CC
        ADD CONSTRAINT FKFACTURA_DOC_CC_DOCUMENTO
               FOREIGN KEY ( DOCUMENTO_CC, TIPO )
                              REFERENCES DOCUMENTOS_CC ( DOCUMENTO, TIPO )
go

 
 ALTER TABLE FACTURA_LINEA
        ADD CONSTRAINT FACLINEAUNDMEDIDA
               FOREIGN KEY (UNIDAD_DISTRIBUCIO)
                              REFERENCES UNIDAD_DE_MEDIDA
go
 
 
ALTER TABLE FACTURA_LINEA
         ADD CONSTRAINT FALILOTE
         FOREIGN KEY  ( ARTICULO, LOTE )
         REFERENCES LOTE ( ARTICULO, LOTE )
go
 
 
 ALTER TABLE FACTURA_LINEA
        ADD CONSTRAINT FALIBODE
               FOREIGN KEY (BODEGA)
                              REFERENCES BODEGA
go
 
 
 ALTER TABLE FACTURA_LINEA
        ADD CONSTRAINT FALIARTI
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE FACTURA_LINEA
        ADD CONSTRAINT FALIFACT_
               FOREIGN KEY (TIPO_DOCUMENTO, FACTURA)
                              REFERENCES FACTURA
go
 
 
 ALTER TABLE FACTURA_LINEA
        ADD CONSTRAINT FACLINSERIECADENA
               FOREIGN KEY (SERIE_CADENA)
                              REFERENCES SERIE_CADENA
go
 
 
 ALTER TABLE FACTURA_LINEA
        ADD CONSTRAINT FACLINSERIECADNOAC
               FOREIGN KEY (SERIE_CAD_NO_ACEPT)
                              REFERENCES SERIE_CADENA
go
 
 
 ALTER TABLE FACTURA_LINEA
        ADD CONSTRAINT FACLINSERIECADACEP
               FOREIGN KEY (SERIE_CAD_ACEPTADA)
                              REFERENCES SERIE_CADENA
go
 
 
 ALTER TABLE FACTURA_LINEA
        ADD CONSTRAINT FACLINLOCALIZA
               FOREIGN KEY (BODEGA, LOCALIZACION)
                              REFERENCES LOCALIZACION
go
 

ALTER TABLE FACTURA_LINEA 
        ADD CONSTRAINT FACTURALINEAFASEPY
               FOREIGN KEY (PROYECTO,FASE)
                              REFERENCES FASE_PY
go


ALTER TABLE FACTURA_LINEA 
	ADD CONSTRAINT FKFACTURALINEACTRCOSTO 
		FOREIGN KEY ( CENTRO_COSTO ) 
			REFERENCES CENTRO_COSTO ( CENTRO_COSTO )
go
			
			
ALTER TABLE FACTURA_LINEA 
	ADD CONSTRAINT FKFACTURALINEACTACONTA 
		FOREIGN KEY ( CUENTA_CONTABLE ) 
			REFERENCES CUENTA_CONTABLE ( CUENTA_CONTABLE )
go

ALTER TABLE FACTURA_RETENCION 
	ADD CONSTRAINT FARETFAC 
		FOREIGN KEY  	(TIPO_DOCUMENTO, FACTURA) 
 			REFERENCES FACTURA (TIPO_DOCUMENTO,FACTURA)
go


 ALTER TABLE FACTURA_RETENCION 
 	ADD CONSTRAINT RETFACTUR 
 		FOREIGN KEY 	(CODIGO_RETENCION) 
 			REFERENCES RETENCIONES 	(CODIGO_RETENCION)
go



ALTER TABLE FIADORES_DOC_FA
         ADD CONSTRAINT FKFACTURAFIADOR
         	FOREIGN KEY  ( TIPO, DOCUMENTO )
         		REFERENCES FACTURA ( TIPO_DOCUMENTO, FACTURA )
go


ALTER TABLE FIADORES_PED_FA
         ADD CONSTRAINT FKPEDIDOFIADOR
         	FOREIGN KEY  ( DOCUMENTO )
         		REFERENCES PEDIDO ( PEDIDO )
go         		


ALTER TABLE GARANTIAS_DOC_FA
         ADD CONSTRAINT FKFACTURAGARANTIA
         	FOREIGN KEY  ( TIPO, DOCUMENTO )
         		REFERENCES FACTURA ( TIPO_DOCUMENTO, FACTURA )
go         		


ALTER TABLE GARANTIAS_DOC_FA
         ADD CONSTRAINT FKARTGARANTIAFAC
         	FOREIGN KEY  ( ART_GARANTIA )
         		REFERENCES ARTICULO ( ARTICULO )
go


ALTER TABLE GARANTIAS_PED_FA
         ADD CONSTRAINT FKPEDIDOGARANTIA
         	FOREIGN KEY  ( DOCUMENTO )
         		REFERENCES PEDIDO ( PEDIDO )
go


ALTER TABLE GARANTIAS_PED_FA
         ADD CONSTRAINT FKARTGARANTIAPED
         	FOREIGN KEY  ( ART_GARANTIA )
         		REFERENCES ARTICULO ( ARTICULO )
go         		
 

 ALTER TABLE GLOBALES_FA
        ADD CONSTRAINT GLFANPPU
               FOREIGN KEY (NIV_PRE_PUBLICO, MONEDA_PUBLICO)
                              REFERENCES NIVEL_PRECIO
go
 
 
 ALTER TABLE GLOBALES_FA
        ADD CONSTRAINT GFACTRCO
               FOREIGN KEY (CTR_CONSUMO)
                              REFERENCES CENTRO_COSTO
go
 
 
 ALTER TABLE GLOBALES_FA
        ADD CONSTRAINT GFATICA
               FOREIGN KEY (TIPO_CAMBIO)
                              REFERENCES TIPO_CAMBIO
go
 
 
 ALTER TABLE GLOBALES_FA
        ADD CONSTRAINT GFACCICO
               FOREIGN KEY (CTR_IMP_COMISIO, CTA_IMP_COMISIO)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE GLOBALES_FA
        ADD CONSTRAINT GFACCIMB
               FOREIGN KEY (CTR_IMPUESTO2, CTA_IMPUESTO2)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE GLOBALES_FA
        ADD CONSTRAINT GFACCIMA
               FOREIGN KEY (CTR_IMPUESTO1, CTA_IMPUESTO1)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE GLOBALES_FA
        ADD CONSTRAINT GLFACCDO
               FOREIGN KEY (CTR_DOCUMENTACI, CTA_DOCUMENTACI)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE GLOBALES_FA
        ADD CONSTRAINT GLFACCSE
               FOREIGN KEY (CTR_SEGURO, CTA_SEGURO)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE GLOBALES_FA
        ADD CONSTRAINT GLFACCFL
               FOREIGN KEY (CTR_FLETE, CTA_FLETE)
                              REFERENCES CENTRO_CUENTA
go
 
 
 ALTER TABLE GLOBALES_FA
        ADD CONSTRAINT GLFABODE
               FOREIGN KEY (BODEGA_DEFAULT)
                              REFERENCES BODEGA
go
 
 
 ALTER TABLE GLOBALES_FA
        ADD CONSTRAINT GLFATASN
               FOREIGN KEY (TIPO_ASIENTO)
                              REFERENCES TIPO_ASIENTO
go
 
 
 ALTER TABLE GLOBALES_FA
        ADD CONSTRAINT GLFAPAQU
               FOREIGN KEY (PAQUETE)
                              REFERENCES PAQUETE
go
 
 
 ALTER TABLE GLOBALES_FA
        ADD CONSTRAINT GLFACNPG
               FOREIGN KEY (COND_PAGO_CONTAD)
                              REFERENCES CONDICION_PAGO
go


ALTER TABLE GLOBALES_FA
   	ADD CONSTRAINT CTRCTATRANGLOBFA
   		FOREIGN KEY ( CTR_INV_DESPACHAR, CTA_INV_DESPACHAR )
   			REFERENCES CENTRO_CUENTA ( CENTRO_COSTO, CUENTA_CONTABLE )
go

ALTER TABLE GLOBALES_FA 
	ADD CONSTRAINT GLOBFACATCLI 
		FOREIGN KEY (CATEGORIA_CLIENTE) 
			REFERENCES CATEGORIA_CLIENTE
go


ALTER TABLE GLOBALES_FA 
	ADD CONSTRAINT GLOBFANIVELPRE
		FOREIGN KEY (NIVEL_PRECIO, MONEDA_NIVEL) 
			REFERENCES NIVEL_PRECIO
go


 ALTER TABLE LINEASPEDIDO_EDI
        ADD CONSTRAINT LINPEDEDIPEDEDI
               FOREIGN KEY (NUMEROORDEN,GLN_COMPRADOR )
                              REFERENCES PEDIDO_EDI
go                              
 
 ALTER TABLE MONEDA_PED_BACKORD
        ADD CONSTRAINT PEDIDO_MONPEDBACK
               FOREIGN KEY (PEDIDO)
                              REFERENCES PEDIDO
go

ALTER TABLE PAQ_DESC_GRUPO
       ADD CONSTRAINT PDGRPADE
              FOREIGN KEY (PAQUETE_DESCUENTO)
                             REFERENCES PAQUETE_DESCUENTO
go                             

ALTER TABLE PAQ_DESC_GRUPO
       ADD CONSTRAINT PDGRGRUP
              FOREIGN KEY (GRUPO)
                             REFERENCES GRUPO
go                             

ALTER TABLE PAQ_DESC_REG_DESC
       ADD CONSTRAINT PDRDREDE
              FOREIGN KEY (PAQUETE_DESCUENTO)
                             REFERENCES PAQUETE_DESCUENTO
go                             

ALTER TABLE PAQ_DESC_REG_DESC
       ADD CONSTRAINT PDRDPADE
              FOREIGN KEY (REGLA_DESCUENTO)
                             REFERENCES REGLA_DESCUENTO
go                             
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT PEDICNPG
               FOREIGN KEY (CONDICION_PAGO)
                              REFERENCES CONDICION_PAGO
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT PEDICOBR
               FOREIGN KEY (COBRADOR)
                              REFERENCES COBRADOR
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT PEDIRUTA
               FOREIGN KEY (RUTA)
                              REFERENCES RUTA
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT PEDICLIEORIGEN
               FOREIGN KEY (CLIENTE_ORIGEN)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT PEDICLIECORPORAC
               FOREIGN KEY (CLIENTE_CORPORAC)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT PEDICLIEDIRECCION
               FOREIGN KEY (CLIENTE_DIRECCION)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT NIPRPEDI
               FOREIGN KEY (NIVEL_PRECIO, MONEDA)
                              REFERENCES NIVEL_PRECIO
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT SUBTIPODOC_PEDIDO
               FOREIGN KEY (TIPO_DOC_CXC, SUBTIPO_DOC_CXC)
                              REFERENCES SUBTIPO_DOC_CC
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT PEDIUSUA
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT PEDIBODE
               FOREIGN KEY (BODEGA)
                              REFERENCES BODEGA
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT PEDIZONA
               FOREIGN KEY (ZONA)
                              REFERENCES ZONA
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT PEDIPAIS
               FOREIGN KEY (PAIS)
                              REFERENCES PAIS
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT PEDICLIE
               FOREIGN KEY (CLIENTE)
                              REFERENCES CLIENTE
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT PEDIVEND
               FOREIGN KEY (VENDEDOR)
                              REFERENCES VENDEDOR
go
 
 
ALTER TABLE PEDIDO  
	ADD CONSTRAINT FKPEDIDOCANCELACOTI 
		FOREIGN KEY ( RAZON_CANCELA_COTI ) 
    			REFERENCES CANCELACION_COTIZACIONES (RAZON)
go

 
 ALTER TABLE PEDIDO_AUTORIZA
        ADD CONSTRAINT USUAPEAU
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE PEDIDO_AUTORIZA
        ADD CONSTRAINT FACTPEAU
               FOREIGN KEY (TIPO_DOCUMENTO, FACTURA)
                              REFERENCES FACTURA
go
 
 
 ALTER TABLE PEDIDO_AUTORIZA
        ADD CONSTRAINT PEDIPEAU
               FOREIGN KEY (PEDIDO)
                              REFERENCES PEDIDO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE PEDIDO_LINEA
        ADD CONSTRAINT PEDLINEAUNDMEDIDA
               FOREIGN KEY (UNIDAD_DISTRIBUCIO)
                              REFERENCES UNIDAD_DE_MEDIDA
go
 
 
 ALTER TABLE PEDIDO_LINEA
        ADD CONSTRAINT PELIBODE
               FOREIGN KEY (BODEGA)
                              REFERENCES BODEGA
go
 
 
 ALTER TABLE PEDIDO_LINEA
        ADD CONSTRAINT PELIARTI
               FOREIGN KEY (ARTICULO)
                              REFERENCES ARTICULO
go
 
 
 ALTER TABLE PEDIDO_LINEA
        ADD CONSTRAINT PELIPEDI
               FOREIGN KEY (PEDIDO)
                              REFERENCES PEDIDO
go
 
 
ALTER TABLE PEDIDO_LINEA
         ADD CONSTRAINT PEDLINLOTE
         FOREIGN KEY  ( ARTICULO, LOTE )
         REFERENCES LOTE ( ARTICULO, LOTE )
go
 
 
 ALTER TABLE PEDIDO_LINEA
        ADD CONSTRAINT PEDLINLOCALIZA
               FOREIGN KEY (BODEGA, LOCALIZACION)
                              REFERENCES LOCALIZACION
go


ALTER TABLE PEDIDO_LINEA 
        ADD CONSTRAINT PEDIDOLINEAFASEPY
               FOREIGN KEY (PROYECTO,FASE)
                              REFERENCES FASE_PY
go


ALTER TABLE PEDIDO_LINEA 
	ADD CONSTRAINT FKPEDIDOLINEACTRCOSTO 
		FOREIGN KEY ( CENTRO_COSTO ) 
			REFERENCES CENTRO_COSTO ( CENTRO_COSTO )
go			
			
						
ALTER TABLE PEDIDO_LINEA 
	ADD CONSTRAINT FKPEDIDOLINEACTACONTA 
		FOREIGN KEY ( CUENTA_CONTABLE ) 
			REFERENCES CUENTA_CONTABLE ( CUENTA_CONTABLE )
go			


ALTER TABLE PLAN_PAGO_DOC
         ADD CONSTRAINT FKPLANPAGOFACTURA
         	FOREIGN KEY  ( TIPO_DOCUMENTO, DOCUMENTO )
         		REFERENCES FACTURA ( TIPO_DOCUMENTO, FACTURA )
go



ALTER TABLE PLAN_PAGO_PED
         ADD CONSTRAINT FKPLANPAGOPEDIDO
        	 FOREIGN KEY  ( DOCUMENTO )
         		REFERENCES PEDIDO ( PEDIDO )
go     

ALTER TABLE REGLA_DESCUENTO
       ADD CONSTRAINT REDECACL
              FOREIGN KEY (CATEGORIA_CLIENTE)
                             REFERENCES CATEGORIA_CLIENTE
go                             

ALTER TABLE REGLA_DESCUENTO
       ADD CONSTRAINT REDECLI
              FOREIGN KEY (CLIENTE)
                             REFERENCES CLIENTE
go                             

ALTER TABLE REGLA_DESCUENTO
       ADD CONSTRAINT REDECLAS
              FOREIGN KEY (CLASIFICACION)
                             REFERENCES CLASIFICACION
go                             


ALTER TABLE REGLA_DESCUENTO
       ADD CONSTRAINT REDEART
              FOREIGN KEY (ARTICULO)
                             REFERENCES ARTICULO
go                             
 
 
 ALTER TABLE SUBTIPO_DOC_CC
        ADD CONSTRAINT ASOC_SUBTCB_SUBTCC
               FOREIGN KEY (TIPO_CB, SUBTIPO_CB)
                              REFERENCES SUBTIPO_DOC_CB
go
 
ALTER TABLE SUBTIPO_DOC_CC
        ADD CONSTRAINT SUBDOCCC_CTAC
               FOREIGN KEY (CENTRO_COSTO, CUENTA_CONTABLE)
                              REFERENCES CENTRO_CUENTA
go                              

ALTER TABLE USUARIO_CAJA_FA
         ADD CONSTRAINT FKCAJA_USRCAJA
         	FOREIGN KEY  ( CAJA )
         		REFERENCES CAJA ( CAJA )
go

ALTER TABLE USUARIO_CAJA_FA
         ADD CONSTRAINT FKUSR_USRCAJA
         	FOREIGN KEY  ( USUARIO )
         		REFERENCES ERPADMIN.USUARIO ( USUARIO )
go

 
 ALTER TABLE VERSION_NIVEL
        ADD CONSTRAINT VERSNIVNIVPREC
               FOREIGN KEY (NIVEL_PRECIO, MONEDA)
                              REFERENCES NIVEL_PRECIO
go
 
 