CREATE TABLE ANTICIPO_MARCA_FACT(
	TIPO 			VARCHAR(3) 	NOT NULL,
	DOCUMENTO_CC 		VARCHAR(50) 	NOT NULL,
	USUARIO 		VARCHAR(25) 	NOT NULL,
	FECHA 			DATETIME 	NOT NULL
)
go

ALTER TABLE ANTICIPO_MARCA_FACT 
	ADD CONSTRAINT PK_ANTICIPO_MARCA_FACT PRIMARY KEY NONCLUSTERED (TIPO, DOCUMENTO_CC)
go


CREATE TABLE APERTURA_CAJA (
         CAJA			VARCHAR(10)	NOT NULL,
         USUARIO		VARCHAR(25)	NOT NULL,
         NUM_APERTURA		INT		NOT NULL,
         FCH_HORA_APERTURA	DATETIME	NULL,
         FCH_HORA_CIERRE	DATETIME	NULL,
         ESTADO			VARCHAR(1)	NOT NULL,
         SALDO_INICIAL_LOC	DECIMAL(28,8)	NOT NULL,
         SALDO_FINAL_LOC	DECIMAL(28,8)	NOT NULL,
         SALDO_RECIBO_LOC	DECIMAL(28,8)	NOT NULL,
         SALDO_INICIAL_DOL	DECIMAL(28,8)	NOT NULL,
         SALDO_FINAL_DOL	DECIMAL(28,8)	NOT NULL,
         SALDO_RECIBO_DOL	DECIMAL(28,8)	NOT NULL,
         NOTAS			TEXT		NULL
		 
 )
go         


ALTER TABLE APERTURA_CAJA
         ADD CONSTRAINT PKAPERTURA_CAJA PRIMARY KEY NONCLUSTERED
        	 (USUARIO, CAJA, NUM_APERTURA )
go  
	
 
 CREATE TABLE ARTICULO_ENSAMBLE (
        ARTICULO_PADRE       VARCHAR(20) NOT NULL,
        ARTICULO_HIJO        VARCHAR(20) NOT NULL,
        CANTIDAD             DECIMAL(28,8) NOT NULL
 )
go
 
 
 ALTER TABLE ARTICULO_ENSAMBLE
        ADD CONSTRAINT ARTICULOENSAMBPK PRIMARY KEY NONCLUSTERED (
               ARTICULO_PADRE, ARTICULO_HIJO)
go
 
 
 CREATE TABLE ARTICULO_PRECIO (
        NIVEL_PRECIO         	VARCHAR(12) 	NOT NULL,
        MONEDA               	VARCHAR(1) 	NOT NULL,
        VERSION              	int 		NOT NULL,
        ARTICULO             	VARCHAR(20) 	NOT NULL,
        VERSION_ARTICULO     	int 		NOT NULL,
        PRECIO               	DECIMAL(28,8) 	NOT NULL,
        ESQUEMA_TRABAJO      	VARCHAR(1) 	NOT NULL,
        MARGEN_MULR          	DECIMAL(28,8) 	NULL,
        MARGEN_UTILIDAD      	DECIMAL(28,8) 	NOT NULL,
        FECHA_INICIO         	DATETIME 	NOT NULL,
        FECHA_FIN            	DATETIME 	NOT NULL,
        FECHA_ULT_MODIF      	DATETIME 	NULL,
        USUARIO_ULT_MODIF    	VARCHAR(25) 	NULL,
        MARGEN_UTILIDAD_MIN 	DECIMAL(28,8)	NULL
 )
go
 
 
 ALTER TABLE ARTICULO_PRECIO
        ADD CONSTRAINT XPKARTICULO_PRECIO PRIMARY KEY NONCLUSTERED (
               NIVEL_PRECIO, MONEDA, VERSION, ARTICULO, 
               VERSION_ARTICULO)
go
 
 
CREATE TABLE $$COMPANIA$$.AUXILIAR_ANTICIPO_FAC
(
	FACTURA			VARCHAR(50) 	NOT NULL,
	TIPO_FAC		VARCHAR(1)	NOT NULL,
	DOCUMENTO_CC		VARCHAR(50)	NOT NULL,
	TIPO_DOC_CC		VARCHAR(3)	NOT NULL,
	MONTO_DOCUMENTO		DECIMAL(28,8)	NULL,
	MONTO_IMPUESTO1		DECIMAL(28,8)	NULL,
	MONTO_IMPUESTO2		DECIMAL(28,8)	NULL,
	MONTO_APLICADO		DECIMAL(28,8)	NULL,
	MONTO_PENDIENTE		DECIMAL(28,8)	NULL,
	APLICADO_IMPUESTO1	DECIMAL(28,8)	NULL,
	APLICADO_IMPUESTO2	DECIMAL(28,8)	NULL,
	SALDO_IMPUESTO1		DECIMAL(28,8)	NULL,
	SALDO_IMPUESTO2		DECIMAL(28,8)	NULL
)
go


ALTER TABLE $$COMPANIA$$.AUXILIAR_ANTICIPO_FAC
       ADD CONSTRAINT XPKAUXIANTICIPOFAC
       		PRIMARY KEY (FACTURA, DOCUMENTO_CC, TIPO_FAC, TIPO_DOC_CC )
go


CREATE TABLE BITACORA_FE (

	EVENTO 			INT IDENTITY(1,1)	NOT NULL,
	DOCUMENTO 		VARCHAR(255) 		NOT NULL,
	TIPO 			VARCHAR(255) 		NOT NULL,
	DESCRIPCION 		VARCHAR(MAX) 		NOT NULL,
	REQUIERE_ATENCION 	VARCHAR(1) 		NOT NULL DEFAULT 'N'
 )
go
 
 
ALTER TABLE BITACORA_FE
	    ADD CONSTRAINT EVENTO_PK PRIMARY KEY (EVENTO)
 go
 
 
 
 CREATE TABLE BLOQUEO_IMPRESO (
        TIPO_DOCUMENTO       VARCHAR(1) NOT NULL,
        FACTURA              VARCHAR(50) NOT NULL,
        USUARIO              VARCHAR(25) NOT NULL,
        FECHA_HORA           DATETIME NOT NULL
 )
go
 
 
 ALTER TABLE BLOQUEO_IMPRESO
        ADD CONSTRAINT BLOQUEO_IMPRESOPK PRIMARY KEY NONCLUSTERED (
               TIPO_DOCUMENTO, FACTURA, USUARIO)
go

CREATE TABLE BONIF_ART_X_CLI (
       	CLIENTE           	VARCHAR(20) 		NOT NULL,
       	ARTICULO		VARCHAR(20)		NOT NULL,
	ESCALA_BONIF      	int 			NOT NULL,		
        VERSION_BONIF     	int 			NOT NULL,
       	CANTIDAD_INICIAL	int	 		NOT NULL,
       	CANTIDAD_FINAL    	int	 		NOT NULL,
       	FECHA_INICIAL     	DATETIME  		NOT NULL,
       	FECHA_FINAL       	DATETIME  		NOT NULL,
       	FACTOR_BONIF	  	decimal(15,5)		NULL,
	ARTICULO_BONIF    	VARCHAR(20) 		NOT NULL,
       	UNIDADES_BONIF    	decimal(15,5) 		NOT NULL	
)
go

ALTER TABLE BONIF_ART_X_CLI 
       ADD CONSTRAINT XPKBONIFARTXCLI 
       		PRIMARY KEY (CLIENTE, ARTICULO, ESCALA_BONIF, VERSION_BONIF)
go

CREATE TABLE BONIF_CLAS_X_CLI  (
       	CLIENTE           	VARCHAR(20) 		NOT NULL,
       	CLASIFICACION	  	VARCHAR(12)		NOT NULL,
	ESCALA_BONIF      	int 			NOT NULL,		
        VERSION_BONIF     	int 			NOT NULL,
       	CANTIDAD_INICIAL	int	 		NOT NULL,
       	CANTIDAD_FINAL    	int	 		NOT NULL,
       	FECHA_INICIAL     	DATETIME 		NOT NULL,
       	FECHA_FINAL       	DATETIME 		NOT NULL,
       	FACTOR_BONIF	  	decimal(15,5)		NULL,
	ARTICULO_BONIF    	VARCHAR(20) 		NOT NULL,
       	UNIDADES_BONIF    	decimal(15,5)		NOT NULL	
)
go

ALTER TABLE BONIF_CLAS_X_CLI 
       ADD CONSTRAINT XPKBONIFCLAXCLI 
       		PRIMARY KEY (CLIENTE, CLASIFICACION, ESCALA_BONIF, VERSION_BONIF)
go
 

CREATE TABLE CAJA (
         CAJA			VARCHAR(10)		NOT NULL,
         DESCRIPCION		VARCHAR(250)		NOT NULL,
         ESTADO			VARCHAR(1)		NOT NULL,
         ACTIVO_FIJO		VARCHAR(10)		NULL,
         NOTAS			TEXT			NULL 
)
go


ALTER TABLE CAJA
         ADD CONSTRAINT PKCAJA PRIMARY KEY NONCLUSTERED
         (CAJA )
go         


CREATE TABLE CANCELACION_COTIZACIONES(
      RAZON 		VARCHAR(10) 	NOT NULL,
      DESCRIPCION	VARCHAR(50) 	NOT NULL
)
go
      
ALTER TABLE CANCELACION_COTIZACIONES  ADD CONSTRAINT PK_CANCELACION_COTIZACIONES PRIMARY KEY NONCLUSTERED (RAZON)
go

 
CREATE TABLE CLIENTE (
        CLIENTE              		VARCHAR(20) 	NOT NULL,
        NOMBRE               		VARCHAR(150) 	NOT NULL,
        DETALLE_DIRECCION    		int 		NULL,
        ALIAS                		VARCHAR(150) 	NULL,
        CONTACTO             		VARCHAR(30) 	NOT NULL,
        CARGO                		VARCHAR(30) 	NOT NULL,
        DIRECCION            		TEXT 		NULL,
        DIR_EMB_DEFAULT      		VARCHAR(8) 	NULL,
        TELEFONO1            		VARCHAR(50) 	NOT NULL,
        TELEFONO2            		VARCHAR(50) 	NOT NULL,
        FAX                  		VARCHAR(50) 	NOT NULL,
        CONTRIBUYENTE        		VARCHAR(20) 	NOT NULL,
        FECHA_INGRESO        		DATETIME 	NOT NULL,
        MULTIMONEDA          		VARCHAR(1) 	NOT NULL,
        MONEDA               		VARCHAR(4) 	NOT NULL,
        SALDO                		DECIMAL(28,8) 	NOT NULL,
        SALDO_LOCAL          		DECIMAL(28,8) 	NOT NULL,
        SALDO_DOLAR          		DECIMAL(28,8) 	NOT NULL,
        SALDO_CREDITO        		DECIMAL(28,8) 	NOT NULL,
        SALDO_NOCARGOS       		DECIMAL(28,8) 	NULL,
        LIMITE_CREDITO       		DECIMAL(28,8) 	NULL,
        EXCEDER_LIMITE       		VARCHAR(1) 	NOT NULL,
        TASA_INTERES         		DECIMAL(28,8) 	NOT NULL,
        TASA_INTERES_MORA    		DECIMAL(28,8) 	NOT NULL,
        FECHA_ULT_MORA       		DATETIME 	NOT NULL,
        FECHA_ULT_MOV        		DATETIME 	NOT NULL,
        CONDICION_PAGO       		VARCHAR(4) 	NOT NULL,
        NIVEL_PRECIO         		VARCHAR(12) 	NOT NULL,
        DESCUENTO            		DECIMAL(28,8) 	NOT NULL,
        MONEDA_NIVEL         		VARCHAR(1) 	NOT NULL,
        ACEPTA_BACKORDER     		VARCHAR(1) 	NOT NULL,
        PAIS                 		VARCHAR(4) 	NOT NULL,
        ZONA                 		VARCHAR(4) 	NOT NULL,
        RUTA                 		VARCHAR(4) 	NOT NULL,
        VENDEDOR             		VARCHAR(4) 	NULL,
        COBRADOR             		VARCHAR(4) 	NOT NULL,
        ACEPTA_FRACCIONES    		VARCHAR(1) 	NOT NULL,
        ACTIVO               		VARCHAR(1) 	NOT NULL,
        EXENTO_IMPUESTOS     		VARCHAR(1) 	NOT NULL,
        EXENCION_IMP1        		DECIMAL(28,8) 	NOT NULL,
        EXENCION_IMP2        		DECIMAL(28,8) 	NOT NULL,
        COBRO_JUDICIAL       		VARCHAR(1) 	NOT NULL,
        CATEGORIA_CLIENTE    		VARCHAR(8) 	NOT NULL,
        CLASE_ABC            		VARCHAR(1) 	NULL,
        DIAS_ABASTECIMIEN    		smallint 	NOT NULL,
        USA_TARJETA          		VARCHAR(1) 	NOT NULL,
        TARJETA_CREDITO      		VARCHAR(20) 	NULL,
        TIPO_TARJETA         		VARCHAR(12) 	NULL,
        FECHA_VENCE_TARJ     		DATETIME 	NULL,
        E_MAIL               		VARCHAR(249) 	NULL,
        REQUIERE_OC          		VARCHAR(1) 	NOT NULL,
        ES_CORPORACION       		VARCHAR(1) 	NOT NULL,
        CLI_CORPORAC_ASOC    		VARCHAR(20)	NULL,
        REGISTRARDOCSACORP   		VARCHAR(1) 	NOT NULL,
        USAR_DIREMB_CORP     		VARCHAR(1) 	NOT NULL,
        APLICAC_ABIERTAS     		VARCHAR(1) 	NOT NULL,
        VERIF_LIMCRED_CORP   		VARCHAR(1) 	NOT NULL,
        USAR_DESC_CORP       		VARCHAR(1) 	NOT NULL,
        DOC_A_GENERAR        		VARCHAR(1) 	NOT NULL,
        RUBRO1_CLIENTE       		VARCHAR(40)	NULL,
        RUBRO2_CLIENTE       		VARCHAR(40)	NULL,
        RUBRO3_CLIENTE       		VARCHAR(40)	NULL,
        TIENE_CONVENIO       		VARCHAR(1) 	NOT NULL,
        NOTAS                		TEXT 		NULL,
        DIAS_PROMED_ATRASO   		smallint 	NOT NULL,
        RUBRO1_CLI           		VARCHAR(50) 	NULL,
        RUBRO2_CLI           		VARCHAR(50) 	NULL,
        RUBRO3_CLI           		VARCHAR(50) 	NULL,
        RUBRO4_CLI           		VARCHAR(50) 	NULL,
        RUBRO5_CLI           		VARCHAR(50) 	NULL,
        ASOCOBLIGCONTFACT    		VARCHAR(1) 	NOT NULL,
        RUBRO4_CLIENTE       		VARCHAR(40) 	NULL,
        RUBRO5_CLIENTE       		VARCHAR(40) 	NULL,
        RUBRO6_CLIENTE       		VARCHAR(40) 	NULL,
        RUBRO7_CLIENTE       		VARCHAR(40) 	NULL,
        RUBRO8_CLIENTE       		VARCHAR(40) 	NULL,
        RUBRO9_CLIENTE       		VARCHAR(40) 	NULL,
        RUBRO10_CLIENTE      		VARCHAR(40) 	NULL,
        USAR_PRECIOS_CORP    		VARCHAR(1) 	NOT NULL,
        USAR_EXENCIMP_CORP   		VARCHAR(1) 	NOT NULL,
        DIAS_DE_COBRO 	     		VARCHAR(13) 	NULL,
        AJUSTE_FECHA_COBRO   		VARCHAR(1)	NOT NULL,
		GLN 	   	     			VARCHAR(13)	NULL,
		UBICACION  	     			VARCHAR(10)	NULL,
		CLASE_DOCUMENTO      		VARCHAR(1) 	NOT NULL,
		LOCAL                		VARCHAR(1) 	DEFAULT ('L')	NOT NULL,
		TIPO_CONTRIBUYENTE   		VARCHAR(1) 	NULL,
		RUBRO11_CLIENTE      		VARCHAR(40)	NULL,
		RUBRO12_CLIENTE      		VARCHAR(40)	NULL,
		RUBRO13_CLIENTE      		VARCHAR(40)	NULL,
		RUBRO14_CLIENTE      		VARCHAR(40)	NULL,
		RUBRO15_CLIENTE      		VARCHAR(40)	NULL,
		RUBRO16_CLIENTE      		VARCHAR(40)	NULL,
		RUBRO17_CLIENTE      		VARCHAR(40)	NULL,
		RUBRO18_CLIENTE      		VARCHAR(40)	NULL,
		RUBRO19_CLIENTE      		VARCHAR(40)	NULL,
		RUBRO20_CLIENTE      		VARCHAR(40)	NULL,
		MODELO_RETENCION     		VARCHAR(4) 	NULL,
		ACEPTA_DOC_ELECTRONICO		VARCHAR(1)	DEFAULT ('N')	NOT NULL ,
		CONFIRMA_DOC_ELECTRONICO	VARCHAR(1)	DEFAULT ('N') 	NOT NULL ,
		EMAIL_DOC_ELECTRONICO		VARCHAR(249)	NULL,
		EMAIL_PED_EDI 				VARCHAR(249) 	NULL,
		ACEPTA_DOC_EDI 				VARCHAR(1) 	NOT NULL DEFAULT 'N',
		NOTIFICAR_ERROR_EDI 		VARCHAR(1) 	NOT NULL DEFAULT 'N',
		EMAIL_ERROR_PED_EDI 		VARCHAR(249) 	NULL,
		CODIGO_IMPUESTO 			VARCHAR(4)      NULL,
		DIVISION_GEOGRAFICA1		VARCHAR(12)	NULL,
		DIVISION_GEOGRAFICA2		VARCHAR(12)	NULL,
		REGIMEN_TRIB				VARCHAR(12)	NULL,
		MOROSO 						VARCHAR(1) 	NOT NULL DEFAULT 'N',
		MODIF_NOMB_EN_FAC 			VARCHAR(1) 	NOT NULL DEFAULT 'N',
		SALDO_TRANS 				DECIMAL(28,8) 	NOT NULL DEFAULT 0,
		SALDO_TRANS_LOCAL 			DECIMAL(28,8) 	NOT NULL DEFAULT 0,
		SALDO_TRANS_DOLAR 			DECIMAL(28,8) 	NOT NULL DEFAULT 0,
		PERMITE_DOC_GP				VARCHAR(1) 	NOT NULL DEFAULT 'N',
		PARTICIPA_FLUJOCAJA			VARCHAR(1)	NOT NULL DEFAULT 'N',
		CURP	 					VARCHAR(18) 	NULL,
		USUARIO_CREACION			VARCHAR(25)	NULL,
		FECHA_HORA_CREACION			DATETIME	NULL,
		USUARIO_ULT_MOD				VARCHAR(25)	NULL,
		FCH_HORA_ULT_MOD			DATETIME	NULL,
		EMAIL_DOC_ELECTRONICO_COPIA VARCHAR(249) 	NULL,
		DETALLAR_KITS 				VARCHAR(1) 	NOT NULL DEFAULT 'N',
		XSLT_PERSONALIZADO 			VARCHAR(20) 	NULL,
		NOMBRE_ADDENDA 				VARCHAR(20) 	NULL,
		GEO_LATITUD 				DECIMAL(28, 12) NULL,
		GEO_LONGITUD 				DECIMAL(28, 12) NULL,
		DIVISION_GEOGRAFICA3 		VARCHAR(12)  NULL,
		DIVISION_GEOGRAFICA4 		VARCHAR(12)  NULL,
		OTRAS_SENAS 				VARCHAR(160) NULL,
		SUBTIPODOC 					VARCHAR(25) NULL
 )
go
 
 
 ALTER TABLE CLIENTE
        ADD CONSTRAINT CLIENTEPK PRIMARY KEY NONCLUSTERED (CLIENTE)
go


CREATE TABLE CLIENTE_RETENCION (
        CLIENTE     	          VARCHAR(20) NOT NULL,
        CODIGO_RETENCION          VARCHAR(4)  NOT NULL,
        NOTAS                     TEXT        NULL
 )
go

  
 ALTER TABLE CLIENTE_RETENCION
        ADD CONSTRAINT XPKCLIENTE_RETENCI PRIMARY KEY (CLIENTE,CODIGO_RETENCION)
go

 
 
 CREATE TABLE CLIENTE_VENDEDOR (
        CLIENTE              VARCHAR(20) NOT NULL,
        VENDEDOR             VARCHAR(4) NOT NULL
 )
go
 
 
 ALTER TABLE CLIENTE_VENDEDOR
        ADD CONSTRAINT CLIENTE_VENDEDORPK PRIMARY KEY NONCLUSTERED (
               CLIENTE, VENDEDOR)
go


CREATE TABLE CONFIG_CLIENTE (
	CAMPO		 VARCHAR(30)	NOT NULL,
	VISIBLE          VARCHAR(1)   	NOT NULL,
       	ORDEN            INT	   	NOT NULL 
)
go

ALTER TABLE CONFIG_CLIENTE 
       ADD CONSTRAINT XPKCONFIGCLIENTE PRIMARY KEY (CAMPO)
go
 

CREATE TABLE CONSECUFA_USUARIO (
         USUARIO         	VARCHAR(25)         NOT NULL,
         CODIGO_CONSECUTIVO     VARCHAR(10)         NOT NULL 
)
go         

ALTER TABLE CONSECUFA_USUARIO
         ADD CONSTRAINT PKCONSECUUSUARIO PRIMARY KEY NONCLUSTERED
         (USUARIO, CODIGO_CONSECUTIVO )
go         

 
 CREATE TABLE CONSECUTIVO_FA (
        CODIGO_CONSECUTIVO   VARCHAR(10) 	NOT NULL,
        USUARIO_ULT          VARCHAR(25) 	NOT NULL,
        DESCRIPCION          VARCHAR(40) 	NOT NULL,
        TIPO                 VARCHAR(1) 	NOT NULL,
        LONGITUD             smallint 		NOT NULL,
        VALOR_CONSECUTIVO    VARCHAR(50) 	NOT NULL,
        MASCARA              VARCHAR(50) 	NULL,
        FECHA_HORA_ULT       DATETIME 		NOT NULL,
        FORMATO              VARCHAR(250) 	NOT NULL,
        USA_DESPACHOS 	     VARCHAR(1) 	NOT NULL,
        USA_ESQUEMA_CAJAS    VARCHAR(1) 	NOT NULL,
        VALOR_MAXIMO 	     VARCHAR(50) 	NOT NULL,
        NUMERO_COPIAS 	     int 		NOT NULL DEFAULT 0,
		ORIGINAL 	     VARCHAR(30) 	NULL,
		COPIA1 		     VARCHAR(30) 	NULL,
		COPIA2 		     VARCHAR(30) 	NULL,
		COPIA3 		     VARCHAR(30) 	NULL,
		COPIA4 		     VARCHAR(30) 	NULL,
		COPIA5 		     VARCHAR(30) 	NULL,
		REIMPRESION 	     VARCHAR(30) 	NULL,
		RESOLUCION	     VARCHAR(20) 	NULL,
		SERIE 		     VARCHAR(25) 	NULL,
		DE_CONS_RPT VARCHAR(254) NULL,
		VALOR_INICIAL VARCHAR(50) NULL
 )
go
 
 
 ALTER TABLE CONSECUTIVO_FA
        ADD CONSTRAINT XPKCONSECUTIVOS_FA PRIMARY KEY NONCLUSTERED (
               CODIGO_CONSECUTIVO)
go
 
 
 CREATE TABLE CONTACTOS (
 	GLN        		VARCHAR(13) 		NOT NULL,
 	CEDULAJURIDICA		VARCHAR(20) 		NOT NULL,
 	NOMBRE		  	VARCHAR(150) 		NOT NULL,
 	EMAIL_EDI		VARCHAR(80)
 )
go
 
  
 ALTER TABLE CONTACTOS
         ADD CONSTRAINT CONTACTOSPK 
         	PRIMARY KEY (GLN )
go

CREATE TABLE DCTO_ART_X_CLI (
       	CLIENTE           	VARCHAR(20) 		NOT NULL,
       	ARTICULO	  	VARCHAR(20)		NOT NULL,		
	ESCALA_DCTO       	int			NOT NULL,
        VERSION_DCTO      	int			NOT NULL,
       	CANTIDAD_INICIAL  	int			NULL,
       	CANTIDAD_FINAL    	int			NULL,
       	FECHA_INICIAL     	DATETIME  		NULL,
       	FECHA_FINAL       	DATETIME  		NULL,
       	PORC_DESCUENTO    	decimal(15,5)		NOT NULL,
       	TIPO_DESCUENTO    	VARCHAR(1) 		NOT NULL	
)
go

ALTER TABLE DCTO_ART_X_CLI 
       ADD CONSTRAINT XPKDCTOARTXCLI 
       		PRIMARY KEY (CLIENTE, ARTICULO, ESCALA_DCTO, VERSION_DCTO, TIPO_DESCUENTO)
go

CREATE TABLE DCTO_CLAS_X_CLI (
       	CLIENTE           	VARCHAR(20) 		NOT NULL,
       	CLASIFICACION	  	VARCHAR(12)		NOT NULL,		
	ESCALA_DCTO       	int 			NOT NULL,
        VERSION_DCTO      	int 			NOT NULL,
       	CANTIDAD_INICIAL	int	 		NULL,
       	CANTIDAD_FINAL    	int	 		NULL,
       	FECHA_INICIAL     	DATETIME 		NULL,
       	FECHA_FINAL       	DATETIME 		NULL,
       	PORC_DESCUENTO    	decimal(15,5)		NOT NULL,
       	TIPO_DESCUENTO    	VARCHAR(1) 		NOT NULL	
)
go

ALTER TABLE DCTO_CLAS_X_CLI  
       ADD CONSTRAINT XPKDCTOCLAXCLI 
       		PRIMARY KEY (CLIENTE, CLASIFICACION, ESCALA_DCTO, VERSION_DCTO, TIPO_DESCUENTO)
go
 

CREATE TABLE DES_BON_ESPECIFICACION_GRUPO(
	ESCALA 				INT IDENTITY(1,1) NOT NULL,
	REGLA 				varchar(20) NOT NULL,
	ARTICULO 			varchar(20) NULL,
	CANTIDAD_MINIMA 	decimal(28, 8) NOT NULL,
	CANTIDAD_MAXIMA 	decimal(28, 8) NOT NULL
)
go 

ALTER TABLE $$COMPANIA$$.DES_BON_ESPECIFICACION_GRUPO 
	ADD  CONSTRAINT PK_ESPECIFICACION_GRUPO 
		PRIMARY KEY  (ESCALA ASC, REGLA ASC)
go
 
 
CREATE TABLE DES_BON_PAQUETE(
	PAQUETE 		VARCHAR(20) 	NOT NULL,
	DESCRIPCION 		VARCHAR(40) 	NOT NULL,
	ACTIVO 			VARCHAR(1)	NOT NULL,
	FECHA_DESDE 		DATETIME 	NOT NULL,
	FECHA_HASTA 		DATETIME 	NOT NULL,
	PRIORIDAD 		INTEGER 	NULL,
	DIAS 			TEXT		NULL,
	APLICA_TODA_TIENDA 	VARCHAR(1) 	NOT NULL DEFAULT ('S'),
	APLICA_TODA_RUTA 	VARCHAR(1) 	NOT NULL DEFAULT ('S')
)
go

ALTER TABLE DES_BON_PAQUETE ADD CONSTRAINT PK_PAQUETE PRIMARY KEY (PAQUETE)
go


CREATE TABLE DES_BON_PAQUETE_TIENDA (
	PAQUETE 	VARCHAR(20) 	NOT NULL,
	TIENDA		VARCHAR(6)	NOT NULL
)
go

ALTER TABLE DES_BON_PAQUETE_TIENDA ADD CONSTRAINT DESBONPAQUETETIENDAPK  PRIMARY KEY (PAQUETE, TIENDA)
go



CREATE TABLE DES_BON_REGLA(
	REGLA 				VARCHAR(20) 	NOT NULL,
	DESCRIPCION 			VARCHAR(40) 	NOT NULL,
	TIPO 				VARCHAR(1) 	NOT NULL,
	ACTIVA 				VARCHAR(1) 	NOT NULL,
	FILTRO_CLIENTE 			TEXT		NULL,
	VALIDAR_CANTIDAD 		VARCHAR(10) 	NOT NULL,
	CANTIDAD_MINIMA 		DECIMAL(28,8)	NULL,
	CANTIDAD_MAXIMA 		DECIMAL(28,8)	NULL,
	FILTRO_ARTICULO 		TEXT		NULL,
	TIPO_DESCUENTO 			VARCHAR(1) 	NOT NULL,
	TIPO_VALOR 			VARCHAR(1) 	NOT NULL,
	VALOR 				DECIMAL(28,8) 	NULL,	
	TIPO_BONIFICACION 		VARCHAR(1) 	NOT NULL,
	UTILIZAR_ARTICULO_LINEA 	VARCHAR(1) 	NOT NULL,
	FILTRO_ARTICULO_BONIFICACION 	TEXT	NULL,
	APLICACION_GRUPOS 		VARCHAR(1) 	NOT NULL,
	PRIORIDAD  			INTEGER  	NULL,
	MONTO_MINIMO 			DECIMAL(28,8)	NOT NULL DEFAULT (0),
	CATEGORIA_MEMBRESIA 		VARCHAR(8) 	NULL,
	FORMA_PAGO 			VARCHAR(4) 	NULL,
	DETALLE_FORMA_PAGO 		VARCHAR(20) 	NULL,
	MINIMO_PAGO 			DECIMAL(28,8)	NULL,
	REQUIERE_AUTORIZACION 		VARCHAR(1) 	NOT NULL DEFAULT ('N'),
	CANTIDAD_MIN_DETALLE 		DECIMAL(28,8)	NULL,
	CANTIDAD_MAX_DETALLE 		DECIMAL(28,8)	NULL,
	CANTIDAD_ALMACEN_COMPRA 	DECIMAL(28,8) 	NULL,
	CANTIDAD_ALMACEN_DESCONTAR 	DECIMAL(28,8) 	NULL,
	CANTIDAD_DETALLE_COMPRA 	DECIMAL(28,8) 	NULL,
	CANTIDAD_DETALLE_DESCONTAR 	DECIMAL(28,8) 	NULL,
	APLICA_ARTICULO_MENOR_PRECIO 	VARCHAR(1) 	NOT NULL DEFAULT ('N'),
	AGRUPACION_ARTICULO  		VARCHAR(1) 	NOT NULL DEFAULT ('N'),
	FILTRO_LOTE      		TEXT 		NULL,
	TIPO_REGLA_LOTE 	 	VARCHAR(1) 	NOT NULL DEFAULT 'M',
	MONTO_DESDE     	 	DECIMAL(28,8) 	NULL,
	MONTO_HASTA     		DECIMAL(28,8) 	NULL,
	CANTIDAD_LIMITE DECIMAL(28,8) NOT NULL DEFAULT (0),
	ESPECIFICACION_GRUPO VARCHAR(1) NOT NULL DEFAULT('N')
	
)
go

ALTER TABLE DES_BON_REGLA ADD CONSTRAINT PK_REGLA PRIMARY KEY (REGLA)
go




CREATE TABLE DES_BON_REGLA_LOTE(
	REGLA 		VARCHAR(20) 	NOT NULL,
	LINEA_REGLA 	INT 		NOT NULL,
	DIAS_DESDE 	INT 		NULL,
	DIAS_HASTA 	INT 		NULL,
	CANT_MESES 	INT 		NULL,
	DESCUENTO 	DECIMAL(28,8) 	NULL)
go


ALTER TABLE DES_BON_REGLA_LOTE 
       ADD CONSTRAINT XPKREGLALOTE 
       		PRIMARY KEY (REGLA, LINEA_REGLA)

go  



CREATE TABLE DES_BON_PAQUETE_REGLA(
	PAQUETE 		VARCHAR(20) 	NOT NULL,
	REGLA 			VARCHAR(20) 	NOT NULL
)
go

ALTER TABLE DES_BON_PAQUETE_REGLA ADD CONSTRAINT PK_PAQUETE_REGLA PRIMARY KEY (PAQUETE,REGLA)
go



CREATE TABLE DES_BON_PAQUETE_RUTA (
	PAQUETE 	VARCHAR(20) 	NOT NULL,
	RUTA        	VARCHAR(4) 	NOT NULL
)
go

ALTER TABLE DES_BON_PAQUETE_RUTA  ADD CONSTRAINT DESBONPAQUETERUTAPK PRIMARY KEY (PAQUETE, RUTA)
go




CREATE TABLE DES_BON_ESCALA_BONIFICACION(
	ESCALA 				INT IDENTITY(1,1) 	NOT NULL,
	REGLA 				VARCHAR(20) 		NOT NULL,
	ARTICULO 			VARCHAR(20)		NULL,
	CANTIDAD_MINIMA 		DECIMAL(28,8) 		NOT NULL,
	CANTIDAD_MAXIMA 		DECIMAL(28,8) 		NOT NULL,
	FACTOR 				DECIMAL(28,8) 		NOT NULL,
	CANTIDAD_INICIAL 		DECIMAL(28,8) 		NOT NULL,
	CANTIDAD_PEDIDA 		DECIMAL(28,8) 		NOT NULL,
	UNIDAD_ALMACEN 			DECIMAL(28,8) 		NULL,
	UNIDAD_DETALLE 			DECIMAL(28,8) 		NULL,
	CANT_MINIMA_DET 		DECIMAL(28,8)		NOT NULL,
	CANT_MAXIMA_DET 		DECIMAL(28,8)		NOT NULL,
	FACTOR_DET 			DECIMAL(28,8) 		NOT NULL 	DEFAULT 0,
	CANTIDAD_INICIAL_DET 		DECIMAL(28,8) 		NOT NULL 	DEFAULT 0,
	CANTIDAD_INICIAL_CONSOL 	DECIMAL(28,8) 		NOT NULL 	DEFAULT 0
)
go

ALTER TABLE DES_BON_ESCALA_BONIFICACION ADD CONSTRAINT PK_ESCALA_BONIFICACION PRIMARY KEY (ESCALA,REGLA)
go
	
	



CREATE TABLE DESPACHO (
	DESPACHO		VARCHAR(20)		NOT NULL,
	CONSECUTIVO		VARCHAR(10)		NOT NULL,
	CLIENTE			VARCHAR(20)		NOT NULL,
	FECHA			DATETIME		NOT NULL,
	TRANSPORTISTA		VARCHAR(80)		NULL,
	NOTAS_TRANSPORTE	VARCHAR(255)		NULL,
	DIRECCION_EMBARQUE	VARCHAR(8)		NULL,
	EMBARCAR_A		VARCHAR(80)		NULL,
	ESTADO			VARCHAR(1)		NOT NULL,
	OBSERVACIONES		TEXT			NULL,
	FCH_HORA_CREACION	DATETIME		NOT NULL,
	USUARIO_CREACION	VARCHAR(25)		NOT NULL,
	FCH_HORA_ULT_MODIF	DATETIME		NULL,
	USUARIO_ULT_MODIF	VARCHAR(25)		NULL,
	FCH_HORA_ANULACION	DATETIME		NULL,
	USUARIO_ANULACION	VARCHAR(25)		NULL,
	FCH_HORA_APLICACION	DATETIME		NULL,
	USUARIO_APLICACION	VARCHAR(25)		NULL,
	CARGADO_CG		VARCHAR(1)		NOT NULL,
	ASIENTO_DESPACHO	VARCHAR(10)		NULL,
	AUDIT_TRANS_INV		int			NULL,
	USUARIO_APROBACION      VARCHAR(25)     	NULL,
	FCH_HORA_APROBACIO      DATETIME        	NULL
)
go

ALTER TABLE DESPACHO 
	ADD CONSTRAINT XPKDESPACHO PRIMARY KEY NONCLUSTERED 
	(DESPACHO)
go



CREATE TABLE DESPACHO_DETALLE (
	DESPACHO		VARCHAR(20)	NOT NULL,
	LINEA			smallint	NOT NULL,
	ARTICULO		VARCHAR(20)	NOT NULL,
	BODEGA			VARCHAR(4)	NOT NULL,
	CANTIDAD		DECIMAL(28,8)	NOT NULL,
	LOTE			VARCHAR(15)	NULL,
	LOCALIZACION		VARCHAR(8)	NULL,
	COSTO_LOCAL		DECIMAL(28,8)	NOT NULL,
	COSTO_DOLAR		DECIMAL(28,8)	NOT NULL,
	DOCUM_ORIG		VARCHAR(50)	NOT NULL,
	TIPO_DOCUM_ORIG		VARCHAR(1)	NOT NULL,
	LINEA_DOCUM_ORIG	smallint	NOT NULL,
	SERIE_CADENA		int		NULL,
	TIPO_LINEA		VARCHAR(1)	NOT NULL,
	LINEA_KIT		smallint	NULL,
	CONSEC_TINV_INI 	int 		NULL,
	CONSEC_TINV_FIN 	int 		NULL,
	COSTO_LOCAL_COMP	DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	COSTO_DOLAR_COMP	DECIMAL(28,8) 	NOT NULL DEFAULT 0
)
go


ALTER TABLE DESPACHO_DETALLE 
	ADD CONSTRAINT XPKDESPACHODET PRIMARY KEY NONCLUSTERED 
	(DESPACHO, LINEA)
go


CREATE TABLE  DETALLE_FACTURA_RETENCION(
	RETENCION 		VARCHAR(4),
	FACTURA   		VARCHAR(50),
	TIPO_DOC  		VARCHAR(3),
	FACTURA_LINEA 	INT,
	ARTICULO  		VARCHAR(20),
	BASE_RETENCION 	DECIMAL(28,8),
	MONTO_RETENCION DECIMAL(28,8)
)
go


 
 CREATE TABLE DIRECC_EMBARQUE (
        CLIENTE              VARCHAR(20) NOT NULL,
        DIRECCION            VARCHAR(8) NOT NULL,
        DETALLE_DIRECCION    int NULL,
        DESCRIPCION          TEXT  NULL,
        CONTACTO             VARCHAR(30) NULL,
        CARGO                VARCHAR(30) NULL,
        TELEFONO1            VARCHAR(50) NULL,
        TELEFONO2            VARCHAR(50) NULL,
        FAX                  VARCHAR(50) NULL,
        EMAIL                VARCHAR(40) NULL
 )
go
 
 
 ALTER TABLE DIRECC_EMBARQUE
        ADD CONSTRAINT DIRECCEMBARQUEPK PRIMARY KEY NONCLUSTERED (
               CLIENTE, DIRECCION)
go


CREATE TABLE DOCUMENTO_ANTICIPO(
	TIPO_DOCUMENTO 		VARCHAR(1) 	NOT NULL,
	DOCUMENTO 		VARCHAR(50) 	NOT NULL,
	DOCUMENTO_CC 		VARCHAR(50) 	NOT NULL,
	TIPO_CC 		VARCHAR(3) 	NOT NULL,
	MONTO 			DECIMAL(28, 8) 	NOT NULL DEFAULT 0
)
go


ALTER TABLE DOCUMENTO_ANTICIPO
        ADD CONSTRAINT PK_DOCUMENTO_ANTICIPO PRIMARY KEY NONCLUSTERED (TIPO_DOCUMENTO, DOCUMENTO, DOCUMENTO_CC, TIPO_CC)
go
        
        

CREATE TABLE DOCUMENTO_ELECTRONICO(
	TIPO_DOC		INT			NOT NULL,
	NUMERO_DOC		DECIMAL(28,8)		NOT NULL,
	NIT_EMISOR		VARCHAR(40)		NOT NULL,
	EMAIL_EMISOR		VARCHAR(40)		NOT NULL,
	GLN_EMISOR		VARCHAR(13)		NOT NULL,
	NIT_RECEPTOR		VARCHAR(40)		NOT NULL,
	EMAIL_RECEPTOR		VARCHAR(40)		NOT NULL,
	GLN_RECEPTOR		VARCHAR(13)		NOT NULL,
	ENVIADO			VARCHAR(1)		NOT NULL,
	ACEPTADO		VARCHAR(1)		NULL,
	CARGADO_ERP		VARCHAR(1)		NULL,
	NUMERO_RECEPCION	DECIMAL(28,8)		NULL,
	CANTIDAD_IMPRESIONES	INT			NOT NULL,
	DOCUMENTO_ELECTRONICO	XML			NULL,
	ACEPTACION_RECHAZO	XML			NULL, 
	NOMBRE_PDF		VARCHAR(255)		NULL,
	DOCUMENTO_ELECTRONICO_TEXT nvarchar(MAX) 	NULL
)
go

ALTER TABLE DOCUMENTO_ELECTRONICO
	ADD CONSTRAINT XPKDOCELEC 
		PRIMARY KEY (TIPO_DOC,NUMERO_DOC,NIT_EMISOR)
go



CREATE TABLE DOCUMENTO_ELECTRONICO_FA(
	TIPO_DOC			INT			NOT NULL,
	NUMERO_DOC			VARCHAR(50)		NOT NULL,
	NIT_EMISOR			VARCHAR(40)		NOT NULL,
	EMAIL_EMISOR			VARCHAR(40)		NOT NULL,
	GLN_EMISOR			VARCHAR(13)		NULL,
	NIT_RECEPTOR			VARCHAR(40)		NOT NULL,
	EMAIL_RECEPTOR			VARCHAR(40)		NOT NULL,
	GLN_RECEPTOR			VARCHAR(13)		NULL,
	ENVIADO				VARCHAR(1)		NOT NULL,
	ACEPTADO			VARCHAR(1)		NULL,
	CARGADO_ERP			VARCHAR(1)		NULL,
	NUMERO_RECEPCION		DECIMAL(28,8)		NULL,
	CANTIDAD_IMPRESIONES		INT			NOT NULL,
	DOCUMENTO_ELECTRONICO		XML			NULL,
	ACEPTACION_RECHAZO		XML			NULL, 
	NOMBRE_PDF			VARCHAR(255)		NULL,
	DOCUMENTO_ELECTRONICO_TEXT 	nvarchar(MAX) 		NULL,
	CONSECUTIVO_RESOLUCION 		INT			NULL,
	SERIE 				VARCHAR(20) 		NULL,
	CONSECUTIVO 			INT 			NULL
)
go



ALTER TABLE DOCUMENTO_ELECTRONICO_FA
	ADD CONSTRAINT XPKDOCELECFA PRIMARY KEY (TIPO_DOC,NUMERO_DOC,NIT_EMISOR)
go


CREATE TABLE DOC_ELECTRONICO_PROCESADO(
	TIPO_DOC				VARCHAR(3)	NOT NULL,
	NUMERO_DOC				VARCHAR(50)	NOT NULL,
	NIT_EMISOR				VARCHAR(40)	NOT NULL,
	MODULO					VARCHAR(2)	NOT NULL,
	EMAIL_EMISOR				VARCHAR(255)	NULL,
	GLN_EMISOR				VARCHAR(13)	NOT NULL,
	NIT_RECEPTOR				VARCHAR(40)	NOT NULL,
	EMAIL_RECEPTOR				VARCHAR(255)	NULL,
	GLN_RECEPTOR				VARCHAR(13)	NOT NULL,
	ENVIADO					VARCHAR(1)	NOT NULL,
	ACEPTADO				VARCHAR(1)	NULL,
	CARGADO_ERP				VARCHAR(1)	NULL,
	NUMERO_RECEPCION			DECIMAL(28,8)	NULL,
	CANTIDAD_IMPRESIONES			INT		NULL,
	DOCUMENTO_ELECTRONICO			XML		NULL,
	ACEPTACION_RECHAZO			XML		NULL, 
	NOMBRE_PDF				VARCHAR(255)	NULL,
	FIRMA_DOCUMENTO 			VARCHAR(MAX)	NULL,
	FECHA_HORA           			DATETIME 	NOT NULL DEFAULT (ERPADMIN.SF_GETDATE()),
	ESTADO               			VARCHAR(1) 	NOT NULL DEFAULT ('N'),
	FOLIO_SAT 				VARCHAR(36) 	NULL,
	CADENA_ORIGINAL 			VARCHAR(MAX)	NULL,
	NOCERTIFICADO 				VARCHAR(20)	NULL,
	FECHATIMBRADO 				VARCHAR (21)	NULL,
	NOCERTIFICADOSAT 			VARCHAR(20)	NULL,
	SELLOSAT 				VARCHAR(MAX)	NULL,
	SELLOCDF 				VARCHAR (MAX)	NULL,
	NOMBRE_XML 				VARCHAR(255) 	NULL,
	CONTIENE_ERRORES 			VARCHAR(1)      NULL,
	NUMERO_CAE 				VARCHAR(MAX) 	NULL,
	NUMERO_DTE 				VARCHAR(MAX) 	NULL,
	XML_TEMP 				NVARCHAR(MAX)	NULL,
	GENERA_CARTA_PORTE 			VARCHAR(1) 	NOT NULL DEFAULT 'N',
	ESTADO_CARTA_PORTE 			VARCHAR(1) 	NULL,
	ULTIMO_ERROR 				VARCHAR(MAX) 	NULL,
	ERROR_WS 				VARCHAR(1) 	NOT NULL DEFAULT 'N',
	ERROR_SOFTLAND 				VARCHAR(1) 	NOT NULL DEFAULT 'N',
	GUUID_GT 				VARCHAR(255) 	NULL
)
go



ALTER TABLE DOC_ELECTRONICO_PROCESADO 
	ADD CONSTRAINT XPKDOCELECPROC PRIMARY KEY (TIPO_DOC,NUMERO_DOC,NIT_EMISOR)
go




CREATE TABLE EMPRESA (
	GLN        		VARCHAR(13) 		NOT NULL,
	CEDULAJURIDICA		VARCHAR(20) 		NOT NULL,
	NOMBRE		  	VARCHAR(80) 		NOT NULL	
)
go

 
ALTER TABLE EMPRESA
        ADD CONSTRAINT EMPRESAPK PRIMARY KEY (
               GLN )
go


 CREATE TABLE ESCALA_BONIF (
        NIVEL_PRECIO         VARCHAR(12) NOT NULL,
        MONEDA               VARCHAR(1) NOT NULL,
        VERSION              int NOT NULL,
        ARTICULO             VARCHAR(20) NOT NULL,
        ESCALA_BONIF         int NOT NULL,
        VERSION_BONIF        int NOT NULL,
        ARTICULO_BONIF       VARCHAR(20) NOT NULL,
        MIN_ART_FACT         int NOT NULL,
        MAX_ART_FACT         int NULL,
        UNIDADES_BONIF       DECIMAL(28,8) NOT NULL,
        FECHA_INICIO_ESC     DATETIME NOT NULL,
        FECHA_FIN_ESC        DATETIME NOT NULL,
        FACTOR_BONIF         DECIMAL(28,8) NULL,
        FECHA_ULT_MODIF      DATETIME NULL,
        USUARIO_ULT_MODIF    VARCHAR(25) NULL
 )
go
 
 
 ALTER TABLE ESCALA_BONIF
        ADD CONSTRAINT XPKESCALA_BONIF PRIMARY KEY (NIVEL_PRECIO, 
               MONEDA, VERSION, ARTICULO, ESCALA_BONIF, VERSION_BONIF)
go
 
 
 CREATE TABLE ESCALA_DCTO (
        NIVEL_PRECIO         VARCHAR(12) NOT NULL,
        MONEDA               VARCHAR(1) NOT NULL,
        VERSION              int NOT NULL,
        ARTICULO             VARCHAR(20) NOT NULL,
        ESCALA_DCTO          int NOT NULL,
        VERSION_DCTO         int NOT NULL,
        MIN_UNID_FACT        int NULL,
        MAX_UNID_FACT        int NULL,
        PORC_DCTO            DECIMAL(28,8) NOT NULL,
        FECHA_INICIO_ESC     DATETIME NOT NULL,
        FECHA_FIN_ESC        DATETIME NOT NULL,
        FECHA_ULT_MODIF      DATETIME NULL,
        USUARIO_ULT_MODIF    VARCHAR(25) NULL
 )
go
 
 
 ALTER TABLE ESCALA_DCTO
        ADD CONSTRAINT XPKESCALA_DCTO PRIMARY KEY (NIVEL_PRECIO, 
               MONEDA, VERSION, ARTICULO, ESCALA_DCTO, VERSION_DCTO)
go
 
 
 CREATE TABLE FACTURA (
        TIPO_DOCUMENTO       		VARCHAR(1) 	NOT NULL,
        FACTURA              		VARCHAR(50) 	NOT NULL,
        AUDIT_TRANS_INV      		int 		NULL,
        ESTA_DESPACHADO      		VARCHAR(1) 	NOT NULL,
        EN_INVESTIGACION     		VARCHAR(1) 	NOT NULL,
        TRANS_ADICIONALES    		VARCHAR(1) 	NOT NULL,
        ESTADO_REMISION      		VARCHAR(1) 	NOT NULL,
        ASIENTO_DOCUMENTO    		VARCHAR(10) 	NULL,
        DESCUENTO_VOLUMEN    		DECIMAL(28,8) 	NOT NULL,
        MONEDA_FACTURA       		VARCHAR(1) 	NOT NULL,
        COMENTARIO_CXC       		VARCHAR(40) 	NULL,
        FECHA_DESPACHO       		DATETIME 	NOT NULL,
        CLASE_DOCUMENTO      		VARCHAR(1) 	NOT NULL,
        FECHA_RECIBIDO       		DATETIME 	NOT NULL,
        PEDIDO               		VARCHAR(50) 	NULL,
        FACTURA_ORIGINAL     		VARCHAR(50) 	NULL,
        TIPO_ORIGINAL        		VARCHAR(1) 	NULL,
        COMISION_COBRADOR    		DECIMAL(28,8) 	NOT NULL,
        TARJETA_CREDITO      		VARCHAR(20) 	NULL,
        TOTAL_VOLUMEN        		DECIMAL(28,8) 	NOT NULL,
        NUMERO_AUTORIZA      		VARCHAR(10) 	NULL,
        TOTAL_PESO           		DECIMAL(28,8) 	NOT NULL,
        MONTO_COBRADO        		DECIMAL(28,8) 	NOT NULL,
        TOTAL_IMPUESTO1      		DECIMAL(28,8) 	NOT NULL,
        FECHA                		DATETIME 	NOT NULL,
        FECHA_ENTREGA        		DATETIME 	NOT NULL,
        TOTAL_IMPUESTO2      		DECIMAL(28,8) 	NOT NULL,
        PORC_DESCUENTO2      		DECIMAL(28,8) 	NOT NULL,
        MONTO_FLETE          		DECIMAL(28,8) 	NOT NULL,
        MONTO_SEGURO         		DECIMAL(28,8) 	NOT NULL,
        MONTO_DOCUMENTACIO   		DECIMAL(28,8) 	NOT NULL,
        TIPO_DESCUENTO1      		VARCHAR(1) 	NOT NULL,
        TIPO_DESCUENTO2      		VARCHAR(1) 	NOT NULL,
        MONTO_DESCUENTO1     		DECIMAL(28,8) 	NOT NULL,
        MONTO_DESCUENTO2     		DECIMAL(28,8) 	NOT NULL,
        PORC_DESCUENTO1      		DECIMAL(28,8) 	NOT NULL,
        TOTAL_FACTURA        		DECIMAL(28,8) 	NOT NULL,
        FECHA_PEDIDO         		DATETIME 	NOT NULL,
        FECHA_HORA_ANULA     		DATETIME 	NULL,
        FECHA_ORDEN          		DATETIME 	NULL,
        TOTAL_MERCADERIA     		DECIMAL(28,8) 	NOT NULL,
        COMISION_VENDEDOR    		DECIMAL(28,8) 	NOT NULL,
        ORDEN_COMPRA         		VARCHAR(30) 	NULL,
        FECHA_HORA           		DATETIME 	NOT NULL,
        TOTAL_UNIDADES       		DECIMAL(28,8) 	NOT NULL,
        NUMERO_PAGINAS       		smallint 	NOT NULL,
        TIPO_CAMBIO          		DECIMAL(28,8) 	NOT NULL,
        ANULADA              		VARCHAR(1) 	NOT NULL,
        MODULO               		VARCHAR(4) 	NOT NULL,
        CARGADO_CG           		VARCHAR(1) 	NOT NULL,
        CARGADO_CXC          		VARCHAR(1) 	NOT NULL,
        EMBARCAR_A           		VARCHAR(80) 	NOT NULL,
        DIREC_EMBARQUE       		VARCHAR(8) 	NULL,
        DIRECCION_FACTURA    		VARCHAR(4000) 	NULL,
        MULTIPLICADOR_EV     		smallint 	NOT NULL,
        OBSERVACIONES        		TEXT 		NULL,
        RUBRO1               		VARCHAR(50) 	NULL,
        RUBRO2               		VARCHAR(50) 	NULL,
        RUBRO3               		VARCHAR(50) 	NULL,
        RUBRO4               		VARCHAR(50) 	NULL,
        RUBRO5               		VARCHAR(50) 	NULL,
        VERSION_NP           		int 		NOT NULL,
        MONEDA               		VARCHAR(1) 	NOT NULL,
        NIVEL_PRECIO         		VARCHAR(12) 	NOT NULL,
        COBRADOR             		VARCHAR(4) 	NOT NULL,
        RUTA                 		VARCHAR(4) 	NOT NULL,
        USUARIO              		VARCHAR(25) 	NOT NULL,
        USUARIO_ANULA        		VARCHAR(25) 	NULL,
        CONDICION_PAGO       		VARCHAR(4) 	NOT NULL,
        ZONA                 		VARCHAR(4) 	NOT NULL,
        VENDEDOR             		VARCHAR(4) 	NOT NULL,
        DOC_CREDITO_CXC      		VARCHAR(50) 	NULL,
        CLIENTE_DIRECCION    		VARCHAR(20) 	NOT NULL,
        CLIENTE_CORPORAC     		VARCHAR(20) 	NOT NULL,
        CLIENTE_ORIGEN       		VARCHAR(20) 	NOT NULL,
        CLIENTE              		VARCHAR(20) 	NOT NULL,
        PAIS                 		VARCHAR(4) 	NOT NULL,
        SUBTIPO_DOC_CXC      		smallint 	NULL,
        TIPO_CREDITO_CXC     		VARCHAR(3) 	NULL,
        TIPO_DOC_CXC         		VARCHAR(3) 	NULL,
        MONTO_ANTICIPO 	     		DECIMAL(28,8) 	NULL,
        TOTAL_PESO_NETO      		DECIMAL(28,8) 	NULL,
        FECHA_RIGE           		DATETIME 	NOT NULL,
        CONTRATO             		VARCHAR(20)   	NULL,
        PORC_INTCTE          		DECIMAL(28,8) 	NULL,
        USA_DESPACHOS 	     		VARCHAR(1) 	NOT NULL,
        COBRADA              		VARCHAR(1) 	NOT NULL,
        DESCUENTO_CASCADA    		VARCHAR(1) 	NOT NULL,
        DIRECCION_EMBARQUE   		VARCHAR(250) 	NULL,
		CONSECUTIVO          		VARCHAR(10) 	NULL,
		REIMPRESO            		INT 		NOT NULL DEFAULT 0,
		DIVISION_GEOGRAFICA1		VARCHAR(12)	NULL,
		DIVISION_GEOGRAFICA2		VARCHAR(12)	NULL,
		BASE_IMPUESTO1				DECIMAL(28,8) 	NULL,
		BASE_IMPUESTO2				DECIMAL(28,8) 	NULL,
		NOMBRE_CLIENTE 				VARCHAR(150) 	NULL,
		DOC_FISCAL 					VARCHAR(50) 	NULL,
		NOMBREMAQUINA 				VARCHAR(20)	NULL,
		SERIE_RESOLUCION			VARCHAR(20)	NULL,
		CONSEC_RESOLUCION			INT		NULL,
		GENERA_DOC_FE 				VARCHAR(1) 	DEFAULT 'N' NOT NULL,
		TASA_IMPOSITIVA 			VARCHAR(4) 	NULL,
		TASA_IMPOSITIVA_PORC 		DECIMAL(28, 8) 	NULL,
		TASA_CREE1 					VARCHAR(4)	NULL,
		TASA_CREE1_PORC 			DECIMAL(28, 8) 	NULL,
		TASA_CREE2 					VARCHAR(4) 	NULL,
		TASA_CREE2_PORC 			DECIMAL(28, 8) 	NULL,
		TASA_GAN_OCASIONAL_PORC 	DECIMAL(28, 8) 	NULL,
		CONTRATO_AC 				VARCHAR(10) 	NULL,
		AJUSTE_REDONDEO 			DECIMAL(28,8) NULL,
		USO_CFDI 					VARCHAR(3) NULL,
		FORMA_PAGO 					VARCHAR(4) NULL,
		CLAVE_REFERENCIA_DE 		VARCHAR(50) NULL,
		FECHA_REFERENCIA_DE 		DATETIME NULL,
		JUSTI_DEV_HACIEND 			VARCHAR(2) NULL,
		INCOTERMS					VARCHAR(3) NULL,
		U_AD_WM_NUMERO_VENDEDOR 	VARCHAR(9) 	NULL,
		U_AD_WM_ENVIAR_GLN 			VARCHAR(13) NULL,
		U_AD_WM_NUMERO_RECEPCION 	VARCHAR(8) 	NULL,
		U_AD_WM_NUMERO_RECLAMO 		VARCHAR(10) NULL,
		U_AD_WM_FECHA_RECLAMO 		VARCHAR(8) 	NULL,
		U_AD_PC_NUMERO_VENDEDOR 	VARCHAR(12) NULL,
		U_AD_PC_ENVIAR_GLN 			VARCHAR(13) NULL,
		U_AD_GS_NUMERO_VENDEDOR 	VARCHAR(12) NULL,
		U_AD_GS_ENVIAR_GLN 			VARCHAR(13) NULL,
		U_AD_GS_NUMERO_RECEPCION 	VARCHAR(8) 	NULL,
		U_AD_GS_FECHA_RECEPCION 	VARCHAR(8) 	NULL,
		U_AD_AM_NUMERO_PROVEEDOR 	VARCHAR(12) NULL,
		U_AD_AM_ENVIAR_GLN 			VARCHAR(13) NULL,
		U_AD_AM_NUMERO_RECEPCION 	VARCHAR(8) 	NULL,
		U_AD_AM_NUMERO_RECLAMO 		VARCHAR(10) NULL,
		U_AD_AM_FECHA_RECLAMO 		VARCHAR(8) 	NULL,
		U_AD_AM_FECHA_RECEPCION 	VARCHAR(8) 	NULL
		
 )
go
 
 
 ALTER TABLE FACTURA
        ADD CONSTRAINT FACTURAPK PRIMARY KEY NONCLUSTERED (
               TIPO_DOCUMENTO, FACTURA)
go
 

CREATE TABLE FACTURA_ADUANA (
	CLIENTE 		VARCHAR(20) 	NOT NULL,
	TIPO_DOCUMENTO 		VARCHAR(1) 	NOT NULL DEFAULT ('F'),
	FACTURA 		VARCHAR(50) 	NOT NULL,
	NUMERO_DUA 		VARCHAR(50) 	NULL,
	FECHA_DUA 		DATETIME	NULL,
	NOMBRE_AGEN_ADUANA 	VARCHAR(80) 	NULL,
	NIT_AGEN_ADUANA 	VARCHAR(20) 	NULL
)
go


ALTER TABLE FACTURA_ADUANA  
	ADD CONSTRAINT PK_FACTURA_ADUANA PRIMARY KEY CLUSTERED ( CLIENTE,TIPO_DOCUMENTO,FACTURA)
go	

 
CREATE TABLE FACTURA_CANCELA (
         TIPO_DOCUMENTO		VARCHAR(1)	NOT NULL,
         FACTURA		VARCHAR(50)	NOT NULL,
         NUMERO_PAGO		INT		NOT NULL,
         TIPO			VARCHAR(1)	NOT NULL,
         MONTO			DECIMAL(28,8)	NOT NULL,
         MONEDA			VARCHAR(1)	NOT NULL,
         NUM_DOCUMENTO		VARCHAR(20)	NULL,
         ENTIDAD_FINANCIERA	VARCHAR(8)	NULL,
         TIPO_TARJETA		VARCHAR(12)	NULL,
         NUM_AUTORIZA		VARCHAR(20)	NULL,
         USUARIO		VARCHAR(25)	NOT NULL,
         CAJA			VARCHAR(10)	NOT NULL,
         FECHA_HORA		DATETIME	NOT NULL,
         DEVOLUCION		VARCHAR(50)	NULL,
         CHECK_DEVOLUCION	VARCHAR(1)	NULL 
)
go




ALTER TABLE FACTURA_CANCELA
         ADD CONSTRAINT PKFACTURA_CANCELA PRIMARY KEY NONCLUSTERED
         	(TIPO_DOCUMENTO, FACTURA, TIPO, NUMERO_PAGO )
go   



CREATE TABLE FACTURA_DOC_CC(
      TIPO_DOCUMENTO 		VARCHAR(1) 	NOT NULL,
      FACTURA 			VARCHAR(50) 	NOT NULL,
      LINEA 			SMALLINT    	NOT NULL,
      TIPO 			VARCHAR(3) 	NOT NULL,
      DOCUMENTO_CC 		VARCHAR(50) 	NOT NULL
)
go
      
      
      
ALTER TABLE FACTURA_DOC_CC
        ADD CONSTRAINT PK_FACTURA_DOC_CC PRIMARY KEY NONCLUSTERED (TIPO_DOCUMENTO, FACTURA, LINEA, TIPO, DOCUMENTO_CC)
go
        
        
        
 CREATE TABLE FACTURA_LINEA (
        FACTURA              	VARCHAR(50) 	NOT NULL,
        TIPO_DOCUMENTO       	VARCHAR(1) 	NOT NULL,
        LINEA                	smallint 	NOT NULL,
        BODEGA               	VARCHAR(4) 	NOT NULL,
        COSTO_TOTAL_DOLAR    	DECIMAL(28,8) 	NOT NULL,
        PEDIDO               	VARCHAR(50) 	NULL,
        ARTICULO             	VARCHAR(20) 	NOT NULL,
        LOCALIZACION         	VARCHAR(8) 	NULL,
        LOTE                 	VARCHAR(15) 	NULL,
        ANULADA              	VARCHAR(1) 	NOT NULL,
        FECHA_FACTURA        	DATETIME 	NOT NULL,
        CANTIDAD             	DECIMAL(28,8) 	NOT NULL,
        PRECIO_UNITARIO      	DECIMAL(28,8) 	NOT NULL,
        TOTAL_IMPUESTO1      	DECIMAL(28,8) 	NOT NULL,
        TOTAL_IMPUESTO2      	DECIMAL(28,8) 	NOT NULL,
        DESC_TOT_LINEA       	DECIMAL(28,8) 	NOT NULL,
        DESC_TOT_GENERAL     	DECIMAL(28,8) 	NOT NULL,
        COSTO_TOTAL          	DECIMAL(28,8) 	NOT NULL,
        PRECIO_TOTAL         	DECIMAL(28,8) 	NOT NULL,
        DESCRIPCION          	TEXT 		NULL,
        COMENTARIO           	VARCHAR(100) 	NULL,
        CANTIDAD_DEVUELT     	DECIMAL(28,8) 	NOT NULL,
        DESCUENTO_VOLUMEN    	DECIMAL(28,8) 	NOT NULL,
        TIPO_LINEA           	VARCHAR(1) 	NOT NULL,
        CANTIDAD_ACEPTADA    	DECIMAL(28,8) 	NOT NULL,
        CANT_NO_ENTREGADA    	DECIMAL(28,8) 	NOT NULL,
        COSTO_TOTAL_LOCAL    	DECIMAL(28,8) 	NOT NULL,
        PEDIDO_LINEA         	smallint 	NULL,
        MULTIPLICADOR_EV     	smallint 	NOT NULL,
        SERIE_CADENA         	int 		NULL,
        SERIE_CAD_NO_ACEPT   	int 		NULL,
        SERIE_CAD_ACEPTADA   	int 		NULL,
        DOCUMENTO_ORIGEN     	VARCHAR(50) 	NULL,
        LINEA_ORIGEN         	smallint 	NULL,
        TIPO_ORIGEN          	VARCHAR(1) 	NULL,
        UNIDAD_DISTRIBUCIO   	VARCHAR(6) 	NULL,
        CANT_DESPACHADA      	DECIMAL(28,8) 	NOT NULL,
        COSTO_ESTIM_LOCAL    	DECIMAL(28,8) 	NOT NULL,
        COSTO_ESTIM_DOLAR    	DECIMAL(28,8) 	NOT NULL,
        CANT_ANUL_PORDESPA   	DECIMAL(28,8) 	NULL,
        MONTO_RETENCION      	DECIMAL(28,8) 	DEFAULT (0) NOT NULL,
        BASE_IMPUESTO1	     	DECIMAL(28,8) 	NULL,
	BASE_IMPUESTO2	     	DECIMAL(28,8) 	NULL,
	PROYECTO		VARCHAR(25) 	NULL,
	FASE			VARCHAR(25)  	NULL,
	CENTRO_COSTO 		VARCHAR(25) 	NULL,
	CUENTA_CONTABLE 	VARCHAR(25) 	NULL,
	COSTO_TOTAL_COMP	DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	COSTO_TOTAL_COMP_LOCAL	DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	COSTO_TOTAL_COMP_DOLAR	DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	COSTO_ESTIM_COMP_LOCAL	DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	COSTO_ESTIM_COMP_DOLAR	DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	CANT_DEV_PROCESO 	DECIMAL(28,8) 	NOT NULL DEFAULT 0
)
go
 
 
 ALTER TABLE FACTURA_LINEA
        ADD CONSTRAINT LINEA_FACTURAPK PRIMARY KEY NONCLUSTERED (
               FACTURA, TIPO_DOCUMENTO, LINEA)
go


CREATE TABLE FACTURA_RETENCION (
        TIPO_DOCUMENTO      VARCHAR(1)	 	NOT NULL,
        FACTURA       		VARCHAR(50) 	NOT NULL,
        CODIGO_RETENCION    VARCHAR(4)	 	NOT NULL,
        MONTO               DECIMAL(28,8) 	NOT NULL,
        DOC_REFERENCIA      VARCHAR(50)  	NOT NULL,
        BASE	 			DECIMAL(28,8) 	DEFAULT (0)		NOT NULL,
		AUTORETENEDORA 		VARCHAR(1)	 	DEFAULT ('N')	NOT NULL,
		FECHA_DOCUMENTO		DATETIME 		NULL,
		FECHA_RIGE 			DATETIME 		NULL
)
go
 

ALTER TABLE FACTURA_RETENCION 
	ADD CONSTRAINT XPKFACTURA_RETENCI
		PRIMARY KEY  ( 	TIPO_DOCUMENTO,FACTURA, CODIGO_RETENCION) 
go


CREATE TABLE FIADORES_DOC_FA (
         FIADOR_ID		VARCHAR(20)	NOT NULL,
         DOCUMENTO		VARCHAR(50)	NOT NULL,
         TIPO			VARCHAR(1)	NOT NULL,
         NOMBRE_FIADOR		VARCHAR(80)	NOT NULL,
         OCUPAC_FIADOR		VARCHAR(30)	NULL,
         TIPO_FIADOR		VARCHAR(20)	NULL,
         DIREC_FIADOR		VARCHAR(80)	NULL,
         TEL_DOM_FIADOR		VARCHAR(10)	NULL,
         LUG_TRAB_FIADOR	VARCHAR(80)	NULL,
         DIR_TRAB_FIADOR	VARCHAR(80)	NULL,
         TEL_TRAB_FIADOR	VARCHAR(10)	NULL,
         CONTRATO_FIADOR	VARCHAR(20)	NULL,
         OBS_FIADOR		VARCHAR(200)	NULL 
)
go


ALTER TABLE FIADORES_DOC_FA
         ADD CONSTRAINT PKFIADOR PRIMARY KEY NONCLUSTERED
         	(FIADOR_ID, DOCUMENTO, TIPO )
go

CREATE TABLE FIADORES_PED_FA (
         FIADOR_ID		VARCHAR(20)	NOT NULL,
         DOCUMENTO		VARCHAR(50)	NOT NULL,
         TIPO			VARCHAR(1)	NOT NULL,
         NOMBRE_FIADOR		VARCHAR(80)	NOT NULL,
         OCUPAC_FIADOR		VARCHAR(30)	NULL,
         TIPO_FIADOR		VARCHAR(20)	NULL,
         DIREC_FIADOR		VARCHAR(80)	NULL,
         TEL_DOM_FIADOR		VARCHAR(10)	NULL,
         LUG_TRAB_FIADOR	VARCHAR(80)	NULL,
         DIR_TRAB_FIADOR	VARCHAR(80)	NULL,
         TEL_TRAB_FIADOR	VARCHAR(10)	NULL,
         CONTRATO_FIADOR	VARCHAR(20)	NULL,
         OBS_FIADOR		VARCHAR(200)	NULL 
)
go


ALTER TABLE FIADORES_PED_FA
         ADD CONSTRAINT PKFIADORPED PRIMARY KEY NONCLUSTERED
         (FIADOR_ID, DOCUMENTO, TIPO )
go


CREATE TABLE GARANTIAS_DOC_FA (
         GARANTIA_ID	VARCHAR(20)	NOT NULL,
         DOCUMENTO	VARCHAR(50)	NOT NULL,
         TIPO		VARCHAR(1)	NOT NULL,
         TIPO_GARANTIA	VARCHAR(20)	NULL,
         DESC_GARANTIA	VARCHAR(40)	NULL,
         OBS_GARANTIA	VARCHAR(200)	NULL,
         ART_GARANTIA	VARCHAR(20)	NULL 
)
go



ALTER TABLE GARANTIAS_DOC_FA
         ADD CONSTRAINT PKGARANTIADOC PRIMARY KEY NONCLUSTERED
         	(GARANTIA_ID, DOCUMENTO, TIPO )
go


CREATE TABLE GARANTIAS_PED_FA (
         GARANTIA_ID	VARCHAR(20)	NOT NULL,
         DOCUMENTO	VARCHAR(50)	NOT NULL,
         TIPO		VARCHAR(1)	NOT NULL,
         TIPO_GARANTIA	VARCHAR(20)	NULL,
         DESC_GARANTIA	VARCHAR(40)	NULL,
         OBS_GARANTIA	VARCHAR(200)	NULL,
         ART_GARANTIA	VARCHAR(20)	NULL 
)
go         


ALTER TABLE GARANTIAS_PED_FA
         ADD CONSTRAINT PKGARANTIAPED PRIMARY KEY NONCLUSTERED
         	(GARANTIA_ID, DOCUMENTO, TIPO )
go         	

 
 
 CREATE TABLE GLOBALES_FA (
        LLAVE                smallint NULL,
        BODEGA_DEFAULT       VARCHAR(4) NULL,
        COND_PAGO_CONTAD     VARCHAR(4) NULL,
        VENDEDOR_OBLIGATOR   VARCHAR(1) NULL,
        FACT_EXC_PEDIDO      VARCHAR(1) NOT NULL,
        USA_TARJETA_CRED     VARCHAR(1) NOT NULL,
        BODEGA_POR_LINEA     VARCHAR(1) NOT NULL,
        PERMITE_BACKORDER    VARCHAR(1) NOT NULL,
        CANCEL_PED_PARCIAL   VARCHAR(1) NULL,
        PED_A_IMPRESORA      VARCHAR(1) NOT NULL,
        DOC_A_IMPRESORA      VARCHAR(1) NOT NULL,
        IMPRE_LOTE_SEPARAD   VARCHAR(1) NULL,
        FACTURA_MULTIPAG     VARCHAR(1) NULL,
        INCR_NUM_FACTURA     VARCHAR(1) NULL,
        MULTIPLE_FMT_FACTU   VARCHAR(1) NOT NULL,
        MULTIPLE_FMT_PEDID   VARCHAR(1) NOT NULL,
        ORDEN_LINEAS_FACT    VARCHAR(1) NOT NULL,
        REIMPRESION_PEDIDO   VARCHAR(1) NOT NULL,
        IMP_PEDIDO_AL_FACT   VARCHAR(1) NOT NULL,
        REDONDEAR_FACTURA    VARCHAR(1) NOT NULL,
        FACTOR_REDONDEO      DECIMAL(28,8) NOT NULL,
        PRECIOS_DEC          smallint NOT NULL,
        DESC_EN_PRECIO       VARCHAR(1) NOT NULL,
        IMP1_EN_PRECIO       VARCHAR(1) NULL,
        IMP1_AFECTA_DESCTO   VARCHAR(1) NOT NULL,
        APLICA_NI_PR_IMP1    VARCHAR(1) NULL,
        MONEDA_IMP1          VARCHAR(1) NULL,
        NIV_PRECIO_IMP1      VARCHAR(12) NULL,
        PAGO_COM_PARCIAL     VARCHAR(1) NULL,
        PORC_IMP_COMISION    DECIMAL(28,8) NULL,
        ASIENTO_VENTA_POR    VARCHAR(1) NOT NULL,
        TIPO_ASIENTO         VARCHAR(4) NULL,
        PAQUETE              VARCHAR(4) NULL,
        CTR_FLETE            VARCHAR(25) NULL,
        CTA_FLETE            VARCHAR(25) NULL,
        CTR_SEGURO           VARCHAR(25) NULL,
        CTA_SEGURO           VARCHAR(25) NULL,
        CTR_DOCUMENTACI      VARCHAR(25) NULL,
        CTA_DOCUMENTACI      VARCHAR(25) NULL,
        CTR_IMPUESTO1        VARCHAR(25) NULL,
        CTA_IMPUESTO1        VARCHAR(25) NULL,
        CTR_IMPUESTO2        VARCHAR(25) NULL,
        CTA_IMPUESTO2        VARCHAR(25) NULL,
        CTR_IMP_COMISIO      VARCHAR(25) NULL,
        CTA_IMP_COMISIO      VARCHAR(25) NULL,
        USAR_RUBROS          VARCHAR(1) NOT NULL,
        RUBRO1_NOMBRE        VARCHAR(15) NULL,
        RUBRO2_NOMBRE        VARCHAR(15) NULL,
        RUBRO3_NOMBRE        VARCHAR(15) NULL,
        RUBRO4_NOMBRE        VARCHAR(15) NULL,
        USA_BOLETAS          VARCHAR(1) NOT NULL,
        NOM_RUBRO6_CLI       VARCHAR(60) NULL,
        NOM_RUBRO7_CLI       VARCHAR(60) NULL,
        NOM_RUBRO8_CLI       VARCHAR(60) NULL,
        NOM_RUBRO9_CLI       VARCHAR(60) NULL,
        RUBRO5_NOMBRE        VARCHAR(15) NULL,
        OBSERVACIONES        TEXT NULL,
        NIV_PRE_PUBLICO      VARCHAR(12) NULL,
        MONEDA_PUBLICO       VARCHAR(1) NULL,
        COLUMNAS_ESTANDAR    VARCHAR(4000) NULL,
        ASIENTO_COSTO_POR    VARCHAR(1) NOT NULL,
        CAMBIAR_ESQ_TRAB     VARCHAR(1) NOT NULL,
        FACT_DOCS_VENCIDOS   VARCHAR(1) NOT NULL,
        FACT_COBRO_JUD       VARCHAR(1) NOT NULL,
        FACT_LIMITE_CRED     VARCHAR(1) NOT NULL,
        MOD_APLIC_ASIENTO    smallint NOT NULL,
        INTEGRACION_CONTA    VARCHAR(1) NOT NULL,
        TIPO_CONTA_OMISION   VARCHAR(1) NOT NULL,
        TIPO_CAMBIO          VARCHAR(4) NULL,
        PRECISION_MAXIMA     VARCHAR(1) NULL,
        LINEAS_ARTICULO      smallint NOT NULL,
        LINEAS_FACTURA       smallint NOT NULL,
        LINEAS_ADICIONALES   smallint NOT NULL,
        DETALLE_KITS         VARCHAR(1) NOT NULL,
        MOD_PRECIOS          VARCHAR(1) NOT NULL,
        PREVISTA1            VARCHAR(1) NULL,
        PREVISTA2            VARCHAR(1) NULL,
        PREVISTA3            VARCHAR(1) NULL,
        PREVISTA4            VARCHAR(1) NULL,
        PREVISTA5            VARCHAR(1) NULL,
        CTR_CONSUMO          VARCHAR(25) NULL,
        CC_EN_LINEA          VARCHAR(1) NOT NULL,
        CG_EN_LINEA          VARCHAR(1) NOT NULL,
        USAR_AUTORIZACION    VARCHAR(1) NOT NULL,
        IMP1_EN_BONIFICA     VARCHAR(1) NOT NULL,
        IMP2_EN_BONIFICA     VARCHAR(1) NOT NULL,
        ASIENTO_CONTCXCPOR   VARCHAR(1) NOT NULL,
        USAR_APROB_PEDIDOS   VARCHAR(1) NOT NULL,
        NOM_RUBRO10_CLI      VARCHAR(60) NULL,
        LISTA_PRECIOS        VARCHAR(1) NOT NULL,
        MARGEN_UTILIDAD      VARCHAR(1) NOT NULL,
        MONTO_MINIMO         VARCHAR(1) NOT NULL,
        DOCS_VENCIDOS        VARCHAR(1) NOT NULL,
        LIMITE_CREDITO       VARCHAR(1) NOT NULL,
        COBRO_JUDICIAL       VARCHAR(1) NOT NULL,
        SIN_OC               VARCHAR(1) NOT NULL,
        DIAS_ATRASO          VARCHAR(1) NOT NULL,
        MONTO_MINIMO_LOCAL   DECIMAL(28,8) NULL,
        MONTO_MINIMO_DOLAR   DECIMAL(28,8) NULL,
        SALDO_MAX_LOCAL      DECIMAL(28,8) NULL,
        SALDO_MAX_DOLAR      DECIMAL(28,8) NULL,
        MAX_DIAS_ATRASO      smallint NULL,
        MAX_DOCS_VENC        smallint NULL,
        PRECIOS_DEC_DOLAR    smallint NOT NULL,
        COND_PAGO_NIV_PRE    VARCHAR(1) NOT NULL,
        FACT_LISTA_PRECIOS   VARCHAR(1) NOT NULL,
        FACT_MARGEN_UTILID   VARCHAR(1) NOT NULL,
        FACT_MONTO_MINIMO    VARCHAR(1) NOT NULL,
        FACT_DIAS_ATRASO     VARCHAR(1) NOT NULL,
        FACT_SIN_OC          VARCHAR(1) NOT NULL,
        USAR_RUBROS_VAL      VARCHAR(1) NOT NULL,
        IMP_DESC_CLASIFIC    VARCHAR(1) NOT NULL,
        LIMITAR_MAX_LINEAS   VARCHAR(1) NULL,
        INDICAD_PEDIDO       VARCHAR(1) NOT NULL,
        PRECIO_COSTO         VARCHAR(1) NOT NULL,
        FACT_MENOR_RESERVA   VARCHAR(1) NOT NULL,
        USA_DESPACHOS 	     VARCHAR(1) NOT NULL,
        CTR_INV_DESPACHAR    VARCHAR(25) NULL,
        CTA_INV_DESPACHAR    VARCHAR(25) NULL,
        ANULA_CXC_APLICADO   VARCHAR(1) NOT NULL,
        USA_ESQUEMA_CAJAS    VARCHAR(1) NOT NULL,
        TIPO_COSTO_NOEXIST   VARCHAR(1) NOT NULL,
        CALCULO_IMP2 	     VARCHAR(1) NOT NULL,
	CATEGORIA_CLIENTE    VARCHAR(8) NOT NULL,
	NIVEL_PRECIO 	     VARCHAR(12) NOT NULL,
	MONEDA_NIVEL 	     VARCHAR(1)  NOT NULL,
	DESCUENTO_CASCADA    VARCHAR(1)  NOT NULL,
	RETENCIONES 	     VARCHAR(1)  NULL,
	RETENCIONES_FLETES   VARCHAR(1)  NULL,
	ARTICULO 	     VARCHAR(20) NULL,
 	CODIGO_RETENCION     VARCHAR(4)  NULL,
 	APLICAR_DESC_GEN     VARCHAR(1) NOT NULL,
        MODO_DESC_MULT       VARCHAR(1) NOT NULL,
        DCTO_GENERAL 	     VARCHAR(1) NOT NULL,
        FACT_DCTO_GENERAL    VARCHAR(1) NOT NULL,
        AUTOR_GRABAR	     VARCHAR(1) NOT NULL,
        AUTOR_APROBAR	     VARCHAR(1) NOT NULL,
        AUTOR_FACTUREMITIR   VARCHAR(1) NOT NULL,
        AUTOR_FACTREMISION   VARCHAR(1) NOT NULL,
        CARGAR_APROBADO_CC   VARCHAR(1) NOT NULL,
        REMISION_A_IMPRES    VARCHAR(1) NOT NULL,
        DEVOLUC_A_IMPRES     VARCHAR(1) NOT NULL,
	NOM_RUBRO16_CLI      VARCHAR(60) NULL,
	NOM_RUBRO17_CLI      VARCHAR(60) NULL,
       	NOM_RUBRO18_CLI      VARCHAR(60) NULL,
       	NOM_RUBRO19_CLI      VARCHAR(60) NULL,
       	NOM_RUBRO20_CLI      VARCHAR(60) NULL        
 )
go

ALTER TABLE GLOBALES_FA
	ADD CONSTRAINT DEFAULTLLAVE DEFAULT 1 FOR LLAVE
go	

CREATE TABLE HISTORIAL_DESCUENTOS(
	GUID		Uniqueidentifier	NOT NULL, 
	DOCUMENTO	VARCHAR(50)		NULL,
	CAJA 		VARCHAR(6)		NULL,
	TIPO        VARCHAR(1)		NULL,
	LINEA		VARCHAR(50)		NOT NULL,
	REGLA		VARCHAR(200)		NOT NULL,
	ARTICULO	VARCHAR(20)		NOT NULL,
	CANTIDAD	DECIMAL(28,8)		NOT NULL,
	DESCUENTO	DECIMAL(28,8)		NOT NULL,
	ORIGEN		VARCHAR(3)		NOT NULL
)

go
 
 
ALTER TABLE HISTORIAL_DESCUENTOS
	ADD CONSTRAINT GUIDLINPK PRIMARY KEY (GUID, LINEA, DESCUENTO) 

go
 
 
  CREATE TABLE LINEASPEDIDO_EDI (
 	NUMEROORDEN          	VARCHAR(30) NOT NULL,
 	GLN_COMPRADOR        	VARCHAR(13) NOT NULL,
 	NUMEROLINEA          	SMALLINT NOT NULL,
 	PEDIDO        		VARCHAR(50) NULL,
 	DUN14                	VARCHAR(18) NULL,
 	PRECIOUNITARIO       	DECIMAL(28,8) NOT NULL default(0),
 	CANTIDAD_PEDIDA      	DECIMAL(28,8) NOT NULL default(0),
 	CANTIDAD_DESPACHADA  	DECIMAL(28,8) NOT NULL default(0),
 	CANTIDAD_RECIBIDA    	DECIMAL(28,8) NOT NULL default(0),
 	MONTO_IMPUESTO1      	DECIMAL(28,8) NOT NULL default(0),
 	PORCENTAJE_IMPUESTO1 	DECIMAL(28,8) NOT NULL default(0),
 	MONTO_IMPUESTO2      	DECIMAL(28,8) NOT NULL default(0),
 	PORCENTAJE_IMPUESTO2 	DECIMAL(28,8) NOT NULL default(0),
 	MONTO_DESCUENTO1     	DECIMAL(28,8) NOT NULL default(0),
 	PORCENTAJE_DESCUENTO1 	DECIMAL(28,8) NOT NULL default(0),
 	MONTO_DESCUENTO2     	DECIMAL(28,8) NOT NULL default(0),
 	PORCENTAJE_DESCUENTO2 	DECIMAL(28,8) NOT NULL
 )
go
 
 
 
 ALTER TABLE LINEASPEDIDO_EDI
         ADD CONSTRAINT LINEASPEDIDO_EDIPK PRIMARY KEY NONCLUSTERED (
                NUMEROORDEN, GLN_COMPRADOR,NUMEROLINEA)
go

 
 
 CREATE TABLE MONEDA_PED_BACKORD (
        PEDIDO               VARCHAR(50) NOT NULL,
        MONEDA_FACTURA       VARCHAR(3) NULL,
        MONEDA_REMISION      VARCHAR(3) NULL
 )
go
 
 
 ALTER TABLE MONEDA_PED_BACKORD
        ADD CONSTRAINT XPKMONEDA_PED_BACKORD PRIMARY KEY (PEDIDO)
go

CREATE TABLE PAQ_DESC_GRUPO(
       	PAQUETE_DESCUENTO 	VARCHAR(12)	NOT NULL,
	GRUPO		 	VARCHAR(6)	NOT NULL
)
go

ALTER TABLE PAQ_DESC_GRUPO
       ADD CONSTRAINT XPKPAQDESCGRUPO 
       	PRIMARY KEY NONCLUSTERED (PAQUETE_DESCUENTO, GRUPO)
go       	


CREATE TABLE PAQ_DESC_REG_DESC(
       	PAQUETE_DESCUENTO 	VARCHAR(12)	NOT NULL,
	REGLA_DESCUENTO 	INT		NOT NULL
)
go

ALTER TABLE PAQ_DESC_REG_DESC
       ADD CONSTRAINT XPKPAQDESCREGDESC 
       	PRIMARY KEY NONCLUSTERED (PAQUETE_DESCUENTO, REGLA_DESCUENTO)
go       	

CREATE TABLE PAQUETE_DESCUENTO(
       	PAQUETE_DESCUENTO 	VARCHAR(12)	NOT NULL,
       	DESCRIPCION             VARCHAR(254)	NOT NULL,
	ACTIVO			VARCHAR(1)	NOT NULL,
	TODA_TIENDA		VARCHAR(1)	NOT NULL,
	FECHA_RIGE		DATETIME	NOT NULL,
	FECHA_VENCE		DATETIME	NOT NULL,
	NOTAS			TEXT		NULL,
	FECHA_HORA_INICIO 	DATETIME 	NULL, 
	FECHA_HORA_FIN 	  	DATETIME 	NULL
)
go

ALTER TABLE PAQUETE_DESCUENTO
       ADD CONSTRAINT XPKPAQUETEDESCUENTO 
       PRIMARY KEY NONCLUSTERED (PAQUETE_DESCUENTO)
go       
 
 
 CREATE TABLE PEDIDO (
        PEDIDO               		VARCHAR(50) 	NOT NULL,
        ESTADO               		VARCHAR(1) 	NOT NULL,
        FECHA_PEDIDO         		DATETIME 	NOT NULL,
        FECHA_PROMETIDA      		DATETIME 	NOT NULL,
        FECHA_PROX_EMBARQU   		DATETIME 	NOT NULL,
        FECHA_ULT_EMBARQUE   		DATETIME 	NULL,
        FECHA_ULT_CANCELAC   		DATETIME 	NULL,
        ORDEN_COMPRA         		VARCHAR(30) 	NULL,
        FECHA_ORDEN          		DATETIME 	NULL,
        TARJETA_CREDITO      		VARCHAR(20) 	NULL,
        EMBARCAR_A           		VARCHAR(80) 	NOT NULL,
        DIREC_EMBARQUE       		VARCHAR(8) 	NOT NULL,
        DIRECCION_FACTURA    		VARCHAR(4000) 	NOT NULL,
        RUBRO1               		VARCHAR(50) 	NULL,
        RUBRO2               		VARCHAR(50) 	NULL,
        RUBRO3               		VARCHAR(50) 	NULL,
        RUBRO4               		VARCHAR(50) 	NULL,
        RUBRO5               		VARCHAR(50) 	NULL,
        OBSERVACIONES        		TEXT 		NULL,
        COMENTARIO_CXC       		VARCHAR(40) 	NULL,
        TOTAL_MERCADERIA     		DECIMAL(28,8) 	NOT NULL,
        MONTO_ANTICIPO       		DECIMAL(28,8) 	NOT NULL,
        MONTO_FLETE          		DECIMAL(28,8) 	NOT NULL,
        MONTO_SEGURO         		DECIMAL(28,8) 	NOT NULL,
        MONTO_DOCUMENTACIO   		DECIMAL(28,8) 	NOT NULL,
        TIPO_DESCUENTO1      		VARCHAR(1) 	NOT NULL,
        TIPO_DESCUENTO2      		VARCHAR(1) 	NOT NULL,
        MONTO_DESCUENTO1     		DECIMAL(28,8) 	NOT NULL,
        MONTO_DESCUENTO2     		DECIMAL(28,8) 	NOT NULL,
        PORC_DESCUENTO1      		DECIMAL(28,8) 	NOT NULL,
        PORC_DESCUENTO2      		DECIMAL(28,8) 	NOT NULL,
        TOTAL_IMPUESTO1      		DECIMAL(28,8) 	NOT NULL,
        TOTAL_IMPUESTO2      		DECIMAL(28,8) 	NOT NULL,
        TOTAL_A_FACTURAR     		DECIMAL(28,8) 	NOT NULL,
        PORC_COMI_VENDEDOR   		DECIMAL(28,8) 	NOT NULL,
        PORC_COMI_COBRADOR   		DECIMAL(28,8) 	NOT NULL,
        TOTAL_CANCELADO      		DECIMAL(28,8) 	NOT NULL,
        TOTAL_UNIDADES       		DECIMAL(28,8) 	NOT NULL,
        IMPRESO              		VARCHAR(1) 	NOT NULL,
        FECHA_HORA           		DATETIME 	NOT NULL,
        DESCUENTO_VOLUMEN    		DECIMAL(28,8) 	NOT NULL,
        TIPO_PEDIDO          		VARCHAR(1) 	NOT NULL,
        MONEDA_PEDIDO        		VARCHAR(1) 	NOT NULL,
        VERSION_NP           		int 		NOT NULL,
        AUTORIZADO           		VARCHAR(1) 	NOT NULL,
        DOC_A_GENERAR        		VARCHAR(1) 	NOT NULL,
        CLASE_PEDIDO         		VARCHAR(1) 	NOT NULL,
        MONEDA               		VARCHAR(1) 	NOT NULL,
        NIVEL_PRECIO         		VARCHAR(12) 	NOT NULL,
        COBRADOR             		VARCHAR(4) 	NOT NULL,
        RUTA                 		VARCHAR(4) 	NOT NULL,
        USUARIO              		VARCHAR(25) 	NOT NULL,
        CONDICION_PAGO       		VARCHAR(4) 	NOT NULL,
        BODEGA               		VARCHAR(4) 	NOT NULL,
        ZONA                 		VARCHAR(4) 	NOT NULL,
        VENDEDOR             		VARCHAR(4) 	NOT NULL,
        CLIENTE              		VARCHAR(20) 	NOT NULL,
        CLIENTE_DIRECCION    		VARCHAR(20) 	NOT NULL,
        CLIENTE_CORPORAC     		VARCHAR(20) 	NOT NULL,
        CLIENTE_ORIGEN       		VARCHAR(20) 	NOT NULL,
        PAIS                 		VARCHAR(4) 	NOT NULL,
        SUBTIPO_DOC_CXC      		smallint 	NULL,
        TIPO_DOC_CXC         		VARCHAR(3) 	NULL,
        BACKORDER            		VARCHAR(1) 	NOT NULL,
        CONTRATO             		VARCHAR(20)   	NULL,
        PORC_INTCTE          		DECIMAL(28,8) 	NULL,
        DESCUENTO_CASCADA    		VARCHAR(1) 	NOT NULL,
        TIPO_CAMBIO          		DECIMAL(28,8) 	NULL,
        FIJAR_TIPO_CAMBIO    		VARCHAR(1) 	NOT NULL,
        ORIGEN_PEDIDO 	     		VARCHAR(1) 	NOT NULL DEFAULT 'F',
        DESC_DIREC_EMBARQUE  		VARCHAR(250) 	NULL,
        DIVISION_GEOGRAFICA1		VARCHAR(12)	NULL,
		DIVISION_GEOGRAFICA2		VARCHAR(12)	NULL,
		BASE_IMPUESTO1			DECIMAL(28,8) 	NULL,
		BASE_IMPUESTO2			DECIMAL(28,8) 	NULL,
		NOMBRE_CLIENTE 			VARCHAR(150)  	NULL,
		FECHA_PROYECTADA		DATETIME	NULL,
		FECHA_APROBACION 		DATETIME 	NULL,
		TIPO_DOCUMENTO 			VARCHAR(1) 	NOT NULL DEFAULT('P'),
		VERSION_COTIZACION 		VARCHAR(10) 	NULL,
		RAZON_CANCELA_COTI 		VARCHAR(10) 	NULL, 
		DES_CANCELA_COTI 		VARCHAR(254)	NULL,
		CAMBIOS_COTI 			VARCHAR(254)  	NULL,
		COTIZACION_PADRE 		VARCHAR(50)	NULL,
		TASA_IMPOSITIVA 		VARCHAR(4) 	NULL,
		TASA_IMPOSITIVA_PORC 		DECIMAL(28, 8) 	NULL,
		TASA_CREE1 			VARCHAR(4) 	NULL,
		TASA_CREE1_PORC 		DECIMAL(28, 8) 	NULL,
		TASA_CREE2 			VARCHAR(4) 	NULL,
		TASA_CREE2_PORC 		DECIMAL(28, 8) 	NULL,
		TASA_GAN_OCASIONAL_PORC 	DECIMAL(28, 8) 	NULL,
		CONTRATO_AC 			VARCHAR(10) 	NULL,
		TIPO_CONTRATO_AC 		VARCHAR(10) 	NULL,
		PERIODICIDAD_CONTRATO_AC 	VARCHAR(10) 	NULL,
		FECHA_CONTRATO_AC 		DATETIME 	NULL,
		FECHA_INICIO_CONTRATO_AC 	DATETIME 	NULL,
		FECHA_PROXFAC_CONTRATO_AC 	DATETIME 	NULL,
		FECHA_FINFAC_CONTRATO_AC 	DATETIME 	NULL,
		FECHA_ULTAUMENTO_CONTRATO_AC 	DATETIME 	NULL,
		FECHA_PROXFACSIST_CONTRATO_AC 	DATETIME 	NULL,
		DIFERIDO_CONTRATO_AC 		VARCHAR(40) 	NULL,
		TOTAL_CONTRATO_AC 		DECIMAL(28,8) 	NULL,
		CONTRATO_REVENTA 		VARCHAR(1) 	NULL,
		USR_NO_APRUEBA 			VARCHAR(25) NULL,
		FECHA_NO_APRUEBA 		DATETIME  NULL,
		RAZON_DESAPRUEBA 		VARCHAR(254) NULL,
		MODULO 				VARCHAR(4) NULL,
		CORREOS_ENVIO 			VARCHAR(4000) NULL,
		USO_CFDI VARCHAR(3) NULL,
		CONTRATO_VIGENCIA_DESDE DATETIME NULL,
		CONTRATO_VIGENCIA_HASTA DATETIME NULL,
		FORMA_PAGO VARCHAR(4) NULL,
		CLAVE_REFERENCIA_DE VARCHAR(50) NULL,
		FECHA_REFERENCIA_DE DATETIME NULL,
		INCOTERMS VARCHAR(3) NULL,
		U_AD_WM_NUMERO_VENDEDOR 	VARCHAR(9) 	NULL,
		U_AD_WM_ENVIAR_GLN 			VARCHAR(13) NULL,
		U_AD_WM_NUMERO_RECEPCION 	VARCHAR(8) 	NULL,
		U_AD_WM_NUMERO_RECLAMO 		VARCHAR(10) NULL,
		U_AD_WM_FECHA_RECLAMO 		VARCHAR(8) 	NULL,
		U_AD_PC_NUMERO_VENDEDOR 	VARCHAR(12) NULL,
		U_AD_PC_ENVIAR_GLN 			VARCHAR(13) NULL,
		U_AD_GS_NUMERO_VENDEDOR 	VARCHAR(12) NULL,
		U_AD_GS_ENVIAR_GLN 			VARCHAR(13) NULL,
		U_AD_GS_NUMERO_RECEPCION 	VARCHAR(8) 	NULL,
		U_AD_GS_FECHA_RECEPCION 	VARCHAR(8) 	NULL,
		U_AD_AM_NUMERO_PROVEEDOR 	VARCHAR(12) NULL,
		U_AD_AM_ENVIAR_GLN 			VARCHAR(13) NULL,
		U_AD_AM_NUMERO_RECEPCION 	VARCHAR(8) 	NULL,
		U_AD_AM_NUMERO_RECLAMO 		VARCHAR(10) NULL,
		U_AD_AM_FECHA_RECLAMO 		VARCHAR(8) 	NULL,
		U_AD_AM_FECHA_RECEPCION 	VARCHAR(8) 	NULL		
		
 )
go
 
 
 ALTER TABLE PEDIDO
        ADD CONSTRAINT PEDIDOPK PRIMARY KEY NONCLUSTERED (PEDIDO)
go
 
 
 CREATE TABLE PEDIDO_AUTORIZA (
        PEDIDO               VARCHAR(50) 	NOT NULL,
        CONSECUTIVO          smallint 		NOT NULL,
        TIPO_DOCUMENTO       VARCHAR(1) 	NULL,
        FACTURA              VARCHAR(50) 	NULL,
        LIM_CREDITO          VARCHAR(1) 	NOT NULL,
        DOC_VENCIDO          VARCHAR(1) 	NOT NULL,
        COBRO_JUDICIAL       VARCHAR(1) 	NOT NULL,
        SIN_OC               VARCHAR(1) 	NOT NULL,
        USUARIO              VARCHAR(25) 	NULL,
        FECHA_HORA           DATETIME 		NULL,
        VIGENTE              VARCHAR(1) 	NOT NULL,
        APROBADA             VARCHAR(1) 	NOT NULL,
        MARGEN_ARTICULO      VARCHAR(1) 	NOT NULL,
        VALOR_VENTA_MENOR    VARCHAR(1) 	NOT NULL,
        MONTO_MINIMO         VARCHAR(1) 	NOT NULL,
        DIAS_ATRASO          VARCHAR(1) 	NOT NULL,
        APROBADA_VENTAS      VARCHAR(1) 	NOT NULL,
        USUARIO_VENTAS       VARCHAR(25) 	NULL,
        FECHA_HORA_VENTAS    DATETIME 		NULL,
        APROBADA_CREDITO     VARCHAR(1) 	NOT NULL,
        FECHA_HORA_CREDITO   DATETIME 		NULL,
        USUARIO_CREDITO      VARCHAR(25) 	NULL,
        DCTO_GENERAL         VARCHAR(1) 	NOT NULL,
        COMENTARIO           TEXT 		NULL
 )
go
 
 
 ALTER TABLE PEDIDO_AUTORIZA
        ADD CONSTRAINT PEDIDOAUTORIZPK PRIMARY KEY NONCLUSTERED (
               PEDIDO, CONSECUTIVO)
go
 

CREATE TABLE PEDIDO_EDI (
	NUMEROORDEN          		VARCHAR(30) 	NOT NULL,
	GLN_COMPRADOR        		VARCHAR(13) 	NOT NULL,
	PEDIDO        			VARCHAR(50) 	NULL,
	CEDULAJURIDICA_COMPRADOR 	VARCHAR(20) 	NOT NULL,
	NOMBREEMPRESACOMPRADOR  	VARCHAR(80) 	NOT NULL,
	DEPARTAMENTO_COMPRADOR 		VARCHAR(17) 	NULL,
	CONTACTO_COMPRADOR   		VARCHAR(35) 	NULL,
	TELEFONO_COMPRADOR   		VARCHAR(25) 	NULL,
	URGENTE              		VARCHAR(1) 	NULL,
	PORTON_ENTREGA       		VARCHAR(3) 	NULL,
	INFORMACION_ADICIONAL 		VARCHAR(350) 	NULL,
	FECHA_EMISION_ORDEN  		DATETIME 	NOT NULL default ERPADMIN.SF_GETDATE(),
	FECHA_ENTREGA        		DATETIME 	NOT NULL default ERPADMIN.SF_GETDATE(), 
	GLN_LUGARENTREGA     		VARCHAR(13) 	NULL,
	CEDULAJURIDICA_LUGARENTREGA 	VARCHAR(20) 	NULL,
	NOMBRE_EMPRESA_LUGARENTREGA 	VARCHAR(80) 	NULL,
	DEPARTAMENTO_LUGARENTREGA 	VARCHAR(17) 	NULL,
	CONTACTO_LUGARENTREGA 		VARCHAR(35) 	NULL,
	TELEFONO_LUGARENTREGA 		VARCHAR(25) 	NULL,
	TOTAL_ORDEN          		DECIMAL(28,8) 	NOT NULL default(0),
	SUBTOTAL_ORDEN       		DECIMAL(28,8) 	NOT NULL default(0),
	TOTAL_IMPUESTOS      		DECIMAL(28,8) 	NOT NULL default(0),
	TOTAL_DESCUENTOS     		DECIMAL(28,8) 	NOT NULL default(0),
	ESTADO				VARCHAR(1) 	NOT NULL default('P')
)
go


 ALTER TABLE PEDIDO_EDI
        ADD CONSTRAINT PEDIDOEDIPK PRIMARY KEY NONCLUSTERED(NUMEROORDEN,GLN_COMPRADOR)
go        


 
 CREATE TABLE PEDIDO_LINEA (
        PEDIDO               	VARCHAR(50) 	NOT NULL,
        PEDIDO_LINEA         	smallint 	NOT NULL,
        BODEGA               	VARCHAR(4) 	NOT NULL,
        LOTE                 	VARCHAR(15) 	NULL,
        LOCALIZACION         	VARCHAR(8) 	NULL,
        ARTICULO             	VARCHAR(20) 	NOT NULL,
        ESTADO               	VARCHAR(1) 	NOT NULL,
        FECHA_ENTREGA        	DATETIME 	NOT NULL,
        LINEA_USUARIO        	smallint 	NOT NULL,
        PRECIO_UNITARIO      	DECIMAL(28,8) 	NOT NULL,
        CANTIDAD_PEDIDA      	DECIMAL(28,8) 	NOT NULL,
        CANTIDAD_A_FACTURA   	DECIMAL(28,8) 	NOT NULL,
        CANTIDAD_FACTURADA   	DECIMAL(28,8) 	NOT NULL,
        CANTIDAD_RESERVADA   	DECIMAL(28,8) 	NOT NULL,
        CANTIDAD_BONIFICAD   	DECIMAL(28,8) 	NOT NULL,
        CANTIDAD_CANCELADA   	DECIMAL(28,8) 	NOT NULL,
        TIPO_DESCUENTO       	VARCHAR(1) 	NOT NULL,
        MONTO_DESCUENTO      	DECIMAL(28,8) 	NOT NULL,
        PORC_DESCUENTO       	DECIMAL(28,8) 	NOT NULL,
        DESCRIPCION          	TEXT 		NULL,
        COMENTARIO           	VARCHAR(100) 	NULL,
        PEDIDO_LINEA_BONIF   	smallint 	NULL,
        UNIDAD_DISTRIBUCIO   	VARCHAR(6) 	NULL,
        FECHA_PROMETIDA      	DATETIME 	NOT NULL,
        LINEA_ORDEN_COMPRA   	INT      	NULL,
        PROYECTO				VARCHAR(25) 	NULL,
		FASE					VARCHAR(25)  	NULL,
		CENTRO_COSTO 			VARCHAR(25) 	NULL,
		CUENTA_CONTABLE 		VARCHAR(25) 	NULL,
		RAZON_PERDIDA 			VARCHAR(250) 	NULL,
		TIPO_DESC 				VARCHAR(10) NULL
 )
go
 
 
 ALTER TABLE PEDIDO_LINEA
        ADD CONSTRAINT PEDIDO_LINEAPK PRIMARY KEY NONCLUSTERED (
               PEDIDO, PEDIDO_LINEA)
go


CREATE TABLE PEDIDO_SOLICITUD_LINEA
(
	PEDIDO 			VARCHAR(50) 	NOT NULL,
	PEDIDO_LINEA 		SMALLINT 	NOT NULL,	
	SOLICITUD_OC 		VARCHAR(10) 	NOT NULL,
	SOLICITUD_OC_LINEA 	SMALLINT 	NOT NULL	
)
go

CREATE TABLE PLAN_PAGO_DOC (
         CONSECUTIVO_PAGO		INT		NOT NULL,
         DOCUMENTO			VARCHAR(50)	NOT NULL,
         TIPO_DOCUMENTO			VARCHAR(1)	NOT NULL,
         FECHA_RIGE			DATETIME	NOT NULL,
         FECHA_VENCE			DATETIME	NOT NULL,
         PORCENTAJE			DECIMAL(28,8)	NOT NULL,
         SALDO				DECIMAL(28,8)	NOT NULL,
         MONTO_PRINCIPAL		DECIMAL(28,8)	NOT NULL,
         SALDO_PRINCIPAL		DECIMAL(28,8)	NOT NULL,
         MONTO_AMORTIZA			DECIMAL(28,8)	NOT NULL,
         SALDO_AMORTIZA			DECIMAL(28,8)	NOT NULL,
         MONTO_INTERES			DECIMAL(28,8)	NOT NULL,
         SALDO_INTERES			DECIMAL(28,8)	NOT NULL,
         MONTO_CUOTA			DECIMAL(28,8)	NOT NULL,
         SALDO_CUOTA			DECIMAL(28,8)	NOT NULL,
         FECHA_PROYECTADA		DATETIME	NULL,
         MONTO_IMP_RENTA 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_RENTA_LOCAL 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_RENTA_DOLAR 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_CREE1 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_CREE1_LOCAL 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_CREE1_DOLAR 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_CREE2 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_CREE2_LOCAL 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_CREE2_DOLAR 		DECIMAL(28, 8) 	NULL,
         MONTO_GAN_OCASIONAL 		DECIMAL(28, 8) 	NULL,
         MONTO_GAN_OCASIONAL_LOCAL 	DECIMAL(28, 8) 	NULL,
         MONTO_GAN_OCASIONAL_DOLAR 	DECIMAL(28, 8) 	NULL
         
)
go


ALTER TABLE PLAN_PAGO_DOC
         ADD CONSTRAINT PKPLANPAGODOC PRIMARY KEY NONCLUSTERED
         (CONSECUTIVO_PAGO, DOCUMENTO, TIPO_DOCUMENTO )
go


CREATE TABLE PLAN_PAGO_PED (
         CONSECUTIVO_PAGO		INT		NOT NULL,
         DOCUMENTO			VARCHAR(50)	NOT NULL,
         TIPO_DOCUMENTO			VARCHAR(1)	NOT NULL,
         FECHA_RIGE			DATETIME	NOT NULL,
         FECHA_VENCE			DATETIME	NOT NULL,
         PORCENTAJE			DECIMAL(28,8)	NOT NULL,
         SALDO				DECIMAL(28,8)	NOT NULL,
         MONTO_PRINCIPAL		DECIMAL(28,8)	NOT NULL,
         SALDO_PRINCIPAL		DECIMAL(28,8)	NOT NULL,
         MONTO_AMORTIZA			DECIMAL(28,8)	NOT NULL,
         SALDO_AMORTIZA			DECIMAL(28,8)	NOT NULL,
         MONTO_INTERES			DECIMAL(28,8)	NOT NULL,
         SALDO_INTERES			DECIMAL(28,8)	NOT NULL,
         MONTO_CUOTA			DECIMAL(28,8)	NOT NULL,
         SALDO_CUOTA			DECIMAL(28,8)	NOT NULL,
         FECHA_PROYECTADA		DATETIME	NULL,
         MONTO_IMP_RENTA 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_RENTA_LOCAL 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_RENTA_DOLAR 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_CREE1 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_CREE1_LOCAL 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_CREE1_DOLAR 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_CREE2 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_CREE2_LOCAL 		DECIMAL(28, 8) 	NULL,
         MONTO_IMP_CREE2_DOLAR 		DECIMAL(28, 8) 	NULL,
         MONTO_GAN_OCASIONAL 		DECIMAL(28, 8) 	NULL,
         MONTO_GAN_OCASIONAL_LOCAL 	DECIMAL(28, 8) 	NULL,
         MONTO_GAN_OCASIONAL_DOLAR 	DECIMAL(28, 8) 	NULL
         
)
go


ALTER TABLE PLAN_PAGO_PED
         ADD CONSTRAINT PKPLANPAGOPED PRIMARY KEY NONCLUSTERED
         (CONSECUTIVO_PAGO, DOCUMENTO )
go

CREATE TABLE REGLA_ARTICULO 
(
	   REGLA_DESCUENTO    INT 	  NOT NULL,
       	   ARTICULO           VARCHAR(20) NOT NULL
)
go

ALTER TABLE REGLA_ARTICULO
       ADD CONSTRAINT XPKREGLA_ARTICULO
       		PRIMARY KEY (REGLA_DESCUENTO, ARTICULO)
go       		

CREATE TABLE REGLA_DESCUENTO(
       	REGLA_DESCUENTO 	INT		NOT NULL,
       	DESCRIPCION             VARCHAR(254)	NOT NULL,
	ACTIVO			VARCHAR(1)	NOT NULL,
	DESCUENTO		DECIMAL(28,8)	NULL,
	PRIORIDAD		INT		NULL,
	CATEGORIA_CLIENTE	VARCHAR(8)	NULL,
	CLIENTE			VARCHAR(20)	NULL,
	CLASIFICACION		VARCHAR(12)	NULL,
	ARTICULO		VARCHAR(20)	NULL,
	ARTICULO_PATRON		VARCHAR(20)	NULL,
	NOTAS			TEXT		NULL,
	TIPO_DESCUENTO 	        VARCHAR(1) 	NOT NULL, 
	CANTIDAD_COMPRA	        DECIMAL(28,8)   NULL,
	CANTIDAD_FACTURAR       DECIMAL(28,8)   NULL,
	CLASIFICACION2 		VARCHAR(12) 	NULL,
	CLASIFICACION3 		VARCHAR(12) 	NULL,
	CLASIFICACION4 		VARCHAR(12) 	NULL,
	CLASIFICACION5 		VARCHAR(12) 	NULL,
	CLASIFICACION6 		VARCHAR(12) 	NULL,
	REQUIERE_AUTORIZACION	VARCHAR(1) 	NOT NULL DEFAULT('N'),
	FORMA_PAGO		VARCHAR(4) 	NULL,
	DETALLE_FORMA_PAGO	VARCHAR(20) 	NULL,
	MINIMO_DOCUMENTO	DECIMAL(28,8) 	NULL,
	MINIMO_PAGO		DECIMAL(28,8) 	NULL,
	DESC_FORMA_PAGO		DECIMAL(28,8) 	NULL
	
)
go

ALTER TABLE REGLA_DESCUENTO
       ADD CONSTRAINT XPKREGLADESCUENTO 
       	PRIMARY KEY NONCLUSTERED (REGLA_DESCUENTO)
go       	

 
CREATE TABLE RESOLUCION_DOC_ELECTRONICO (
	RESOLUCION			VARCHAR(20)  	NOT NULL,
	CAJA 				VARCHAR(6) 	NULL,
	TIPO_DOCUMENTO			VARCHAR(1) 	NOT NULL,
	TIPO_ACTIVO			VARCHAR(8)	NOT NULL,
	FECHA_RESOLUCION		DATETIME 	NULL,
	FECHA_AUTORIZACION	    	DATETIME 	NULL,
	NUMERO_AUTORIZACION		VARCHAR(80)  	NULL,
	FECHA_CREACION			DATETIME 	NULL,
	INFORMACION_REGIMEN		VARCHAR(15)  	NOT NULL DEFAULT('PAGO_TRIMESTRAL'),
	SERIE				VARCHAR(20)  	NOT NULL,
	MASCARA			        VARCHAR(50)	NULL,
	FOLIO_INICIAL			INT		NOT NULL,
	FOLIO_FINAL			INT		NOT NULL,
	ULTIMO_FOLIO			INT		NULL,
	ESTADO				VARCHAR(1) 	NOT NULL,
	USUARIO_CREACION		VARCHAR(25)  	NOT NULL,
	SUCURSAL			VARCHAR(80)  	NOT NULL,
	NOMBRE_SUCURSAL			VARCHAR(150)  	NOT NULL,       
	DISPOSITIVO_ELECTRONICO		VARCHAR(4)	NULL	DEFAULT('000'),
	DIRECCION1			VARCHAR(80)	NULL,
	MUNICIPIO			VARCHAR(35)  	NULL,
	DEPARTAMENTO			VARCHAR(80)	NULL,
	CODIGO_PAIS			VARCHAR(6)   	NULL   DEFAULT('GT'),
	FORMATO_PDF			VARCHAR(300) 	NULL,
	FORMATO_XSLT			VARCHAR(300) 	NULL,
	ANNO_ACTUAL			INT		NULL,
	CORRELATIVO			INT		NULL,
	SIN_VENCIMIENTO 		VARCHAR(1) 	NOT NULL DEFAULT('N')
)
go


ALTER TABLE RESOLUCION_DOC_ELECTRONICO
         ADD CONSTRAINT PKRESOLUCION_DOC_ELECTRONICO PRIMARY KEY NONCLUSTERED (RESOLUCION)
go 
 
 
 

CREATE TABLE SEGUIMIENTO_FACT (
         CONSECUTIVO	INT			NOT NULL,
         FACTURA	VARCHAR(10)		NOT NULL,
         ESTADO		VARCHAR(1)		NOT NULL,
         DESCRIPCION	VARCHAR(50)		NULL,
         MEDIO		VARCHAR(1)		NOT NULL,
         FUENTE		VARCHAR(10)		NOT NULL 
         )
go         

 
 CREATE TABLE SUBTIPO_DOC_CC (
        TIPO                 VARCHAR(3) 	NOT NULL,
        SUBTIPO              smallint 		NOT NULL,
        TIPO_CB              VARCHAR(3) 	NULL,
        SUBTIPO_CB           smallint 		NULL,
        DESCRIPCION          VARCHAR(25) 	NOT NULL,
        CUENTA_CONTABLE      VARCHAR(25) 	NULL,
        CENTRO_COSTO         VARCHAR(25) 	NULL,
        CALCULA_IMP2 	     VARCHAR(1) 	NOT NULL DEFAULT 'S',
	TIPO_ASIENTO 	     VARCHAR(4) 	NULL,
	PAQUETE 	     VARCHAR(4) 	NULL,
	TIPO_SERVICIO 	     VARCHAR(2) 	NULL,
	DOCUMENTO_GLOBAL     VARCHAR(10) 	NULL
 )
go
 
 
 ALTER TABLE SUBTIPO_DOC_CC
        ADD CONSTRAINT XPKSUBTIPO_DOC_CC PRIMARY KEY (TIPO, SUBTIPO)
go


CREATE TABLE USUARIO_CAJA_FA (
         CAJA			VARCHAR(10)	NOT NULL,
         USUARIO		VARCHAR(25)	NOT NULL,
         PRIVILEGIOS		VARCHAR(1)	NOT NULL,
         PORC_DIFERENCIA	DECIMAL(28,8)	NULL,
         MONTO_DIF_DOLAR	DECIMAL(28,8)	NULL,
         NOTAS			TEXT		NULL )
go


ALTER TABLE USUARIO_CAJA_FA
         ADD CONSTRAINT PKUSR_CAJA PRIMARY KEY NONCLUSTERED
         (CAJA, USUARIO )
go 
 
CREATE TABLE USO_CFDI(	
USO_CFDI VARCHAR(3) NOT NULL,
DESCRIPCION VARCHAR(150) NULL,
TIPO_PERSONA_FISICA VARCHAR(1) NULL,
TIPO_PERSONA_MORAL	VARCHAR(1) NULL
)
go
 
 CREATE TABLE VERSION_NIVEL (
        NIVEL_PRECIO         VARCHAR(12) 	NOT NULL,
        MONEDA               VARCHAR(1) 	NOT NULL,
        VERSION              int 		NOT NULL,
        FECHA_INICIO         DATETIME 		NOT NULL,
        FECHA_CORTE          DATETIME 		NOT NULL,
        ESTADO               VARCHAR(1) 	NOT NULL,
        USUARIO_CREACION     VARCHAR(25) 	NOT NULL,
        FCH_HORA_CREACION    DATETIME 		NOT NULL,
        USUARIO_ULT_MODIF    VARCHAR(25) 	NULL,
        FCH_HORA_ULT_MODIF   DATETIME 		NULL,
        USUARIO_APROBACION   VARCHAR(25) 	NULL,
        FCH_HORA_APROBACIO   DATETIME 		NULL,
        USUARIO_ANULACION    VARCHAR(25) 	NULL,
        FCH_HORA_ANULACION   DATETIME 		NULL,
        IDENTIFICADOR 	     VARCHAR(10) 	NULL,
        IMPUESTO1_INCLUIDO   VARCHAR(1) 	NOT NULL DEFAULT('N')
 )
go
 
 
 ALTER TABLE VERSION_NIVEL
        ADD CONSTRAINT XPKVERSION_NIVEL PRIMARY KEY (NIVEL_PRECIO, 
               MONEDA, VERSION)
go
 
 
 