CREATE UNIQUE INDEX XAK1LSTPRECIOALDO ON ERPADMIN.LSTPRECIO_ALDO_RT 
(
         COMPANIA,
         NIVEL_PRECIO,
         MONEDA, FECHA, RUTA 
)
go

CREATE  INDEX XAK1FECHAHORAINI ON ERPADMIN.VISITAS_DET_RT 
(
         FECHA_HORA_INI 

)
go

CREATE  INDEX XAK1FECHAHORAFIN ON ERPADMIN.VISITAS_DET_RT 
(
         FECHA_HORA_FIN 
)
go

CREATE  INDEX XAK1FECHAPLAN ON ERPADMIN.VISITAS_RT
(
         FECHA_PLAN 
)
go

CREATE  INDEX XAK1FECHAREAL ON ERPADMIN.VISITAS_RT
(
         FECHA_REAL 
)
go

CREATE INDEX XIDOCLINEA ON ERPADMIN.HISTORIAL_DESCUENTOS 
(
	DOCUMENTO
)
go

CREATE INDEX XIREGLA ON ERPADMIN.HISTORIAL_DESCUENTOS 
(
	LINEA, ARTICULO
)
	INCLUDE (REGLA)
go