
ALTER TABLE ERPADMIN.alFAC_DESC_PRONTO_PAGO
	ADD CONSTRAINT  FK_DESCPRONTOPAGOCNDPAG FOREIGN KEY ( COD_CND, COD_CIA) 
		REFERENCES ERPADMIN.alFAC_CND_PAG( COD_CND, COD_CIA)
			ON DELETE CASCADE
go			

ALTER TABLE ERPADMIN.AGENTE_ASOC_RT
	ADD CONSTRAINT AGTASOCAGT
		FOREIGN KEY ( AGENTE )
         		REFERENCES ERPADMIN.AGENTE_RT
         			ON DELETE CASCADE
go


ALTER TABLE ERPADMIN.ARCHIVO_DETALLE_FR
         ADD CONSTRAINT FKARCHIVOFR_DETALLEARCHIVOFR
         	FOREIGN KEY  ( VERSION, ARCHIVO, TIPO_ARCHIVO )
         		REFERENCES ERPADMIN.ARCHIVO_FR ( VERSION, ARCHIVO, TIPO_ARCHIVO ) 
         			ON DELETE CASCADE
go



ALTER TABLE ERPADMIN.ARCHIVO_HANDHELD
         ADD CONSTRAINT FKHH_ARCHIVOHH
         	FOREIGN KEY  ( HANDHELD )
         		REFERENCES ERPADMIN.HANDHELD_RT ( HANDHELD )
go
 
 
 
ALTER TABLE ERPADMIN.ARCHIVO_HANDHELD
         ADD CONSTRAINT FKARCHIVOHH_ARCHIVOFR
         	FOREIGN KEY  ( VERSION, ARCHIVO, TIPO_ARCHIVO )
         		REFERENCES ERPADMIN.ARCHIVO_FR ( VERSION, ARCHIVO, TIPO_ARCHIVO ) 
         			ON DELETE CASCADE
go



ALTER TABLE ERPADMIN.BODEGA_ASOC_RT  ADD
	CONSTRAINT FK_BODEGA 
		FOREIGN KEY (BODEGA) 
			REFERENCES ERPADMIN.BODEGA_RT (BODEGA) 
go

ALTER TABLE ERPADMIN.CLIENTE_ASOC_RT
	ADD CONSTRAINT CLNTASOCCLNT
		FOREIGN KEY  ( CLIENTE )
			REFERENCES ERPADMIN.CLIENTE_RT ( CLIENTE ) 
				ON DELETE CASCADE
go

			
ALTER TABLE ERPADMIN.DES_BON_PAQUETE_REGLA
	ADD CONSTRAINT FK_PAQUETE_REGLA_PAQUETE
		FOREIGN KEY(COMPANIA, PAQUETE) 
			REFERENCES ERPADMIN.DES_BON_PAQUETE (COMPANIA, PAQUETE)
go
		
		
ALTER TABLE ERPADMIN.DES_BON_PAQUETE_REGLA
	ADD CONSTRAINT FK_PAQUETE_REGLA_REGLA
		FOREIGN KEY(COMPANIA, REGLA) 
			REFERENCES ERPADMIN.DES_BON_REGLA (COMPANIA, REGLA)
go



		
ALTER TABLE ERPADMIN.DES_BON_ESCALA_BONIFICACION
	ADD CONSTRAINT FK_ESCALA_BONIFICACION_REGLA
		FOREIGN KEY(COMPANIA, REGLA) 
			REFERENCES ERPADMIN.DES_BON_REGLA (COMPANIA, REGLA)
go


ALTER TABLE ERPADMIN.DES_BON_ESPECIFICACION_GRUPO  WITH CHECK 
	ADD  CONSTRAINT FK_ESPECIFICACION_GRUPO_REGLA 
		FOREIGN KEY(COMPANIA, REGLA)
			REFERENCES ERPADMIN.DES_BON_REGLA (COMPANIA, REGLA)
go


ALTER TABLE ERPADMIN.DES_BON_PAQUETE_RUTA
	ADD CONSTRAINT FK_DESBONPAQRUTA_PAQUETE
		FOREIGN KEY(COMPANIA, PAQUETE) 
			REFERENCES ERPADMIN.DES_BON_PAQUETE (COMPANIA, PAQUETE)
go


ALTER TABLE ERPADMIN.DES_BON_PAQUETE_RUTA
	ADD CONSTRAINT FK_DESBONPAQRUTA_RUTA
		FOREIGN KEY(RUTA) 
			REFERENCES ERPADMIN.RUTA_RT (RUTA)
go


ALTER TABLE ERPADMIN.DES_BON_PAQUETE_TIENDA
	ADD CONSTRAINT FK_DESBONPAQTIENDA_PAQUETE
		FOREIGN KEY(COMPANIA, PAQUETE) 
			REFERENCES ERPADMIN.DES_BON_PAQUETE (COMPANIA, PAQUETE)
go


ALTER TABLE ERPADMIN.DET_MOD_RETENCION 
	ADD CONSTRAINT  DET_MOD_RETENCION_FKMOD FOREIGN KEY (MODELO_RETENCION,COD_CIA) 
		REFERENCES ERPADMIN.MODELO_RETENCION(MODELO_RETENCION,COD_CIA)
go


ALTER TABLE $$COMPANIA$$.FACTURA_CANCELA_FR  
	ADD  CONSTRAINT FKFAC_FACCANCEFR 
		FOREIGN KEY(TIPO_DOCUMENTO, FACTURA) 
			REFERENCES $$COMPANIA$$.FACTURA (TIPO_DOCUMENTO, FACTURA)
go



ALTER TABLE $$COMPANIA$$.FACTURA_CANCELA_FR CHECK CONSTRAINT FKFAC_FACCANCEFR
go



ALTER TABLE ERPADMIN.GLOBALES_CONF_FR  
	ADD  CONSTRAINT FKHHGLOBALESCONFFR FOREIGN KEY(HANDHELD)
		REFERENCES ERPADMIN.HANDHELD_RT (HANDHELD)
 			ON DELETE CASCADE
go 			



ALTER TABLE ERPADMIN.GRUPO_ART_ASOC_RT
	ADD CONSTRAINT GRPASOARTCGRPART
		FOREIGN KEY  ( GRUPO_ARTICULO )
			REFERENCES ERPADMIN.GRUPO_ARTICULO_RT ( GRUPO_ARTICULO ) 
				ON DELETE CASCADE
go

ALTER TABLE ERPADMIN.GRUPO_ART_ASOC_RT
	ADD CONSTRAINT GRPASOARTARTRT
		FOREIGN KEY  ( COMPANIA, ARTICULO )
			REFERENCES ERPADMIN.ARTICULO_RT ( COMPANIA, ARTICULO ) 
			ON DELETE CASCADE
go





ALTER TABLE erpadmin.NCF_CONSECUTIVO_RT
        ADD CONSTRAINT FK_NCFCONSECCIA
               FOREIGN KEY ( COMPANIA )
                              REFERENCES erpadmin.COMPANIA ( COMPANIA )
go                              


ALTER TABLE erpadmin.NCF_CONSECUTIVO_RT
        ADD CONSTRAINT FK_NCFCONSECHH
               FOREIGN KEY ( HANDHELD )
                              REFERENCES erpadmin.HANDHELD_RT( HANDHELD )
go                             


ALTER TABLE ERPADMIN.REGIMENES 
	ADD CONSTRAINT XFKREGIMENES_MOD_RET FOREIGN KEY(MODELO_RETENCION,COD_CIA) 
		REFERENCES ERPADMIN.MODELO_RETENCION(MODELO_RETENCION,COD_CIA)
go


ALTER TABLE ERPADMIN.RUTA_ASIGNADA_RT
	ADD CONSTRAINT RUTAASIGHH
		FOREIGN KEY  ( HANDHELD )
			REFERENCES ERPADMIN.HANDHELD_RT ( HANDHELD )
go

ALTER TABLE ERPADMIN.RUTA_ASIGNADA_RT
	ADD CONSTRAINT RUTAASIGAGNT
		FOREIGN KEY  ( AGENTE )
			REFERENCES ERPADMIN.AGENTE_RT ( AGENTE )
go

ALTER TABLE ERPADMIN.RUTA_ASIGNADA_RT
	ADD CONSTRAINT RUTAASIG
		FOREIGN KEY  ( GRUPO_ARTICULO )
			REFERENCES ERPADMIN.GRUPO_ARTICULO_RT ( GRUPO_ARTICULO )
go

ALTER TABLE ERPADMIN.RUTA_ASIGNADA_RT
	ADD CONSTRAINT RUTAASIGRUTA
		FOREIGN KEY  ( RUTA )
			REFERENCES ERPADMIN.RUTA_RT ( RUTA )
go

ALTER TABLE ERPADMIN.RUTA_ASIGNADA_RT  
	ADD CONSTRAINT RUTAASIGBOD 
		FOREIGN KEY( BODEGA )
			REFERENCES ERPADMIN.BODEGA_RT ( BODEGA )
go

ALTER TABLE ERPADMIN.RUTA_CLIENTE  
	ADD  CONSTRAINT RT_RUTACLIENTECLIENTE 
		FOREIGN KEY( CLIENTE )
			REFERENCES ERPADMIN.CLIENTE_RT ( CLIENTE ) 
				ON DELETE CASCADE
go

ALTER TABLE ERPADMIN.RUTA_CLIENTE  
	ADD CONSTRAINT RT_RUTACLIENTERUTA 
		FOREIGN KEY ( RUTA )
			REFERENCES ERPADMIN.RUTA_ASIGNADA_RT (RUTA) 
				ON DELETE CASCADE
go

ALTER TABLE ERPADMIN.RUTA_CONSECUT_RT
	ADD CONSTRAINT RUTACONSECRUTA
		FOREIGN KEY  ( RUTA )
			REFERENCES ERPADMIN.RUTA_RT ( RUTA ) 
				ON DELETE CASCADE
go

ALTER TABLE ERPADMIN.SUGERIDOVENTA_DETALLE 
	ADD CONSTRAINT FK_SUGERIDO 
		FOREIGN KEY(SUGERIDO) 
			REFERENCES ERPADMIN.SUGERIDOVENTA (SUGERIDO) 

go
ALTER TABLE ERPADMIN.SUGERIDO_ASOC 
	ADD CONSTRAINT FK_CLIENTE_RT 
		FOREIGN KEY (CLIENTE) 
			REFERENCES ERPADMIN.CLIENTE_RT (CLIENTE)
go

ALTER TABLE ERPADMIN.SUGERIDO_ASOC 
	ADD CONSTRAINT FK_SUGERIDO_ASOC 
		FOREIGN KEY (SUGERIDO) 
			REFERENCES ERPADMIN.SUGERIDOVENTA (SUGERIDO)
go

ALTER TABLE ERPADMIN.SUGERIDO_ASOC_LINEA 
	ADD CONSTRAINT FK_ARTICULO_RT 
		FOREIGN KEY (COMPANIA,ARTICULO) 
			REFERENCES ERPADMIN.ARTICULO_RT (COMPANIA,ARTICULO)
go

ALTER TABLE ERPADMIN.SUGERIDO_ASOC_LINEA 
	ADD CONSTRAINT FK_SUGERIDOVENTA 
		FOREIGN KEY (CLIENTE,SUGERIDO) 
			REFERENCES ERPADMIN.SUGERIDO_ASOC (CLIENTE,SUGERIDO) 
				ON DELETE CASCADE 
go

ALTER TABLE ERPADMIN.VISITAS_RT
	ADD CONSTRAINT VISITARUTA
		FOREIGN KEY  ( RUTA )
			REFERENCES ERPADMIN.RUTA_RT ( RUTA )
go

ALTER TABLE ERPADMIN.VISITAS_RT
	ADD CONSTRAINT VISITACLIENTE
		FOREIGN KEY  ( CLIENTE )
			REFERENCES ERPADMIN.CLIENTE_RT ( CLIENTE ) 
				ON DELETE CASCADE
go

ALTER TABLE ERPADMIN.VISITAS_DET_RT
	ADD CONSTRAINT VISITADETRUTA
		FOREIGN KEY  ( RUTA )
			REFERENCES ERPADMIN.RUTA_RT ( RUTA )
go

ALTER TABLE ERPADMIN.VISITAS_DET_RT
	ADD CONSTRAINT VISITADETCLIENTE
		FOREIGN KEY  ( CLIENTE )
			REFERENCES ERPADMIN.CLIENTE_RT ( CLIENTE ) 
				ON DELETE CASCADE
go

ALTER TABLE ERPADMIN.VISITAS_DET_RT
	ADD CONSTRAINT VISITADETEFECT
		FOREIGN KEY  ( EFECT_VISITA )
			REFERENCES ERPADMIN.EFECT_VISITA_RT ( EFECT_VISITA )
go

