
CREATE TABLE ERPADMIN.LINEA_DEPOSITO(
	NUMERO			DECIMAL(28,0)	NOT NULL,
	DOCUMENTO		VARCHAR(20)	NOT NULL,
	TIPO_CC			VARCHAR(3)	NULL,
	CUENTA_BANCO		VARCHAR(20)	NOT NULL,
	TIPO_CB			VARCHAR(3)	NULL,
	MONTO_EFECTIVO		DECIMAL(28,8)	NULL,
	MONTO_CHEQUES		DECIMAL(28,8)	NULL,
	REFERENCIAS		VARCHAR(80)	NULL
)
go	

ALTER TABLE ERPADMIN.LINEA_DEPOSITO
       ADD CONSTRAINT PK_LINEA_DEPOSITO PRIMARY KEY (NUMERO, DOCUMENTO)
go       


CREATE TABLE ERPADMIN.AGENTE_ASOC_RT (
         AGENTE         VARCHAR(4)   NOT NULL,
         COMPANIA	VARCHAR(10)  NOT NULL,
         CODIGO         VARCHAR(4)   NOT NULL,
         TIPO         	VARCHAR(1)   NOT NULL 
)
go

ALTER TABLE ERPADMIN.AGENTE_ASOC_RT
         ADD CONSTRAINT XPKAGENTEASOC 
         	PRIMARY KEY NONCLUSTERED (AGENTE, COMPANIA, CODIGO, TIPO )
go

ALTER TABLE ERPADMIN.AGENTE_ASOC_RT
         ADD CONSTRAINT XAK1AGENTE_ASOC_RT 
         	UNIQUE NONCLUSTERED (AGENTE,COMPANIA,TIPO)
go


CREATE TABLE ERPADMIN.AGENTE_RT (
         AGENTE         VARCHAR(4)   NOT NULL,
         NOMBRE         VARCHAR(40)  NOT NULL )
go

ALTER TABLE ERPADMIN.AGENTE_RT
         ADD CONSTRAINT XPKAGENTE 
         	PRIMARY KEY NONCLUSTERED (AGENTE )
go


CREATE TABLE ERPADMIN.AGENTE_VISITA_RT (
         AGENTE         VARCHAR(4) 	NOT NULL,
         RUTA        	VARCHAR(4) 	NOT NULL,
         COMPANIA    	VARCHAR(10)	NOT NULL,
         FECHA_INICIO	DATETIME   	NOT NULL,
         FECHA_FIN      DATETIME        NOT NULL 
)
go

CREATE TABLE ERPADMIN.AUTOR_VENTA (
         CODIGO			VARCHAR(4)	NOT NULL ,
         DESCRIPCION		VARCHAR(30)	NOT NULL,
         CLIENTE		VARCHAR(20)		NOT NULL,
         NUM_AUTOR	VARCHAR(50) NOT	NULL,
         FECHA_RIGE	DATETIME NOT	NULL,
		 FECHA_VENCE	DATETIME NOT	NULL,
         PORCENTAJE			DECIMAL(28,8)	NOT NULL,
         NOTAS			TEXT		NULL,
		 TIPO_DOC		VARCHAR(3)	 NULL,
		 NOMBRE_INSTITUCION		VARCHAR(100)	 NULL
 )
go
  

ALTER TABLE ERPADMIN.AUTOR_VENTA ADD PRIMARY KEY (CODIGO)
go

CREATE TABLE ERPADMIN.CLASIFICACION_VENTA (
         CODIGO			VARCHAR(4)	 NULL,
         CODIGO_ARTICULO		VARCHAR(20)	 NULL
         
 )
go




ALTER TABLE ERPADMIN.AGENTE_VISITA_RT
         ADD CONSTRAINT XPKAGENTEVISITA 
         	PRIMARY KEY NONCLUSTERED (AGENTE, RUTA, COMPANIA, FECHA_INICIO )
go

CREATE TABLE ERPADMIN.alCXC_BCO (
       COD_BCO              VARCHAR(10) NOT NULL,
       COD_CIA              VARCHAR(10) NOT NULL,
       DES_BCO              VARCHAR(40) NOT NULL
)
go

ALTER TABLE ERPADMIN.alCXC_BCO ADD
	CONSTRAINT BANCO_PK PRIMARY KEY NONCLUSTERED (COD_BCO, COD_CIA)
go

CREATE TABLE ERPADMIN.alCXC_CHE (
       COD_CIA              VARCHAR(10) 	NOT NULL,
       COD_ZON              VARCHAR(4) 		NOT NULL,
       COD_BCO              VARCHAR(10) 	NOT NULL,
       COD_CLT              VARCHAR(20) 	NOT NULL,
       NUM_REC              VARCHAR(20) 	NOT NULL,
       NUM_CHE              VARCHAR(20) 	NOT NULL,
       NUM_CTA              VARCHAR(20) 	NOT NULL,
       MON_CHE              DECIMAL(28,8) 	NOT NULL,
       TIP_DOC              VARCHAR(2) 		NULL,
       FEC_CHE              DATETIME 		NOT NULL
)
go

ALTER TABLE ERPADMIN.alCXC_CHE ADD
	CONSTRAINT XPKalCXC_CHE  
		PRIMARY KEY NONCLUSTERED (COD_CIA, COD_ZON, COD_BCO, COD_CLT, NUM_REC,NUM_CHE, NUM_CTA)
go

CREATE TABLE ERPADMIN.alCXC_CTA_BCO (
       CTA_BCO              VARCHAR(20) NOT NULL,
       COD_BCO              VARCHAR(10) NOT NULL,
       NOM_CTA              VARCHAR(40) NOT NULL,
       COD_CIA              VARCHAR(20) NOT NULL,
       MONEDA               VARCHAR(4) NOT NULL
)
go

ALTER TABLE ERPADMIN.alCXC_CTA_BCO ADD
	CONSTRAINT XPKalCXC_CTA_BCO 
		PRIMARY KEY NONCLUSTERED (CTA_BCO, COD_BCO, COD_CIA)
go

CREATE TABLE ERPADMIN.alCXC_DET_DEP (
       NUM_DEP              decimal(28,0) NOT NULL,
       NUM_DOC              VARCHAR(20) NOT NULL,
       MON_CHE              DECIMAL(28,8) NULL,
       MON_EFE              DECIMAL(28,8) NULL,
       REF                  VARCHAR(80) NULL,
	   CTA_BCO 				VARCHAR(20) NOT NULL DEFAULT 'No Definida'
)
go

ALTER TABLE ERPADMIN.alCXC_DET_DEP
	ADD CONSTRAINT PK_alCXC_DET_DEP PRIMARY KEY(NUM_DEP,NUM_DOC,CTA_BCO)
go

CREATE TABLE ERPADMIN.alCXC_DOC_APL (
       COD_CIA              	VARCHAR(10) 	NOT NULL,
       NUM_REC              	VARCHAR(50) 	NOT NULL,
       COD_TIP_DC           	VARCHAR(3) 	NOT NULL,
       COD_ZON              	VARCHAR(4) 	NOT NULL,
       COD_CLT              	VARCHAR(20) 	NOT NULL,
       FEC_PRO              	DATETIME 	NULL,
       IND_ANL              	VARCHAR(1) 	NULL,
       IND_MON              	VARCHAR(1) 	NULL,
       MON_DOC_LOC          	DECIMAL(28,8) 	NOT NULL,
       MON_DOC_DOL          	DECIMAL(28,8) 	NOT NULL,
       MON_EFE_LOCAL        	DECIMAL(28,8) 	NULL DEFAULT 0,
       MON_EFE_DOLAR        	DECIMAL(28,8) 	NULL DEFAULT 0,
       MON_CHE_DOLAR        	DECIMAL(28,8) 	NULL DEFAULT 0,
       MON_CHE_LOCAL        	DECIMAL(28,8)	NULL DEFAULT 0,
       HOR_INI              	DATETIME 	NULL,
       HOR_FIN              	DATETIME 	NULL,
       DOC_PRO              	VARCHAR(1) 	NULL,
       IMPRESO			VARCHAR(1) 	NOT NULL DEFAULT 'N'
)
go

ALTER TABLE ERPADMIN.alCXC_DOC_APL ADD
	CONSTRAINT alCXC_DOC_APL_PK 
		PRIMARY KEY NONCLUSTERED (COD_CIA, NUM_REC, COD_TIP_DC, COD_ZON, COD_CLT)
go

CREATE TABLE ERPADMIN.alCXC_ENC_DEP (
       CTA_BCO              VARCHAR(20) 	NOT NULL,
       COD_BCO              VARCHAR(10) 	NOT NULL,
       COD_CIA              VARCHAR(10) 	NOT NULL,
       NUM_DEP              decimal(28,0) 	NOT NULL,
       MON_DEP              DECIMAL(28,8)	NOT NULL,
       FEC_DEP              DATETIME 		NOT NULL,
       IND_MON              VARCHAR(1) 		NOT NULL,
       NOTAS                VARCHAR(80) 	NULL,
       DOC_PRO              VARCHAR(1) 		NULL,
	   CONSEC_DEP 			INT 			IDENTITY(1,1), 
	   HandHeld 			VARCHAR(30) 	NULL 
)
go

ALTER TABLE ERPADMIN.alCXC_ENC_DEP
	ADD CONSTRAINT PK_alCXC_ENC_DEP 
		PRIMARY KEY (CTA_BCO, COD_BCO, COD_CIA, NUM_DEP, CONSEC_DEP)
go

CREATE TABLE ERPADMIN.alCXC_MOV_DIR (
	COD_CIA		VARCHAR(10) 	NOT NULL,
	COD_TIP_DC	VARCHAR(3) 	NOT NULL,
	COD_ZON		VARCHAR(4) 	NOT NULL,
	NUM_REC		VARCHAR(50) 	NOT NULL,
	NUM_DOC		VARCHAR(50) 	NOT NULL,
	COD_TIP_DA	VARCHAR(3) 	NOT NULL,
	NUM_DOC_AF	VARCHAR(50) 	NOT NULL,
	COD_CLT		VARCHAR(20) 	NOT NULL,
	FEC_DOC		DATETIME 	NULL,
	FEC_PRO		DATETIME 	NULL,
	IND_ANL		VARCHAR(1) 	NULL,
	MON_MOV_LOCAL	DECIMAL(28,8)	NULL,
	MON_MOV_DOL	DECIMAL(28,8) 	NULL,
	MON_SAL_LOC	DECIMAL(28,8) 	NULL,
	MON_SAL_DOL	DECIMAL(28,8) 	NULL,
	DOC_PRO		VARCHAR(1) 	NULL,
	NCF_PREFIJO 	VARCHAR(20) 	NULL,
	NCF 		VARCHAR(20) 	NULL
)
go

ALTER TABLE ERPADMIN.alCXC_MOV_DIR ADD
	CONSTRAINT alCXC_MOV_DIR_PK 
		PRIMARY KEY NONCLUSTERED (COD_CIA, NUM_DOC_AF, NUM_REC, NUM_DOC, COD_TIP_DA,COD_TIP_DC, COD_CLT, COD_ZON)
go

CREATE TABLE ERPADMIN.alCXC_PEN_COB (
       COD_CIA		VARCHAR(20) 	NOT NULL,
       COD_ZON		VARCHAR(4) 	NOT NULL,
       COD_TIP_DC	VARCHAR(18) 	NOT NULL,
       NUM_DOC		VARCHAR(50) 	NOT NULL,
       COD_CLT		VARCHAR(20) 	NOT NULL,
       SALDO_DOLAR	DECIMAL(28,8) 	NULL,
       SALDO_LOCAL	DECIMAL(28,8) 	NULL,
       MONTO_DOLAR	DECIMAL(28,8) 	NULL,
       MONTO_LOCAL	DECIMAL(28,8) 	NULL,
       FEC_DOC_FT	DATETIME 	NULL,
       FEC_PRO		DATETIME 	NULL,
       FEC_VEN		DATETIME 	NULL,
       IND_MON		VARCHAR(20) 	NOT NULL,
       IND_ANL		VARCHAR(20) 	NULL,
       TIP_CMB_DOL	DECIMAL(28,8)	NULL,
       CONDICION_PAGO 	VARCHAR(4)	NULL
)
go

ALTER TABLE ERPADMIN.alCXC_PEN_COB ADD
	CONSTRAINT PENDIENTECOBRO_PK 
		PRIMARY KEY NONCLUSTERED (COD_CIA, COD_TIP_DC, COD_ZON, NUM_DOC, COD_CLT)
go

CREATE TABLE ERPADMIN.alFAC_CND_PAG (
      COD_CND               VARCHAR(4) 	NOT NULL, 
      COD_CIA               VARCHAR(10) NOT NULL,
      CAN_DIA               int 	NOT NULL, 
      DES_CND               VARCHAR(40) NOT NULL
)
go

ALTER TABLE ERPADMIN.alFAC_CND_PAG ADD
	CONSTRAINT CONDICIONP_PK 
		PRIMARY KEY NONCLUSTERED (COD_CND, COD_CIA)
go


CREATE TABLE ERPADMIN.alFAC_DESC_PRONTO_PAGO
(
	COD_CIA 		VARCHAR(10) 	NOT NULL,
	COD_CND 		VARCHAR(4) 	NOT NULL,
	CONSECUTIVO 		int 		NOT NULL,
	DIA_INICIO 		int 		NOT NULL,
	DIA_FIN 		int 		NOT NULL,
	DESCUENTO 		decimal(28, 8) 	NOT NULL
)
go


ALTER TABLE ERPADMIN.alFAC_DESC_PRONTO_PAGO
         ADD CONSTRAINT DESCPRONTOPAGO PRIMARY KEY NONCLUSTERED (COD_CIA, COD_CND, CONSECUTIVO)
go
         

CREATE TABLE ERPADMIN.alFAC_DET_CONSIG (
       NUM_LN			INT 		NOT NULL,
       COD_CIA			VARCHAR(10) 	NOT NULL,
       COD_ZON			VARCHAR(4) 	NOT NULL,
       COD_CLT			VARCHAR(20) 	NOT NULL,
       COD_ART			VARCHAR(20) 	NOT NULL,
       CNT_MAX			DECIMAL(28,8) 	NOT NULL,
       CNT_MIN			DECIMAL(28,8) 	NOT NULL,
       MON_PRC_MX		DECIMAL(28,8) 	NOT NULL,
       MON_PRC_MN		DECIMAL(28,8) 	NULL,
       MON_TOT			DECIMAL(28,8) 	NOT NULL,
       NUM_CSG			VARCHAR(20) 	NOT NULL DEFAULT 'CONSIG00000000000000'
)
go

ALTER TABLE ERPADMIN.alFAC_DET_CONSIG
       ADD CONSTRAINT PK_alFAC_DET_CONSIG
       		PRIMARY KEY NONCLUSTERED (COD_ZON, COD_CIA, COD_CLT, NUM_CSG, NUM_LN)
go

CREATE TABLE ERPADMIN.alFAC_DET_DEV (
	NUM_DEV		VARCHAR(50) 	NOT NULL,
	COD_CIA		VARCHAR(10) 	NOT NULL,
	COD_ZON		VARCHAR(4) 	NOT NULL,
	COD_ART		VARCHAR(20) 	NOT NULL,
	IND_DEV		VARCHAR(1) 	NOT NULL,
	MON_TOT		DECIMAL(28,8) 	NOT NULL,
	MON_PRC_MX	DECIMAL(28,8) 	NOT NULL,
	MON_PRC_MN	DECIMAL(28,8)	NOT NULL,
	CNT_MAX		DECIMAL(28,8) 	NOT NULL,
	CNT_MIN		DECIMAL(28,8) 	NOT NULL,
	LST_PRE		INT 		NOT NULL,
	OBS_DEV		VARCHAR(80) 	NULL,
	MON_DSC		DECIMAL(28,8)	NOT NULL,
	POR_DSC_AP	DECIMAL(28,8) 	NOT NULL,
	LOTE		VARCHAR(15) 	NOT NULL DEFAULT 'NULL',
	LOTE_HIST 	VARCHAR(15) 	NOT NULL DEFAULT('ND'),
	ART_BON 	VARCHAR(1) 		NOT NULL DEFAULT '0'
)
go

ALTER TABLE ERPADMIN.ALFAC_DET_DEV 
	ADD CONSTRAINT PK_alFAC_DET_DEV PRIMARY KEY(NUM_DEV,COD_CIA,COD_ZON,COD_ART,IND_DEV,LOTE_HIST,LOTE,ART_BON)
go


CREATE TABLE ERPADMIN.alFAC_DET_HIST_PED (
       NUM_PED              VARCHAR(50) 	NOT NULL,
       COD_ART              VARCHAR(20) 	NOT NULL,
       NUM_LN               int 		NOT NULL,
       COD_CIA              VARCHAR(20) 	NULL,
       EST_BON              VARCHAR(20) 	NULL,
       CANT_PED	            DECIMAL(28,8) 	NULL,
       CANT_FAC 	    DECIMAL(28,8) 	NULL,
       CANT_CNL	            DECIMAL(28,8) 	NULL,
       CANT_BKO	            DECIMAL(28,8) 	NULL,
       MONT_LN		    DECIMAL(28,8) 	NULL,
       EST_LN		    VARCHAR(1) 		NULL,
	   MONT_DESC 		DECIMAL(28,8) NULL,
		PRC_DESC 		DECIMAL(28,8) NULL
)
go

ALTER TABLE ERPADMIN.alFAC_DET_HIST_PED
       ADD CONSTRAINT PK_alFAC_DET_HIST_PED
       	PRIMARY KEY NONCLUSTERED (NUM_PED, COD_ART, NUM_LN)
go

CREATE TABLE ERPADMIN.alFAC_DET_INV (
       COD_ART              VARCHAR(20) NOT NULL,
       COD_ZON              VARCHAR(4) NOT NULL,
       NUM_INV              VARCHAR(20) NOT NULL,
       COD_CIA              VARCHAR(10) NOT NULL,
       CNT_MAX              DECIMAL(28,8) NOT NULL,
       CNT_MIN              DECIMAL(28,8) NOT NULL,
       DOC_PRO              VARCHAR(1) NULL
)
go

ALTER TABLE ERPADMIN.alFAC_DET_INV
	 ADD CONSTRAINT PK_alFAC_DET_INV 
	 	PRIMARY KEY NONCLUSTERED (COD_ART, COD_ZON, NUM_INV, COD_CIA)
go

CREATE TABLE ERPADMIN.alFAC_DET_PED (
	NUM_LN			int 		NOT NULL,
	NUM_PED              	VARCHAR(50) 	NOT NULL,
	COD_CIA              	VARCHAR(10) 	NOT NULL,
	COD_ART              	VARCHAR(20)	NOT NULL,
	ART_BON              	VARCHAR(1) 	NOT NULL,
	TIP_DOC              	VARCHAR(1) 	NULL,
	MON_PRC_MN           	DECIMAL(28,8) 	NULL,
	POR_DSC_AP           	DECIMAL(28,8) 	NOT NULL,
	MON_TOT              	DECIMAL(28,8) 	NOT NULL,
	MON_DSC              	DECIMAL(28,8) 	NOT NULL,
	MON_PRC_MX           	DECIMAL(28,8) 	NOT NULL,
	CNT_MAX              	DECIMAL(28,8) 	NOT NULL,
	CNT_MIN              	DECIMAL(28,8) 	NOT NULL,
	COD_ART_RFR          	VARCHAR(20) 	NULL,
	LST_PRE              	int 		NOT NULL,
	TOPE 			VARCHAR (6) 	NULL
)
go

ALTER TABLE ERPADMIN.alFAC_DET_PED
	 ADD CONSTRAINT PK_alFAC_DET_PED 
	 	PRIMARY KEY NONCLUSTERED (NUM_LN,NUM_PED, COD_CIA, COD_ART, ART_BON)
go


CREATE TABLE ERPADMIN.alFAC_DET_GARANTIA(
	NUM_LIN 	int 		NOT NULL DEFAULT 0,
	NUM_GAR 	varchar(20) 	NOT NULL,
	COD_CIA 	varchar(10) 	NOT NULL,
	COD_ART 	varchar(20) 	NOT NULL,
	MON_TOT 	decimal(28, 8) 	NOT NULL,
	MON_PRC_MX 	decimal(28, 8) 	NOT NULL,
	MON_PRC_MN 	decimal(28, 8) 	NOT NULL,
	CNT_MAX 	decimal(28, 8) 	NOT NULL,
	CNT_MIN 	decimal(28, 8) 	NOT NULL,
	LST_PRE 	int 		NOT NULL)
go


ALTER TABLE ERPADMIN.alFAC_DET_GARANTIA
       ADD   CONSTRAINT PK_DetGarantiaComposite 
				PRIMARY KEY ( NUM_LIN, NUM_GAR, COD_CIA, COD_ART )
go



CREATE TABLE ERPADMIN.alFAC_DET_HIST_FAC (
       NUM_FAC              VARCHAR(50) 	NOT NULL,
       COD_ART              VARCHAR(20) 	NOT NULL,
       NUM_LN               INT 		NOT NULL,
       COD_CIA              VARCHAR(20) 	NULL,
       CANT_FAC 	    DECIMAL(28,8) 	NULL,
       CANT_DEV	            DECIMAL(28,8) 	NULL,
       PRE_UNI	            DECIMAL(28,8) 	NULL,	
       MONT_LN		    DECIMAL(28,8) 	NULL,
       EST_BON		    VARCHAR(1) 		NULL,
       LOTE 		    VARCHAR(15) 	NULL,
	   MONT_DESC DECIMAL(28,8) NULL
)
go

ALTER TABLE ERPADMIN.alFAC_DET_HIST_FAC
       ADD CONSTRAINT PK_alFAC_DET_HIST_FAC 
       PRIMARY KEY NONCLUSTERED(NUM_FAC, COD_ART, NUM_LN)

go

CREATE TABLE ERPADMIN.alFAC_DIR_EMB_CLT (
       COD_CLT              VARCHAR(20) NOT NULL,
       COD_CIA              VARCHAR(10) NOT NULL,
       DIR_EMB              VARCHAR(8) NOT NULL,
       COD_ZON              VARCHAR(4) NOT NULL,
       DETA_EMB             TEXT NULL
)
go

ALTER TABLE ERPADMIN.alFAC_DIR_EMB_CLT
       ADD CONSTRAINT PK_alFAC_DIR_EMB_CLT
       PRIMARY KEY NONCLUSTERED (COD_CLT, COD_CIA, DIR_EMB, COD_ZON)
go

CREATE TABLE ERPADMIN.alFAC_ENC_CONSIG (
       COD_CIA			VARCHAR(10) 	NOT NULL,
       COD_ZON			VARCHAR(4) 	NOT NULL,
       COD_CLT			VARCHAR(20) 	NOT NULL,
       HOR_INI			DATETIME 	NOT NULL,
       HOR_FIN			DATETIME 	NOT NULL,
       FEC_BOLETA		DATETIME 	NOT NULL,
       NUM_ITM			INT		NOT NULL,
       COD_CND			VARCHAR(4) 	NOT NULL,
       COD_PAIS			VARCHAR(4) 	NOT NULL,
       CLASE			VARCHAR(1) 	NOT NULL DEFAULT 'N',
       COD_BOD			VARCHAR(4) 	NOT NULL,
       LST_PRE			INT		NOT NULL,
       OBSERVACIONES		VARCHAR(60) 	NULL,
       DESC1			DECIMAL(28,8) 	NOT NULL,
       DESC2			DECIMAL(28,8) 	NOT NULL,
       MONT_DESC1		DECIMAL(28,8) 	NOT NULL,
       MONT_DESC2		DECIMAL(28,8) 	NOT NULL,
       DESCUENTO_CASCADA	VARCHAR(1) 	NOT NULL DEFAULT 'N',
       MON_IMP_VT		DECIMAL(28,8) 	NOT NULL,
       MON_IMP_CS		DECIMAL(28,8) 	NOT NULL,
       MON_SIV			DECIMAL(28,8) 	NOT NULL,
       DOC_PRO			VARCHAR(1) 	NOT NULL DEFAULT 'N',
       IMPRESO			VARCHAR(1) 	NOT NULL DEFAULT 'N',
       NUM_CSG			VARCHAR(20) 	NOT NULL DEFAULT 'CONSIG00000000000000'       
)
go

ALTER TABLE ERPADMIN.alFAC_ENC_CONSIG
       ADD CONSTRAINT PK_alFAC_ENC_CONSIG  
       PRIMARY KEY NONCLUSTERED (COD_ZON, COD_CIA, COD_CLT, NUM_CSG)
go

CREATE TABLE ERPADMIN.alFAC_ENC_DEV (
	NUM_DEV              	VARCHAR(50) 	NOT NULL,
	COD_CIA              	VARCHAR(10) 	NOT NULL,
	COD_ZON              	VARCHAR(4) 	NOT NULL,
	COD_CLT              	VARCHAR(20) 	NOT NULL,
	HOR_INI              	DATETIME 	NOT NULL,
	HOR_FIN              	DATETIME 	NOT NULL,
	FEC_DEV              	DATETIME	NOT NULL,
	OBS_DEV              	VARCHAR(80) 	NULL,
	NUM_ITM              	int 		NOT NULL,
	LST_PRE		     	int 		NOT NULL,
	EST_DEV              	VARCHAR(1) 	NOT NULL,
	DOC_PRO              	VARCHAR(1) 	NULL,
	MON_SIV              	DECIMAL(28,8) 	NOT NULL,
	MON_DSC              	DECIMAL(28,8) 	NOT NULL,
	POR_DSC_AP           	DECIMAL(28,8) 	NOT NULL,
	MON_IMP_VT           	DECIMAL(28,8) 	NOT NULL,
	MON_IMP_CS           	DECIMAL(28,8) 	NOT NULL,
	COD_BOD              	VARCHAR(4) 	NOT NULL DEFAULT 'ND',
	IMPRESO			VARCHAR(1) 	NOT NULL DEFAULT 'N',
	CONSIGNACION		VARCHAR(1) 	NOT NULL DEFAULT 'N',
	NUM_REF			VARCHAR(50)	NULL,
	AUTOMATICA		VARCHAR(1)	NULL,
	TIPO			VARCHAR(50)	NULL,
	NCF_PREFIJO 		VARCHAR(20) 	NULL,
	NCF 			VARCHAR(40) 	NULL,
	NIVEL_PRECIO 		VARCHAR(12)	NULL,
	MONEDA 			VARCHAR(1)	NULL,
	FORMA_PAGO_DEV 		VARCHAR(1) 	NULL,
	COD_PAIS      		varchar(4) 	null,
	COD_GEO1      		varchar(12) 	null,
	COD_GEO2      		varchar(12) 	null,
	SERIE_RESOLUCION 	VARCHAR(25) 	NULL,
	CONSEC_RESOLUCION 	INT 		NULL,
	TIPO_ANULACION 		VARCHAR(3) 	NULL,
	POR_DESC_AP2 DECIMAL(28,8) NULL,
    MONT_DESC2 DECIMAL(28,8) NULL
)
go

ALTER TABLE ERPADMIN.alFAC_ENC_DEV
	ADD CONSTRAINT PK_alFAC_ENC_DEV 
		PRIMARY KEY NONCLUSTERED (NUM_DEV, COD_CIA, COD_ZON)
go



CREATE TABLE ERPADMIN.alFAC_ENC_GARANTIA(
	COD_CIA 		varchar(10) 	NOT NULL,
	NUM_GAR 		varchar(20) 	NOT NULL,
	NUM_PED 		varchar(20)     NULL,
	COD_CLT 		varchar(20) 	NOT NULL,
	COD_ZON 		varchar(4) 	NOT NULL,
	TIP_DOC 		VARCHAR(4) 	NOT NULL	DEFAULT ('E'),
	FEC_GAR 		datetime 	NOT NULL,
	NUM_ITM 		decimal(28, 8) 	NOT NULL,
	MON_TOT 		decimal(28, 8) 	NOT NULL,
	MONEDA 			varchar(1)	NULL,
	LST_PRE 		int 		NOT NULL,
	OBS_GAR 		varchar(60) 	NULL,
	DOC_PRO 		varchar(1) 	NULL,
	COD_BOD 		varchar(4) 	NOT NULL,
	COD_PAIS		varchar(4) 	NOT NULL,
	IMPRESO 		varchar(1) 	NOT NULL 	DEFAULT 'N',
	NIVEL_PRECIO 		varchar(12)	NULL,
	ASIENTO_CONTABLE 	varchar(50)	NULL,
	COD_CND 		VARCHAR(4) 	NOT NULL 	DEFAULT '0'
)
go

ALTER TABLE ERPADMIN.alFAC_ENC_GARANTIA
       ADD   CONSTRAINT PK_EncGarantiaComposite 
				PRIMARY KEY ( COD_CIA, NUM_GAR, COD_CLT )
go


CREATE TABLE ERPADMIN.alFAC_ENC_HIST_FAC (
	COD_CIA		VARCHAR(10) 	NOT NULL,
	NUM_FAC		VARCHAR(50) 	NOT NULL,
	MON_FAC		DECIMAL(28,8) 	NULL,
	COD_CLT		VARCHAR(20) 	NOT NULL,
	COD_ZON		VARCHAR(4) 	NOT NULL,
	NUM_PED		VARCHAR(50) 	NULL,
	FEC_FAC		DATETIME	NULL,
	ANULAR		VARCHAR(1)	NULL,
	NCF 		VARCHAR(20) 	NULL,
	COD_CND   	VARCHAR(4) 	NULL,
	DESC1 		DECIMAL(28,8) NULL,
	DESC2 		DECIMAL(28,8) NULL,
	MONT_DESC1 	DECIMAL(28,8) NULL,
	MONT_DESC2 	DECIMAL(28,8) NULL
)
go

ALTER TABLE ERPADMIN.alFAC_ENC_HIST_FAC
       ADD CONSTRAINT PK_alFAC_ENC_HIST_FAC 
       		PRIMARY KEY NONCLUSTERED (COD_CIA, NUM_FAC,COD_ZON)
go

CREATE TABLE ERPADMIN.alFAC_ENC_HIST_PED (
       COD_CIA              VARCHAR(10) 	NOT NULL,
       NUM_PED              VARCHAR(50) 	NOT NULL,
       MON_PED              DECIMAL(28,8) 	NULL,
       EST_PED              VARCHAR(20) 	NULL,
       COD_CLT              VARCHAR(20) 	NOT NULL,
       COD_ZON              VARCHAR(4) 		NOT NULL,
       FEC_PED		    	DATETIME		NULL,
	   DESC1 		DECIMAL(28,8) NULL,
	   DESC2 		DECIMAL(28,8) NULL,
	   MONT_DESC1 	DECIMAL(28,8) NULL,
	   MONT_DESC2 	DECIMAL(28,8) NULL
)
go

ALTER TABLE ERPADMIN.alFAC_ENC_HIST_PED
       ADD CONSTRAINT PK_alFAC_ENC_HIST_PED 
       	PRIMARY KEY NONCLUSTERED (COD_CIA, NUM_PED,COD_ZON)
go

CREATE TABLE ERPADMIN.alFAC_ENC_INV (
       COD_CIA              VARCHAR(10) NOT NULL,
       NUM_INV              VARCHAR(20) NOT NULL,
       COD_ZON              VARCHAR(4) 	NOT NULL,
       COD_CLT              VARCHAR(20) NOT NULL,
       HOR_INI              DATETIME 	NULL,
       HOR_FIN              DATETIME 	NULL,
       FEC_INV              DATETIME 	NULL,
       NUM_ITM              int 	NULL,
       DOC_PRO              VARCHAR(1) 	NULL
)
go

ALTER TABLE ERPADMIN.alFAC_ENC_INV
	 ADD CONSTRAINT PK_alFAC_ENC_INV 
	 	PRIMARY KEY NONCLUSTERED (COD_CIA, NUM_INV, COD_ZON, COD_CLT)
go

CREATE TABLE ERPADMIN.alFAC_ENC_PED (
       	COD_CIA             	VARCHAR(10) 	NOT NULL,
       	NUM_PED             	VARCHAR(50) 	NOT NULL,
       	COD_ZON             	VARCHAR(4) 	NOT NULL,
       	COD_CLT             	VARCHAR(20) 	NOT NULL,
       	TIP_DOC             	VARCHAR(1) 	NOT NULL,
       	HOR_FIN             	DATETIME 	NOT NULL,
       	FEC_PED             	DATETIME 	NOT NULL,
       	FEC_DES             	DATETIME 	NOT NULL,
       	HOR_INI             	DATETIME 	NOT NULL,
       	MON_IMP_VT          	DECIMAL(28,8) 	NOT NULL,
       	MON_IMP_CS          	DECIMAL(28,8) 	NOT NULL,
       	MON_CIV             	DECIMAL(28,8) 	NOT NULL,
       	MON_SIV             	DECIMAL(28,8) 	NOT NULL,
       	MON_DSC             	DECIMAL(28,8) 	NOT NULL,
       	NUM_ITM             	int 		NOT NULL,
       	LST_PRE             	int 		NOT NULL,
       	OBS_PED		    	VARCHAR(60) 	NULL,
       	DOC_PRO             	VARCHAR(1) 	NULL,
       	ESTADO              	VARCHAR(1) 	NOT NULL,
       	COD_CND             	VARCHAR(4) 	NOT NULL,
       	COD_BOD             	VARCHAR(4) 	NOT NULL DEFAULT 'ND',
       	COD_PAIS		VARCHAR(4) 	NOT NULL,
       	CLASE		    	VARCHAR(1) 	NOT NULL DEFAULT 'N',
       	DIR_ENT		    	VARCHAR(8) 	NOT NULL DEFAULT 'ND',
       	DESC1		    	DECIMAL(28,8) 	NULL,
       	DESC2		    	DECIMAL(28,8) 	NULL,
       	MONT_DESC1	    	DECIMAL(28,8) 	NULL,
       	MONT_DESC2	    	DECIMAL(28,8) 	NULL,
       	DESCUENTO_CASCADA	VARCHAR(1) 	NOT NULL DEFAULT 'N',
	IMPRESO			VARCHAR(1) 	NOT NULL DEFAULT 'N',
	CONSIGNACION		VARCHAR(1) 	NOT NULL DEFAULT 'N',
	NCF_PREFIJO 		VARCHAR(20) 	NULL,
	FACTURA_UNICA 		VARCHAR (20) 	NULL,
	NCF 			VARCHAR(40) 	NULL,
	NIVEL_PRECIO 		VARCHAR(12)	NULL,
	MONEDA 			VARCHAR(1)	NULL,
	SERIE_RESOLUCION 	VARCHAR(25) 	NULL,
	COD_GEO1      		varchar(12) 	null,
	COD_GEO2      		varchar(12)	null,
	CONSEC_RESOLUCION 	INT 		NULL,
	TIPO_ANULACION 		VARCHAR(3) 	NULL
)
go

ALTER TABLE ERPADMIN.alFAC_ENC_PED
	 ADD CONSTRAINT PK_alFAC_ENC_PED 
	 	PRIMARY KEY NONCLUSTERED (COD_CIA, NUM_PED, COD_ZON, COD_CLT)
go

CREATE TABLE ERPADMIN.alFAC_PAIS (
       COD_PAIS             	VARCHAR(4) 	NOT NULL,
       COD_CIA              	VARCHAR(10)	NOT NULL,
       NOMBRE              	VARCHAR(40) 	NOT NULL,
       ETIQUETA_DIV_GEO1 	varchar(20) 	null,
       ETIQUETA_DIV_GEO2 	varchar(20) 	null
)
go

ALTER TABLE ERPADMIN.alFAC_PAIS ADD
	CONSTRAINT PAIS_PK PRIMARY KEY NONCLUSTERED (COD_PAIS, COD_CIA)
go

CREATE TABLE ERPADMIN.alFAC_RUTA_ORDEN (
       COD_ZON		VARCHAR(4) 	NOT NULL,
       COD_CLT		VARCHAR(20) 	NOT NULL,
       DIA		VARCHAR(1) 	NOT NULL,
       ORDEN		int 		NOT NULL
)
go

ALTER TABLE ERPADMIN.alFAC_RUTA_ORDEN ADD 
	CONSTRAINT PK_alFAC_RUTA_ORDEN 
		PRIMARY KEY NONCLUSTERED (COD_ZON, COD_CLT, DIA)
go

CREATE TABLE ERPADMIN.alFAC_RZN_VIS (
       COD_RZN              VARCHAR(2) 	NOT NULL,
       COD_CIA              VARCHAR(10) 	NOT NULL,
       DES_RZN              VARCHAR(20) 	NOT NULL
)
go

ALTER TABLE ERPADMIN.alFAC_RZN_VIS
	ADD CONSTRAINT PK_alFAC_RZN_VIS 
		PRIMARY KEY NONCLUSTERED (COD_RZN, COD_CIA)
go

CREATE TABLE ERPADMIN.alFAC_TIP_CLT (
       COD_TIP_CL           VARCHAR(8) 	NOT NULL,
       COD_CIA              VARCHAR(10) NOT NULL,
       DES_TIP_CL           VARCHAR(60) NOT NULL
)
go

ALTER TABLE ERPADMIN.alFAC_TIP_CLT
	ADD CONSTRAINT PK_alFAC_TIP_CLT 
		PRIMARY KEY NONCLUSTERED (COD_TIP_CL, COD_CIA)
go

CREATE TABLE ERPADMIN.alSYS_PRM (
       	COD_ZON              	VARCHAR(4) 	NOT NULL,
       	NUM_PED              	VARCHAR(50) 	NOT NULL,
       	NUM_REC              	VARCHAR(50) 	NOT NULL,
       	NUM_DOC              	VARCHAR(10) 	NOT NULL,
       	NUM_DEV              	VARCHAR(50) 	NOT NULL,
       	COD_CIA              	VARCHAR(10) 	NOT NULL,
       	NUM_INV              	VARCHAR(20) 	NOT NULL,
       	NUM_FAC              	VARCHAR(50) 	NOT NULL,
       	NUM_PED_DESC         	VARCHAR(50) 	NOT NULL DEFAULT '0',
       	NOTACREDITO 	    	VARCHAR(20) 	NULL,
	NCF_CONSUMIDOR_F 	VARCHAR(20)	NULL,
	NCF_ORGANIZADO 		VARCHAR(20)	NULL,
	NCF_REGIMEN_ESP 	VARCHAR(20)	NULL,
	NCF_GUBERNAMENTAL 	VARCHAR(20)	NULL,
	NCF_DEVOLUCION 		VARCHAR(20)	NULL,
	NCF_RECIBO 		VARCHAR(20)	NULL,
	NUM_GAR 		VARCHAR(20)	NULL
)
go


ALTER TABLE ERPADMIN.alSYS_PRM
	ADD CONSTRAINT PK_alSYS_PRM PRIMARY KEY NONCLUSTERED  (COD_ZON,COD_CIA)
go		

CREATE TABLE ERPADMIN.ARCHIVO_DETALLE_FR
(
	VERSION 			VARCHAR(11) 	NOT NULL,
	ARCHIVO 			VARCHAR(8) 	NOT NULL,
	TIPO_ARCHIVO 			VARCHAR(1) 	NOT NULL,
	NOMBRE_ARCHIVO 			VARCHAR(256) 	NOT NULL,
	NOMBRE_DESCRIPCION 		VARCHAR(256) 	NULL,
	VERSION_ARCHIVO_DETALLE 	VARCHAR(11) 	NOT NULL,	
	FECHA_ARCHIVO 			DATETIME 	NOT NULL,		
	TIPO_ARCHIVO_DETALLE 		VARCHAR(1) 	NOT NULL,
	ARCHIVOBINARIO 			IMAGE 		NOT NULL
)
go


ALTER TABLE ERPADMIN.ARCHIVO_DETALLE_FR
         ADD CONSTRAINT PKDETALLE_ARCHIVO_FR PRIMARY KEY NONCLUSTERED
        	 (VERSION, ARCHIVO, TIPO_ARCHIVO, NOMBRE_ARCHIVO, VERSION_ARCHIVO_DETALLE )
go



CREATE TABLE ERPADMIN.ARCHIVO_FR
(
	VERSION 	VARCHAR(11) 	NOT NULL,
	ARCHIVO 	VARCHAR(8) 	NOT NULL,	
	TIPO_ARCHIVO 	VARCHAR(1) 	NOT NULL,
	PUBLICADO 	VARCHAR(1) 	NOT NULL DEFAULT 'N',
	DESCRIPCION 	VARCHAR(80) 	NULL
)
go

ALTER TABLE ERPADMIN.ARCHIVO_FR
         ADD CONSTRAINT PKARCHIVO_FR PRIMARY KEY NONCLUSTERED  (VERSION, ARCHIVO, TIPO_ARCHIVO )
go


CREATE TABLE ERPADMIN.ARCHIVO_HANDHELD
(
	HANDHELD 		VARCHAR(4) 	NOT NULL,
	VERSION 		VARCHAR(11) 	NOT NULL,
	ARCHIVO 		VARCHAR(8) 	NOT NULL,	
	TIPO_ARCHIVO 		VARCHAR(1)	NOT NULL,
	ESTADO 			VARCHAR(1) 	DEFAULT('N') NOT NULL,
	FECHA_ACTUALIZACION 	DATETIME 	NULL	
)
go


ALTER TABLE ERPADMIN.ARCHIVO_HANDHELD
         ADD CONSTRAINT PKARCHIVO_HANDHELD PRIMARY KEY NONCLUSTERED
        	 (HANDHELD, ARCHIVO, VERSION, TIPO_ARCHIVO )
go


CREATE TABLE ERPADMIN.ARTICULO (
	GRP_ART      		VARCHAR(3) 	NOT NULL,
	COD_ART      		VARCHAR(20) 	NOT NULL,
	COD_CIA      		VARCHAR(10) 	NOT NULL,       
	UND_EMP      		DECIMAL(28,8) 	NOT NULL,       
	EMP_ALM      		VARCHAR(6) 	NULL,       
	EMP_DET      		VARCHAR(6) 	NULL,       
	COD_BAR      		VARCHAR(20) 	NULL,       
	DES_ART      		VARCHAR(75) 	NOT NULL,       
	COD_FAM      		VARCHAR(12) 	NULL,       
	COD_CLS      		VARCHAR(12) 	NULL,
	IMPUESTO        	VARCHAR(4) 	NOT NULL,
	USA_LOTES		VARCHAR(1) 	NOT NULL DEFAULT 'N',
	COSTO_LOCAL		DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	COSTO_DOLAR		DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	FACTOR_PRECIO 		DECIMAL(28,8)	NOT NULL DEFAULT 0,
	ORDEN_ART 		VARCHAR (5) 	NULL,
	FACTOR_VENTA 		DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	ARTICULO_ENVASE 	varchar(20)	NULL,
	TIPO  			varchar(1)	NULL,
	CODIGO_RETENCION 	varchar(4) 	null,
	RETENCION_VENTA 	varchar(4) 	null,
	RETENCION_COMPRA 	varchar(4) 	null,
	MODELO_RETENCION 	varchar(4) 	null,
	CLASIFICACION3 		VARCHAR(12) 	NULL,
	CLASIFICACION4 		VARCHAR(12) 	NULL,
	CLASIFICACION5 		VARCHAR(12) 	NULL,
	CLASIFICACION6 		VARCHAR(12) 	NULL	
)
go

ALTER TABLE ERPADMIN.ARTICULO ADD 
	CONSTRAINT ARTICULO_PK 
		PRIMARY KEY NONCLUSTERED (GRP_ART,COD_ART,COD_CIA)
go



CREATE TABLE ERPADMIN.ARTICULO_ENSAMBLE
(
	COMPANIA 		VARCHAR(20) 	NOT NULL,
	ARTICULO_PADRE 		VARCHAR(20) 	NOT NULL,
	ARTICULO_HIJO 		VARCHAR(20) 	NOT NULL,
	CANTIDAD 		DECIMAL(28,8) 	DEFAULT 0 NOT NULL 
)
go





CREATE TABLE ERPADMIN.ARTICULO_EXISTENCIA (
	ARTICULO 	VARCHAR(20) 	NOT NULL,
	COMPANIA	VARCHAR(10) 	NOT NULL,
	BODEGA		VARCHAR(4) 		NOT NULL,
	EXISTENCIA	DECIMAL(28,8)	NOT NULL
)
go

ALTER TABLE ERPADMIN.ARTICULO_EXISTENCIA ADD 
	CONSTRAINT ARTICULO_EXISTENCIA_PK 
		PRIMARY KEY NONCLUSTERED (ARTICULO,COMPANIA,BODEGA)
go



CREATE TABLE ERPADMIN.ARTICULO_EXISTENCIA_LOTE
(
	COMPANIA 		VARCHAR(10) 	NOT NULL,
	BODEGA 			VARCHAR(4) 	NOT NULL,
	ARTICULO 		VARCHAR(20) 	NOT NULL,
	LOCALIZACION 		VARCHAR(8) 	NOT NULL,
	LOTE 			VARCHAR(15) 	NOT NULL,	
	FECHA_VENCIMIENTO 	DATETIME 	NOT NULL,	
	EXISTENCIA 		DECIMAL(28, 8) 	NOT NULL,
	TIPO_INGRESO 		VARCHAR(1) 	NOT NULL DEFAULT('P')
)
go

ALTER TABLE ERPADMIN.ARTICULO_EXISTENCIA_LOTE
         ADD CONSTRAINT PKARTICULO_EXISTENCIA_LOTE PRIMARY KEY NONCLUSTERED
        	 (COMPANIA, BODEGA, ARTICULO, LOCALIZACION, LOTE)
go


CREATE TABLE ERPADMIN.ARTICULO_PRECIO (
    ARTICULO		VARCHAR(20) 	NOT NULL,
	COMPANIA		VARCHAR(10) 	NOT NULL,
	NIVEL_PRECIO	VARCHAR(12) 	NOT NULL,
	MONEDA			VARCHAR(1) 		NOT NULL,
	PRECIO			DECIMAL(28,8) 	NOT NULL,
	MARGEN_UTILIDAD	DECIMAL(28,8)	NOT NULL DEFAULT 0,
	VERSION 		INT not NULL default 1,
	VERSION_ARTICULO INT not NULL default 1,
	FECHA_INICIO_VERSION_ARTICULO 	DATETIME NOT NULL DEFAULT GETDATE(),
	FECHA_FINAL_VERSION_ARTICULO 	DATETIME NOT NULL DEFAULT GETDATE()
)
go

ALTER TABLE ERPADMIN.ARTICULO_PRECIO 
	ADD CONSTRAINT ARTICULO_PRECIO_PK 
		PRIMARY KEY (ARTICULO,COMPANIA,NIVEL_PRECIO,MONEDA,VERSION,VERSION_ARTICULO)
go


CREATE TABLE ERPADMIN.ARTICULO_RT (
        COMPANIA        	VARCHAR(10)   	NOT NULL,
        ARTICULO        	VARCHAR(20)   	NOT NULL,
        DESCRIPCION     	VARCHAR(75)   	NOT NULL,
        FACTOR_PRECIO   	DECIMAL(38,8) 	NOT NULL,
        ORDEN_ARTICULO  	VARCHAR (5)   	NULL,
	BODEGA 			VARCHAR(4)   	NULL,
	LOCALIZACION 		VARCHAR(4) 	NULL
)
go

ALTER TABLE ERPADMIN.ARTICULO_RT
         ADD CONSTRAINT XPKARTICULO 
         	PRIMARY KEY NONCLUSTERED (COMPANIA, ARTICULO )
go



CREATE TABLE ERPADMIN.BODEGA_ASOC_RT	(
    BODEGA 				VARCHAR(4)	NOT NULL,
	CODIGO 				VARCHAR(4) 	NOT NULL,
 	COMPANIA 			VARCHAR(10) 	NOT NULL,
 	CODIGO_BODEGA_RETABLECER 	VARCHAR(4)	NULL,
	PAQUETE_INVENTARIO		VARCHAR(4)	NULL,
	CONSECUTIVO_CI			VARCHAR(10)	NULL,
	LOCALIZACION 			VARCHAR(8) 	NULL
)
go

ALTER TABLE ERPADMIN.BODEGA_ASOC_RT
         ADD CONSTRAINT XPKBODEGAASOC PRIMARY KEY NONCLUSTERED
         (BODEGA,CODIGO,COMPANIA)
go

CREATE TABLE ERPADMIN.BODEGA_RT (
        BODEGA        VARCHAR (4) NOT NULL,
        NOMBRE        VARCHAR (40) NOT NULL)
go

ALTER TABLE ERPADMIN.BODEGA_RT
         ADD CONSTRAINT XPKBODEGA PRIMARY KEY NONCLUSTERED
         (BODEGA)
go

CREATE TABLE ERPADMIN.BONIFICACION_CLIART (
	COMPANIA		VARCHAR(10) 	NOT NULL,
	CLIENTE			VARCHAR(20) 	NOT NULL,
	ARTICULO		VARCHAR(20) 	NOT NULL,
	CANT_MIN		int 			NOT NULL,
	CANT_MAX		int 			NOT NULL,
	FECHA_INICIO	DATETIME 		NOT NULL,
	FECHA_FIN		DATETIME 		NOT NULL,
	ARTICULO_BONIF	VARCHAR(20) 	NOT NULL,
	UNIDADES_BONIF	DECIMAL(28,8) 	NOT NULL,
	FACTOR_BONIF	DECIMAL(28,8)	NULL
)
go

ALTER TABLE ERPADMIN.BONIFICACION_CLIART ADD 
	CONSTRAINT BONIFICACION_CLIART_PK 
		PRIMARY KEY NONCLUSTERED
			(COMPANIA,CLIENTE,ARTICULO,CANT_MIN,CANT_MAX,FECHA_INICIO,FECHA_FIN)
go

CREATE TABLE ERPADMIN.BONIFICACION_NIVEL  (
	COMPANIA		VARCHAR(10)	NOT NULL,	
	NIVEL_PRECIO	VARCHAR(12)	NOT NULL,	
	MONEDA			VARCHAR(1)	NOT NULL,	
	ARTICULO		VARCHAR(20)	NOT NULL,	
	CANT_MIN		int			NOT NULL,
	CANT_MAX		int			NOT NULL,	
	FECHA_INICIO	DATETIME	NOT NULL,
	FECHA_FIN		DATETIME	NOT NULL,
	ARTICULO_BONIF	VARCHAR(20)	NOT NULL,
	UNIDADES_BONIF	DECIMAL(28,8)	NOT NULL,
	FACTOR_BONIF	DECIMAL(28,8)	NULL
)
go

ALTER TABLE ERPADMIN.BONIFICACION_NIVEL
	ADD CONSTRAINT PK_BONIFICACION_NIVEL 
		PRIMARY KEY NONCLUSTERED
			(COMPANIA,NIVEL_PRECIO,MONEDA,ARTICULO,CANT_MIN,CANT_MAX,FECHA_INICIO,FECHA_FIN)
go

CREATE TABLE ERPADMIN.CARGA_REALIZADA_RT (
         FECHA            DATETIME      NOT NULL,
         RUTA         	  VARCHAR(4)    NOT NULL,
         COMPANIA	  	  VARCHAR(10)	NOT NULL )
go

ALTER TABLE ERPADMIN.CARGA_REALIZADA_RT
         ADD CONSTRAINT XPKCARGAREALIZADA 
         	PRIMARY KEY NONCLUSTERED (FECHA, RUTA, COMPANIA )
go


CREATE TABLE ERPADMIN.CLASIFICACION_FR(
	COMPANIA 	VARCHAR(10) 	NOT NULL,
	CLASIFICACION 	VARCHAR(12) 	NOT NULL,
	DESCRIPCION 	VARCHAR(40) 	NOT NULL,
	AGRUPACION 	INT 		NOT NULL DEFAULT 1
)
go




ALTER TABLE ERPADMIN.CLASIFICACION_FR ADD 
	CONSTRAINT PK_CLASIF_ARTICULO PRIMARY KEY (COMPANIA,CLASIFICACION)
go
	






CREATE TABLE ERPADMIN.CLIENTE (
       COD_ZON              VARCHAR(4) 		NOT NULL,
       COD_CLT              VARCHAR(20) 	NOT NULL,
       FEC_PLN              DATETIME 		NULL,
       NOM_CLT              VARCHAR(150) 	NOT NULL,
       DIR_CLT              VARCHAR(MAX) 	NOT NULL,
       DESGLOSE		    VARCHAR(1)  	NOT NULL 	DEFAULT 'N'
)
go

ALTER TABLE ERPADMIN.CLIENTE
	ADD CONSTRAINT PK_CLIENTE 
		PRIMARY KEY NONCLUSTERED (COD_ZON,COD_CLT)
go

CREATE TABLE ERPADMIN.CLIENTE_ASOC_RT (
         CLIENTE         	VARCHAR(20)  NOT NULL,
         COMPANIA        	VARCHAR(10)  NOT NULL,
         CODIGO          	VARCHAR(20)  NOT NULL,
         BODEGA_CONSIGNA 	VARCHAR(4)   NOT NULL DEFAULT 'ND',
         LOCALIZACION_CONSIGNA 	VARCHAR(8) 	NULL
)
go

ALTER TABLE ERPADMIN.CLIENTE_ASOC_RT
         ADD CONSTRAINT XPKCLIENTEASOC 
         	PRIMARY KEY NONCLUSTERED (CODIGO, COMPANIA )
go



ALTER TABLE ERPADMIN.CLIENTE_ASOC_RT
         ADD CONSTRAINT XAK1CLIENTE_ASOC_RT 
         	UNIQUE NONCLUSTERED (CLIENTE, COMPANIA )
go


CREATE TABLE ERPADMIN.CLIENTE_CIA (
       COD_CLT              	VARCHAR(20) 	NOT NULL,
       COD_CIA              	VARCHAR(10) 	NOT NULL,
       LST_PRE              	int 		NOT NULL,
       IND_MON              	VARCHAR(1) 	NULL,
       NOM_CTO              	VARCHAR(30) 	NULL,
       NUM_TEL              	VARCHAR(50)	NULL,
       COD_CND              	VARCHAR(4) 	NULL,
       DIA_CRE              	int 		NOT NULL,
       SAL_CRE              	DECIMAL(28,8) 	NOT NULL,
       LIM_CRE              	DECIMAL(28,8) 	NOT NULL,
       POR_EXC_VT           	DECIMAL(28,8) 	NULL,
       POR_EXC_CS           	DECIMAL(28,8) 	NULL,
       COD_PAIS             	VARCHAR(4) 	NOT NULL,
       COD_TIP_CL           	VARCHAR(8) 	NULL,
       DIR_EMB_DEFAULT	    	VARCHAR(8) 	NOT NULL,
       DESCUENTO            	DECIMAL(28,8) 	NOT NULL,
       BODEGA_CONSIGNA 		VARCHAR(4) 	NOT NULL DEFAULT 'ND',
       MULT_MON 		VARCHAR(1) 	NULL,
       ACEPTA_FRACCIONES 	VARCHAR(1) 	NOT NULL DEFAULT 'N',
       TIPO_CONTRIBUYENTE 	VARCHAR(1) 	NULL,
       CONTRIBUYENTE 		VARCHAR(20) 	NULL,
       DIVISION_GEOGRAFICA1 	varchar(12) 	null,
       DIVISION_GEOGRAFICA2 	varchar(12) 	null,
       REGIMEN_TRIB 		varchar(12) 	null,
	     LOCALIZACION_CONSIGNA    VARCHAR(8) NULL,
       CODIGO VARCHAR(20) NULL
)
go

ALTER TABLE ERPADMIN.CLIENTE_CIA
	ADD CONSTRAINT PK_CLIENTE_CIA 
		PRIMARY KEY NONCLUSTERED(COD_CLT, COD_CIA)
go



CREATE TABLE ERPADMIN.CLIENTE_RETENCION(
	COD_CIA 		varchar(10) 	NOT NULL,
	CLIENTE 		varchar(20) 	NOT NULL,
	CODIGO_RETENCION 	varchar(4) 	NOT NULL
)
go

ALTER TABLE ERPADMIN.CLIENTE_RETENCION 
	ADD  CONSTRAINT XPKCLIENTE_RETENCI 
		PRIMARY KEY CLUSTERED (COD_CIA,CLIENTE,CODIGO_RETENCION)
go



CREATE TABLE ERPADMIN.CLIENTE_RT (
        CLIENTE        			VARCHAR(20)  	NOT NULL,
        NOMBRE         			VARCHAR(150)  	NOT NULL,
    	LATITUD 			DECIMAL (28,8) 	NULL,
    	LONGITUD 			DECIMAL (28,8) 	NULL,
    	ALTITUD 			DECIMAL (28,8) 	NULL,
    	FECHA_ACTUALIZACION_UBICACION 	DATETIME 	NULL
)
go

ALTER TABLE ERPADMIN.CLIENTE_RT
         ADD CONSTRAINT XPKCLIENTE 
         	PRIMARY KEY NONCLUSTERED (CLIENTE )
go



CREATE TABLE ERPADMIN.CLIENTE_UBICACION(
	RUTA 		VARCHAR(20) 	NOT NULL,
	CLIENTE 	VARCHAR(20) 	NOT NULL,
	LATITUD 	DECIMAL (28,8) 	NULL,
	LONGITUD 	DECIMAL (28,8) 	NULL,
	ALTITUD 	DECIMAL (28,8) 	NULL
)
go


ALTER TABLE ERPADMIN.CLIENTE_UBICACION  ADD CONSTRAINT CLIUBICPK PRIMARY KEY  (RUTA, CLIENTE)
go
         
         

CREATE TABLE ERPADMIN.CLIENTE_UBICACION_LOG(
	RUTA 		VARCHAR(20) 	NOT NULL,
	CLIENTE 	VARCHAR(20) 	NOT NULL,
	FECHA 		DATETIME 	NOT NULL,
	ESTADO 		VARCHAR(1) 	NULL,
	LATITUD 	DECIMAL(28,8) 	NULL,
	LONGITUD 	DECIMAL(28,8) 	NULL,
	ALTITUD 	DECIMAL(28,8) 	NULL,
	ERROR   	VARCHAR(200) 	NULL
)
go


ALTER TABLE ERPADMIN.CLIENTE_UBICACION_LOG ADD CONSTRAINT CLIUBICLOGPK PRIMARY KEY NONCLUSTERED (RUTA, CLIENTE, FECHA)
go




CREATE TABLE ERPADMIN.CODCLT_ALDO_RT (
         COD_CLT_HH      VARCHAR(20)         NOT NULL,
         COMPANIA        VARCHAR(10)         NOT NULL,
         COD_CLT         VARCHAR(20)         NOT NULL 
)
go

ALTER TABLE ERPADMIN.CODCLT_ALDO_RT
         ADD CONSTRAINT XPKCODCLTALDORT 
         	PRIMARY KEY NONCLUSTERED (COD_CLT_HH, COMPANIA, COD_CLT )
go

CREATE TABLE ERPADMIN.COMPANIA (
	COMPANIA			VARCHAR(10) 	NOT NULL,
	NOMBRE				VARCHAR (100) 	NOT NULL,
	USA_LOTES			VARCHAR (1) 	NOT NULL,
	VISTA_CLIETE			VARCHAR (4000) 	NULL,
	VISTA_ARTICULO			VARCHAR (4000) 	NULL,
	VISTA_AGENTE			VARCHAR (4000) 	NULL,
	VISTA_CLASIFICACION 		VARCHAR (4000) 	NULL,
	VISTA_LOTE			VARCHAR (4000) 	NULL,
	VISTA_LOCALIZACION		VARCHAR (4000) 	NULL,
	VISTA_BODEGAS			VARCHAR (4000) 	NULL,
	VISTA_BODEGAS_CONSIG 		VARCHAR (4000) 	NULL,
	VISTA_COBRADOR			VARCHAR (4000) 	NULL,
	VISTA_VENDEDOR			VARCHAR (4000) 	NULL,
	VISTA_PAQUETE_INVENTARIO 	VARCHAR(4000)	NULL,
	VISTA_CONSECUTIVO_CI		VARCHAR(4000)	NULL,
	VISTA_NCF_CONSECUTIVO		VARCHAR(4000)	NULL,
	NCF_DEVOLUCION			VARCHAR(20)	NULL,
	VISTA_PEDIDOS_FA 		VARCHAR(4000) 	NULL,
	CODIGO_CONSECUTIVO_FA 		VARCHAR(10) 	NULL,
	VISTA_CONSECUTIVO_FA 		VARCHAR(4000) 	NULL,
	COND_PAGO_DEV 			VARCHAR(4)	NULL,
	SUBTIPO_RECIBO 			INT		NULL,
	SUBTIPO_NOTACREDITO 		INT		NULL,
	SUBTIPO_NOTADEBITO 		INT		NULL,
	CONSECUTIVO_CONSIGNACION 	VARCHAR(10)	NULL,
	VISTA_RESOLUCION 		VARCHAR(MAX) 	NULL,
	SUBTIPO_COMODATO 		INT 		NOT NULL DEFAULT 0
)
go

ALTER TABLE ERPADMIN.COMPANIA
         ADD CONSTRAINT XPKCOMPANIA 
         	PRIMARY KEY NONCLUSTERED (COMPANIA )
go

CREATE TABLE ERPADMIN.COMPANIA_DESCRIPCION (
       COD_CIA              		VARCHAR(10) 	NOT NULL,
       NOM_CIA              		VARCHAR(50) 	NOT NULL,
       DI1_CIA              		VARCHAR(30) 	NULL,
       DI2_CIA              		VARCHAR(30) 	NULL,
       TEL_CIA              		VARCHAR(20) 	NULL,
       SLG_CIA              		VARCHAR(30) 	NULL,
       NIT_CIA              		VARCHAR(20) 	NULL,
       IMP1_AFECTA_DESCTO   		VARCHAR(1) 	NOT NULL,
       COND_PAGO_CONTAD     		VARCHAR(4) 	NOT NULL,
       CAMBIODOLAR          		DECIMAL(28,8)	NOT NULL,
       DESCUENTO_CASCADA    		VARCHAR(1) 	NOT NULL,
       USA_NCF 				VARCHAR(1) 	NULL,
       COND_PAGO_DEV 			VARCHAR(4)	NULL,
       MODO_DESC_MULT 			VARCHAR(1)	NULL,
       PAIS 				varchar(20) 	null,
       RETENCIONES 			varchar(1)	not null default 'N',
       UTILIZA_REDONDEO VARCHAR(1)  NOT NULL DEFAULT 'S'
)
go

ALTER TABLE ERPADMIN.COMPANIA_DESCRIPCION ADD 
	CONSTRAINT COMPANIA_PK 
		PRIMARY KEY NONCLUSTERED (COD_CIA)
go



CREATE TABLE ERPADMIN.CONFIG_HH
(
	HANDHELD 	VARCHAR(4) 	NOT NULL,
	CONSTANTE 	VARCHAR(50) 	NOT NULL,
	VALOR 		VARCHAR(50) 	NULL
) 
go


ALTER TABLE ERPADMIN.CONFIG_HH  
      ADD CONSTRAINT PKCONFIG_HH PRIMARY KEY NONCLUSTERED (HANDHELD, CONSTANTE)
go


CREATE TABLE ERPADMIN.CONTROL_VISITAS_RT (
         RUTA         VARCHAR(4)       NOT NULL,
         COMPANIA     VARCHAR(10)      NOT NULL,
         FECHA_INICIO DATETIME         NOT NULL,
         FECHA_FIN    DATETIME         NOT NULL )
go

ALTER TABLE ERPADMIN.CONTROL_VISITAS_RT
         ADD CONSTRAINT XPKCTRLVISITASRT PRIMARY KEY NONCLUSTERED
         (RUTA, COMPANIA, FECHA_INICIO )
go





CREATE TABLE ERPADMIN.DES_BON_PAQUETE(
	COMPANIA 		VARCHAR(10) 	NOT NULL, 
	PAQUETE 		VARCHAR(20) 	NOT NULL, 
	DESCRIPCION 		VARCHAR(40) 	NOT NULL, 
	ACTIVO 			VARCHAR(1)	NOT NULL, 
	FECHA_DESDE 		DATETIME 	NOT NULL, 
	FECHA_HASTA 		DATETIME 	NOT NULL, 
	PRIORIDAD 		INTEGER		NULL, 
	DIAS 			TEXT		NULL,
	APLICA_TODA_TIENDA 	VARCHAR(1) 	NOT NULL DEFAULT ('S'),
	APLICA_TODA_RUTA 	VARCHAR(1) 	NOT NULL DEFAULT ('S')
)
go

ALTER TABLE ERPADMIN.DES_BON_PAQUETE ADD CONSTRAINT PK_PAQUETE PRIMARY KEY (COMPANIA, PAQUETE)
go


CREATE TABLE ERPADMIN.DES_BON_PAQUETE_TIENDA (
	COMPANIA 		VARCHAR(10) 	NOT NULL, 
	PAQUETE 		VARCHAR(20) 	NOT NULL,
	TIENDA			VARCHAR(6)	NOT NULL
)
go

ALTER TABLE ERPADMIN.DES_BON_PAQUETE_TIENDA ADD CONSTRAINT DESBONPAQUETETIENDAPK  PRIMARY KEY (TIENDA, PAQUETE, COMPANIA )
go



CREATE TABLE ERPADMIN.DES_BON_REGLA(
	COMPANIA 			VARCHAR(10) 	NOT NULL,
	REGLA 				VARCHAR(20) 	NOT NULL,
	DESCRIPCION 			VARCHAR(40) 	NOT NULL,
	TIPO 				VARCHAR(1) 	NOT NULL,
	ACTIVA 				VARCHAR(1) 	NOT NULL,
	FILTRO_CLIENTE 			TEXT		NULL,
	VALIDAR_CANTIDAD 		VARCHAR(10) 	NOT NULL,
	CANTIDAD_MINIMA 		DECIMAL(28,8)	NULL,
	CANTIDAD_MAXIMA 		DECIMAL(28,8)	NULL,
	FILTRO_ARTICULO 		TEXT		NULL,
	TIPO_DESCUENTO 			VARCHAR(1) 	NOT NULL,
	TIPO_VALOR 			VARCHAR(1) 	NOT NULL,
	VALOR 				DECIMAL(28,8) 	NULL,
	TIPO_BONIFICACION 		VARCHAR(1) 	NOT NULL,
	UTILIZAR_ARTICULO_LINEA 	VARCHAR(1) 	NOT NULL,
	FILTRO_ARTICULO_BONIFICACION 	TEXT		NULL,
	PRIORIDAD			INTEGER 	NULL,
	MONTO_MINIMO 			DECIMAL(28,8)	NOT NULL DEFAULT (0),
	CATEGORIA_MEMBRESIA 		VARCHAR(8) 	NULL,
	FORMA_PAGO 			VARCHAR(4) 	NULL,
	DETALLE_FORMA_PAGO 		VARCHAR(20) 	NULL,
	MINIMO_PAGO 			DECIMAL(28,8)	NULL,
	REQUIERE_AUTORIZACION 		VARCHAR(1) 	NOT NULL DEFAULT ('N'),
	CANTIDAD_MIN_DETALLE 		DECIMAL(28,8)	NULL,
	CANTIDAD_MAX_DETALLE 		DECIMAL(28,8)	NULL,
	APLICACION_GRUPOS 		VARCHAR(1) 	NOT NULL,
	CANTIDAD_ALMACEN_COMPRA 	DECIMAL(28,8) 	NULL,
	CANTIDAD_ALMACEN_DESCONTAR 	DECIMAL(28,8) 	NULL,
	CANTIDAD_DETALLE_COMPRA 	DECIMAL(28,8) 	NULL,
	CANTIDAD_DETALLE_DESCONTAR 	DECIMAL(28,8) 	NULL,
	APLICA_ARTICULO_MENOR_PRECIO 	VARCHAR(1) 	NOT NULL DEFAULT ('N'),
	CANTIDAD_LIMITE DECIMAL(28,8) NOT NULL DEFAULT (0)
)
go

ALTER TABLE ERPADMIN.DES_BON_REGLA ADD CONSTRAINT PK_REGLA PRIMARY KEY (COMPANIA, REGLA)
go



CREATE TABLE ERPADMIN.DES_BON_PAQUETE_REGLA(
	COMPANIA 		VARCHAR(10) 	NOT NULL, 
	PAQUETE 		VARCHAR(20) 	NOT NULL,
	REGLA 			VARCHAR(20) 	NOT NULL
)
go


ALTER TABLE ERPADMIN.DES_BON_PAQUETE_REGLA ADD CONSTRAINT PK_PAQUETE_REGLA
		PRIMARY KEY (COMPANIA, PAQUETE, REGLA)
go


CREATE TABLE ERPADMIN.DES_BON_PAQUETE_RUTA (
	COMPANIA 		VARCHAR(10) 	NOT NULL, 
	PAQUETE 		VARCHAR(20) 	NOT NULL,
	RUTA        		VARCHAR(4) 	NOT NULL
)
go

ALTER TABLE ERPADMIN.DES_BON_PAQUETE_RUTA  
	ADD CONSTRAINT DESBONPAQUETERUTAPK PRIMARY KEY (RUTA, PAQUETE, COMPANIA )
go




CREATE TABLE ERPADMIN.DES_BON_ESCALA_BONIFICACION(
	COMPANIA 			VARCHAR(10) 	NOT NULL,		   
	ESCALA 				INTEGER		NOT NULL,
	REGLA 				VARCHAR(20) 	NOT NULL,
	ARTICULO 			VARCHAR(20)	NULL,
	CANTIDAD_MINIMA 		DECIMAL(28,8) 	NOT NULL,
	CANTIDAD_MAXIMA 		DECIMAL(28,8) 	NOT NULL,
	FACTOR 				DECIMAL(28,8) 	NOT NULL,
	CANTIDAD_INICIAL 		DECIMAL(28,8) 	NOT NULL,
	CANTIDAD_PEDIDA 		DECIMAL(28,8) 	NOT NULL,
	UNIDAD_ALMACEN 			DECIMAL(28,8) 	NULL,
	UNIDAD_DETALLE 			DECIMAL(28,8) 	NULL,
	CANT_MINIMA_DET 		DECIMAL(28,8)	NOT NULL 	DEFAULT 0,
	CANT_MAXIMA_DET 		DECIMAL(28,8)	NOT NULL 	DEFAULT 0,
	FACTOR_DET 			DECIMAL(28,8) 	NOT NULL 	DEFAULT 0,
	CANTIDAD_INICIAL_DET 		DECIMAL(28,8) 	NOT NULL 	DEFAULT 0,
	CANTIDAD_INICIAL_CONSOL 	DECIMAL(28,8) 	NOT NULL 	DEFAULT 0
)
go

ALTER TABLE ERPADMIN.DES_BON_ESCALA_BONIFICACION ADD CONSTRAINT PK_ESCALA_BONIFICACION
		PRIMARY KEY (COMPANIA, ESCALA, REGLA)
go
		
CREATE TABLE ERPADMIN.DES_BON_ESPECIFICACION_GRUPO(
	COMPANIA varchar(10) NOT NULL,
	ESCALA int NOT NULL,
	REGLA varchar(20) NOT NULL,
	ARTICULO varchar(20) NULL,
	CANTIDAD_MINIMA decimal(28, 8) NOT NULL,
	CANTIDAD_MAXIMA decimal(28, 8) NOT NULL
)

go

ALTER TABLE ERPADMIN.DES_BON_ESPECIFICACION_GRUPO 
	ADD CONSTRAINT PK_ESPECIFICACION_GRUPO 
		PRIMARY KEY (COMPANIA ASC, ESCALA ASC, REGLA ASC)
		
go

CREATE TABLE ERPADMIN.DES_BON_ARTICULO (
	COMPANIA 		VARCHAR(10)	NULL, 
	GRUPO_ARTICULO 		VARCHAR(3)	NULL,	 
	ARTICULO 		VARCHAR(20) 	NOT NULL, 
	DESCRIPCION 		VARCHAR(254)	NOT NULL, 
	CLASIFICACION_1 	VARCHAR(12) 	NULL, 
	CLASIFICACION_2 	VARCHAR(12) 	NULL, 
	CLASIFICACION_3 	VARCHAR(12) 	NULL, 
	CLASIFICACION_4 	VARCHAR(12) 	NULL, 
	CLASIFICACION_5 	VARCHAR(12) 	NULL, 
	CLASIFICACION_6 	VARCHAR(12) 	NULL, 
	TIPO 			VARCHAR(1) 	NOT NULL, 
	ORIGEN_CORP 		VARCHAR(1) 	NOT NULL, 
	PESO_NETO 		DECIMAL(28,10) 	NOT NULL, 
	PESO_BRUTO 		DECIMAL(28,10) 	NOT NULL, 
	VOLUMEN 		DECIMAL(28,10) 	NOT NULL, 
	BULTOS 			smallint 	NOT NULL, 
	IMPUESTO 		VARCHAR(4) 	NOT NULL, 
	FACTOR_EMPAQUE 		DECIMAL(28,10) 	NOT NULL, 
	FACTOR_VENTA 		DECIMAL(28,10) 	NOT NULL, 
	CLASE_ABC 		VARCHAR(1) 	NOT NULL, 
	CODIGO_BARRAS_VENT 	VARCHAR(20) 	NULL, 
	CODIGO_BARRAS_INVT 	VARCHAR(20) 	NULL, 
	ACTIVO 			VARCHAR(1) 	NOT NULL, 
	USA_LOTES 		VARCHAR(1) 	NOT NULL, 
	PROVEEDOR 		VARCHAR(20) 	NULL, 
	ARTICULO_DEL_PROV 	VARCHAR(20) 	NULL, 
	USA_NUMEROS_SERIE 	VARCHAR(1) 	NOT NULL, 
	UNIDAD_ALMACEN 		VARCHAR(6) 	NOT NULL, 
	UNIDAD_EMPAQUE 		VARCHAR(6) 	NOT NULL, 
	UNIDAD_VENTA 		VARCHAR(6) 	NOT NULL, 
	PERECEDERO 		VARCHAR(1) 	NOT NULL		    
)
go




CREATE TABLE ERPADMIN.DES_BON_CLIENTE (
	COD_ZON 		VARCHAR(4) 	NOT NULL, 
	COD_CLI 		VARCHAR(20) 	NOT NULL, 
	CLIENTE 		VARCHAR(20) 	NOT NULL, 
	NOMBRE 			VARCHAR(150) 	NOT NULL, 
	DETALLE_DIRECCION 	int 		NULL, 
	ALIAS 			VARCHAR(80) 	NULL, 
	CONTACTO 		VARCHAR(30) 	NOT NULL, 
	DIR_EMB_DEFAULT 	VARCHAR(8) 	NULL, 
	FECHA_INGRESO 		DATETIME 	NOT NULL, 
	MULTIMONEDA 		VARCHAR(1) 	NOT NULL, 
	MONEDA 			VARCHAR(4) 	NOT NULL, 
	SALDO 			DECIMAL(28,10) 	NOT NULL, 
	SALDO_LOCAL 		DECIMAL(28,10) 	NOT NULL, 
	SALDO_DOLAR 		DECIMAL(28,10) 	NOT NULL, 
	SALDO_CREDITO 		DECIMAL(28,10) 	NOT NULL, 
	LIMITE_CREDITO 		DECIMAL(28,10) 	NULL,	
	EXCEDER_LIMITE 		VARCHAR(1) 	NOT NULL, 
	CONDICION_PAGO 		VARCHAR(4) 	NOT NULL, 
	NIVEL_PRECIO 		VARCHAR(12) 	NOT NULL, 
	DESCUENTO 		DECIMAL(28,10) 	NOT NULL, 
	MONEDA_NIVEL 		VARCHAR(1) 	NOT NULL, 
	PAIS 			VARCHAR(4) 	NOT NULL, 
	ZONA 			VARCHAR(4) 	NOT NULL, 
	RUTA 			VARCHAR(4) 	NOT NULL, 
	VENDEDOR 		VARCHAR(4) 	NULL, 
	COBRADOR 		VARCHAR(4) 	NOT NULL, 
	ACTIVO 			VARCHAR(1) 	NOT NULL, 
	EXENTO_IMPUESTOS 	VARCHAR(1) 	NOT NULL, 
	CATEGORIA_CLIENTE 	VARCHAR(8) 	NOT NULL, 
	CLASE_ABC 		VARCHAR(1) 	NULL, 
	E_MAIL 			VARCHAR(249) 	NULL, 
	ES_CORPORACION 		VARCHAR(1) 	NOT NULL, 
	RUBRO1_CLIENTE 		VARCHAR(40) 	NULL, 
	RUBRO2_CLIENTE 		VARCHAR(40) 	NULL, 
	RUBRO3_CLIENTE 		VARCHAR(40) 	NULL, 
	RUBRO1_CLI 		VARCHAR(50) 	NULL, 
	RUBRO2_CLI 		VARCHAR(50) 	NULL, 
	RUBRO3_CLI 		VARCHAR(50) 	NULL, 
	RUBRO4_CLI 		VARCHAR(50) 	NULL, 
	RUBRO5_CLI 		VARCHAR(50) 	NULL, 
	RUBRO4_CLIENTE 		VARCHAR(40) 	NULL, 
	RUBRO5_CLIENTE 		VARCHAR(40) 	NULL, 
	RUBRO6_CLIENTE 		VARCHAR(40) 	NULL, 
	RUBRO7_CLIENTE 		VARCHAR(40) 	NULL, 
	RUBRO8_CLIENTE 		VARCHAR(40) 	NULL, 
	RUBRO9_CLIENTE 		VARCHAR(40) 	NULL, 
	RUBRO10_CLIENTE 	VARCHAR(40) 	NULL, 
	GLN 			VARCHAR(13) 	NULL, 
	UBICACION 		VARCHAR(10) 	NULL, 
	LOCAL 			VARCHAR(1) 	NOT NULL, 
	RUBRO11_CLIENTE 	VARCHAR(40) 	NULL, 
	RUBRO12_CLIENTE 	VARCHAR(40) 	NULL, 
	RUBRO13_CLIENTE 	VARCHAR(40) 	NULL, 
	RUBRO14_CLIENTE 	VARCHAR(40) 	NULL, 
	RUBRO15_CLIENTE 	VARCHAR(40) 	NULL, 
	RUBRO16_CLIENTE 	VARCHAR(40) 	NULL, 
	RUBRO17_CLIENTE 	VARCHAR(40) 	NULL, 
	RUBRO18_CLIENTE 	VARCHAR(40) 	NULL, 
	RUBRO19_CLIENTE 	VARCHAR(40) 	NULL, 
	RUBRO20_CLIENTE 	VARCHAR(40) 	NULL, 
	ACEPTA_DOC_ELECTRONICO 	VARCHAR(1) 	NOT NULL, 
	CODIGO_IMPUESTO 	VARCHAR(4) 	NULL, 
	MOROSO 			VARCHAR(1) 	NOT NULL,
	COMPANIA 		VARCHAR(10) 	NOT NULL
)
go




CREATE TABLE ERPADMIN.DESCUENTO_CLAS (
	COMPANIA	VARCHAR(10) 	NOT NULL,
	CLIENTE		VARCHAR(20) 	NOT NULL,
	CLASIFICACION1	VARCHAR(12) 	NOT NULL,
	CLASIFICACION2	VARCHAR(12) 	NOT NULL,
	CLASIFICACION3	VARCHAR(12) 	NOT NULL,
	CANT_MIN	int 		NOT NULL,
	CANT_MAX	int 		NOT NULL,
	FECHA_INICIO	DATETIME 	NOT NULL,
	FECHA_FIN 	DATETIME 	NOT NULL,
	TIPO		VARCHAR(1) 	NOT NULL,
	MONTO		DECIMAL(28,8)	NOT NULL
)
go

ALTER TABLE ERPADMIN.DESCUENTO_CLAS ADD 
	CONSTRAINT DESCUENTO_CLAS_PK PRIMARY KEY NONCLUSTERED
	(COMPANIA,CLIENTE,CLASIFICACION1,CLASIFICACION2,
	CLASIFICACION3,CANT_MIN,CANT_MAX,FECHA_INICIO,FECHA_FIN)
go

ALTER TABLE ERPADMIN.DESCUENTO_CLAS ADD 
	CONSTRAINT DESCUENTO_CLASTIPO_CK CHECK (TIPO IN ('P','F'))
go

CREATE TABLE ERPADMIN.DESCUENTO_CLIART (
	COMPANIA	VARCHAR(10) 	NOT NULL,
	ARTICULO	VARCHAR(20) 	NOT NULL,
	CLIENTE		VARCHAR(20) 	NOT NULL,
	CANT_MIN	int 			NOT NULL,
	CANT_MAX	int 			NOT NULL,
	FECHA_INICIO	DATETIME 	NOT NULL,
	FECHA_FIN	DATETIME 		NOT NULL,
	TIPO		VARCHAR(1) 		NOT NULL,
	MONTO		DECIMAL(28,8)	NOT NULL
)
go

ALTER TABLE ERPADMIN.DESCUENTO_CLIART ADD 
	CONSTRAINT DESCUENTO_CLIART_PK PRIMARY KEY NONCLUSTERED
	(COMPANIA,ARTICULO,CLIENTE,CANT_MIN,CANT_MAX,FECHA_INICIO,FECHA_FIN)
go

ALTER TABLE ERPADMIN.DESCUENTO_CLIART ADD 
	CONSTRAINT DESCUENTO_CLIARTTIPO_CK CHECK (TIPO IN ('P','F'))
go


CREATE TABLE ERPADMIN.DESCUENTO_NIVEL (
	COMPANIA 		VARCHAR(10) NOT NULL,
	NIVEL_PRECIO 	VARCHAR(12) NOT NULL,
	MONEDA			VARCHAR(1) 	NOT NULL,
	ARTICULO		VARCHAR(20) NOT NULL,
	CANT_MIN		int 		NOT NULL,
	CANT_MAX		int 		NOT NULL,	
	FECHA_INICIO		Datetime 	NOT NULL,
	FECHA_FIN		Datetime 	NOT NULL,
	PORC_DESC		DECIMAL(28,8)	NOT NULL
)
go

ALTER TABLE ERPADMIN.DESCUENTO_NIVEL
	ADD CONSTRAINT PK_DESCUENTO_NIVEL 
		PRIMARY KEY NONCLUSTERED 
			(COMPANIA,NIVEL_PRECIO,MONEDA,ARTICULO,CANT_MIN,CANT_MAX,FECHA_INICIO,FECHA_FIN)
go


CREATE TABLE ERPADMIN.DET_MOD_RETENCION(
	CODIGO_RETENCION 	varchar(4) 	NOT NULL,
	MODELO_RETENCION 	varchar(4) 	NOT NULL,
	COD_CIA 		varchar(10) 	NOT NULL,
	APLICA 			varchar(1) 	NOT NULL DEFAULT ('A'))
go

ALTER TABLE ERPADMIN.DET_MOD_RETENCION 
	ADD CONSTRAINT  DET_MOD_RETENCION_PKCOMPOSITE 
		PRIMARY KEY (CODIGO_RETENCION,MODELO_RETENCION,COD_CIA)
go



CREATE TABLE ERPADMIN.DIVISION_GEOGRAFICA1(
	PAIS 			varchar(4) 	NOT NULL,
	COMPANIA 		varchar(10) 	NOT NULL,
	DIVISION_GEOGRAFICA1 	varchar(12) 	NOT NULL,
	NOMBRE 			varchar(40) 	NOT NULL)
go

	
ALTER TABLE ERPADMIN.DIVISION_GEOGRAFICA1 
	ADD CONSTRAINT PK_DIVISION_GEOGRAFICA1 
		PRIMARY KEY (PAIS,COMPANIA,DIVISION_GEOGRAFICA1)
go



CREATE TABLE ERPADMIN.DIVISION_GEOGRAFICA2(
	PAIS 			varchar(4) 	NOT NULL,
	COMPANIA 		varchar(10) 	NOT NULL,
	DIVISION_GEOGRAFICA1 	varchar(12) 	NOT NULL,
	DIVISION_GEOGRAFICA2 	varchar(12) 	NOT NULL,
	NOMBRE 			varchar(40) 	NOT NULL)
go

	
ALTER TABLE ERPADMIN.DIVISION_GEOGRAFICA2 
	ADD CONSTRAINT PK_DIVISION_GEOGRAFICA2 
		PRIMARY KEY (PAIS,COMPANIA,DIVISION_GEOGRAFICA1,DIVISION_GEOGRAFICA2)
go





CREATE TABLE ERPADMIN.DOC_FR_RETENCION
(
       DOCUMENTO                VARCHAR(20)       NOT NULL,
       COD_CIA			VARCHAR(10)	  NOT NULL,
       TIPO                     VARCHAR(1)        NOT NULL DEFAULT('F'),
       COD_ZON                  VARCHAR(4)        NOT NULL,
       CODIGO_RETENCION         VARCHAR(4)        NOT NULL,
       AUTORETENEDORA           VARCHAR(1)        NOT NULL DEFAULT('N'),
       MONTO                    DECIMAL(28,8)     NOT NULL,       
       BASE                     DECIMAL(28,8)     NOT NULL,       
       DOC_REFERENCIA           VARCHAR(50)       NOT NULL,
       DOC_CXC_RETENCION        VARCHAR(50)       NULL,
       TIPO_DOC_RETENCION       VARCHAR(3)        NULL,
       DOC_PRO			VARCHAR(1)	  NULL	
)
go

ALTER TABLE ERPADMIN.DOC_FR_RETENCION 
      ADD CONSTRAINT XPKDOC_FR_RETENCION 
            PRIMARY KEY (DOCUMENTO,COD_CIA, TIPO, COD_ZON, CODIGO_RETENCION)
go




CREATE TABLE ERPADMIN.EFECT_VISITA_RT (
         EFECT_VISITA     VARCHAR(2)  NOT NULL,
         DESCRIPCION      VARCHAR(20) NOT NULL )
go

ALTER TABLE ERPADMIN.EFECT_VISITA_RT
         ADD CONSTRAINT XPKRAZONEFE 
         	PRIMARY KEY NONCLUSTERED (EFECT_VISITA )
go


CREATE TABLE ERPADMIN.EXCEP_CIUDAD(
	COD_CIA 		VARCHAR(10) 	NOT NULL,	
	PAIS 			VARCHAR(4) 	NOT NULL,
	DIVISION_GEOGRAFICA1 	VARCHAR(12) 	NOT NULL,
	DIVISION_GEOGRAFICA2 	VARCHAR(12) 	NOT NULL,
	CODIGO_RETENCION 	VARCHAR(4) 	NOT NULL,
	PORCENTAJE 		DECIMAL(28, 8) 	NOT NULL,
	CENTRO_COSTO 		VARCHAR(25) 	NULL,
	CUENTA_CONTABLE 	VARCHAR(25) 	NULL)
go

ALTER TABLE ERPADMIN.EXCEP_CIUDAD 
	ADD CONSTRAINT XPKEXCEP_CIUDAD_COMPOSITE 
		PRIMARY KEY (COD_CIA,PAIS,DIVISION_GEOGRAFICA1,DIVISION_GEOGRAFICA2,CODIGO_RETENCION)
go



CREATE TABLE ERPADMIN.EXCEP_REGIMEN(
	CODIGO 			VARCHAR(12)	 NOT NULL,
	COD_CIA 		VARCHAR(10)	 NOT NULL,
	CODIGO_RETENCION 	VARCHAR(4) 	 NOT NULL,
	PORCENTAJE 		DECIMAL(28,8)	 NOT NULL,
	CENTRO_COSTO 		VARCHAR(25)	 NULL,
	CUENTA_CONTABLE 	VARCHAR(25)	 NULL)
go

ALTER TABLE ERPADMIN.EXCEP_REGIMEN 
	ADD CONSTRAINT XPKEXCEP_REGIMEN_COMPOSITE 
		PRIMARY KEY(CODIGO,COD_CIA,CODIGO_RETENCION)
go




CREATE TABLE $$COMPANIA$$.FACTURA_CANCELA_FR(
	TIPO_DOCUMENTO 		VARCHAR(1) 	NOT NULL,
	FACTURA 		VARCHAR(50) 	NOT NULL,
	NUMERO_PAGO 		INT 		NOT NULL,
	TIPO 			VARCHAR(1) 	NOT NULL,
	MONTO 			DECIMAL(28, 8) 	NOT NULL,
	MONEDA 			VARCHAR(1) 	NOT NULL,
	NUM_DOCUMENTO 		VARCHAR(20) 	NULL
)
go



ALTER TABLE $$COMPANIA$$.FACTURA_CANCELA_FR ADD  CONSTRAINT PKFACTURA_CANCELA_FR PRIMARY KEY NONCLUSTERED 
(
	TIPO_DOCUMENTO ASC,
	FACTURA ASC,
	TIPO ASC,
	NUMERO_PAGO ASC
)
go




CREATE TABLE ERPADMIN.GLOBALES
(
	MODULO 		VARCHAR(20) 	NOT NULL,
	NOMBRE 		VARCHAR(30) 	NOT NULL,
	TIPO 		VARCHAR(1) 		NOT NULL,
	VALOR 		VARCHAR(250) 	NULL,
	TEXTO 		TEXT 			NULL
)
go


ALTER TABLE ERPADMIN.GLOBALES  
      ADD CONSTRAINT PKGLOBALES PRIMARY KEY NONCLUSTERED (MODULO, NOMBRE)
go      


CREATE TABLE ERPADMIN.GLOBALES_MODULO
(
	MODULO 		VARCHAR(20) 	NOT NULL,
	NOMBRE 		VARCHAR(30) 	NOT NULL,
	TIPO 		VARCHAR(1) 		NOT NULL,
	VALOR 		VARCHAR(250) 	NULL,
	TEXTO 		TEXT 	NULL
)
go



ALTER TABLE ERPADMIN.GLOBALES_MODULO 
      ADD CONSTRAINT PKGLOBALES_MODULO
			PRIMARY KEY NONCLUSTERED (MODULO, NOMBRE)
go


CREATE TABLE ERPADMIN.GLOBALES_CONF_FR
(
	HANDHELD 	VARCHAR(4) 	NOT NULL,
	CONSTANTE 	VARCHAR(50) 	NOT NULL,
	VALOR 		VARCHAR(50) 	NULL
)
go


ALTER TABLE ERPADMIN.GLOBALES_CONF_FR ADD CONSTRAINT PKGLOBALESCONFFR  
            PRIMARY KEY NONCLUSTERED (HANDHELD, CONSTANTE)
go            



CREATE TABLE ERPADMIN.GLOBALES_FR (
       DIR_EML              	VARCHAR(30)   	NULL,
       NUM_FAX              	VARCHAR(15)   	NULL,
       SLG_CRP              	VARCHAR(30)   	NULL,
       NIT_CRP              	VARCHAR(20)   	NULL,
       WEB_SIT              	VARCHAR(30)   	NULL,
       NOM_CRP              	VARCHAR(40)   	NULL,
       DIR_CRP              	VARCHAR(60)   	NULL,
       TEL_CRP              	VARCHAR(15)   	NULL,
       CAM_LST_PRC          	VARCHAR(1)    	NOT NULL,
       CAM_CON_PG          	VARCHAR(1)    	NOT NULL,
       CAM_PAIS             	VARCHAR(1)    	NOT NULL,
       CAM_CLA_PED          	VARCHAR(1)    	NOT NULL,
       ESQUEMA_DESC         	VARCHAR(1)    	NOT NULL,
       APLICA_RECARGO		VARCHAR(1)    	NOT NULL 	DEFAULT 'N',
       PORC_RECARGO		DECIMAL(28,8) 	NOT NULL 	DEFAULT 0,
       USA_CONSIGNACION 	VARCHAR(1)  	NOT NULL 	DEFAULT 'N',
       COBRO_MAL_ESTADO 	VARCHAR(1)  	NOT NULL 	DEFAULT 'N',
       USA_RUTEO 		VARCHAR(1)	NOT NULL 	DEFAULT 'N',
       COBROS_FACTURA_CONTADO 	VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
       RECAL_PRECIO             VARCHAR (1) 	NOT NULL 	DEFAULT 'N',
       USA_SUG_VENTA 		VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
       USA_RUBROS_JORNADA 	VARCHAR(1) 	not null 	default 'N',
       Rubro1_JORNADA 		VARCHAR(40)	NULL,
       Rubro2_JORNADA 		VARCHAR(40)	NULL,
       Rubro3_JORNADA 		VARCHAR(40)	NULL,
       Rubro4_JORNADA 		VARCHAR(40)	NULL,
       Rubro5_JORNADA 		VARCHAR(40)	NULL,
       SOPORTE_TRASIEGOS 	VARCHAR(1) 	NOT NULL 	default 'N',
       USA_ENVASES  		VARCHAR(1) 	NOT NULL 	default 'N',
       VERIF_TOMAFISICA  	VARCHAR(1) 	NOT NULL 	default 'N',
       PRONTO_PAGO_TOTALES 	VARCHAR(1) 	NOT NULL 	DEFAULT('N'),
       PORCENTAJE_RESOLUCION 	INT 		NOT NULL 	DEFAULT 0,
       PED_TEMP 		VARCHAR(1) 	NOT NULL 	DEFAULT('N'),
       ESQUEMA_RESOLUCIONES 	VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
       SINCRO_DESATENDIDA 	VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
       OPT_BUSQ_ARTICULO 	VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
       VALIDA_LOTE_DEV 		VARCHAR(1) 	NOT NULL 	DEFAULT 'S',
	   NRC_CRP 				 VARCHAR(20),
	   GIRO_CRP				 VARCHAR(60)
)
go

CREATE TABLE ERPADMIN.GLOBALES_RUTEO (
	CORP_NOMBRE		VARCHAR(40)     NULL,
	CORP_DIRECCION		VARCHAR(60)     NULL,
	CORP_TELEFONO		VARCHAR(15)     NULL,
	CORP_SLOGAN		VARCHAR(30)     NULL,
	CORP_NIT		VARCHAR(20)     NULL,
	CORP_WEB		VARCHAR(30)     NULL,
	CORP_EMAIL		VARCHAR(30)     NULL,
	CORP_FAX		VARCHAR(15)     NULL,
	APLICA_RECARGO		VARCHAR(1) 	NOT NULL 	DEFAULT 'N' ,
	PORC_RECARGO		DECIMAL        	NULL,
	USUARIO_ALDO		VARCHAR(25)     NULL,
	PASSWORD_ALDO		VARCHAR(10)     NULL,
	COMPANIAS		TEXT         	NULL,
	CORREOS_EXAC_ALDO	VARCHAR(254)    NULL,
	CORREOS_ALDO_EXAC	VARCHAR(254)    NULL,
	COPIAR_RUTAS		VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	CAM_LST_PRC		VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	CAM_CON_PG		VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	CAM_PAIS		VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	CAM_CLA_PED		VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	HISTORICO_PEDIDOS 	VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	CANTIDAD_MESES 	    	INT 		NULL,
	ESQUEMA_DESC        	VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	USA_CONSIGNACION	VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	COBRO_MAL_ESTADO 	VARCHAR(1)  	NOT NULL 	DEFAULT 'N',
	USA_RUTA_CLIENTE 	VARCHAR(1)  	NOT NULL 	DEFAULT 'N',
	USA_BODEGA_FA		VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	SUGERIR_LOTES		VARCHAR(1)	NOT NULL 	DEFAULT 'N',
	SUG_LOCALIZACION	VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	GENERAR_BITACORA	VARCHAR(1)	NOT NULL 	DEFAULT 'N',
	USA_RUTEO 		VARCHAR(1)  	NOT NULL 	DEFAULT 'N',
	SUBTIPO_RECIBO		INT 		NULL,
	CONSECUTIVO		VARCHAR(10) 	NULL,
	COBROS_FACTURA_CONTADO 	VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	RECAL_PRECIO		VARCHAR (1)	NOT NULL 	DEFAULT 'N',
	HISTORICO_FACTURA 	VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	CANTIDAD_MESES_FAC 	INT 		NULL 	 	DEFAULT  0,
	SUBTIPO_NOTACREDITO 	INT		NULL,
	RUTA_EMM		VARCHAR(254) 	NULL,
	USA_SUG_VENTA 		VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	USA_RUBROS_JORNADA 	varchar(1) 	not null 	default 'N',
	Rubro1_JORNADA 		varchar(40) 	NULL,
	Rubro2_JORNADA 		varchar(40)	NULL,
	Rubro3_JORNADA 		varchar(40)	NULL,
	Rubro4_JORNADA 		varchar(40)	NULL,
	Rubro5_JORNADA 		varchar(40)	NULL,
	SOPORTE_TRASIEGOS 	varchar(1) 	not null 	default 'N',
	USA_ENVASES  		varchar(1) 	not null 	default 'N',
	VERIF_TOMAFISICA  	varchar(1) 	not null 	default 'N',
	PERMITIDO_FALTANTE 	decimal(28,8)	NULL,
	VERIF_CARGAS  		varchar(1)	not null 	default 'N',
	PRONTO_PAGO_TOTALES 	VARCHAR(1) 	NOT NULL 	DEFAULT('N'),
	PORCENTAJE_RESOLUCION 	INT 		DEFAULT 0 	NOT NULL,
	PED_TEMP 		VARCHAR(1) 	NOT NULL 	DEFAULT('N'),
	ESQUEMA_RESOLUCIONES 	VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	SINCRO_DESATENDIDA 	VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	OPT_BUSQ_ARTICULO 	VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	VALIDA_LOTE_DEV 	VARCHAR(1) 	NOT NULL 	DEFAULT 'S',
	CORP_NRC  			VARCHAR(20),
	CORP_GIRO 			VARCHAR(60)
)
go

CREATE TABLE ERPADMIN.GRUPO_ART_ASOC_RT (
         GRUPO_ARTICULO  VARCHAR(3)   NOT NULL,
         COMPANIA        VARCHAR(10)  NOT NULL,
         ARTICULO        VARCHAR(20)  NOT NULL )
go

ALTER TABLE ERPADMIN.GRUPO_ART_ASOC_RT
         ADD CONSTRAINT XPKGRPASOCART 
         	PRIMARY KEY NONCLUSTERED (GRUPO_ARTICULO, COMPANIA, ARTICULO )
go

CREATE TABLE ERPADMIN.GRUPO_ARTICULO_RT (
         GRUPO_ARTICULO  VARCHAR(3)   NOT NULL,
         DESCRIPCION     VARCHAR(40)  NOT NULL )
go

ALTER TABLE ERPADMIN.GRUPO_ARTICULO_RT
         ADD CONSTRAINT XPKGRUPOART 
         	PRIMARY KEY NONCLUSTERED (GRUPO_ARTICULO )
go

CREATE TABLE ERPADMIN.HANDHELD_RT (
         HANDHELD	VARCHAR(4)   	NOT NULL,
         DESCRIPCION    VARCHAR(40)  	NOT NULL,
         SERIE         	VARCHAR(15) 	NULL,
         MODELO         VARCHAR(15)  	NULL,
         ESTADO 	VARCHAR(1)   	NOT NULL DEFAULT('I'),
         FIRMA 		VARCHAR(2048) 	NULL
)
go

ALTER TABLE ERPADMIN.HANDHELD_RT
         ADD CONSTRAINT XPKHANDHELD 
         	PRIMARY KEY NONCLUSTERED (HANDHELD )
go


CREATE TABLE ERPADMIN.IMPRESORA_HH(
	HANDHELD 	varchar(4) 	NOT NULL,
	IMPRESORA 	varchar(50) 	NOT NULL,
	PUERTO 		varchar(20) 	NOT NULL,
	CANT_LINEAS 	int 		NOT NULL,
	CANT_COPIAS 	int 		NOT NULL,
	IMPR_DEFAULT 	varchar(1)  	NOT NULL	DEFAULT 'N'
)
go

ALTER TABLE ERPADMIN.IMPRESORA_HH 
	ADD CONSTRAINT IMPRESORAHH_PK 
		PRIMARY KEY (HANDHELD,IMPRESORA)
go



CREATE TABLE ERPADMIN.IMPUESTO (
	COMPANIA	VARCHAR(10) 	NOT NULL,
	IMPUESTO	VARCHAR(4) 		NOT NULL,
	IMPUESTO1	DECIMAL(28,8)	NOT NULL,
	IMPUESTO2	DECIMAL(28,8) 	NULL
)
go

ALTER TABLE ERPADMIN.IMPUESTO ADD 
	CONSTRAINT ALDOIMPUESTO_PK 
		PRIMARY KEY NONCLUSTERED (COMPANIA,IMPUESTO)
go


CREATE TABLE ERPADMIN.INFO_DEVOLUCION_RT (
    COMPANIA	     			VARCHAR(10) NOT NULL,
    GENERAR_DEVOLUC     		VARCHAR(1)  NOT NULL,
    BODEGA_BUEN_ESTADO  		VARCHAR(4)  NULL,
    BODEGA_MAL_ESTADO   		VARCHAR(4)  NULL,
    LOCALIZACION_BUEN_ESTADO 	VARCHAR(8) 	NOT NULL DEFAULT 'ND',
    LOCALIZACION_MAL_ESTADO 	VARCHAR(8) 	NOT NULL DEFAULT 'ND',
    NOMBRE_LOC_BUEN_ESTADO 		VARCHAR(40) NOT NULL DEFAULT 'No Definida',
    NOMBRE_LOC_MAL_ESTADO 		VARCHAR(40)	NOT NULL DEFAULT 'No Definida'
)
go

ALTER TABLE ERPADMIN.INFO_DEVOLUCION_RT
         ADD CONSTRAINT XPKINFODEVOL 
         	PRIMARY KEY NONCLUSTERED (COMPANIA )
go




CREATE TABLE ERPADMIN.JORNADA(
	HandHeld 	varchar(4) 	NOT NULL,
	Dia 		datetime 	NOT NULL,
	Rubro1 		varchar(40) 	NULL,
	Rubro2 		varchar(40) 	NULL,
	Rubro3 		varchar(40) 	NULL,
	Rubro4 		varchar(40) 	NULL,
	Rubro5 		varchar(40) 	NULL,
	DOC_PRO		varchar(1) 	NULL
)
go

ALTER TABLE ERPADMIN.JORNADA 
	ADD Constraint PK_JornadaComposite 
			PRIMARY KEY (HandHeld,Dia)
go




CREATE TABLE ERPADMIN.JORNADA_RUTAS(
	RUTA 				VARCHAR(4) 	NOT NULL,
	FECHA 				DATETIME 	NOT NULL,
	FECHA_HORA_INICIO 		DATETIME 	NOT NULL,
	FECHA_HORA_FIN 			DATETIME 	NULL,
	PEDIDOS_LOCAL 			DECIMAL(28,8) 	NULL,
	MONTO_PEDIDOS_LOCAL 		DECIMAL(28,8) 	NULL,
	PEDIDOS_DOLAR 			DECIMAL(28,8) 	NULL,
	MONTO_PEDIDOS_DOLAR 		DECIMAL(28,8) 	NULL,
	FACTURAS_LOCAL 			DECIMAL(28,8) 	NULL,
	MONTO_FACTURAS_LOCAL 		DECIMAL(28,8) 	NULL,
	FACTURAS_DOLAR 			DECIMAL(28,8) 	NULL,
	MONTO_FACTURAS_DOLAR 		DECIMAL(28,8) 	NULL,
	DEVOLUCIONES_LOCAL 		DECIMAL(28,8) 	NULL,
	MONTO_DEVOLUCIONES_LOCAL 	DECIMAL(28,8) 	NULL,
	DEVOLUCIONES_DOLAR 		DECIMAL(28,8) 	NULL,
	MONTO_DEVOLUCIONES_DOLAR 	DECIMAL(28,8) 	NULL,
	COBROS_LOCAL 			DECIMAL(28,8) 	NULL,
	COBROS_DOLAR 			DECIMAL(28,8) 	NULL,
	MONTO_COBROS_LOCAL 		DECIMAL(28,8) 	NULL,
	MONTO_COBROS_DOLAR 		DECIMAL(28,8) 	NULL,
	MONTO_COBROS_CHQ_LOCAL 		DECIMAL(28,8) 	NULL,
	MONTO_COBROS_CHQ_DOLAR 		DECIMAL(28,8) 	NULL,
	MONTO_COBROS_EFC_LOCAL 		DECIMAL(28,8) 	NULL,
	MONTO_COBROS_EFC_DOLAR 		DECIMAL(28,8) 	NULL,
	MONTO_COBROS_NC_LOCAL 		DECIMAL(28,8) 	NULL,
	MONTO_COBROS_NC_DOLAR 		DECIMAL(28,8) 	NULL,
	DEPOSITOS_LOCAL 		DECIMAL(28,8) 	NULL,
	MONTO_DEPOSITOS_LOCAL 		DECIMAL(28,8) 	NULL,
	DEPOSITOS_DOLAR 		DECIMAL(28,8) 	NULL,
	MONTO_DEPOSITOS_DOLAR 		DECIMAL(28,8) 	NULL,
	DEVOLUCIONES_EFC_LOCAL 		DECIMAL(28,8)	NULL,
	DEVOLUCIONES_EFC_DOLAR 		DECIMAL(28,8)	NULL,
	MONTO_DEVOLUCION_EFC_LOCAL 	DECIMAL(28,8)	NULL,
	MONTO_DEVOLUCION_EFC_DOLAR 	DECIMAL(28,8)	NULL,
	FACTURASTF_LOCAL 		DECIMAL(28,8)	NULL,
	MONTO_FACTURASTF_LOCAL 		DECIMAL(28,8)	NULL,
	FACTURASTF_DOLAR 		DECIMAL(28,8)	NULL,
	MONTO_FACTURASTF_DOLAR 		DECIMAL(28,8)	NULL,
	GARANTIAS_LOCAL 		DECIMAL(28,8)	NULL,
	MONTO_GARANTIAS_LOCAL 		DECIMAL(28,8)	NULL,
	GARANTIAS_DOLAR 		DECIMAL(28,8)	NULL,
	MONTO_GARANTIAS_DOLAR 		DECIMAL(28,8)	NULL,
	CIERRE 				VARCHAR(1) 	NOT NULL 	DEFAULT 'N',
	OBSERVACION 			VARCHAR(500)	NULL,
	FACTURAS_LOCAL_CRE 		decimal(28,8) NULL,
	FACTURAS_DOLAR_CRE 		decimal(28,8) NULL,
	MONTO_FACTURAS_LOCAL_CRE 	decimal(28,8) NULL,
	MONTO_FACTURAS_DOLAR_CRE 	decimal(28,8) NULL,
	GARANTIAS_LOCAL_CRE 		decimal(28,8) NULL,
	GARANTIAS_DOLAR_CRE 		decimal(28,8) NULL,
	MONTO_GARANTIAS_LOCAL_CRE 	decimal(28,8) NULL,
	MONTO_GARANTIAS_DOLAR_CRE 	decimal(28,8) NULL,
	FACTURASTF_LOCAL_CRE 		decimal(28,8) NULL,
	FACTURASTF_DOLAR_CRE 		decimal(28,8) NULL,
	MONTO_FACTURASTF_LOCAL_CRE 	decimal(28,8) NULL,
	MONTO_FACTURASTF_DOLAR_CRE 	decimal(28,8) NULL,
	FACTURAS_LOCAL_CONT 		decimal(28,8) NULL,
	FACTURAS_DOLAR_CONT 		decimal(28,8) NULL,
	MONTO_FACTURAS_LOCAL_CONT 	decimal(28,8) NULL,
	MONTO_FACTURAS_DOLAR_CONT 	decimal(28,8) NULL,
	GARANTIAS_LOCAL_CONT 		decimal(28,8) NULL,
	GARANTIAS_DOLAR_CONT 		decimal(28,8) NULL,
	MONTO_GARANTIAS_LOCAL_CONT 	decimal(28,8) NULL,
	MONTO_GARANTIAS_DOLAR_CONT 	decimal(28,8) NULL,
	FACTURASTF_LOCAL_CONT 		decimal(28,8) NULL,
	FACTURASTF_DOLAR_CONT 		decimal(28,8) NULL,
	MONTO_FACTURASTF_LOCAL_CONT 	decimal(28,8) NULL,
	MONTO_FACTURASTF_DOLAR_CONT 	decimal(28,8) NULL,
	MONTO_DEPOSITOS_LOCAL_EFEC 	decimal(28,8) NULL,
	MONTO_DEPOSITOS_LOCAL_CHECK 	decimal(28,8) NULL,
	MONTO_DEPOSITOS_DOLAR_EFEC 	decimal(28,8) NULL,
	MONTO_DEPOSITOS_DOLAR_CHECK 	decimal(28,8) NULL
)
go

ALTER TABLE ERPADMIN.JORNADA_RUTAS 
	ADD CONSTRAINT PK_JORNADA_RUTAS PRIMARY KEY NONCLUSTERED (RUTA, FECHA) 
go	

CREATE TABLE ERPADMIN.HISTORIAL_DESCUENTOS(
	HANDHELD	VARCHAR(4)		NOT NULL,
	COMPANIA	VARCHAR(10)		NOT NULL,
	COD_ZON		VARCHAR(4)		NOT NULL,
	DOCUMENTO	VARCHAR(50)		NOT NULL,
	LINEA		VARCHAR(5)		NOT NULL,
	REGLA		VARCHAR(200)	NOT NULL,
	ARTICULO	VARCHAR(20)		NOT NULL,
	CANTIDAD	DECIMAL(28,8)	NOT NULL,
	DESCUENTO	DECIMAL(28,8)	NOT NULL,
	ORIGEN		VARCHAR(3)		NOT NULL,
	DOC_PRO		VARCHAR(1)		NULL
)

go

ALTER TABLE ERPADMIN.HISTORIAL_DESCUENTOS
	ADD CONSTRAINT GUIDLINPK PRIMARY KEY (HANDHELD, COMPANIA, COD_ZON, DOCUMENTO, LINEA, REGLA)

go






CREATE TABLE ERPADMIN.LINEA_CONSIG_LOTE_LOC(
	COMPANIA 	VARCHAR(10) 	NOT NULL,
	BODEGA 		VARCHAR(4) 	NOT NULL,
	NUM_CONSIG 	VARCHAR(20) 	NOT NULL,
	NUM_LN 		INT 		NOT NULL,
	ARTICULO 	VARCHAR(20) 	NOT NULL,
	LOCALIZACION 	VARCHAR(8) 	NOT NULL,
	LOTE 		VARCHAR(15) 	NOT NULL,
	CNT_MAX 	DECIMAL(28, 8) 	NOT NULL,
	CNT_MIN 	DECIMAL(28, 8) 	NOT NULL,
	ART_BON 	VARCHAR(1) 	NOT NULL DEFAULT 'N',
	DOC_PRO 	VARCHAR(1)	NULL
)
go	

ALTER TABLE ERPADMIN.LINEA_CONSIG_LOTE_LOC 
	ADD CONSTRAINT PKLINEA_CONSIG_LOTE_LOC PRIMARY KEY NONCLUSTERED (COMPANIA ASC,BODEGA ASC,NUM_CONSIG ASC,NUM_LN ASC,ARTICULO ASC,LOCALIZACION ASC,LOTE ASC)
go



CREATE TABLE ERPADMIN.LINEA_PED_LOTE_LOC
(
	COMPANIA 		VARCHAR(10) 	NOT NULL,
	BODEGA 			VARCHAR(4) 		NOT NULL,
	NUM_PED 		VARCHAR(20) 	NOT NULL,
	NUM_LN 			int 			NOT NULL,
	ARTICULO 		VARCHAR(20) 	NOT NULL,
	LOCALIZACION 	VARCHAR(8) 		NOT NULL,
	LOTE 			VARCHAR(15) 	NOT NULL,		
	CNT_MAX 		decimal(28, 8) 	NOT NULL,
	CNT_MIN 		decimal(28, 8) 	NOT NULL,
	ART_BON 		VARCHAR(1) 		NOT NULL
)
go

ALTER TABLE ERPADMIN.LINEA_PED_LOTE_LOC
         ADD CONSTRAINT PKLINEA_PED_LOTE_LOC PRIMARY KEY NONCLUSTERED
        	 (COMPANIA, BODEGA, NUM_PED, NUM_LN, ARTICULO, LOCALIZACION, LOTE )
go




CREATE TABLE ERPADMIN.LSTPRECIO_ALDO_RT (
         RUTA         	VARCHAR(4)      NOT NULL,
         LISTA_PRECIO	INT         	NOT NULL,
         COMPANIA    	VARCHAR(10)     NOT NULL,
         FECHA       	DATETIME        NOT NULL,
         NIVEL_PRECIO   VARCHAR(12)		NOT NULL,
         MONEDA         VARCHAR(1)      NOT NULL 
)
go

ALTER TABLE ERPADMIN.LSTPRECIO_ALDO_RT
         ADD CONSTRAINT XPKLSTPRECIOALDO 
         	PRIMARY KEY NONCLUSTERED (RUTA, LISTA_PRECIO, COMPANIA )
go


CREATE TABLE ERPADMIN.MODELO_RETENCION(
	MODELO_RETENCION 	varchar(4) 		NOT NULL,
	COD_CIA 		varchar(10)		NOT NULL,
	DESCRIPCION 		varchar(40) 		NOT NULL)
go
	

ALTER TABLE ERPADMIN.MODELO_RETENCION 
	ADD CONSTRAINT XPKMODELO_RETENCION 
		PRIMARY KEY(MODELO_RETENCION,COD_CIA)
go



CREATE TABLE erpadmin.NCF_CONSECUTIVO_RT(
	COMPANIA 		VARCHAR(10) 	NOT NULL,
	HANDHELD 		VARCHAR(4) 	NOT NULL,
	PREFIJO 		VARCHAR(20) 	NOT NULL,
	DESCRIPCION 		VARCHAR(70) 	NOT NULL,
	ULTIMO_VALOR 		VARCHAR(20) 	NOT NULL,
	SECUENCIA_INICIAL 	VARCHAR(20) 	NOT NULL,
	SECUENCIA_FINAL 	VARCHAR(20) 	NOT NULL,
	TIPO 			VARCHAR(6) 	NOT NULL,
	TIPO_DOC 		VARCHAR(3) 	NOT NULL,
	TIPO_CONTRIBUYENTE 	VARCHAR(1) 	NOT NULL,
	SECUENCIA 			INT  		NULL
) 
go


ALTER TABLE erpadmin.NCF_CONSECUTIVO_RT
        ADD CONSTRAINT PKNCF_CONSECUTIVORT PRIMARY KEY NONCLUSTERED (COMPANIA, HANDHELD, PREFIJO)
go        



CREATE TABLE ERPADMIN.NCF_SECUENCIA_RT 
( 
	PKNCF_SECUENCIA INT NOT NULL,
	PREFIJO VARCHAR(50) NOT NULL,
	SECUENCIA_INICIAL VARCHAR(20) NOT NULL,
	SECUENCIA_FINAL VARCHAR(20),
	FECHA_VENCE DATETIME NOT NULL,
	ULTIMO_VALOR VARCHAR(20) NULL
)
go


ALTER TABLE ERPADMIN.NCF_SECUENCIA_RT
	ADD CONSTRAINT PKNCF_SECUENCIA PRIMARY KEY (PKNCF_SECUENCIA)
go



CREATE TABLE ERPADMIN.NIVEL_LISTA (
	COMPANIA		VARCHAR(10) NOT NULL,
	NIVEL_PRECIO		VARCHAR(12) NOT NULL,
	MONEDA			VARCHAR(1)  NOT NULL,
	LISTA			int 	    NOT NULL,
	IMPUESTO1_INCLUIDO 	VARCHAR(1)  NOT NULL DEFAULT('N')
)
go

ALTER TABLE ERPADMIN.NIVEL_LISTA ADD 
	CONSTRAINT NIVEL_LISTA_PK 
		PRIMARY KEY NONCLUSTERED (COMPANIA,NIVEL_PRECIO,MONEDA)
go



CREATE TABLE ERPADMIN.REGIMENES(
	REGIMEN 		VARCHAR(12)	 NOT NULL,
	COD_CIA 		VARCHAR(10)	 NOT NULL,
	DESCRIPCION 		VARCHAR(40)	 NOT NULL,
	MODELO_RETENCION 	VARCHAR(4) 	 NULL,
	IMP1_ASUMIDO_COMPRAS 	VARCHAR(1) 	 NOT NULL 	DEFAULT ('A'),
	CENTRO_COSTO 		VARCHAR(25)	 NULL,
	CUENTA_CONTABLE 	VARCHAR(25)	 NULL,
	CONSECUTIVO 		VARCHAR(10)	 NULL)
go
	
ALTER TABLE ERPADMIN.REGIMENES 
	ADD CONSTRAINT XPKREGIMENES 
		PRIMARY KEY (REGIMEN,COD_CIA)
go


CREATE TABLE ERPADMIN.REGLAS_PRECARGADAS_DESC
(
	COMPANIA 	VARCHAR(10) NOT NULL,
	PAQUETE 	VARCHAR(20) NOT NULL,
	REGLA 		VARCHAR(20) NOT NULL,
	ARTICULOS 	VARCHAR(MAX),
	CLIENTES 	VARCHAR(MAX)
)
go

ALTER TABLE ERPADMIN.REGLAS_PRECARGADAS_DESC 
	ADD CONSTRAINT PK_REGLAS_PRECARGADAS_DESC PRIMARY KEY (COMPANIA,PAQUETE,REGLA)
go


CREATE TABLE ERPADMIN.REGLAS_PRECARGADAS_BONIF
(
	COMPANIA 	VARCHAR(10) NOT NULL,
	PAQUETE 	VARCHAR(20) NOT NULL,
	REGLA 		VARCHAR(20) NOT NULL,
	ARTICULOS 	VARCHAR(MAX),
	CLIENTES 	VARCHAR(MAX)
)
go

ALTER TABLE ERPADMIN.REGLAS_PRECARGADAS_BONIF 
	ADD CONSTRAINT PK_REGLAS_PRECARGADAS_BONIF PRIMARY KEY (COMPANIA,PAQUETE,REGLA)
go



CREATE TABLE ERPADMIN.REPORTE_FACTURA(
	HANDHELD 		varchar(4) 	NOT NULL,
	REPORTE 		varchar(50) 	NOT NULL,
	DESCRIPCION 		varchar(150) 	NULL,
	TIPO_CREDITO_FACT 	varchar(1) 	NOT NULL	DEFAULT 'N',
	REP_DEFAULT 		varchar(1) 	NOT NULL 	DEFAULT 'N'
)
go

ALTER TABLE ERPADMIN.REPORTE_FACTURA 
	ADD CONSTRAINT REPORTE_FACTURA_PK 
		PRIMARY KEY (HANDHELD,REPORTE)
go


CREATE TABLE ERPADMIN.RETENCIONES(
	CODIGO_RETENCION 	varchar(4) 		NOT NULL,
	COD_CIA 		varchar(10) 		NOT NULL,
	DESCRIPCION 		varchar(40) 		NOT NULL,
	PORCENTAJE 		decimal(28, 8) 		NOT NULL,
	TIPO 			varchar(1) 		NOT NULL 	DEFAULT ('R'),
	APLICA_MONTO 		varchar(1) 		NOT NULL 	DEFAULT ('N'),
	APLICA_SUBTOTAL 	varchar(1) 		NOT NULL 	DEFAULT ('N'),
	APLICA_SUB_DESC 	varchar(1) 		NOT NULL 	DEFAULT ('N'),
	APLICA_IMPUESTO1 	varchar(1) 		NOT NULL 	DEFAULT ('N'),
	APLICA_IMPUESTO2 	varchar(1) 		NOT NULL 	DEFAULT ('N'),
	APLICA_RUBRO1 		varchar(1) 		NOT NULL 	DEFAULT ('N'),
	APLICA_RUBRO2 		varchar(1) 		NOT NULL 	DEFAULT ('N'),
	ESTADO 			varchar(1) 		NOT NULL 	DEFAULT ('I'),
	MONTO_MINIMO 		decimal(28, 8) 		NOT NULL,
	CTR_RETENCION 		varchar(25) 		NULL,
	CTA_RETENCION 		varchar(25) 		NULL,
	RET_POR_ARTICULO 	varchar(1) 		NOT NULL 	DEFAULT ('N'),
	ES_AUTORETENEDOR 	varchar(1) 		NOT NULL 	DEFAULT ('N'),
	CLASIFICACION_ART 	varchar(12) 		NULL,
	CTR_AUTORETENCION 	varchar(25) 		NULL,
	CTA_AUTORETENCION 	varchar(25) 		NULL,
	TIPO_EXCEPCION 		varchar(1) 		NOT NULL 	DEFAULT ('D'),
	NOAPLICA_PROV_AUTO 	varchar(1) 		NOT NULL 	DEFAULT ('N'),
	APLICA_RETENCION 	varchar(1) 		NOT NULL 	DEFAULT ('N'),
	RETENCION_BASE 		varchar(4) 		NULL,
	APLICA_IMP1_DESC 	varchar(1) 		NOT NULL 	DEFAULT ('N'),
	APLICA_IMP1_NODESC 	varchar(1) 		NOT NULL 	DEFAULT ('N'),
	TIPO_DOC_CC_CREDITO 	varchar(4000) 		NULL,
	TIPO_DOC_CC_DEBITO 	varchar(4000) 		NULL,
	TIPO_DOC_CP_CREDITO 	varchar(4000) 		NULL,
	TIPO_DOC_CP_DEBITO 	varchar(4000) 		NULL,
	UTILIZA_TARIFA_UVT 	varchar(1) 		NOT NULL 	DEFAULT ('N'),
	CONSEC_RET_VENTA 	varchar(10) 		NULL,
	CONSEC_RET_COMPRA 	varchar(10) 		NULL,
	PER_GENERAR_RET_CERO 	varchar(1) 		NOT NULL 	DEFAULT ('N'),
	TIPO_APLI_CANCELAR 	varchar(1) 		NOT NULL 	DEFAULT ('T')
)
go



ALTER TABLE ERPADMIN.RETENCIONES
	ADD  CONSTRAINT XPKRETENCIONES 
		PRIMARY KEY CLUSTERED(CODIGO_RETENCION,COD_CIA ASC)
go




CREATE TABLE ERPADMIN.RUTA_ASIGNADA_RT (
         RUTA           VARCHAR(4)    NOT NULL,
         COMPANIA       VARCHAR(10)   NOT NULL,
         AGENTE         VARCHAR(4)    NOT NULL,
         HANDHELD       VARCHAR(4)    NOT NULL,
         ACTIVA         VARCHAR(1)    NOT NULL,
         GRUPO_ARTICULO VARCHAR(3)    NOT NULL,
         BODEGA         VARCHAR(4)    NOT NULL DEFAULT 'ND' )
go

ALTER TABLE ERPADMIN.RUTA_ASIGNADA_RT
         ADD CONSTRAINT XPKRUTASIG 
         	PRIMARY KEY NONCLUSTERED ( RUTA )
go

CREATE TABLE ERPADMIN.RUTA_CFG (
       COMPANIA             VARCHAR(10) NOT NULL,
       RUTA              	VARCHAR(4) 	NOT NULL,
       GRUPO_ART            VARCHAR(3) 	NOT NULL,
       HANDHELD             VARCHAR(4) 	NOT NULL,
       BODEGA				VARCHAR(4)	NOT NULL DEFAULT 'ND',
       FECHA_INICIO         DATETIME 	NOT NULL,	
       FECHA_FIN            DATETIME 	NOT NULL
)
go

ALTER TABLE ERPADMIN.RUTA_CFG
	ADD CONSTRAINT PK_RUTA_CFG 
		PRIMARY KEY NONCLUSTERED (COMPANIA, RUTA, GRUPO_ART, HANDHELD, BODEGA)
go

CREATE TABLE ERPADMIN.RUTA_CLIENTE(
	RUTA			VARCHAR (4) 	NOT NULL,
	CLIENTE			VARCHAR (20)	NOT NULL,
	DIA				INT				NOT NULL,
	ORDEN			INT				NOT NULL
)
go

ALTER TABLE ERPADMIN.RUTA_CLIENTE
		ADD CONSTRAINT XPKRUTACLIENTE 
			PRIMARY KEY NONCLUSTERED ( RUTA,CLIENTE,DIA )
go

CREATE TABLE ERPADMIN.RUTA_CONSECUT_RT (
    RUTA         		VARCHAR(4)    	NOT NULL,
    COMPANIA         	VARCHAR(20)   	NOT NULL,
    PEDIDO           	VARCHAR(50)   	NOT NULL,
    RECIBO           	VARCHAR(50)   	NOT NULL,
    DEVOLUCION       	VARCHAR(50)   	NOT NULL,
    FACTURA          	VARCHAR(50)   	NOT NULL DEFAULT '0',
    INVENTARIO       	VARCHAR(20)   	NOT NULL,
    PEDIDO_DESCUENTO 	VARCHAR(50)   	NOT NULL DEFAULT '0',
    NOTACREDITO 		VARCHAR(20) 	NULL,
	NCF_CONSUMIDOR_F 	VARCHAR(20)	NULL,
	NCF_ORGANIZADO 		VARCHAR(20)	NULL,
	NCF_REGIMEN_ESP 	VARCHAR(20)	NULL,
	NCF_GUBERNAMENTAL 	VARCHAR(20)	NULL,
	NCF_DEVOLUCION 		VARCHAR(20)	NULL,
	NCF_RECIBO 		VARCHAR(20)	NULL,
	GARANTIA 		VARCHAR(20)     NULL,
	CONSEC_RESOLUCION_FAC 	VARCHAR(20) 	NULL,
	CONSEC_RESOLUCION_DEV 	VARCHAR(20) 	NULL,
	NCF_CONSUMIDOR_F_SEC 	INT 		NULL,
	NCF_ORGANIZADO_SEC 		INT 		NULL,
	NCF_REGIMEN_ESP_SEC 	INT 		NULL, 
	NCF_GUBERNAMENTAL_SEC 	INT			NULL, 
	NCF_DEVOCULION_SEC 		INT 		NULL,
	NCF_RECIBO_SEC 			INT 		NULL
	)
go

ALTER TABLE ERPADMIN.RUTA_CONSECUT_RT
         ADD CONSTRAINT XPKRUTACONSEC 
         	PRIMARY KEY NONCLUSTERED (RUTA, COMPANIA )
go

CREATE TABLE ERPADMIN.RUTA_RT (
         RUTA         	 VARCHAR(4)   NOT NULL,
         DESCRIPCION     VARCHAR(40)  NOT NULL,
         ACTIVA          VARCHAR(1)   NOT NULL,
         PERIODICIDAD    VARCHAR(1)   NOT NULL,
         GRUPO_TELEFONO  VARCHAR(4)   NULL )
go

ALTER TABLE ERPADMIN.RUTA_RT
         ADD CONSTRAINT XPKRUTA 
         	PRIMARY KEY NONCLUSTERED (RUTA )
go

CREATE TABLE ERPADMIN.SUGERIDO_ASOC (
    CLIENTE 	VARCHAR (20) NOT NULL ,
    SUGERIDO	VARCHAR (20) NOT NULL
) 
go

ALTER TABLE ERPADMIN.SUGERIDO_ASOC ADD 
	CONSTRAINT PK_SUGERIDO_ASOC 
		PRIMARY KEY NONCLUSTERED (CLIENTE,SUGERIDO)
go

CREATE TABLE ERPADMIN.SUGERIDO_ASOC_LINEA (
    CLIENTE 	VARCHAR (20) 	NOT NULL ,
    SUGERIDO 	VARCHAR (20) 	NOT NULL ,
    COMPANIA 	VARCHAR (10)	NOT NULL ,
    ARTICULO 	VARCHAR (20) 	NOT NULL ,
    CANTALM 	decimal (28,8) 	DEFAULT (1) NOT NULL ,
    CANTDET 	decimal (28,8)	DEFAULT (0) NOT NULL
) 
go

ALTER TABLE ERPADMIN.SUGERIDO_ASOC_LINEA ADD 
	CONSTRAINT PK_SUGERIDO_ASOC_LINEA 
		PRIMARY KEY NONCLUSTERED (CLIENTE,SUGERIDO,COMPANIA,ARTICULO)
go

ALTER TABLE ERPADMIN.SUGERIDO_ASOC_LINEA ADD 
	CONSTRAINT CK_CANTALM CHECK (CANTALM >= 0)
go

ALTER TABLE ERPADMIN.SUGERIDO_ASOC_LINEA ADD 
	CONSTRAINT CK_CANTDET CHECK (CANTDET >= 0)
go

ALTER TABLE ERPADMIN.SUGERIDO_ASOC_LINEA
	ADD CONSTRAINT CK_CANTIDADES CHECK (CANTALM > 0 OR CANTDET > 0)
go

CREATE TABLE ERPADMIN.SUGERIDOVENTA (
	SUGERIDO 	VARCHAR (20) NOT NULL ,
	DESCRIPCION	VARCHAR (80) NOT NULL 
) 
go

ALTER TABLE ERPADMIN.SUGERIDOVENTA ADD 
	CONSTRAINT PK_SUGERIDOVENTA PRIMARY KEY	NONCLUSTERED (SUGERIDO)  
go

CREATE TABLE ERPADMIN.SUGERIDOVENTA_DETALLE (
	SUGERIDO 		VARCHAR (20)  	NOT NULL ,
	COMPANIA 		VARCHAR (10)  	NOT NULL ,
	CLASIFICACION_1		VARCHAR (12)  	NOT NULL 
) 
go

ALTER TABLE ERPADMIN.SUGERIDOVENTA_DETALLE ADD 
	CONSTRAINT PK_SUGERIDOVENTA_DETALLE 
		PRIMARY KEY NONCLUSTERED (SUGERIDO,COMPANIA,CLASIFICACION_1)
go

CREATE TABLE ERPADMIN.VISITA (
	CLIENTE		VARCHAR(20) 		NOT NULL,
	RUTA		VARCHAR(4) 		NOT NULL,
	INICIO		DATETIME 		NOT NULL,
	RAZON		VARCHAR(2) 		NOT NULL,
	FIN		DATETIME 		NOT NULL,
	FECHA_PLAN	DATETIME 		NOT NULL,
	TIPO		VARCHAR(1) 		NULL,
	NOTAS		VARCHAR(512)		NULL,
	DOC_PRO		VARCHAR(1) 		NULL
)
go

ALTER TABLE ERPADMIN.VISITA ADD 
	CONSTRAINT VISITA_PK 
		PRIMARY KEY NONCLUSTERED(CLIENTE,RUTA,INICIO)
go

CREATE TABLE ERPADMIN.VISITA_DOCUMENTO (
	CLIENTE			VARCHAR(20) 	NOT NULL,
	RUTA			VARCHAR(4) 	NOT NULL,
	INICIO			DATETIME 	NOT NULL,
	COMPANIA		VARCHAR(10) 	NOT NULL,
	DOCUMENTO		VARCHAR(50)	NOT NULL,
	TIPO_DOCUMENTO		VARCHAR(1) 	NOT NULL
)
go



ALTER TABLE ERPADMIN.VISITA_DOCUMENTO ADD CONSTRAINT VISITA_DOCUMENTO_PK PRIMARY KEY NONCLUSTERED 
(
	CLIENTE ASC,
	RUTA ASC,
	INICIO ASC,
	COMPANIA ASC,
	DOCUMENTO ASC,
	TIPO_DOCUMENTO ASC
)
go
						


CREATE TABLE ERPADMIN.VISITAS_DET_RT (
         RUTA			VARCHAR(4) 	NOT NULL,
         COMPANIA         	VARCHAR(10)	NOT NULL,
         CLIENTE         	VARCHAR(20)	NOT NULL,
         FECHA_PLAN         	DATETIME   	NOT NULL,
         FECHA_HORA_INI     	DATETIME   	NOT NULL,
         DOCUMENTO         	VARCHAR(50)	NOT NULL,
         FECHA_HORA_FIN     	DATETIME   	NOT NULL,
         EFECT_VISITA      	VARCHAR(2) 	NOT NULL,
         TIPO_DOCUMENTO		VARCHAR(1) 	NULL 
)
go

ALTER TABLE ERPADMIN.VISITAS_DET_RT
         ADD CONSTRAINT XPKVISITASDET 
         	PRIMARY KEY NONCLUSTERED (RUTA, COMPANIA, CLIENTE, FECHA_PLAN, FECHA_HORA_INI )
go

CREATE TABLE ERPADMIN.VISITAS_RT (
         FECHA_PLAN	DATETIME   	NOT NULL,
         COMPANIA       VARCHAR(10)	NOT NULL,
         RUTA         	VARCHAR(4) 	NOT NULL,
         CLIENTE        VARCHAR(20)	NOT NULL,
         FECHA_REAL	DATETIME   	NULL,
         ORDEN_PLAN	INT        	NOT NULL,
         ORDEN_REAL	INT        	NULL 
)
go

ALTER TABLE ERPADMIN.VISITAS_RT
         ADD CONSTRAINT XPKVISITAS 
         	PRIMARY KEY NONCLUSTERED (FECHA_PLAN, COMPANIA, RUTA, CLIENTE )
go



CREATE TABLE ERPADMIN.VISITA_UBICACION(
	CLIENTE 	VARCHAR(20) 	NOT NULL,
	RUTA 		VARCHAR(4) 	NOT NULL,
	INICIO 		DATETIME 	NOT NULL,
	LATITUD 	DECIMAL(28,8) 	NULL,
	LONGITUD 	DECIMAL(28,8) 	NULL,
	ALTITUD 	DECIMAL(28,8)  	NULL,
	TIEMPO_GPS 	DATETIME 	NULL,
	TIEMPO_PDA 	DATETIME 	NULL,
	PDOP 		DECIMAL(28,8) 	NULL,
	ERROR 		VARCHAR(200) 	NULL
)
go

ALTER TABLE ERPADMIN.VISITA_UBICACION ADD CONSTRAINT VISUBIPK PRIMARY KEY (CLIENTE, RUTA, INICIO) 
go


CREATE TABLE ERPADMIN.TIPO_ANULACIONES
(
  COMPANIA 		VARCHAR(10) NOT NULL,
  TIPO_ANULACION 	VARCHAR(3) NOT NULL,
  DESCRIPCION 		VARCHAR(50) NOT NULL
)
go


CREATE TABLE ERPADMIN.TOMA_FISICA_INV
(
	CONSECUTIVO 		INTEGER IDENTITY(1,1) 	NOT NULL,
	COMPANIA 		VARCHAR(10) 		NOT NULL,
	HANDHELD 		VARCHAR(4) 		NOT NULL,
	FECHA 			DATETIME 		NOT NULL,
	ARTICULO 		VARCHAR(20) 		NOT NULL,
	BODEGA 			VARCHAR(4) 		NOT NULL,
	LOCALIZACION 		VARCHAR(8) 		NOT NULL,
	LOTE 			VARCHAR(15) 		NOT NULL,
	CANTIDAD 		DECIMAL(28,8) 		NOT NULL,
	CANT_FACT 		DECIMAL(28,8) 		NOT NULL DEFAULT 0,
	CANT_DIFERENCIA 	DECIMAL(28,8) 		NOT NULL DEFAULT 0,
	ESTADO 			VARCHAR(1) 		NOT NULL DEFAULT 'P'
	
)
go



CREATE TABLE ERPADMIN.TRASIEGO(
	Consecutivo 	int 		NOT NULL  IDENTITY(1,1),
	Compania 	varchar(10) 	NOT NULL,
	HandHeld 	varchar(4) 	NOT NULL,
	Fecha 		datetime 	NOT NULL,
	Articulo 	varchar(20) 	NOT NULL,
	Bodega 		varchar(4) 	NOT NULL,
	Localizacion 	varchar(8) 	NOT NULL,
	Lote 		varchar(15) 	NOT NULL,
	Tipo 		varchar(1) 	NOT NULL default 'E',
	Clase 		varchar(1) 	NOT NULL default 'L',
	Cant_dif 	decimal(28, 8) 	NOT NULL,
	Estado 		varchar(1) 	NOT NULL default 'P',
	OBS 		VARCHAR(1024) 	NULL
	)
go

ALTER TABLE ERPADMIN.TRASIEGO
       ADD   CONSTRAINT PK_TrasiegoFrd 
				PRIMARY KEY ( Consecutivo )
go


CREATE TABLE ERPADMIN.RESOLUCION_CONSECUTIVO_RT(
	COMPANIA 		VARCHAR(20) 	NOT NULL,
	HANDHELD 		VARCHAR(4) 	NOT NULL,
	RESOLUCION 		VARCHAR(20) 	NOT NULL,
	TIPO_DOCUMENTO 		VARCHAR(1) 	NOT NULL DEFAULT('F'),
	FECHA_RESOLUCION 	DATETIME 	NULL,
	FECHA_AUTORIZACION 	DATETIME 	NULL,
	FECHA_CREACION 		DATETIME 	NULL,
	SERIE 			VARCHAR(25) 	NOT NULL,
	MASCARA 		VARCHAR(50) 	NULL,
	CONSEC_INICIAL 		VARCHAR(50) 	NOT NULL,
	CONSEC_FINAL 		VARCHAR(50) 	NOT NULL,
	VALOR 			VARCHAR(50) 	NOT NULL,
	ESTADO 			VARCHAR(1) 	NOT NULL DEFAULT('D'),
	USUARIO_CREACION 	VARCHAR(25) 	NOT NULL,
	RUTA 			VARCHAR(4) 	NOT NULL,
	NUMERO_AUTORIZACION 	VARCHAR(80) 	NULL
)
go


ALTER TABLE ERPADMIN.RESOLUCION_CONSECUTIVO_RT 
	ADD CONSTRAINT RESOLUCION_CONSECUT_RT_PK  
		PRIMARY KEY (COMPANIA,HANDHELD,RESOLUCION,RUTA)
go