INSERT INTO ERPADMIN.MODULO_INSTALADO(ACCION,CONJUNTO) VALUES(3861, '$$COMPANIA$$')
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1000','ACTIVO CORRIENTE','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1001','UTILIDAD ANTES DE IMPUESTO VS. RENTA LIQUIDA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1002','UTILIDAD ANTES DE IMPUESTO VS. PERDIDA LIQUIDA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1003','PERDIDA DEL EJERCICIO VS. RENTA LIQUIDA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1004','PERDIDA DEL EJERCICIO VS. PERDIDA LIQUIDA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1005','PATRIMONIO CONTABLE VS. PATRIMONIO LIQUIDO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1006','PATRIMONIO CONTABLE NEGATIVO VS. PATRIMONIO LIQUIDO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1010','INFORMACION DE FIDEICOMISOS MOBILIARIOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1020','INFORMACION DE FIDEICOMISOS DE ADMINISTRACION','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1030','INFORMACION DE FIDEICOMISOS DE GARANTIA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1040','OTROS ENCARGOS FIDUCIARIOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1050','RENDIMIENTOS PAGADOS EN FIDUCIAS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1105','SALDO A 31 DE DICIEMBRE DE 2005 EN CAJA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1110','SALDO A 31 DE DICIEMBRE DE 2005 DE LAS CUENTAS CORRIENTES Y\O AHORRO QUE POSEA EN EL PAIS O EN EL EXTERIOR','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1111','PATRIMONIO CONTABLE NEGATIVO VS. PATRIMONIO LIQUIDO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1115','EL VALOR TOTAL DEL SALDO DE LAS CUENTAS CORRIENTES Y\O AHORRO POSEIDAS EN EL EXTERIOR','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1200','EL VALOR PATRIMONIAL DE LOS BONOS POSEIDOS A 31 DE DICIEMBRE DE 2005','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1201','EL VALOR PATRIMONIAL DE LOS CERTIFICADOS DE DEPOSITO POSEIDOS A 31 DE DICIEMBRE DE 2005','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1202','VALOR PATRIMONIAL DE LOS TITULOS POSEIDOS A 31 DE DICIEMBRE DE 2005','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1203','VALOR PATRIMONIAL DE LOS DERECHOS FIDUCIARIOS POSEIDOS A 31 DE DICIEMBRE DE 2005','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1204','VALOR PATRIMONIAL DE LAS DEMAS INVERSIONES POSEIDAS A 31 DE DICIEMBRE DE 2005','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1205','ACCIONES O APORTES POSEIDOS EN SOCIEDADES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1301','RETENCIONES POR SALARIOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1302','RETENCIONES POR VENTAS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1303','RETENCIONES POR SERVICIOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1304','RETENCIONES POR HONORARIOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1305','RETENCIONES POR COMISIONES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1306','RETENCIONES POR INTERESES Y RENDIMIENTOS FINANCIEROS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1307','RETENCIONES POR ARRENDAMIENTOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1308','OTRAS RETENCIONES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1309','RETENCION POR IMPUESTO A LAS VENTAS RETENIDO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1315','CUENTAS POR COBRAR- CLIENTES','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1316','CUENTAS POR COBRAR COMPAÑIAS ACCIONISTAS, SOCIOS Y COMPAÑIAS VINCULADAS','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1317','OTRAS CUENTAS POR COBRAR','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1318','SALDO FISCAL PROVISION DE CARTERA','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1340','CUENTAS POR COBRAR EN CONTRATOS DE MANDATO O DE ADMINISTRACION DELEGADA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1350','CUENTAS POR COPBRAR EN CONTRATOS DE ASOCIACION POR EXPLORACION Y EXPLOTACION MINERA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1402','TOTAL COMPRAS NETAS DEL AÑO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1403','COSTO DE MANO DE OBRA DIRECTA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1404','COSTOS INDIRECTOS DE FABRICACION','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1405','OTROS COSTOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1406','COSTOS DE VENTAS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1407','VALOR INVENTARIO FINAL A 31 DE DICIEMBRE','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1408','NACIMIENTOS DEL AÑO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1409','MUERTES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1410','COMPRAS Y GASTOS CAPITALIZADOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1411','TOTAL VALORIZACIONES GANADO BOVINO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1412','VALOR INVENTARIO FINAL A 31 DE DICIEMBRE DE LOS SEMOVIENTES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1501','VALOR PATRIMONIAL DE LOS INMUEBLES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1502','VALOR PATRIMONIAL DE LA MAQUINARIA Y EQUIPO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1503','VALOR PATRIMONIAL DEL EQUIPO DE OFICINA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1504','VALOR PATRIMONIAL DE LA FLOTA Y EQUIPO DE TRANSPORTE','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1505','VALOR PATRIMONIAL DEL EQUIPO DE COMPUTACION Y COMUNICACION','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1506','VALOR PATRIMONIAL DE LOS ACTIVOS FIJOS AMORTIZABLES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1507','VALOR PATRIMONIAL DE LOS DEMAS ACTIVOS FIJOS POSEIDOS','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1508','VALOR DE LA DEPRECIACION, AMORTIZACION Y AGOTAMIENTO ACUMULADO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('1509','VALOR PATRIMONIAL DE OTROS ACTIVOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2000','PASIVO CORRIENTE','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2001','PASIVO NO CORRIENTE','S', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2002','INTERES MINORITARIO DE BALANCE','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2201','PASIVOS CON PROVEEDORES','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2202','CUENTAS POR PAGAR A CASA MATRIZ, COMPAÑIAS VINCULADAS, SOCIOS Y ACCIONISTAS','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2203','OBLIGACIONES CON EL SECTOR FINANCIERO','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2204','PASIVOS POR IMPUESTOS GRAVAMENES Y TASAS','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2205','PASIVOS LABORALES','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2206','OTROS PASIVOS','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2240','PASIVOS EN CONTRATO DE MANDATO O DE ADMINITRACION DELEGADA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2250','PASIVOS EN CONTRATOS DE ASOCIACION POR EXPLORACION Y EXPLOTACION MINERA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2301','RETENCIONES POR SALARIOS Y DEMAS PAGOS LABORALES','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2302','RETENCIONES POR COMPRAS','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2303','RETENCIONES POR COMISIONES','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2304','RETENCIONES POR HONORARIOS','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2305','RETENCIONES POR SERVICIOS','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2306','RETENCIONES POR ARRENDAMIENTOS','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2307','RETENCIONES POR RENDIMIENTOS FINANCIEROS','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2308','RETENCIONES POR DIVIDENDOS Y PARTICIPACIONES','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2309','RETENCION POR ENAJENACION DE ACTIVOS FIJOS DE PERSONAS NATURALES ANTE NOTARIOS Y AUTORIDADES DE TRANSITO','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2310','RETENCION SOBRE INGRESOS DE TARJETAS DEBITO Y CREDITO','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2311','RETENCIONES POR LOTERIAS, APUESTAS Y SIMILARES','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2312','RETENCIONES POR PAGOS AL EXTERIOR A TITULO DE RENTA Y DE REMESAS','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2313','OTRAS RETENCIONES','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2314','AUTORETENCIONES POR VENTAS','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2315','AUTORETENCIONES POR SERVICIOS','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2316','AUTORETENCIONES POR RENDIMIENTOS FINANCIEROS','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2317','OTRAS AUTORETENCIONES','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2318','RETENCION DE IMPUESTO A LAS VENTAS RETENIDO A REGIMEN COMUN','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2319','RETENCION EN LA FUENTE ASUMIDA POR OPRACIONES','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2320','RETENCION EN LA FUENTE A PERSONAS O ENTIDADES SIN RESIDENCIA EN EL PAIS','N', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('2408','IMPUESTOS SOBRE LAS VENTAS','S', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('3000','PATRIMONIO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('4001','IMPUESTOS OPERACIONALES','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('4002','IMPUESTOS NO OPERACIONALES DIFERENTES DE INTERESES Y RENDIMIENTOS FINANCIEROS','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('4003','INGRESOS POR INTERESES Y RENDIMIENTOS FINANCIEROS','S', 'S', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('4010','INGRESOS DE CONSORCIOS Y UNIONES TEMPORALES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('4040','INGRESOS A TRAVES DE CONTRATOS DE MANDATO O DE ADMINISTRACION DELEGADA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('4050','INGRESOS EN CONTRATOS DE EXPLORACION Y EXPLOTACION MINERA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('4100','INGRESOS OPERACIONALES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('4200','OTROS INGRESOS NO OPERACIONALES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5001','SALARIOS Y DEMAS PAGOS LABORALES','S', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5002','HONORARIOS','S', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5003','COMISIONES','S', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5004','SERVICIOS','S', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5005','ARRENDAMIENTOS','S', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5006','INTERESES Y RENDIMIENTOS FINANCIEROS','S', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5007','COMPRA DE ACTIVOS MOVILES','S', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5008','COMPRA DE ACTIVOS FIJOS','S', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5009','CARGOS DIFERIDOS O GASTOS PAGADOS POR ANTICIPADO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5010','APORTES PARAFISCALES SENA, BIENESTAR FAMILIAR Y CAJAS DE COMPENSACION','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5011','APORTES PARAFISCALES EPS, ISS Y ARP','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5012','APORTE  OBLIGATORIO DE PENSIONES AL ISS Y A FONDO DE PENSIONES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5013','DONACIONES EN DINERO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5014','DONACIONES EN OTROS ACTIVOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5015','IMPUESTOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5016','OTROS COSTOS Y DEDUCCIONES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5017','IMPORTE DE SINIESTROS PAGADOS O ABONADOS EN CUENTA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5018','IMPORTE DE PRIMAS DE REASEGUROS PAGADOS O ABONADOS EN CUENTA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5100','GASTOS OPERACIONALES DE ADMINISTRACION','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5200','GASTOS OPERACIONALES DE VENTAS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5300','OTROS EGRESOS NO OPERACIONALES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5301','UTILIDAD ANTES DE IMPUESTO DE RENTA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5302','INTERES MINORITARIO DE RESULTADOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5304','UTILIDAD NETA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5305','IMPUESTO DE RENTA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('5306','PERDIDA NETA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('6000','COSTO DE VENTAS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('8001','INGRESOS NO CONSTITUTIVOS - DIVIDENDOS Y PARTICIPACIONES','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('8002','INGRESOS NO CONSTITUTIVOS-RENDIMIENTOS FINANCIEROS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('8003','OTROS INGRESOS NO CONSTITUTIVOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('8101','RENTAS HOTELERAS EXENTAS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('8102','RENTAS EXENTAS POR LEY PAEZ','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('8103','RENTAS EXENTAS EJE CAFETERO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('8206','CARGOS DIFERIDOS Y/O GASTOS PAGADOS POR ANTICIPADO','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('8301','POR REFORESTACION','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('8302','IMPUESTO A LAS VENTAS EN LA IMPORTACION DE MAQUINARIA PESADA','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('8303','IMPUESTOS PAGADOS EN EL EXTERIOR','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('8304','OTROS IMPUESTOS TRIBUTARIOS','N', 'N', 0)
go

INSERT INTO CONCEPTOS_ME(CONCEPTO,DESCRIPCION,CUANTIAS_MENORES,TRANSACCIONES_EXTERIOR,TOPE) VALUES('SC','SIN CONCEPTO','N', 'N', 0)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1001','PAGOS O ABONOS EN CUENTA',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1003','RETENCIONES EN LA FUENTE QUE LE PRACTICARON',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1004','DESCUENTOS TRIBUTARIOS',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1005','IMPUESTO A LAS VENTAS POR PAGAR (DESCONTABLE)',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1006','IMPUESTO A LAS VENTAS POR PAGAR (GENERADO)',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1007','INGRESOS RECIBIDOS',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1008','SALDO DE CUENTAS POR COBRAR AL 31 DE DICIEMBRE',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1009','SALDO DE CUENTAS POR PAGAR AL 31 DE DICIEMBRE',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1010','INFORMACION DE SOCIOS Y ACCIONISTAS.',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1011','INFORMACION DE LAS DECLARACIONES TRIBUTARIAS',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1012','INFORMACION DE DECLARACIONES TRIBUTARIAS, ACCIONES Y APORTES E INVERSIONES EN BONOS, CERTIFICADOS, TITULOS Y DEMAS INVERSIONES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1013','INFORMACION DE LOS FIDEICOMISOS QUE ADMINISTRAN',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1014','PAGOS O ABONOS EN CUENTA EFECTUADOS CON CARGO A LOS PATRIMONIOS AUTONOMOS',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1016','PAGOS O ABONOS EN CUENTA EFECTUADOS EN CONTRATOS DE MANDATO O DE ADMINISTRACION DELEGADA',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1017','INGRESOS RECIBIDOS POR CONTRATOS DE MANDATO O DE ADMINISTRACION DELEGADA',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1018','INFORMACION DE SALDOS DE CUENTAS POR COBRAR AL 31 DE DICIEMBRE EN CONTRATOS DE MANDATO O ADMINISTRACION DELEGADA',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1019','MOVIMIENTO EN CUENTA CORRIENTE Y/O AHORRO',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12800)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1020','INFORMACION DE INVERSIONES EN CDT',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12800)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1021','INVERSIONES EN FONDOS DE VALORES, FONDOS DE INVERSION, FONDO MUTUOS DE INVERSION',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12800)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1022','AHORRO VOLUNTARIO EN FONDOS DE PENSIONES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12800)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1023','CONSUMOS CON TARJETAS DE CREDITO',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12800)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1024','VENTAS CON TARJETAS DE CREDITO',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12800)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1025','DIFERENCIAS CONTABLES Y FISCALES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12800)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1026','PRESTAMOS BANCARIOS OTORGADOS.',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12800)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1027','INFORMACION DE SALDOS DE CUENTAS POR PAGAR AL 31 DE DICIEMBRE EN CONTRATO DE MANDATO O ADMINISTRACION DELEGADA',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1028','PERSONAS FALLECIDAS',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12800)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1032','INFORMACION DE ENAJENACIONES DE BIENES Y DERECHOS A TRAVES DE NOTARIAS',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12804)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1034','INFORMACION DE ESTADOS FINANCIEROS CONSOLIDADOS-GRUPOS ECONOMICOS',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12806)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1035','IDENTIFICACION SUBORDINADAS NACIONALES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12806)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1036','IDENTIFICACION SUBORDINADAS DEL EXTERIOR',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12806)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1037','ELABORACION DE FACTURACION POR LITOGRAFOS Y TIPOGRAFOS',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12805)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1038','INFORMACION DE LAS SOCIEDADES CREADAS',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12801)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1039','SOCIEDADES LIQUIDADAS',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12801)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1041','INFORMACION DE BOLSA DE VALORES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12802)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1042','INFORMACION DE COMISIONISTAS DE BOLSAS',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12802)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1043','INFORMACION DE PAGOS O ABONOS EN CUENTA A TRAVES DE CONSORCIOS Y UNIONES TEMPORALES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1045','INFORMACION DE INGRESOS RECIBIDOS POR CONSORCIOS Y UNIONES TEMPORALES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1046','INFORMACION DE PAGOS O ABONOS EN CUENTA DE LOS CONTRATOS DE ASOCIACION PARA EXPLORACION Y EXPLOTACION MINERA',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1048','INFORMACION DE INGRESOS RECIBIDOS DE LOS CONTRATOS DE ASOCIACION PARA EXPLORACION Y EXPLOTACION MINERA',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1049','IMPUESTO A LAS VENTAS POR PAGAR (DESCONTABLE) EN CONTRATOS DE ASOCIACION PARA EXPLORACION Y EXPLOTACION MINERA',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1050','IMPUESTO A LAS VENTAS POR PAGAR (GENERADO) EN CONTRATOS DE ASOCIACION PARA EXPLORACION Y EXPLOTACION MINERA',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1051','SALDOS DE CUENTAS POR COBRAR AL 31 DE DICIEMBRE EN CONTRATOS DE ASOCIACION PARA EXPLORACION Y EXPLOTACION MINERA.',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1052','SALDOS DE CUENTAS POR PAGAR AL 31 DE DICIEMBRE EN CONTRATOS DE ASOCIACION PARA EXPLORACION Y EXPLOTACION MINERA.',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1054','INFORMACION DEL IMPUESTO A LAS VENTAS POR PAGAR (DESCONTABLE) EN CONTRATOS DE MANDATO O DE ADMINISTRACION DELEGADA',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1055','IMPUESTO A LAS VENTAS POR PAGAR (GENERADO) EN CONTRATOS DE MANDATO O DE ADMINISTRACION DELEGADA',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1056','PAGOS O ABONOS EN CUENTA POR SECRETARIOS GENERALES QUE ADMINISTRAN RECURSOS DEL TESORO',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12807)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1159','INFORMACION DE CONVENIOS DE COOPERACION CON ORGANISMOS INTERNACIONALES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',12808)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1585','IMPUESTO A LAS VENTAS POR PAGAR (DESCONTABLE) EN CONSORCIOS Y UNIONES TEMPORALES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',11429)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1586','IMPUESTO A LAS VENTAS POR PAGAR (GNERADO) EN CONSORCIOS Y UNIONES TEMPORALES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',11429)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1587','SALDO DE CUENTAS POR COBRAR AL 31 DE DICIEMBRE EN CONSORCIO O UNIONES TEMPORALES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',11429)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1588','SALDO DE CUENTAS POR PAGAR AL 31 DE DICIEMBRE EN CONSORCIO O UNIONES TEMPORALES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',11429)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('1647','INFORMACIÓN DE INGRESOS RECIBIDOS PARA TERCEROS',0,'$$PATHERP$$\MediosElectronicos\Esquemas',11429)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('2276','INGRESOS Y RETENCIONES PARA PERSONAS NATURALES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',68)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('2275','INGRESOS NO CONSTITUTIVOS DE RENTA NI GANANCIA OCASIONAL',0,'$$PATHERP$$\MediosElectronicos\Esquemas',68)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('2278','COMPRA DE BONOS ELECTRONICOS O PAPEL DE SERVICIO, CHEQUES, O VALES PARA EL BENEFICIO DE LOS TRABAJADORES',0,'$$PATHERP$$\MediosElectronicos\Esquemas',68)
go

INSERT INTO FORMATOS_ME(FORMATO,DESCRIPCION,TOPE,RUTA_ESQUEMA,RESOLUCION) VALUES('2280','EMPLEADORES QUE OCUPEN TRABAJADORAS MUJERES VICTIMAS DE LA VIOLENCIA COMPROBADA',0,'$$PATHERP$$\MediosElectronicos\Esquemas',68)
go
