CREATE TABLE CONCEPTOS_ME (
	CONCEPTO 		VARCHAR(4) 	NOT NULL,
	DESCRIPCION 		VARCHAR(200) 	NULL,
	CUANTIAS_MENORES 	VARCHAR(1) 	NOT NULL DEFAULT('N'),
	TRANSACCIONES_EXTERIOR 	VARCHAR (1) 	NOT NULL DEFAULT('N'),
	TOPE 			decimal (28,0) 	NOT NULL DEFAULT(0)  
)
go


ALTER TABLE CONCEPTOS_ME
          ADD CONSTRAINT XPKCONCEPTOS_ME PRIMARY KEY (CONCEPTO)
go



CREATE TABLE FORMATO_CONCEPTO_ME (
	FORMATO 		VARCHAR(4) 	NOT NULL,
	CONCEPTO 		VARCHAR(4) 	NOT NULL  
)
go

ALTER TABLE FORMATO_CONCEPTO_ME
          ADD CONSTRAINT XPKFORMATCONCEP_ME PRIMARY KEY (FORMATO, CONCEPTO)
go




CREATE TABLE FORMATOS_ME (
	FORMATO 		VARCHAR (4) 	NOT NULL,
	DESCRIPCION 		VARCHAR (200) 	NULL,
	TOPE 			decimal (28,0) 	NOT NULL DEFAULT(0) ,
	RUTA_ESQUEMA 		VARCHAR (200) 	NULL,
	RESOLUCION 		VARCHAR (10) 	NULL 
)
go

ALTER TABLE FORMATOS_ME
          ADD CONSTRAINT XPKFORMATOS_ME PRIMARY KEY (FORMATO)
go



CREATE TABLE ME_PREVIA_MEDIO
(
	FORMATO 		VARCHAR(4) 	NULL,
	CONCEPTO 		VARCHAR(4) 	NULL,
	VALOR_A_MOSTRAR 	VARCHAR(10) 	NULL,
	TIPO_DOCUMENTO 		VARCHAR(2) 	NULL,
	NUMERO_DOC_NIT 		VARCHAR(20) 	NULL,
	DIGITO_VERIFICADOR 	VARCHAR(10) 	NULL,
	PRIMER_APELLIDO 	VARCHAR(60) 	NULL,
	SEGUNDO_APELLIDO 	VARCHAR(60) 	NULL,
	PRIMER_NOMBRE 		VARCHAR(60) 	NULL,
	SEGUNDO_NOMBRE 		VARCHAR(60) 	NULL,
	RAZON_SOCIAL 		VARCHAR(150) 	NULL,
	DIRECCION 		VARCHAR(3000) 	NULL,
	DEPARTAMENTO 		VARCHAR(2) 	NULL,
	MUNICIPIO 		VARCHAR(12) 	NULL,
	PAIS 			VARCHAR(3) 	NULL,
	EXTERIOR 		VARCHAR(1) 	NULL,
	FECHA 			DATETIME 	NULL,
	TIPO_MOVIMIENTO 	VARCHAR(1) 	NULL,
	TOPE_FORMATO 		DECIMAL(28,8) 	NULL,
	TOPE_CONCEPTO 		DECIMAL(28,8) 	NULL,
	CUANTIAS_MENORES 	VARCHAR(1) 	NULL,
	TRANSACCIONES_EXTERIOR 	VARCHAR(1) 	NULL,
	CUENTA_CONTABLE 	VARCHAR(25) 	NULL,
	ES_CUENTA_DEVOLUCIONES 	VARCHAR(1) 	NULL,
	SALDO_INICIAL 		DECIMAL(28,8) 	NULL,
	SALDO_FINAL 		DECIMAL(28,8) 	NULL,
	VALOR 			DECIMAL(28,8) 	NULL,
	VALOR_BASE 		DECIMAL(28,8) 	NULL,
	NIT 			VARCHAR(20) 	NULL,
	CENTRO_COSTO 		VARCHAR(25) 	NULL,
	FECHA_INICIO 		DATETIME 	NULL,
	FECHA_FIN 		DATETIME 	NULL,
	EMAIL 			VARCHAR(100) 	NULL,
	TIPO_MEDIDA 		INT 		NULL,
	CARGO_CONTRATO 		VARCHAR(40) 	NULL,
	EDAD 			INT 		NULL,
	NIVEL_EDUCATIVO 	INT 		NULL,
	TIPO_IMPUESTO 		VARCHAR(4) 	NULL
)
go



CREATE TABLE MEDIOS_ELECTRONICOS (
	FORMATO 		VARCHAR(4) 	NOT NULL ,
	CONCEPTO 		VARCHAR(4) 	NOT NULL ,
	CUENTA_CONTABLE_INI 	VARCHAR(25) 	NOT NULL ,
	CUENTA_CONTABLE_FIN 	VARCHAR(25) 	NOT NULL ,
	TIPO_MOVIMIENTO 	VARCHAR(1) 	NOT NULL DEFAULT ('S') ,
	CAMBIO_NATURALEZA 	VARCHAR(1) 	NOT NULL DEFAULT ('N') ,
	ES_CUENTA_DEVOLUCIONES 	VARCHAR(1) 	NOT NULL DEFAULT ('N') ,
	PAGOS_ABONOS_CTAS 	VARCHAR(1) 	NOT NULL DEFAULT ('N') ,
	VALOR_A_MOSTRAR 	VARCHAR(10) 	NOT NULL DEFAULT ('ND') ,
	TOPE_FORMATO 		DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	TOPE_CONCEPTO 		DECIMAL(28,8) 	NOT NULL DEFAULT 0,
	TIPO_IMPUESTO 		VARCHAR(4) 	NULL,
	TIPO_CONTABILIDAD VARCHAR(1) NOT NULL DEFAULT 'F'
)
go

ALTER TABLE MEDIOS_ELECTRONICOS
	ADD CONSTRAINT XPKMEDIOS_ELECTRONICOS 
		PRIMARY KEY (FORMATO, CONCEPTO, CUENTA_CONTABLE_INI, CUENTA_CONTABLE_FIN, VALOR_A_MOSTRAR, TIPO_CONTABILIDAD)	
go          




CREATE TABLE NIT_ME (
	NIT                  	VARCHAR(20) 	NOT NULL,
	RAZON_SOCIAL         	VARCHAR(450) 	NOT NULL,
	ALIAS                	VARCHAR(80) 	NULL,
	NOTAS                	TEXT 		NULL,
	TIPO                 	VARCHAR(25) 	NOT NULL DEFAULT ('ND'),
	DIGITO_VERIFICADOR   	VARCHAR(10) 	NULL,
	ORIGEN			VARCHAR(1)  	NOT NULL DEFAULT('O'),
	NUMERO_DOC_NIT		VARCHAR(20) 	NULL,
	SUCURSAL		VARCHAR(20) 	NULL,
	PRIMER_NOMBRE		VARCHAR(60) 	NULL,
	SEGUNDO_NOMBRE		VARCHAR(60) 	NULL,
	PRIMER_APELLIDO		VARCHAR(60) 	NULL,
	SEGUNDO_APELLIDO	VARCHAR(60) 	NULL,
	TIPO_DOCUMENTO		VARCHAR(2) 	NULL,
	CLASE_DOCUMENTO		VARCHAR(5) 	NULL,
	DEPARTAMENTO		VARCHAR(2) 	NULL,
	MUNICIPIO		VARCHAR(3) 	NULL,
	PAIS			VARCHAR(4) 	NULL,
	EXTERIOR		VARCHAR(1) 	NULL,
	DETALLE_DIRECCION	INT 		NULL,
	DIRECCION		VARCHAR(3000) 	NULL		
 )
go


ALTER TABLE NIT_ME
          ADD CONSTRAINT XPKNIT_ME PRIMARY KEY (NIT)
go