ALTER TABLE ARTICULO_SERIE_POS
	ADD CONSTRAINT ARTSERPOSDOCPOSLIN
		FOREIGN KEY (DOCUMENTO, TIPO, CAJA, LINEA)
			REFERENCES DOC_POS_LINEA(DOCUMENTO, TIPO, CAJA, LINEA)
				ON DELETE CASCADE
go
ALTER TABLE ARTICULO_SERIE_POS
	ADD CONSTRAINT BODEGAARTSERIEPOS
		FOREIGN KEY (BODEGA)
			REFERENCES BODEGA(BODEGA)
go			
ALTER TABLE ASIENTOS_DOC_POS
	ADD CONSTRAINT ASIDOCPOSDOCPOS
		FOREIGN KEY (DOCUMENTO,TIPO, CAJA)
			REFERENCES DOCUMENTO_POS(DOCUMENTO,TIPO, CAJA)
				ON DELETE CASCADE
go
ALTER TABLE AUXILIAR_POS
	ADD CONSTRAINT AUXPOSDOCPOS
		FOREIGN KEY (DOCUMENTO, TIPO, CAJA)
			REFERENCES DOCUMENTO_POS(DOCUMENTO,TIPO, CAJA)
go
ALTER TABLE AUXILIAR_POS
       ADD CONSTRAINT AUXPOSAPLDOCPOS
		FOREIGN KEY (DOCUM_APLICA, TIPO_APLICA, CAJA_DOCUM_APLICA)
			REFERENCES DOCUMENTO_POS(DOCUMENTO,TIPO, CAJA)
				ON DELETE CASCADE
go
ALTER TABLE AUDIT_CUPON
	ADD CONSTRAINT AUDITCUPONCUPON
		FOREIGN KEY (CUPON)
            		REFERENCES CUPON(CUPON)
go
ALTER TABLE BITACORA
	ADD CONSTRAINT BITCAJPOS
		FOREIGN KEY (CAJA)
			REFERENCES CAJA_POS(CAJA)
go
ALTER TABLE BITACORA
	ADD CONSTRAINT BITDOCPOS
		FOREIGN KEY (DOCUMENTO, TIPO, CAJA_DOC)
			REFERENCES DOCUMENTO_POS(DOCUMENTO,TIPO, CAJA)
go
ALTER TABLE BITACORA
	ADD CONSTRAINT BITUSU
		FOREIGN KEY (SUPERVISOR)
			REFERENCES ERPADMIN.USUARIO
go
ALTER TABLE CAJA_POS
	ADD CONSTRAINT CAJPOSBOD
		FOREIGN KEY (BODEGA)
			REFERENCES BODEGA(BODEGA)
go
ALTER TABLE CAJA_POS
	ADD CONSTRAINT CAJPOSCENCOS
		FOREIGN KEY (CENTRO_COSTO)
			REFERENCES CENTRO_COSTO(CENTRO_COSTO)
go
ALTER TABLE CAJA_POS
	ADD CONSTRAINT CAJPOSGRU
		FOREIGN KEY (SUCURSAL)
			REFERENCES GRUPO(GRUPO)
go
ALTER TABLE CONFIG_CAJA
	ADD CONSTRAINT CAJACONFIGCAJAPOS
		FOREIGN KEY (CAJA)
			REFERENCES CAJA_POS(CAJA)
go
ALTER TABLE CONSEC_CAJA_POS
	ADD CONSTRAINT CONSCAJACAJAPOS 
		FOREIGN KEY (CAJA) 
			REFERENCES CAJA_POS (CAJA)
go
ALTER TABLE CONSEC_CAJA_POS
	ADD CONSTRAINT CONSECCAJAPOSRESOL
		FOREIGN KEY (RESOLUCION, CAJA)
			REFERENCES RESOLUCION_POS (RESOLUCION, CAJA)
go
ALTER TABLE CAJERO
	ADD CONSTRAINT CAJGRU
		FOREIGN KEY (GRUPO)
			REFERENCES GRUPO(GRUPO)
go
ALTER TABLE CAJERO
	ADD CONSTRAINT CAJUSU
		FOREIGN KEY (CAJERO)
			REFERENCES ERPADMIN.USUARIO
go
ALTER TABLE CAJERO
	ADD CONSTRAINT CAJVEN
		FOREIGN KEY (VENDEDOR)
			REFERENCES VENDEDOR(VENDEDOR)
go
ALTER TABLE CIERRE_DESG_TARJ
	ADD CONSTRAINT CIEDESTARCIEPOS
		FOREIGN KEY (NUM_CIERRE, CAJERO, CAJA)
			REFERENCES CIERRE_POS(NUM_CIERRE, CAJERO, CAJA)
				ON DELETE CASCADE
go
ALTER TABLE CIERRE_DET_PAGO
	ADD CONSTRAINT CIEDETPAGCIEPOS
		FOREIGN KEY (NUM_CIERRE, CAJERO, CAJA)
			REFERENCES CIERRE_POS(NUM_CIERRE, CAJERO, CAJA)
			ON DELETE CASCADE
go
ALTER TABLE CIERRE_INFO_TARJ
	ADD CONSTRAINT CIERINFTARJTAR
		FOREIGN KEY (COD_TARJETA)
			REFERENCES TIPO_TARJETA(TIPO_TARJETA)
go
ALTER TABLE CIERRE_INFO_TARJ
	ADD CONSTRAINT CIERRINFOTARJCIERCAJA
		FOREIGN KEY (NUM_CIERRE_CAJA, CAJA)
			REFERENCES CIERRE_CAJA(NUM_CIERRE_CAJA, CAJA)
go
ALTER TABLE CIERRE_POS
	ADD CONSTRAINT CIEPOSCAJPOS
		FOREIGN KEY (CAJA)
			REFERENCES CAJA_POS(CAJA)
go
ALTER TABLE CIERRE_POS
	ADD CONSTRAINT CIEPOSCAJ
		FOREIGN KEY (CAJERO)
			REFERENCES CAJERO(CAJERO)
go
ALTER TABLE CIERRE_POS
	ADD CONSTRAINT NUMCIERRECAJA
		FOREIGN KEY (NUM_CIERRE_CAJA, CAJA)
			REFERENCES CIERRE_CAJA(NUM_CIERRE_CAJA, CAJA)
go
ALTER TABLE CIERRE_TIENDA
	ADD CONSTRAINT CIETIEGRU
		FOREIGN KEY (GRUPO)
			REFERENCES GRUPO(GRUPO)
go
ALTER TABLE CLIENTE_FORMA_PAGO
	ADD CONSTRAINT CLIFORPAGCLI
		FOREIGN KEY (CLIENTE)
			REFERENCES CLIENTE(CLIENTE)
go
ALTER TABLE CLIENTE_FORMA_PAGO
	ADD CONSTRAINT CLIFORPAGENTFIN
		FOREIGN KEY (ENTIDAD_FINANCIERA)
			REFERENCES ENTIDAD_FINANCIERA(ENTIDAD_FINANCIERA)
go
ALTER TABLE CLIENTE_FORMA_PAGO
	ADD CONSTRAINT CLIFORPAGFORPAG
		FOREIGN KEY (FORMA_PAGO)
			REFERENCES FORMA_PAGO(FORMA_PAGO)
go
ALTER TABLE CLIENTE_POS
	ADD CONSTRAINT CLIPOSCLI
		FOREIGN KEY (CLIENTE)
			REFERENCES CLIENTE(CLIENTE)
				ON DELETE CASCADE
go
ALTER TABLE CLIENTE_POS
	ADD CONSTRAINT CLIPOSPAI
		FOREIGN KEY (PAIS_EMBAJADA)
			REFERENCES PAIS(PAIS)
go
ALTER TABLE COBRO_POS
	ADD CONSTRAINT COBPOSGRU
		FOREIGN KEY (TIENDA)
			REFERENCES GRUPO(GRUPO)
go

ALTER TABLE COMISION_ARTICULO
	ADD CONSTRAINT COMARTREGCOMISION
		FOREIGN KEY (COMISION)
			REFERENCES REGLA_COMISION(COMISION)
go			
			
ALTER TABLE COMISION_ARTICULO
	ADD CONSTRAINT COMARTARTICULO
		FOREIGN KEY (ARTICULO)
			REFERENCES ARTICULO(ARTICULO)
go	
			
ALTER TABLE COMISION_EXCEPCION
	ADD CONSTRAINT COMEXCEPREGCOMISION
		FOREIGN KEY (COMISION)
			REFERENCES REGLA_COMISION(COMISION)
go
			
ALTER TABLE COMISION_EXCEPCION
	ADD CONSTRAINT COMEXCEPARTICULO
		FOREIGN KEY (ARTICULO)
			REFERENCES ARTICULO(ARTICULO)
go

ALTER TABLE CONEXION
	ADD CONSTRAINT CONCAJPOS
		FOREIGN KEY (CAJA)
			REFERENCES CAJA_POS(CAJA)
go


ALTER TABLE CONEXION
	ADD CONSTRAINT CONCAJ
		FOREIGN KEY (CAJERO)
			REFERENCES CAJERO(CAJERO)
go


ALTER TABLE DEPOSITO_POS
	ADD CONSTRAINT DEPPOSCUEBAN
		FOREIGN KEY (CUENTA_BANCO)
			REFERENCES CUENTA_BANCARIA(CUENTA_BANCO)
go

ALTER TABLE DEPOSITO_POS
	ADD CONSTRAINT DEPPOSGRU
		FOREIGN KEY (TIENDA)
			REFERENCES GRUPO(GRUPO)
go

ALTER TABLE DET_REG_BILLETE
	ADD CONSTRAINT DETREGBILLINFOREGBILL
		FOREIGN KEY (IDENTIFICACION, PAGO, DOCUMENTO, TIPO, CAJA)
			REFERENCES INFO_REG_BILLETE(IDENTIFICACION, PAGO, DOCUMENTO, TIPO, CAJA)
go

ALTER TABLE DETALLE_PERFIL_CLI
	ADD CONSTRAINT DETPERCLIPERCLI
		FOREIGN KEY (PERFIL)
			REFERENCES PERFIL_CLIENTE(PERFIL)
go

ALTER TABLE DISTRIBUCION_ARTICULO
	ADD CONSTRAINT DISTARTARTICULO
		FOREIGN KEY (ARTICULO)
			REFERENCES ARTICULO(ARTICULO)
go
			
ALTER TABLE DISTRIBUCION_ARTICULO
	ADD CONSTRAINT DISTARTCUENCONT
		FOREIGN KEY (CUENTA_CONTABLE)
			REFERENCES CUENTA_CONTABLE(CUENTA_CONTABLE)
go
			
ALTER TABLE DISTRIBUCION_ARTICULO
	ADD CONSTRAINT DISTARTCENCOSTO
		FOREIGN KEY (CENTRO_COSTO)
			REFERENCES CENTRO_COSTO(CENTRO_COSTO)
go



ALTER TABLE DOCUMENTO_EN_ESPERA
	ADD CONSTRAINT DOCESPERACAJA
		FOREIGN KEY (CAJA)
			REFERENCES CAJA_POS(CAJA)
go


ALTER TABLE DOC_ESPERA_SERIE_POS
	ADD CONSTRAINT DOCESPSERIEDOCLINESPERA
		FOREIGN KEY (LINEA, DOCUMENTO, CAJA, TIPO)
			REFERENCES DOCUMENTO_LINEA_ESPERA(LINEA, DOCUMENTO, CAJA, TIPO)
go


ALTER TABLE DOC_POS_RETENCION
	ADD CONSTRAINT DOCPOSRETDOCPOS
		FOREIGN KEY (DOCUMENTO, TIPO, CAJA)
			REFERENCES DOCUMENTO_POS(DOCUMENTO, TIPO, CAJA)
				ON DELETE CASCADE
go


ALTER TABLE MENSAJERO
	ADD CONSTRAINT GRUPOMENSAJERO
		FOREIGN KEY (TIENDA)
			REFERENCES GRUPO(GRUPO)
go


ALTER TABLE CLIENTE_EXPR_ENTR
	ADD CONSTRAINT CLIEXPRCLIEXPRENTR
		FOREIGN KEY (CLIENTE_EXP)
			REFERENCES CLIENTE_EXPRESS(CLIENTE_EXP)
			ON DELETE CASCADE
go

ALTER TABLE DOCUMENTO_LINEA_ESPERA
	ADD CONSTRAINT DOCLINESPDOCESPERA
		FOREIGN KEY (DOCUMENTO, CAJA, TIPO)
			REFERENCES DOCUMENTO_EN_ESPERA(DOCUMENTO, CAJA, TIPO)
go


ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSCAJPOS
		FOREIGN KEY (CAJA)
			REFERENCES CAJA_POS(CAJA)
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSCOBCAJPOS
		FOREIGN KEY (CAJA_COBRO)
			REFERENCES CAJA_POS(CAJA)
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSCAJ
		FOREIGN KEY (CAJERO)
			REFERENCES CAJERO(CAJERO)
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSCLI
		FOREIGN KEY (CLIENTE)
			REFERENCES CLIENTE(CLIENTE)
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSCONPAG
		FOREIGN KEY (CONDICION_PAGO_APA)
			REFERENCES CONDICION_PAGO(CONDICION_PAGO)
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSPERCLI
		FOREIGN KEY (PERFIL)
			REFERENCES PERFIL_CLIENTE(PERFIL)
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSVEN
		FOREIGN KEY (VENDEDOR)
			REFERENCES VENDEDOR(VENDEDOR)
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSANUUSU
		FOREIGN KEY (USUARIO_ANULACION)
			REFERENCES ERPADMIN.USUARIO
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSAPLUSU
		FOREIGN KEY (USUARIO_APLICACION)
			REFERENCES ERPADMIN.USUARIO
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSULTIMPUSU
		FOREIGN KEY (USUARIO_ULT_IMPRE)
			REFERENCES ERPADMIN.USUARIO
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSCONSCAJA
		FOREIGN KEY (CORRELATIVO, CAJA) 
			REFERENCES CONSEC_CAJA_POS (CODIGO, CAJA)
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT MENSAJERODOCPOS
		FOREIGN KEY (MENSAJERO) 
			REFERENCES MENSAJERO(MENSAJERO) 
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT CLIEEXPRDOCPOS
		FOREIGN KEY (CLIENTE_EXPRESS) 
			REFERENCES CLIENTE_EXPRESS(CLIENTE_EXP) 
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT MOTCANCEXPRDOCPOS
		FOREIGN KEY (MOTIV_CANCELA_EXPR) 
			REFERENCES MOTIVO_CANCEL_EXPR(CODIGO) 
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCUMEPOSRESOL
		FOREIGN KEY (RESOLUCION,CAJA)
			REFERENCES RESOLUCION_POS(RESOLUCION, CAJA)
go
ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT CLASEDOCPOS
		FOREIGN KEY (COD_CLASE_DOC)
			REFERENCES CLASE_DOC_POS(CODIGO)
go


ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSNCFCAJA
		FOREIGN KEY (CAJA, PREFIJO)
			REFERENCES NCF_CAJA_POS(CAJA, PREFIJO)
go


ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSPEDIDO
       		FOREIGN KEY (PEDIDO_AUTORIZADO)
		      REFERENCES PEDIDO
go		      


ALTER TABLE DOCUMENTO_POS 
	ADD CONSTRAINT DOCPOSNIT 
		FOREIGN KEY(NIT_CLIENTE) 
			REFERENCES NIT (NIT)
go			


ALTER TABLE DOC_POS_LINEA
	ADD CONSTRAINT DOCPOSLINART
		FOREIGN KEY (ARTICULO)
			REFERENCES ARTICULO(ARTICULO)
go
ALTER TABLE DOC_POS_LINEA
	ADD CONSTRAINT DOCPOSLINDOCPOS
		FOREIGN KEY (DOCUMENTO, TIPO, CAJA)
			REFERENCES DOCUMENTO_POS(DOCUMENTO, TIPO, CAJA)
				ON DELETE CASCADE
go
ALTER TABLE DOC_POS_LINEA
	ADD CONSTRAINT DOCPOSLINLOT
		FOREIGN KEY (ARTICULO,LOTE)
			REFERENCES LOTE(ARTICULO,LOTE)
go
ALTER TABLE DOC_POS_LINEA
	ADD CONSTRAINT BODEGADOCPOSLINEA
		FOREIGN KEY (BODEGA)
			REFERENCES BODEGA(BODEGA)
go
ALTER TABLE DOC_POS_LINEA
        ADD CONSTRAINT LOCALIZDOCPOSLINEA
        	FOREIGN KEY (BODEGA, LOCALIZACION)
                	REFERENCES LOCALIZACION(BODEGA, LOCALIZACION)
go
ALTER TABLE ERROR_CAJA
	ADD CONSTRAINT ERRCAJCAJPOS
		FOREIGN KEY (CAJA)
			REFERENCES CAJA_POS(CAJA)
go
ALTER TABLE ERROR_CAJA
	ADD CONSTRAINT ERRCAJCAJ
		FOREIGN KEY (CAJERO)
			REFERENCES CAJERO(CAJERO)
go
ALTER TABLE FACTURA_DEVUELTA
	ADD CONSTRAINT FACDEVDOCPOS
		FOREIGN KEY (DEV_DOCUMENTO, DEV_TIPO, DEV_CAJA)
			REFERENCES DOCUMENTO_POS(DOCUMENTO, TIPO, CAJA)
go
ALTER TABLE FORMA_PAGO
	ADD CONSTRAINT FORPAGCENCOS
		FOREIGN KEY (CENTRO_COSTO)
			REFERENCES CENTRO_COSTO(CENTRO_COSTO)
go
ALTER TABLE FORMA_PAGO
	ADD CONSTRAINT FORPAGCUECON
		FOREIGN KEY (CUENTA_CONTABLE)
			REFERENCES CUENTA_CONTABLE(CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSBOD
		FOREIGN KEY (BODEGA_CENTRAL)
			REFERENCES BODEGA(BODEGA)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSCATCLI
		FOREIGN KEY (CATEGORIA_CLIENTE)
			REFERENCES CATEGORIA_CLIENTE(CATEGORIA_CLIENTE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSABOCENCUE
		FOREIGN KEY (CTR_ABONOS, CTA_ABONOS)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSBONCENCUE
		FOREIGN KEY (CTR_BONO, CTA_BONO)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSCERCENCUE
		FOREIGN KEY (CTR_CERTIFICADO, CTA_CERTIFICADO)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSCEROBSCENCUE
		FOREIGN KEY (CTR_CERTIF_OBSEQUI, CTA_CERTIF_OBSEQUI)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSCERVENCENCUE
		FOREIGN KEY (CTR_CERTIF_VENCIDO, CTA_CERTIF_VENCIDO)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSCHECENCUE
		FOREIGN KEY (CTR_CHEQUE, CTA_CHEQUE)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSCIECRECENCUE
		FOREIGN KEY (CTR_CIERRE_CREDITO, CTA_CIERRE_CREDITO)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSCIEDEBCENCUE
		FOREIGN KEY (CTR_CIERRE_DEBITO, CTA_CIERRE_DEBITO)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSDEVDINCENCUE
		FOREIGN KEY (CTR_DEVOL_DINERO, CTA_DEVOL_DINERO)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSDIFEGRCENCUE
		FOREIGN KEY (CTR_DIFER_EGRESO, CTA_DIFER_EGRESO)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSDIFINGCENCUE
		FOREIGN KEY (CTR_DIFER_INGRESO, CTA_DIFER_INGRESO)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSEFEDOLCENCUE
		FOREIGN KEY (CTR_EFECTIVO_DOLAR, CTA_EFECTIVO_DOLAR)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSEFELOCCENCUE
		FOREIGN KEY (CTR_EFECTIVO_LOCAL, CTA_EFECTIVO_LOCAL)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSINVDESCENCUE
		FOREIGN KEY (CTR_INV_DESPACHAR, CTA_INV_DESPACHAR)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSNCVECCENCUE
		FOREIGN KEY (CTR_NC_VENCIDA, CTA_NC_VENCIDA)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSNCCENCUE
		FOREIGN KEY (CTR_NOTACREDITO, CTA_NOTACREDITO)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSOTRINGCENCUE
		FOREIGN KEY (CTR_OTROS_INGRESOS, CTA_OTROS_INGRESOS)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSVTAAPACENCUE
		FOREIGN KEY (CTR_VTA_APARTADO, CTA_VTA_APARTADO)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSAPACLI
		FOREIGN KEY (CLIENTE_APARTADO)
			REFERENCES CLIENTE(CLIENTE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSOMICLI
		FOREIGN KEY (CLIENTE_OMISION)
			REFERENCES CLIENTE(CLIENTE)
go
ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSCONPAG
		FOREIGN KEY (CONDICION_PAGO)
			REFERENCES CONDICION_PAGO(CONDICION_PAGO)
go


ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSVENAPACONPAG
		FOREIGN KEY (CONDPAG_VENC_APART)
			REFERENCES CONDICION_PAGO(CONDICION_PAGO)
go


ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSCONFA
		FOREIGN KEY (CONSECUTIVO_DEVOL)
			REFERENCES CONSECUTIVO_FA(CODIGO_CONSECUTIVO)
go


ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSNIVPRE
		FOREIGN KEY (NIVEL_PRECIO, MONEDA_NIVEL)
			REFERENCES NIVEL_PRECIO(NIVEL_PRECIO, MONEDA)
go


ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSPAQ
		FOREIGN KEY (PAQUETE)
			REFERENCES PAQUETE(PAQUETE)
go


ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSTIPASI
		FOREIGN KEY (TIPO_ASIENTO)
			REFERENCES TIPO_ASIENTO(TIPO_ASIENTO)
go


ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSCAJUSU
		FOREIGN KEY (GRUPO_CAJERO)
			REFERENCES ERPADMIN.USUARIO
go


ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT GLOPOSSUPUSU
		FOREIGN KEY (GRUPO_SUPERVISOR)
			REFERENCES ERPADMIN.USUARIO
go


ALTER TABLE GLOBALES_POS
	ADD CONSTRAINT FKGLOPOSTIENDAOFF
		FOREIGN KEY (TIENDA_OFF_LOCAL)
			REFERENCES TIENDA_OFFLINE(TIENDA_OFF)
go			


ALTER TABLE GRUPO
	ADD CONSTRAINT GRUCAD
		FOREIGN KEY (CADENA)
			REFERENCES CADENA(CADENA)
				ON DELETE CASCADE
go


ALTER TABLE GRUPO
	ADD CONSTRAINT GRUCONCI
		FOREIGN KEY (CONSECUTIVO_CI)
			REFERENCES CONSECUTIVO_CI(CONSECUTIVO)
go


ALTER TABLE GRUPO
	ADD CONSTRAINT GRUNIVPRE
		FOREIGN KEY (NIVEL_PRECIO, MONEDA_NIVEL)
			REFERENCES NIVEL_PRECIO(NIVEL_PRECIO, MONEDA)
				ON DELETE CASCADE
go

ALTER TABLE GRUPO
	ADD CONSTRAINT GRUPONCFCONSEC
		FOREIGN KEY (NCF_UNICO)
			REFERENCES NCF_CONSECUTIVO(PREFIJO)
go			

ALTER TABLE GRUPO
	ADD CONSTRAINT GRUPONCFCONSEC
		FOREIGN KEY (NCF_UNICO)
			REFERENCES NCF_CONSECUTIVO(PREFIJO)
go

ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSNCFCONSEC 
		FOREIGN KEY(PREFIJO) 
			REFERENCES NCF_CONSECUTIVO (PREFIJO)
go 

ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSNCFCAJA
		FOREIGN KEY (CAJA, PREFIJO)
			REFERENCES NCF_CAJA_POS(CAJA, PREFIJO)
go
			
			
ALTER TABLE GRUPO_CAJA
	ADD CONSTRAINT GRUCAJCAJPOS
		FOREIGN KEY (CAJA)
			REFERENCES CAJA_POS(CAJA)
				ON DELETE CASCADE
go


ALTER TABLE GRUPO_CAJA
	ADD CONSTRAINT GRUCAJGRU
		FOREIGN KEY (GRUPO)
			REFERENCES GRUPO(GRUPO)
go


ALTER TABLE HIST_MEMBRESIA_POS
	ADD CONSTRAINT  HISTMEMB_MEMBRESIA 
		FOREIGN KEY (MEMBRESIA) 
			REFERENCES MEMBRESIA_POS(MEMBRESIA)
go


ALTER TABLE HIST_MEMBRESIA_POS
	ADD CONSTRAINT  HISTMEMB_DOCPOS 
		FOREIGN KEY (DOCUMENTO,TIPO,CAJA) 
			REFERENCES DOCUMENTO_POS(DOCUMENTO,TIPO,CAJA)
go	



ALTER TABLE INCONSIST_INV_POS
	ADD CONSTRAINT INCINVPOSBOD
		FOREIGN KEY (BODEGA)
			REFERENCES BODEGA(BODEGA)
go


ALTER TABLE INCONSIST_INV_POS
	ADD CONSTRAINT INCINVPOSDOCPOS
		FOREIGN KEY (DOCUMENTO, TIPO, CAJA)
			REFERENCES DOCUMENTO_POS(DOCUMENTO, TIPO, CAJA)
go


ALTER TABLE INCONSISTENCIA_SINC_POS
	ADD CONSTRAINT INCOSINCGRUPO
		FOREIGN KEY (TIENDA)
			REFERENCES GRUPO(GRUPO)
go			


ALTER TABLE INFO_DOC_SEGURO
	ADD CONSTRAINT INFODOCSEGUROPAGPOS
		FOREIGN KEY (PAGO, DOCUMENTO, TIPO, CAJA)
			REFERENCES PAGO_POS(PAGO, DOCUMENTO, TIPO, CAJA)
go
			
			
ALTER TABLE INFO_DOC_SEGURO
	ADD CONSTRAINT DOCSEGUROAFILIADO
		FOREIGN KEY (AFILIADO, ASEGURADORA)
			REFERENCES AFILIADO(AFILIADO, ASEGURADORA)
go


ALTER TABLE INFO_REG_BILLETE
	ADD CONSTRAINT INFOREGBILLETEPAGPOS
		FOREIGN KEY (PAGO, DOCUMENTO, TIPO, CAJA)
			REFERENCES PAGO_POS(PAGO, DOCUMENTO, TIPO, CAJA)
go

ALTER TABLE MEMBRESIA_POS
	ADD CONSTRAINT  MEMBRESIA_CLIENTE 
		FOREIGN KEY (CLIENTE) 
			REFERENCES CLIENTE(CLIENTE) 
go


		

ALTER TABLE MEMBRESIA_POS
	ADD CONSTRAINT  MEMBR_EMIUSUARIO 
		FOREIGN KEY (USUARIO_EMISION) 
			REFERENCES ERPADMIN.USUARIO(USUARIO) 
go


		


ALTER TABLE MEMBRESIA_POS
	ADD CONSTRAINT  MEMBR_AUTOUSUARIO 
		FOREIGN KEY (USUARIO_AUTORIZA_ING) 
			REFERENCES ERPADMIN.USUARIO(USUARIO) 
go



ALTER TABLE MEMBRESIA_POS
	ADD CONSTRAINT  MEMBR_RENUSUARIO 
		FOREIGN KEY (USUARIO_RENOVACION) 
			REFERENCES ERPADMIN.USUARIO(USUARIO)  
go

		

ALTER TABLE MEMBRESIA_POS
	ADD CONSTRAINT  MEMBR_REPUSUARIO 
		FOREIGN KEY (USUARIO_REPOSICION) 
			REFERENCES ERPADMIN.USUARIO(USUARIO)  
go

		
		
ALTER TABLE MEMBRESIA_POS
	ADD CONSTRAINT  MEMBR_PAIS
		FOREIGN KEY (PAIS_ORIGEN) 
			REFERENCES PAIS(PAIS) 
go

		


ALTER TABLE MEMBRESIA_POS
	ADD CONSTRAINT  MEMBR_MEMBREPUESTA
		FOREIGN KEY (MEMBRESIA_REPUESTA) 
			REFERENCES MEMBRESIA_POS(MEMBRESIA) 
go

	
ALTER TABLE MONITOR_CATEGORIA
  ADD CONSTRAINT MONCONSMONCAT FOREIGN KEY (MONITOR_CATEGORIA)
    REFERENCES MONITOR_CATEGORIA(MONITOR_CATEGORIA)	
go	


ALTER TABLE MONITOR_COLUMNAS
  ADD CONSTRAINT MONCOLSMONCONS FOREIGN KEY (MONITOR_CONSULTA, MONITOR_CATEGORIA)
    REFERENCES MONITOR_CONSULTA(MONITOR_CONSULTA, MONITOR_CATEGORIA)
go


ALTER TABLE PAGO_POS
	ADD CONSTRAINT PAGPOSCONPAG
		FOREIGN KEY (CONDICION_PAGO)
			REFERENCES CONDICION_PAGO(CONDICION_PAGO)
go


ALTER TABLE PAGO_POS
	ADD CONSTRAINT PAGPOSDOCPOS
		FOREIGN KEY (DOCUMENTO, TIPO, CAJA)
			REFERENCES DOCUMENTO_POS(DOCUMENTO, TIPO, CAJA)
				ON DELETE CASCADE
go


ALTER TABLE PAGO_POS
	ADD CONSTRAINT PAGPOSENTFIN
		FOREIGN KEY (ENTIDAD_FINANCIERA)
			REFERENCES ENTIDAD_FINANCIERA(ENTIDAD_FINANCIERA)
go


ALTER TABLE PAGO_POS
	ADD CONSTRAINT PAGPOSFORPAG
		FOREIGN KEY (FORMA_PAGO)
			REFERENCES FORMA_PAGO(FORMA_PAGO)
go


ALTER TABLE PAGO_POS
	ADD CONSTRAINT PAGPOSTIPTAR
		FOREIGN KEY (TIPO_TARJETA, CLIENTE_LIQUIDADOR, TIPO_COBRO)
			REFERENCES TIPO_TARJETA_POS(TIPO_TARJETA, CLIENTE, TIPO_COBRO)
go


ALTER TABLE REGLA_COMISION
 	ADD CONSTRAINT REGCOMICLASIF1
 		FOREIGN KEY (CLASIFICACION_1)
 			REFERENCES CLASIFICACION(CLASIFICACION)
go
 			
ALTER TABLE REGLA_COMISION
 	ADD CONSTRAINT REGCOMICLASIF2
 		FOREIGN KEY (CLASIFICACION_2)
 			REFERENCES CLASIFICACION(CLASIFICACION)
go
 
ALTER TABLE REGLA_COMISION
 	ADD CONSTRAINT REGCOMICLASIF3
 		FOREIGN KEY (CLASIFICACION_3)
 			REFERENCES CLASIFICACION(CLASIFICACION)
go
 
ALTER TABLE REGLA_COMISION
 	ADD CONSTRAINT REGCOMICLASIF4
 		FOREIGN KEY (CLASIFICACION_4)
 			REFERENCES CLASIFICACION(CLASIFICACION)
go
 
ALTER TABLE REGLA_COMISION
 	ADD CONSTRAINT REGCOMICLASIF5
 		FOREIGN KEY (CLASIFICACION_5)
 			REFERENCES CLASIFICACION(CLASIFICACION)
go
 
ALTER TABLE REGLA_COMISION
 	ADD CONSTRAINT REGCOMICLASIF6
 		FOREIGN KEY (CLASIFICACION_6)
 			REFERENCES CLASIFICACION(CLASIFICACION)
go


ALTER TABLE TIENDA_OFF_GRUPO
	ADD CONSTRAINT GRUPOTIENDAOFFGRUPO
		FOREIGN KEY (GRUPO)
			REFERENCES GRUPO(GRUPO)
go


ALTER TABLE TIENDA_OFF_GRUPO
	ADD CONSTRAINT TIENDAOFFGRUPO
		FOREIGN KEY (TIENDA_OFF)
			REFERENCES TIENDA_OFFLINE(TIENDA_OFF)
go		


ALTER TABLE TIPO_TARJETA_CAJA
	ADD CONSTRAINT TARJCAJATAR
		FOREIGN KEY (TIPO_TARJETA)
			REFERENCES TIPO_TARJETA(TIPO_TARJETA)
go

ALTER TABLE TIPO_TARJETA_CAJA
	ADD CONSTRAINT TARJCAJACAJA
		FOREIGN KEY (CAJA)
			REFERENCES CAJA_POS(CAJA)
go


ALTER TABLE TIPO_TARJETA_POS
	ADD CONSTRAINT TIPTARPOSAUTCENCUE
		FOREIGN KEY (CTR_AUTORIZADOR, CTA_AUTORIZADOR)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go


ALTER TABLE TIPO_TARJETA_POS
	ADD CONSTRAINT TIPTARPOSCOMCENCUE
		FOREIGN KEY (CTR_COMISION, CTA_COMISION)
			REFERENCES CENTRO_CUENTA(CENTRO_COSTO, CUENTA_CONTABLE)
go


ALTER TABLE TIPO_TARJETA_POS
	ADD CONSTRAINT SUBDOCCCTIPOTARJ
		FOREIGN KEY (TIPO_DOC_CXC, SUBTIPO_DOC_CXC )
			REFERENCES SUBTIPO_DOC_CC(TIPO, SUBTIPO)
go			

			
ALTER TABLE  TIPO_TARJETA_POS
	ADD CONSTRAINT SUBDOCCOMTIPOTARJ
		FOREIGN KEY (TIPO_DOC_COMISION, SUBTIPO_DOC_COMISION)
			REFERENCES SUBTIPO_DOC_CC(TIPO, SUBTIPO)
go			


ALTER TABLE TRASPASO_POS
	ADD CONSTRAINT TRAPOSDESBOD
		FOREIGN KEY (BODEGA_DESTINO)
			REFERENCES BODEGA(BODEGA)
go


ALTER TABLE TRASPASO_POS
	ADD CONSTRAINT TRAPOSORIBOD
		FOREIGN KEY (BODEGA_ORIGEN)
			REFERENCES BODEGA(BODEGA)
go


ALTER TABLE TRASPASO_POS
	ADD CONSTRAINT TRAPOSCONCI
		FOREIGN KEY (CONSECUTIVO_CI)
			REFERENCES CONSECUTIVO_CI(CONSECUTIVO)
go


ALTER TABLE TRASPASO_POS_DET
	ADD CONSTRAINT TRAPOSDETART
		FOREIGN KEY (ARTICULO)
			REFERENCES ARTICULO(ARTICULO)
go


ALTER TABLE TRASPASO_POS_DET
	ADD CONSTRAINT TRAPOSDETLOT
		FOREIGN KEY (ARTICULO,LOTE)
			REFERENCES LOTE(ARTICULO,LOTE)
go


ALTER TABLE TRASPASO_POS_DET
	ADD CONSTRAINT TRAPOSDETTRAPOS
		FOREIGN KEY (CONSECUTIVO_CI, DOCUMENTO)
			REFERENCES TRASPASO_POS(CONSECUTIVO_CI, DOCUMENTO)
				ON DELETE CASCADE
go


ALTER TABLE SUPERVISOR 
	ADD CONSTRAINT SUPGRU
		FOREIGN KEY (GRUPO)
			REFERENCES GRUPO
go


ALTER TABLE SUPERVISOR
	ADD CONSTRAINT SUPUSU
		FOREIGN KEY (SUPERVISOR)
			REFERENCES ERPADMIN.USUARIO
go


ALTER TABLE UNIDAD_FRACCION
	ADD CONSTRAINT UNIFRAUNIMED
		FOREIGN KEY (UNIDAD_MEDIDA)
			REFERENCES UNIDAD_DE_MEDIDA(UNIDAD_MEDIDA)
go


ALTER TABLE PAQ_DESC_GRUPO
	ADD CONSTRAINT PAQDESGRUGRU
		FOREIGN KEY (GRUPO)
			REFERENCES GRUPO(GRUPO)
go


ALTER TABLE BONO_TIENDA
       ADD CONSTRAINT FKBONOTIENDABONOPAGO
              FOREIGN KEY (CODIGO)
                             REFERENCES BONO_PAGO(CODIGO)
                             	ON DELETE CASCADE
go 

                            
ALTER TABLE BONO_TIENDA
       ADD CONSTRAINT FKBONOTIENDAGRUPO
              FOREIGN KEY (TIENDA)
                             REFERENCES GRUPO(GRUPO)
go                             
                            
ALTER TABLE BONO_CATEGORIA
       ADD CONSTRAINT FKBONOCATEGBONOPAGO
              FOREIGN KEY (CODIGO)
                             REFERENCES BONO_PAGO(CODIGO)
                             	ON DELETE CASCADE
go

ALTER TABLE BONO_CATEGORIA
       ADD CONSTRAINT FKBONOCATEGCATECLIENTE
              FOREIGN KEY (CATEGORIA_CLIENTE)
                             REFERENCES CATEGORIA_CLIENTE(CATEGORIA_CLIENTE)
go

ALTER TABLE CUPON
	ADD CONSTRAINT CUPONCLIENTE
		FOREIGN KEY (CLIENTE)
			REFERENCES CLIENTE(CLIENTE)
go


ALTER TABLE RESOLUCION_POS
	ADD CONSTRAINT RESOLPOSUSUARIOCR
		FOREIGN KEY (USUARIO_CREACION)
			REFERENCES ERPADMIN.USUARIO
go


ALTER TABLE RESOLUCION_POS
	ADD CONSTRAINT CAJARESOLUCIONPOS
		FOREIGN KEY (CAJA)
			REFERENCES CAJA_POS(CAJA)
go


ALTER TABLE CLASE_DOC_POS
	ADD CONSTRAINT SUBDOCCCCLASEDOC
		FOREIGN KEY (TIPO, SUBTIPO)
			REFERENCES SUBTIPO_DOC_CC(TIPO, SUBTIPO)
go

ALTER TABLE TIPO_DOC_DEFAULT
	ADD CONSTRAINT CONSECAJATIPODOC
		FOREIGN KEY (CONSEC_DEFAULT,CAJA)
			REFERENCES CONSEC_CAJA_POS(CODIGO,CAJA)
			ON DELETE CASCADE
go

ALTER TABLE DOCUMENTO_POS
	ADD CONSTRAINT DOCPOSNCFCONSEC 
		FOREIGN KEY(PREFIJO) 
			REFERENCES NCF_CONSECUTIVO (PREFIJO)
go	
		
ALTER TABLE TIPO_TARJETA_POS WITH NOCHECK
	 ADD CONSTRAINT TIPOTARJETAPOSTIPOTARJETA 
		FOREIGN KEY(TIPO_TARJETA)
			REFERENCES TIPO_TARJETA (TIPO_TARJETA)
				ON DELETE CASCADE
go
	