
CREATE TABLE AFILIADO (
	AFILIADO		VARCHAR(20)		NOT NULL,
	ASEGURADORA		VARCHAR(20)		NOT NULL,
	NOMBRE			VARCHAR(80)		NOT NULL,
	CEDULA			VARCHAR(30)		NOT NULL,
	TELEFONO		VARCHAR(15)		NOT NULL
)
go


ALTER TABLE AFILIADO  
	ADD CONSTRAINT XPKAFILIADO PRIMARY KEY  NONCLUSTERED (AFILIADO, ASEGURADORA)
go
	



CREATE TABLE ARTICULO_SERIE_POS (
       DOCUMENTO            	VARCHAR(50) 	NOT NULL,
       TIPO                 	VARCHAR(1) 	NOT NULL,
       CAJA                 	VARCHAR(6) 	NOT NULL,
       LINEA                	VARCHAR(4) 	NOT NULL,
       LINEA_SERIE          	INT 		NOT NULL,
       ARTICULO             	VARCHAR(20) 	NOT NULL,
       SERIE_INICIAL        	VARCHAR(20) 	NOT NULL,
       SERIE_FINAL          	VARCHAR(20) 	NOT NULL,
       CANTIDAD             	DECIMAL(28,8) 	NOT NULL,
       CANT_RESERVADA_PED   	DECIMAL(28,8)	NULL,
       BODEGA 		    		VARCHAR(4) 	NOT NULL,
       PEDIDO 		    		VARCHAR(55) 	NULL
)
go

ALTER TABLE ARTICULO_SERIE_POS
       ADD CONSTRAINT XPKARTICULO_SERIE_POS PRIMARY KEY (DOCUMENTO, TIPO, CAJA, LINEA, LINEA_SERIE)
go


CREATE TABLE ASIENTOS_DOC_POS (
       DOCUMENTO   		VARCHAR(50)	NOT NULL,
       TIPO             	VARCHAR(1)	NOT NULL,
       CAJA             	VARCHAR(6)	NOT NULL,
       TIPO_ASIENTO		VARCHAR(2)	NOT NULL,
       ASIENTO     		VARCHAR(10) 	NOT NULL
 )
go

ALTER TABLE ASIENTOS_DOC_POS
       ADD CONSTRAINT XPKASIENTOS_DOC_POS PRIMARY KEY (DOCUMENTO, TIPO, CAJA, TIPO_ASIENTO)
go


CREATE TABLE AUDIT_CUPON (	
       CUPON                	VARCHAR(20) 		NOT NULL,
       TIPO                 	VARCHAR(1) 		NOT NULL,
       DOCUMENTO            	VARCHAR(50) 		NOT NULL,
       CAJA                 	VARCHAR(6) 		NOT NULL,
       TIENDA               	VARCHAR(6) 		NOT NULL,
       FECHA_APLICA         	DATETIME 		NOT NULL,
       CAJERO               	VARCHAR(25) 		NOT NULL,
       MONTO_APLICA         	DECIMAL(28,8) 		NOT NULL
)
go

ALTER TABLE AUDIT_CUPON
       ADD CONSTRAINT XPKAUDIT_CUPON PRIMARY KEY (CUPON, TIPO, DOCUMENTO, CAJA)
go


CREATE TABLE AUDITORIA_MODIFICACION (
       FECHA                	DATETIME 	NOT NULL,
       USUARIO              	VARCHAR(25) 	NULL,
       CONJUNTO             	VARCHAR(20) 	NOT NULL,
       TABLA                	VARCHAR(20) 	NOT NULL,
       OPERACION            	VARCHAR(1) 	NOT NULL,
       MODIFICACIONES       	TEXT 		NOT NULL
)
go

ALTER TABLE AUDITORIA_MODIFICACION
       ADD CONSTRAINT XPKAUDITORIA_MODIFICACION PRIMARY KEY (FECHA)
go


CREATE TABLE AUXILIAR_POS (
        DOCUM_APLICA           	VARCHAR(50)	NOT NULL,
        TIPO_APLICA		VARCHAR(1) 	NOT NULL,
        CAJA_DOCUM_APLICA	VARCHAR(6) 	NOT NULL,
        DOCUMENTO            	VARCHAR(50) 	NOT NULL,
        TIPO			VARCHAR(1) 	NOT NULL,
        CAJA                    VARCHAR(6) 	NOT NULL,
        MONTO_APLICADO	        DECIMAL(28,8) 	NOT NULL DEFAULT(0),
        CARGADO		        VARCHAR(1) 	NOT NULL DEFAULT('N'),
        FECHA_APLICACION	DATETIME 	NULL,
        DOC_CC_APLICADO		VARCHAR(50) 	NULL,
       	TIPO_DOC_CC_APLICADO 	VARCHAR(3) 	NULL,
       	CARGADO_CG		VARCHAR(1) 	NOT NULL DEFAULT ('N'),
	ASIENTO_APLICACION 	VARCHAR(10) 	NULL
)
go
  
ALTER TABLE AUXILIAR_POS
	ADD  CONSTRAINT XPKAUXILIAR_POS PRIMARY KEY CLUSTERED (DOCUM_APLICA, TIPO_APLICA, CAJA_DOCUM_APLICA, DOCUMENTO, TIPO, CAJA)
go


CREATE TABLE BITACORA (
       FECHA            	DATETIME 	NOT NULL,
       CAJERO           	VARCHAR(25) 	NOT NULL,
       CAJA             	VARCHAR(6) 	NOT NULL,
       CAJA_DOC       		VARCHAR(6) 	NULL,
       DOCUMENTO		VARCHAR(50) 	NULL,
       TIPO			VARCHAR(1) 	NULL,
       SUPERVISOR		VARCHAR(25)	NULL,
       EVENTO           	VARCHAR(4) 	NOT NULL,
       CANTIDAD         	DECIMAL(28,8) 	NULL,
       TIPO_REG			VARCHAR(1)	NOT NULL,
       OBSERVACIONES 		VARCHAR(4000)	NULL
)
go
  
 
CREATE TABLE BONO_CATEGORIA (
       CODIGO			VARCHAR(20) 		NOT NULL,
       CATEGORIA_CLIENTE	VARCHAR(8)		NOT NULL
)
go

ALTER TABLE BONO_CATEGORIA
       ADD CONSTRAINT XPKBONO_CATEGORIA PRIMARY KEY (CODIGO, CATEGORIA_CLIENTE)
go

  
CREATE TABLE BONO_PAGO (
       CODIGO			VARCHAR(20)		NOT NULL,
       DESCRIPCION		VARCHAR(60)		NOT NULL,
       ESTADO			VARCHAR(1)		NOT NULL,
       FECHA_INI		DATETIME		NOT NULL,
       FECHA_FIN		DATETIME		NOT NULL,
       MONTO_MINIMO		DECIMAL(28,8) 		NULL,
       TIPO_DESCUENTO		VARCHAR(1)		NOT NULL,
       VALOR			DECIMAL(28,8)		NOT NULL,
       TODA_TIENDA		VARCHAR(1)		NOT NULL,
       TODA_CATEGORIA		VARCHAR(1)		NOT NULL,
       APLICAR_SUBTOTAL 	VARCHAR(1)		NOT NULL
)
go

ALTER TABLE BONO_PAGO
       ADD CONSTRAINT XPKBONO_PAGO PRIMARY KEY (CODIGO)
go 


CREATE TABLE BONO_TIENDA (
       CODIGO			VARCHAR(20)		NOT NULL,
       TIENDA			VARCHAR(6)		NOT NULL
)
go

ALTER TABLE BONO_TIENDA
       ADD CONSTRAINT XPKBONO_TIENDA PRIMARY KEY (CODIGO, TIENDA)
go  

  
CREATE TABLE CADENA (
       CADENA   		VARCHAR(20)		NOT NULL,
       DESCRIPCION      	VARCHAR(254)		NOT NULL
)
go

ALTER TABLE CADENA
       ADD CONSTRAINT XPKCADENA PRIMARY KEY (CADENA)
go
  
  
CREATE TABLE CAJA_POS (
       CAJA             	VARCHAR(6) 	NOT NULL,
       CODIGO_CORTO		VARCHAR(2)	NOT NULL,
       SUCURSAL        		VARCHAR(6) 	NOT NULL,
       BODEGA           	VARCHAR(4) 	NOT NULL,
       UBICACION        	VARCHAR(40) 	NULL,
       ASIGNADO         	VARCHAR(1) 	NOT NULL,
       IDENTIFICADOR		VARCHAR(20) 	NULL,       
       CENTRO_COSTO 		VARCHAR(25) 	NULL,
       CONS_CIERRE_CAJA 	VARCHAR(20) 	NOT NULL DEFAULT  ('00000000000000000000'),
       CONSEC_DOC_ESPERA 	VARCHAR(20) 	NULL,
       ESTADO 			VARCHAR(1) 	NOT NULL DEFAULT('I'),
       FIRMA 			TEXT 		NULL
)
go
  
ALTER TABLE CAJA_POS
       ADD CONSTRAINT XPKCAJA_POS PRIMARY KEY (CAJA)
go  
  
  
CREATE TABLE CAJERO (
       CAJERO               	VARCHAR(25) 	NOT NULL,
       GRUPO                	VARCHAR(6) 	NULL,
       VENDEDOR             	VARCHAR(4) 	NOT NULL,
       VERIFICACION         	VARCHAR(1) 	NOT NULL,
       ROTATIVO		    	VARCHAR(1) 	NOT NULL
)
go

ALTER TABLE CAJERO
       ADD CONSTRAINT XPKCAJERO PRIMARY KEY (CAJERO)
go  
  
  
CREATE TABLE CARGA_CCCB_ERRORES (
       DOCUMENTO   		INT			NOT NULL,
       TIPO_DOCUMENTO       	VARCHAR(1)		NOT NULL,
       TIPO_ERR             	VARCHAR(1)		NOT NULL,
       DESCRIPCION		VARCHAR(4000)		NOT NULL
 
)
go
  
CREATE TABLE CIERRE_CAJA (
       NUM_CIERRE_CAJA		VARCHAR(20)		NOT NULL,
       CAJA			VARCHAR(6)		NOT NULL,
       FECHA_APERTURA		DATETIME 		NOT NULL,
       CAJERO_CIERRE 		VARCHAR(25)		NULL,
       FECHA_CIERRE		DATETIME 		NULL,
       ESTADO			VARCHAR(1)		NOT NULL,
       FECHA_ANULACION		DATETIME 		NULL,
       CAJERO_APERTURA   	VARCHAR(25) 		NOT NULL,
       DOC_FISCAL 		VARCHAR(50) 		NULL,
	   DOCUMENTO   		VARCHAR(50)		NULL,
	   CORRELATIVO 		VARCHAR(10)		NULL
)
go

ALTER TABLE CIERRE_CAJA
	ADD  CONSTRAINT XPKCIERRECAJA_POS PRIMARY KEY CLUSTERED (NUM_CIERRE_CAJA, CAJA)
go


CREATE TABLE CIERRE_DESG_TARJ (
	NUM_CIERRE 		VARCHAR(20) 	NOT NULL,
	CAJERO 			VARCHAR(25)  	NOT NULL,
	CAJA          		VARCHAR(6)	NOT NULL,
	CONSECUTIVO		INT 		NOT NULL,
	TIPO_TARJETA		VARCHAR(12)	NOT NULL,
    	DOCUMENTO		VARCHAR(50) 	NOT NULL,
	TIPO			VARCHAR(1)	NOT NULL,
    	AUTORIZACION		VARCHAR(80)	NULL,
	MONTO			DECIMAL(28,8)	NOT NULL
)
go

ALTER TABLE CIERRE_DESG_TARJ
       ADD CONSTRAINT XPKCIERRE_DESG_TARJ PRIMARY KEY (NUM_CIERRE, CAJERO, CAJA, CONSECUTIVO)
go



CREATE TABLE CIERRE_DET_PAGO (
	NUM_CIERRE 		VARCHAR(20) 	NOT NULL,
	CAJERO 			VARCHAR(25)  	NOT NULL,
	CAJA          		VARCHAR(6)	NOT NULL,
	TIPO_PAGO		VARCHAR(40)	NOT NULL,
    	TOTAL_SISTEMA		DECIMAL(28,8) 	NOT NULL,
    	TOTAL_USUARIO		DECIMAL(28,8)	NOT NULL,
	DIFERENCIA		DECIMAL(28,8)	NOT NULL,
	ORDEN			INT		NOT NULL
)
go

ALTER TABLE CIERRE_DET_PAGO
       ADD CONSTRAINT XPKCIERRE_DET_PAGO PRIMARY KEY (NUM_CIERRE, CAJERO, CAJA, TIPO_PAGO)
go  



CREATE TABLE CIERRE_INFO_TARJ
(
	NUM_CIERRE_CAJA		VARCHAR(20) 	NOT NULL,
	CAJA          		VARCHAR(6)	NOT NULL,
	COD_TARJETA		VARCHAR(12)  	NOT NULL,
	CIERRE_TARJETA		VARCHAR(50)  	NOT NULL,
	CANT_VENTAS		DECIMAL(28,8)  	NULL,
	MONTO_VENTAS		DECIMAL(28,8)  	NULL,
	CANT_ANULACION		DECIMAL(28,8)  	NULL,
	MONTO_ANULACION		DECIMAL(28,8)  	NULL
)
go

ALTER TABLE CIERRE_INFO_TARJ 
       ADD CONSTRAINT XPKCIERRE_INFO_TARJ PRIMARY KEY NONCLUSTERED (COD_TARJETA, NUM_CIERRE_CAJA, CAJA)
go


CREATE TABLE CIERRE_POS (
	NUM_CIERRE 		VARCHAR(20) 	NOT NULL,
    	CAJERO			VARCHAR(25) 	NOT NULL,
	CAJA          		VARCHAR(6)	NOT NULL,
	TIPO_CIERRE		VARCHAR(1)	NOT NULL,
	NOMBRE_VENDEDOR		VARCHAR(40)	NOT NULL,
    	FECHA_HORA		DATETIME	NOT NULL,
	TIPO_CAMBIO		DECIMAL(28,8)	NOT NULL,
	MONTO_APERTURA		DECIMAL(28,8)	NOT NULL,
	TOTAL_DIFERENCIA	DECIMAL(28,8)	NOT NULL,
	DOCUMENTO_AJUSTE    	VARCHAR(50)	NULL,
	TOTAL_LOCAL		DECIMAL(28,8)	NOT NULL,
	TOTAL_DOLAR		DECIMAL(28,8)	NOT NULL,
	VENTAS_EFECTIVO		DECIMAL(28,8)	NOT NULL,
	ESTADO			VARCHAR(1)	NOT NULL,
	FECHA_HORA_INICIO 	DATETIME 	NULL,
	NOTAS			VARCHAR(4000)	NULL,
	COBRO_EFECTIVO_REP 	DECIMAL(28, 8) 	NOT NULL DEFAULT(0),
	NUM_CIERRE_CAJA		VARCHAR(20)	NULL,
	DOC_FISCAL 		VARCHAR(50) 	NULL,
	DOCUMENTO   		VARCHAR(50)		NULL,
	CORRELATIVO 		VARCHAR(10)		NULL
)
go

ALTER TABLE CIERRE_POS
       ADD CONSTRAINT XPKCIERRE_POS PRIMARY KEY (NUM_CIERRE, CAJERO, CAJA)
go



CREATE TABLE CIERRE_TIENDA (
        GRUPO     		VARCHAR(6)	NOT NULL,
        NUM_CIERRE       	INT	 	NOT NULL,
        FECHA_INICIO		DATETIME	NULL,
        FECHA_FIN		DATETIME	NOT NULL,
        USUARIO			VARCHAR(25)	NOT NULL,
        DESCUENTO_LINEA 	DECIMAL(28,8) 	NULL,
       	DESCUENTO_GENERAL 	DECIMAL(28,8) 	NULL,
       	IMPUESTO1 		DECIMAL(28,8) 	NULL,
       	IMPUESTO2 		DECIMAL(28,8) 	NULL,
       	TOTAL 			DECIMAL(28,8) 	NULL,
       	TOTAL_PAGAR		DECIMAL(28,8) 	NULL,
       	PREFIJO 		VARCHAR(50)   	NULL,
	NCF 			VARCHAR(20)   	NULL
)
go

ALTER TABLE CIERRE_TIENDA
       ADD CONSTRAINT XPKCIERRE_TIENDA PRIMARY KEY (GRUPO, NUM_CIERRE)
go
  
  
CREATE TABLE CLASE_DOC_POS (
       CODIGO               	VARCHAR(10) 		NOT NULL,
       CLASE_DOC            	VARCHAR(1) 		NOT NULL,
       TIPO                 	VARCHAR(3) 		NOT NULL,
       SUBTIPO              	SMALLINT 		NOT NULL,
       DESCRIPCION 		VARCHAR(80) 		NULL,
       APLICA_MONTO_MIN_FISCAL 	VARCHAR(1) 		NOT NULL DEFAULT ('N')
)
go

ALTER TABLE CLASE_DOC_POS   
       ADD CONSTRAINT XPKCLASE_DOC_POS PRIMARY KEY NONCLUSTERED  (CODIGO)
go
  
  
CREATE TABLE CLIENTE_EXPR_ENTR
(
	CLIENTE_EXP		VARCHAR(20) 		NOT NULL,
	ENTREGAR_A		VARCHAR(80) 		NOT NULL
)
go

ALTER TABLE CLIENTE_EXPR_ENTR   
	ADD CONSTRAINT XPKCLIENTEEXPRENTR PRIMARY KEY NONCLUSTERED  (CLIENTE_EXP,ENTREGAR_A)
go
  
  

CREATE TABLE CLIENTE_EXPRESS
(
	CLIENTE_EXP		VARCHAR(20) 		NOT NULL,
	DIRECCION_ENTREGA	VARCHAR(1000) 		NOT NULL
)
go

ALTER TABLE CLIENTE_EXPRESS   
	ADD CONSTRAINT XPKCLIENTEEXPRESS PRIMARY KEY NONCLUSTERED  (CLIENTE_EXP)
go

  

CREATE TABLE CLIENTE_FORMA_PAGO (
       FORMA_PAGO           	VARCHAR(4) 	NOT NULL,
       CLIENTE              	VARCHAR(20)	NOT NULL,
       ENTIDAD_FINANCIERA	VARCHAR(8) 	NOT NULL,
       NUMERO_CTA           	VARCHAR(25) 	NULL,
       ESTADO               	VARCHAR(1) 	NULL,
       RESP_CTA             	VARCHAR(40) 	NULL
)
go

ALTER TABLE CLIENTE_FORMA_PAGO
       ADD CONSTRAINT XPKCLIENTE_FORMA_PAGO PRIMARY KEY (FORMA_PAGO, CLIENTE, ENTIDAD_FINANCIERA)
go
  
  
CREATE TABLE CLIENTE_POS (
        CLIENTE              	VARCHAR(20) 	NOT NULL,
        FECHA_NACIMIENTO     	DATETIME 	NULL,
        PAIS_EMBAJADA 		VARCHAR(4)	NULL,
        CARNE 			VARCHAR(40) 	NULL,
        ES_VIP  		VARCHAR(1)  	NOT NULL DEFAULT ('N'),
	GENERO			VARCHAR(1)  	NOT NULL DEFAULT ('M')
 )
go

ALTER TABLE CLIENTE_POS
       ADD CONSTRAINT XPKCLIENTE_POS PRIMARY KEY NONCLUSTERED (CLIENTE)
go
  
  
   
CREATE TABLE COBRO_POS (
       COBRO	          	INT  	  	NOT NULL,
       TIENDA			VARCHAR(6)	NOT NULL,
       FECHA			DATETIME	NOT NULL,
       MONTO			DECIMAL(28,8)	NOT NULL,
       CLIENTE			VARCHAR(20)	NOT NULL,
       COMISION			DECIMAL(28,8)	NULL,
       COMENTARIO		VARCHAR(254)	NULL,
       APROBADO             	VARCHAR(1) 	NOT NULL,
       FECHA_HORA_CARGA     	DATETIME 	NULL,
       TIPO_CAMBIO 		DECIMAL(28,8) 	NOT NULL,
       MONEDA_REPORTE 		VARCHAR(1) 	NOT NULL,
       NUM_CIERRE		INT 		NULL,
       ESTADO 			VARCHAR(1) 	NOT NULL DEFAULT('P'),
       DOC_OD			VARCHAR(50) 	NULL,
       TIPO_DOC_OD 		VARCHAR(20) 	NULL,
       DOC_OC			VARCHAR(50) 	NULL,
       TIPO_DOC_OC 		VARCHAR(20) 	NULL,
       FCH_HORA_ANUL 		DATETIME	NULL,
       TIPO_COBRO  		VARCHAR(1)   	NOT NULL DEFAULT ('T'),
       APLICACION 		VARCHAR(249) 	NULL,
	   TIPO_DOC 		VARCHAR(1) NULL
)
go
 
ALTER TABLE COBRO_POS ADD CONSTRAINT XPKCOBRO_POS 
	PRIMARY KEY (COBRO, TIENDA)
go

  
CREATE TABLE CONEXION (
       CAJERO           	VARCHAR(25)  	NOT NULL,
       CAJA             	VARCHAR(6)   	NOT NULL,
       CONEXIONES		SMALLINT     	NOT NULL
)
go

ALTER TABLE CONEXION
       ADD CONSTRAINT XPKCONEXION PRIMARY KEY (CAJERO)
go
  


CREATE TABLE CONFIG_CAJA(
	   CAJA				VARCHAR(6) 	NOT NULL,
	   NOMBRE            		VARCHAR(30)     NOT NULL,
       	   VALOR                 	VARCHAR(MAX)    NOT NULL,
           TIPO				VARCHAR(1) 	NOT NULL 	DEFAULT 'S'
)
go


ALTER TABLE CONFIG_CAJA
       ADD CONSTRAINT XPKGLOBALES_CAJA PRIMARY KEY (CAJA, NOMBRE)
go


CREATE TABLE CONSEC_CAJA_POS
(
	CODIGO 			VARCHAR(10)	NOT NULL ,
	CAJA 			VARCHAR(6)	NOT NULL ,
	DESCRIPCION 		VARCHAR(60)	NULL ,
	TIPO_DOCUMENTO 		VARCHAR(1)	NOT NULL ,
	MASCARA 		VARCHAR(50)	NOT NULL ,
	VALOR 			VARCHAR(50)	NOT NULL ,
	CREDITO_FISCAL 		VARCHAR(1)	NOT NULL ,
	FORMATO_IMPRESION 	VARCHAR(30)	NULL,
	CONSEC_FAC_DEV		VARCHAR(20)	NULL,
	RESOLUCION		VARCHAR(20)	NULL,
	ACTIVO 			VARCHAR(1)   	NOT NULL DEFAULT ('S'),
	CLASE_DOCUMENTO 	VARCHAR(10) 	NULL,
	USA_DESPACHOS VARCHAR(1) NOT NULL DEFAULT('N')
)
go

ALTER TABLE CONSEC_CAJA_POS 
  ADD CONSTRAINT XPKCONSECCAJAPOS PRIMARY KEY (CODIGO, CAJA)
go


CREATE TABLE COMISION_ARTICULO (
       COMISION			VARCHAR(6)    	NOT NULL,
       ARTICULO			VARCHAR(20)   	NOT NULL,
       TIPO_META		VARCHAR(1)    	NOT NULL,
       META_INFERIOR	     	DECIMAL(28,8) 	NOT NULL,
       META_SUPERIOR	     	DECIMAL(28,8) 	NOT NULL)
go


ALTER TABLE COMISION_ARTICULO ADD CONSTRAINT XPKCOMISIONARTICULO 
	PRIMARY KEY NONCLUSTERED  (COMISION, ARTICULO)
go


CREATE TABLE COMISION_EXCEPCION (
       COMISION       		VARCHAR(6)  	NOT NULL,
       ARTICULO	      		VARCHAR(20) 	NOT NULL
)
go
  
ALTER TABLE COMISION_EXCEPCION ADD CONSTRAINT XPKCOMISIONEXCEPCION 
	PRIMARY KEY NONCLUSTERED  (COMISION, ARTICULO)
go

 
CREATE TABLE CUPON (
       CUPON                	VARCHAR(20) 		NOT NULL,
       DESCRIPCION          	VARCHAR(60) 		NULL,
       ESTADO               	VARCHAR(1) 		NOT NULL,
       CLIENTE              	VARCHAR(20) 		NOT NULL,
       MONEDA               	VARCHAR(1) 		NOT NULL,
       MONTO                	DECIMAL(28,8) 		NOT NULL,
       SALDO                	DECIMAL(28,8) 		NOT NULL,
       FECHA_VENCE          	DATETIME 		NOT NULL,
       FCH_HORA_BLOQUEO     	DATETIME 		NULL,
       CAJERO_BLOQUEO       	VARCHAR(20) 		NULL,
       TIPO_CUPON 	    	VARCHAR(1) 		NOT NULL DEFAULT('D')
)
go

ALTER TABLE CUPON
       ADD CONSTRAINT XPKCUPON PRIMARY KEY (CUPON)
go
 
 
CREATE TABLE DEPOSITO_POS (
       DEPOSITO          	INT 	 	NOT NULL,
       TIENDA			VARCHAR(6)	NOT NULL,
       CUENTA_BANCO         	VARCHAR(20)	NOT NULL,
       DOCUMENTO		INT		NOT NULL,
       FECHA			DATETIME	NOT NULL,
       MONTO			DECIMAL(28,8)	NOT NULL,
       APROBADO             	VARCHAR(1) 	NOT NULL,
       FECHA_HORA_CARGA     	DATETIME 	NULL
)
go

ALTER TABLE DEPOSITO_POS
       ADD CONSTRAINT XPKDEPOSITO_POS PRIMARY KEY (DEPOSITO, TIENDA)
go 
 
 
CREATE TABLE DET_REG_BILLETE (
	DOCUMENTO		VARCHAR(50)		NOT NULL,
	CAJA			VARCHAR(6)		NOT NULL,
	TIPO			VARCHAR(1)		NOT NULL,
	PAGO			VARCHAR(4)		NOT NULL,
	IDENTIFICACION		VARCHAR(80)		NOT NULL,
	LINEA			INT	   		NOT NULL,
	DENOMINACION		VARCHAR(30)		NOT NULL,
	SERIE			VARCHAR(100)		NOT NULL
)
go 


ALTER TABLE DET_REG_BILLETE  
	ADD CONSTRAINT XPKDETREGBILLETE
		PRIMARY KEY  NONCLUSTERED (IDENTIFICACION, PAGO, DOCUMENTO, TIPO, CAJA, LINEA)
go 
		 
 
 
CREATE TABLE DETALLE_PERFIL_CLI (
       LINEA            	VARCHAR(4) 	NOT NULL,
       PERFIL           	VARCHAR(4) 	NOT NULL,
       MODIFICADOR      	DECIMAL(28,8) 	NOT NULL,
       DESCRIPCION		VARCHAR(40)	NULL
)
go

ALTER TABLE DETALLE_PERFIL_CLI
       ADD CONSTRAINT XPKDETALLE_PERFIL_CLI PRIMARY KEY (LINEA, PERFIL)
go




CREATE TABLE DIRECC_CLIENTE_POS
(
	TIENDA_OFF	VARCHAR(20)	NOT NULL,
	CLIENTE		VARCHAR(20)	NOT NULL,
	DIRECCION	VARCHAR(10)	NULL,
	CAMPO_1		VARCHAR(250)	NULL,
	CAMPO_2		VARCHAR(250)	NULL,
	CAMPO_3		VARCHAR(250)	NULL,
	CAMPO_4		VARCHAR(250)	NULL,
	CAMPO_5		VARCHAR(250)	NULL,
	CAMPO_6		VARCHAR(250)	NULL,
	CAMPO_7		VARCHAR(250)	NULL,
	CAMPO_8		VARCHAR(250)	NULL,
	CAMPO_9		VARCHAR(250)	NULL,
	CAMPO_10	VARCHAR(250)	NULL,
	APLICADA	VARCHAR(1)	NOT NULL DEFAULT ('N')
)
go


ALTER TABLE DIRECC_CLIENTE_POS
       ADD CONSTRAINT XPKDIRECC_CLIENTE_POS PRIMARY KEY (TIENDA_OFF, CLIENTE)
go

 
 
CREATE TABLE DISTRIBUCION_ARTICULO 
(
	ARTICULO		VARCHAR(20)		NOT NULL,
	CENTRO_COSTO		VARCHAR(25)		NOT NULL,
	CUENTA_CONTABLE		VARCHAR(25)		NOT NULL,
	DISTRIBUCION		DECIMAL(28,8)		NOT NULL
)
go

ALTER TABLE DISTRIBUCION_ARTICULO  ADD CONSTRAINT XPKDISTRIBUCIONARTICULO 
	PRIMARY KEY (ARTICULO, CENTRO_COSTO, CUENTA_CONTABLE
)
go 
 
 
 
CREATE TABLE DOC_POS_CARGA (
       DOCUMENTO           	VARCHAR(50) 		NOT NULL,
       TIPO			VARCHAR(1) 		NOT NULL,
       CAJA	                VARCHAR(6) 		NOT NULL,
       TEXTO_ERROR		TEXT	 		NOT NULL
)
go

ALTER TABLE DOC_POS_CARGA 
       ADD CONSTRAINT XPKDOC_POS_CARGA PRIMARY KEY (DOCUMENTO, TIPO, CAJA)
go
 
 
CREATE TABLE DOC_POS_LINEA (
       DOCUMENTO         	VARCHAR(50)		NOT NULL,
       TIPO		 	VARCHAR(1) 		NOT NULL,
       CAJA              	VARCHAR(6) 		NOT NULL,
       LINEA             	VARCHAR(4) 		NOT NULL,
       ARTICULO          	VARCHAR(20) 		NOT NULL,
       LOTE              	VARCHAR(15) 		NULL,
       CANTIDAD          	DECIMAL(28,8) 		NOT NULL,
       PRECIO_VENTA	 	DECIMAL(28,8) 		NOT NULL,
       DESCUENTO_LINEA   	DECIMAL(28,8) 		NOT NULL,
       DESCUENTO_GENERAL 	DECIMAL(28,8) 		NOT NULL,
       TOTAL_IMPUESTO1 		DECIMAL(28,8) 		NOT NULL,
       TOTAL_IMPUESTO2 		DECIMAL(28,8) 		NOT NULL,
       LEYENDA 			VARCHAR(254) 		NULL,
       CANT_RESERVADA_PED 	DECIMAL(28,8)		NULL,
       BODEGA 			VARCHAR(4) 		NOT NULL,
       PEDIDO 			VARCHAR(55) 		NULL,
       LOCALIZACION 		VARCHAR(8) 		NULL,
       BASE_IMPUESTO1		DECIMAL(28,8) 		NULL,
       BASE_IMPUESTO2		DECIMAL(28,8) 		NULL,
       NOTAS			VARCHAR(4000) 		NULL,
       MONTO_RETENCION 		DECIMAL(28,8) 		NULL,
       DESCRIPCION 		VARCHAR(254)		NULL,
       MONTO_BONIFICADO  	DECIMAL(28,8)  		DEFAULT(0) NOT NULL
)
go

ALTER TABLE DOC_POS_LINEA
       ADD CONSTRAINT XPKDOC_POS_LINEA PRIMARY KEY (DOCUMENTO, TIPO, CAJA, LINEA)
go
 

CREATE TABLE DOC_POS_RETENCION (
       DOCUMENTO            		VARCHAR(50) 	NOT NULL,
       TIPO                 		VARCHAR(1) 	NOT NULL,
       CAJA                 		VARCHAR(6) 	NOT NULL,
       CODIGO_RETENCION			VARCHAR(4) 	NOT NULL,
       AUTORETENEDORA      		VARCHAR(1) 	NOT NULL,
       MONTO	        		DECIMAL(28,8) 	NOT NULL,       
       BASE             		DECIMAL(28,8) 	NOT NULL,       
       DOC_REFERENCIA	    		VARCHAR(50) 	NOT NULL,
       DOC_CXC_RETENCION  		VARCHAR(50) 	NULL,
       TIPO_DOC_RETENCION		VARCHAR(3)	NULL
)
go

ALTER TABLE DOC_POS_RETENCION 
	ADD CONSTRAINT XPKDOC_POS_RETENCION PRIMARY KEY (DOCUMENTO, TIPO, CAJA, CODIGO_RETENCION)
go


CREATE TABLE DOCUMENTO_EN_ESPERA (
	DOCUMENTO		VARCHAR(20)		NOT NULL,
	CAJA			VARCHAR(6)		NOT NULL,
	TIPO			VARCHAR(1)		NOT NULL,
	VENDEDOR		VARCHAR(4) 		NOT NULL,
	CLIENTE			VARCHAR(20)		NOT NULL,
	NOMBRE_CLIENTE		VARCHAR(80)		NULL,
	CAJERO			VARCHAR(25)		NOT NULL,
	BASE_IMPUESTO1		DECIMAL(28,8)   	NULL,
	IMPUESTO1		DECIMAL(28,8)   	NOT NULL,
	BASE_IMPUESTO2		DECIMAL(28,8)   	NULL,
	IMPUESTO2		DECIMAL(28,8)   	NOT NULL,
	DESCUENTO		DECIMAL(28,8)   	NOT NULL,
	TOTAL			DECIMAL(28,8)   	NOT NULL,
	TOTAL_PAGAR		DECIMAL(28,8)   	NOT NULL,
	FCH_HORA_CREACION	DATETIME		NOT NULL,
	NIVEL_PRECIO		VARCHAR(12)		NOT NULL,
	MONEDA_NIVEL		VARCHAR(1)		NOT NULL,
	VERSION			INT			NOT NULL,
	FECHANAC_CLIENTE	DATETIME		NULL,
	TELEFONO_CLIENTE	VARCHAR(15)		NULL,
	NIT_CLIENTE		VARCHAR(20)		NULL,
	NOTAS			VARCHAR(4000)		NULL,
	CLASE_DOCUMENTO		VARCHAR(1)		NOT NULL,
	DIRECCION		VARCHAR(4000)		NULL,
	TIPO_CAMBIO		DECIMAL(28,8)   	NOT NULL,
	NCF			VARCHAR(20)		NULL,
	TIPO_NCF		VARCHAR(6)		NULL,
	COD_CLASE_DOC		VARCHAR(10)		NOT NULL,
	DOC_EXPRESS		VARCHAR(1)		NOT NULL,
	CLIENTE_EXPRESS		VARCHAR(20)		NULL,
	ENTREGA_EXPRESS_A	VARCHAR(80)		NULL,
	MEMBRESIA   		VARCHAR(25) 		NULL,
	MONTO_BONIFICADO  	DECIMAL(28,8) 		DEFAULT(0) NOT NULL
)
go

ALTER TABLE DOCUMENTO_EN_ESPERA  ADD CONSTRAINT XPKDOCUMENTOENESPERA 
	PRIMARY KEY (DOCUMENTO, CAJA, TIPO
)
go


CREATE TABLE DOCUMENTO_LINEA_ESPERA (
	LINEA			VARCHAR(4)		NOT NULL,
	DOCUMENTO		VARCHAR(20)		NOT NULL,
	CAJA			VARCHAR(6)		NOT NULL,
	TIPO			VARCHAR(1)		NOT NULL,
	ARTICULO		VARCHAR(20)		NOT NULL,
	BODEGA			VARCHAR(4)		NOT NULL,
	LOTE			VARCHAR(15)		NULL,
	LOCALIZACION		VARCHAR(8)		NULL,
	PEDIDO			VARCHAR(20)		NULL,
	CANT_RESERVADA_PED	DECIMAL(28,8)		NULL,
	CANTIDAD		DECIMAL(28,8)		NOT NULL,
	PRECIO_UNITARIO		DECIMAL(28,8)		NOT NULL,
	DESCUENTO_LINEA		DECIMAL(28,8)		NOT NULL,
	DESCUENTO_GENERAL	DECIMAL(28,8)		NOT NULL,
	TOTAL_IMPUESTO1		DECIMAL(28,8)		NOT NULL,
	TOTAL_IMPUESTO2		DECIMAL(28,8)		NOT NULL,
	BASE_IMPUESTO1		DECIMAL(28,8)		NULL,
	BASE_IMPUESTO2		DECIMAL(28,8)		NULL,
	LEYENDA			VARCHAR(254)		NULL,
	NOTAS			VARCHAR(4000) 		NULL,
	MONTO_BONIFICADO  	DECIMAL(28,8) 		DEFAULT(0) NOT NULL,
	ES_BONIFICADA  		VARCHAR(1) 		DEFAULT('N') NOT NULL,
	LINEA_ASOCIADA  	INT 			DEFAULT(-1) NOT NULL,
	TIPO_BONIFICACION 	VARCHAR(3) 		NULL,
	TIPO_DESCUENTO  	VARCHAR(3) 		NULL,
	DESCUENTO_APLICADO 	VARCHAR(1) 		DEFAULT('N') NOT NULL
)
go

ALTER TABLE DOCUMENTO_LINEA_ESPERA  ADD CONSTRAINT XPKDOCUMENTOLINEAESPERA 
	PRIMARY KEY (LINEA, DOCUMENTO, CAJA, TIPO)
go


CREATE TABLE DOC_ESPERA_SERIE_POS (
	LINEA_SERIE		INT	   		NOT NULL,
	LINEA			VARCHAR(4)		NOT NULL,
	DOCUMENTO		VARCHAR(20)		NOT NULL,
	CAJA			VARCHAR(6)		NOT NULL,
	TIPO			VARCHAR(1)		NOT NULL,
	ARTICULO		VARCHAR(20)		NOT NULL,
	BODEGA			VARCHAR(4)		NULL,
	PEDIDO			VARCHAR(20)		NULL,
	SERIE_INICIAL		VARCHAR(20)		NOT NULL,
	SERIE_FINAL		VARCHAR(20)		NOT NULL,
	CANTIDAD		DECIMAL(28,8)		NOT NULL,
	CANT_RESERVADA_PED	DECIMAL(28,8)		NULL
)
go

ALTER TABLE DOC_ESPERA_SERIE_POS  ADD CONSTRAINT XPKDOCESPERASERIEPOS 
	PRIMARY KEY (LINEA_SERIE, LINEA, DOCUMENTO, CAJA, TIPO)
go



CREATE TABLE DOCUMENTO_POS (
       DOCUMENTO   		VARCHAR(50)		NOT NULL,
       TIPO             	VARCHAR(1)		NOT NULL,
       CAJA             	VARCHAR(6)		NOT NULL,
       CAJA_COBRO       	VARCHAR(6) 		NULL,
       CORRELATIVO 		VARCHAR(10)		NOT NULL,
       PERFIL          		VARCHAR(4)		NULL,
       VENDEDOR     		VARCHAR(4)		NULL,
       CLIENTE          	VARCHAR(20)		NOT NULL,
       NOMBRE_CLIENTE      	VARCHAR(150)		NULL,
       CAJERO           	VARCHAR(25)		NOT NULL,
       IMPUESTO1       		DECIMAL(28,8) 		NOT NULL,
       IMPUESTO2       		DECIMAL(28,8) 		NOT NULL,
       DESCUENTO       		DECIMAL(28,8) 		NOT NULL,
       TOTAL_PAGAR		DECIMAL(28,8) 		NOT NULL,
       TOTAL            	DECIMAL(28,8) 		NOT NULL,
       FCH_HORA_CREACION	DATETIME 		NOT NULL,
       FCH_HORA_COBRO      	DATETIME 		NULL,
       FCH_HORA_ANULA 		DATETIME 		NULL,
       EXPORTADO           	VARCHAR(1) 		NOT NULL,
       ESTADO_COBRO        	VARCHAR(1) 		NOT NULL,
       SALDO			DECIMAL(28,8)		NOT NULL,
       SALDO_REPORTE 		DECIMAL(28,8) 		NOT NULL,
       MONEDA_DOC		VARCHAR(1)		NOT NULL,
       FECHA_VENCE		DATETIME 		NOT NULL,
       LISTO_INVENTARIO		VARCHAR(1)		NOT NULL,
       NIVEL_PRECIO		VARCHAR(12)		NULL,
       MONEDA_NIVEL		VARCHAR(1)		NULL,
       VERSION			INT			NULL,
       FECHANAC_CLIENTE  	DATETIME 		NULL,
       TELEFONO_CLIENTE  	VARCHAR(50) 		NULL,
       NIT_CLIENTE  		VARCHAR(20) 		NULL,
       NOTAS  			TEXT 			NULL,
       PAIS 		    	VARCHAR(4)   		NULL,
       CLASE_DOCUMENTO      	VARCHAR(1)  		NULL,
       DIRECCION 		VARCHAR(4000)		NULL,
       EXPORTADO_TIENDA 	VARCHAR(1) 		NULL,
       CONDICION_PAGO_APA	VARCHAR(4)		NULL,
       DOC_CC     		VARCHAR(50)		NULL,
       TIPO_DOC_CC		VARCHAR(3)		NULL,
       CARGADO_CC		VARCHAR(1)		NOT NULL,
       CARGADO_CG		VARCHAR(1)		NOT NULL,
       DEVUELVE_DINERO		VARCHAR(1)		NULL,
       DOC_CC_ANUL		VARCHAR(50)		NULL,
       TIPO_DOC_CC_ANUL		VARCHAR(3)		NULL,
       GENERO_FACTURA_INICIO	VARCHAR(1) 		NULL,
       AFECTA_CONTABIL		VARCHAR(1) 		NULL,
       EFECTIVO_DEVUELTO 	DECIMAL(28,8) 		NULL,
       TIPO_CAMBIO 		DECIMAL(28,8) 		NOT NULL,
       BENEFICIARIO 		VARCHAR(254) 		NULL,
       MONEDA 			VARCHAR(1) 		NULL,
       SUBTIPO 			VARCHAR(1) 		NULL,
       ID_BENEFICIARIO 		VARCHAR(20) 		NULL,
       USUARIO_ULT_IMPRE 	VARCHAR(25) 		NULL,
       FCH_HORA_ULT_IMPRE 	DATETIME 		NULL,
       USUARIO_APLICACION 	VARCHAR(25) 		NULL,
       FCH_HORA_APLICACIO 	DATETIME 		NULL,
       USUARIO_ANULACION 	VARCHAR(25) 		NULL,
       ESTADO_IMPRESION 	VARCHAR(1) 		NULL,
       TELEFONO_BENEFICIA 	VARCHAR(50) 		NULL,
       NCF			VARCHAR(20)		NULL,
       TIPO_NCF			VARCHAR(6)		NULL,
       NUM_CIERRE 		VARCHAR(20) 		NULL,
       RECIBIDO_DE 		VARCHAR(80) 		NULL,
       RESOLUCION		VARCHAR(20)		NULL,
       COD_CLASE_DOC        VARCHAR(10)    		NULL,
       DOC_EXPRESS 			VARCHAR(1) 		NOT NULL DEFAULT('N'),
       MENSAJERO 			VARCHAR(10) 		NULL,
       CLIENTE_EXPRESS 		VARCHAR(20) 		NULL,
       ENTREGA_EXPRSS_A 	VARCHAR(80) 		NULL,
       ESTADO_EXPRESS 		VARCHAR(1) 		NOT NULL DEFAULT ('P'),
       MONTO_ENTREGADO		DECIMAL(28,8)		NULL,
       MONTO_DEVUELTO		DECIMAL(28,8)		NULL,
       FCH_ENVIO 			DATETIME 		NULL,
       FCH_ENTREGA 			DATETIME		NULL,
       MOTIV_CANCELA_EXPR 	VARCHAR(10) 		NULL,
       NOTA_EXPRESS 		VARCHAR(1000) 		NULL,
       BASE_IMPUESTO1		DECIMAL(28,8) 		NULL,
       BASE_IMPUESTO2		DECIMAL(28,8) 		NULL,
       DOC_FISCAL 			VARCHAR(50) 		NULL,
       PREFIJO 	  			VARCHAR(50) 		NULL,
       PEDIDO_AUTORIZADO 	VARCHAR(50) 		NULL,
       DOC_CC_ANTICIPO 		VARCHAR(50) 		NULL,
       NOMBREMAQUINA 		VARCHAR(20)			NULL,
       CIERRE_ANULACION 	VARCHAR(20) 		NULL,
       DOC_SINCRONIZADO 	VARCHAR(1) 			NOT NULL DEFAULT('N'),
       MONTO_BONIFICADO  	DECIMAL(28,8) 		DEFAULT(0) NOT NULL,
       ES_DOC_EXTERNO 		VARCHAR(1) 			DEFAULT ('N') NOT NULL,
       TIENDA_ENVIADO 		VARCHAR(4000) 		NULL,
	   USA_DESPACHOS 		VARCHAR(1) 			NOT NULL DEFAULT('N'),
	   CLAVE_REFERENCIA_DE 	VARCHAR(50) 		NULL,
		FECHA_REFERENCIA_DE DATETIME 			NULL,
		FORMA_PAGO 			VARCHAR(4) NULL,
		USO_CFDI 			VARCHAR(3) NULL,
		JUSTI_DEV_HACIEND VARCHAR(2) NULL
)
go

ALTER TABLE DOCUMENTO_POS
       ADD CONSTRAINT XPKDOCUMENTO_POS PRIMARY KEY (DOCUMENTO, TIPO, CAJA)
go



CREATE TABLE ERROR_CAJA (
       CAJA			VARCHAR(6) 		NOT NULL,
       ERROR_CAJA		INT 			NOT NULL,
       TIPO			VARCHAR(1)		NOT NULL,
       CAJERO			VARCHAR(25)		NOT NULL,
       FECHA_HORA		DATETIME		NOT NULL,
       MENSAJE			VARCHAR(4000)		NOT NULL,
       ESTADO			VARCHAR(1)		NOT NULL
)
go

ALTER TABLE ERROR_CAJA
       ADD CONSTRAINT PK_ERROR_CAJA PRIMARY KEY (CAJA,ERROR_CAJA)
go



CREATE TABLE FACTURA_DEVUELTA (
       DEV_DOCUMENTO           	VARCHAR(50) 		NOT NULL,
       DEV_TIPO			VARCHAR(1) 		NOT NULL,
       DEV_CAJA                 VARCHAR(6) 		NOT NULL,
       FAC_DOCUMENTO           	VARCHAR(50)		NOT NULL,
       FAC_CAJA			VARCHAR(6) 		NOT NULL,
       FAC_TIPO			VARCHAR(1) 		NOT NULL
)
go

ALTER TABLE FACTURA_DEVUELTA
       ADD CONSTRAINT XPKFACTURA_DEVUELTA PRIMARY KEY (DEV_DOCUMENTO, DEV_TIPO, DEV_CAJA)
go


CREATE TABLE FORMA_PAGO (
       FORMA_PAGO       	VARCHAR(4) 		NOT NULL,
       DESCRIPCION      	VARCHAR(40) 		NULL,
       IMPRESION_DOBLE		VARCHAR(1) 		NULL,
       CANTIDAD         	INT 			NULL,
       FORMULARIO       	VARCHAR(40)		NULL,
       USO_INTERNO      	VARCHAR(1) 		NOT NULL,
       ACTIVO           	VARCHAR(1) 		NOT NULL,
       CENTRO_COSTO			VARCHAR(25) 		NULL,
       CUENTA_CONTABLE		VARCHAR(25) 		NULL,
       NOMBRE_CAMPO1		VARCHAR(40) 		NULL,
       NOMBRE_CAMPO2		VARCHAR(40) 		NULL,
       MONEDA_REPORTE 		VARCHAR(1)  		NOT NULL DEFAULT('N'),
       REQUIERE_AUTORIZACION 	VARCHAR(1) 		NOT NULL DEFAULT ('N')
)
go

ALTER TABLE FORMA_PAGO
       ADD CONSTRAINT XPKFORMA_PAGO PRIMARY KEY (FORMA_PAGO)
go



CREATE TABLE GLOBALES_POS (
       CONDICION_PAGO       	VARCHAR(4) 		NOT NULL,
       TIPO_ASIENTO         	VARCHAR(4) 		NULL,
       PAQUETE              	VARCHAR(4) 		NULL,
       GRUPO_CAJERO         	VARCHAR(25)		NOT NULL,
       GRUPO_SUPERVISOR     	VARCHAR(25) 		NOT NULL,
       CLIENTE_OMISION      	VARCHAR(20) 		NOT NULL,
       INGRESO_CANTIDAD     	VARCHAR(1) 		NULL,
       IMPUESTO_INCLUIDO    	VARCHAR(1) 		NOT NULL,
       DETALLE_KITS         	VARCHAR(1) 		NULL,
       REDONDEAR_FACTURA	VARCHAR(1) 		NOT NULL,
       FACTOR_REDONDEO      	DECIMAL(28,8) 		NULL,
       INTEGRACION_CONTA    	VARCHAR(1) 		NOT NULL,
       VALIDAR_CHEQUES      	VARCHAR(1) 		NULL,
       PAGO_MIXTO           	VARCHAR(1) 		NOT NULL,
       IMPRESION_DOBLE      	VARCHAR(1) 		NULL,
       MAX_FORMA_PAGO       	INT 			NULL,
       FOTO_ARTICULO        	VARCHAR(1) 		NULL,
       ESQUEMA_VENDEDOR  	VARCHAR(1) 		NOT NULL,
       MANEJO_LOTE          	VARCHAR(1) 		NULL,
       VERIFICAR_FECHA      	VARCHAR(1) 		NULL,
       VALIDAR_EXISTENCIAS  	VARCHAR(1) 		NOT NULL,
       MODO_APLIC_ASIENTO  	SMALLINT 		NULL,
       IMPRESION_SIMULTANEA   	VARCHAR(1) 		NULL,
       ACTUALIZACION_SIMULTANEA VARCHAR(1) 		NULL,
       PERMITE_REDUCCIONES  	VARCHAR(1) 		NULL,
       MOD_CONDICION_PAGO   	VARCHAR(1) 		NOT NULL,
       LINEA_SUPERIOR1		VARCHAR(254) 		NULL,
       LINEA_SUPERIOR2      	VARCHAR(254) 		NULL,
       LINEA_SUPERIOR3      	VARCHAR(254) 		NULL,
       LINEA_SUPERIOR4      	VARCHAR(254) 		NULL,
       LINEA_INFERIOR1      	VARCHAR(254) 		NULL,
       LINEA_INFERIOR2      	VARCHAR(254) 		NULL,
       LINEA_INFERIOR3      	VARCHAR(254) 		NULL,
       LINEA_INFERIOR4      	VARCHAR(254) 		NULL,
       IMP1_AFECTA_DESCTO	VARCHAR(1) 		NOT NULL,
       CALCULO_IMPUESTOS 	VARCHAR(1) 		NULL,
       AUTORIZA_PRECIO      	VARCHAR(1) 		NULL,
       PORC_DCTO_LINEA      	DECIMAL(28,8)   	NOT NULL,
       PORC_DCTO_TOTAL      	DECIMAL(28,8)   	NOT NULL,
       PORC_DCTO_LIN_SUP      	DECIMAL(28,8)   	NOT NULL,
       PORC_DCTO_TOT_SUP      	DECIMAL(28,8)   	NOT NULL,
       ARTICULO_APARTADO	VARCHAR(20) 		NULL,
       LINEA_INFER1_APART	VARCHAR(40) 		NULL,
       LINEA_INFER2_APART	VARCHAR(40) 		NULL,
       LINEA_INFER3_APART	VARCHAR(40) 		NULL,
       LINEA_INFER4_APART	VARCHAR(40) 		NULL,
       DIAS_VENCE_APART		SMALLINT 		NULL,
       IMPRIMIR_PRELECTURA	VARCHAR(1) 		NOT NULL,
       NIVEL_PRECIO		VARCHAR(12)   		NOT NULL,
       MONEDA_NIVEL             VARCHAR(1) 		NOT NULL,
       USAR_NIVEL_CLIENTE 	VARCHAR(1)		NOT NULL,
       USAR_BLOQUEO_AUTOM 	VARCHAR(1)      	NOT NULL,
       TIEMPO_BLOQUEO           INT			NULL,
       CTR_ABONOS		VARCHAR(25)		NULL,
       CTA_ABONOS		VARCHAR(25)		NULL,
       CTR_CIERRE_CREDITO	VARCHAR(25)		NULL,
       CTA_CIERRE_CREDITO	VARCHAR(25)		NULL,
       CTR_CIERRE_DEBITO	VARCHAR(25)		NULL,
       CTA_CIERRE_DEBITO	VARCHAR(25)		NULL,
       CTR_DIFER_INGRESO	VARCHAR(25)		NULL,
       CTA_DIFER_INGRESO	VARCHAR(25)		NULL,
       CTR_DIFER_EGRESO		VARCHAR(25)		NULL,
       CTA_DIFER_EGRESO		VARCHAR(25)		NULL,
       TIPO_CONTA_OMISION	VARCHAR(1)		NULL,
       CTR_OTROS_INGRESOS	VARCHAR(25)		NULL, 
       CTA_OTROS_INGRESOS	VARCHAR(25)		NULL,
       USAR_FECHA_DADA		VARCHAR(1)		NOT NULL,
       CAMPOS_OBLIG_TARJ 	VARCHAR(1) 		NOT NULL,
       IMPR_DESC_LINEAS 	VARCHAR(1) 		NOT NULL,
       MODIF_COD_CLIENTE 	VARCHAR(1) 		NOT NULL,
       VALID_PAGO_DEV_FAC 	VARCHAR(1) 		NOT NULL,
       CTR_BONO 		VARCHAR(25) 		NULL,
       CTA_BONO 		VARCHAR(25) 		NULL,
       MODIF_CLNTS_CONT        	VARCHAR(1) 		NOT NULL,
       DEVOLUCION_EFECTIVO  	VARCHAR(1)  		NOT NULL,
       DEVOLUCION_CHEQUE  	VARCHAR(1)  		NOT NULL,
       DEVOLUCION_TARJETA   	VARCHAR(1)  		NOT NULL,
       DEVOLUCION_CREDITO   	VARCHAR(1)  		NOT NULL,
       DEVOLUCION_VALE  	VARCHAR(1)  		NOT NULL,
       DEVOLUCION_BONO   	VARCHAR(1)  		NOT NULL,
       DEVOLUCION_DOLAR  	VARCHAR(1)  		NOT NULL,
       LIMITAR_LINEAS 		VARCHAR(1) 		NOT NULL,
       CANT_LINEAS_DOCUM  	INT 			NULL,
       CAPTURA_FECHA_NAC  	VARCHAR(1) 		NOT NULL,
       CAPTURA_NIT	  	VARCHAR(1) 		NOT NULL,
       CAPTURA_TELEFONO  	VARCHAR(1) 		NOT NULL,
       AUTOR_DESC_MONTO  	VARCHAR(1) 		NOT NULL,
       USO_FORMULARIOS  	VARCHAR(1) 		NOT NULL,
       VIS_MOD_NUM_DOC  	VARCHAR(1) 		NOT NULL,
       DEV_MENU_PRINCIPAL  	VARCHAR(1) 		NOT NULL,
       USAR_NOTASCREDITO  	VARCHAR(1) 		NOT NULL,
       IMPRIMIR_ULT_ABONO	VARCHAR(1) 		NOT NULL,
       FACTURA_AL_APARTAR 	VARCHAR(1) 		NOT NULL,
       CLIENTE_APARTADO		VARCHAR(20) 		NULL,
       DESG_CIERRE_CAJERO 	VARCHAR(1) 		NOT NULL,
       CONTROL_INFO_FISCAL	VARCHAR(1) 		NOT NULL,
       AUTO_CAMBIO_PRECIO 	VARCHAR(1) 		NOT NULL,
       CONDPAG_VENC_APART	VARCHAR(4) 		NOT NULL,
       USA_APA_CNDPAG_CLI 	VARCHAR(1) 		NOT NULL,
       CTA_VTA_APARTADO 	VARCHAR(25) 		NULL,
       CTR_VTA_APARTADO 	VARCHAR(25) 		NULL,
       CATEGORIA_CLIENTE 	VARCHAR(8) 		NOT NULL,
       PORC_MIN_PRI_ABONO 	DECIMAL(28,8) 		NOT NULL,
       CONTROL_CXC 		VARCHAR(1) 		NOT NULL,
       CTA_DEVOL_DINERO 	VARCHAR(25) 		NULL,
       CTR_DEVOL_DINERO 	VARCHAR(25) 		NULL,
       CONSECUTIVO_DEVOL 	VARCHAR(10)		NULL,
       CTA_INV_DESPACHAR 	VARCHAR(25) 		NULL,
       CTR_INV_DESPACHAR 	VARCHAR(25) 		NULL,
       CALCULAR_IMP2 		VARCHAR(1) 		NOT NULL,
       PORC_DEVEFE_ANUAPA	DECIMAL(28,8)		NOT NULL,
       DIAS_VIGENCIA_DEV 	DECIMAL(28,8) 		NOT NULL,
       TIPO_CAMBIO_CIERRE 	VARCHAR(1) 		NOT NULL,
       USAR_CADENAS 		VARCHAR(1) 		NOT NULL,
       CTR_EFECTIVO_LOCAL 	VARCHAR(25) 		NULL,
       CTA_EFECTIVO_LOCAL 	VARCHAR(25) 		NULL,
       CTR_EFECTIVO_DOLAR 	VARCHAR(25) 		NULL,
       CTA_EFECTIVO_DOLAR 	VARCHAR(25) 		NULL,
       CTR_CHEQUE		VARCHAR(25) 		NULL,
       CTA_CHEQUE		VARCHAR(25) 		NULL,
       CTR_NOTACREDITO		VARCHAR(25)		NULL,
       CTA_NOTACREDITO		VARCHAR(25)		NULL,
       CTR_CERTIFICADO		VARCHAR(25)		NULL,
       CTA_CERTIFICADO		VARCHAR(25)		NULL,
       CTR_CERTIF_OBSEQUI	VARCHAR(25)		NULL,
       CTA_CERTIF_OBSEQUI	VARCHAR(25)		NULL,
       CTR_CERTIF_VENCIDO	VARCHAR(25)		NULL,
       CTA_CERTIF_VENCIDO	VARCHAR(25)		NULL,
       CTR_NC_VENCIDA		VARCHAR(25)		NULL,
       CTA_NC_VENCIDA		VARCHAR(25)		NULL,
       CONTABILIZAR_DIA		VARCHAR(1)  		NOT NULL,
       CONTABILIZAR_CAJA	VARCHAR(1)  		NOT NULL,
       CONTABILIZAR_TRANS	VARCHAR(1)  		NOT NULL,
       CONTABILIZAR_PAGOS	VARCHAR(1)  		NOT NULL,
       DIAS_VIGENCIA_CERT 	INT 			NOT NULL,
       SITIO_LOCAL 		VARCHAR(20)  		NULL,
       TIPO_SITIO_LOCAL		VARCHAR(1) 		NULL,
       BODEGA_CENTRAL 		VARCHAR(4)   		NULL,
       TRASPASO_TIENDA		VARCHAR(1)   		NULL,
       USUARIO_WSQM		VARCHAR(25)   		NULL,
       USA_BIMONEDA 		VARCHAR(1) 		NOT NULL,
       DIAS_GRACIA 		INT			NOT NULL,
       MANEJA_SERIES		VARCHAR(1)		NOT NULL,
       CIERRE_CAJERO 		VARCHAR(1) 		NOT NULL,
       MODIF_INFO_FISCAL 	VARCHAR(1)		NOT NULL,
       PORC_AUMEN_PRE		DECIMAL (28, 8)		NOT NULL,
       PORC_DISMIN_PRE		DECIMAL (28, 8)		NOT NULL,
       SOLO_CERT_CLIENTE	VARCHAR(1)		NOT NULL,
       SUBT_CRED_FISCAL	        INT			NOT NULL,
       VALIDA_PRELECTURA	VARCHAR(1)		NOT NULL,
       LOCALIZACION		VARCHAR(8)  		NULL,
       MULT_CORRELATIVO		VARCHAR(1)		NOT NULL,
       TIENDA_OFF_LOCAL 	VARCHAR(20) 		NULL,
       TIPO_TIENDA 		VARCHAR(1) 		NOT NULL DEFAULT 'C'
)
go

CREATE TABLE GRUPO (
       GRUPO            	VARCHAR(6) 		NOT NULL,
       DESCRIPCION		VARCHAR(40) 		NULL,
       SUCURSAL         	VARCHAR(1) 		NOT NULL,
       LINEA_SUPERIOR1		VARCHAR(254) 		NULL,
       LINEA_SUPERIOR2      	VARCHAR(254) 		NULL,
       LINEA_SUPERIOR3      	VARCHAR(254) 		NULL,
       LINEA_SUPERIOR4      	VARCHAR(254) 		NULL,
       LINEA_INFERIOR1      	VARCHAR(254) 		NULL,
       LINEA_INFERIOR2      	VARCHAR(254) 		NULL,
       LINEA_INFERIOR3      	VARCHAR(254) 		NULL,
       LINEA_INFERIOR4      	VARCHAR(254) 		NULL,
       ULT_CIERRE 		INT			NULL,
       FECHA			DATETIME		NULL,
       ABONO_APRT_VENCIDO 	VARCHAR(1) 		NOT NULL,
       NIVEL_PRECIO 		VARCHAR(12) 		NOT NULL,
       MONEDA_NIVEL 		VARCHAR(1) 		NOT NULL,
       CADENA 			VARCHAR(20) 		NULL,
       CONSECUTIVO_CI		VARCHAR(10) 		NULL,
       CONSEC_CIERRE 		VARCHAR(20) 		NULL,
	   NCF_UNICO VARCHAR(50) NULL
)
go

ALTER TABLE GRUPO
       ADD CONSTRAINT XPKGRUPO PRIMARY KEY (GRUPO)
go


CREATE TABLE GRUPO_CAJA (
       GRUPO			VARCHAR(6) 		NOT NULL,
       CAJA     		VARCHAR(6) 		NOT NULL
)
go

ALTER TABLE GRUPO_CAJA
       ADD CONSTRAINT XPKGRUPO_CAJA PRIMARY KEY (GRUPO, CAJA)
go



CREATE TABLE HIST_MEMBRESIA_POS  (
	MEMBRESIA       	VARCHAR(25)  	NOT NULL ,
	DOCUMENTO       	VARCHAR(50)  	NOT NULL ,
	TIPO            	VARCHAR(1)   	NOT NULL ,
	CAJA            	VARCHAR(6)   	NOT NULL ,
	TIPO_OPERACION  	VARCHAR(1)   	NOT NULL 
)
go


ALTER TABLE HIST_MEMBRESIA_POS ADD CONSTRAINT	XPHISTMEMBRESIA 
	     PRIMARY KEY  NONCLUSTERED (MEMBRESIA, DOCUMENTO, TIPO, CAJA)
go




CREATE TABLE INCONSIST_INV_POS (
         CONSECUTIVO		INT			NOT NULL,
         FECHA         		DATETIME		NOT NULL,
         DOCUMENTO         	VARCHAR(50)		NOT NULL,
         TIPO         		VARCHAR(1)		NOT NULL,
         CAJA         		VARCHAR(6)		NOT NULL,
         ARTICULO         	VARCHAR(20)		NOT NULL,
         CANT_REBAJADA      	DECIMAL(28,8)		NOT NULL,
         CANT_NO_REBAJADA	DECIMAL(28,8)		NOT NULL,
         BODEGA         	VARCHAR(4)		NOT NULL,
         LOTE         		VARCHAR(15)		NOT NULL,
         LOCALIZACION       	VARCHAR(8)		NOT NULL,
         COSTO_MISCELANEO 	DECIMAL(28, 8) 		NOT NULL DEFAULT(0)
)
go

ALTER TABLE INCONSIST_INV_POS
       ADD CONSTRAINT XPKINCONSIST_INV_POS PRIMARY KEY (CONSECUTIVO)
go


CREATE TABLE INCONSISTENCIA_SINC_POS(
	INCONSISTENCIA		INT	IDENTITY(1,1)	NOT NULL,
	FECHA			DATETIME		NOT NULL,
	TIENDA			VARCHAR(6)		NOT NULL,
	CATALOGO		VARCHAR(80)		NOT NULL,
	DATO_ESPECIAL 		VARCHAR(254)		NULL,
	MENSAJE_ERR		VARCHAR(8000)		NULL,
	DATOS			XML			NOT NULL
)
go


CREATE TABLE INFO_DOC_SEGURO (
	ASEGURADORA		VARCHAR(20)		NOT NULL,
	AFILIADO		VARCHAR(20)		NOT NULL,
	DOCUMENTO		VARCHAR(50)		NOT NULL,
	CAJA			VARCHAR(6)		NOT NULL,
	TIPO			VARCHAR(1)		NOT NULL,
	PAGO			VARCHAR(4)		NOT NULL,
	CENTRO_MEDICO   	VARCHAR(80)		NOT NULL,
	DIAGNOSTICO		VARCHAR(254)		NOT NULL,
	MEDICO			VARCHAR(80)		NOT NULL,
	ESPECIALIDAD		VARCHAR(80)		NOT NULL,
	CONTRATO		VARCHAR(80)		NULL
)
go



ALTER TABLE INFO_DOC_SEGURO  ADD CONSTRAINT XPKINFODOCSEGURO 
		PRIMARY KEY NONCLUSTERED (AFILIADO, ASEGURADORA, PAGO, DOCUMENTO, TIPO, CAJA)
go
		

CREATE TABLE INFO_REG_BILLETE (
	DOCUMENTO		VARCHAR(50)		NOT NULL,
	CAJA			VARCHAR(6)		NOT NULL,
	TIPO			VARCHAR(1)		NOT NULL,
	PAGO			VARCHAR(4)		NOT NULL,
	IDENTIFICACION		VARCHAR(80)		NOT NULL,
	CLIENTE			VARCHAR(80)		NOT NULL,	
	TELEFONO		VARCHAR(15)		NULL	
)
go


ALTER TABLE INFO_REG_BILLETE ADD CONSTRAINT XPKINFOREGBILLETE
		PRIMARY KEY NONCLUSTERED (IDENTIFICACION, PAGO, DOCUMENTO, TIPO, CAJA)
go
		



CREATE TABLE MEMBRESIA_POS (	
	MEMBRESIA               VARCHAR(25)  	NOT NULL ,
	CLIENTE                 VARCHAR(20)  	NOT NULL ,
	FECHA_EMISION           DATETIME     	NOT NULL ,
	USUARIO_EMISION         VARCHAR(25)  	NOT NULL ,
	FECHA_VENCE             DATETIME     	NOT NULL ,
	FECHA_VENCE_ANT         DATETIME     	NULL ,
	ESTADO                  VARCHAR(1)   	NOT NULL ,
	APLICA_DESC_VENTA       VARCHAR(1)   	NOT NULL ,
	APLICA_DESC_RENOVACION  VARCHAR(1)   	NOT NULL ,		
	ES_EXTERIOR             VARCHAR(1)   	NOT NULL ,
	PAIS_ORIGEN             VARCHAR(4)  	NULL ,
	USUARIO_AUTORIZA_ING    VARCHAR(25)  	NULL ,	
	FECHA_RENOVACION        DATETIME     	NULL ,
	USUARIO_RENOVACION      VARCHAR(25)  	NULL ,
	FECHA_REPOSICION        DATETIME     	NULL ,	
	USUARIO_REPOSICION      VARCHAR(25)  	NULL ,
	MEMBRESIA_REPUESTA      VARCHAR(25)  	NULL ,	
    	OBSERVACIONES           VARCHAR(254) 	NULL	
)
go



ALTER TABLE MEMBRESIA_POS  ADD CONSTRAINT  XPMEMBRESIAPOS
	        PRIMARY KEY   NONCLUSTERED (MEMBRESIA)
go





CREATE TABLE MENSAJERO 
(
       MENSAJERO		VARCHAR(10) 		NOT NULL,
       NOMBRE			VARCHAR(100) 		NOT NULL,
       ROTATIVO			VARCHAR(1) 		NOT NULL,
       TIENDA			VARCHAR(6) 		NULL
)
go

ALTER TABLE MENSAJERO   
	ADD CONSTRAINT XPKMENSAJERO PRIMARY KEY NONCLUSTERED  (MENSAJERO)
go


CREATE TABLE MONITOR_CATEGORIA (
   MONITOR_CATEGORIA      VARCHAR(50)   NOT NULL,
   NOMBRE                 VARCHAR(80)   NOT NULL,
   DESCRIPCION            VARCHAR(254)  NULL,
   IMAGEN                 VARCHAR(MAX)  NULL
)
go

ALTER TABLE MONITOR_CATEGORIA
        ADD CONSTRAINT XPKMONITORCATEGORIA
            PRIMARY KEY NONCLUSTERED (MONITOR_CATEGORIA)
go


CREATE TABLE MONITOR_CONSULTA (
   MONITOR_CONSULTA     VARCHAR(50)   NOT NULL,  
   NOMBRE               VARCHAR(80)   NOT NULL,
   DESCRIPCION          VARCHAR(254)  NULL,
   MONITOR_CATEGORIA    VARCHAR(50)   NOT NULL,
   TIPO_CONSULTA        VARCHAR(1)    NOT NULL DEFAULT('C'),    
   TIPO_VISUALIZACION   VARCHAR(1)    NOT NULL DEFAULT('N'),    
   IMAGEN               VARCHAR(MAX)  NULL,
   CONSULTA             TEXT          NOT NULL
)
go

ALTER TABLE MONITOR_CONSULTA
        ADD CONSTRAINT   XPKMONITORCONSULTA 
          PRIMARY KEY NONCLUSTERED (MONITOR_CONSULTA, MONITOR_CATEGORIA)
go


CREATE TABLE MONITOR_COLUMNAS (
   COLUMNA              VARCHAR(80)   NOT NULL,
   MONITOR_CONSULTA     VARCHAR(50)   NOT NULL,  
   MONITOR_CATEGORIA    VARCHAR(50)   NOT NULL,
   COLUMNA_SQL          VARCHAR(32)   NOT NULL,
   TITULO               VARCHAR(80)   NOT NULL,
   DESCRIPCION          VARCHAR(254)  NULL,
   CONJUNTO_DATOS       VARCHAR(508)  NULL,                  
   ANCHO                INT           NULL,
   ALINEADO             VARCHAR(1)    NOT NULL DEFAULT('I'),
   TIPO                 VARCHAR(1)    NOT NULL DEFAULT('T'), 
   PERMITE_ORDENAR      VARCHAR(1)    NOT NULL DEFAULT('S'),
   ORDEN_SUGERIDO       VARCHAR(1)    NOT NULL DEFAULT('S'), 
   PERMITE_FILTRAR      VARCHAR(1)    NOT NULL DEFAULT('N'),
   PERMITE_AGRUPAR      VARCHAR(1)    NOT NULL DEFAULT('N')
) 
go

ALTER TABLE MONITOR_COLUMNAS
        ADD CONSTRAINT XPKMONITORCOLUMNAS
          PRIMARY KEY NONCLUSTERED(COLUMNA, MONITOR_CONSULTA, MONITOR_CATEGORIA)
go


CREATE TABLE MOTIVO_CANCEL_EXPR
(
	CODIGO			VARCHAR(10) 		NOT NULL,
	DESCRIPCION		VARCHAR(80)	 	NOT NULL
)
go

ALTER TABLE MOTIVO_CANCEL_EXPR   
	ADD CONSTRAINT XPKMOTIVOCANCELEXPR PRIMARY KEY NONCLUSTERED  (CODIGO)
go


CREATE TABLE NCF_CAJA_POS( 
       CAJA				VARCHAR(6)		NOT NULL,
       TIPO 			VARCHAR(6) 		NOT NULL,
       PREFIJO 			VARCHAR(50) 		NOT NULL,
       TIPO_DOC_POS		VARCHAR(1)		NOT NULL,
	   SECUENCIA 		INT NULL
)
go

ALTER TABLE NCF_CAJA_POS ADD CONSTRAINT XPKNCF_CAJA_POS
	PRIMARY KEY (CAJA, PREFIJO)
go


CREATE TABLE PAGO_POS (
       DOCUMENTO            	VARCHAR(50)		NOT NULL,
       PAGO                 	VARCHAR(4) 		NOT NULL,
       CAJA                 	VARCHAR(6) 		NOT NULL,
       TIPO			VARCHAR(1) 		NOT NULL,
       CONDICION_PAGO       	VARCHAR(4) 		NULL,
       ENTIDAD_FINANCIERA	VARCHAR(8) 		NULL,
       TIPO_TARJETA         	VARCHAR(12) 		NULL,
       FORMA_PAGO           	VARCHAR(4) 		NOT NULL,
       NUMERO               	VARCHAR(80) 		NULL,
       MONTO_LOCAL          	DECIMAL(28,8) 		NOT NULL,
       MONTO_DOLAR          	DECIMAL(28,8) 		NOT NULL,
       AUTORIZACION         	VARCHAR(80) 		NULL,
       FECHA_EXPIRACION     	VARCHAR(5) 		NULL,
       COBRO			INT 			NULL,
       CLIENTE_LIQUIDADOR	VARCHAR(20) 		NULL,
       TIPO_COBRO		VARCHAR(1) 		NOT NULL DEFAULT ('T'),
       REFERENCIA 		VARCHAR(80) 		NULL,
       NUM_SEGUIMIENTO 		VARCHAR(80) 		NULL,
       NUM_TRANSAC_TARJETA 	VARCHAR(50) 		NULL,
       CAMPO1 			VARCHAR(30) 		NULL,
       VALOR1 			VARCHAR(50) 		NULL,
       CAMPO2 			VARCHAR(30) 		NULL,
       VALOR2 			VARCHAR(50) 		NULL,
       CAMPO3 			VARCHAR(30) 		NULL,
       VALOR3 			VARCHAR(50) 		NULL,
       CAMPO4 			VARCHAR(30) 		NULL,
       VALOR4 			VARCHAR(50) 		NULL,
       CAMPO5 			VARCHAR(30) 		NULL,
       VALOR5 			VARCHAR(50) 		NULL,
       CAMPO6 			VARCHAR(30) 		NULL,
       VALOR6 			VARCHAR(50) 		NULL
)
go

ALTER TABLE PAGO_POS 
	ADD CONSTRAINT XPKPAGO_POS PRIMARY KEY NONCLUSTERED(PAGO, DOCUMENTO, TIPO, CAJA)
go 


CREATE TABLE PERFIL_CLIENTE (
       PERFIL           	VARCHAR(4) 		NOT NULL,
       DESCRIPCION		VARCHAR(40)		NULL,
       MODIFICADOR      	DECIMAL(28,8) 		NOT NULL
)
go

ALTER TABLE PERFIL_CLIENTE
       ADD CONSTRAINT XPKPERFIL_CLIENTE PRIMARY KEY (PERFIL)
go


CREATE TABLE RESOLUCION_POS (
       RESOLUCION		VARCHAR(20) 		NOT NULL,
       CAJA 			VARCHAR(6) 		NOT NULL,
       TIPO_DOCUMENTO		VARCHAR(1) 		NOT NULL,
       FECHA_RESOLUCION		DATETIME 		NULL,
       FECHA_AUTORIZACION	DATETIME 		NULL,
       FECHA_CREACION		DATETIME 		NULL,
       SERIE			VARCHAR(25) 		NOT NULL,
       MASCARA			VARCHAR(50)		NOT NULL,
       CONSEC_INICIAL		VARCHAR(50) 		NOT NULL,
       CONSEC_FINAL		VARCHAR(50) 		NOT NULL,
       VALOR			VARCHAR(50) 		NOT NULL,
       ESTADO			VARCHAR(1) 		NOT NULL,
       USUARIO_CREACION		VARCHAR(25) 		NOT NULL,
       SIN_VENCIMIENTO 		VARCHAR(1)		NOT NULL 	DEFAULT('N')
)
go

ALTER TABLE RESOLUCION_POS
	ADD  CONSTRAINT XPKRESOLUCIONPOS PRIMARY KEY NONCLUSTERED (RESOLUCION, CAJA)
go



CREATE TABLE REGLA_COMISION (
       COMISION            	VARCHAR(6)		NOT NULL,
       DESCRIPCION		VARCHAR(60)		NOT NULL,
       PRIORIDAD		INT			NOT NULL,
       ESTADO			VARCHAR(1)     		NOT NULL,
       PORC_COMISION	   	DECIMAL(28,8)  		NOT NULL,
       CLASIFICACION_1  	VARCHAR(12)    		NULL,
       CLASIFICACION_2  	VARCHAR(12)    		NULL,
       CLASIFICACION_3  	VARCHAR(12)    		NULL,
       CLASIFICACION_4  	VARCHAR(12)    		NULL,
       CLASIFICACION_5  	VARCHAR(12)    		NULL,
       CLASIFICACION_6  	VARCHAR(12)    		NULL
)
go	

ALTER TABLE REGLA_COMISION  
	ADD CONSTRAINT XPKREGLACOMISION PRIMARY KEY NONCLUSTERED  (COMISION)
go	


CREATE TABLE SITIO_TIENDA (
       TIENDA               	VARCHAR(20) 		NOT NULL,
       SITIO                	VARCHAR(20) 		NOT NULL
)
go

ALTER TABLE SITIO_TIENDA
       ADD CONSTRAINT XPKSITIO_TIENDA PRIMARY KEY (TIENDA, SITIO)
go


CREATE TABLE SUPERVISOR (
       SUPERVISOR           	VARCHAR(25) 		NOT NULL,
       GRUPO                	VARCHAR(6)  		NULL,
       SUPERUSUARIO         	VARCHAR(1)  		NOT NULL
)
go

ALTER TABLE SUPERVISOR
       ADD CONSTRAINT XPKSUPERVISOR PRIMARY KEY (SUPERVISOR)
go


CREATE TABLE TEMP_SITIO (
       SITIO                 	VARCHAR(20) 		NULL,
       DESCRIPCION           	VARCHAR(40) 		NULL
)
go


CREATE TABLE TIENDA_OFF_GRUPO (
       TIENDA_OFF              	VARCHAR(20) 	NOT NULL,
       GRUPO                	VARCHAR(6) 	NOT NULL
)
go


ALTER TABLE TIENDA_OFF_GRUPO ADD CONSTRAINT XPKTIENDA_OFF_GRUPO PRIMARY KEY (TIENDA_OFF, GRUPO)
go


CREATE TABLE TIENDA_OFFLINE(
	TIENDA_OFF		VARCHAR(20)		NOT NULL,
	DESCRIPCION		VARCHAR(80)		NOT NULL,
	ACTIVO			VARCHAR(1)		NOT NULL DEFAULT ('S'),
	DESCONECTADO		VARCHAR(1)		NOT NULL DEFAULT ('N'),
	CENTRAL_PADRE		VARCHAR(20)		NULL,
	FECHA_ULT_ENVIO		DATETIME		NULL,
	FECHA_ULT_RECEPCION	DATETIME		NULL,
	FECHA_HORA_SINCRO 	DATETIME 		NULL
)
go


ALTER TABLE TIENDA_OFFLINE  ADD CONSTRAINT XPKTIENDAOFF PRIMARY KEY  NONCLUSTERED (TIENDA_OFF)
go


CREATE TABLE TIPO_DOC_DEFAULT (
       CAJA               	VARCHAR(6) 		NOT NULL,
       CONSEC_DEFAULT	  	VARCHAR(10) 		NOT NULL,
       TIPO_DOCUMENTO     	VARCHAR(1) 		NOT NULL,
       FORMATO_DEFAULT    	VARCHAR(30) 		NULL
)
go

ALTER TABLE TIPO_DOC_DEFAULT 
       ADD CONSTRAINT XPKTIPODOCDEFAULT PRIMARY KEY NONCLUSTERED  (CAJA, CONSEC_DEFAULT, TIPO_DOCUMENTO)
go
  

CREATE TABLE TIPO_TARJETA_CAJA
(
	TIPO_TARJETA 		VARCHAR(12) 	NOT NULL,
	CAJA          		VARCHAR(6)	NOT NULL,
	CONSECUTIVO_TARJETA 	VARCHAR(50) 	NOT NULL DEFAULT ('000000000000')
)
go

ALTER TABLE TIPO_TARJETA_CAJA 
       ADD CONSTRAINT XPKTIPO_TARJETA_CAJA PRIMARY KEY NONCLUSTERED (TIPO_TARJETA, CAJA)
go


CREATE TABLE TIPO_TARJETA_POS (
        TIPO_TARJETA          		VARCHAR(12)  	NOT NULL,
        CLIENTE				VARCHAR(20)	NOT NULL,
        COMISION 			DECIMAL(28,8) 	NOT NULL,
        CTR_AUTORIZADOR 		VARCHAR(25) 	NULL,
        CTA_AUTORIZADOR 		VARCHAR(25) 	NULL,
        CTR_COMISION 			VARCHAR(25) 	NULL,
        CTA_COMISION 			VARCHAR(25) 	NULL,
        TIPO_COBRO 			VARCHAR(1) 	NOT NULL DEFAULT ('T'),
       	CONFIGURACION_PAGO    		VARCHAR(1) 	NOT NULL DEFAULT ('M'),
       	PORCENTAJE_PAGO			DECIMAL(28,8) 	NULL,
       	PORCENTAJE_FIJO			VARCHAR(1)	NOT NULL DEFAULT ('N'),
       	NCF_FACTURA			VARCHAR(20)	NULL,
       	NCF_DEVOLUCION			VARCHAR(20)	NULL,
       	CONFIGURACION_COBRO   		VARCHAR(1) 	NOT NULL DEFAULT ('C'),
       	TIPO_CONF_COBRO_CLIENTE 	VARCHAR(1) 	NOT NULL DEFAULT ('N'),
	GENERAR_COBRO			VARCHAR(1)	NOT NULL DEFAULT ('N'),
	TIPO_DOC_CXC			VARCHAR(3) 	NULL,
	SUBTIPO_DOC_CXC			SMALLINT 	NULL,
	TIPO_DOC_COMISION		VARCHAR(3) 	NULL,
	SUBTIPO_DOC_COMISION		SMALLINT 	NULL
)
go



ALTER TABLE TIPO_TARJETA_POS ADD CONSTRAINT XPKTIPO_TARJETA_POS 
		PRIMARY KEY  NONCLUSTERED (TIPO_TARJETA, CLIENTE, TIPO_COBRO)
go


CREATE TABLE TRASPASO_POS (
       CONSECUTIVO_CI       	VARCHAR(10) 		NOT NULL,
       DOCUMENTO            	VARCHAR(50) 		NOT NULL,
       FECHA                	DATETIME		NOT NULL,
       BODEGA_ORIGEN        	VARCHAR(4) 		NOT NULL,
       BODEGA_DESTINO       	VARCHAR(4) 		NOT NULL,
       ESTADO	            	VARCHAR(1) 		NOT NULL,
       EXPORTADO            	VARCHAR(1) 		NOT NULL,
       EXPORTADO_TIENDA     	VARCHAR(1) 		NULL,
       LOCAL                	VARCHAR(1) 		NOT NULL,
       OBSERVACIONES	    	VARCHAR(254) 		NULL,
       PAQUETE_INV		VARCHAR(4)		NULL
)
go

ALTER TABLE TRASPASO_POS
       ADD CONSTRAINT XPKTRASPASO_POS PRIMARY KEY (CONSECUTIVO_CI, DOCUMENTO)
go


CREATE TABLE TRASPASO_POS_DET (
       CONSECUTIVO_CI       	VARCHAR(10) 		NOT NULL,
       DOCUMENTO            	VARCHAR(50) 		NOT NULL,
       LINEA 			INT 			NOT NULL,
       ARTICULO             	VARCHAR(20) 		NOT NULL,
       CANTIDAD             	DECIMAL(28,8)		NOT NULL,
       LOTE		    	VARCHAR(15) 		NULL,
       BODEGA_ORIGEN        	VARCHAR(4) 		NULL,
       BODEGA_DESTINO       	VARCHAR(4) 		NULL
)
go

ALTER TABLE TRASPASO_POS_DET
       ADD CONSTRAINT XPKTRASPASO_POS_DET PRIMARY KEY (CONSECUTIVO_CI, DOCUMENTO, LINEA)
go


CREATE TABLE UNIDAD_FRACCION (
       UNIDAD_MEDIDA		VARCHAR(6) 		NOT NULL,
       FRACCION         	VARCHAR(1) 		NOT NULL,
       BALANZA_ELECTRONICA 	VARCHAR(1) 		NOT NULL DEFAULT('N')
)
go
 
ALTER TABLE UNIDAD_FRACCION
       ADD CONSTRAINT XPKUNIDAD_FRACCION PRIMARY KEY (UNIDAD_MEDIDA)
go



CREATE TABLE TEMP_CONFIG_PAR_SITIO(
       SUSCRIPTOR		VARCHAR(20) 		NULL,
       PUBLICADOR		VARCHAR(20) 		NULL
)
go



CREATE TABLE CUENTA_CONTABLE (
        CUENTA_CONTABLE      	VARCHAR(25)  NOT NULL,
        SECCION_CUENTA       	VARCHAR(4) 	 NULL,
        UNIDAD               	VARCHAR(15)  NULL,
        DESCRIPCION          	VARCHAR(200) NOT NULL,
        TIPO                 	VARCHAR(1) 	 NOT NULL,
        TIPO_DETALLADO       	VARCHAR(1) 	 NOT NULL,
        TIPO_OAF             	VARCHAR(1) 	 NOT NULL,
        SALDO_NORMAL         	VARCHAR(1) 	 NOT NULL,
        CONVERSION           	VARCHAR(1) 	 NOT NULL,
        TIPO_CAMBIO          	VARCHAR(4) 	 NOT NULL,
        ACEPTA_DATOS         	VARCHAR(1) 	 NOT NULL,
        CONSOLIDA            	VARCHAR(1) 	 NOT NULL,
        USA_CENTRO_COSTO     	VARCHAR(1) 	 NOT NULL,
        NOTAS                	TEXT 		 NULL,
        USUARIO              	VARCHAR(25)  NOT NULL,
        FECHA_HORA           	DATETIME 	 NOT NULL,
        USUARIO_ULT_MOD      	VARCHAR(25)  NOT NULL,
        FCH_HORA_ULT_MOD     	DATETIME 	 NOT NULL,
        ACEPTA_UNIDADES      	VARCHAR(1) 	 NOT NULL,
        USO_RESTRINGIDO      	VARCHAR(1) 	 NOT NULL,
        ORIGEN_CONVERSION    	VARCHAR(1)	 NULL,
        VALIDA_PRESUP_CR		VARCHAR(1)	 NOT NULL 	DEFAULT('N'),
        CUENTA_IFRS 			VARCHAR(25)  NULL,
        USA_CONTA_ELECTRO 		VARCHAR(1) 	 NOT NULL 	DEFAULT ('N'),
		VERSION					VARCHAR(5) 	 NOT NULL     	DEFAULT ('1.0'),
		FECHA_INI_CE 			DATETIME     NULL,
		FECHA_FIN_CE 			DATETIME     NULL,
		COD_AGRUPADOR 			VARCHAR(15)  NULL,
		DESC_COD_AGRUP 			VARCHAR(60)  NULL,
		SUB_CTA_DE 				VARCHAR(100) NULL,
		DESC_SUB_CTA 			VARCHAR(100) NULL,
		NIVEL 					VARCHAR(5) 	 NULL,
		DESCRIPCION_IFRS        VARCHAR(200) NULL,
		MANEJA_TERCERO  		VARCHAR(1) NOT NULL DEFAULT 'S'
)
go

 ALTER TABLE CUENTA_CONTABLE
        ADD CONSTRAINT XPKCUENTA_CONTABLE PRIMARY KEY NONCLUSTERED (
               CUENTA_CONTABLE)
go               


 CREATE TABLE CENTRO_CUENTA (
        CENTRO_COSTO         VARCHAR(25) 	NOT NULL,
        CUENTA_CONTABLE      VARCHAR(25) 	NOT NULL,
        ESTADO               VARCHAR(1) 	NOT NULL,
        CENTRO_POZO          VARCHAR(25) 	NULL,
        CUENTA_POZO          VARCHAR(25) 	NULL,
        CENTRO_GASTO         VARCHAR(25) 	NULL,
        CUENTA_GASTO         VARCHAR(25) 	NULL,
        CENTRO_CONSOLIDA     VARCHAR(25) 	NULL,
        CUENTA_CONSOLIDA     VARCHAR(25) 	NULL
)
go
 
ALTER TABLE CENTRO_CUENTA
        ADD CONSTRAINT CENTRO_CUENTAPK PRIMARY KEY NONCLUSTERED (
               CENTRO_COSTO, CUENTA_CONTABLE)
go               
               

CREATE TABLE PAQUETE (
        PAQUETE              	VARCHAR(4) 	NOT NULL,
        DESCRIPCION          	VARCHAR(40) 	NOT NULL,
        USUARIO_CREADOR      	VARCHAR(25) 	NOT NULL,
        ULTIMO_USUARIO       	VARCHAR(25) 	NOT NULL,
        FECHA_ULT_ACCESO     	DATETIME 	NOT NULL,
        ULTIMO_ASIENTO       	VARCHAR(10) 	NOT NULL,
        DOBLE_ASIENTO        	VARCHAR(1) 	NOT NULL,
        MARCADO              	VARCHAR(1) 	NOT NULL,
        USA_DOBLE_ASIENTO    	VARCHAR(1) 	NOT NULL DEFAULT 'N',
        ULTIMO_ASIENTO_CORP 	VARCHAR(10) 	NULL
)
go
 
 
 ALTER TABLE PAQUETE
        ADD CONSTRAINT PAQUETEPK PRIMARY KEY NONCLUSTERED (PAQUETE)
go
 
 
 
 CREATE TABLE TIPO_ASIENTO (
        TIPO_ASIENTO         VARCHAR(4) 	NOT NULL,
        DESCRIPCION          VARCHAR(40) 	NOT NULL
)
go
 
 ALTER TABLE TIPO_ASIENTO
        ADD CONSTRAINT TIPO_ASIENTOPK PRIMARY KEY NONCLUSTERED (
               TIPO_ASIENTO)
go



 CREATE TABLE CUENTA_BANCARIA (
        CUENTA_BANCO         	VARCHAR(20)	NOT NULL,
        NOMBRE               	VARCHAR(40)	NOT NULL,
        ENTIDAD_FINANCIERA   	VARCHAR(8) 	NOT NULL,
        MONEDA               	VARCHAR(4) 	NOT NULL,
        DIRECCION            	VARCHAR(90)	NOT NULL,
        TELEFONO1            	VARCHAR(15)	NOT NULL,
        TELEFONO2            	VARCHAR(15)	NOT NULL,
        CONTACTO             	VARCHAR(40)	NOT NULL,
        CARGO                	VARCHAR(40)	NOT NULL,
        FORMATO              	VARCHAR(128) 	NOT NULL,
        FECHA_ULT_MOV        	DATETIME 	NOT NULL,
        SALDO                	DECIMAL(28,8) 	NOT NULL,
        SALDO_BANCOS         	DECIMAL(28,8) 	NOT NULL,
        POSICION_DE_CAJA     	DECIMAL(28,8) 	NOT NULL,
        SALDO_ANTERIOR       	DECIMAL(28,8) 	NOT NULL,
        TIPO_CAMBIO_LOCAL    	DECIMAL(28,8) 	NOT NULL,
        TIPO_CAMBIO_DOLAR    	DECIMAL(28,8) 	NOT NULL,
        ACTIVA               	VARCHAR(1) 	NOT NULL,
        ULTIMO_DEPOSITO      	decimal(28,0) 	NOT NULL,
        ULTIMA_TEFCR         	decimal(28,0) 	NOT NULL,
        LIMITE_SOBREGIRO     	DECIMAL(28,8) 	NOT NULL,
        CTR_CONTABLE         	VARCHAR(25) 	NULL,
        CTA_CONTABLE         	VARCHAR(25) 	NULL,
        CTR_CIERRE_DEB       	VARCHAR(25) 	NULL,
        CTA_CIERRE_DEB       	VARCHAR(25) 	NULL,
        CTR_CIERRE_CRED      	VARCHAR(25) 	NULL,
        CTA_CIERRE_CRED      	VARCHAR(25) 	NULL,
        ULTIMA_NOTACR        	decimal(28,0) 	NOT NULL,
        ULTIMO_CHEQUE        	DECIMAL(28,8) 	NULL,
        ULTIMO_OTROCR        	decimal(28,0) 	NOT NULL,
        ULTIMA_TEFDB         	DECIMAL(28,8) 	NULL,
        ULTIMA_NOTADB        	decimal(28,0) 	NOT NULL,
        ULTIMO_OTRODB        	decimal(28,0) 	NOT NULL,
        ULTIMA_CONCIL        	int 		NULL,
        MODO_CONCILIAR       	VARCHAR(1) 	NOT NULL,
        IDIOMA_MON_LETRAS    	VARCHAR(1) 	NOT NULL,
        TIPO_CRED_AJUSTE     	VARCHAR(3) 	NULL,
        SUBTIPO_CRED_AJUST   	smallint 	NULL,
        TIPO_DEB_AJUSTE      	VARCHAR(3) 	NULL,
        SUBTIPO_DEB_AJUST    	smallint 	NULL,
        PERMITE_SOBREGIRO    	VARCHAR(1) 	NOT NULL,
        CTA_AJUSTE_CRED      	VARCHAR(25) 	NULL,
        FCH_HORA_CREACION    	DATETIME 	NOT NULL,
        USUARIO_CREACION     	VARCHAR(25) 	NOT NULL,
        CTR_AJUSTE_DEB       	VARCHAR(25) 	NULL,
        CTR_GASTO_TRANSF     	VARCHAR(25) 	NULL,
        CTA_AJUSTE_DEB       	VARCHAR(25) 	NULL,
        CTA_GASTO_TRANSF     	VARCHAR(25) 	NULL,
        CTR_LIQUIDAR_CRED    	VARCHAR(25) 	NULL,
        CTA_LIQUIDAR_CRED    	VARCHAR(25) 	NULL,
        CTR_LIQUIDAR_DEB     	VARCHAR(25) 	NULL,
        CTA_LIQUIDAR_DEB     	VARCHAR(25) 	NULL,
        CTR_AJUSTE_CRED      	VARCHAR(25) 	NULL,
        FCH_HORA_MODIFIC     	DATETIME 	NULL,
        USUARIO_MODIFIC      	VARCHAR(25)	NULL,
        PERMITE_TRANSF_IC    	VARCHAR(1) 	NOT NULL,
        CTA_TRANSF_IC        	VARCHAR(25)	NULL,
        CTR_TRANSF_IC        	VARCHAR(25)	NULL,
        RUBRO1_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO2_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO3_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO4_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO5_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO6_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO7_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO8_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO9_CTABANCO	     	VARCHAR(40)	NULL,
        RUBRO10_CTABANCO     	VARCHAR(40)	NULL,
        CONSE_CHEQUE 	     	VARCHAR(10)	NULL,
		CONSE_TEF 	     		VARCHAR(10)	NULL,
		TIPO_CUENTA	     		VARCHAR(12) 	NULL,
		CTR_DOC_GP 				VARCHAR(25) 	NULL,
		CTA_DOC_GP 				VARCHAR(25) 	NULL,
		SALDO_TRANS 			DECIMAL(28,8) 	DEFAULT 0 	NOT NULL,
		SALDO_TRANS_LOCAL 		DECIMAL(28,8) 	DEFAULT 0 	NOT NULL,
		SALDO_TRANS_DOLAR 		DECIMAL(28,8) 	DEFAULT 0 	NOT NULL,
		PERMITE_DOC_GP			VARCHAR(1) 		DEFAULT 'N' 	NOT NULL,
		PARTICIPA_FLUJOCAJA		VARCHAR(1)  	DEFAULT 'N'	NOT NULL,
		CTA_ELECTRONICA 		VARCHAR(50) 	NULL
)
go
 
 ALTER TABLE CUENTA_BANCARIA
        ADD CONSTRAINT XPKCUENTA_BANCARIA PRIMARY KEY NONCLUSTERED (
               CUENTA_BANCO)
go               