CREATE VIEW $$Compania$$.VREP_CIERREDIA
(
	DOCUMENTO,
	CAJA,
	TIPO,
	TOTAL,
	TOTAL_PAGAR,
	DESCUENTO,
	IMPUESTO1,
	IMPUESTO2,
	ESTADO_COBRO,
	FCH_HORA_COBRO,
	FCH_HORA_CREACION,
	MONTO_BONIFICADO,
	FACTURA_APARTADO
) AS
SELECT	DOCPOS.DOCUMENTO,
	DOCPOS.CAJA,
	DOCPOS.TIPO,
	DOCPOS.TOTAL,
	DOCPOS.TOTAL_PAGAR,
	DOCPOS.DESCUENTO,
 	DOCPOS.IMPUESTO1,
	DOCPOS.IMPUESTO2,
	DOCPOS.ESTADO_COBRO,
	DOCPOS.FCH_HORA_COBRO,
	DOCPOS.FCH_HORA_CREACION,
	DOCPOS.MONTO_BONIFICADO,
	(
		SELECT 	CASE 	COUNT(*) 
				WHEN	1
					THEN	'S'
				WHEN	0
					THEN	'N'
			END
		FROM 	$$Compania$$.AUXILIAR_POS
		WHERE 	DOCUMENTO = DOCPOS.DOCUMENTO AND
			CAJA = DOCPOS.CAJA AND
			TIPO = DOCPOS.TIPO AND
			TIPO_APLICA = 'P'
	) AS FACTURA_APARTADO
FROM 	$$Compania$$.DOCUMENTO_POS DOCPOS
;


CREATE VIEW $$Compania$$.VSUBREP_CIERREDIA
(
	DOCUMENTO,
	CAJA,
	TIPO,
	DOCUM_APLICA,
	TOTAL_PAGAR,
	ESTADO_COBRO,
	FCH_HORA_COBRO,
	FCH_HORA_CREACION
) AS
SELECT	AUX.DOCUMENTO,
	AUX.CAJA,
	AUX.TIPO,
	AUX.DOCUM_APLICA,
	DOCPOS.TOTAL_PAGAR,
	DOCPOS.ESTADO_COBRO,
	DOCPOS.FCH_HORA_COBRO,
	DOCPOS.FCH_HORA_CREACION
FROM	$$Compania$$.DOCUMENTO_POS DOCPOS,
	$$Compania$$.AUXILIAR_POS AUX
WHERE	DOCPOS.DOCUMENTO = AUX.DOCUMENTO AND
	DOCPOS.CAJA = AUX.CAJA AND
	DOCPOS.TIPO = AUX.TIPO AND
	AUX.TIPO_APLICA = 'P'
;






CREATE VIEW $$Compania$$.V_SUCURSAL_BODEGA
AS 
SELECT	DISTINCT GRP.GRUPO,
	C.BODEGA
FROM	$$Compania$$.GRUPO GRP,
	$$Compania$$.GRUPO_CAJA GRPCJ,
	$$Compania$$.CAJA_POS C
WHERE	GRP.GRUPO = GRPCJ.GRUPO AND
	GRPCJ.CAJA = C.CAJA
;




CREATE VIEW $$Compania$$.V_UNIDADES_VENDIDAS_RPT
AS
SELECT 	DOCP.*,
	(	CASE 
			WHEN	DOCS.TIPO = 'P'
				THEN	DOCS.DOCUMENTO
			ELSE	NULL
		END
	) AS APARTADO, 
	(
		CASE
			WHEN	DOCS.TIPO = 'P'
				THEN	DOCS.FCH_HORA_CREACION
			ELSE	NULL
		END
	) AS FECHA_APARTADO,
	(
		CASE
			WHEN	DOCS.TIPO = 'P'
				THEN	DOCS.TIPO
			ELSE	NULL
		END
	)  TIPO_APARTADO
FROM	$$COMPANIA$$.DOCUMENTO_POS DOCP 
	LEFT JOIN $$COMPANIA$$.AUXiliar_pos AUX 
	ON	DOCP.DOCUMENTO = AUX.DOCUMENTO AND
		DOCP.CAJA = AUX.CAJA AND
		DOCP.TIPO = AUX.TIPO AND
		AUX.TIPO_APLICA = 'P'
	LEFT JOIN $$COMPANIA$$.DOCUMENTO_POS DOCS
	ON	DOCS.DOCUMENTO = AUX.DOCUM_APLICA AND
		DOCS.CAJA = AUX.CAJA_DOCUM_APLICA AND
		DOCS.TIPO = AUX.TIPO_APLICA
WHERE	DOCP.TIPO IN ('F', 'D', 'P','O') OR (DOCP.TIPO = 'T' AND DOCP.ESTADO_COBRO = 'C');





CREATE VIEW $$Compania$$.V_DOCUMENTO_POS
AS
SELECT	D.*,
	CASE TIPO
		WHEN	'F'
			THEN	ISNULL((
					SELECT	'S'
					FROM	$$Compania$$.AUXILIAR_POS A
					WHERE	D.DOCUMENTO = A.DOCUMENTO AND
						D.TIPO = A.TIPO AND
						D.CAJA = A.CAJA AND
						A.TIPO_APLICA = 'P'
				) ,'N')
		ELSE	'N'
	END APARTADO_ASOCIADO,
	(
		SELECT	CASE
				WHEN	COUNT(*) > 0
					THEN 	'R'
				WHEN	COUNT(*) = 0
					THEN 	'C'
			END
		FROM	$$Compania$$.PAGO_POS P
		WHERE	P.FORMA_PAGO = '0004' AND
			P.DOCUMENTO = D.DOCUMENTO AND
			P.CAJA = D.CAJA AND
			P.TIPO = D.TIPO
	) AS CONDICION_PAGO	
FROM	$$Compania$$.DOCUMENTO_POS D
;




CREATE VIEW $$Compania$$.V_GRUPO_BODEGA
(GRUPO, BODEGA)
AS
SELECT SUCURSAL, BODEGA
FROM $$Compania$$.CAJA_POS
;




CREATE VIEW $$COMPANIA$$.V_DET_MOV_ARTICULOS_POS
AS
SELECT	DOCUMENTO_POS.DOCUMENTO,
	(
		CASE
			WHEN	DOCUMENTO_POS.ESTADO_COBRO = 'P'
				THEN	DOCUMENTO_POS.FCH_HORA_CREACION
			WHEN	DOCUMENTO_POS.ESTADO_COBRO = 'C' AND
				DOCUMENTO_POS.TIPO = 'F'
				THEN	DOCUMENTO_POS.FCH_HORA_COBRO
			WHEN	DOCUMENTO_POS.ESTADO_COBRO = 'C' AND
				DOCUMENTO_POS.TIPO = 'T'
				THEN	DOCUMENTO_POS.FCH_HORA_COBRO
			WHEN	DOCUMENTO_POS.ESTADO_COBRO = 'C' AND
				DOCUMENTO_POS.TIPO = 'O'
				THEN	DOCUMENTO_POS.FCH_HORA_COBRO
			WHEN 	DOCUMENTO_POS.ESTADO_COBRO = 'C' AND
				DOCUMENTO_POS.TIPO IN ('P','D')
				THEN	DOCUMENTO_POS.FCH_HORA_CREACION
			ELSE	DOCUMENTO_POS.FCH_HORA_ANULA
		END
	) AS FECHA,
	DOC_POS_LINEA.ARTICULO,
	DOC_POS_LINEA.CANTIDAD,
	GRUPO_CAJA.GRUPO,
	DOCUMENTO_POS.ESTADO_COBRO AS ESTADO,
	DOCUMENTO_POS.TIPO,
	'' AS BODEGA_ORIGEN,
	'' AS BODEGA_DESTINO,
	(
		SELECT	CASE
				WHEN	COUNT(*) >= 1
					THEN 'S'
				WHEN	COUNT(*) = 0
					THEN 'N'
			END
		FROM 	$$COMPANIA$$.AUXILIAR_POS AX
		WHERE	DOCUMENTO_POS.DOCUMENTO = AX.DOCUMENTO AND
			DOCUMENTO_POS.CAJA = AX.CAJA AND
			DOCUMENTO_POS.TIPO = AX.TIPO AND
			AX.TIPO_APLICA = 'P'
	) AS APARTADO_ASOCIADO, '' AS TIPO_MOVIMIENTO
FROM	$$COMPANIA$$.DOCUMENTO_POS DOCUMENTO_POS,
	$$COMPANIA$$.DOC_POS_LINEA DOC_POS_LINEA,
	$$COMPANIA$$.GRUPO_CAJA GRUPO_CAJA
WHERE	DOCUMENTO_POS.DOCUMENTO = DOC_POS_LINEA.DOCUMENTO AND
	DOCUMENTO_POS.CAJA = DOC_POS_LINEA.CAJA AND
	DOCUMENTO_POS.TIPO = DOC_POS_LINEA.TIPO AND
	(
		(
			DOCUMENTO_POS.ESTADO_COBRO IN ('P','C','A') AND
			DOCUMENTO_POS.TIPO IN ('P', 'D')
		) OR
		(
			DOCUMENTO_POS.ESTADO_COBRO IN ('C','A') AND
			DOCUMENTO_POS.TIPO IN ('F','T','O')
		)
	) AND
	DOCUMENTO_POS.CAJA = GRUPO_CAJA.CAJA
UNION
SELECT  (SELECT CASE 
		WHEN AINV.APLICACION IS NULL OR AINV.APLICACION = '' THEN 'CI_MOV_INV'
		ELSE AINV.APLICACION END
		), TINV.FECHA, TINV.ARTICULO, ABS(TINV.CANTIDAD), VSB.GRUPO, 'A',
	TINV.NATURALEZA, TINV.BODEGA AS BODEGA_ORIGEN,
	'' AS BODEGA_DESTINO, 'N', TINV.TIPO AS TIPO_MOVIMIENTO
FROM    $$COMPANIA$$.V_GRUPO_BODEGA VSB, $$COMPANIA$$.TRANSACCION_INV TINV, 
	$$COMPANIA$$.AUDIT_TRANS_INV AINV
WHERE   TINV.BODEGA = VSB.BODEGA
	AND TINV.AUDIT_TRANS_INV = AINV.AUDIT_TRANS_INV
	AND ((TINV.SUBTIPO = 'D' AND TINV.TIPO ='V')
	OR (TINV.TIPO = 'R'))
	AND 0 = (SELECT COUNT(*)
		FROM $$COMPANIA$$.TRANSACCION_INV TI,
		$$COMPANIA$$.AUDIT_TRANS_INV ATI, 
		$$COMPANIA$$.FACTURA F, 
		$$COMPANIA$$.CAJA_POS CP, 
		$$COMPANIA$$.DOCUMENTO_POS DP
		WHERE 
		TI.AUDIT_TRANS_INV = ATI.AUDIT_TRANS_INV AND 
		ATI.AUDIT_TRANS_INV = F.AUDIT_TRANS_INV AND
		SUBSTRING(F.FACTURA,1,2) = CP.CODIGO_CORTO AND
		CP.CAJA = DP.CAJA AND
		DP.DOCUMENTO = SUBSTRING(F.FACTURA,3,LEN(F.FACTURA)) AND
		DP.TIPO = F.TIPO_DOCUMENTO AND
		TI.TIPO in ('V','R') AND 
		ATI.AUDIT_TRANS_INV = AINV.AUDIT_TRANS_INV)
	AND NOT (AINV.APLICACION LIKE 'ANU-FAC#%' OR AINV.APLICACION LIKE 'ANU-DEV#%')
	AND AINV.APLICACION NOT IN (SELECT CAJA+TIPO+DOCUMENTO FROM $$COMPANIA$$.DOCUMENTO_POS WHERE TIPO = 'P')
UNION
SELECT  (SELECT CASE 
		WHEN AINV.APLICACION IS NULL OR AINV.APLICACION = '' THEN 'CI_MOV_INV'
		ELSE AINV.APLICACION END
		), TINV.FECHA, TINV.ARTICULO, ABS(TINV.CANTIDAD), VSB.GRUPO, 'A',
	TINV.NATURALEZA, (SELECT BODEGA 
		FROM $$COMPANIA$$.TRANSACCION_INV 
		WHERE AUDIT_TRANS_INV = AINV.AUDIT_TRANS_INV AND 
		ARTICULO = TINV.ARTICULO AND 
		NATURALEZA = 'S' AND
		TIPO = 'T' AND 
		CONSECUTIVO = TINV.CONSECUTIVO -1)  AS BODEGA_ORIGEN,
	TINV.BODEGA AS BODEGA_DESTINO, 'N', TINV.TIPO AS TIPO_MOVIMIENTO
FROM    $$COMPANIA$$.V_GRUPO_BODEGA VSB, $$COMPANIA$$.TRANSACCION_INV TINV, 
	$$COMPANIA$$.AUDIT_TRANS_INV AINV
WHERE   TINV.BODEGA = VSB.BODEGA
	AND TINV.AUDIT_TRANS_INV = AINV.AUDIT_TRANS_INV
	AND TINV.SUBTIPO = 'D'
	AND TINV.TIPO = 'T'
	AND TINV.NATURALEZA = 'E'
UNION
SELECT  (SELECT CASE 
		WHEN AINV.APLICACION IS NULL OR AINV.APLICACION = '' THEN 'CI_MOV_INV'
		ELSE AINV.APLICACION END
	 ), TINV.FECHA, TINV.ARTICULO, ABS(TINV.CANTIDAD), VSB.GRUPO, 'A',
	TINV.NATURALEZA, TINV.BODEGA AS BODEGA_ORIGEN,
	(SELECT BODEGA 
		FROM $$COMPANIA$$.TRANSACCION_INV 
		WHERE AUDIT_TRANS_INV = AINV.AUDIT_TRANS_INV AND 
		ARTICULO = TINV.ARTICULO AND 
		NATURALEZA = 'E' AND
		TIPO = 'T' AND 
		CONSECUTIVO = TINV.CONSECUTIVO +1) AS BODEGA_DESTINO, 'N', TINV.TIPO AS TIPO_MOVIMIENTO
FROM    $$COMPANIA$$.V_GRUPO_BODEGA VSB, $$COMPANIA$$.TRANSACCION_INV TINV, 
	$$COMPANIA$$.AUDIT_TRANS_INV AINV
WHERE   TINV.BODEGA = VSB.BODEGA
	AND TINV.AUDIT_TRANS_INV = AINV.AUDIT_TRANS_INV
	AND TINV.SUBTIPO = 'D'
	AND TINV.TIPO = 'T'
	AND TINV.NATURALEZA = 'S'
UNION
SELECT (SELECT CASE 
		WHEN AINV.APLICACION IS NULL OR AINV.APLICACION = '' THEN 'CI_MOV_INV'
		ELSE AINV.APLICACION END
		), TINV.FECHA, TINV.ARTICULO, ABS(TINV.CANTIDAD), VSB.GRUPO, 'A',
	TINV.NATURALEZA, TINV.BODEGA AS BODEGA_ORIGEN,
	'' AS BODEGA_DESTINO, 'N', TINV.TIPO AS TIPO_MOVIMIENTO
FROM    $$COMPANIA$$.V_GRUPO_BODEGA VSB, $$COMPANIA$$.TRANSACCION_INV TINV, 
	$$COMPANIA$$.AUDIT_TRANS_INV AINV
WHERE   TINV.BODEGA = VSB.BODEGA
	AND TINV.AUDIT_TRANS_INV = AINV.AUDIT_TRANS_INV
	AND TINV.SUBTIPO = 'D'
	AND TINV.TIPO NOT IN ('T', 'V','R')
;



CREATE VIEW $$Compania$$.V_MOV_ARTICULOS_X_BODEGA
AS
SELECT	(
		CASE
			WHEN	DP.ESTADO_COBRO = 'P' OR
				DP.ESTADO_COBRO = 'C'
				THEN	DP.FCH_HORA_CREACION
			ELSE	DP.FCH_HORA_ANULA
		END
	) AS FECHA,
	DPL.ARTICULO,
	DPL.CANTIDAD,
	CP.BODEGA,
	DP.TIPO,
	(
		CASE
			WHEN	DP.ESTADO_COBRO = 'P' OR
				DP.ESTADO_COBRO = 'C'
				THEN	'N'
			ELSE	'S'
		END
	) AS ANULADO,
	DP.FCH_HORA_CREACION AS FECHA_CREACION,
	ISNULL((
		SELECT	CASE
				WHEN	COUNT(*) > 0
					THEN	'S'
				ELSE	'N'
			END
		FROM	$$Compania$$.AUXILIAR_POS AP
		WHERE	AP.DOCUMENTO = DP.DOCUMENTO AND
			AP.CAJA = DP.CAJA AND
			AP.TIPO = DP.TIPO AND
			AP.TIPO_APLICA = 'P'
	),'N') AS FACTURA_APARTADO
FROM	$$Compania$$.DOCUMENTO_POS DP,
	$$Compania$$.DOC_POS_LINEA DPL,
	$$Compania$$.CAJA_POS CP
WHERE	DP.DOCUMENTO = DPL.DOCUMENTO AND
	DP.CAJA = DPL.CAJA AND
	DP.TIPO = DPL.TIPO AND
	(
		(
			DP.TIPO = 'F' AND
			DP.ESTADO_COBRO IN ('C', 'A')
		) OR
		(
			DP.TIPO = 'D' AND
			DP.ESTADO_COBRO IN ('P', 'C', 'A')
		)
	) AND
	DP.CAJA = CP.CAJA
UNION
SELECT	(
		CASE
			WHEN	TP.ESTADO = 'A'
				THEN	TP.FECHA
			ELSE	TP.RecordDate
		END
	) AS FECHA,
	TPD.ARTICULO,
	TPD.CANTIDAD,
	TP.BODEGA_DESTINO AS BODEGA,
	'E' AS TIPO,
	(
		CASE
			WHEN	TP.ESTADO = 'A'
				THEN	'N'
			ELSE	'S'
		END
	) AS ANULADO,
	TP.FECHA AS FECHA_CREACION,
	'N'
FROM	$$Compania$$.TRASPASO_POS TP,
	$$Compania$$.TRASPASO_POS_DET TPD
WHERE	TP.CONSECUTIVO_CI = TPD.CONSECUTIVO_CI AND
	TP.DOCUMENTO = TPD.DOCUMENTO AND
	TP.ESTADO IN ('A', 'U')
UNION
SELECT	(
		CASE
			WHEN	TP.ESTADO = 'A'
				THEN	TP.FECHA
			ELSE	TP.RecordDate
		END
	) AS FECHA,
	TPD.ARTICULO,
	TPD.CANTIDAD,
	TP.BODEGA_ORIGEN AS BODEGA,
	'S' AS TIPO,
	(
		CASE
			WHEN	TP.ESTADO = 'A'
				THEN	'N'
			ELSE	'S'
		END
	) AS ANULADO,
	TP.FECHA AS FECHA_CREACION,
	'N'
FROM	$$Compania$$.TRASPASO_POS TP,
	$$Compania$$.TRASPASO_POS_DET TPD
WHERE	TP.CONSECUTIVO_CI = TPD.CONSECUTIVO_CI AND
	TP.DOCUMENTO = TPD.DOCUMENTO AND
	TP.ESTADO IN ('A', 'U')
;




CREATE VIEW $$Compania$$.V_APARTADOS_X_BODEGA
AS 
SELECT	DP.FCH_HORA_CREACION AS FECHA,
	DPL.ARTICULO,
	DPL.CANTIDAD,
	CP.BODEGA,
	DP.ESTADO_COBRO,
	DP.FCH_HORA_CREACION AS FECHA_CREACION
FROM	$$Compania$$.DOCUMENTO_POS DP, 
	$$Compania$$.DOC_POS_LINEA DPL,
	$$Compania$$.CAJA_POS CP
WHERE	DP.DOCUMENTO = DPL.DOCUMENTO AND
	DP.CAJA = DPL.CAJA AND
	DP.TIPO = DPL.TIPO AND
	DP.TIPO = 'P' AND
	DP.ESTADO_COBRO = 'P' AND
	DP.CAJA = CP.CAJA
UNION
SELECT	(
		SELECT	DP1.FCH_HORA_COBRO
		FROM	$$Compania$$.DOCUMENTO_POS DP1
		WHERE	DP1.DOCUMENTO + DP1.CAJA+DP1.TIPO = (
			SELECT AP.DOCUMENTO + AP.CAJA+AP.TIPO
			FROM	$$Compania$$.AUXILIAR_POS AP
			WHERE	AP.DOCUM_APLICA = DP.DOCUMENTO AND
				AP.CAJA_DOCUM_APLICA = DP.CAJA AND
				AP.TIPO_APLICA = DP.TIPO
			)
	) AS FECHA,
	DPL.ARTICULO,
	DPL.CANTIDAD,
	CP.BODEGA,
	DP.ESTADO_COBRO,
	DP.FCH_HORA_CREACION AS FECHA_CREACION
FROM	$$Compania$$.DOCUMENTO_POS DP,
	$$Compania$$.DOC_POS_LINEA DPL,
	$$Compania$$.CAJA_POS CP
WHERE	DP.DOCUMENTO = DPL.DOCUMENTO AND
	DP.CAJA = DPL.CAJA AND
	DP.TIPO = DPL.TIPO AND
	DP.TIPO = 'P' AND
	DP.ESTADO_COBRO = 'C' AND
	DP.CAJA = CP.CAJA
UNION
SELECT	DP.FCH_HORA_ANULA AS FECHA,
	DPL.ARTICULO,
	DPL.CANTIDAD,
	CP.BODEGA,
	DP.ESTADO_COBRO,
	DP.FCH_HORA_CREACION AS FECHA_CREACION
FROM	$$Compania$$.DOCUMENTO_POS DP,
	$$Compania$$.DOC_POS_LINEA DPL,
	$$Compania$$.CAJA_POS CP
WHERE	DP.DOCUMENTO = DPL.DOCUMENTO AND
	DP.CAJA = DPL.CAJA AND
	DP.TIPO = DPL.TIPO AND
	DP.TIPO = 'P' AND
	DP.ESTADO_COBRO = 'A' AND
	DP.CAJA = CP.CAJA
;




CREATE VIEW $$Compania$$.V_DET_MOV_ARTICULOS
AS
SELECT	SUBSTRING(AUDIT_TRANS.REFERENCIA, 14, 
	CHARINDEX(',', AUDIT_TRANS.REFERENCIA, 14) - 14) AS DOCUMENTO,
	'FACTURA' AS CONSECUTIVO,
	TRINV.FECHA AS FECHA,
	TRINV.BODEGA,
	ARTICULO,
	ABS(CANTIDAD) AS CANTIDAD,
	GRUPO.GRUPO,
	'F' AS TIPO,
	TRINV.NATURALEZA AS TIPO_MOV,
	TRINV.TIPO AS TIPO_CI,
	TRINV.SUBTIPO AS SUBTIPO_CI,
	'' AS BODEGA_ORIGEN,
	'' AS BODEGA_DESTINO
FROM	$$Compania$$.TRANSACCION_INV TRINV,
	(
		SELECT	ATV.AUDIT_TRANS_INV,
			ATV.REFERENCIA 
		FROM	$$Compania$$.AUDIT_TRANS_INV ATV
		WHERE	ATV.AUDIT_TRANS_INV <> 0 AND
			ATV.REFERENCIA LIKE '%POS -Factura:%' AND
			ATV.REFERENCIA NOT LIKE '%por Apartado%' AND
			ATV.REFERENCIA NOT LIKE '%Anulación%'
	) AUDIT_TRANS,
	$$Compania$$.V_SUCURSAL_BODEGA VSB,
	$$Compania$$.GRUPO GRUPO		 
WHERE	TRINV.AUDIT_TRANS_INV = AUDIT_TRANS.AUDIT_TRANS_INV AND
	TRINV.BODEGA = VSB.BODEGA AND
	VSB.GRUPO = GRUPO.GRUPO
UNION
SELECT	SUBSTRING(AUDIT_TRANS.REFERENCIA, 17, 
	CHARINDEX(',', AUDIT_TRANS.REFERENCIA, 17) - 17) AS DOCUMENTO,
	'DEVOLUCION' AS CONSECUTIVO,
	TRINV.FECHA AS FECHA,
	TRINV.BODEGA,
	ARTICULO,
	ABS(CANTIDAD) AS CANTIDAD,
	GRUPO.GRUPO,
	'D' AS TIPO,
	TRINV.NATURALEZA AS TIPO_MOV,
	TRINV.TIPO AS TIPO_CI,
	TRINV.SUBTIPO AS SUBTIPO_CI,
	'' AS BODEGA_ORIGEN,
	'' AS BODEGA_DESTINO
FROM	$$Compania$$.TRANSACCION_INV TRINV,
	(
		SELECT	ATV.AUDIT_TRANS_INV,
			ATV.REFERENCIA
		FROM	$$Compania$$.AUDIT_TRANS_INV ATV
		WHERE	ATV.AUDIT_TRANS_INV <> 0 AND
			ATV.REFERENCIA LIKE '%POS -Devolución:%' AND
			ATV.REFERENCIA NOT LIKE '%Anulación%'
	) AUDIT_TRANS,
	$$Compania$$.V_SUCURSAL_BODEGA VSB,
	$$Compania$$.GRUPO GRUPO		 
WHERE	TRINV.AUDIT_TRANS_INV = AUDIT_TRANS.AUDIT_TRANS_INV AND
	TRINV.BODEGA = VSB.BODEGA AND
	VSB.GRUPO = GRUPO.GRUPO
UNION
SELECT	SUBSTRING(AUDIT_TRANS.REFERENCIA, 
	15, 
	CHARINDEX(',', AUDIT_TRANS.REFERENCIA, 15) - 15) AS DOCUMENTO,
	'APARTADO' AS CONSECUTIVO,
	TRINV.FECHA AS FECHA,
	TRINV.BODEGA,
	ARTICULO,
	ABS(CANTIDAD) AS CANTIDAD,
	GRUPO.GRUPO,
	'P' AS TIPO,
	TRINV.NATURALEZA AS TIPO_MOV,
	TRINV.TIPO AS TIPO_CI,
	TRINV.SUBTIPO AS SUBTIPO_CI,
	'' AS BODEGA_ORIGEN,
	'' AS BODEGA_DESTINO
FROM	$$Compania$$.TRANSACCION_INV TRINV,
	(
		SELECT	ATV.AUDIT_TRANS_INV,
			ATV.REFERENCIA
		FROM	$$Compania$$.AUDIT_TRANS_INV ATV
		WHERE	ATV.AUDIT_TRANS_INV <> 0 AND
			ATV.REFERENCIA LIKE '%POS -Apartado:%' AND
			ATV.REFERENCIA NOT LIKE '%Anulación%'
	) AUDIT_TRANS,
	$$Compania$$.V_SUCURSAL_BODEGA VSB,
	$$Compania$$.GRUPO GRUPO		 
WHERE	TRINV.AUDIT_TRANS_INV = AUDIT_TRANS.AUDIT_TRANS_INV AND
	TRINV.BODEGA = VSB.BODEGA AND
	VSB.GRUPO = GRUPO.GRUPO
UNION
SELECT	SUBSTRING(AUDIT_TRANS.REFERENCIA, CHARINDEX(':', AUDIT_TRANS.REFERENCIA, 1) + 3 , 8) AS DOCUMENTO,
	'FACTURA' AS CONSECUTIVO,
	TRINV.FECHA AS FECHA,
	TRINV.BODEGA,
	ARTICULO,
	ABS(CANTIDAD) AS CANTIDAD,
	GRUPO.GRUPO,
	'F' AS TIPO,
	TRINV.NATURALEZA AS TIPO_MOV,
	TRINV.TIPO AS TIPO_CI,
	TRINV.SUBTIPO AS SUBTIPO_CI,
	'' AS BODEGA_ORIGEN,
	'' AS BODEGA_DESTINO
FROM	$$Compania$$.TRANSACCION_INV TRINV,
	(
		SELECT	ATV.AUDIT_TRANS_INV,
			ATV.REFERENCIA
		FROM	$$Compania$$.AUDIT_TRANS_INV ATV
		WHERE	ATV.AUDIT_TRANS_INV <> 0 AND
			ATV.REFERENCIA LIKE '%POS -Factura:%' AND
			ATV.REFERENCIA LIKE '%por Apartado%' AND
			ATV.REFERENCIA NOT LIKE '%-Desreserva/venta Cobro%' AND
			ATV.REFERENCIA NOT LIKE '%-Desreserva por cancelación%'	AND
			ATV.REFERENCIA NOT LIKE '%Anulación%'
	) AUDIT_TRANS,
	$$Compania$$.V_SUCURSAL_BODEGA VSB,
	$$Compania$$.GRUPO GRUPO
WHERE	TRINV.AUDIT_TRANS_INV = AUDIT_TRANS.AUDIT_TRANS_INV AND
	TRINV.BODEGA = VSB.BODEGA AND
	VSB.GRUPO = GRUPO.GRUPO
UNION
SELECT	SUBSTRING(AUDIT_TRANS.REFERENCIA, CHARINDEX(':', AUDIT_TRANS.REFERENCIA, 1) + 3 , 8) AS DOCUMENTO,
	'FACTURA' AS CONSECUTIVO,
	TRINV.FECHA AS FECHA,
	TRINV.BODEGA,
	ARTICULO,
	ABS(CANTIDAD) AS CANTIDAD,
	GRUPO.GRUPO,
	'F' AS TIPO,
	TRINV.NATURALEZA AS TIPO_MOV,
	TRINV.TIPO AS TIPO_CI,
	TRINV.SUBTIPO AS SUBTIPO_CI,
	'' AS BODEGA_ORIGEN,
	'' AS BODEGA_DESTINO
FROM	$$Compania$$.TRANSACCION_INV TRINV,
	(
		SELECT	ATV.AUDIT_TRANS_INV,
			ATV.REFERENCIA
		FROM	$$Compania$$.AUDIT_TRANS_INV ATV
		WHERE	ATV.AUDIT_TRANS_INV <> 0 AND
		ATV.REFERENCIA LIKE '%POS -Factura:%' AND
		ATV.REFERENCIA LIKE '%por Apartado%-Desreserva/venta Cobro%' AND
		ATV.REFERENCIA NOT LIKE '%Anulación%'
	) AUDIT_TRANS,
	$$Compania$$.V_SUCURSAL_BODEGA VSB,
	$$Compania$$.GRUPO GRUPO
WHERE	TRINV.AUDIT_TRANS_INV = AUDIT_TRANS.AUDIT_TRANS_INV AND
	TRINV.BODEGA = VSB.BODEGA AND
	VSB.GRUPO = GRUPO.GRUPO
UNION
SELECT	SUBSTRING(AUDIT_TRANS.REFERENCIA, CHARINDEX(':', AUDIT_TRANS.REFERENCIA, 37) + 1 , 8) AS DOCUMENTO,
	'ANULACION' AS CONSECUTIVO,
	TRINV.FECHA AS FECHA,
	TRINV.BODEGA,
	ARTICULO,
	ABS(CANTIDAD) AS CANTIDAD,
	GRUPO.GRUPO,
	'N' AS TIPO,
	TRINV.NATURALEZA AS TIPO_MOV,
	TRINV.TIPO AS TIPO_CI,
	TRINV.SUBTIPO AS SUBTIPO_CI,
	'' AS BODEGA_ORIGEN,
	'' AS BODEGA_DESTINO
FROM	$$Compania$$.TRANSACCION_INV TRINV,
	(
		SELECT	ATV.AUDIT_TRANS_INV,
			ATV.REFERENCIA
		FROM	$$Compania$$.AUDIT_TRANS_INV ATV
		WHERE	ATV.AUDIT_TRANS_INV <> 0 AND
			ATV.REFERENCIA LIKE '%POS -Factura:%' AND
			ATV.REFERENCIA LIKE '%por Apartado%-Desreserva por cancelación%' AND
			ATV.REFERENCIA NOT LIKE '%Anulación%'
	) AUDIT_TRANS,
	$$Compania$$.V_SUCURSAL_BODEGA VSB,
	$$Compania$$.GRUPO GRUPO
WHERE	TRINV.AUDIT_TRANS_INV = AUDIT_TRANS.AUDIT_TRANS_INV AND
	TRINV.BODEGA = VSB.BODEGA AND
	VSB.GRUPO = GRUPO.GRUPO
UNION
SELECT	SUBSTRING(AUDIT_TRANS.REFERENCIA, 
	26, 
	CHARINDEX(',', AUDIT_TRANS.REFERENCIA, 26) - 26) AS DOCUMENTO,
	'ANULACION' AS CONSECUTIVO,
	TRINV.FECHA AS FECHA,
	TRINV.BODEGA,
	ARTICULO,
	ABS(CANTIDAD) AS CANTIDAD,
	GRUPO.GRUPO,
	'N' AS TIPO,
	TRINV.NATURALEZA AS TIPO_MOV,
	TRINV.TIPO AS TIPO_CI,
	TRINV.SUBTIPO AS SUBTIPO_CI,
	'' AS BODEGA_ORIGEN,
	'' AS BODEGA_DESTINO
FROM	$$Compania$$.TRANSACCION_INV TRINV,
	(
		SELECT	ATV.AUDIT_TRANS_INV,
			ATV.REFERENCIA
		FROM	$$Compania$$.AUDIT_TRANS_INV ATV
		WHERE	ATV.AUDIT_TRANS_INV <> 0 AND
			ATV.REFERENCIA LIKE '%Anulación%'
	) AUDIT_TRANS,
	$$Compania$$.V_SUCURSAL_BODEGA VSB,
	$$Compania$$.GRUPO GRUPO		 
WHERE	TRINV.AUDIT_TRANS_INV = AUDIT_TRANS.AUDIT_TRANS_INV AND
	TRINV.BODEGA = VSB.BODEGA AND
	VSB.GRUPO = GRUPO.GRUPO
UNION
SELECT	AUDIT_TRANS.APLICACION AS DOCUMENTO,
	CASE
		WHEN	TIPO = 'R'
			THEN	'RESERVACION'
		WHEN	TIPO = 'V'
			THEN	'VENTA'
		WHEN	TIPO = 'C'
			THEN	'CONSUMO'
		WHEN	TIPO = 'O'
			THEN	'COMPRA'
		WHEN	TIPO = 'P'
			THEN	'PRODUCCION'
		WHEN	TIPO = 'E'
			THEN	'ENSAMBLE'
		WHEN	TIPO = 'F'
			THEN	'FISICO'
		WHEN	TIPO = 'M'
			THEN	'MICELANEO'
		WHEN	TIPO = 'A'
			THEN	'APROBACION'
		WHEN	TIPO = 'N'
			THEN	'VENCIMIENTO'
		WHEN	TIPO = 'S'
			THEN	'COSTO'
		WHEN	TIPO = 'R'
			THEN	'REMISION'
	END AS CONSECUTIVO,
	TRINV.FECHA AS FECHA,
	TRINV.BODEGA,
	ARTICULO,
	ABS(CANTIDAD) AS CANTIDAD,
	GRUPO.GRUPO,
	'O' AS TIPO,
	TRINV.NATURALEZA AS TIPO_MOV,
	TRINV.TIPO AS TIPO_CI,
	TRINV.SUBTIPO AS SUBTIPO_CI,
	'' AS BODEGA_ORIGEN,
	'' AS BODEGA_DESTINO
FROM	$$Compania$$.TRANSACCION_INV TRINV,
	(
		SELECT	ATV.AUDIT_TRANS_INV,
			ATV.APLICACION ,
			ATV.CONSECUTIVO
		FROM	$$Compania$$.AUDIT_TRANS_INV ATV
		WHERE	ATV.AUDIT_TRANS_INV <> 0 AND
			ATV.REFERENCIA NOT LIKE '%POS %'
	) AUDIT_TRANS,
	$$Compania$$.V_SUCURSAL_BODEGA VSB,
	$$Compania$$.GRUPO GRUPO		 
WHERE	TRINV.AUDIT_TRANS_INV = AUDIT_TRANS.AUDIT_TRANS_INV AND
	TRINV.BODEGA = VSB.BODEGA AND
	VSB.GRUPO = GRUPO.GRUPO AND
	TRINV.TIPO IN ('R','V','C','O','P','E','F','M','A','N','S','R')	AND
	TRINV.AJUSTE_CONFIG NOT IN (
		SELECT	AJUSTE_CONFIG
		FROM	$$Compania$$.AJUSTE_CONFIG
		WHERE AJUSTE_BASE = 'T'
	)
UNION
SELECT	DISTINCT H.APLICACION AS DOCUMENTO,
	H.CONSECUTIVO,
	H.FECHA_HORA AS FECHA,
	B.BODEGA,
	A.ARTICULO,
	ABS(A.CANTIDAD) AS CANTIDAD,
	GRUPO.GRUPO,
	'E' AS TIPO,
	B.NATURALEZA AS TIPO_MOV,
	A.TIPO AS TIPO_CI,
	A.SUBTIPO AS SUBTIPO_CI,
	A.BODEGA AS BODEGA_ORIGEN,
	B.BODEGA AS BODEGA_DESTINO
FROM	$$Compania$$.AUDIT_TRANS_INV H,
	$$Compania$$.TRANSACCION_INV A,
	$$Compania$$.TRANSACCION_INV B,
	$$Compania$$.V_SUCURSAL_BODEGA VSB,
	$$Compania$$.GRUPO GRUPO
WHERE	H.AUDIT_TRANS_INV  = A.AUDIT_TRANS_INV AND
	A.AUDIT_TRANS_INV = B.AUDIT_TRANS_INV AND
	A.CONSECUTIVO != B.CONSECUTIVO AND
	A.ARTICULO = B.ARTICULO AND
	A.BODEGA != B.BODEGA AND
	B.BODEGA = VSB.BODEGA AND
	VSB.GRUPO = GRUPO.GRUPO AND
	B.BODEGA IN (
		SELECT	BODEGA
		FROM	$$Compania$$.GRUPO G,
			$$Compania$$.CAJA_POS C
		WHERE	G.SUCURSAL = 'S' AND
			G.GRUPO = C.SUCURSAL
	) AND
	A.BODEGA NOT IN (
		SELECT	BODEGA
		FROM	$$Compania$$.GRUPO G,
			$$Compania$$.CAJA_POS C
		WHERE	G.SUCURSAL = 'S' AND
			G.GRUPO = C.SUCURSAL
	) AND
	B.NATURALEZA = 'E' AND
	A.AJUSTE_CONFIG IN (
		SELECT	AJUSTE_CONFIG
		FROM	$$Compania$$.AJUSTE_CONFIG
		WHERE	AJUSTE_BASE = 'T'
	) AND
	B.AJUSTE_CONFIG IN (
		SELECT	AJUSTE_CONFIG
		FROM	$$Compania$$.AJUSTE_CONFIG
		WHERE	AJUSTE_BASE = 'T'
	)
UNION
SELECT	DISTINCT H.APLICACION AS DOCUMENTO,
	H.CONSECUTIVO,
	H.FECHA_HORA AS FECHA,
	A.BODEGA,
	A.ARTICULO,
	ABS(A.CANTIDAD) AS CANTIDAD,
	GRUPO.GRUPO,
	'S' AS TIPO,
	A.NATURALEZA AS TIPO_MOV,
	A.TIPO AS TIPO_CI,
	A.SUBTIPO AS SUBTIPO_CI,
	A.BODEGA AS BODEGA_ORIGEN,
	B.BODEGA AS BODEGA_DESTINO
FROM	$$Compania$$.AUDIT_TRANS_INV H,
	$$Compania$$.TRANSACCION_INV A,
	$$Compania$$.TRANSACCION_INV B,
	$$Compania$$.V_SUCURSAL_BODEGA VSB,
	$$Compania$$.GRUPO GRUPO
WHERE	H.AUDIT_TRANS_INV  = A.AUDIT_TRANS_INV AND
	A.AUDIT_TRANS_INV = B.AUDIT_TRANS_INV AND
	A.CONSECUTIVO != B.CONSECUTIVO AND
	A.ARTICULO = B.ARTICULO AND
	A.BODEGA != B.BODEGA AND
	A.BODEGA = VSB.BODEGA AND
	VSB.GRUPO = GRUPO.GRUPO AND
	B.BODEGA NOT IN (
		SELECT	BODEGA
		FROM	$$Compania$$.GRUPO G,
			$$Compania$$.CAJA_POS C
		WHERE	G.SUCURSAL = 'S' AND
			G.GRUPO = C.SUCURSAL
	) AND
	A.BODEGA IN (
		SELECT	BODEGA
		FROM	$$Compania$$.GRUPO G,
			$$Compania$$.CAJA_POS C
		WHERE	G.SUCURSAL = 'S' AND
			G.GRUPO = C.SUCURSAL
	) AND
	A.NATURALEZA = 'S' AND
	A.AJUSTE_CONFIG IN (
		SELECT	AJUSTE_CONFIG
		FROM	$$Compania$$.AJUSTE_CONFIG
		WHERE	AJUSTE_BASE = 'T'
	) AND
	B.AJUSTE_CONFIG IN (
		SELECT	AJUSTE_CONFIG
		FROM	$$Compania$$.AJUSTE_CONFIG
		WHERE	AJUSTE_BASE = 'T'
	)
;



CREATE VIEW $$Compania$$.V_CANT_DISPONIBLES_A_FECHA
(
	ARTICULO,
	BODEGA,
	FECHA,
	CANT_DISPONIBLE,
	CANT_RESERVADA
)
AS
SELECT	ARTICULO,
	BODEGA,
	CONVERT(DATETIME,CONVERT(VARCHAR,FECHA_HORA_TRANSAC,112)),
	(
		SELECT ISNULL(SUM(
				CASE
					WHEN	TIPO IN ('V','I','C','O','P','F','M','T','N','A','E') AND
						SUBTIPO = 'D' AND
						NATURALEZA = 'E'
						THEN	ISNULL(-ABS(CANTIDAD),0)
					WHEN	TIPO IN ('V','I','C','O','P','F','M','T','N','A','E') AND
						SUBTIPO = 'D' AND
						NATURALEZA = 'S'
						THEN	ISNULL(ABS(CANTIDAD),0)
					WHEN	TIPO = 'R' AND
						NATURALEZA = 'E'
						THEN	ISNULL(-ABS(CANTIDAD),0)
					WHEN	TIPO = 'R' AND
						NATURALEZA = 'S'
						THEN	ISNULL(ABS(CANTIDAD),0)
				END
			),0)
		FROM	$$Compania$$.TRANSACCION_INV VDMA
		WHERE	VDMA.ARTICULO = V.ARTICULO AND
			VDMA.BODEGA = V.BODEGA AND
			VDMA.FECHA_HORA_TRANSAC >= CONVERT(DATETIME,CONVERT(VARCHAR,V.FECHA_HORA_TRANSAC,112) + ' 23:59:59')
	) + (
		SELECT	CANT_DISPONIBLE
		FROM	$$Compania$$.EXISTENCIA_BODEGA
		WHERE	ARTICULO = V.ARTICULO AND
			BODEGA = V.BODEGA
	) AS CANT_DISP,
	(
		SELECT	ISNULL(SUM(
				CASE
					WHEN	TIPO IN ('V','I','C','O','M','T','N') AND
						SUBTIPO = 'R' AND
						NATURALEZA = 'E'
						THEN	ISNULL(-ABS(CANTIDAD),0)
					WHEN	TIPO IN ('V','I','C','O','M','T','N') AND
						SUBTIPO = 'R' AND
						NATURALEZA = 'S'
						THEN	ISNULL(ABS(CANTIDAD),0)
					WHEN	TIPO = 'R' AND
						NATURALEZA = 'E'
						THEN	ISNULL(ABS(CANTIDAD),0)
					WHEN	TIPO = 'R' AND
						NATURALEZA = 'S'
						THEN	ISNULL(-ABS(CANTIDAD),0)
				END
			),0)
		FROM	$$Compania$$.TRANSACCION_INV VDMA
		WHERE	VDMA.ARTICULO = V.ARTICULO AND
			VDMA.BODEGA = V.BODEGA AND
			VDMA.FECHA_HORA_TRANSAC >= CONVERT(DATETIME,CONVERT(VARCHAR,V.FECHA_HORA_TRANSAC,112) + ' 23:59:59')
	) + (
		SELECT	CANT_RESERVADA
		FROM	$$Compania$$.EXISTENCIA_BODEGA
		WHERE ARTICULO = V.ARTICULO AND
		BODEGA = V.BODEGA
	) AS CANT_RESERV
FROM	$$Compania$$.TRANSACCION_INV V
;



CREATE VIEW $$Compania$$.V_CANT_MOV_ARTICULO
(
	ARTICULO,
	BODEGA,
	FECHA,
	CANT_MOVIMIENTOS
)
AS
SELECT	ARTICULO,
	BODEGA,
	CONVERT(DATETIME,CONVERT(VARCHAR,FECHA,112)),
	COUNT(ARTICULO)
FROM	$$Compania$$.V_DET_MOV_ARTICULOS V
GROUP BY	ARTICULO,
		BODEGA,
		CONVERT(DATETIME,CONVERT(VARCHAR,FECHA,112))
;




CREATE VIEW $$COMPANIA$$.V_SITIO_BODEGA
AS 
SELECT	DISTINCT ST.SITIO,
	CP.BODEGA,
	NULL AS NoteExistsFlag,
	NULL AS RecordDate,
	NULL AS RowPointer,
	NULL AS CreatedBy,
	NULL AS UpdatedBy, 
	NULL AS CreateDate
FROM	$$COMPANIA$$.SITIO_TIENDA ST,
		$$COMPANIA$$.CAJA_POS CP
WHERE	CP.SUCURSAL = ST.TIENDA
UNION
SELECT CPS.suscriptor, 
	GP.BODEGA_CENTRAL,
	NULL AS NoteExistsFlag,
	NULL AS RecordDate,
	NULL AS RowPointer,
	NULL AS CreatedBy,
	NULL AS UpdatedBy, 
	NULL AS CreateDate
FROM $$COMPANIA$$.GLOBALES_POS GP, $$COMPANIA$$.temp_config_par_sitio CPS
where GP.sitio_local = CPS.publicador
; 



CREATE VIEW $$Compania$$.V_CANT_MOV_ARTICULO_X_BODEGA
(
	ARTICULO,
	BODEGA,
	FECHA,
	CANT_MOVIMIENTOS
)
AS
SELECT	ARTICULO,
	BODEGA,
	CONVERT(DATETIME,CONVERT(VARCHAR,FECHA,112)),
	COUNT(ARTICULO)
FROM	$$Compania$$.V_MOV_ARTICULOS_X_BODEGA
GROUP BY	ARTICULO,
		BODEGA,
		CONVERT(DATETIME,CONVERT(VARCHAR,FECHA,112))
;




CREATE VIEW $$Compania$$.PRECIO_ARTICULO
	(ARTICULO,
	 PRECIO,
	 DESCRIPCION,
	 NIVEL_PRECIO,
	 MONEDA,
	 CODIGO_BARRAS_VENT,
	 CANTIDAD, 
	 GRUPO) AS
	 
SELECT DISTINCT
	AP.ARTICULO,
	AP.PRECIO + (AP.PRECIO * (SELECT (I.IMPUESTO1 + I.IMPUESTO2)/100
		FROM $$Compania$$.IMPUESTO I    WHERE I.IMPUESTO = A.IMPUESTO))  AS PRECIO,
	A.DESCRIPCION,
	AP.NIVEL_PRECIO,
	AP.MONEDA,
	A.CODIGO_BARRAS_VENT,
	EB.CANTIDAD,
	GR.GRUPO
FROM $$Compania$$.ARTICULO_PRECIO AP,
( SELECT MN.NIVEL_PRECIO, MN.MONEDA, MAX(MN.VERSION) AS VERSION
  FROM $$Compania$$.VERSION_NIVEL MN
  WHERE MN.ESTADO = 'A'
  GROUP BY MN.NIVEL_PRECIO, MN.MONEDA  ) AS VN,
(
  SELECT MV.ARTICULO, MV.NIVEL_PRECIO, MV.MONEDA, MV.VERSION, MAX(MV.VERSION_ARTICULO) AS VERSION_ARTICULO
    FROM $$Compania$$.ARTICULO_PRECIO MV
  GROUP BY MV.ARTICULO, MV.NIVEL_PRECIO, MV.MONEDA, MV.VERSION  ) AS MV1,
$$Compania$$.ARTICULO A,
(
  select SUM(eb1.CANT_DISPONIBLE) as cantidad, eb1.articulo 
  from $$Compania$$.EXISTENCIA_BODEGA as eb1
  group by eb1.ARTICULO ) AS EB,
$$Compania$$.EXISTENCIA_BODEGA EB2,
$$Compania$$.CAJA_POS CP,
$$Compania$$.GRUPO GR,
$$Compania$$.GRUPO_CAJA GC
	WHERE A.ARTICULO         = AP.ARTICULO
	AND AP.NIVEL_PRECIO = VN.NIVEL_PRECIO
	AND AP.MONEDA = VN.MONEDA
	AND AP.VERSION = VN.VERSION
	AND AP.ARTICULO         = MV1.ARTICULO
	AND AP.NIVEL_PRECIO     = MV1.NIVEL_PRECIO
	AND AP.MONEDA		= MV1.MONEDA
	AND AP.VERSION          = MV1.VERSION
	AND AP.VERSION_ARTICULO = MV1.VERSION_ARTICULO
	AND A.ARTICULO = EB.ARTICULO 
	AND EB.ARTICULO = EB2.ARTICULO 
	AND EB2.BODEGA = CP.BODEGA
	AND CP.CAJA = GC.CAJA
	AND GC.GRUPO = GR.GRUPO
;



CREATE VIEW $$Compania$$.CONJUNTO
AS
	SELECT	*   FROM ERPADMIN.CONJUNTO
;



CREATE VIEW $$Compania$$.MEMBRESIA
AS
	SELECT	*   FROM ERPADMIN.MEMBRESIA
;



CREATE VIEW $$Compania$$.PRIVILEGIO_EX
AS
	SELECT	*    FROM	ERPADMIN.PRIVILEGIO_EX
;

    
CREATE VIEW $$Compania$$.USUARIO
AS
	SELECT	*  FROM	ERPADMIN.USUARIO
;

 
CREATE VIEW $$Compania$$.V_SITIO AS
	SELECT	SITIO, DESCRIPCION, ERPADMIN.SF_GETDATE() as RecordDate, newid() as RowPointer
FROM	$$Compania$$.TEMP_SITIO
;




CREATE VIEW $$COMPANIA$$.V_CLIENTE_MOROSO (cliente, docum_pendientes)
AS /*   DOCUMENTOS DEL ERP YA VENCIDOS */
  SELECT cliente,  
  	COUNT(0)
  FROM   $$COMPANIA$$.documentos_cc
  WHERE  fecha_vence < CONVERT(DATETIME, CONVERT(VARCHAR(30), ERPADMIN.SF_GETDATE(), 112))
         AND saldo > 0
         AND tipo IN ( 'B/V', 'FAC', 'I/C', 'INT',
                       'L/C', 'N/D', 'O/D', 'RED', 'RHP' )
         AND anulado = 'N'
  GROUP  BY cliente
  UNION ALL /* FACTURAS DE POS NO CARGADAS AL ERP Y YA VENCIDAS */
  SELECT cliente,
         COUNT(0)
  FROM   $$COMPANIA$$.documento_pos dp
  WHERE  fecha_vence < CONVERT(DATETIME, CONVERT(VARCHAR(30), ERPADMIN.SF_GETDATE(), 112))
         AND saldo > 0
         AND tipo = 'F'
         AND estado_cobro = 'C'
         AND exportado = 'N'
         AND 1 >= (SELECT COUNT(0)
                   FROM   $$COMPANIA$$.pago_pos
                   WHERE  documento = dp.documento
                          AND caja = dp.caja
                          AND tipo = dp.tipo
                          AND forma_pago = '0004')
  GROUP  BY cliente
  UNION ALL /* FACTURAS NO CARGADAS A CC Y YA VENCIDAS */
  SELECT f.cliente,
         COUNT(0)
  FROM   $$COMPANIA$$.factura f,
         $$COMPANIA$$.globales_fa gf,
         $$COMPANIA$$.condicion_pago cp
  WHERE  f.tipo_documento = 'F'
         AND f.cargado_cxc = 'N'
         AND f.anulada = 'N'
         AND f.condicion_pago <> gf.cond_pago_contad
         AND f.condicion_pago = cp.condicion_pago
         AND Dateadd(d, cp.dias_neto, f.fecha) <  
         CONVERT(DATETIME, CONVERT(VARCHAR(30), ERPADMIN.SF_GETDATE(), 112))
  GROUP  BY cliente;





CREATE FUNCTION $$Compania$$.NextStrCodigo(
	@codigoActual VARCHAR(20),
	@maximaLongitud INT
)
RETURNS VARCHAR(20)
BEGIN
	DECLARE @siguienteConsec VARCHAR(20)	
	DECLARE @ultimoCaracter VARCHAR(20)		
	DECLARE @siguienteCaracter VARCHAR(20)	
	DECLARE @buscarSigteConsec INT			
	DECLARE @esSeparador INT				
	DECLARE @longitudValor INT				
	DECLARE @indice INT						
	DECLARE @esCaracterLimite INT			
	DECLARE @LIST_SEPARATOR VARCHAR(1)		
	DECLARE @LIST_SEPARATOR2 VARCHAR(1)		


	SET @LIST_SEPARATOR = 'Ç'
	SET @LIST_SEPARATOR2 = '~'

        SET @buscarSigteConsec = 1

	IF @codigoActual = '' OR @codigoActual IS NULL
		BEGIN
			SET @siguienteConsec = '1'
			SET @buscarSigteConsec = 0
	END	
	
	IF @buscarSigteConsec = 1
		BEGIN
			SET @siguienteConsec = @codigoActual
			SET @longitudValor = LEN(@codigoActual)
			
			IF @longitudValor > @maximaLongitud
				BEGIN
					SET @siguienteConsec = @codigoActual
					SET @buscarSigteConsec = 0 
				END
		END
		
	IF @buscarSigteConsec = 1
		BEGIN
			SET @indice = @longitudValor - 1
		END
	
	IF @buscarSigteConsec = 1
		BEGIN
			
		WHILE @indice >= 0
			BEGIN
                        SET @ultimoCaracter = SUBSTRING ( @siguienteConsec, @indice + 1, 1 )
			

			IF @ultimoCaracter >= '0' AND @ultimoCaracter <= '9'
				BEGIN

					SET @esSeparador = 0
					

					IF @ultimoCaracter = '9'
						BEGIN

							SET @siguienteCaracter = '0'
							

							SET @esCaracterLimite = 1
						END
					ELSE
						BEGIN

							SET @siguienteCaracter = CAST ( ( CAST ( SUBSTRING( @ultimoCaracter, 1, 1 ) AS INT) + 1) AS VARCHAR(1) )						
						

							SET @esCaracterLimite = 0
						END
						

						SET @siguienteConsec = STUFF(@siguienteConsec, @indice + 1, 1, @siguienteCaracter)
				END
			ELSE IF (@ultimoCaracter >= 'A' AND @ultimoCaracter <= 'Z') OR (@ultimoCaracter >= 'a' AND @ultimoCaracter <= 'z')
				BEGIN

					SET @esSeparador = 0
					

					IF @ultimoCaracter = 'Z'
						BEGIN
							SET @siguienteCaracter = 'A'
							SET @esCaracterLimite = 1
						END
					ELSE IF @ultimoCaracter = 'z'
						BEGIN
							SET @siguienteCaracter = 'a'
							SET @esCaracterLimite = 1
						END
					ELSE
						BEGIN

							SET @siguienteCaracter = CHAR(( ASCII(@ultimoCaracter) + 1 ))
							SET @esCaracterLimite = 0
						END
						

					SET @siguienteConsec = STUFF(@siguienteConsec, @indice + 1, 1, @siguienteCaracter)
				END
			ELSE IF @ultimoCaracter = @LIST_SEPARATOR
				BEGIN
					SET @esSeparador = 1
					

					SET @siguienteCaracter = 'A'
					SET @esCaracterLimite = 0
					

					SET @siguienteConsec = STUFF(@siguienteConsec, @indice + 1, 1, @siguienteCaracter)
				END
			ELSE IF @ultimoCaracter = @LIST_SEPARATOR2
				BEGIN
					SET @esSeparador = 1
					

					SET @siguienteCaracter = 'a'
					SET @esCaracterLimite = 0
					

					SET @siguienteConsec = STUFF(@siguienteConsec, @indice + 1, 1, @siguienteCaracter)
				END
			Else If @indice = @longitudValor - 1
				BEGIN
					SET @esCaracterLimite = 1
				END
				
			IF @indice = 0
				BEGIN
					IF @esCaracterLimite = 1
						BEGIN

						IF LEN(@siguienteConsec) = @maximaLongitud
							BEGIN
								SET @siguienteConsec = @codigoActual
							END
						ELSE
							BEGIN
								IF 	@esSeparador = 0
									BEGIN
										IF @siguienteCaracter = '0'
											BEGIN
											SET @siguienteConsec = '1' + @siguienteConsec
												END
											ELSE IF @siguienteCaracter = 'A'
												BEGIN
													SET @siguienteConsec = 'A' + @siguienteConsec
												END
											ELSE
												BEGIN
													SET @siguienteConsec = 'a' + @siguienteConsec
												END
										END
								END
						END
						BREAK
					END
				Else If @esCaracterLimite = 0
					BEGIN
						BREAK
					END
					

					SET @indice = @indice - 1				
				END
		END
	

	RETURN @siguienteConsec
END
;





CREATE PROCEDURE $$Compania$$.OBTENER_CONSEC_CIERRE 
@CAJA		VARCHAR(15),
@TIPO_DOC	VARCHAR(1),
@AUTO_INCREMENTAR BIT
AS
  BEGIN
      DECLARE @SIGTE VARCHAR(20)
      DECLARE @ACTUAL VARCHAR(20)
      DECLARE @NUEVA_RESOLUCION VARCHAR (20)
      DECLARE @CONSECUTIVO VARCHAR(20)
      DECLARE @RESOLUCION VARCHAR(20)

      IF @AUTO_INCREMENTAR = 1
        BEGIN
            SELECT TOP 1 @CONSECUTIVO = valor,
                         @RESOLUCION = resolucion
            FROM   $$Compania$$.consec_caja_pos
            WHERE  tipo_documento = @TIPO_DOC
                   AND caja = @CAJA

            IF @CONSECUTIVO IS NULL
              BEGIN
                  SET @TIPO_DOC = 'G'

                  SELECT TOP 1 @CONSECUTIVO = valor,
                               @RESOLUCION = resolucion
                  FROM   $$Compania$$.consec_caja_pos
                  WHERE  tipo_documento = @TIPO_DOC
                         AND caja = @CAJA
                         AND credito_fiscal = 'N'
              END

            IF NOT @CONSECUTIVO IS NULL
              BEGIN
	              SET @ACTUAL = @CONSECUTIVO
                  SET @SIGTE = $$Compania$$.Nextstrcodigo(@CONSECUTIVO, 20)
					
                  UPDATE $$Compania$$.consec_caja_pos
                  SET    valor = @SIGTE
                  WHERE  tipo_documento = @TIPO_DOC
                         AND caja = @CAJA

                  IF NOT @RESOLUCION IS NULL
                    BEGIN
                        SELECT @NUEVA_RESOLUCION = valor
                        FROM   $$Compania$$.resolucion_pos
                        WHERE  resolucion = @RESOLUCION

                        SET @NUEVA_RESOLUCION =
                        $$Compania$$.Nextstrcodigo(@NUEVA_RESOLUCION, 20
                        )

                        UPDATE $$Compania$$.resolucion_pos
                        SET    valor = @NUEVA_RESOLUCION
                        WHERE  resolucion = @RESOLUCION
                    END
              END
            ELSE
              BEGIN
                  SET @CONSECUTIVO = 'CONSECUTIVO NO ASIGNADO'
              END
        END

      SELECT rowpointer,
             @ACTUAL            AS consecutivo,
             @AUTO_INCREMENTAR AS auto_incrementa
      FROM   $$Compania$$.globales_pos
  END ;




CREATE TRIGGER $$Compania$$.TID_DOC_POS_LINEA
   ON  $$Compania$$.DOC_POS_LINEA
   FOR INSERT
AS 
BEGIN
      DECLARE @DOCUMENTO VARCHAR(20)
      DECLARE @TIPO_DOC VARCHAR(1)
DECLARE @CAJA_DOC VARCHAR(6)
      DECLARE @LINEA_DOC VARCHAR(4)
      DECLARE @BODEGA_DOC VARCHAR(4)

      DECLARE C_INSERTED CURSOR LOCAL FOR
            SELECT DOCUMENTO, CAJA, TIPO, LINEA, BODEGA
            FROM INSERTED
      
      OPEN C_INSERTED
      FETCH NEXT FROM C_INSERTED INTO 
            @DOCUMENTO, @CAJA_DOC, @TIPO_DOC, @LINEA_DOC, @BODEGA_DOC
            
      WHILE @@FETCH_STATUS = 0
      BEGIN

            IF @BODEGA_DOC IS NULL
            BEGIN
                  UPDATE $$Compania$$.DOC_POS_LINEA
                  SET BODEGA = C.BODEGA
                  FROM $$Compania$$.DOC_POS_LINEA DPL, $$Compania$$.CAJA_POS C
                  WHERE DPL.CAJA = C.CAJA
                  AND DPL.DOCUMENTO = @DOCUMENTO
                  AND DPL.TIPO = @TIPO_DOC
                  AND DPL.CAJA = @CAJA_DOC
                  AND DPL.LINEA = @LINEA_DOC
            END

            FETCH NEXT FROM C_INSERTED INTO 
            @DOCUMENTO, @CAJA_DOC, @TIPO_DOC, @LINEA_DOC, @BODEGA_DOC
      END
      CLOSE C_INSERTED
      DEALLOCATE C_INSERTED
END
;




CREATE TRIGGER $$Compania$$.TID_ARTICULO_SERIE_POS
   ON  $$Compania$$.ARTICULO_SERIE_POS
   FOR INSERT
AS 
BEGIN
      DECLARE @DOCUMENTO VARCHAR(20)
      DECLARE @TIPO_DOC VARCHAR(1)
      DECLARE @CAJA_DOC VARCHAR(6)
      DECLARE @LINEA_DOC VARCHAR(4)
      DECLARE @LINEA_SERIE_DOC VARCHAR(4)
      DECLARE @BODEGA_DOC VARCHAR(4)

      DECLARE C_INSERTED CURSOR LOCAL FOR
            SELECT DOCUMENTO, CAJA, TIPO, LINEA, LINEA_SERIE, BODEGA
            FROM INSERTED
      
      OPEN C_INSERTED
      FETCH NEXT FROM C_INSERTED INTO 
            @DOCUMENTO, @CAJA_DOC, @TIPO_DOC, @LINEA_DOC, @LINEA_SERIE_DOC , @BODEGA_DOC
            
      WHILE @@FETCH_STATUS = 0
      BEGIN

            IF @BODEGA_DOC IS NULL
            BEGIN
                  UPDATE $$Compania$$.ARTICULO_SERIE_POS
                  SET BODEGA = DPL.BODEGA
                  FROM $$Compania$$.ARTICULO_SERIE_POS ASP, $$Compania$$.DOC_POS_LINEA DPL
                  WHERE DPL.DOCUMENTO = ASP.DOCUMENTO
                  AND DPL.TIPO = ASP.TIPO
                  AND DPL.CAJA = ASP.CAJA
                  AND DPL.LINEA = ASP.LINEA
                  AND ASP.DOCUMENTO = @DOCUMENTO
                  AND ASP.TIPO = @TIPO_DOC
                  AND ASP.CAJA = @CAJA_DOC
                  AND ASP.LINEA = @LINEA_DOC
                  AND ASP.LINEA_SERIE = @LINEA_SERIE_DOC
            END

            FETCH NEXT FROM C_INSERTED INTO 
            @DOCUMENTO, @CAJA_DOC, @TIPO_DOC, @LINEA_DOC, @LINEA_SERIE_DOC , @BODEGA_DOC
      END
      CLOSE C_INSERTED
      DEALLOCATE C_INSERTED
END;





CREATE FUNCTION $$COMPANIA$$.RESOLUCION_DATA (@factura varchar(50), @tipo varchar(1))
RETURNS TABLE
AS
RETURN (SELECT 
		   ISNULL(RE.RESOLUCION, 'CAMPO EN BLANCO') AS RESOLUCION,
		   ISNULL(RE.TIPO_ACTIVO, 'CAMPO EN BLANCO') AS TIPO_ACTIVO,
		   ISNULL(RE.FECHA_RESOLUCION, ERPADMIN.SF_GETDATE()) AS FECHA_RESOLUCION,
		   ISNULL(RE.NUMERO_AUTORIZACION, 'CAMPO EN BLANCO') AS NUMERO_AUTORIZACION,
		   ISNULL(RE.INFORMACION_REGIMEN, 'CAMPO EN BLANCO') AS INFORMACION_REGIMEN,
		   ISNULL(DEF.SERIE, 'CAMPO EN BLANCO') AS SERIE,
		   ISNULL(RE.FOLIO_INICIAL, 0) AS FOLIO_INICIAL,
		   ISNULL(RE.FOLIO_FINAL, 0) AS FOLIO_FINAL,
		   ISNULL(DEF.CONSECUTIVO, 0) AS ULTIMO_FOLIO,
		   ISNULL(RE.ESTADO, 'CAMPO EN BLANCO') AS ESTADO,
		   ISNULL(RE.USUARIO_CREACION, 'CAMPO EN BLANCO') AS USUARIO_CREACION,
		   ISNULL(RE.SUCURSAL, 'CAMPO EN BLANCO') AS SUCURSAL,
		   ISNULL(RE.NOMBRE_SUCURSAL, 'CAMPO EN BLANCO') AS NOMBRE_SUCURSAL,
		   ISNULL(RE.DISPOSITIVO_ELECTRONICO, 'CAMPO EN BLANCO') AS DISPOSITIVO_ELECTRONICO,
		   ISNULL(RE.DIRECCION1, 'CAMPO EN BLANCO') AS DIRECCION1,
		   ISNULL(RE.MUNICIPIO, 'CAMPO EN BLANCO') AS MUNICIPIO,
		   ISNULL(RE.DEPARTAMENTO, 'CAMPO EN BLANCO') AS DEPARTAMENTO,
		   ISNULL(RE.CODIGO_PAIS, 'CAMPO EN BLANCO') AS CODIGO_PAIS
		   FROM $$Compania$$.FACTURA F     
		   LEFT JOIN $$Compania$$.DOCUMENTOS_CC DC
		   ON DC.DOCUMENTO = F.FACTURA AND (CASE DC.TIPO WHEN 'FAC' THEN 'F' WHEN 'N/C' THEN 'D' END) = F.TIPO_DOCUMENTO
		   LEFT JOIN $$Compania$$.CONSECUTIVO_FA CF 
		   ON F.CONSECUTIVO = CF.CODIGO_CONSECUTIVO
		   LEFT JOIN $$Compania$$.RESOLUCION_DOC_ELECTRONICO RE 
		   ON CF.RESOLUCION = RE.RESOLUCION
		   LEFT JOIN $$Compania$$.DOCUMENTO_ELECTRONICO_FA DEF
		   ON DEF.NUMERO_DOC = F.FACTURA
		   WHERE F.FACTURA = @factura
		   AND F.TIPO_DOCUMENTO = @tipo
		   AND RE.RESOLUCION IS NOT NULL
UNION ALL
SELECT 
		ISNULL(RE.RESOLUCION, 'CAMPO EN BLANCO') AS RESOLUCION,
		ISNULL(RE.TIPO_ACTIVO, 'CAMPO EN BLANCO') AS TIPO_ACTIVO,
		ISNULL(RE.FECHA_RESOLUCION, ERPADMIN.SF_GETDATE()) AS FECHA_RESOLUCION,
		ISNULL(RE.NUMERO_AUTORIZACION, 'CAMPO EN BLANCO') AS NUMERO_AUTORIZACION,
		ISNULL(RE.INFORMACION_REGIMEN, 'CAMPO EN BLANCO') AS INFORMACION_REGIMEN,
		ISNULL(DEF.SERIE, 'CAMPO EN BLANCO') AS SERIE,
		ISNULL(RE.FOLIO_INICIAL, 0) AS FOLIO_INICIAL,
		ISNULL(RE.FOLIO_FINAL, 0) AS FOLIO_FINAL,
		ISNULL(DEF.CONSECUTIVO, 0) AS ULTIMO_FOLIO,
		ISNULL(RE.ESTADO, 'CAMPO EN BLANCO') AS ESTADO,
		ISNULL(RE.USUARIO_CREACION, 'CAMPO EN BLANCO') AS USUARIO_CREACION,
		ISNULL(RE.SUCURSAL, 'CAMPO EN BLANCO') AS SUCURSAL,
		ISNULL(RE.NOMBRE_SUCURSAL, 'CAMPO EN BLANCO') AS NOMBRE_SUCURSAL,
		ISNULL(RE.DISPOSITIVO_ELECTRONICO, 'CAMPO EN BLANCO') AS DISPOSITIVO_ELECTRONICO,
		ISNULL(RE.DIRECCION1, 'CAMPO EN BLANCO') AS DIRECCION1,
		ISNULL(RE.MUNICIPIO, 'CAMPO EN BLANCO') AS MUNICIPIO,
		ISNULL(RE.DEPARTAMENTO, 'CAMPO EN BLANCO') AS DEPARTAMENTO,
		ISNULL(RE.CODIGO_PAIS, 'CAMPO EN BLANCO') AS CODIGO_PAIS
		FROM $$COMPANIA$$.FACTURA A, $$COMPANIA$$.DOCUMENTO_POS B, 
		$$COMPANIA$$.CONSEC_CAJA_POS C, $$COMPANIA$$.RESOLUCION_DOC_ELECTRONICO RE,
		$$Compania$$.DOCUMENTO_ELECTRONICO_FA DEF 
		WHERE A.FACTURA = B.DOCUMENTO
		AND A.TIPO_DOCUMENTO = B.TIPO 
		AND B.CAJA = C.CAJA
		AND B.CORRELATIVO = C.CODIGO
		AND RE.RESOLUCION = c.RESOLUCION
		AND DEF.NUMERO_DOC = A.FACTURA 
		AND A.TIPO_DOCUMENTO = @tipo					
		AND A.FACTURA = @factura	
UNION ALL
SELECT 
		ISNULL(RE.RESOLUCION, 'CAMPO EN BLANCO') AS RESOLUCION,
		ISNULL(RE.TIPO_ACTIVO, 'CAMPO EN BLANCO') AS TIPO_ACTIVO,
		ISNULL(RE.FECHA_RESOLUCION, ERPADMIN.SF_GETDATE()) AS FECHA_RESOLUCION,
		ISNULL(RE.NUMERO_AUTORIZACION, 'CAMPO EN BLANCO') AS NUMERO_AUTORIZACION,
		ISNULL(RE.INFORMACION_REGIMEN, 'CAMPO EN BLANCO') AS INFORMACION_REGIMEN,
		ISNULL(DEF.SERIE, 'CAMPO EN BLANCO') AS SERIE,
		ISNULL(RE.FOLIO_INICIAL, 0) AS FOLIO_INICIAL,
		ISNULL(RE.FOLIO_FINAL, 0) AS FOLIO_FINAL,
		ISNULL(RE.ULTIMO_FOLIO, 0) AS ULTIMO_FOLIO,
		ISNULL(RE.ESTADO, 'CAMPO EN BLANCO') AS ESTADO,
		ISNULL(RE.USUARIO_CREACION, 'CAMPO EN BLANCO') AS USUARIO_CREACION,
		ISNULL(RE.SUCURSAL, 'CAMPO EN BLANCO') AS SUCURSAL,
		ISNULL(RE.NOMBRE_SUCURSAL, 'CAMPO EN BLANCO') AS NOMBRE_SUCURSAL,
		ISNULL(RE.DISPOSITIVO_ELECTRONICO, 'CAMPO EN BLANCO') AS DISPOSITIVO_ELECTRONICO,
		ISNULL(RE.DIRECCION1, 'CAMPO EN BLANCO') AS DIRECCION1,
		ISNULL(RE.MUNICIPIO, 'CAMPO EN BLANCO') AS MUNICIPIO,
		ISNULL(RE.DEPARTAMENTO, 'CAMPO EN BLANCO') AS DEPARTAMENTO,
		ISNULL(RE.CODIGO_PAIS, 'CAMPO EN BLANCO') AS CODIGO_PAIS
		FROM $$COMPANIA$$.FACTURA A, $$COMPANIA$$.DOCUMENTO_POS B, 
		$$COMPANIA$$.CAJA_POS D, $$COMPANIA$$.CONSEC_CAJA_POS C, 
		$$COMPANIA$$.RESOLUCION_DOC_ELECTRONICO RE,
		$$Compania$$.DOCUMENTO_ELECTRONICO_FA DEF 
		WHERE SUBSTRING (A.FACTURA,3,LEN(A.FACTURA)) = B.DOCUMENTO
		AND A.TIPO_DOCUMENTO = B.TIPO 
		AND SUBSTRING (A.FACTURA,0,3) = D.CODIGO_CORTO 
		AND B.CAJA = C.CAJA
		AND B.CORRELATIVO = C.CODIGO 
		AND RE.RESOLUCION = c.RESOLUCION 
		AND DEF.NUMERO_DOC = A.FACTURA 
		AND A.TIPO_DOCUMENTO = @tipo
		AND A.FACTURA = @factura);
		
		
						

	
CREATE VIEW $$COMPANIA$$.ConcecTransacFactFA_POS
AS	
		SELECT	fac.CONSECUTIVO AS CONCE, fac.FACTURA
		FROM	$$COMPANIA$$.FACTURA fac
		WHERE	fac.factura Not In (	 SELECT fac.FACTURA
							 FROM	 $$COMPANIA$$.FACTURA fac, $$COMPANIA$$.DOCUMENTO_POS dp
							 WHERE	 fac.FACTURA = dp.DOCUMENTO
							 UNION 
							 SELECT fac.FACTURA
							 FROM	 $$COMPANIA$$.FACTURA fac, $$COMPANIA$$.DOCUMENTO_POS dp
							 WHERE	 SUBSTRING(fac.FACTURA,3,20) = dp.DOCUMENTO
						   )
		GROUP BY fac.CONSECUTIVO, fac.FACTURA
		UNION ALL
		SELECT	ppos.CORRELATIVO AS CONCE, fac.FACTURA
		FROM	$$COMPANIA$$.FACTURA fac,
				$$COMPANIA$$.DOCUMENTO_POS ppos 
		WHERE	fac.FACTURA = ppos.DOCUMENTO
		GROUP BY ppos.CORRELATIVO, fac.FACTURA
		UNION
		SELECT	ppos.CORRELATIVO AS CONCE, fac.FACTURA
		FROM	$$COMPANIA$$.FACTURA fac,
				$$COMPANIA$$.DOCUMENTO_POS ppos 
		WHERE	SUBSTRING(fac.FACTURA,3,20) = ppos.DOCUMENTO
		GROUP BY ppos.CORRELATIVO, fac.FACTURA;







CREATE VIEW $$COMPANIA$$.TotalFacturaXTipoPagoPOS_FA
AS
	SELECT fac.FACTURA, fac.TOTAL_FACTURA AS TOTALES, fac.CONSECUTIVO , '0001' AS FORMA_PAGO, 
		   'EFECTIVO' AS DESCRIPCION, FAC.TIPO_DOCUMENTO AS TIPO_DOCUMENTO
	FROM   $$COMPANIA$$.FACTURA fac
	WHERE  fac.factura Not In (	 SELECT fac.FACTURA
			 FROM	 $$COMPANIA$$.FACTURA fac, $$COMPANIA$$.DOCUMENTO_POS dp
			 WHERE	 fac.FACTURA = dp.DOCUMENTO
			 UNION 
			 SELECT fac.FACTURA
			 FROM	 $$COMPANIA$$.FACTURA fac, $$COMPANIA$$.DOCUMENTO_POS dp
			 WHERE	 SUBSTRING(fac.FACTURA,3,20) = dp.DOCUMENTO
		)
	UNION
	SELECT fac.FACTURA AS FACTURA,(pp.MONTO_LOCAL + (pp.MONTO_DOLAR*fac.TIPO_CAMBIO)) AS TOTALES, dp.correlativo AS CORRELATIVO, 
		   pp.FORMA_PAGO AS FORMA_PAGO,fp.DESCRIPCION AS DESCRIPCION, dp.TIPO AS TIPO_DOCUMENTO
	FROM   $$COMPANIA$$.FACTURA fac LEFT JOIN $$COMPANIA$$.DOCUMENTO_POS dp ON fac.factura = dp.documento,
		   $$COMPANIA$$.PAGO_POS pp INNER JOIN $$COMPANIA$$.FORMA_PAGO fp ON pp.FORMA_PAGO = fp.FORMA_PAGO
	WHERE  fac.factura  IN (  Select fac.FACTURA
							  FROM	 $$COMPANIA$$.FACTURA fac, $$COMPANIA$$.DOCUMENTO_POS dp
							  WHERE	 fac.FACTURA = dp.DOCUMENTO
							)	
	 AND   dp.DOCUMENTO = pp.DOCUMENTO
	 AND   dp.TIPO = pp.TIPO
	 AND   pp.FORMA_PAGO = fp.FORMA_PAGO
	 UNION
	 Select fac.FACTURA,(pp.MONTO_LOCAL + (pp.MONTO_DOLAR*fac.TIPO_CAMBIO)) AS TOTALES, dp.correlativo AS CORRELATIVO,
			pp.FORMA_PAGO AS FORMA_PAGO,fp.DESCRIPCION AS DESCRIPCION, dp.TIPO AS TIPO_DOCUMENTO
	 From	 $$COMPANIA$$.FACTURA fac, $$COMPANIA$$.DOCUMENTO_POS dp,
			 $$COMPANIA$$.PAGO_POS pp, $$COMPANIA$$.FORMA_PAGO fp
	 WHERE	 SUBSTRING(fac.FACTURA,3,20) = dp.DOCUMENTO
	 AND   dp.DOCUMENTO = pp.DOCUMENTO
	 AND   dp.TIPO = pp.TIPO
	 AND   pp.FORMA_PAGO = fp.FORMA_PAGO ;






CREATE VIEW $$COMPANIA$$.V_DiarioConta
AS
	SELECT	fac.FACTURA, fac.FECHA, fac.ANULADA, fac.TIPO_DOCUMENTO,
			fac.NOMBREMAQUINA, ctf.CONCE
	FROM   (($$COMPANIA$$.FACTURA fac 
			INNER JOIN $$COMPANIA$$.SUBTIPO_DOC_CC sdc 
			ON (fac.TIPO_DOC_CXC=sdc.TIPO) 
			AND (fac.SUBTIPO_DOC_CXC=sdc.SUBTIPO)) 
			LEFT OUTER JOIN $$COMPANIA$$.DOCUMENTO_POS dp 
			ON (fac.FACTURA=dp.DOCUMENTO) 
			AND (fac.TIPO_DOCUMENTO=dp.TIPO)
			OR (SUBSTRING(fac.FACTURA,3,20) = dp.DOCUMENTO)) 
			FULL OUTER JOIN $$COMPANIA$$.ConcecTransacFactFA_POS ctf 
			ON (fac.CONSECUTIVO = ctf.CONCE) 
			OR (dp.CORRELATIVO = ctf.CONCE)
			WHERE  fac.ANULADA = 'N' 
			AND fac.TIPO_DOCUMENTO='F';




			
CREATE TRIGGER $$Compania$$.ACTUALIZA_SALDOS_POS
ON $$COMPANIA$$.DOCUMENTOS_CC 
 FOR UPDATE 
 AS 
   BEGIN 
       DECLARE @ERROR INT 
       DECLARE @CONCAT_COD_CORTO VARCHAR(1) 
       DECLARE @EXISTE_DOC_POS INT 
       DECLARE @TIPO_DOC_PARA_POS VARCHAR(20) 
       DECLARE @DOCUMENTO VARCHAR(50) 
       DECLARE @TIPO VARCHAR(3) 
       DECLARE @APLICACION VARCHAR(249) 
       DECLARE @FECHA_DOC DATETIME 
       DECLARE @MONTO_DOC DECIMAL (28, 8) 
       DECLARE @SALDO_DOC DECIMAL (28, 8) 
       DECLARE @DOC_POS VARCHAR(50) 
       DECLARE @TIPO_DOC_POS VARCHAR(3) 
       DECLARE @CAJA VARCHAR(3) 
 
       SET @TIPO_DOC_PARA_POS = 'FAC,N/C,REC' 
 
       SELECT @CONCAT_COD_CORTO = valor 
       FROM   $$COMPANIA$$.globales 
       WHERE  modulo = 'PO'
              AND nombre = 'CONCAT_COD_CORTO'
 
       DECLARE c_modified CURSOR local FOR 
         SELECT documento, 
                tipo, 
                aplicacion, 
                fecha_documento, 
                monto, 
                saldo_local 
         FROM   inserted I 
 
       OPEN c_modified 
 
       FETCH next FROM c_modified INTO @DOCUMENTO, @TIPO, @APLICACION, @FECHA_DOC, @MONTO_DOC, @SALDO_DOC 
 
       WHILE @@FETCH_STATUS = 0 
         BEGIN 
              IF ( NOT Update(recorddate) 
                  AND Update (saldo_local) 
                  AND ( Charindex (@TIPO, @TIPO_DOC_PARA_POS) > 0 ) ) 
               BEGIN 
                   SELECT @TIPO_DOC_POS = CASE @TIPO 
                                            WHEN 'FAC' THEN 'F' 
                                            WHEN 'N/C' THEN 'D' 
                                            WHEN 'REC' THEN 'R' 
                                          END 
 
                   IF @CONCAT_COD_CORTO = 'S'
                     BEGIN 
                         SET @DOC_POS = Substring (@DOCUMENTO, 3, Len(@DOCUMENTO)
                                         ) 
 
                         SELECT  @CAJA = caja 
                         FROM   $$COMPANIA$$.caja_pos 
                         WHERE  codigo_corto = Substring (@DOCUMENTO, 1, 2) 
 
                         SELECT @EXISTE_DOC_POS = Count(0) 
                         FROM   $$COMPANIA$$.documento_pos 
                         WHERE  tipo = @TIPO_DOC_POS 
                                AND documento = @DOC_POS 
                                AND caja = @CAJA 
 
                         IF @EXISTE_DOC_POS > 0 
                           BEGIN 
                             IF @SALDO_DOC = 0
								BEGIN
									UPDATE $$COMPANIA$$.documento_pos 
									SET    saldo = @SALDO_DOC,
										   estado_cobro = 'C' 
									WHERE  tipo = @TIPO_DOC_POS 
											AND documento = @DOC_POS 
											AND caja = @CAJA 
								END
							 ELSE
								BEGIN
									UPDATE $$COMPANIA$$.documento_pos 
									SET    saldo = @SALDO_DOC,
											estado_cobro = 'D'  
									WHERE  tipo = @TIPO_DOC_POS 
											AND documento = @DOC_POS 
											AND caja = @CAJA 
								END	
					     END 
                     END 
                   ELSE 
                     BEGIN 
                         SET @DOC_POS = @DOCUMENTO 
 
                         SELECT @EXISTE_DOC_POS = Count(0) 
                         FROM   $$COMPANIA$$.documento_pos 
                         WHERE  tipo = @TIPO_DOC_POS 
                                AND documento = @DOCUMENTO 
 
                         IF @EXISTE_DOC_POS > 0 
                          BEGIN 
							IF @SALDO_DOC = 0
								BEGIN
									UPDATE $$COMPANIA$$.documento_pos 
									SET    saldo = @SALDO_DOC,
										   estado_cobro = 'C' 
									WHERE  tipo = @TIPO_DOC_POS 
											AND documento = @DOC_POS 
											AND caja = @CAJA 
								END
							ELSE
								BEGIN
									UPDATE $$COMPANIA$$.documento_pos 
									SET    saldo = @SALDO_DOC,
											estado_cobro = 'D'  
									WHERE  tipo = @TIPO_DOC_POS 
											AND documento = @DOC_POS 
											AND caja = @CAJA 
								END
                        END 
                     END 
               END 
 
             FETCH next FROM c_modified INTO @DOCUMENTO, @TIPO, @APLICACION, @FECHA_DOC, @MONTO_DOC, @SALDO_DOC 
         END 
 
       CLOSE c_modified 
 
       DEALLOCATE c_modified 
 
       IF ( @@ERROR <> 0 ) 
         BEGIN 
             RAISERROR( 'Error actualizando los saldos de los documentos que se han actualizado desde módulo de Cuentas por Cobrar.',16,1 ) 
 END 
 END;



CREATE TRIGGER $$COMPANIA$$.ACTUALIZA_SALDOS_POS_INS
ON $$COMPANIA$$.DOCUMENTOS_CC 
FOR INSERT 
AS 
   BEGIN 
       DECLARE @ERROR INT 
       DECLARE @CONCAT_COD_CORTO VARCHAR(1) 
       DECLARE @EXISTE_DOC_POS INT 
       DECLARE @TIPO_DOC_PARA_POS VARCHAR(20) 
       DECLARE @DOCUMENTO VARCHAR(50) 
       DECLARE @TIPO VARCHAR(3) 
       DECLARE @APLICACION VARCHAR(249) 
       DECLARE @FECHA_DOC DATETIME 
       DECLARE @MONTO_DOC DECIMAL (28, 8) 
       DECLARE @SALDO_DOC DECIMAL (28, 8) 
       DECLARE @DOC_POS VARCHAR(50) 
       DECLARE @TIPO_DOC_POS VARCHAR(3) 
       DECLARE @CAJA VARCHAR(3) 
 
       SET @TIPO_DOC_PARA_POS = 'FAC,N/C,REC'
 
       SELECT @CONCAT_COD_CORTO = valor 
       FROM   $$COMPANIA$$.globales 
       WHERE  modulo = 'PO'
              AND nombre = 'CONCAT_COD_CORTO' 
 
       DECLARE c_inserted CURSOR local FOR 
         SELECT documento, 
                tipo, 
                aplicacion, 
                fecha_documento, 
                monto, 
                saldo_local 
         FROM   inserted I 
 
       OPEN c_inserted 
 
       FETCH next FROM c_inserted INTO @DOCUMENTO, @TIPO, @APLICACION, @FECHA_DOC, @MONTO_DOC, @SALDO_DOC 
 
       WHILE @@FETCH_STATUS = 0 
         BEGIN 
            SELECT @TIPO_DOC_POS = CASE @TIPO 
                                    WHEN 'FAC' THEN 'F' 
                                    WHEN 'N/C' THEN 'D' 
                                    WHEN 'REC' THEN 'R' 
                                    END 
 
            IF @CONCAT_COD_CORTO = 'S'
                BEGIN 
                    SET @DOC_POS = Substring (@DOCUMENTO, 3, Len(@DOCUMENTO)
                                    ) 
 
                    SELECT @CAJA = caja 
                    FROM   $$COMPANIA$$.caja_pos 
                    WHERE  codigo_corto = Substring (@DOCUMENTO, 1, 2) 
 
                    SELECT @EXISTE_DOC_POS = Count(0) 
                    FROM   $$COMPANIA$$.documento_pos 
                    WHERE  tipo = @TIPO_DOC_POS 
                        AND documento = @DOC_POS 
                        AND caja = @CAJA 
 
                    IF @EXISTE_DOC_POS > 0 
                    BEGIN 
						IF @SALDO_DOC = 0
							BEGIN
								UPDATE $$COMPANIA$$.documento_pos 
								SET    saldo = @SALDO_DOC,
									   estado_cobro = 'C' 
								WHERE  tipo = @TIPO_DOC_POS 
										AND documento = @DOC_POS 
										AND caja = @CAJA 
							END
						ELSE
							BEGIN
								UPDATE $$COMPANIA$$.documento_pos 
								SET    saldo = @SALDO_DOC,
										estado_cobro = 'D'  
								WHERE  tipo = @TIPO_DOC_POS 
										AND documento = @DOC_POS 
										AND caja = @CAJA 
						END
                    END 
                END 
            ELSE 
                BEGIN 
                    SET @DOC_POS = @DOCUMENTO 
 
                    SELECT @EXISTE_DOC_POS = Count(0) 
                    FROM   $$COMPANIA$$.documento_pos 
                    WHERE  tipo = @TIPO_DOC_POS 
                        AND documento = @DOCUMENTO 
 
                    IF @EXISTE_DOC_POS > 0 
                    BEGIN 
						IF @SALDO_DOC = 0
							BEGIN
								UPDATE $$COMPANIA$$.documento_pos 
								SET    saldo = @SALDO_DOC,
									   estado_cobro = 'C' 
								WHERE  tipo = @TIPO_DOC_POS 
										AND documento = @DOC_POS 
										AND caja = @CAJA 
							END
						ELSE
							BEGIN
								UPDATE $$COMPANIA$$.documento_pos 
								SET    saldo = @SALDO_DOC,
										estado_cobro = 'D'  
								WHERE  tipo = @TIPO_DOC_POS 
										AND documento = @DOC_POS 
										AND caja = @CAJA 
						END
                    END 
                END 
 
             FETCH next FROM c_inserted INTO @DOCUMENTO, @TIPO, @APLICACION, @FECHA_DOC, @MONTO_DOC, @SALDO_DOC 
         END 
 
       CLOSE c_inserted 
 
       DEALLOCATE c_inserted 
 
       IF ( @@ERROR <> 0 ) 
         BEGIN 
             RAISERROR( 'Error actualizando los saldos de los documentos que se han actualizado desde módulo de Cuentas por Cobrar.',16,1 ) 
 END  
 END;

 
CREATE TRIGGER $$COMPANIA$$.NCF_CAJA_POS_POS_SINC_DEL
ON $$COMPANIA$$.NCF_CAJA_POS
FOR DELETE  
AS 
BEGIN   	
	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @CAJA VARCHAR(6)
	DECLARE @PREFIJO VARCHAR(20)

	SET @NOMBRETABLA = 'NCF_CAJA_POS'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT CAJA, PREFIJO
			FROM DELETED d

		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@CAJA, @PREFIJO
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM $$COMPANIA$$.' + @NOMBRETABLA + ' WHERE CAJA = ''' + @CAJA + ''' AND PREFIJO = ''' + @PREFIJO + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			FETCH NEXT FROM C_DELETED INTO 
			@CAJA, @PREFIJO
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla NCF_CAJA_POS.',16,1 )
	END
END;


CREATE TRIGGER $$COMPANIA$$.MENSAJERO_POS_SINC_DEL
ON $$COMPANIA$$.MENSAJERO
FOR DELETE  
AS 
BEGIN   	
	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @MENSAJERO VARCHAR(10)

	SET @NOMBRETABLA = 'MENSAJERO'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT MENSAJERO
			FROM DELETED d

		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@MENSAJERO
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM $$COMPANIA$$.' + @NOMBRETABLA + ' WHERE MENSAJERO = ''' + @MENSAJERO + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			FETCH NEXT FROM C_DELETED INTO 
			@MENSAJERO
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla MENSAJERO.',16,1 )
	END
END;


CREATE TRIGGER $$COMPANIA$$.TI_OFF_GRU_POS_SINC_DEL
ON $$COMPANIA$$.TIENDA_OFF_GRUPO
FOR DELETE  
AS 
BEGIN   	
	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @TIENDA_OFF VARCHAR(20)
	DECLARE @GRUPO VARCHAR(6)

	SET @NOMBRETABLA = 'TIENDA_OFF_GRUPO'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT TIENDA_OFF, GRUPO
			FROM DELETED d

		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@TIENDA_OFF, @GRUPO
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM $$COMPANIA$$.' + @NOMBRETABLA + ' WHERE TIENDA_OFF = ''' + @TIENDA_OFF + ''' AND GRUPO = ''' + @GRUPO + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			FETCH NEXT FROM C_DELETED INTO 
			@TIENDA_OFF, @GRUPO
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla TIENDA_OFF_GRUPO.',16,1 )
	END
END;


CREATE TRIGGER $$COMPANIA$$.GRUPO_CAJA_POS_SINC_DEL
ON $$COMPANIA$$.GRUPO_CAJA
FOR DELETE  
AS 
BEGIN   	
	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @GRUPO VARCHAR(6)
	DECLARE @CAJA VARCHAR(6)

	SET @NOMBRETABLA = 'GRUPO_CAJA'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT GRUPO, CAJA
			FROM DELETED d

		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@GRUPO, @CAJA
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM $$COMPANIA$$.' + @NOMBRETABLA + ' WHERE GRUPO = ''' + @GRUPO + ''' AND CAJA = ''' + @CAJA + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			FETCH NEXT FROM C_DELETED INTO 
			@GRUPO, @CAJA
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla GRUPO_CAJA.',16,1 )
	END
END;



CREATE TRIGGER $$COMPANIA$$.CONSEC_CAJA_POS_POS_SINC_DEL
ON $$COMPANIA$$.CONSEC_CAJA_POS
FOR DELETE  
AS 
BEGIN   	
	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @CODIGO VARCHAR(10)
	DECLARE @CAJA VARCHAR(6)
	
	SET @NOMBRETABLA = 'CONSEC_CAJA_POS'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT CODIGO, CAJA
			FROM DELETED d

		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@CODIGO, @CAJA
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM $$COMPANIA$$.' + @NOMBRETABLA + ' WHERE CODIGO = ''' + @CODIGO + ''' AND CAJA = ''' + @CAJA + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			FETCH NEXT FROM C_DELETED INTO 
			@CODIGO, @CAJA
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla CONSEC_CAJA_POS.',16,1 )
	END
END;


CREATE TRIGGER $$COMPANIA$$.TIPO_TARJ_POS_POS_SINC_DEL
ON $$COMPANIA$$.TIPO_TARJETA_POS
FOR DELETE  
AS 
BEGIN   	
 	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @TIPO_TARJETA VARCHAR(12)
	DECLARE @CLIENTE VARCHAR(20)
	DECLARE @TIPO_COBRO VARCHAR(1)

	SET @NOMBRETABLA = 'TIPO_TARJETA_POS'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT TIPO_TARJETA, CLIENTE, TIPO_COBRO
			FROM DELETED d
			
		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@TIPO_TARJETA, @CLIENTE, @TIPO_COBRO
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM $$COMPANIA$$.' + @NOMBRETABLA + ' WHERE TIPO_TARJETA = ''' + @TIPO_TARJETA + ''' AND CLIENTE = ''' + @CLIENTE + ''' AND TIPO_COBRO = ''' + @TIPO_COBRO + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			FETCH NEXT FROM C_DELETED INTO 
			@TIPO_TARJETA, @CLIENTE, @TIPO_COBRO
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla TIPO_TARJETA_POS.',16,1 )
	END
END;

CREATE TRIGGER $$COMPANIA$$.TIPO_TARJ_CAJA_POS_SINC_DEL
ON $$COMPANIA$$.TIPO_TARJETA_CAJA
FOR DELETE  
AS 
BEGIN   	
	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @TIPO_TARJETA VARCHAR(12)
	DECLARE @CAJA VARCHAR(6)

	SET @NOMBRETABLA = 'TIPO_TARJETA_CAJA'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT TIPO_TARJETA, CAJA
			FROM DELETED d

		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@TIPO_TARJETA, @CAJA
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM $$COMPANIA$$.' + @NOMBRETABLA + ' WHERE TIPO_TARJETA = ''' + @TIPO_TARJETA + ''' AND CAJA = ''' + @CAJA + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			FETCH NEXT FROM C_DELETED INTO 
			@TIPO_TARJETA, @CAJA
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla TIPO_TARJETA_CAJA.',16,1 )
	END
END;


CREATE TRIGGER $$COMPANIA$$.TIPO_DOC_DEF_POS_SINC_DEL
ON $$COMPANIA$$.TIPO_DOC_DEFAULT
FOR DELETE  
AS 
BEGIN   	
	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @CAJA VARCHAR(6)
	DECLARE @CONSEC_DEFAULT VARCHAR(10)
	DECLARE @TIPO_DOCUMENTO VARCHAR(1)

	SET @NOMBRETABLA = 'TIPO_DOC_DEFAULT'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT CAJA, CONSEC_DEFAULT, TIPO_DOCUMENTO
			FROM DELETED d

		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@CAJA, @CONSEC_DEFAULT, @TIPO_DOCUMENTO
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM $$COMPANIA$$.' + @NOMBRETABLA + ' WHERE CAJA = ''' + @CAJA + ''' AND CONSEC_DEFAULT = ''' + @CONSEC_DEFAULT + ''' AND TIPO_DOCUMENTO = ''' + @TIPO_DOCUMENTO + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			FETCH NEXT FROM C_DELETED INTO 
			@CAJA, @CONSEC_DEFAULT, @TIPO_DOCUMENTO
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla TIPO_DOC_DEFAULT.',16,1 )
	END
END;

CREATE TRIGGER $$COMPANIA$$.CLASE_DOC_POS_POS_SINC_DEL
ON $$COMPANIA$$.CLASE_DOC_POS
FOR DELETE  
AS 
BEGIN   	
	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @CODIGO VARCHAR(10)
	
	SET @NOMBRETABLA = 'CLASE_DOC_POS'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT CODIGO
			FROM DELETED d

		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@CODIGO
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM $$COMPANIA$$.' + @NOMBRETABLA + ' WHERE CODIGO = ''' + @CODIGO + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			FETCH NEXT FROM C_DELETED INTO 
			@CODIGO
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla CLASE_DOC_POS.',16,1 )
	END
END;


CREATE TRIGGER $$COMPANIA$$.MOTIVO_CAN_EXP_POS_SINC_DEL
ON $$COMPANIA$$.MOTIVO_CANCEL_EXPR
FOR DELETE  
AS 
BEGIN   	
	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @CODIGO VARCHAR(10)

	SET @NOMBRETABLA = 'MOTIVO_CANCEL_EXPR'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT CODIGO
			FROM DELETED d

		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@CODIGO
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM $$COMPANIA$$.' + @NOMBRETABLA + ' WHERE CODIGO = ''' + @CODIGO + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			FETCH NEXT FROM C_DELETED INTO 
			@CODIGO
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla MOTIVO_CANCEL_EXPR.',16,1 )
	END
END;


CREATE TRIGGER $$COMPANIA$$.CLIENTE_EXPR_ENTR_POS_SINC_DEL
ON $$COMPANIA$$.CLIENTE_EXPR_ENTR
FOR DELETE  
AS 
BEGIN   	
	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @CLIENTE_EXP VARCHAR(20)
	DECLARE @ENTREGAR_A VARCHAR(80)

	SET @NOMBRETABLA = 'CLIENTE_EXPR_ENTR'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT CLIENTE_EXP, ENTREGAR_A
			FROM DELETED d

		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@CLIENTE_EXP, @ENTREGAR_A
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM $$COMPANIA$$.' + @NOMBRETABLA + ' WHERE CLIENTE_EXP = ''' + @CLIENTE_EXP + ''' AND ENTREGAR_A = ''' + @ENTREGAR_A + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			
			FETCH NEXT FROM C_DELETED INTO 
			@CLIENTE_EXP, @ENTREGAR_A
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla CLIENTE_EXPR_ENTR.',16,1 )
	END
END;


CREATE TRIGGER ERPADMIN.PRIVILEGIO_EX_POS_SINC_DEL
ON ERPADMIN.PRIVILEGIO_EX
FOR DELETE 
AS
BEGIN 
	DECLARE @ERROR				INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @USUARIO			VARCHAR(10)
	DECLARE @CONJUNTO			VARCHAR(10)
	DECLARE @ACCION				INT
	
	SET @NOMBRETABLA = 'PRIVILEGIO_EX'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR

		SELECT USUARIO, CONJUNTO, ACCION
		FROM DELETED d

		OPEN C_DELETED	
		FETCH NEXT FROM C_DELETED INTO
		@USUARIO, @CONJUNTO, @ACCION

		SET @ERROR = 0

		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN

			SET @SENTENCIA = 'DELETE FROM ERPADMIN.' + @NOMBRETABLA + ' WHERE USUARIO = ''' + @USUARIO + ''' AND CONJUNTO = ''' + @CONJUNTO + ''' AND ACCION = ''' + CONVERT(VARCHAR(36),@ACCION) + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA

			FETCH NEXT FROM C_DELETED INTO
			@USUARIO, @CONJUNTO, @ACCION
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	IF (@@ERROR <> 0 OR @ERROR <> 0)
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla PRIVILEGIO_EX.',16,1 )
	END
END;


CREATE TRIGGER ERPADMIN.MEMBRESIA_POS_SINC_DEL
ON ERPADMIN.MEMBRESIA
FOR DELETE  
AS 
BEGIN   	
	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @GRUPO VARCHAR(25)
	DECLARE @USUARIO VARCHAR(25)

	SET @NOMBRETABLA = 'MEMBRESIA'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT GRUPO, USUARIO
			FROM DELETED d
			
		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@GRUPO, @USUARIO
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM ERPADMIN.' + @NOMBRETABLA + ' WHERE GRUPO = ''' + @GRUPO + ''' AND USUARIO = ''' + @USUARIO + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			FETCH NEXT FROM C_DELETED INTO 
			@GRUPO, @USUARIO
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla MEMBRESIA.',16,1 )
	END
END;


CREATE TRIGGER ERPADMIN.REPORTE_DETALLE_POS_SINC_DEL
ON ERPADMIN.REPORTE_DETALLE
FOR DELETE  
AS 
BEGIN   	
	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @ACCION VARCHAR(10)
	DECLARE @REPORTE VARCHAR(100)

	SET @NOMBRETABLA = 'REPORTE_DETALLE'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT ACCION, REPORTE
			FROM DELETED d

		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@ACCION, @REPORTE
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM ERPADMIN.' + @NOMBRETABLA + ' WHERE ACCION = ''' + @ACCION + ''' AND REPORTE = ''' + @REPORTE + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			FETCH NEXT FROM C_DELETED INTO 
			@ACCION, @REPORTE
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla REPORTE_DETALLE.',16,1 )
	END
END;


CREATE TRIGGER ERPADMIN.REPORTE_USUARIO_POS_SINC_DEL
ON ERPADMIN.REPORTE_USUARIO
FOR DELETE  
AS 
BEGIN   	
	DECLARE @ERROR INT
	DECLARE @SENTENCIA   		VARCHAR(254)
	DECLARE @NOMBRETABLA		VARCHAR(254)
	DECLARE @USUARIO_ACTUAL		VARCHAR(30)

	DECLARE @ACCION VARCHAR(10)
	DECLARE @USUARIO VARCHAR(25)
	DECLARE @REPORTE VARCHAR(100)

	SET @NOMBRETABLA = 'REPORTE_USUARIO'

	EXEC ERPADMIN.LeerUsuarioActual @USUARIO_ACTUAL OUTPUT

	
	IF NOT ('SoftlandSync' = @USUARIO_ACTUAL)
	BEGIN
		DECLARE C_DELETED CURSOR LOCAL FOR
			SELECT ACCION, USUARIO, REPORTE
			FROM DELETED d

		OPEN C_DELETED
		FETCH NEXT FROM C_DELETED INTO 
		@ACCION, @USUARIO, @REPORTE
		
		SET @ERROR = 0
		
		WHILE @@FETCH_STATUS = 0 AND @ERROR = 0
		BEGIN
			SET @SENTENCIA = 'DELETE FROM ERPADMIN.' + @NOMBRETABLA + ' WHERE ACCION = ''' + @ACCION + ''' AND USUARIO = ''' + @USUARIO + ''' AND REPORTE = ''' + @REPORTE + ''''
			
			EXECUTE @ERROR = $$COMPANIA$$.POS_INSERTA_ELIMINACION @SENTENCIA, @NOMBRETABLA
			
			FETCH NEXT FROM C_DELETED INTO 
			@ACCION, @USUARIO, @REPORTE
		END

		CLOSE C_DELETED
		DEALLOCATE C_DELETED
	END
	
	IF (@@ERROR <> 0) 
	BEGIN
		RAISERROR( 'Error generando la sentencia de eliminación de la tabla REPORTE_USUARIO.',16,1 )
	END
END;

