
CREATE TABLE INFORMACION_GRUPO (
         INFORMACION_GRUPO	INT	NOT NULL,
         MODULO			INT	NOT NULL,
         INFORMACION		INT	NOT NULL )
go 


ALTER TABLE INFORMACION_GRUPO
         ADD CONSTRAINT INFGRUPOPK PRIMARY KEY NONCLUSTERED
         	(INFORMACION_GRUPO, MODULO, INFORMACION )
go 


CREATE TABLE IMAGEN_CE (
         INFORMACION		INT		NOT NULL,
         MODULO			INT		NOT NULL,
         DIRECCION_IMAGEN	VARCHAR(70)	NOT NULL,
         POSICION_IMAGEN	VARCHAR(15)	NULL,
         LINK_IMAGEN		VARCHAR(50)	NULL )
go 


ALTER TABLE IMAGEN_CE
         ADD CONSTRAINT IMAGENCEPK PRIMARY KEY NONCLUSTERED
         	(INFORMACION, MODULO )
go 
         	

CREATE TABLE INFORMACION (
         INFORMACION		INT		NOT NULL IDENTITY(1,1),
         MODULO			INT		NOT NULL,
         TIPO_FORMATO		INT		NOT NULL,
         TIPO_INFORMACION	INT		NOT NULL,
         NOMBRE_INFORMACION     VARCHAR(50)     NOT NULL,         
         FECHA_INICIO		DATETIME	NOT NULL,
         FECHA_HASTA		DATETIME	NOT NULL,
         CUERPO			TEXT		NULL,
         TEXTO_LINK		VARCHAR(50)	NULL,
         DIRECCION_LINK		VARCHAR(50)	NULL,
         IDIOMA 		VARCHAR(5) 	NULL)
go 


ALTER TABLE INFORMACION
         ADD CONSTRAINT INFORMACIONPK PRIMARY KEY NONCLUSTERED
         	(INFORMACION, MODULO )
go 
         	

CREATE TABLE MODULO (
         MODULO		INT		NOT NULL,
         NOMBRE_MODULO	VARCHAR(50)	NOT NULL )
go 


ALTER TABLE MODULO
         ADD CONSTRAINT MODULOPK PRIMARY KEY NONCLUSTERED (MODULO )
go 


CREATE TABLE NOTICIA (
         INFORMACION	INT	NOT NULL,
         MODULO		INT	NOT NULL )
go 


ALTER TABLE NOTICIA
         ADD CONSTRAINT NOTICIAPK PRIMARY KEY NONCLUSTERED
         	(INFORMACION, MODULO )
go 


CREATE TABLE PAGINA (
         PAGINA		INT		NOT NULL,
         MODULO		INT		NOT NULL,
         NOMBRE_PAGINA	VARCHAR(30)	NOT NULL )
go 


ALTER TABLE PAGINA
         ADD CONSTRAINT PAGINAPK PRIMARY KEY NONCLUSTERED (PAGINA, MODULO )
go 


CREATE TABLE SCROLL (
         INFORMACION	INT		NOT NULL,
         MODULO		INT		NOT NULL )
go 


ALTER TABLE SCROLL
         ADD CONSTRAINT SCROLLPK PRIMARY KEY NONCLUSTERED
         	(INFORMACION, MODULO )
go 
         	

CREATE TABLE SEC_INFORMACION (
         SECCION	INT		NOT NULL,
         PAGINA		INT		NOT NULL,
         MODULO		INT		NOT NULL,
         INFORMACION	INT		NOT NULL )
go 


ALTER TABLE SEC_INFORMACION
         ADD CONSTRAINT SECINFPK PRIMARY KEY NONCLUSTERED
         	(SECCION, PAGINA, MODULO, INFORMACION )
go 


CREATE TABLE SECCION (
         SECCION	INT		NOT NULL,
         PAGINA		INT		NOT NULL,
         MODULO		INT		NOT NULL,
         DESC_SECCION	VARCHAR(50)	NOT NULL )
go 


ALTER TABLE SECCION
         ADD CONSTRAINT SECCIONPK PRIMARY KEY NONCLUSTERED
         	(SECCION, PAGINA, MODULO )
go 


CREATE TABLE TEXTO (
         INFORMACION		INT		NOT NULL,
         MODULO			INT		NOT NULL,
         TITULO			VARCHAR(50)	NULL,
         COLOR_TITULO		VARCHAR(15)	NOT NULL,
         POSICION_TITULO	VARCHAR(15)	NOT NULL,
         COLOR_CUERPO		VARCHAR(15)	NULL )
go 


ALTER TABLE TEXTO
         ADD CONSTRAINT TEXTOPK PRIMARY KEY NONCLUSTERED
         	(INFORMACION, MODULO )
go 
         	

CREATE TABLE TIPO_FORMATO (
         TIPO_FORMATO		INT		NOT NULL,
         MODULO			INT		NOT NULL,
         DESC_TIPO_FORMATO	VARCHAR(10)	NOT NULL )
go 


ALTER TABLE TIPO_FORMATO
         ADD CONSTRAINT TIPOFORMATOPK PRIMARY KEY NONCLUSTERED
         	(TIPO_FORMATO, MODULO )
go 


CREATE TABLE TIPO_INFORMACION (
         TIPO_INFORMACION	INT		NOT NULL,
         MODULO			INT		NOT NULL,
         DESC_TIPO_INFO		VARCHAR(10)	NOT NULL )
go 


ALTER TABLE TIPO_INFORMACION
         ADD CONSTRAINT TIPINFPK PRIMARY KEY NONCLUSTERED
         	(TIPO_INFORMACION, MODULO )
go 


