CREATE NONCLUSTERED INDEX Ind_Asiento_Fase_PY_PFCF ON $$COMPANIA$$.ASIENTO_FASE_PY
(
	PROYECTO ASC,
	FASE ASC,
	CONTABILIDAD ASC,
	FECHA ASC
)
INCLUDE ( 	DEBITO_DOLAR,
	CREDITO_DOLAR) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX Ind_ASIENTO_FASE_PY_FPCF ON $$COMPANIA$$.ASIENTO_FASE_PY
(
	FECHA ASC,
	PROYECTO ASC,
	CONTABILIDAD ASC,
	FASE ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX Ind_ASIENTO_FASE_PY_PFCF2 ON $$COMPANIA$$.ASIENTO_FASE_PY
(
	PROYECTO ASC,
	FASE ASC,
	CONTABILIDAD ASC,
	FECHA ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX Ind_ASIENTO_FASE_PY_C ON $$COMPANIA$$.ASIENTO_FASE_PY
(
	CONTABILIDAD ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE STATISTICS Std_ASIENTO_FASE_PY_C ON $$COMPANIA$$.ASIENTO_FASE_PY(FASE, CONTABILIDAD)
go

CREATE STATISTICS Std_ASIENTO_FASE_PY_CFP ON $$COMPANIA$$.ASIENTO_FASE_PY(CONTABILIDAD, FECHA, PROYECTO)
go

CREATE STATISTICS Std_ASIENTO_FASE_PY_FPF ON $$COMPANIA$$.ASIENTO_FASE_PY(FASE, PROYECTO, FECHA)
go

CREATE STATISTICS Std_ASIENTO_FASE_PY_PCF ON $$COMPANIA$$.ASIENTO_FASE_PY(FASE, PROYECTO, CONTABILIDAD, FECHA)
go

CREATE NONCLUSTERED INDEX Ind_FASE_PY_PTFNDAFF ON $$COMPANIA$$.FASE_PY
(
	PROYECTO ASC,
	TIPO ASC,
	FASE ASC,
	NOMBRE ASC,
	DESCRIPCION ASC,
	ACEPTA_DATOS ASC,
	FECHA_INICIAL ASC,
	FECHA_FINAL ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE STATISTICS Std_FASE_PY_FNDAFFP ON $$COMPANIA$$.FASE_PY(FASE, NOMBRE, DESCRIPCION, ACEPTA_DATOS, FECHA_INICIAL, FECHA_FINAL, PROYECTO)
go
