
 
 CREATE TABLE ACC_PER_IMPRESION (
        NUMERO_ACCION        int 		NOT NULL,
        USUARIO              VARCHAR(25) 	NOT NULL
 )
go
 
 
 ALTER TABLE ACC_PER_IMPRESION
        ADD CONSTRAINT XPKACC_PER_IMPRESI PRIMARY KEY NONCLUSTERED (
               NUMERO_ACCION, USUARIO)
go


CREATE TABLE CATALOGO_SUIRPLUS
(
	CODIGO 			VARCHAR(15) 	NOT NULL,
	CODIGO_SUIRPLUS 	VARCHAR(15) 	NOT NULL,
	DESC_SUIRPLUS 		VARCHAR (50) 	NOT NULL,
	TIPO 			VARCHAR(1) 	NOT NULL
)
go


ALTER TABLE CATALOGO_SUIRPLUS 
	ADD CONSTRAINT CATALOGO_SUIRPLUSPK PRIMARY KEY NONCLUSTERED (CODIGO, TIPO)
go

 
CREATE TABLE CAT_PUESTO_EXTERNO (
         CAT_PUESTO_EXTERNO         VARCHAR(12)         NOT NULL,
         DESCRIPCION         VARCHAR(254)         NOT NULL )
go

ALTER TABLE CAT_PUESTO_EXTERNO
         ADD CONSTRAINT CATPUESTOEXTERNOPK PRIMARY KEY NONCLUSTERED
         (CAT_PUESTO_EXTERNO )
go 

CREATE TABLE CLASE_SEGURO (
         CLASE_SEGURO         VARCHAR(4)         NOT NULL,
         DESCRIPCION         VARCHAR(40)         NOT NULL )
go

ALTER TABLE CLASE_SEGURO
         ADD CONSTRAINT CLASE_SEGUROPK PRIMARY KEY NONCLUSTERED
         (CLASE_SEGURO )
go



CREATE TABLE DETALLE_PREASIENTO (
	ASIENTO           	VARCHAR(10) 	NOT NULL,
        CONSECUTIVO		int 		NOT NULL,
        NIT                  	VARCHAR(20) 	NULL,
        CENTRO_COSTO         	VARCHAR(25)	NOT NULL,
        CUENTA_CONTABLE      	VARCHAR(25) 	NOT NULL,
        FUENTE               	VARCHAR(40) 	NOT NULL,
        REFERENCIA           	VARCHAR(249) 	NOT NULL,
        DEBITO_LOCAL         	DECIMAL(28,8) 	NULL,
        DEBITO_DOLAR         	DECIMAL(28,8) 	NULL,
        CREDITO_LOCAL        	DECIMAL(28,8) 	NULL,
        CREDITO_DOLAR        	DECIMAL(28,8) 	NULL,
        DEBITO_UNIDADES      	DECIMAL(28,8) 	NULL,
        CREDITO_UNIDADES     	DECIMAL(28,8) 	NULL,
        TIPO_CAMBIO 	     	DECIMAL(28,8) 	NULL,
        BASE_LOCAL           	DECIMAL(28,8) 	NULL,
	BASE_DOLAR           	DECIMAL(28,8) 	NULL,
	PROYECTO             	VARCHAR(25) 	NULL,
	FASE 		     	VARCHAR(25) 	NULL,
	PROCESO			VARCHAR(10) 	NOT NULL
 )
go
 
ALTER TABLE DETALLE_PREASIENTO
	ADD CONSTRAINT PREASIENTOPK PRIMARY KEY NONCLUSTERED (PROCESO, ASIENTO, CONSECUTIVO)
go


CREATE TABLE DOCUMENTO (
         DOCUMENTO 	INT        	NOT NULL,
         NOMBRE         VARCHAR(254) 	NOT NULL,
         CONTENIDO 	IMAGE         	NULL )
go         

ALTER TABLE DOCUMENTO
         ADD CONSTRAINT DOCUMENTOPK PRIMARY KEY NONCLUSTERED
         	(DOCUMENTO )
go  
 
 CREATE TABLE DOCUMENTOS_RH (
        DOCUMENTO            VARCHAR(8)  	NOT NULL,
        DESCRIPCION          VARCHAR(40) 	NOT NULL,
        UBICACION            VARCHAR(50) 	NULL,
        NOTAS                TEXT 		NULL,
        IDENTIFICADOR 	     INT 		NULL
 )
go
 
 
 ALTER TABLE DOCUMENTOS_RH
        ADD CONSTRAINT XPKDOCUMENTOS_RH PRIMARY KEY (DOCUMENTO)
go
 

CREATE TABLE EMP_EXPERIENCIA (
         EMPLEADO         	VARCHAR(20) 	NOT NULL,
         CONSECUTIVO         	SMALLINT        NOT NULL,
         FECHA_INGRESO         	DATETIME        NOT NULL,
         FECHA_SALIDA         	DATETIME        NULL,
         EMPRESA         	VARCHAR(100)    NOT NULL,
         PUESTO         	VARCHAR(100)    NOT NULL,
         MOTIVO_SALIDA         	VARCHAR(254)    NULL,
         REFERENCIA         	VARCHAR(100)    NULL,
         TEL_REFERENCIA         VARCHAR(20)     NULL,
         EMAIL_REFERENCIA       VARCHAR(40)     NULL,
         FUNCIONES         	TEXT         	NULL )
go


ALTER TABLE EMP_EXPERIENCIA
         ADD CONSTRAINT EMP_EXPERIENCIAPK PRIMARY KEY NONCLUSTERED
         (EMPLEADO, CONSECUTIVO )
go
 
 CREATE TABLE EMPLEADO (
        EMPLEADO             	VARCHAR(20) 	NOT NULL,
        DETALLE_DIR_HAB      	int 			NULL,
        NOMBRE               	VARCHAR(70) 	NOT NULL,
        SEXO                 	VARCHAR(1) 		NOT NULL,
        TIPO_SANGRE          	VARCHAR(4) 		NULL,
        ESTADO_EMPLEADO      	VARCHAR(4) 		NOT NULL,
        ACTIVO               	VARCHAR(1) 		NOT NULL,
        IDENTIFICACION       	VARCHAR(20) 	NULL,
        PASAPORTE            	VARCHAR(20) 	NULL,
        FECHA_INGRESO        	DATETIME 		NOT NULL,
        FECHA_SALIDA         	DATETIME 		NULL,
        DEPARTAMENTO         	VARCHAR(10) 	NOT NULL,
        PUESTO               	VARCHAR(8) 		NOT NULL,
        PLAZA                	VARCHAR(8) 		NOT NULL,
        NOMINA               	VARCHAR(4) 		NOT NULL,
        CENTRO_COSTO         	VARCHAR(25) 	NOT NULL,
        FECHA_NACIMIENTO     	DATETIME 		NOT NULL,
        UBICACION            	VARCHAR(8) 		NOT NULL,
        PAIS                 	VARCHAR(4) 		NOT NULL,
        ESTADO_CIVIL         	VARCHAR(1) 		NOT NULL,
        DEPENDIENTES         	smallint 		NULL,
        ASEGURADO            	VARCHAR(20) 	NULL,
        CLASE_SEGURO         	VARCHAR(4) 		NULL,
        PERMISO_CONDUCIR     	VARCHAR(20) 	NULL,
        PERMISO_SALUD        	VARCHAR(20) 	NULL,
        NIT                  	VARCHAR(20) 	NULL,
        VACS_PENDIENTES      	DECIMAL(28,8) 	NOT NULL,
        VACS_ULT_CALCULO     	DATETIME 		NOT NULL,
        FECHA_PROX_EVAL      	DATETIME 		NULL,
        SALARIO_REFERENCIA   	DECIMAL(28,8) 	NOT NULL,
        FORMA_PAGO           	VARCHAR(1) 		NOT NULL,
        CUENTA_ENTIDAD  		VARCHAR(50) 	NULL,
        ENTIDAD_FINANCIERA   	VARCHAR(8) 		NULL,
        HORARIO              	VARCHAR(4) 		NOT NULL,
        DIRECCION_HAB        	TEXT 			NULL,
        DIRECCION_POSTAL     	TEXT 			NULL,
        TELEFONO1            	VARCHAR(20) 	NULL,
        NOTAS_TEL1           	VARCHAR(40) 	NULL,
        TELEFONO2            	VARCHAR(20) 	NULL,
        NOTAS_TEL2           	VARCHAR(40) 	NULL,
        TELEFONO3            	VARCHAR(20) 	NULL,
        NOTAS_TEL3           	VARCHAR(40) 	NULL,
        FOTOGRAFIA           	image 			NULL,
        RUBRO1               	VARCHAR(40) 	NULL,
        RUBRO2               	VARCHAR(40) 	NULL,
        RUBRO3               	VARCHAR(40) 	NULL,
        RUBRO4               	VARCHAR(40) 	NULL,
        RUBRO5               	VARCHAR(40) 	NULL,
        RUBRO6               	VARCHAR(40) 	NULL,
        RUBRO7               	VARCHAR(40) 	NULL,
        RUBRO8               	VARCHAR(40) 	NULL,
        RUBRO9               	VARCHAR(40) 	NULL,
        RUBRO10              	VARCHAR(40) 	NULL,
        RUBRO11              	VARCHAR(40) 	NULL,
        RUBRO12              	VARCHAR(40) 	NULL,
        RUBRO13              	VARCHAR(40) 	NULL,
        RUBRO14              	VARCHAR(40) 	NULL,
        RUBRO15              	VARCHAR(40) 	NULL,
        FECHA_NO_PAGO        	DATETIME 		NOT NULL,
        TIPO_SALARIO_AUMEN   	VARCHAR(1) 		NOT NULL,
        FECHA_ANTIG_EMP      	DATETIME 		NULL,
        FECHA_ANTIG_GOB      	DATETIME 		NULL,
        SALARIO_DIARIO_INT   	DECIMAL(28,8) 	NULL,
        PRIMER_APELLIDO      	VARCHAR(20) 	NULL,
        SEGUNDO_APELLIDO     	VARCHAR(20) 	NULL,
        NOMBRE_PILA          	VARCHAR(30) 	NULL,
        E_MAIL               	VARCHAR(249) 	NULL,
        DETALLE_DIR_POSTAL   	int 			NULL,
        VACS_ADICIONALES     	DECIMAL(28,8) 	NOT NULL,
        RUBRO16              	VARCHAR(40) 	NULL,
		RUBRO17              	VARCHAR(40) 	NULL,
		RUBRO18              	VARCHAR(40) 	NULL,
		RUBRO19              	VARCHAR(40) 	NULL,
		RUBRO20              	VARCHAR(40) 	NULL,
		RUBRO21              	VARCHAR(40) 	NULL,
		RUBRO22              	VARCHAR(40) 	NULL,
		RUBRO23              	VARCHAR(40) 	NULL,
		RUBRO24              	VARCHAR(40) 	NULL,
        RUBRO25              	VARCHAR(40) 	NULL,
        SALARIOPD_LOCAL	     	DECIMAL(28,8) 	NULL,
		SALARIOPD_DOLAR	     	DECIMAL(28,8) 	NULL,
		SALARIOPD_NOMINA     	DECIMAL(28,8) 	NULL,
		DIAS_DISP_INCAP 		DECIMAL(28,8) 	NULL,
		USUARIO_CREACION		VARCHAR(25)		NULL,
		FECHA_HORA_CREACION		DATETIME		NULL,
		USUARIO_ULT_MOD			VARCHAR(25)		NULL,
		FCH_HORA_ULT_MOD		DATETIME		NULL,
		TIPO_CUENTA_ENTIDAD 	VARCHAR(12) 	NULL,
		CTA_ELECTRONICA 		VARCHAR(50) 	NULL,
		DIVISION_GEOGRAFICA1 	VARCHAR(12) 	NULL,
		DIVISION_GEOGRAFICA2 	VARCHAR(12) 	NULL,
		PAIS_DIREC				VARCHAR(4)  	NULL,
		TIPO_SALARIO 			VARCHAR(1) 		NULL,
		BENEFICIO_COLECTIVO 	VARCHAR(2) 		NULL,
		TIPO_MEDIDAS_CERTIFICADAS int NULL,
		TIPO_NIVEL_EDUCATIVO int NULL
)
go
 
 
 ALTER TABLE EMPLEADO
        ADD CONSTRAINT EMPLEADOPK PRIMARY KEY NONCLUSTERED (EMPLEADO)
go
 
 
 CREATE TABLE EMPLEADO_ACADEMICO (
        EMPLEADO             VARCHAR(20) NOT NULL,
        FECHA_OBTENCION      DATETIME NOT NULL,
        TITULO               VARCHAR(50) NOT NULL,
        INSTITUCION          VARCHAR(250) NOT NULL,
        FECHA_VENCIMIENTO    DATETIME NULL,
        HORAS_CURSO          smallint NULL,
        HORAS_COMPLETAS      smallint NULL,
        CONCLUIDO            VARCHAR(1) NOT NULL,
        PROFESOR             VARCHAR(40) NULL,
        NOTAS                TEXT NULL,
        TIPO_CAPACITACION    VARCHAR(40) NULL,
        CONSECUTIVO         SMALLINT     NOT NULL,
        TIPO_ACADEMICO         VARCHAR(4)         NOT NULL
 )
go
 
 
ALTER TABLE EMPLEADO_ACADEMICO
         ADD CONSTRAINT EMPACADPKEMPLEADO PRIMARY KEY NONCLUSTERED
         (EMPLEADO, CONSECUTIVO )
go
 
 
 CREATE TABLE EMPLEADO_ACC_PER (
        NUMERO_ACCION        int 		NOT NULL,
        PUESTO               VARCHAR(8)  	NULL,
        PLAZA                VARCHAR(8)  	NULL,
        CENTRO_COSTO         VARCHAR(25) 	NULL,
        DEPARTAMENTO         VARCHAR(10) 	NULL,
        TIPO_ACCION          VARCHAR(4) 	NOT NULL,
        FECHA                DATETIME 		NOT NULL,
        EMPLEADO             VARCHAR(20) 	NOT NULL,
        SALARIO_PROMEDIO     DECIMAL(28,8) 	NULL,
        TIPO_AUSENCIA        VARCHAR(4) 	NULL,
        ESTADO_EMPLEADO      VARCHAR(4) 	NULL,
        FECHA_RIGE           DATETIME 		NOT NULL,
        FECHA_VENCE          DATETIME 		NULL,
        NOTAS                TEXT 		NULL,
        USUARIO              VARCHAR(25) 	NULL,
        FECHA_HORA           DATETIME 		NOT NULL,
        APROBADA_POR         VARCHAR(25) 	NULL,
        FECHA_APROBACION     DATETIME 		NULL,
        USUARIO_VIGENTE      VARCHAR(25) 	NULL,
        FECHA_VIGENTE        DATETIME 		NULL,
        USUARIO_APLICACION   VARCHAR(25) 	NULL,
        FECHA_APLICACION     DATETIME 		NULL,
        ESTADO_ACCION        VARCHAR(1) 	NOT NULL,
        DIAS_ACCION          Decimal(28,8) 	NULL,
        SALARIO_DIARIO_INT   DECIMAL(28,8) 	NULL,
        RUBRO1               VARCHAR(40) 	NULL,
        RUBRO2               VARCHAR(40) 	NULL,
        RUBRO3               VARCHAR(40) 	NULL,
        RUBRO4               VARCHAR(40) 	NULL,
        RUBRO5               VARCHAR(40) 	NULL,
        RUBRO6               VARCHAR(40) 	NULL,
        RUBRO7               VARCHAR(40) 	NULL,
        RUBRO8               VARCHAR(40) 	NULL,
        RUBRO9               VARCHAR(40) 	NULL,
        RUBRO10              VARCHAR(40) 	NULL,
        SALDO         	     DECIMAL(28,8) 	NOT NULL,
        NOMINA         	     VARCHAR(4)    	NULL,
        USUARIO_ANULACION    VARCHAR(25)   	NULL,
        FECHA_ANULACION      DATETIME      	NULL,
        REGIMEN_VACACIONAL   VARCHAR(12)   	NULL,
	ADMINISTRADORA	     VARCHAR(10)	NULL        
 )
go
 
 
 ALTER TABLE EMPLEADO_ACC_PER
        ADD CONSTRAINT ACCPERPKTACCEMP PRIMARY KEY NONCLUSTERED (
               NUMERO_ACCION)
go

CREATE TABLE EMPLEADO_ACC_SALDO (
         CONSECUTIVO         INT         NOT NULL,
         NUMERO_ACCION         INT         NOT NULL,
         NOMINA         VARCHAR(4)         NULL,
         NUMERO_NOMINA         SMALLINT         NULL,
         LIQUIDACION         INT         NULL,
         DIAS_APLICADOS         DECIMAL(28,8)         NOT NULL )
go

ALTER TABLE EMPLEADO_ACC_SALDO
         ADD CONSTRAINT EMPACCSALDOPK PRIMARY KEY NONCLUSTERED
         (CONSECUTIVO )
go 
 
 CREATE TABLE EMPLEADO_ACCIDENTE (
        EMPLEADO             VARCHAR(20) NOT NULL,
        FECHA                DATETIME NOT NULL,
        NUMERO_ACCION        int NULL,
        PUESTO               VARCHAR(8) NOT NULL,
        DEPARTAMENTO         VARCHAR(10) NOT NULL,
        TIPO_ACCIDENTE       VARCHAR(4) NOT NULL,
        LUGAR                VARCHAR(25) NOT NULL,
        EFECTO               VARCHAR(25) NOT NULL,
        CAUSA                VARCHAR(25) NOT NULL,
        DESCRIPCION          VARCHAR(250) NOT NULL,
        DIAS_INCAPACIDAD     DECIMAL(28,8) NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE EMPLEADO_ACCIDENTE
        ADD CONSTRAINT EMPACCPKEMPFECHA PRIMARY KEY NONCLUSTERED (
               EMPLEADO, FECHA)
go
 
 
 CREATE TABLE EMPLEADO_AUDITORIA (
        ATRIBUTO             VARCHAR(40) NOT NULL,
        USUARIO              VARCHAR(25) NOT NULL,
        TIPO_ACCION          VARCHAR(4) NOT NULL,
        FECHA                DATETIME NOT NULL
 )
go
 
 
 ALTER TABLE EMPLEADO_AUDITORIA
        ADD CONSTRAINT EMPLEADOAUDITORPK PRIMARY KEY (ATRIBUTO)
go
 
 
 CREATE TABLE EMPLEADO_AUSENCIA (
        EMPLEADO             VARCHAR(20) NOT NULL,
        FECHA_INICIAL        DATETIME NOT NULL,
        NUMERO_ACCION        int NULL,
        TIPO_AUSENCIA        VARCHAR(4) NOT NULL,
        FECHA_FINAL          DATETIME NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE EMPLEADO_AUSENCIA
        ADD CONSTRAINT EMPAUSPKEMPFECHI PRIMARY KEY NONCLUSTERED (
               EMPLEADO, FECHA_INICIAL)
go
 
 
 CREATE TABLE EMPLEADO_CALENDAR (
        EMPLEADO             VARCHAR(20) NOT NULL,
        FECHA                DATETIME NOT NULL,
        DESCRIPCION          TEXT NOT NULL
 )
go
 
 
 ALTER TABLE EMPLEADO_CALENDAR
        ADD CONSTRAINT EMPCALPKEMPLEADO PRIMARY KEY NONCLUSTERED (
               EMPLEADO, FECHA)
go
 
 
 CREATE TABLE EMPLEADO_CONTRATO (
        EMPLEADO             VARCHAR(20) NOT NULL,
        FECHA_INICIO         DATETIME NOT NULL,
        TIPO_CONTRATO        VARCHAR(4) NOT NULL,
        FECHA_FINALIZACION   DATETIME NOT NULL,
        ESTADO_CONTRATO      VARCHAR(1) NOT NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE EMPLEADO_CONTRATO
        ADD CONSTRAINT XPKEMPLEADO_CONTRA PRIMARY KEY NONCLUSTERED (
               EMPLEADO, FECHA_INICIO)
go


CREATE TABLE EMPLEADO_DOCUMENTO (
         EMPLEADO	   VARCHAR(20)         NOT NULL,
         DOCUMENTO         INT         NOT NULL )
go


ALTER TABLE EMPLEADO_DOCUMENTO
         ADD CONSTRAINT EMPLEADODOCPK PRIMARY KEY NONCLUSTERED
         (EMPLEADO, DOCUMENTO )
go
 
 
 CREATE TABLE EMPLEADO_EVALUACIO (
        EMPLEADO             VARCHAR(20) NOT NULL,
        FECHA_EVALUACION     DATETIME NOT NULL,
        EVALUACION           VARCHAR(8) NOT NULL,
        FECHA_PROXIMA        DATETIME NOT NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE EMPLEADO_EVALUACIO
        ADD CONSTRAINT XPKEMPLEADO_EVALUA PRIMARY KEY NONCLUSTERED (
               EMPLEADO, FECHA_EVALUACION)
go


CREATE TABLE EMPLEADO_JERARQUIA (
         SUPERIOR         VARCHAR(20)         NOT NULL,
         SUBORDINADO      VARCHAR(20)         NOT NULL )
go


ALTER TABLE EMPLEADO_JERARQUIA
         ADD CONSTRAINT EMPJERARQUIAPK PRIMARY KEY NONCLUSTERED
         	(SUPERIOR, SUBORDINADO ) 
go


 CREATE TABLE EMPLEADO_NOTAS (
        EMPLEADO             VARCHAR(20) NOT NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE EMPLEADO_NOTAS
        ADD CONSTRAINT EMPLEADO_NOTASPK PRIMARY KEY NONCLUSTERED (
               EMPLEADO)
go
 
 
 CREATE TABLE EMPLEADO_PARIENTE (
        EMPLEADO             VARCHAR(20) NOT NULL,
        CONSECUTIVO          smallint NOT NULL,
        NOMBRE               VARCHAR(40) NOT NULL,
        FECHA_NACIMIENTO     DATETIME NULL,
        PARENTESCO           VARCHAR(8) NOT NULL,
        LUGAR_TRABAJO        VARCHAR(40) NULL,
        PUESTO               VARCHAR(40) NULL,
        NIVEL_ACADEMICO      VARCHAR(15) NULL,
        LUGAR_ESTUDIO        VARCHAR(40) NULL,
        TELEFONO             VARCHAR(20) NULL,
        NOTAS                TEXT NULL
 )
go
 
 
 ALTER TABLE EMPLEADO_PARIENTE
        ADD CONSTRAINT EMPPARPKEMPLEADO PRIMARY KEY NONCLUSTERED (
               EMPLEADO, CONSECUTIVO)
go
 
 
 CREATE TABLE ESTADO_EMPLEADO (
        ESTADO_EMPLEADO      VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        ACTIVO               VARCHAR(1) NOT NULL,
        PAGO                 VARCHAR(1) NOT NULL,
        TEMPORAL             VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE ESTADO_EMPLEADO
        ADD CONSTRAINT ESTEMPPKESTEMP PRIMARY KEY NONCLUSTERED (
               ESTADO_EMPLEADO)
go
 
 
CREATE TABLE FILTRO_EMPLEADO_REPORTES(
		PROCESO 			VARCHAR(150) NOT NULL,
		EMPLEADO 			VARCHAR(20) NOT NULL
)
go

ALTER TABLE FILTRO_EMPLEADO_REPORTES 
	ADD CONSTRAINT PK_FILTRO_EMPLEADO_REPORTES
		PRIMARY KEY (PROCESO, EMPLEADO)
go
 
 
 CREATE TABLE GLOBALES_RH (
        DEF_RUBRO10_ACCPER   	VARCHAR(60) 	NULL,
        DEF_RUBRO4_ACCPER    	VARCHAR(60) 	NULL,
        DEF_RUBRO2_ACCPER    	VARCHAR(60) 	NULL,
        DEF_RUBRO3_ACCPER    	VARCHAR(60) 	NULL,
        ULTIMA_ACCION        	int 		NOT NULL,
        USA_PLAZA            	VARCHAR(1) 	NOT NULL,
        MOD_PLAZA_POR_EMP    	VARCHAR(1) 	NOT NULL,
        RUBRO1_NOMBRE        	VARCHAR(15) 	NULL,
        RUBRO2_NOMBRE        	VARCHAR(15) 	NULL,
        RUBRO3_NOMBRE        	VARCHAR(15) 	NULL,
        RUBRO4_NOMBRE        	VARCHAR(15) 	NULL,
        RUBRO5_NOMBRE        	VARCHAR(15) 	NULL,
        USA_RUBRO            	VARCHAR(1) 	NOT NULL,
        GENERA_CONTRATO      	VARCHAR(1) 	NOT NULL,
        TIPO_ACCION_CONT     	VARCHAR(4) 	NULL,
        PAQUETE              	VARCHAR(4) 	NULL,
        TIPO_ASIENTO         	VARCHAR(4) 	NULL,
        MOD_APLIC_ASIENTO    	smallint 	NOT NULL,
        TIPO_CONTA_OMISION   	VARCHAR(1) 	NOT NULL,
        CENTRO_COSTO_LIQ     	VARCHAR(25) 	NULL,
        CUENTA_CONTA_LIQ     	VARCHAR(25) 	NULL,
        USA_SALARIO_DIARIO   	VARCHAR(1) 	NOT NULL,
        USA_RUBROS_ACCPER    	VARCHAR(1) 	NOT NULL,
        ESTADO_EMP_CONT      	VARCHAR(4) 	NULL,
        TIPO_SALARIO         	VARCHAR(1) 	NULL,
        ULTIMA_LIQUIDACION   	int 		NOT NULL,
        TIPO_ACCION_LIQ      	VARCHAR(4) 	NULL,
        ESTADO_EMP_LIQ       	VARCHAR(4) 	NULL,
        FORMATO_LIQUIDAC     	VARCHAR(30)	NULL,
        NOTAS_LIQUIDACION    	TEXT 		NULL,
        INTEGRACION_CONTA    	VARCHAR(1) 	NOT NULL,
        DEF_RUBRO1_ACCPER    	VARCHAR(60) 	NULL,
        DEF_RUBRO5_ACCPER    	VARCHAR(60) 	NULL,
        DEF_RUBRO9_ACCPER    	VARCHAR(60) 	NULL,
        DEF_RUBRO8_ACCPER    	VARCHAR(60) 	NULL,
        DEF_RUBRO6_ACCPER    	VARCHAR(60) 	NULL,
        DEF_RUBRO7_ACCPER    	VARCHAR(60) 	NULL,
        USA_NOMBRES_SEP      	VARCHAR(1) 	NULL,
        SUBTDOC_CHK_LIQ      	smallint 	NULL,
        SUBTDOC_TEF_LIQ      	smallint 	NULL,
        E_MAIL_RH            	VARCHAR(40) 	NULL,
        ESTADO_EMP_NUEVO     	VARCHAR(4)  	NULL,
        DIAS_AMPLIA_CONT     	smallint    	NULL,
        TIPO_ACCION_ACUM     	VARCHAR(4)   	NULL,
	TIPO_ACCION_PAGO     	VARCHAR(4)   	NULL,
	TIPO_AUSENCIA_PAGO   	VARCHAR(4)   	NULL,
	TIPO_ACC_ACUM_ADIC   	VARCHAR(4)   	NULL,
	TIPO_ACC_PAG_ADIC    	VARCHAR(4)   	NULL,
        TIPO_AUS_PAG_ADIC    	VARCHAR(4)   	NULL,
        TIPO_ACC_INC_ACUM 	VARCHAR(4) 	NULL,
	TIPO_ACC_INC_DISM 	VARCHAR(4) 	NULL,
	INTEGRACION_CR		VARCHAR(1) 	NULL,
	REQUIERE_PRESUP		VARCHAR(1) 	NULL,
	PAQUETE_CR		VARCHAR(4) 	NULL,
	PRESUPUESTO_CR		VARCHAR(20) 	NULL,
	TIPO_ACC_INC_AJUST 	VARCHAR(4) 	NULL,
	APROB_ADICIONAL 	VARCHAR(1) 	NOT NULL DEFAULT('N'),
	INFO_HISTORICA 		VARCHAR(1)  	NOT NULL DEFAULT('N'),
	USA_CONTROL_SALARIOS 	VARCHAR(1) 	DEFAULT('N') NOT NULL,
	HORAS_INCAP 			VARCHAR(1)  NOT NULL DEFAULT 'N'
 )	
go 
 
 
 CREATE TABLE $$COMPANIA$$.HISTORICO_EMPLEADO
 (
 	NUMERO_HISTORICO     INT 		NOT NULL,
 	EMPLEADO             VARCHAR(20) 	NOT NULL,
 	ULT_FECHA_INGRESO    DATETIME 		NOT NULL,
 	FECHA_SALIDA         DATETIME 		NOT NULL,
 	PUESTO               VARCHAR(8)  	NOT NULL,
 	DEPARTAMENTO         VARCHAR(10) 	NOT NULL,
 	CENTRO_COSTO         VARCHAR(25) 	NOT NULL,
 	NOMINA         	     VARCHAR(4)    	NOT NULL,
 	UBICACION            VARCHAR(8) 	NOT NULL,
 	ANTIGUEDAD	     DECIMAL(28,8) 	NOT NULL,
 	PRIMER_SALARIO       DECIMAL(28,8) 	NOT NULL,
 	ULTIMO_SALARIO       DECIMAL(28,8) 	NOT NULL,
 	JEFE                 VARCHAR(20) 	NULL,
 	RAZON_SALIDA	     VARCHAR(40) 	NOT NULL
 )
 go
 
ALTER TABLE $$COMPANIA$$.HISTORICO_EMPLEADO
        ADD CONSTRAINT XPKHISTORICO_EMPLEADO PRIMARY KEY NONCLUSTERED (NUMERO_HISTORICO)
go
 
 
 
 
 CREATE TABLE HORARIO (
        HORARIO              VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        TOLERA_ENTRADA       smallint NOT NULL,
        TOLERA_SALIDA        smallint NOT NULL,
        REDONDEO_ENTRAD      smallint NOT NULL,
        REDONDEO_SALIDA      smallint NOT NULL,
		HORAS_INCAPACIDAD 	 DECIMAL (28,8) NULL
 )
go
 
 
 ALTER TABLE HORARIO
        ADD CONSTRAINT HORARIOPK PRIMARY KEY NONCLUSTERED (HORARIO)
go
 
 
 CREATE TABLE LIQUIDACION (
        LIQUIDACION          	int 		NOT NULL,
        EMPLEADO             	VARCHAR(20) 	NOT NULL,
        MONEDA               	VARCHAR(4) 	NOT NULL,
        ESTADO_LIQUIDAC      	VARCHAR(1) 	NOT NULL,
        FECHA_INGRESO        	DATETIME 	NOT NULL,
        FECHA_SALIDA         	DATETIME 	NOT NULL,
        CERRAR_CONTRATOS     	VARCHAR(1) 	NOT NULL,
        NUMERO_ACCION        	int 		NOT NULL,
        FORMA_PAGO           	VARCHAR(1) 	NOT NULL,
        CUENTA_BANCO         	VARCHAR(20) 	NULL,
        NUMERO_DOC_PAGO      	decimal(28,0) 	NULL,
        ASIENTO_CONTABLE     	VARCHAR(10) 	NULL,
        FECHA_RETIRO_PAGO    	DATETIME 	NULL,
        USUARIO_ULT_MODI     	VARCHAR(25) 	NOT NULL,
        FECHA_ULT_MODI       	DATETIME 	NOT NULL,
        USUARIO_LIQUIDAC     	VARCHAR(25) 	NULL,
        FECHA_LIQUIDACION    	DATETIME 	NULL,
        OBSERVACIONES        	TEXT 		NULL,
        SUBTIPODOC_PAGO      	smallint 	NULL,
		PRESUPUESTO         	VARCHAR(20)     NULL,
        UNIDAD_OPERATIVA	VARCHAR(4)      NULL,
        NUMERO_APARTADO        	INT         	NULL,
        NUMERO_EJERCIDO        	INT         	NULL,
        CALCULA_PAGO_NOMINA 	VARCHAR(1) 	NOT NULL DEFAULT ('N'),
        NOMINA_CALCULO 		VARCHAR(4) 	NULL,
	NUMERO_NOMINA_CALCULO 	SMALLINT 	NULL
 )
go
 
 
 ALTER TABLE LIQUIDACION
        ADD CONSTRAINT XPKLIQUIDACION PRIMARY KEY (LIQUIDACION)
go
 
 
 CREATE TABLE LIQUIDACION_APORTE (
        LIQUIDACION          int NOT NULL,
        CONCEPTO             VARCHAR(20) NOT NULL,
        MONEDA               VARCHAR(4) NOT NULL,
        FECHA_LIQUIDAC       DATETIME NOT NULL,
        TIPO_CAMBIO          DECIMAL(28,8) NULL,
        TOTAL_CALCULADO      DECIMAL(28,8) NULL,
        TOTAL_MODIFICADO     DECIMAL(28,8) NULL
 )
go
 
 
 ALTER TABLE LIQUIDACION_APORTE
        ADD CONSTRAINT XPKLIQUIDACION_APO PRIMARY KEY (LIQUIDACION, CONCEPTO, MONEDA, FECHA_LIQUIDAC)
go
 
 
 CREATE TABLE LIQUIDACION_CONCEP (
        LIQUIDACION          int NOT NULL,
        LINEA                smallint NOT NULL,
        CONCEPTO             VARCHAR(20) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        TIPO_CONCEPTO        VARCHAR(1) NOT NULL,
        SECUENCIA            smallint NOT NULL,
        CANTIDAD             DECIMAL(28,8) NOT NULL,
        MONTO                DECIMAL(28,8) NOT NULL,
        TOTAL_CALCULADO      DECIMAL(28,8) NOT NULL,
        CENTRO_COSTO         VARCHAR(25) NULL,
        CUENTA_CONTABLE      VARCHAR(25) NULL
 )
go
 
 
 ALTER TABLE LIQUIDACION_CONCEP
        ADD CONSTRAINT XPKLIQUIDACION_CON PRIMARY KEY (LIQUIDACION, 
               LINEA)
go
 
 
 CREATE TABLE LIQUIDACION_CONTRA (
        LIQUIDACION          int NOT NULL,
        EMPLEADO             VARCHAR(20) NOT NULL,
        FECHA_INICIAL        DATETIME NOT NULL,
        FECHA_FINAL_ANT      DATETIME NOT NULL,
        FECHA_FINAL_NUEV     DATETIME NOT NULL
 )
go
 
 
 ALTER TABLE LIQUIDACION_CONTRA
        ADD CONSTRAINT XPKLIQUIDACION_COT PRIMARY KEY (LIQUIDACION, 
               EMPLEADO, FECHA_INICIAL)
go
 
 
 
 CREATE TABLE PLAZA (
        PUESTO               VARCHAR(8) NOT NULL,
        PLAZA                VARCHAR(8) NOT NULL,
        DEPARTAMENTO         VARCHAR(10) NOT NULL,
        COMPARTIDA           VARCHAR(1) NOT NULL,
        TIPO                 VARCHAR(1) NOT NULL,
        ESTADO               VARCHAR(1) NOT NULL,
        CANTIDAD_EMPLEADOS   int NOT NULL,
        FECHA_VACANTE        DATETIME NULL,
        RIGE_DESDE           DATETIME NULL,
        RIGE_HASTA           DATETIME NULL,
        NOTAS                TEXT NULL,
        USUARIO              VARCHAR(25) NOT NULL,
        FECHA_HORA_MOD       DATETIME NOT NULL
 )
go
 
 
 ALTER TABLE PLAZA
        ADD CONSTRAINT XPKPLAZA PRIMARY KEY NONCLUSTERED (PUESTO, 
               PLAZA)
go
 
 
CREATE TABLE PREASIENTO (
	ASIENTO              	VARCHAR(10) 	NOT NULL,
        PAQUETE              	VARCHAR(4) 	NOT NULL,
        TIPO_ASIENTO         	VARCHAR(4) 	NOT NULL,
        FECHA                	DATETIME 	NOT NULL,
        CONTABILIDAD         	VARCHAR(1) 	NOT NULL,
        ORIGEN               	VARCHAR(4) 	NOT NULL,
        CLASE_ASIENTO        	VARCHAR(1) 	NOT NULL,
        TOTAL_DEBITO_LOC     	DECIMAL(28,8) 	NOT NULL,
        TOTAL_DEBITO_DOL     	DECIMAL(28,8) 	NOT NULL,
        TOTAL_CREDITO_LOC    	DECIMAL(28,8) 	NOT NULL,
        TOTAL_CREDITO_DOL    	DECIMAL(28,8) 	NOT NULL,
        ULTIMO_USUARIO       	VARCHAR(25) 	NOT NULL,
        FECHA_ULT_MODIF      	DATETIME 	NOT NULL,
        NOTAS                	TEXT 		NULL,
        TOTAL_CONTROL_LOC    	DECIMAL(28,8) 	NOT NULL,
        TOTAL_CONTROL_DOL    	DECIMAL(28,8) 	NOT NULL,
        USUARIO_CREACION     	VARCHAR(25) 	NOT NULL,
        FECHA_CREACION       	DATETIME 	NOT NULL,
        DEPENDENCIA 		VARCHAR(10) 	NULL,
	PROCESO			VARCHAR(10) 	NOT NULL,
	NOMINA			VARCHAR(4) 	NULL
	
 )
go 
 
ALTER TABLE PREASIENTO 	
	ADD CONSTRAINT XPKPREASIENTO PRIMARY KEY NONCLUSTERED ( ASIENTO )
go 
 
 CREATE TABLE PUESTO (
        PUESTO               VARCHAR(8) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        SALARIO_MINIMO       DECIMAL(28,8) NULL,
        SALARIO_INTERM1      DECIMAL(28,8) NULL,
        SALARIO_INTERM2      DECIMAL(28,8) NULL,
        SALARIO_MAXIMO       DECIMAL(28,8) NULL,
        SALARIO_ACTUAL       DECIMAL(28,8) NULL,
        CONSECUTIVO_PLAZA    VARCHAR(8) NOT NULL,
        NOTAS                TEXT NULL,
        ACTIVO 		     VARCHAR(1) NOT NULL DEFAULT('S')
 )
go
 
 
 ALTER TABLE PUESTO
        ADD CONSTRAINT PUESTOPKPUESTO PRIMARY KEY NONCLUSTERED (
               PUESTO)
go


CREATE TABLE PTO_EXTERNO_PUESTO (
         PUESTO         VARCHAR(8)         NOT NULL,
         CAT_PUESTO_EXTERNO         VARCHAR(12)         NOT NULL,
         PUESTO_EXTERNO         VARCHAR(12)         NOT NULL )
go         

ALTER TABLE PTO_EXTERNO_PUESTO
         ADD CONSTRAINT PTOEXTERNOPUESTOPK PRIMARY KEY NONCLUSTERED
         (PUESTO, CAT_PUESTO_EXTERNO )
go         
 
 
 CREATE TABLE PUESTO_EXTERNO (
          CAT_PUESTO_EXTERNO         VARCHAR(12)         NOT NULL,
          PUESTO_EXTERNO         VARCHAR(12)         NOT NULL,
          DESCRIPCION         VARCHAR(254)         NOT NULL )
go

 
 ALTER TABLE PUESTO_EXTERNO
          ADD CONSTRAINT PUESTOEXTERNOPK PRIMARY KEY NONCLUSTERED
         (CAT_PUESTO_EXTERNO, PUESTO_EXTERNO )
go        
 
 CREATE TABLE PUESTO_FUNCIONES (
        PUESTO               VARCHAR(8) NOT NULL,
        PUESTO_FUNCIONES     TEXT NULL
 )
go
 
 
 ALTER TABLE PUESTO_FUNCIONES
        ADD CONSTRAINT XPKPUESTO_FUNCIONE PRIMARY KEY (PUESTO)
go
 
 
 CREATE TABLE PUESTO_SALARIO (
        PUESTO               VARCHAR(8) NOT NULL,
        FECHA                DATETIME NOT NULL,
        MERCADO_MINIMO       DECIMAL(28,8) NULL,
        MERCADO_CUARTIL1     DECIMAL(28,8) NULL,
        MERCADO_CUARTIL2     DECIMAL(28,8) NULL,
        MERCADO_CUARTIL3     DECIMAL(28,8) NULL,
        MERCADO_MAXIMO       DECIMAL(28,8) NULL,
        SALARIO_COMPANIA     DECIMAL(28,8) NULL,
        MERCADO_PROMEDIO     DECIMAL(28,8) NULL,
        MERCADO_MODA         DECIMAL(28,8) NULL,
        MINIMO_LEY           DECIMAL(28,8) NULL
 )
go
 
 
 ALTER TABLE PUESTO_SALARIO
        ADD CONSTRAINT PTOSALPKPTOFECHA PRIMARY KEY NONCLUSTERED (
               PUESTO, FECHA)
go

CREATE TABLE SAL_DIARIO_INT (
        CONSECUTIVO       int 	        NOT NULL,
        APLICADO          VARCHAR(1)    NOT NULL,
        NOMINA       	  VARCHAR(4)    NOT NULL,
        FECHA_INICIAL     DATETIME      NOT NULL,
        FECHA_FINAL       DATETIME      NOT NULL,
        DIAS_SDIV         DECIMAL(28,8) NOT NULL,
        TIPO_ACCION       VARCHAR(4)    NOT NULL,
        FECHA_ACCION      DATETIME      NOT NULL,
        FECHA_RIGE        DATETIME      NOT NULL,
        SAL_MINIMO_DF     DECIMAL(28,8) NOT NULL,
        SAL_MINIMO_ZONA   DECIMAL(28,8) NOT NULL,
        TOPE_SDI          DECIMAL(28,8) NOT NULL,
        DIAS_LABORADOS	  VARCHAR(20)    NOT NULL,
        CALCULAR_SDIF	  VARCHAR(1)    NOT NULL,
	DIAS_SD		  DECIMAL(28,8) NOT NULL,
	USAR_SDIV_SD	  VARCHAR(4)    NOT NULL,
	RUBRO_SDIV_SD	  int           NULL,
	PORC_FONDO_AHORRO DECIMAL(28,8) NULL,
	TOPE_FONDO_AHORRO DECIMAL(28,8) NULL,
	PORC_DESPENSA	  DECIMAL(28,8) NULL,
	TOPE_DESPENSA	  DECIMAL(28,8) NULL,
	RUBRO1_NOMBRE	  VARCHAR(20)   NULL,
	RUBRO1		  DECIMAL(28,8) NULL,
	RUBRO2_NOMBRE	  VARCHAR(20)   NULL,
	RUBRO2   	  DECIMAL(28,8) NULL,
	RUBRO3_NOMBRE	  VARCHAR(20)   NULL,
	RUBRO3		  DECIMAL(28,8) NULL,
	RUBRO4_NOMBRE	  VARCHAR(20)   NULL,
	RUBRO4		  DECIMAL(28,8) NULL,
	NOTAS		  TEXT          NULL,
	NEXCEDE_SALMINZONA VARCHAR(1)   NOT NULL,
	FECHA_REFERENCIA  VARCHAR(1) 	NOT NULL DEFAULT 'I'
)
go
 
ALTER TABLE SAL_DIARIO_INT
        ADD CONSTRAINT SALDIAINTPK PRIMARY KEY (
               CONSECUTIVO )
go

CREATE TABLE SAL_DIARIO_INT_CON (
        CONSECUTIVO     int 		NOT NULL,
        CONCEPTO	VARCHAR(20) 	NOT NULL,
	MODALIDAD	VARCHAR(1) 	NOT NULL,
	TOPE_EXENCION	DECIMAL(28,8)	NULL,
	SUMA_SDI	VARCHAR(1) 	NULL
)
go
 
ALTER TABLE SAL_DIARIO_INT_CON
        ADD CONSTRAINT SALDIAINTCONPK PRIMARY KEY (
               CONSECUTIVO,CONCEPTO )
go

CREATE TABLE SAL_DIARIO_INT_DET (
        CONSECUTIVO       	int 		NOT NULL,
        CONCEPTO	  	VARCHAR(20) 	NOT NULL,
	EMPLEADO		VARCHAR(20) 	NOT NULL,
	ACUMULADO		DECIMAL(28,8) 	NULL,
	PROPORCION_DIARIA	DECIMAL(28,8)	NULL
)
go

 
ALTER TABLE SAL_DIARIO_INT_DET
        ADD CONSTRAINT SALDIAINTDETPK PRIMARY KEY (
               CONSECUTIVO,CONCEPTO, EMPLEADO )
go               

CREATE TABLE SAL_DIARIO_INT_EMP (
        CONSECUTIVO       	int           NOT NULL,
        EMPLEADO	  	VARCHAR(20)   NOT NULL,
	NUMERO_ACCION		int           NULL,
	SALARIO_REFERENCIA	DECIMAL(28,8) NOT NULL,
	SDI_ANTERIOR		DECIMAL(28,8) NOT NULL,
	DIAS_ANTIGUEDAD		DECIMAL(28,8) NOT NULL,
	DIAS_VACACIONES		DECIMAL(28,8) NOT NULL,
	DIAS_LABORADOS		DECIMAL(28,8) NOT NULL,
	DIAS_AGUINALDO		DECIMAL(28,8) NOT NULL,
	PORCENTAJE_PRIMA	DECIMAL(28,8) NOT NULL,
	FACTOR			DECIMAL(28,8) NOT NULL,
	SDI_FIJO		DECIMAL(28,8) NOT NULL,
	SDI_VARIABLE		DECIMAL(28,8) NOT NULL,
	SDI_NUEVO		DECIMAL(28,8) NOT NULL,
	MARCA_CALCULO           VARCHAR(1)    NOT NULL
)
go
 
ALTER TABLE SAL_DIARIO_INT_EMP
        ADD CONSTRAINT SALDIAINTEMPPK PRIMARY KEY (
               CONSECUTIVO,EMPLEADO )
go   
 
CREATE TABLE SOLICITUD_RH (
         SOLICITUD_RH         	INT         NOT NULL,
         TIPO_SOLICITUD_RH      VARCHAR(4)  NOT NULL,
         EMPLEADO         	VARCHAR(20) NOT NULL,
         ESTADO         	VARCHAR(1)  NOT NULL,
         FECHA_RIGE         	DATETIME    NULL,
         FECHA_VENCE         	DATETIME    NULL,
         DIAS         		REAL        NULL,
         NUMERO_ACCION         	INT         NULL,
         GENERADA_POR           VARCHAR(20) NOT NULL,
         FECHA_HORA         	DATETIME    NOT NULL,
         FECHA_ESTADO         	DATETIME    NOT NULL,
         OBSERVACIONES         	TEXT        NULL )
go


ALTER TABLE SOLICITUD_RH
         ADD CONSTRAINT SOLRHPK PRIMARY KEY NONCLUSTERED
         	(SOLICITUD_RH )
go


CREATE TABLE SOLICITUD_RH_AUDIT (
         SOLICITUD_RH    INT          NOT NULL,
         USUARIO         VARCHAR(25)  NOT NULL,
         NIVEL           SMALLINT     NOT NULL,
         ESTADO          VARCHAR(1)   NOT NULL,
         FECHA_ESTADO    DATETIME     NOT NULL,
         OBSERVACIONES   TEXT         NULL )
go


ALTER TABLE SOLICITUD_RH_AUDIT
         ADD CONSTRAINT SOLRHAUDITPK PRIMARY KEY NONCLUSTERED
         (SOLICITUD_RH, USUARIO )
go    


CREATE TABLE SOLICITUD_RH_DOC (
         SOLICITUD_RH      INT         NOT NULL,
         DOCUMENTO         INT         NOT NULL )
go         


ALTER TABLE SOLICITUD_RH_DOC
         ADD CONSTRAINT SOLICITUDRHDOCPK PRIMARY KEY NONCLUSTERED
         (SOLICITUD_RH, DOCUMENTO )
go  

CREATE TABLE SOLICITUD_RH_NOTIF (
         SOLICITUD_RH  	INT         NOT NULL,
         CONSECUTIVO   	INT         NOT NULL,
         EMPLEADO      	VARCHAR(20) NOT NULL,
         ESTADO        	VARCHAR(1)  NOT NULL,
         FECHA_HORA    	DATETIME    NULL )
go


ALTER TABLE SOLICITUD_RH_NOTIF
         ADD CONSTRAINT SOLICITUDRHNOTIFPK PRIMARY KEY NONCLUSTERED
         	(SOLICITUD_RH, CONSECUTIVO )
go         	

         
CREATE TABLE TIP_SOL_RH_USUARIO (
         TIPO_SOLICITUD_RH   VARCHAR(4)		NOT NULL,
         USUARIO             VARCHAR(25)	NOT NULL,
         PRIVILEGIO          VARCHAR(1)         NOT NULL )
go         

ALTER TABLE TIP_SOL_RH_USUARIO
         ADD CONSTRAINT TIPSOLRHUSUARPK PRIMARY KEY NONCLUSTERED
         (TIPO_SOLICITUD_RH, USUARIO )
go         
          
         
CREATE TABLE TIPO_ACADEMICO (
         TIPO_ACADEMICO      VARCHAR(4)          NOT NULL,
         DESCRIPCION         VARCHAR(40)         NOT NULL )
go

ALTER TABLE TIPO_ACADEMICO
         ADD CONSTRAINT TIPO_ACADEMICOPK PRIMARY KEY NONCLUSTERED
         (TIPO_ACADEMICO )
go

  
 CREATE TABLE TIPO_ACCIDENTE (
        TIPO_ACCIDENTE       VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL
 )
go
 
 
 ALTER TABLE TIPO_ACCIDENTE
        ADD CONSTRAINT XPKTIPO_ACCIDENTE PRIMARY KEY NONCLUSTERED (
               TIPO_ACCIDENTE)
go
 
 
 CREATE TABLE TIPO_ACCION (
        TIPO_ACCION          		VARCHAR(4) 	NOT NULL,
        DESCRIPCION          		VARCHAR(40) 	NOT NULL,
        FIJA                 		VARCHAR(1) 	NULL,
        TIPO_ACCION_PREDEF   		smallint 	NOT NULL,
        TEXTO_PREDEF         		TEXT 		NULL,
        RESTAURA_ESTADOEMP   		VARCHAR(1) 	NOT NULL,
        CODIF_APLIC_RUBROS   		VARCHAR(10) 	NULL,
        ESTADO_EMPLEADO      		VARCHAR(4) 	NULL,
        MOD_ESTADO_EMP       		VARCHAR(1) 	NULL,
        REPORTE				VARCHAR(100) 	NULL,
        CODIF_TEXTOPREDEF_RUBROS 	VARCHAR(255) 	NULL
 )
go
 
 
 ALTER TABLE TIPO_ACCION
        ADD CONSTRAINT TACCPKTACC PRIMARY KEY NONCLUSTERED (
               TIPO_ACCION)
go


CREATE TABLE TIPO_ACCION_CONCEP (
         TIPO_ACCION   VARCHAR(4)       NOT NULL,
         SECUENCIA     SMALLINT         NOT NULL,
         CONCEPTO      VARCHAR(20)       NOT NULL,
         NOMINA        VARCHAR(4)       NULL )
go        

ALTER TABLE TIPO_ACCION_CONCEP
         ADD CONSTRAINT XPKTIPO_ACCION_CON PRIMARY KEY NONCLUSTERED
         (TIPO_ACCION, SECUENCIA )
go         


CREATE TABLE TIPO_ACCION_USUARIO(
         TIPO_ACCION	VARCHAR(4)	NOT NULL,
         USUARIO	VARCHAR(25)	NOT NULL,
         PRIVILEGIO	VARCHAR(1)	NOT NULL,
         CREAR 		VARCHAR(1)	NOT NULL DEFAULT 'N',
	 APROBAR 	VARCHAR(1)	NOT NULL DEFAULT 'N',
	 DESAPROBAR 	VARCHAR(1)	NOT NULL DEFAULT 'N',
	 APLICAR 	VARCHAR(1)	NOT NULL DEFAULT 'N',
	 DESAPLICAR 	VARCHAR(1)	NOT NULL DEFAULT 'N',
	 ANULAR 	VARCHAR(1)	NOT NULL DEFAULT 'N',
	 TOTAL 		VARCHAR(1)	NOT NULL DEFAULT 'N')
go


ALTER TABLE TIPO_ACCION_USUARIO
         ADD CONSTRAINT TIPOACCPERUSUPK PRIMARY KEY NONCLUSTERED
         (TIPO_ACCION, USUARIO )
go         


 CREATE TABLE TIPO_AUSENCIA (
        TIPO_AUSENCIA        VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL,
        JUSTIFICADA          VARCHAR(1) NOT NULL,
        PAGO                 VARCHAR(1) NOT NULL
 )
go
 
 
 ALTER TABLE TIPO_AUSENCIA
        ADD CONSTRAINT TAUSPKTAUS PRIMARY KEY NONCLUSTERED (
               TIPO_AUSENCIA)
go
 
 
 CREATE TABLE TIPO_CONTRATO (
        TIPO_CONTRATO        VARCHAR(4) NOT NULL,
        DESCRIPCION          VARCHAR(40) NOT NULL
 )
go
 
 
 ALTER TABLE TIPO_CONTRATO
        ADD CONSTRAINT XPKTIPO_CONTRATO PRIMARY KEY NONCLUSTERED (
               TIPO_CONTRATO)
go
 

CREATE TABLE TIPO_SOLI_RH_NOTIF (
         TIPO_SOLICITUD_RH      VARCHAR(4)         NOT NULL,
         EMPLEADO         	VARCHAR(20)        NOT NULL )
go         


ALTER TABLE TIPO_SOLI_RH_NOTIF
         ADD CONSTRAINT TIPOSOLIRHNOTIFPK PRIMARY KEY NONCLUSTERED
         	(TIPO_SOLICITUD_RH, EMPLEADO )
go   


CREATE TABLE TIPO_SOLICITUD_RH (
         TIPO_SOLICITUD_RH   VARCHAR(4)       NOT NULL,
         DESCRIPCION         VARCHAR(50)      NOT NULL,
         TIPO_ACCION         VARCHAR(4)       NULL,
         ESTADO_EMPLEADO     VARCHAR(4)       NULL,
         TIPO_AUSENCIA       VARCHAR(4)       NULL,
         APRUEBA_SUPERIOR    VARCHAR(1)       NOT NULL,
         NIVEL_APROBACION    SMALLINT         NULL,
         DIAS_PARA_ESCALAR   SMALLINT         NULL,
         DIAS_PARA_VENCER    SMALLINT         NULL,
         MULTI_SUPERIORES    VARCHAR(1)       NULL,
         APROB_FINAL_RH      VARCHAR(1)       NOT NULL,
         OBSERVACIONES       TEXT             NULL,
         ACCESO_DIRECTO      VARCHAR(1)       NULL,
       	 DESC_ACCESO         VARCHAR(15)      NULL)
go


ALTER TABLE TIPO_SOLICITUD_RH
         ADD CONSTRAINT TIPOSOLICITUDRHPK PRIMARY KEY NONCLUSTERED
         	(TIPO_SOLICITUD_RH )
go

 

 CREATE TABLE VACACION (
        SECUENCIA            smallint NOT NULL,
        ANTIGUEDAD           DECIMAL(28,8) NOT NULL,
        CANTIDAD             DECIMAL(28,8) NOT NULL
 )
go
 
 
 ALTER TABLE VACACION
        ADD CONSTRAINT XPKVACACION PRIMARY KEY (SECUENCIA)
go
 
 
 CREATE TABLE BENEFICIOS_ANTIGUE (
        NOMINA               VARCHAR(4) NOT NULL,
        DIAS_ANTIGUEDAD      DECIMAL(28,8) NOT NULL,
        DIAS_VACACIONES      DECIMAL(28,8) NOT NULL,
        DIAS_AGUINALDO       DECIMAL(28,8) NOT NULL,
	PORC_PRIMA_VAC       DECIMAL(28,8) NOT NULL 
 )
go
 
 
 ALTER TABLE BENEFICIOS_ANTIGUE
        ADD CONSTRAINT XPKBENEFICIOS_ANTIGUE PRIMARY KEY (
                NOMINA,DIAS_ANTIGUEDAD)
go


 