
 
 ALTER TABLE ACCION_VERSION
        ADD CONSTRAINT ACCION_VERS_ACCION
               FOREIGN KEY (ACCION)
                              REFERENCES ACCION
                              ON DELETE CASCADE
go
 
 
 
ALTER TABLE APLICA_ESQUEMA
         ADD CONSTRAINT XFKSENTENCIAAPLICAESQ
                FOREIGN KEY  ( IDSQL )
                	REFERENCES ERPADMIN.SENTENCIAS_SQL( IDSQL )
                        	ON DELETE CASCADE
go                        	
 

ALTER TABLE APLICA_ESQUEMA
         ADD CONSTRAINT XFKUSUAPLICAPLICAESQUEM
                FOREIGN KEY  ( USUARIO_APLICACION )
                	REFERENCES ERPADMIN.USUARIO( USUARIO )
go 

ALTER TABLE AUTENTICA_CATALOGO
         ADD CONSTRAINT AUTCAAU
         	FOREIGN KEY  ( CODIGO )
         		REFERENCES AUTENTICACION ( CODIGO )
			ON DELETE CASCADE
go	
	

ALTER TABLE AUTENTICA_CATALOGO
         ADD CONSTRAINT AUTCATCO
         	FOREIGN KEY  ( CONJUNTO )
         		REFERENCES CONJUNTO ( CONJUNTO )
			ON DELETE CASCADE
go	
	

 ALTER TABLE AUTENTICACION
         ADD CONSTRAINT AUTENTUS
         	FOREIGN KEY  ( USUARIO_EXACTUS )
         		REFERENCES USUARIO ( USUARIO )
         		ON DELETE CASCADE
go

ALTER TABLE CARPETA_FAVORITOS  
	ADD  CONSTRAINT CARFAVUSUARIO 
		FOREIGN KEY(USUARIO)
			REFERENCES USUARIO (USUARIO)
go
 
 ALTER TABLE CONJUNTO
        ADD CONSTRAINT USUAULTMOD
               FOREIGN KEY (USUARIO_ULT_MOD)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE CONSOLIDACION_CG
        ADD CONSTRAINT USUACONSOLID
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go

 
ALTER TABLE DD_MODULO 
	ADD CONSTRAINT FKDD_MODULO
		FOREIGN KEY(AREA) 
			REFERENCES ERPADMIN.DD_AREA(AREA)
go

ALTER TABLE DD_MODULO_TABLA 
	ADD CONSTRAINT FKDD_MODULO_TABLA
		FOREIGN KEY(MODULO) 
			REFERENCES ERPADMIN.DD_MODULO(MODULO)
go

ALTER TABLE DD_MODULO_TABLA 
	ADD CONSTRAINT FKDD_TABLA
		FOREIGN KEY(TABLA) 
			REFERENCES ERPADMIN.DD_TABLA(TABLA)
go

ALTER TABLE DD_PROPIETARIO_TABLA 
	ADD CONSTRAINT FKDD_PROPIETARIO_TABLA
		FOREIGN KEY(TABLA) 
			REFERENCES ERPADMIN.DD_TABLA (TABLA)
go  


ALTER TABLE FAVORITOS 
 	ADD CONSTRAINT FK_FAVORITOS_ACCION 
 		FOREIGN KEY (ACCION) 
 			REFERENCES ERPADMIN.ACCION
go
 
 ALTER TABLE FAVORITOS 
 	ADD CONSTRAINT FK_FAVORITOS_USUARIO 
 		FOREIGN KEY (Usuario) 
 			REFERENCES ERPADMIN.USUARIO
go 			
 
 
 
 ALTER TABLE HOOK_DETALLE
          ADD CONSTRAINT HOOK_DETALLE_RIF
                 FOREIGN KEY (HOOK)
                                REFERENCES HOOK_PERSONALIZ
go

ALTER TABLE LOCKS
        ADD CONSTRAINT LOCKUSR
               FOREIGN KEY (USUARIO)
                              REFERENCES USUARIO
go                              



ALTER TABLE MAPEO_DET_CARGA  
		  ADD  CONSTRAINT FK_MAPEO_CARGA FOREIGN KEY(MAPEO)
				REFERENCES MAPEO_CARGA (MAPEO)
go				

 
 ALTER TABLE MEMBRESIA
        ADD CONSTRAINT USU_MEM
               FOREIGN KEY (GRUPO)
                              REFERENCES ERPADMIN.USUARIO
                              ON DELETE CASCADE
go


 ALTER TABLE MEMBRESIA
        ADD CONSTRAINT MEM_USU
               FOREIGN KEY (USUARIO)
                              REFERENCES USUARIO
go 
 
 ALTER TABLE MODULO_INSTALADO
        ADD CONSTRAINT AC_MI
               FOREIGN KEY (ACCION)
                              REFERENCES ACCION
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE MODULO_INSTALADO
        ADD CONSTRAINT CON_MI
               FOREIGN KEY (CONJUNTO)
                              REFERENCES CONJUNTO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE OPCION_CONFIG
        ADD CONSTRAINT AC_OPMOD
               FOREIGN KEY (MODULO)
                              REFERENCES ACCION
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE OPCION_CONFIG
        ADD CONSTRAINT USU_OPUL
               FOREIGN KEY (ULTIMO_USUARIO)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 ALTER TABLE OPCION_CONFIG
        ADD CONSTRAINT USU_OPCR
               FOREIGN KEY (USUARIO_CREADOR)
                              REFERENCES ERPADMIN.USUARIO
go
 
 
 
 ALTER TABLE OPCION_CONFIG
        ADD CONSTRAINT AC_OPCON
               FOREIGN KEY (ACCION)
                              REFERENCES ACCION
go


 ALTER TABLE OPCION_CONFIG
        ADD CONSTRAINT AC_OPMANT
               FOREIGN KEY (MANTENIMIENTO)
                              REFERENCES ACCION
go                  
 
 ALTER TABLE PARENTESCO
        ADD CONSTRAINT PA_AC
               FOREIGN KEY (ACCION)
                              REFERENCES ACCION
                              ON DELETE CASCADE
go



 ALTER TABLE PARENTESCO
        ADD CONSTRAINT AC_PA
               FOREIGN KEY (PADRE)
                              REFERENCES ACCION
go
 
 
 
 ALTER TABLE PRIVILEGIO_EX
        ADD CONSTRAINT CO_PRI
               FOREIGN KEY (CONJUNTO)
                              REFERENCES CONJUNTO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE PRIVILEGIO_EX
        ADD CONSTRAINT USU_PRI
               FOREIGN KEY (USUARIO)
                              REFERENCES ERPADMIN.USUARIO
                              ON DELETE CASCADE
go
 
 
 ALTER TABLE PRIVILEGIO_EX
        ADD CONSTRAINT AC_PRI
               FOREIGN KEY (ACCION)
                              REFERENCES ACCION
                              ON DELETE CASCADE
go
 

ALTER TABLE REPORTE_DETALLE
         ADD CONSTRAINT REPORTE_DETALLE_RIF
                FOREIGN KEY (ACCION)
                               REFERENCES REPORTE_PERSONALIZ
go

ALTER TABLE REPORTE_USUARIO
         ADD CONSTRAINT REPORTE_USUARIO_RIF
                FOREIGN KEY (accion, reporte)
                               REFERENCES REPORTE_DETALLE
				ON DELETE CASCADE
go				

ALTER TABLE REPORTE_USUARIO
         ADD CONSTRAINT USUARIO_REPORTE_RIF
                FOREIGN KEY (USUARIO)
                               REFERENCES USUARIO
				ON DELETE CASCADE
go				


ALTER TABLE SENTENCIAS_SQL
         ADD CONSTRAINT XFKUSUACREACSENTENCSQL
                FOREIGN KEY  ( USUARIO_CREACION )
                	REFERENCES ERPADMIN.USUARIO( USUARIO )
go                	
                	
ALTER TABLE SENTENCIAS_SQL
         ADD CONSTRAINT XFKUSUAMODIFISENTENCSQL
                FOREIGN KEY  ( USUARIO_MODIFICACION )
                	REFERENCES ERPADMIN.USUARIO( USUARIO )
go