
IF NOT exists (SELECT * FROM systypes WHERE name = N'RowPointerType')
EXECUTE sp_addtype N'RowPointerType', N'uniqueidentifier', N'null'
go

 
 CREATE TABLE ACCION (
        ACCION               int NOT NULL,
        NOMBREACCION         VARCHAR(40) NOT NULL,
        DESCRIPCION          VARCHAR(100) NULL,
        NOMBRECONSTANTE      VARCHAR(18) NOT NULL,
        ESMODULO             VARCHAR(1) NOT NULL,
        ESESTANDAR           VARCHAR(1) NOT NULL,
        TIPO                 VARCHAR(1) NOT NULL,
	SUBTIPO              VARCHAR(1) NOT NULL,
	TABLA                VARCHAR(30) NULL,	
        INVOCACION           VARCHAR(1024) NULL
 )
go
 
 
 ALTER TABLE ACCION
        ADD CONSTRAINT XPKACCION PRIMARY KEY NONCLUSTERED (ACCION)
go
 
 
 CREATE TABLE ACCION_VERSION (
        ACCION               int 		NOT NULL,
        ULT_VERSION          VARCHAR(11) 	DEFAULT '6.00.00'	NULL,
        USUARIO              VARCHAR(25) 	NOT NULL,
        FCH_HORA_VERSION     DATETIME 		NOT NULL,
        ULT_VERSIONERP 	     VARCHAR(12)	DEFAULT '6.0.0.0' 	NOT NULL
 )
go
 
 
 ALTER TABLE ACCION_VERSION
        ADD CONSTRAINT XPKACCION_VERSION PRIMARY KEY (ACCION)
go
 

CREATE TABLE APLICA_ESQUEMA(
                IDAPLICA_ESQUEMA    	int    IDENTITY(1,1)  	NOT NULL,
                IDSQL         		int    			NOT NULL,
                VERSION                 INT           		NOT NULL,
                USUARIO_APLICACION     	VARCHAR(25)    		NOT NULL,
                FECHA_APLICACION       	DATETIME       		NOT NULL,
                RESULTADO_APLICACION    TEXT                	NOT NULL,
                NOMBRE_ESQUEMA        	VARCHAR(10)          	NOT NULL
)
go


ALTER TABLE APLICA_ESQUEMA
         ADD CONSTRAINT XPKAPLICA_ESQUEMA PRIMARY KEY (IDAPLICA_ESQUEMA)
go         

 
CREATE TABLE ARCHIVO_APLICADO (
        COMPANIA          VARCHAR(10)	NOT NULL,
        ARCHIVO           VARCHAR(20)	NOT NULL,
        ESTADO            VARCHAR(1) 	NOT NULL,
        APLICADO_POR      VARCHAR(10)    NOT NULL,
        FECHA_HORA_APLIC  DATETIME      NULL,
        CONTENIDO         TEXT        	NULL,
        TIPO              VARCHAR(1)    NULL   
 )
go
 
 
 CREATE  INDEX ARCAPLICIAARCH ON ARCHIVO_APLICADO (
          COMPANIA,ARCHIVO )  
go

 
CREATE TABLE AUTENTICA_CATALOGO (
         CODIGO          	VARCHAR(40)         NOT NULL,
         CATALOGO         	VARCHAR(1)          NOT NULL,
         CONJUNTO         	VARCHAR(10)         NOT NULL,
         CODIGO_CATALOGO  	VARCHAR(20)         NOT NULL,
         ACTIVO           	VARCHAR(1)          NOT NULL,
         USUARIO_PRIVILEGIOS 	VARCHAR(25) 	    NULL)
go


ALTER TABLE AUTENTICA_CATALOGO
         ADD CONSTRAINT AUTENCATALOGOPK PRIMARY KEY NONCLUSTERED
         (CODIGO, CATALOGO, CONJUNTO )         
go


CREATE TABLE AUTENTICACION (
         CODIGO         	VARCHAR(40)         NOT NULL,
         USUARIO_EXACTUS        VARCHAR(25)         NULL,
         USUARIO_WINDOWS        VARCHAR(254)        NULL,
         CLAVE         		VARCHAR(254)        NULL )
go


ALTER TABLE AUTENTICACION
         ADD CONSTRAINT AUTENTICACIONPK PRIMARY KEY NONCLUSTERED
         (CODIGO )
go         

CREATE TABLE BITACORA_PROCESO (
       LLAVE_BIT_PROCESO    INT 		NOT NULL,
       USUARIO              VARCHAR(25)  	NOT NULL,
       COMPANIA             VARCHAR(10)  	NOT NULL,
       FECHA                DATETIME 	 	NOT NULL,
       ESTACION             VARCHAR(270) 	NOT NULL,
       PROCESO              VARCHAR(50)  	NOT NULL,
       TIPO                 VARCHAR(15)  	NOT NULL,
       DESCRIPCION          VARCHAR(512) 	NOT NULL
)
go


ALTER TABLE BITACORA_PROCESO
    ADD CONSTRAINT XPKBITACORA_PROCES   
    	PRIMARY KEY NONCLUSTERED (LLAVE_BIT_PROCESO)
go    


 
CREATE TABLE BITACORA_MENSAJES (
	COMPANIA	VARCHAR(10)    NOT NULL,
	ARCHIVO		VARCHAR(20)    NOT NULL,
	TIPO         	VARCHAR(1)     NOT NULL,
        FECHA_HORA      DATETIME       NOT NULL,
        NUM_MENSAJE	INT	       NULL,
        TEXTO_MENSAJE   VARCHAR(254)   NULL )

go
 
 
CREATE  INDEX BITMENCIAARCH ON BITACORA_MENSAJES (
          			COMPANIA,
          			ARCHIVO )
go

CREATE TABLE CARGA_MODIF
(
		CARGA_MODIF 	VARCHAR(48) NOT NULL,
		GUID_DOCUMENTO 	VARCHAR(48) NOT NULL
)
go

ALTER TABLE CARGA_MODIF
          ADD CONSTRAINT PK_CARGA_MODIF
          	PRIMARY KEY ( CARGA_MODIF, GUID_DOCUMENTO )
go	

CREATE TABLE CARPETA_FAVORITOS(
      ID_CARPETA  INT               NOT NULL,
      USUARIO     VARCHAR(25)       NOT NULL,
      POSICION    INT               NULL,
      PADRE       INT               NULL,
      DESCRIPCION VARCHAR(40)       NOT NULL
) 
go


ALTER TABLE CARPETA_FAVORITOS
	ADD CONSTRAINT CARPETAFAVORITOSPK PRIMARY KEY NONCLUSTERED 
		(ID_CARPETA, USUARIO)
go


CREATE TABLE CONFIG_SEGURIDAD (
       VARIABLE             VARCHAR(60) NOT NULL,
       VALOR                TEXT 	NOT NULL
)
go

ALTER TABLE CONFIG_SEGURIDAD
       ADD CONSTRAINT XPKCONFIG_SEGURIDA   
       	PRIMARY KEY NONCLUSTERED (VARIABLE)
go       	
        
 
 CREATE TABLE CONFIGURACION (
        VARIABLE             VARCHAR(100) 	NOT NULL,
        VALOR                TEXT 		NOT NULL
 )
go
 
 
 ALTER TABLE CONFIGURACION
        ADD CONSTRAINT XPKCONFIGURACION PRIMARY KEY (VARIABLE)
go
 
 
 CREATE TABLE CONJUNTO (
        CONJUNTO             	VARCHAR(10) 	NOT NULL,
        NOMBRE               	VARCHAR(100) 	NOT NULL,
        DIREC1               	VARCHAR(30) 	NOT NULL,
        DIREC2               	VARCHAR(30) 	NOT NULL,
        TELEFONO             	VARCHAR(30) 	NOT NULL,
        LOGO                 	VARCHAR(100) 	NULL,
        DOBLE_MONEDA         	VARCHAR(1) 	NOT NULL,
        DOBLE_CONTABILIDAD   	VARCHAR(1) 	NOT NULL,
        INVENTARIO_DOLAR     	VARCHAR(1) 	NOT NULL,
        USA_LOTES            	VARCHAR(1) 	NOT NULL,
        USAR_CENTROS_COSTO   	VARCHAR(1) 	NOT NULL,
        CONSOLIDA            	VARCHAR(1) 	NOT NULL,
        CONSOLIDADORA        	VARCHAR(10) 	NULL,
        BD_CIA_CONSOLIDAD    	VARCHAR(1) 	NULL,
        CONTA_A_CONSOLID     	SMALLINT 	NULL,
        MISMO_CUADRO_CTB     	VARCHAR(1) 	NULL,
        USUARIO_ULT_MOD      	VARCHAR(25) 	NOT NULL,
        FCH_HORA_ULT_MOD     	DATETIME NOT 	NULL,
        NOTAS                	TEXT 		NULL,
        USA_UNIDADES         	VARCHAR(1)  	NOT NULL,
        UNIDAD_OMISION       	VARCHAR(15) 	NULL,
        MONEDA_CONSOLIDA     	VARCHAR(1)  	NULL,
        VERSION_BD           	VARCHAR(8)  	NULL,
        USUARIO_MODIF_BD     	VARCHAR(40) 	NULL,
        FCH_HORA_MODIF_BD    	DATETIME    	NULL,
        VERSION_INSTALAC     	VARCHAR(8)  	NULL,
        NIT                  	VARCHAR(20) 	NULL,
        PAIS         	     	VARCHAR(20) 	NULL,
       	GLN 	  	     		VARCHAR(13) 	NULL,
		UBICACION 	     		VARCHAR(10) 	NULL,
		IDIOMA 	  	     		VARCHAR(10) 	NULL,
		USA_SUCURSAL         	VARCHAR(1)	DEFAULT ('N')  	NULL,
		MASCARA_SUCURSAL     	VARCHAR(10) 	DEFAULT ('')	NULL,
		DIRECCION_WEB1       	VARCHAR(50) 	NULL,
		DIRECCION_WEB2       	VARCHAR(50) 	NULL,
		NOMBRE_WEB1          	VARCHAR(30) 	NULL,
		NOMBRE_WEB2          	VARCHAR(30) 	NULL,
		DIRECCION_PAG_WEB    	VARCHAR(50) 	NULL,
		EMAIL_DOC_ELECTRONICO 	VARCHAR(249)	NULL,
		PAIS_DIVISION	     	VARCHAR(4)  	NULL,
		DIVISION_GEOGRAFICA1 	VARCHAR(12) 	NULL,
		DIVISION_GEOGRAFICA2 	VARCHAR(12) 	NULL,
		LOGO_CIA 	     		VARBINARY(MAX)	NULL,
		NUMERO_REGISTRO      	VARCHAR(25) 	NULL,
		DIREC3 					VARCHAR(30) 	NULL,
		COD_POSTAL 				VARCHAR(10) 	NULL,
		DIVISION_GEOGRAFICA3 	VARCHAR(12) NULL,
		DIVISION_GEOGRAFICA4 	VARCHAR(12) NULL,
		REGIMEN_FISCAL 			VARCHAR(3) NULL
)
go
 
 
 ALTER TABLE CONJUNTO
        ADD CONSTRAINT XPKCONJUNTO PRIMARY KEY (CONJUNTO)
go
 
 
 CREATE TABLE CONSOLIDACION_CG (
        CONSOLIDADORA        VARCHAR(10) 	NOT NULL,
        CONSOLIDADA          VARCHAR(10) 	NOT NULL,
        FECHA_CONSOLIDAC     DATETIME 		NOT NULL,
        CONTABILIDAD         VARCHAR(1) 	NOT NULL,
        FECHA_HORA           DATETIME 		NOT NULL,
        USUARIO              VARCHAR(25) 	NOT NULL,
        ASIENTO              VARCHAR(10) 	NOT NULL
 )
go
 
 
 ALTER TABLE CONSOLIDACION_CG
        ADD CONSTRAINT XPKCONSOLIDACION_C PRIMARY KEY (CONSOLIDADORA, 
               CONSOLIDADA, FECHA_CONSOLIDAC, CONTABILIDAD, 
               FECHA_HORA)
go


 
CREATE TABLE DD_AREA
(
	AREA 		VARCHAR(4) 	NOT NULL,
	DESCRIPCION 	VARCHAR(40) 	NOT NULL
)
go

ALTER TABLE DD_AREA
        ADD CONSTRAINT PKDD_AREA PRIMARY KEY (AREA)
go


CREATE TABLE DD_CARGA_CONSTR (
	NOMBRE_TABLA VARCHAR(30) 	NOT NULL, 
	NOMBRE_COLUM VARCHAR(30) 	NOT NULL, 
	VALOR_CONSTR VARCHAR(10) 	NOT NULL, 
	DEFINICION_CONSTR VARCHAR(120) 	NOT NULL
)
go

ALTER TABLE DD_CARGA_CONSTR
        ADD CONSTRAINT XPKDD_CARGA_CONSTR PRIMARY KEY (NOMBRE_TABLA,NOMBRE_COLUM,VALOR_CONSTR,DEFINICION_CONSTR)
go        

CREATE TABLE DD_CARGA_DICCIO(
	NOMBRE_TABLA 		VARCHAR(30)	NOT NULL, 
	PROPIET_TABLA 		VARCHAR(50)	NOT NULL, 
	NOMBRE_COLUM 		VARCHAR(30) 	NOT NULL,
	TIPO_COLUM 		VARCHAR(20)	NOT NULL,
	TAMANO_COLUM 		VARCHAR(4)	NULL, 
	NULIDAD 		VARCHAR(1)	NOT NULL, 
	ES_PK 			VARCHAR(1) 	NOT NULL, 
	ES_FK 			VARCHAR(1) 	NOT NULL, 
	COMENTARIO 		VARCHAR(1024)	NULL, 
	VALOR_DEFAULT 		VARCHAR(30)	NULL, 
	CONSTR_COLUM 		VARCHAR(50)	NULL,  
	DOM_EDIT_ENPROCMAS 	VARCHAR(10) 	NOT NULL, 
	DOM_EDIT_PRIMVEZ 	VARCHAR(10) 	NOT NULL, 
	DOM_MODO_CASE 		VARCHAR(10) 	NOT NULL, 
	DOM_TIPO_MASCARA 	VARCHAR(30) 	NOT NULL, 
	DOM_ES_AUTOCALC 	VARCHAR(10) 	NOT NULL,
	DOM_USO_MODVISUAL 	VARCHAR(10) 	NOT NULL, 
	DOM_SOLO_LECT 		VARCHAR(10) 	NOT NULL, 
	DOM_ES_REQUER 		VARCHAR(10) 	NOT NULL, 
	DOM_MOSTRAR_COMO 	VARCHAR(10) 	NOT NULL,
	DOM_TIPO_CONSEC 	VARCHAR(30) 	NOT NULL, 
	DOM_FORMATOJUSTIF 	VARCHAR(10) 	NOT NULL,
	DOM_VALORETIQUETA 	VARCHAR(50) 	NOT NULL, 
	DOM_MOSTRARENF1 	VARCHAR(10) 	NOT NULL, 
	EDIT_ENPROCMAS 		VARCHAR(10) 	NOT NULL, 
	EDIT_PRIMVEZ 		VARCHAR(10) 	NOT NULL, 
	MODO_CASE 		VARCHAR(10) 	NOT NULL, 
	TIPO_MASCARA 		VARCHAR(30) 	NOT NULL, 
	ES_AUTOCALC 		VARCHAR(10) 	NOT NULL, 
	USO_MODVISUAL 		VARCHAR(10) 	NOT NULL, 
	SOLO_LECT 		VARCHAR(10) 	NOT NULL, 
	ES_REQUER 		VARCHAR(10) 	NOT NULL, 
	MOSTRAR_COMO 		VARCHAR(10) 	NOT NULL, 
	TIPO_CONSEC 		VARCHAR(30) 	NOT NULL, 
	FORMATOJUSTIF 		VARCHAR(10) 	NOT NULL, 
	VALORETIQUETA 		VARCHAR(50) 	NOT NULL, 
	MOSTRARENF1 		VARCHAR(10) 	NOT NULL,
	CARGA_DICCIO            INT             NOT NULL,
	MODULO 			VARCHAR(100) 	NULL
)
go

ALTER TABLE DD_CARGA_DICCIO
        ADD CONSTRAINT XPKDD_CARGA_DICCIO PRIMARY KEY (NOMBRE_TABLA,PROPIET_TABLA,NOMBRE_COLUM)
go        

CREATE TABLE DD_CARGA_ENCDET
(
		ENCABEZADO 	VARCHAR(30) NOT NULL,
		DETALLE 	VARCHAR(30) NOT NULL,
		TIPO 		VARCHAR(1)  NULL
)
go

ALTER TABLE DD_CARGA_ENCDET
          ADD CONSTRAINT PK_DD_CARGA_ENCDET
          	PRIMARY KEY ( ENCABEZADO, DETALLE )
go          	


CREATE TABLE DD_MODULO
(
	MODULO 		VARCHAR(10) 	NOT NULL,
	DESCRIPCION 	VARCHAR(254)	NULL,
	ESTANDAR 	VARCHAR(1) 	NOT NULL,
	AREA 		VARCHAR(4) 	NOT NULL
)
go

ALTER TABLE DD_MODULO
        ADD CONSTRAINT PKDD_MODULO PRIMARY KEY (MODULO)
go


CREATE TABLE DD_MODULO_TABLA
(
	MODULO 		VARCHAR(10) 	NOT NULL,
	TABLA 		VARCHAR(30) 	NOT NULL,
	PRINCIPAL 	VARCHAR(1) 	NOT NULL
)
go

ALTER TABLE DD_MODULO_TABLA
        ADD CONSTRAINT PKDD_MODULO_TABLA PRIMARY KEY (MODULO, TABLA)
go


CREATE TABLE DD_PROPIETARIO_TABLA
(
	PROPIETARIO 	VARCHAR(12) 	NOT NULL,
	TABLA 		VARCHAR(30) 	NOT NULL,
	PRINCIPAL 	VARCHAR(1) 	NOT NULL
)
go

ALTER TABLE DD_PROPIETARIO_TABLA
        ADD CONSTRAINT PKDD_PROPIETARIO_TABLA PRIMARY KEY (PROPIETARIO, TABLA)
go	


CREATE TABLE DD_TABLA
(
	TABLA 		VARCHAR(30) 	NOT NULL,
	DESCRIPCION 	VARCHAR(1024)	NULL,
	NOMBRE 		VARCHAR(60) 	NOT NULL,
	ALIAS 		VARCHAR(12)  	NOT NULL
)
go

ALTER TABLE DD_TABLA
        ADD CONSTRAINT PKDD_TABLA PRIMARY KEY (TABLA)
go
 
 
CREATE TABLE FAVORITOS (
 	ACCION 		INTEGER 	NOT NULL,
 	USUARIO 	VARCHAR(25)	NOT NULL,
 	POSICION 	INT	        NULL,
 	ACCION_MODULO	INT 	        NOT NULL,
 	PADRE 		INT DEFAULT (0)	NOT NULL
)
go 
 
 ALTER TABLE FAVORITOS  
 	ADD CONSTRAINT PK_FAVORITOS 
 		PRIMARY KEY NONCLUSTERED (ACCION, USUARIO) 
go 


CREATE TABLE GLOBALES (
         MODULO	   VARCHAR(20) 	NOT NULL,
         NOMBRE	   VARCHAR(30) 	NOT NULL,
         TIPO	   VARCHAR(1) 	NOT NULL,
         VALOR	   VARCHAR(250) NULL,
	 TEXTO     TEXT         NULL
)
go

ALTER TABLE GLOBALES
        ADD CONSTRAINT GLOBALESPK 
		PRIMARY KEY NONCLUSTERED (MODULO, NOMBRE)
go		


CREATE TABLE HISTORICO_CLAVE (
       LLAVE_HIST_CLAVE     INT NOT NULL,
       USUARIO              VARCHAR(25) NOT NULL,
       CLAVE                VARCHAR(256) NOT NULL
)
go


ALTER TABLE HISTORICO_CLAVE
    ADD CONSTRAINT  XPKHISTORICO_CLAVE PRIMARY KEY NONCLUSTERED 
    	(LLAVE_HIST_CLAVE)
go

CREATE TABLE HOOK_PERSONALIZ(
        HOOK                    VARCHAR(50) NOT NULL,
        NOMBRE                  VARCHAR(100) NOT NULL,               
        DESCRIPCION             VARCHAR(254) NULL        
 )
go
  
ALTER TABLE HOOK_PERSONALIZ
        ADD CONSTRAINT HOOKPK PRIMARY KEY NONCLUSTERED (HOOK)
go


CREATE TABLE HOOK_DETALLE(
        HOOK               VARCHAR(50) NOT NULL,        
        CONSECUTIVO	   INTEGER NOT NULL,    
        FECHA	           DATETIME NOT NULL,        
        DESCRIPCION        VARCHAR(254) NULL,
        ARCHIVO     	   IMAGE NOT NULL,
        CRC 		   VARCHAR(254) NULL,
	VIGENTE 	   VARCHAR(1) NULL
 )
go


 
ALTER TABLE HOOK_DETALLE
        ADD CONSTRAINT HOOK_DETALLEPK 
        	PRIMARY KEY NONCLUSTERED (HOOK, CONSECUTIVO)
go

CREATE TABLE LOCKS (
        LLAVE                VARCHAR(75) 	NOT NULL,
        USUARIO              VARCHAR(25) 	NOT NULL,
        CONNECTION_ID        VARCHAR(80) 	NOT NULL,
        FECHA                DATETIME 		NOT NULL
 )
go

ALTER TABLE LOCKS
        ADD CONSTRAINT LOCKSPK PRIMARY KEY NONCLUSTERED (LLAVE)
go        


CREATE TABLE MAPEO_CARGA
(
	MAPEO 		INT IDENTITY(1,1) NOT NULL,
	DESCRIPCION 	VARCHAR(40) NOT NULL,
	RUTA 		VARCHAR(249) NULL,
	TABLA 		VARCHAR(30) NOT NULL,
	SELECCION 	VARCHAR(1) NOT NULL DEFAULT ('N')
)
go

ALTER TABLE MAPEO_CARGA
          ADD CONSTRAINT PK_MAPEO_CARGA
          	PRIMARY KEY ( MAPEO )
go          	

CREATE TABLE MAPEO_DET_CARGA
(
		MAPEO 		INT NOT NULL,
		TABLA 		VARCHAR(30) NOT NULL,
		COL_CARGAD 	VARCHAR(40) NOT NULL,
		COL_ARCHIVO 	VARCHAR(40) NOT NULL
)
go

ALTER TABLE MAPEO_DET_CARGA
          ADD CONSTRAINT PK_DET_MAPEO_CARGA
          	PRIMARY KEY ( MAPEO, TABLA, COL_CARGAD, COL_ARCHIVO )
go 
 
 CREATE TABLE MEMBRESIA (
        GRUPO                VARCHAR(25) NOT NULL,
        USUARIO              VARCHAR(25) NOT NULL
 )
go
 
 
 ALTER TABLE MEMBRESIA
        ADD CONSTRAINT XPKMEMBRESIA PRIMARY KEY NONCLUSTERED (GRUPO, 
               USUARIO)
go
 
 

 
 CREATE TABLE MODULO_INSTALADO (
        CONJUNTO             VARCHAR(10) NOT NULL,
        ACCION               int NOT NULL
 )
go
 
 
 ALTER TABLE MODULO_INSTALADO
        ADD CONSTRAINT XPKMODULO_INSTALAD PRIMARY KEY (CONJUNTO, 
               ACCION)
go
 
 
 CREATE TABLE OPCION_CONFIG (
        ACCION               int 	  NOT NULL,
        OPCION_CONFIG        VARCHAR(20)  NOT NULL,
        MODULO               int 	  NOT NULL,
        MENU                 VARCHAR(1)   NOT NULL,
        DESCRIPCION          VARCHAR(100) NOT NULL,
        NOTAS                TEXT 	  NULL,
        EJECUTABLE           VARCHAR(64)  NOT NULL,
        PARAMETROS           VARCHAR(128) NULL,
        ACTIVA               VARCHAR(1)   NOT NULL,
        USUARIO_CREADOR      VARCHAR(25)  NOT NULL,
        FECHA_CREACION       DATETIME 	  NOT NULL,
        ULTIMO_USUARIO       VARCHAR(25)  NOT NULL,
        FECHA_ULT_ACCESO     DATETIME 	  NOT NULL,
        MANTENIMIENTO 	     INT 	  NULL,
        NOMBRE_IMAGEN 	     VARCHAR(250) NULL,
        IMAGEN 		     TEXT 	  NULL
 )
go
 
 
 ALTER TABLE OPCION_CONFIG
        ADD CONSTRAINT XPKOPCION_CONFIG PRIMARY KEY NONCLUSTERED (
               ACCION)
go
 
 
 CREATE TABLE PARENTESCO (
        ACCION               int NOT NULL,
        PADRE                int NOT NULL,
        NUMEROHERMANO        smallint NOT NULL
 )
go
 
 
 ALTER TABLE PARENTESCO
        ADD CONSTRAINT XPKPARENTESCO PRIMARY KEY NONCLUSTERED (ACCION, 
               PADRE)
go
 
 
 CREATE TABLE PRIVILEGIO_EX (
        USUARIO              VARCHAR(25) NOT NULL,
        CONJUNTO             VARCHAR(10) NOT NULL,
        ACCION               int 	 NOT NULL,
        ACTIVO		     VARCHAR(1)	 NOT NULL DEFAULT ('S')
 )
go
 
 
ALTER TABLE ERPADMIN.PRIVILEGIO_EX ADD  CONSTRAINT [XPKPRIVILEGIO] PRIMARY KEY NONCLUSTERED 
(
	[CONJUNTO] ASC,
	[USUARIO] ASC,
	[ACCION] ASC
)
go
 
 
 CREATE TABLE REPORTE_PERSONALIZ(
         ACCION               	VARCHAR(10) 	NOT NULL,        
         REPORTE	      	VARCHAR(100) 	NULL,
         DESCRIPCION          	VARCHAR(254) 	NULL,        
         MODULO		      	VARCHAR(50) 	NULL,
         TIPO                 	VARCHAR(10) 	NOT NULL,
         ESTANDAR 	      	VARCHAR(1) 	NULL,
         MODALIDAD            	VARCHAR(1) 	NULL DEFAULT 'G',
         FORMATO 	      	VARCHAR(250) 	NULL,
         PERSONALIZACION 	VARCHAR(max) 	NULL
  )
go
  
  
 ALTER TABLE REPORTE_PERSONALIZ
         ADD CONSTRAINT REPORTEPK 
         	PRIMARY KEY NONCLUSTERED (ACCION)
go
 
 
 CREATE TABLE REPORTE_DETALLE(
         ACCION               VARCHAR(10) 	NOT NULL,        
         REPORTE	      VARCHAR(100) 	NOT NULL,
         DESCRIPCION          VARCHAR(254) 	NULL,        
         NOTAS	              VARCHAR(254) 	NULL,        
         ACTIVO	              VARCHAR(1) 	NULL,
         SEGURIDAD  	      VARCHAR(1) 	NULL,
	 CRC 		      VARCHAR(254) 	NULL,
	 ARCHIVO 	      IMAGE default (' ') NOT NULL,
	 ARCHIVODTD 	      IMAGE NULL,
	 DTD 		      VARCHAR(100) 	NULL,
         FORMATO 	      VARCHAR(250) 	NULL,
         PERSONALIZACION      VARCHAR(max) 	NULL,
         FUENTEDATOS 	      VARCHAR(max) 	NULL
  )
go
  
  
 ALTER TABLE REPORTE_DETALLE
         ADD CONSTRAINT REPORTE_DETALLEPK 
        	PRIMARY KEY NONCLUSTERED (ACCION, REPORTE)
go 
  
CREATE TABLE REPORTE_PREF(
         ACCION              VARCHAR(10) NOT NULL,        
         CONJUNTO	     VARCHAR(10) NOT NULL,
         USUARIO	     VARCHAR(25) NOT NULL,
         REPORTE	     VARCHAR(100) NOT NULL         
)
go
  
ALTER TABLE REPORTE_PREF
         ADD CONSTRAINT REPORTE_PREFPK 
        	PRIMARY KEY NONCLUSTERED (ACCION, CONJUNTO, USUARIO)
go        	

CREATE TABLE REPORTE_USUARIO(
         ACCION              VARCHAR(10) 	NOT NULL,
         USUARIO	     VARCHAR(25) 	NOT NULL,
         REPORTE	     VARCHAR(100) 	NOT NULL 
)
go
  
ALTER TABLE REPORTE_USUARIO
         ADD CONSTRAINT REPORTE_USUARIOFPK 
        	PRIMARY KEY NONCLUSTERED (ACCION, USUARIO, REPORTE)
go        	


CREATE TABLE SENTENCIAS_SQL(
                IDSQL                   int      IDENTITY(1,1) 	NOT NULL,
                NOMBRE_SQL              VARCHAR(30)    		NOT NULL,
                DESCRIPCION_SQL         VARCHAR(254)  		NOT NULL,
                CONTENIDO_SQL           TEXT         		NOT NULL,
                APLICAR_RECURRENTE      VARCHAR(1)        	NOT NULL,
                APLICAR_NUEVASCIAS      VARCHAR(1)        	NOT NULL,
                TIPO_ESQUEMA            VARCHAR(10)      	NOT NULL,
                VERSION                 int               	NOT NULL,
                USUARIO_CREACION        VARCHAR(25)        	NOT NULL,
                FECHA_CREACION          DATETIME       		NOT NULL,
                USUARIO_MODIFICACION  	VARCHAR(25)         	NOT NULL,
                FECHA_MODIFICACION      DATETIME          	NOT NULL
)
go

ALTER TABLE SENTENCIAS_SQL
         ADD CONSTRAINT XPKSENTENCIAS_SQL PRIMARY KEY (IDSQL)
go


CREATE TABLE USUARIO (
        USUARIO              VARCHAR(25) 	NOT NULL,
        NOMBRE               VARCHAR(100) 	NOT NULL,
        TIPO                 VARCHAR(1) 	NOT NULL,
        ACTIVO               VARCHAR(1) 	NOT NULL,
        REQ_CAMBIO_CLAVE     VARCHAR(1) 	NOT NULL,
        FRECUENCIA_CLAVE     smallint 		NOT NULL,
        FECHA_ULT_CLAVE      DATETIME 		NOT NULL,
        MAX_INTENTOS_CONEX   smallint 		NOT NULL,
        CLAVE 		     	VARCHAR(68) 	NULL,
        CORREO_ELECTRONICO   VARCHAR(249)	NULL,
        TIPO_ACCESO 	     VARCHAR(1) 	NOT NULL DEFAULT('T'),
        CELULAR 	     	VARCHAR(25)        NULL,
		TIPO_PERSONALIZADO 	VARCHAR(256) NULL
 )
go
 
 
 ALTER TABLE USUARIO
        ADD CONSTRAINT XPKUSUARIO PRIMARY KEY NONCLUSTERED (USUARIO)
go

CREATE TABLE ERPADMIN.AUDITORIA_USUARIOS 
(
	CODIGO				INT IDENTITY(1,1)	NOT NULL,
	USUARIO				VARCHAR(100)		NOT NULL,
	ACCION				VARCHAR(50)			NOT NULL,
	FECHA				DATETIME			NULL,
	ESTADO				VARCHAR(50)			DEFAULT 'NUEVO',
	NOMBRE_TABLA		VARCHAR(100)		NULL
)
go


ALTER TABLE ERPADMIN.AUDITORIA_USUARIOS 
        ADD CONSTRAINT XPKAUDITORIAUSUARIOS
            PRIMARY KEY NONCLUSTERED (CODIGO)
go

			
CREATE TABLE ERPADMIN.DOC_ADJUNTO
(
	TABLA 		VARCHAR(32) 			NOT NULL,
	ROW_ID 		UNIQUEIDENTIFIER 		NOT NULL,
	CONSECUTIVO 	INTEGER 	IDENTITY(1,1) 	NOT NULL,
	NOMBRE 		VARCHAR(40) 			NOT NULL,
	DESCRIPCION 	VARCHAR(254) 			NOT NULL,
	CONTENIDO 	IMAGE 				NOT NULL
)
go

ALTER TABLE ERPADMIN.DOC_ADJUNTO
	ADD CONSTRAINT DOC_ADJUNTO_PK  
		PRIMARY KEY (TABLA,ROW_ID,CONSECUTIVO,NOMBRE)
go


CREATE TABLE ERPADMIN.FIRMA(
	CONJUNTO 	VARCHAR(10) 		NOT NULL,
	TABLA 		VARCHAR(32) 		NOT NULL,
	ID_ROWPOINTER 	uniqueidentifier 	NOT NULL,
	FIRMA 		VARCHAR(32) 		NOT NULL
)
go


ALTER TABLE ERPADMIN.FIRMA
	ADD CONSTRAINT XPKFIRMA PRIMARY KEY (CONJUNTO, TABLA, ID_ROWPOINTER)

go	


CREATE TABLE ERPADMIN.INFO_NOTICIAS 
(
          IDENTIFICADOR			int NOT NULL,
          TIPO					int NULL,
          TITULO				varchar(128) NULL,
          DESCRIPCION			varchar(max) NULL,
          PRIORIDAD				int NULL,
          PERIODICIDAD			int NULL,
          FECHA_INICIO			datetime NULL,
          FECHA_FIN				datetime NULL,
		  ULTIMA_NOTIFICACION	datetime NULL,
          MODULOS				varchar(256) NULL,
		  VISTO_POR				varchar(max) NULL,
		  PERIODO_VISTO			int DEFAULT 0,
		  VINCULO 				varchar(256) NULL,
		  ESTADO 				varchar(20) NULL
)
go


ALTER TABLE ERPADMIN.INFO_NOTICIAS ADD
	CONSTRAINT XPKINFO_NOTICIAS 
		PRIMARY KEY NONCLUSTERED (IDENTIFICADOR)
go

CREATE TABLE ERPADMIN.LOCKS (
        LLAVE                VARCHAR(100) 	NOT NULL,
        USUARIO              VARCHAR(10) 	NOT NULL,
        CONNECTION_ID        VARCHAR(80) 	NOT NULL,
        FECHA                DATETIME 		NOT NULL
)
go

ALTER TABLE ERPADMIN.LOCKS
       ADD  CONSTRAINT LOCKSPK PRIMARY KEY (LLAVE)
go

CREATE TABLE ERPADMIN.PREFERENCIA (
        USUARIO              VARCHAR(25) 	NOT NULL,
        ORIGEN               VARCHAR(4) 	NOT NULL,
        OPCION               VARCHAR(50) 	NOT NULL,
        PREFERENCIA1         VARCHAR(250) 	NULL,
        PREFERENCIA2         VARCHAR(250) 	NULL,
        PREFERENCIA3         VARCHAR(250) 	NULL,
        PREFERENCIA4         TEXT 		NULL
)
go

ALTER TABLE ERPADMIN.PREFERENCIA
        ADD CONSTRAINT PREFERENCIAPK 
        	PRIMARY KEY NONCLUSTERED (USUARIO, ORIGEN, OPCION)
go        	
 
 
 
CREATE TABLE ERPADMIN.LICENCIA
(
	XML 	VARCHAR(max) 	NOT NULL
)
go

CREATE TABLE erpadmin.MODULO_ADICIONAL
(
 INICIALES   	VARCHAR(50)  NOT NULL,
 DESCRIPCION   	VARCHAR(250) NOT NULL,
 FIRMA    		VARCHAR(MAX) DEFAULT 'NO FIRMADO',
 FECHA_FIRMA   	DATETIME  	 DEFAULT GETDATE()
)

go

ALTER TABLE erpadmin.MODULO_ADICIONAL 
        ADD CONSTRAINT XPKMODULOADICIONAL PRIMARY KEY NONCLUSTERED (INICIALES)

go

CREATE TABLE ERPADMIN.CONTROL
(
	XML 	VARCHAR(max) 		NOT NULL
)
go

CREATE TABLE ERPADMIN.REPORTE_SUBREPORTE(
	ACCION_PADRE VARCHAR(10) 	NOT NULL,
	NOMBRE_CONTROL VARCHAR(100) 	NOT NULL,
	ARCHIVO VARCHAR(max) 		NULL,
	REPORTE_PADRE VARCHAR(100) 	NOT NULL
)
go


ALTER TABLE ERPADMIN.REPORTE_SUBREPORTE ADD 
	CONSTRAINT PK_SUBREPORTE PRIMARY KEY (ACCION_PADRE,NOMBRE_CONTROL,REPORTE_PADRE)
go	

CREATE TABLE ERPADMIN.SITE
(
	XML 	VARCHAR(max) 		NOT NULL
)
go

CREATE TABLE erpadmin.TIMEZONE
(
	NAME varchar(1024),
	DIFFMINUTES int,
	ISDEFAULT varchar(1) NOT NULL DEFAULT 'N'  
)
go


CREATE TABLE erpadmin.SCH_CONFIG_WEB_API(
	COMPANIA 			varchar(100) NOT NULL,
	TOKEN 				varchar(100) NOT NULL,
	DIRECCION_WEB 		varchar(150) NOT NULL,
	USUARIO 			varchar(50) NOT NULL,
	CLAVE 				varchar(100) NOT NULL,
	ACCIONDEPARTAMENTO 	varchar(4) NOT NULL,
	ACCIONPUESTO 		varchar(4) NOT NULL,
	ACCIONBAJA 			varchar(4) NOT NULL,
	ACCIONSALARIO 		varchar(4) NOT NULL,
	ACCIONVACASGOCE 	varchar(4) NOT NULL,
	ACCIONVACASACUM 	varchar(4) NOT NULL,
	ACCIONVACASGOCEADIC varchar(4) NULL,
	ACCIONVACASACUMADIC varchar(4) NULL,
	CONSECEMPLEADO 		varchar(10) NOT NULL,
	PAGINA_SCH 			varchar(400) NOT NULL
)
go
	
CREATE TABLE erpadmin.SCH_BITACORA(
	COMPANIA 			varchar(100) NOT NULL,
	PROCESO 			varchar(150) NOT NULL,
	ERROR 				varchar(max) NULL,
	FECHA 				datetime NOT NULL DEFAULT (getdate())
)
go

CREATE TABLE erpadmin.SCH_TRANSICION(
	ENTIDAD 			varchar(25) NOT NULL,
	COMPANIA 			varchar(100) NOT NULL,
	ACCION 				varchar(50) NOT NULL,
	ID 					varchar(25) NOT NULL,
	JSON 				varchar(max) NULL,
	FECHA 				datetime NOT NULL DEFAULT (getdate()),
	ESTADO 				varchar(3) NULL,
	DESCRIPCIONERROR 	varchar(max) NULL
)
go

CREATE TABLE erpadmin.ERP_TRANSICION(
	ENTIDAD 			varchar(25) NOT NULL,
	COMPANIA 			varchar(100) NOT NULL,
	ACCION 				varchar(50) NOT NULL,
	ID 					varchar(25) NOT NULL,
	ID_FINAL 			varchar(25),
	JSON 				varchar(max) NULL,
	FECHA 				datetime NOT NULL DEFAULT (getdate()),
	ESTADO 				varchar(3) NULL
)
go

CREATE TABLE erpadmin.SCH_ARBOL_ORG(
	ID 					integer NULL,
	IDPADRE 			integer NULL,
	DESCRIPCION 		varchar(250) NULL,
	TIPO 				varchar(10) NULL,
	IDEXTERNO 			varchar(50) NULL,
	IDPADREEXTERNO 		varchar(50) NULL,
	RAIZ 				varchar(1) NULL DEFAULT 'N',
)
go

CREATE TABLE erpadmin.SCH_PUESTO(
	ID 					integer NULL,
	DESCRIPCION 		varchar(250) NULL,
	IDARBOL 			integer NULL,
	IDARBOLEXTERNO 		varchar(50) NULL,
	IDEXTERNO 			varchar(50) NULL
)
go

CREATE TABLE erpadmin.SCH_USUARIOEMPLEADO(
	COMPANIA 			varchar(20) NOT NULL,
	USUARIO 			varchar(20) NOT NULL,
	EMPLEADO 			varchar(20) NOT NULL
)
go


/* Se incluye la funsión SF_GETDATE para Zonas Horarioas */

CREATE FUNCTION ERPADMIN.SF_GETDATE
(
	/* Add the parameters for the function here*/
	
)
RETURNS DATETIME
AS
BEGIN
	DECLARE @start DATETIME
	DECLARE @diff INT
	DECLARE @end DATETIME
	SET @diff = 0
	DECLARE db_cursor CURSOR FOR  	
	SELECT DIFFMINUTES 
	FROM erpadmin.TIMEZONE 
	WHERE  ISDEFAULT = 'S'
	OPEN db_cursor   
	FETCH NEXT FROM db_cursor INTO @diff
	CLOSE db_cursor
	IF @diff != 0
	BEGIN
	SET @start = GETUTCDATE()
	SET @end = DATEADD(MINUTE,@diff, @start)
	RETURN @end
	END
	ELSE
	SET @end = GETDATE()
	RETURN @end
END
go


